### ISSUE TITLE
[Concurso interno] Criação do logo, cores e fonte do programa

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#1]
Precisamos de um logo para o projeto! Nada melhor que aflorar a criatividade de cada integrante da equipe com um concurso interno de escolha. Para participar, basta comentar essa issue com o seguinte:

* 01 (imagem) Logo marca 
* 03 cores principais (em uma imagem) que serão usadas no projeto (identidade visual; excluindo branco e preto)
* 01 Exemplo de texto com a fonte a ser usada
* Nome dos autores (máximo 2)
* Pequena descrição da história do logo e seus simbolismos (max 140 chars)

Prazo para entrega: 19/06 (sexta-feira) até 14:00
Votação: 19/06 (sexta-feira) das 14:00 as 15:00 (link a ser informado)

**Comment by isabelirk** [comment]
Dúvidas:
-> A logo precisa estar na sua versão final, pronta para ser usada?
-> Não entendi o item do "nome dos autores".

**Comment by isabelirk** [comment]
![Screenshot_20200618-212606](https://user-images.githubusercontent.com/31291959/85084404-1189f800-b1ab-11ea-9813-2faa1b0112c1.jpg)

OBS: Na imagem são 6 logotipos diferentes!

-> As cores usadas foram: azul, verde e laranja.

-> A fonte do texto poderia ser uma bem limpa visualmente, pois remete a algo prático, simples, limpo e fácil. As letras seriam em caixa alta.
Exemplos de fontes que gosto a partir de fontes padrão em qualquer editor de texto como Word: 
 - Times New Roman
 - Georgia
 - Munito
 - Roboto

-> Os autores (no que eu entendi, quem criou): Isabeli Reik

-> Os símbolos usados: os três risquinhos, que remetem a sensação de ter uma ideia; as setas, como sinal de avanço e empoderamento; e o chapéu de formando, que aponta para a educação.

**Comment by MaNegrao** [comment]
![PRACTICE](https://user-images.githubusercontent.com/31110971/85090852-7dc12780-b1bc-11ea-99d3-ecdbe147e069.png)
![PRACTICE-2](https://user-images.githubusercontent.com/31110971/85091665-5a977780-b1be-11ea-8a3d-36a65b1a02bf.png)
![Cores](https://user-images.githubusercontent.com/31110971/85090859-81ed4500-b1bc-11ea-8e5b-e68599fbd065.png)
![Fontes](https://user-images.githubusercontent.com/31110971/85090862-831e7200-b1bc-11ea-86c3-3deffbdaa88f.png)

- Autores: Matheus D. Negrão e Zaira I. Teston
- Descrição: Representa a universidade, o capelo é o telhado e o "PRACTICE" é a escadaria pois fomenta as conexões necessárias (por isso os conectores).

**Comment by estelavilasboas** [comment]
Imagens e descrições:


![image](https://user-images.githubusercontent.com/30927758/85154468-dd0b5000-b22d-11ea-9c06-8dafb7051b04.png)
Como nome do projeto já uma brincadeira com a palavra “prática”, é possível trazer o mesmo conceito para logo. Prática nada mais é do que repetir uma ação diversas.

![image](https://user-images.githubusercontent.com/30927758/85154636-15129300-b22e-11ea-96eb-66dfed1689b2.png)
Quando o projeto foi apresentado, palavras como “inovação” e “criatividade” foram trazidas. Ambas são conceitos abstratos, e tendemos a relacionar conceitos abstratos com concretos. Uma lâmpada remete a uma ideia. Nessa lâmpada podem ser inseridas cores em contraste com as demais e que lembrem a aquarela. Aquarelas e cores são frequentemente utilizadas para representar criatividade.
Uma engranagem pode remeter a construção, ao o que está sendo construído a partir de uma ideia, o que é contruído a partir da prática.


Fonte:
![image](https://user-images.githubusercontent.com/30927758/85154810-53a84d80-b22e-11ea-9d58-14546320d29f.png)
Para escrita foi utilizada uma mistura entre as letras maiúsculas e minúsculas da fonte “Caviar Dreams” visando mais dinâmica.
![image](https://user-images.githubusercontent.com/30927758/85154926-7aff1a80-b22e-11ea-9e77-87339f818563.png)
Nas criações apresentadas acima, não foram utilizadas todas as cores dessa paleta. A ideia é uma paleta que inserisse contraste utilizando azul e laranja. Pode-se fazer a analogia de que entre um oceano de pensamentos há uma luz, e esta é representada pelos tons mais quentes.


Autor: Estela Vilas Boas

**Comment by estelavilasboas** [comment]
Seguindo a paleta, fonte e ideias dos logotipos (criados pela Estela) expostos anteriormente, o logotipo a seguir contém um pássaro de origami e um galho de grafos. Um pássaro pode ser visto como um símbolo de liberdade, no nosso caso de pensamento para alcançar a inovação, e o origami é uma arte, sendo assim a criatividade. O galho de grafos é o mais próximo da tecnologia.

![image](https://user-images.githubusercontent.com/30927758/85158875-25793c80-b233-11ea-96a1-27b52e1e268d.png)
![image](https://user-images.githubusercontent.com/30927758/85158919-3164fe80-b233-11ea-9ef9-189a7fd05f30.png)

**Comment by Dovyski** [comment]
Logo:
<img width="1899" alt="logo-practice-full" src="https://user-images.githubusercontent.com/512405/85170976-8c532180-b244-11ea-94c4-773479b419e1.png">

Proposta:
![PRACTICE - logo](https://user-images.githubusercontent.com/512405/85170735-33838900-b244-11ea-886b-4e1ac1ea80cc.png)

Descrição:
O logo tem os famosos três horizontes que, inicialmente, são algo longínquo (desconexo) e que pretendemos, com trabalho, trazer à vida (conectá-los).

Autor: Fernando Bevilacqua

**Comment by franca20** [comment]
Logo produzido por Vinícius França e Lucas Ferreira 

Ideia do logo

**Comment by Dovyski** [comment]
A votação para o logo do projeto ficará aberta até amanhã, para todos terem tempo de olhar os logos ou fazer mais sugestões.

Para votar, basta clicar na "carinha feliz" (canto superior esquerdo do comentário com o logo que você gostou) e escolher uma reação: 👍❤️😄.

Cada pessoa pode votar em *2* logos diferentes. No final, o logo que tiver mais reações ganha.
