### ISSUE TITLE
[Equipe de trabalho] Escolha das caixinhas

### ISSUE THREAD

**Issue by isabelirk** [practice-uffs/programa#10]
Cada membro poderá manifestar em qual equipe de trabalho, conforme a área desejada (caixinhas), gostaria de trabalhar.

**Comment by isabelirk** [comment]
Minhas opções:

1º Texto e Imagem (@ con-material)
2º Web e digital (@ con-digital)
3º Auxilio operacional (@ ger-auxilio)

**Comment by CleissonVieira** [comment]
Minhas opções:

1º Internet e websites (@ dev-web)
2º Tecnologias móveis (@ dev-mobile)
3º Gerência de produção (@ ger)

**Comment by andrewmsilva** [comment]
Minhas opções:

1. dev-ops
2. dev-mobile
3. dev-web

**Comment by MaNegrao** [comment]
Minhas opções:

1º Vídeo e audio - @con-midia
2º Auxilio operacional - @ger-auxilio
3º Web e digital - @con-digital

**Comment by alessandrapedrotti** [comment]
Minhas opções:

1º Texto e imagem - @ con-material
2º Vídeo e áudio - @ con-midia
3º Auxílio operacional - @ ger-auxilio

**Comment by vini2reis** [comment]
Minhas opções:

1º Vídeo e audio - @con-midia
2º Auxilio operacional - @ger-auxilio
3º Web e digital - @con-digital

**Comment by oigor** [comment]
1° Vídeo e áudio - @con-midia 
2° Imagem e Texto - @con-material 
3°  Auxílio operacional @ger-axulio

**Comment by franca20** [comment]
Minhas opções:

1° Auxílio operacional @ ger-axulio
2° Imagem e Texto - @ con-material
3° Vídeo e áudio - @ con-midia

**Comment by mariagelain** [comment]
Minhas opções:

1° texto e imagem - @ con-material 
2° vídeo é áudio - @ con-mídia 
3° web e digital - @ con-digital

**Comment by lucasgalize** [comment]
1º Texto e Imagem (@ con-material)
2º Vídeo e áudio - @ con-midia)
3º Web e digital (@ con-digital)

**Comment by estelavilasboas** [comment]
Minhas opções:

1º Internet e websites (@ dev-web)
2º Imagem e Texto (@ con-material)
3º Infra-estrutura digital (@ dev-ops)

**Comment by Dovyski** [comment]
Os grupos de trabalho foram definidos:

@practice-uffs/con-material:
* Isabeli Reik - @isabelirk
* Alessandra Pedrotti  - @alessandrapedrotti
* Maria Gelain	- @mariagelain
* Lucas Ferreira - @lucasgalize

@practice-uffs/con-midia:
* Matheus Negrão - @MaNegrao
* Vinícius do Reis - @vini2reis
* Igor Matheus - @oigor

@practice-uffs/dev-ops:
* Andrew M. Silva - @andrewmsilva

@practice-uffs/dev-web:
* Cleisson Vieira - @CleissonVieira
* Estela Vilas Boas - @estelavilasboas

@practice-uffs/ger-auxilio:
* Vinícis França - @franca20

Lembro que todos podem, eventualmente, ajudar todos conforme a demanda. Entretanto, as demandas que forem do seu grupo devem ser atentidas com a máxima prioridade em detrimento das demais.
