### ISSUE TITLE
Cartilha: Dicas de produção de videoaula

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#100]
Texto de dicas para a elaboração de videoaulas, baseado no modelo de texto da issue #61.

https://drive.google.com/drive/u/0/folders/1HJsw5yl6LkNepll07fZJ2ASTXwdzOA5U

**Comment by alessandrapedrotti** [comment]
Primeira versão do texto pronta.
Aguardo comentários da @elisribas com sugestões de alterações e adições.

**Comment by alessandrapedrotti** [comment]
Terminei de escrever o texto com o auxílio da Isabeli. Agora preciso que a @mariagelain faça a revisão da diagramação e a @estelavilasboas coloque umas ilustrações, como na cartilha #61.

**Comment by mariagelain** [comment]
Revisão feita. O produto já está pronto para ser aprovado.

**Comment by alessandrapedrotti** [comment]
Aguardo a leitura do @Dovyski. Caso não surja nehuma sugestão de alteração, o material está pronto.

**Comment by Dovyski** [comment]
Ficou maravilho, meninas! Gostei de absolutamente tudo (diagramação, conteúdo e cadência). ❤️ 🥳  Pode gerar a versão final em PDF, colocar na pasta `saída` e encaminhar para a web colocar no site.
