### ISSUE TITLE
Criação de Modelo de Roteiro para Lives

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#103]
A ideia é criar um modelo roteiro com blocos e informações para serem utilizadas nas transmissões ao vivo. Peguei como base o roteiro que utilizamos no FronteiraCast.

[Pasta Drive](https://drive.google.com/drive/u/0/folders/13cG5Or3l0nSOUpZ7cfvO95KDpQn_yByP)

**Comment by MaNegrao** [comment]
A primeira versão do modelo está pronto na pasta, creio que não há muita coisa a acrescentar, se alguém tiver alguma sugestão, pode adicionar.

**Comment by VIF-Franca** [comment]
@MaNegrao  realizei a inclusão que julguei necessária.

**Comment by MaNegrao** [comment]
@VIF-Franca Não sei se colocar dados como a senha do youtube, publicamente em um roteiro, é indicado... Talvez seja melhor a gente obter esse dado em uma conversa particular com o organizador do evento. O que acha?

**Comment by VIF-Franca** [comment]
Perfeito, creio que podemos deixar os dados o mais seguro possível.

**Comment by MaNegrao** [comment]
@lcaimi Creio que o modelo base é esse, podemos colocar ele em algum lugar mais visível e acessível e fechar a issue, o que acha?

**Comment by lcaimi** [comment]
Sim, podemos colocar para baixar diretamente do site em diferentes formatos  (.doc, .odt e .pdf) para os clientes baixarem.
