### ISSUE TITLE
Divulgar edital de novos bolsistas do PRACTICE nas redes sociais - Laranjeiras do Sul 

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#104]
Precisamos divulgar o edital para bolsista do PRACTICE. Para isso, fazer o seguinte:

 
- [x] Criar arte com as informações sobre o edital para bolsistas do programa (@practice-uffs/con);

- [x]  @practice-uffs/ger-auxilio após a criação deve realizar a postagens em todas as redes sociais;

- [x]  Criar uma notícia do site do PRACTICE com uma das artes e com as informações acima (@practice-uffs/dev) .

Link para o Edital:  https://www.uffs.edu.br/atos-normativos/edital/gr/2020-0483?fbclid=IwAR3D6xwnACJlBUhbuNN-iqPKoBV_HXgriN7yjXY8tLV2EllOJEXiOPFsbAY

**Comment by VIF-Franca** [comment]
Exemplo base localizado na pasta do drive, issue #88 

[PASTA DRIVE](https://drive.google.com/drive/folders/1GK9UmEH4vO1R0Q0tpsxvqSuCNsR1Q1vI?usp=sharing)

**Comment by estelavilasboas** [comment]
@practice-uffs/dev-web , imagem para o site já foi finalizada

**Comment by estelavilasboas** [comment]
Imagens finalizadas, seguindo o mesmo padrão de ordenação numerada no nome de arquivo da Issue 88.
O tamanho das imagens está conforme o tamanho que as redes sociais exigem para publicação de link em sua descrição.

**Comment by VIF-Franca** [comment]
Show, arte postada. 

Solicitei para a ASCOM divulgar no campus via e-mail, aguardo link com a notícia do site para disponibilizar para a ASCOM.
