### ISSUE TITLE
Criar material com instruções simples e diretas para as Interpretes de Libras

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/programa#105]
Material de uma página com instruções para Lives:

- Sala que cada uma deve entrar;
- Contraste de roupa e fundo
- Iluminação do local
- Período de alternância pré-determinado e controlado pela operação e não pelas intérpretes.

[Pasta Drive](https://drive.google.com/drive/folders/1L_XTY6Tnd1aTtieieMpzDcJ6_No24JSd?usp=sharing).

@phdmauricio 
@VIF-Franca

**Comment by phdmauricio** [comment]
Além do que o @lcaimi descreveu, é preciso orientar sobre os equipamentos e o posiocionamento adequados dos mesmos, bem como sobre o cabeamento de rede.

**Comment by VIF-Franca** [comment]
Litas de tarefas vinculadas a elaboração da cartilha:

- [ ] elaborar esqueleto sobre os itens que deverá conter nessa cartilha;

- [ ] elaboração dos itens descritos nas etapas anteriores; 

- [ ] solicitar sugestões de itens;

- [ ] enviar para a revisão.

**Comment by MaNegrao** [comment]
Creio que não precisamos necessariamente fazer uma cartilha para isso. Talvez se criarmos um panfleto ou coisa do genero, bem simples com poucas paginas e produzirmos um video, ficaria mais intuitivo e acessivel para as interpretes.

**Comment by VIF-Franca** [comment]
Olá pessoal, finalizei a primeira versão da cartilha, busquei deixar o mais curta possível @MaNegrao veja se quer adicionar algo.

**Comment by MaNegrao** [comment]
> Olá pessoal, finalizei a primeira versão da cartilha, busquei deixar o mais curta possível @MaNegrao veja se quer adicionar algo.

Opa, pode adicionar o link da pasta do drive na descrição da issue?

**Comment by VIF-Franca** [comment]
@estelavilasboas  e @mariagelain acho que ficaria bem legal colocar umas imagens dei umas ideias, porém vocês são melhores nisso podem dar uns ajustes de diagramação também.

**Comment by VIF-Franca** [comment]
> > Olá pessoal, finalizei a primeira versão da cartilha, busquei deixar o mais curta possível @MaNegrao veja se quer adicionar algo.
> 
> Opa, pode adicionar o link da pasta do drive na descrição da issue?

Opa está aqui na pasta [programa#105](https://drive.google.com/drive/folders/1L_XTY6Tnd1aTtieieMpzDcJ6_No24JSd?usp=sharing).

**Comment by MaNegrao** [comment]
Eu terminei a leitura, fiz algumas alterações quanto a troca e o uso de um fundo verde e tenho algumas sugestões.

Quanto a conexão com a internet creio que podemos fazer mais um tópico falando sobre a câmera. É preferível que as interpretes utilizem o celular, por conta da câmera do celular ter uma qualidade superior a de notebooks. Então acho que podemos fazer essa menção e indicarmos o download do aplicativo do webex no celular para interpretação e acesso no notebook para escutar.

**Comment by MaNegrao** [comment]
@practice-uffs/con-conteudo O material está pronto para revisão gráfica e textual

**Comment by alessandrapedrotti** [comment]
Fiz a primeira leitura da revisão e deixei alguns comentários para o redator @VIF-Franca arrumar.
Num geral, acho que o texto ficou vago demais, principalmente no que se refere as informações mais técnicas (como no 5, por exemplo).
Sugeri adicionar uma página de introdução, para contextualizar o público-alvo da necessidade da leitura do material.

**Comment by VIF-Franca** [comment]
@alessandrapedrotti, posso adicionar sim, porém, acredito que foge um pouco do modelo que o @lcaimi e @Dovyski sugeriram, que fosse o mais concisa possível e o material final de até uma página.

**Comment by VIF-Franca** [comment]
@alessandrapedrotti , quanto aos demais comentários, já estou lendo e alterando.

**Comment by VIF-Franca** [comment]
@alessandrapedrotti , realizei as alterações propostas no material, assim como fiz uma página introdutória sobre a importância do material para o programa. Está pronto para a segunda revisão. 

@MaNegrao , te marquei num dos comentários para que você coloque a referência na imagem da intérprete.

**Comment by alessandrapedrotti** [comment]
> @alessandrapedrotti, posso adicionar sim, porém, acredito que foge um pouco do modelo que o @lcaimi e @Dovyski sugeriram, que fosse o mais concisa possível e o material final de até uma página.

Entendo a orientação de que o material tivesse que ser o mais conciso possível, entretanto, acredito que valha mais ter um material completo que sane as dúvidas dos intérpretes do que algo conciso demais que ainda os deixe com questionamentos.

**Comment by alessandrapedrotti** [comment]
Fiz a segunda leitura de revisão.
Alterei o texto de introdução;
Alterei alguns aspectos de ordem gramatical e de pontuação;
deixei um comentário para o redator.

Além disso, informo que não há necessidade de toda vez que o texto faz referência aos intérpretes, colocar "os(as) intérpretes" ou similar. Basta deixar "os intérpretes" ou "o intérprete",  já que o substantivo "intérprete" é comum de dois gêneros.

**Comment by MaNegrao** [comment]
Assim que o material estiver pronto iremos fechar a issue e abrir uma para adaptar para vídeo

**Comment by MaNegrao** [comment]
Eu fiz uma alteração, também fui redator da cartilha hehe. 
Eu só tenho uma duvida, existe revisão técnica nos materiais de texto?

**Comment by MaNegrao** [comment]
Eu li a definição da label de técnico e pela definição está ok também. 

Agora creio que o @practice-uffs/dev-web incluirá no site a cartilha?

**Comment by alessandrapedrotti** [comment]
> Eu fiz uma alteração, também fui redator da cartilha hehe.
> Eu só tenho uma duvida, existe revisão técnica nos materiais de texto?

Depende do conteúdo. Se for um material mais simples, não tem necessidade, agora se for um texto mais complexo ou com informações muito específicas, é interessante fazer a revisão técnica.

**Comment by CleissonVieira** [comment]
@MaNegrao @alessandrapedrotti Verifiquei o Dev marcado na Issue, então adicionei a cartilha no site. 
Se este era o passo final a issue pode ser finalizada.

**Comment by MaNegrao** [comment]
Material finalizado e postsdo
