### ISSUE TITLE
Produção de flyer para divulgação dos serviços do Practice

### ISSUE THREAD

**Issue by elisribas** [practice-uffs/programa#106]
@estelavilasboas 
Precisamos, com urgência, criar um flyer, com uma página, que descreva todos os serviços ofertados pelo Practice.

Para descrever os serviços, acessar o site do Practice, aba serviço e fazer uma breve descrição de cada item descrito.
https://practice.uffs.cc/ 

Produzir algo em linguagem mais dialogada possível, com perguntas do tipo: Você gostaria de gravar um vídeo? O Pratice pode te ajudar, temos os estúdos... (@Dovyski confirmar quais campi estão confirmados os estúdios para detalhamento, caso venhamos a descrever todos os campi/ caso não seja, favor alterar a descrição da issue). 

O que você deseja é que alguém te ajude a editar seu vídeo? Podemos ajudá-lo, pois xxx.... aí descreva o serviço de edição. Assim será para todos os demais serviços ofertados, para o caso de áudio, não há necessidade de listar todos aqueles descritos no site. Para a produção de conteúdo da equipe específica, poderá que o Practice contribui na criação ou formatação de materiais visuais, como cartilhas, manuais, flyers. A pergunta pode ser: Quer tornar seu material textual mais atrativo? Podemos auxiliá-lo na produção disso, disso e disso.

Faz uma proposta com base no modelo de panfleto disponível em: 
https://drive.google.com/drive/u/0/folders/1OQQlDWQL1u1ix5DLQr20pQ7OjSbGDMGU

Reduz a parte azul, já que a ideia é concentrar tudo em uma página e apresentar bastante informação.

Vamos dialogando.

@lcaimi @Dovyski @phdmauricio por favor, ajudem a complementar a demanda, caso necessário. ❤️

**Comment by lcaimi** [comment]
Os estúdios em operação em Chapecó e Laranjeiras do Sul.
Colocar a observação abaixo sobre o serviço de gravação em estúdio.
"O agendamento e gravação em estúdio depende do NSO (Nível de Segurança Operacional) definido para cada Campus"

**Comment by elisribas** [comment]
Tarefa em elaboração em:
https://drive.google.com/drive/u/0/folders/13RhKXcXVwd5A_e378PCqMZ7Ww1hAtb_i 
@alessandrapedrotti e @estelavilasboas vamos trabalhar juntas nessa tarefa.

**Comment by elisribas** [comment]
> Os estúdios em operação em Chapecó e Laranjeiras do Sul.
> Colocar a observação abaixo sobre o serviço de gravação em estúdio.
> "O agendamento e gravação em estúdio depende do NSO (Nível de Segurança Operacional) definido para cada Campus"

@lcaimi isso se aplica para gravação de podcast tbm ou apenas Chapecó possui estúdio de áudio?

**Comment by lcaimi** [comment]
Os podcast podem ser gravados com cada participante da sua casa, sem o deslocamento até o estúdio

**Comment by phdmauricio** [comment]
Por hora temos estúdios apenas em Chapecó e Laranjeiras do Sul.

**Comment by phdmauricio** [comment]
Colocar a informação: Se você coordena algum Programa Institucional, entre em contato para conhecer as possibilidades de desenvolvimento de software e aplicativos.

**Comment by phdmauricio** [comment]
Seria legal inserir a sugestão para gravação de epsódios de podcasts.

**Comment by elisribas** [comment]
@estelavilasboas insere o template de panfleto em uma apresentação do Google Apresentação.
Assim, a gerência terá acesso ao conteúdo e poderá editá-lo. 
O texto requer pequenos ajustes e revisão textual.
Texto: https://docs.google.com/document/d/1edTcC-tcDoM088JAzo9bn_MbfcDomWOX6LNwWTzHjnw/edit
Templates: https://drive.google.com/drive/u/0/folders/1OQQlDWQL1u1ix5DLQr20pQ7OjSbGDMGU

**Comment by alessandrapedrotti** [comment]
Revisão textual concluída, com exceção da parte "4. Aplicativos" que a @elisribas pediu no documento que o @Dovyski escrevesse.

**Comment by estelavilasboas** [comment]
Gente, eu estou produzindo o flyer que requisitaram, mas tenho alguns questionamentos a fazer

Geralmente um flyer é bem simples, sucinto e direto, contando com pelo menos uma frase que chame a atenção e algumas outras informações em baixo. Aliás, ele geralmente impresso em folhas A5 e A6, então se colocar muito conteúdo, pode ficar muito poluído e difícil de ler.

Materiais que contêm mais informações podem ser postos em folders, os quais têm de 2 a 3 folhas dobráveis. No entanto, creio que este não seja o objetivo, já que será apresentado para comunidade acadêmica.

O que eu fiz até o momento é basicamente um folder de uma página, já que apresenta muitas informações em um espaço bem pequeno. Tentei encaixar a parte do texto, que já havia sido finalizada, em uma página e ainda sim tive problemas. Por conta disso, reduzi parte do conteúdo e deixei o exemplo na [primeira página do arquivo](https://drive.google.com/file/d/1R3H6wjn2fnQlLLYiO7L34jF-DjIBrAzu/view).

Gostaria que dessem um feedback e sugerissem algumas soluções para que o flyer fique um pouco menos poluído.

**Comment by Dovyski** [comment]
A [primeira página do arquivo](https://drive.google.com/file/d/1R3H6wjn2fnQlLLYiO7L34jF-DjIBrAzu/view) que a @estelavilasboas  mencionou está ótima, porém tem muito texto. Precisamos reduzir o texto, ou reduzir o tamanho da fonte dele.

Sobre o tamanho, ele precisa ser A4.

**Comment by alessandrapedrotti** [comment]
Vou trabalhar na redução do texto. Devo considerar apenas o que está na primeira página do arquivo compartilhado?

**Comment by Dovyski** [comment]
Não necessariamente, Ale. Confere se tem algum texto na segunda página que falta na primeira e que tu julgue pertinente de existir no flyer. A ideia é termos um panfleto que consigamos passar, de forma clara e simples, o que é o practice e o que ele oferece.

**Comment by alessandrapedrotti** [comment]
Não julguei necessário fazer alterações nas duas páginas, trabalhei apenas na primeira e deixei o texto mais simples e sucinto.
Fiz algumas alterações no texto e deixei um comentário de sugestão de disposição de uma frase em particular.
Se for necessário, faço mais uma leitura após a finalização da parte gráfica.

@estelavilasboas aguardo teu retorno.

**Comment by elisribas** [comment]
Reduzam o texto para que caiba tudo em 2 páginas.

**Comment by estelavilasboas** [comment]
> Não julguei necessário fazer alterações nas duas páginas, trabalhei apenas na primeira e deixei o texto mais simples e sucinto.
> Fiz algumas alterações no texto e deixei um comentário de sugestão de disposição de uma frase em particular.
> Se for necessário, faço mais uma leitura após a finalização da parte gráfica.
> 
> @ estelavilasboas aguardo teu retorno.

Fiz a alteração que solicitou e reposicionei os itens para que os tamanhos dos parágrafos não destoassem uns dos outros

**Comment by alessandrapedrotti** [comment]
No que tange a parte textual, o material está pronto.
Basta a finalização gráfica e aprovação da coordenação @Dovyski .
