### ISSUE TITLE
Colocar notícia no site do Practice sobre o Edital 490/GR/UFFS/2020

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/programa#107]
Colocar notícia sobre as inscrições para o Edital 490  (bolsista para LS) "igual" a existente sobre o Edital 460.

Inscrições encerram dia 08/09/2020.

**Comment by lcaimi** [comment]
@CleissonVieira não achei a notícia nem no site (practice.uffs.cc) nem no git do site.

**Comment by CleissonVieira** [comment]
No git está, no site o sistema de deploy acusou um erro, eu não entendo dessa parta, não sei como resolver esse erro. 

![image](https://user-images.githubusercontent.com/29258164/92269023-bc13dc00-eeb9-11ea-9e80-7872284392d5.png)
![image](https://user-images.githubusercontent.com/29258164/92269042-c59d4400-eeb9-11ea-8d6a-d2a8b4ff21f3.png)

**Comment by Dovyski** [comment]
@CleissonVieira quando qualquer problema dessa natureza aparecer, por favor, bipar a @practice-uffs/dev-ops . O problema no site foi causado pela minha pessoa espetacularmente brequando o deploy de CI/produção em todos os repos para tentar arrumar o deploy do app do Practice.

Tudo certo agora ❤️ :shipit:  Malz!
