### ISSUE TITLE
Live da Semana Acadêmica de Pedagogia - Chapecó (08/09/2020)

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/programa#108]
Organização: Curso de Pedagogia - Chapecó

Contato: Profa. Marcia Andreia Triches <marcia.triches@uffs.edu.br>

Titulo: ABUSO SEXUAL: A FORMAÇÃO DO/A PROFESSOR/A E SUA RESPONSABILIDADE NO PROTEÇÃO DA CRIANÇA E ADOLESCENTE

Ministrantes: Psicóloga Clínica Thaíse Kunzler
Profª. Carme Collet 

Link Youtube: https://youtu.be/VftFk3PHRD8

**Data: 08.09.2020**

**Horário: 19h - 21h**

**Comment by lcaimi** [comment]
Roteiro disponível [neste arquivo](https://drive.google.com/file/d/1Jzspok5gK86NtgFHT7T2geCEZgwqLySw/view?usp=sharing).

**Comment by MaNegrao** [comment]
Live concluída com sucesso 😁
