### ISSUE TITLE
Live da Semana Acadêmica de Pedagogia - Chapecó (09/09/2020)

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/programa#109]
Organização: Curso de Pedagogia - Chapecó

Contato: Profa. Marcia Andreia Triches marcia.triches@uffs.edu.br

Titulo: O APAGAMENTO DOS ESTUDOS DE GÊNERO DAS POLÍTICAS EDUCACIONAIS

Ministrante:  Profª. Dra. Mirian Grossi - UFSC

Mediador: Profª. Dra. Noeli Gemelli Reali 
                  Profª. Dra. Neide Cardoso de Moura – UFFS/CH
                 Acadêmica Sabrina Brandão

**Data: 09.09.2020

Horário: 19h - 21h**

**Comment by Dovyski** [comment]
@lcaimi tu precisa de alguma coisa da @practice-uffs/con-design aqui ou foi o label errado? Se precisar de algo, não está muito claro o que é 😝 Se foi um erro, por favor, confere as labels.

**Comment by lcaimi** [comment]
:raised_hand: Erro meu!!! Obrigado @Fernando :cop:

**Comment by lcaimi** [comment]
Roteiro disponível [neste arquivo](https://drive.google.com/file/d/1Xj1eBlGCYTdzfMp9djYZBggGZCZFVyip/view?usp=sharing).

**Comment by MaNegrao** [comment]
Live Finalizada, ótimo retorno da coordenadora :D
