### ISSUE TITLE
[Cartilha] Ferramenta de gravação e edição de vídeo

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/programa#11]
É necessário montar uma cartilha documentando explicando as ferramentas e tecnologias que utilizamos e recomendamos. Dentre elas, está o [Shotcut](https://shotcut.org/), uma ferramenta de gravação e edição de vídeo. Ele deve ser adicionado à cartilha devidamente explicado (download, instalação, uso, etc).

**Comment by oigor** [comment]
Em processo...

**Comment by oigor** [comment]
Olá senhores e senhoras, queria pedir sugestão de vocês sobre programas indicados:
1-) Programa de gravação
2-) Programa de edição  

Os mesmos ficaram presentes na página de recomendação da cartilha.


A cartilha está estruturada da seguinte forma: 

Programa de Gravação:(tela e áudio) 
Tutorial sobre programa: aTube Catcher  
Resumo do programa e programas recomendados:  ( OBS se encontra como recomendado)

Programa de edição de vídeo:
Tutorial sobre programa: Shotcut  
Resumo do programa e programas recomendados:

@practice-uffs/con-material @practice-uffs/con-midia  @Dovyski

**Comment by phdmauricio** [comment]
1-) Programa de gravação (Será que o OBS é muito rocket science pra indicar? Tem o próprio "Camera" do Windows, se for pra ser mais simples, aí já faz aúdio e video.

Se for somente aúdio, sugiro o Audacity.

Edição o ShotCut, com certeza.

**Comment by Dovyski** [comment]
Gravação de tela: 
* [OBS Studio](https://obsproject.com/)
* [ShareX](https://getsharex.com/)

Edição de vídeo:
* [Shotcut](https://shotcut.org/)
* [OpenShot](https://www.openshot.org/)

**Comment by oigor** [comment]
Ok então, Cartilha finalizada.

Poderia a equipe da @practice-uffs/con-midia  fazer a revisão ?

**Comment by alessandrapedrotti** [comment]
A cartilha deve ser editadapara ficar com o tamanho de uma folha A4? @oigor @Dovyski @practice-uffs/con-material

**Comment by oigor** [comment]
Eu fiz nesse formato por acreditar que assim fica mais visível as imagens e mais dinâmico. Acredito que o formato A4 tenha seus méritos em material impresso, porém em divulgação digital um PDF de slide é mais pratico para o usuário: cada página contém um "tema/funcionalidade".

**Comment by Dovyski** [comment]
@practice-uffs/ger acredito que todas as cartilhas devam seguir o mesmo formato A4, para eventual impressão ou criação de apostilas. Entendo o posicionamento que o @oigor comentou, mas não vejo razão para termos um material diferente de A4 se for uma cartilha.

O que vocês acham?

**Comment by alessandrapedrotti** [comment]
Primeira leitura de revisão textual finalizada no dia 17/07.

Fiz muitos comentários ao longo do texto de tópicos diversos, eles abortam tanto questões textuais quanto de design. Acredito que teremos um certo trabalho para moldar essa tarefa em um manual (como apontei tanto num comentário no texto quanto em reunião de sprint).

Peço que a @mariagelain faça uma leitura e observação do texto para contribuições sobre o design desse material.
Também peço que a @elisribas olhe esse material para revisão pedagógica (alguns dos comentários que fiz são pedindo algumas orientações dela).

No mais considerei o texto bem completo. Fugiu completamente da proposição elaborada para uma cartilha, entretanto podemos simplesmente adaptar o material para um manual e vai ficar 100%.

**Comment by alessandrapedrotti** [comment]
> @practice-uffs/ger acredito que todas as cartilhas devam seguir o mesmo formato A4, para eventual impressão ou criação de apostilas. Entendo o posicionamento que o @oigor comentou, mas não vejo razão para termos um material diferente de A4 se for uma cartilha.
> 
> O que vocês acham?

Eu não entendo muito de design, mas também acho que o formado A4 é mais adequado para esse tipo de material, não só pensando na impressão, mas que a proposição é que seja um material de estudo, portanto ter páginas maiores com o texto melhor distribuído fica mais fácil do leitor acompanhar e se situar.

**Comment by oigor** [comment]
A segunda versão já está pronta para a revisão no formato A4 e com as alterações pedidas

**Comment by Dovyski** [comment]
Ajustar o seguinte:

* [ ] Algumas imagens estão distorcidas. Reduzir o tamanho delas para evitar a distorção.
* [ ] Reduzir o tamanho do texto (tamanho da fonte) para os conteúdos que não forem títulos. Atualmente eles estão praticamente do mesmo tamanho dos títulos e subtítulos. Tamanho 12 de fonte para o texto está bom.

Também deixo o registro para a @practice-uffs/con-material que eu quero fazer a revisão de design final do documento antes da publicação.

**Comment by elisribas** [comment]
Vc vai revisar todos os conteúdos da equipe de Conteúdo, @Dovyski?

**Comment by Dovyski** [comment]
Eu estou revisando com um olhar mais técnico e gráfico, não de conteúdo propriamente dita.

**Comment by elisribas** [comment]
Mas então não precisaremos atentar para as questões gráficas? Acho que precisamos discutir sobre isso em reunião. Considero retrabalho. ;)

**Comment by elisribas** [comment]
> Eu estou revisando com um olhar mais técnico e gráfico, não de conteúdo propriamente dita.

@Dovyski depois de revisar, nos avise para concluirmos a tarefa.

**Comment by Dovyski** [comment]
Vou deixar a revisão gráfica final para a @estelavilasboas como conversamos na reunião, @elisribas, assim a con-conteúdo/material tem mais autonomia nos trabalhos e não depende de mim.

**Comment by elisribas** [comment]
@estelavilasboas concluir revisão.

**Comment by elisribas** [comment]
@Dovyski considerando que:

- o material está pronto pela equipe de conteúdo;
- que não dominamos o manuseio do sw;
- que o criador do conteúdo não está mais no programa;

Você pode fazer uma revisão final sobre as explicações de como manusear o sw e nos dizer se está adequado? Assim poderemos fechar a issue.

**Comment by alessandrapedrotti** [comment]
Complementando o comentário da @elisribas, na verdade ainda preciso fazer a última leitura da revisão textual, para deixar ela 100% pronta. Muito provavelmente precisarei da sua ajuda @Dovyski pois não domino as ferramentas que são o assunto do manual. Portanto, adicionarei novamente a label de "texto:emrevisão".

**Comment by alessandrapedrotti** [comment]
Fiz a segunda leitura de revisão e alterei alguns aspectos do texto. Gostaria que vocês dessem uma olhada, pois deixei alguns comentários que preciso de ajuda para resolver.
@Dovyski @elisribas

**Comment by MaNegrao** [comment]
@alessandrapedrotti podemos desmembrar essa issue em duas e prosseguirmos o trabalho, ou até recomeçar. A parte de gravação a gente pode substituir pelo manual de gravação do obs. A parte de edição a gente mantem e passamos adiante, reescrita e reestruturar tudo que for necessario

**Comment by alessandrapedrotti** [comment]
> @alessandrapedrotti podemos desmembrar essa issue em duas e prosseguirmos o trabalho, ou até recomeçar. A parte de gravação a gente pode substituir pelo manual de gravação do obs. A parte de edição a gente mantem e passamos adiante, reescrita e reestruturar tudo que for necessario

Faremos o seguinte:

Essa issue será fechada e a tarefa de elaborar um manual da ferramenta Shotcut será retomada num futuro próximo pela equipe de mídia, em complementação aos vídeos que estão sendo feitos com a mesma temática.
Quando a elaboração do material for recomeçada, você @MaNegrao como líder da equipe de mídia poderá julgar se o que foi produzido até o momento será aproveitado ou não.
Se vale a minha sugestão, como a ideia é que o material escrito seja apenas um complemento ao já feito em vídeos, que seja então produzida um cartilha com dicas da ferramenta, é não um manual propriamente dito.
