### ISSUE TITLE
Edição de Audio para Prof. Morgana - Letras Chapecó 

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/programa#111]
Edição de Audio para a profa. Morgana - Letras Chapecó

Email: Coordenacao do Curso de Letras - Chapeco letras.ch@uffs.edu.br

Material será disponibilizado na [pasta do Drive da ISSUE](https://drive.google.com/drive/folders/1zHkNB8tpmSARB1-TDA9Co1z50ysIc0za?usp=sharing) na segunda-feira 07/09

Prazo de entrega: 08/09/2020

**Comment by VIF-Franca** [comment]
Primeira versão do podcast editado, disponível no drive.

Obs.: essa versão está sem a vinheta sonora, creio não ter a melhor voz para isso hahaha. Caso alguém gravar um áudio posso adicionar ou suprimimos o momento que a narradora diz sobre vinheta. 

Aguardo feedback,

**Comment by VIF-Franca** [comment]
Deixei disponível no drive todos os efeitos sonoros captados na plataforma do Youtube que consta no guia.

**Comment by VIF-Franca** [comment]
Versão final no drive na pasta SAÍDA

**Comment by Dovyski** [comment]
Falta apenas o cliente assinar o termo de direitos autorais. O produto ficou excelente! Meus parabéns e aplausos de pé pelo trabalho, @VIF-Franca!

**Comment by lcaimi** [comment]
Aprovado e com felicitações do cliente.
![audio_editado](https://user-images.githubusercontent.com/12415747/92633526-450b8880-f2a9-11ea-991f-27b19dc92169.jpg)
