### ISSUE TITLE
Edição dos vídeos das intérpretes de libras dos Campi

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/programa#112]
Edição solicitada pelas interpretes de Libras onde as mesmas se apresentam e apresentam sinais que descrevem locais vinculados a UFFS. São 6 videos e as ações solicitadas são:

- [ ] inserir o nome da pessoa com o símbolo da UFFS no inicio e uma barra com o nome; Ver manual de identidade visual da UFFS para pegar a imagem correta e visualmente atraente de acordo com o padrão de cada vídeo;
![image](https://user-images.githubusercontent.com/12415747/92280344-8aa60b00-eecf-11ea-9d86-2158c396c0ab.png)

- [ ] inserir em um dos cantos superiores a imagem com os três estados, e o local e nome da cidade da pessoa que está no vídeo em destaque. As demais cidades apenas o ponto do local;

Achei as duas imagens abaixo para exemplificar, mas nenhuma está legal para o propósito.
![image](https://user-images.githubusercontent.com/12415747/92280579-0c963400-eed0-11ea-81ea-c62154856b2f.png)
![image](https://user-images.githubusercontent.com/12415747/92280611-2899d580-eed0-11ea-951b-48e350ae978e.png)

- [ ] Inserir uma musica "ambiente/instrumental" no vídeo;

Na [pasta do drive](https://drive.google.com/drive/folders/1UDVTbKWY3yISsOE3rTlha3U0fO4q-VZU?usp=sharing) estão os vídeos e um [documento com as informações a serem utilizadas em cada vídeo](https://docs.google.com/document/d/1sdQ6z1xc4ageIIR5QPHMv5pSItxA-sF5IiYp31HLgy4/edit?usp=sharing).

Fazer [primeiro este vídeo](https://drive.google.com/file/d/1xrZUAJkKdtRcX4Rp74mNgKcXb1cpz5SN/view?usp=sharing) para apresentar para o Cliente aprovar.

**Comment by lcaimi** [comment]
Contato: 
Sheila Marques Duarte Bassoli - <sheila.bassoli@uffs.edu.br>

**Comment by vini2reis** [comment]
@estelavilasboas você pode fazer uma barra em branco igual aquela que o Negrao usa nas lives so que com as cores da UFFS?
E o segundo tópico também?

**Comment by estelavilasboas** [comment]
Fiz algumas [barras flutuantes](https://drive.google.com/drive/folders/11mBUsesS_nmRGTlYnzXfSqS1MFDlZW56), assim como havia sido feito inicialmente para as Lives do PRACTICE. Porém, não sei se estão em proporções adequadas para os vídeos. Favor verificar.
Verifiquei o Manual de Identidade Visual e usei os subtons de verde do site.

O mapa vai levar mais tempo para ser feito.

**Comment by estelavilasboas** [comment]
A princípio fiz o mapa transparente com um "pin" para montar. Favor, verificar quais ajustes devem ser feitos (por exemplo, cor de fundo).
![mapa](https://user-images.githubusercontent.com/30927758/92778682-c7fb1480-f377-11ea-95b1-f988e47baf43.png)

**Comment by Dovyski** [comment]
@estelavilasboas o mapa ficou ótimo. Precisamos de uma versão com cada um dos estados preenchidos com a cor verde, para quem sabe deixar o conteúdo mais interessante. Outro detalhe é que você precisa colocar pedidos de design na pasta da issue no drive, e colar aqui a imagem apenas para discussão/feedback.

@practice-uffs/con-midia discutimos na gerência que, quando uma tarefa exigir material gráfico que *pode* ser montado pelo responsável da tarefa (como uma mapa), a @practice-uffs/con-design não precisa ser solicitada. De qualquer forma, fica a cargo do @lcaimi decidir isso sempre que julgar que o material gráfico exige a mão da @practice-uffs/con-design.

**Comment by lcaimi** [comment]
Retorno do cliente:
Gostei do V2. 
- Penso que o mapa deve aparecer só quando tiver os outros vídeos indicando os campis.
- Nesse primeiro momento do vídeo(Amanda) pode ser tirado o mapa e no lugar colocar a logo da UFFS [pq é o sinal geral] e quando for acrescentado os demais coloca o mapa com uma indicação do campus junto.
@vini2reis

**Comment by vini2reis** [comment]
Fiz as alterações e ja subi no drive a nova versao

**Comment by lcaimi** [comment]
Retorno do solicitante:

- O que eu identifiquei foi a ultima [Sonize] ela não é tradutora e sim professora do Campus Erechim (coloquei em destaque no roteiro) ela apenas colaborou pq no campus Passo Fundo não temos intérprete. 
Só verificar o roteiro no drive que ta certinho o nome e função [video passo fundo]

Acho que no final do vídeo pode ter uma imagem só pra não terminar direto com o vídeo, e pode ser a capa do vídeo. Coloquei um modelo no drive (a imagem em azul refere-se "acessível em Libras).

**Comment by vini2reis** [comment]
Corrigido

**Comment by lcaimi** [comment]
Solicitante aprovou, agradeceu e elogiou.

Parabéns @vini2reis por mais esta atividade concluida.
