### ISSUE TITLE
Edição de 2 videoaulas do prof. Fabrício (ADM) 

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/programa#113]
Editar as 2 videoaulas do Prof. Fabrício (ADM)

- [ ] Iniciar com a vinheta do Practice
- [ ] Usar modelo com slides + video do professor
- [ ] colocar créditos no final: 
- Nome do professor 
- Disciplina 
- Curso
- Gravação
- Edição
- Arte

Arquivos estão na [Pasta do Drive](https://drive.google.com/drive/folders/16_KViiSVh-pcd8DuN-qrYAAMWI_mqRuX?usp=sharing)

Professor ainda não enviou os Slides

**Comment by vini2reis** [comment]
Esses vídeo são referentes á gravação da issue #99?

**Comment by lcaimi** [comment]
Exatamente.

**Comment by lcaimi** [comment]
Os Slides das duas aulas estão disponíveis na pasta do Drive da Issue#113

**Comment by vini2reis** [comment]
O vídeo editado da Aula 1 já esta na pasta do drive.

**Comment by lcaimi** [comment]
Retorno do prof. Fabricio solicitando adequações: @vini2reis 

> Queria ver se podemos deixar os slides menos opacos, me pareceu meu ofuscado o conteúdo. E| aumentar o som da minha fala?
> No mais ficou SHOW.
> Material de profissional.

**Comment by vini2reis** [comment]
Na questao da opacidade esse é o menos opaco possivel, mas eu mexi na saturaçao para deixar as cores mais fortes (creio que isso deixou menos ofuscado).
E som aumeitei o maximo possivel para o chiado nao atrapalhar

Vou usar essas mudanças para o segundo video tambem.

**Comment by vini2reis** [comment]
Na questao da opacidade esse é o menos opaco possivel, mas eu mexi na saturaçao para deixar as cores mais fortes (creio que isso deixou menos ofuscado).
E som aumeitei o maximo possivel para o chiado nao atrapalhar

Vou usar essas mudanças para o segundo video tambem.

**Comment by vini2reis** [comment]
O vídeo 1 com as alterações e o vídeo 2 ja estao disponiveis na pasta do drive

**Comment by lcaimi** [comment]
Encaminhado para o cliente revisar.

**Comment by lcaimi** [comment]
Aprovado pelo cliente.
Parabéns @vini2reis o trabalho foi bastante elogiado.
