### ISSUE TITLE
ETAPA 2: Revisão, correção e aprimoramento APP-saúde I

### ISSUE THREAD

**Issue by robisonjose** [practice-uffs/programa#1136]
Toda a equipe do projeto deverá revisar, corrigir e aprimorar o aplicativo como um todo.

**Comment by robisonjose** [comment]
Meu feedback:

- Deveria ter uma aba que você pode ver as respostas que você deu, separado em dias e turnos, das perguntinhas que aparecem pro SAE e o "como você está se sentindo agora?". Isso poderia estar dentro da parte "estatísticas";
- As dicas do SAE poderiam ficar em uma aba separada (Com o nome de "Dicas do SAE") e dentro dessa aba, os itens: Saúde, sono, alimentação, atividade física;
- O questionário não está funcionando, mas também deveria ter um lugar que você consegue ver suas respostas por semana;
- Batimentos cardiacos, não está funcionado e não sei qual câmera eu devo colocar o dedo indicador;
- No tema escuro não dá pra ver direito as bolinhas na parte de baixo, ai não da pra saber que tem coisa pro lado. Eu sugiro fazer tudo de rolagem cima-baixo; 
- Mudanças em relação à organização:

No lugar de 13 opções na tela inicial, poderiamos colocar 4 e dentro dessas 4 colocar o resto:

1. Transtornos mais comuns

Dentro dele a gente coloca os nomes dos transtornos mais comuns, e as opções "Preconceitos e tabus" e "Buscar ajuda". Quando clicamos no nome dos transtornos, isso nos leva a uma tela com uma explicação breve do transtorno e duas palavras clicáveis (Principais sintomas e Fatores responsáveis) que quando expandidas mostram os principais sintomas e os fatores responsáveis por aquele transtorno.

2. Dicas do SAE:

Dentro dele a gente tem os ícones clicáveis de:  Saúde, sono, alimentação e atividade física.

3. Meditação guiada: 

Dentro dele a gente faz a parte da meditação guiada.

4. Minhas estatísticas: 

Daria pra deixar mais ou menos como está, mas com a possiblidade de ver "Minhas respostas", com a data, dia, e hora. Também poderiamos fazer mais umas perguntas, como: Quantas horas você dormiu essa noite? Quantas refeições você fez hoje? Quão satisfeito você ficou com suas atividades da universidade hoje? Quão satisfeito você ficou com as tarefas que você realizou hoje? 

- Seria interessante, no lugar de colocar a porcentagem nas estatísticas, colocar aquelas carinhas em todo o meio círculo, pra pessoa ver qual "carinha" ela mais se aproxima na média. E quando tiver perguntas que tem números como resposta, colocar a média das respostas. 

- Ainda não vi a parte de meditação guiada, então vou atualizar a resposta quando eu ver.

**Comment by morgana-mo** [comment]
O aplicativo como um todo está bem legal, precisamos de alguns "acabamentos", concordo com tudo que o @robisonjose colocou.
Minhas sugestões:

- Padronizar a organização das telas, ou todas de puxar para o lado ou todas com rolagem.


- A funcionalidade dos batimentos cardíacos não funciona para mim (ou pelo menos não funcionou até agora)

- Quando são usadas imagens em algumas telas, sugiro não usarmos, ou usarmos em todas pois fica estranho apenas um item da seção ter imagem e os outros não.
![image](https://user-images.githubusercontent.com/71781124/160188373-03ec57de-aa98-4466-879e-8ea9c694f84d.png)

- Na aba da meditação guiada acho que a gente pode tentar uma configuração diferente, eu particularmente achei estranha da forma que está, eu fiz um modelinho da minha idéia, que seria basicamente separar cada uma das meditações  e separando elas a gente poderia ter um textinho explicando cada uma. 
![Android Large - 1](https://user-images.githubusercontent.com/71781124/160190338-d4079161-cd01-4c48-ab67-eeaa557e4dd6.png)
![Android Large - 1 (1)](https://user-images.githubusercontent.com/71781124/160191746-d92f03e2-1ca0-4224-bac3-38020c27a562.png)

**Comment by brendaellen** [comment]
@SWE3T, deixei um [documento](https://docs.google.com/document/d/1s59cu5q_epG-wG08mL0UlbXKIBAIpnBblWK-Uq1saSo/edit?usp=drive_web&ouid=107308426775444044736) na pasta de entrada contendo algumas sugestões e observações em relação ao conteúdo do app.
