### ISSUE TITLE
Criar vídeo de animação LS

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#115]
Demanda enviada pelo coordenador Thiago, criar um vídeo animado com imagens (paisagens) do campus adicionando o áudio e imagens disponível no drive. 

Deverá conter legenda de acordo com o texto fornecido.

**Comment by Dovyski** [comment]
Um detalhe de não esquecer de colocar todos os materiais enviados pelo cliente na pasta `entrada` dessa issue no drive.

**Comment by VIF-Franca** [comment]
O cliente aprovou a primeira versão do vídeo que consta na pasta SAÍDA do drive e também já realizou divulgação. Tarefa concluída.
