### ISSUE TITLE
Criação de duas vinhetas para o PPGE

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/programa#116]
Email da solicitação: 

O PPGE está com a intenção de lançar vídeos na página do programa e em outros meios com o intuito de dar maior visibilidade ao programa (vídeos falando sobre o programa e as pesquisas que são desenvolvidas).

Estamos organizando isso, e precisamos que sejam desenvolvidas a vinheta inicial e a final. As informações para tanto são as seguintes:

Estrutura do vídeo- dados gerais:

- [ ] Abertura

Slogan/Chamado: Conheça o PPGE: Diálogos e Saberes

Trilha Sonora: [https://www.youtube.com/watch?v=NFcGmLyOh4w](https://www.youtube.com/watch?v=NFcGmLyOh4w)

Arte de abertura do vídeo (vinheta inicial):
O fundo semelhante com desse vídeo (considerar a partir dos 23 segundos do vídeo): [https://www.youtube.com/watch?v=V1GVC32xZoI
](https://www.youtube.com/watch?v=V1GVC32xZoI
)
Mas em tons verdes (ao invés do vermelho), e ao invés do símbolo do infinito, algo que imite, ou semelhante a esse a esta imagem:

[https://4.bp.blogspot.com/_6AmvP-Yi0tA/S7p16850NjI/AAAAAAAAAHg/h4rwBE5LJTo/s1600/conhecimento.jpg](https://4.bp.blogspot.com/_6AmvP-Yi0tA/S7p16850NjI/AAAAAAAAAHg/h4rwBE5LJTo/s1600/conhecimento.jpg)

Durante essa abertura, desceria o slogan e o tópico do vídeo em específico(com uma fonte menor ou maior do que o Slogan, o que ficar mais agradável visualmente). E em um canto o símbolo da Uffs escrito Mestrado em Educação embaixo.

A cor da fonte: Branco

Fonte: Universal

- [ ] Arte do Encerramento:

Aumentar o volume da música (a intenção é que a trilha sonora fique rodando o tempo todo durante o vídeo)- mas nas vinhetas iniciais e finais deve estar em um volume maior

Mesmo Fundo da abertura

Primeiro Quadro 
Simbolo UFFS Chapecó e;
Mestrado em Educação.
Segundo quadro
Organização:
Bernardo Andre Mantovani
Claudia Soares
Geomara Balsanello
Karin Henzel
Lauren Pieta Canan
Letícia Stein
Thaís Stella

Editores: Nomes da equipe de edição

**Comment by vini2reis** [comment]
Ja esta no drive as vinhetas. Fiz duas versões de cada uma

**Comment by Dovyski** [comment]
A vinheta `final-versao2` ficou excelente. A música de ambas as vinhetas (início e fim) também está excelente. As vinhetas de início (1 e 2) não está tão legal assim. Os elementos usados e as cores estão excelentes, mas acho que precisamos de movimentos diferentes.

Eu sugiro tu usar a `inicio-versao2` como base e fazer as seguintes alterações:

- Fazer o logo do programa aparecer na tela com o zoom que foi usado, porém no centro da tela (e bem mais rápido).
- Fazer o tamanho da fonte do texto "Diálogos e saberes" um pouco menor que a do "PPGE".
- Fazer o texto aparecer linha por linhas, e cada linha aparecer com um `fade in` na tela, na seguinte disposição:

![image](https://user-images.githubusercontent.com/512405/93131855-1592bc80-f6ab-11ea-9b48-86ac0351d7f3.png)

**Comment by vini2reis** [comment]
> A vinheta `final-versao2` ficou excelente. A música de ambas as vinhetas (início e fim) também está excelente. As vinhetas de início (1 e 2) não está tão legal assim. Os elementos usados e as cores estão excelentes, mas acho que precisamos de movimentos diferentes.
> 
> Eu sugiro tu usar a `inicio-versao2` como base e fazer as seguintes alterações:
> 
> * Fazer o logo do programa aparecer na tela com o zoom que foi usado, porém no centro da tela (e bem mais rápido).
> * Fazer o tamanho da fonte do texto "Diálogos e saberes" um pouco menor que a do "PPGE".
> * Fazer o texto aparecer linha por linhas, e cada linha aparecer com um `fade in` na tela, na seguinte disposição:
> 
> ![image](https://user-images.githubusercontent.com/512405/93131855-1592bc80-f6ab-11ea-9b48-86ac0351d7f3.png)

Criei mais uma versão, a `inicio-versao2-3`, com essas sugestões. Já esta na pasta da tarefa.

**Comment by Dovyski** [comment]
Achei bem melhor! Só tem um problema ainda: o logo da UFFS (canto inferior esquerdo) não pode ser sombreado. A marca de UFFS nunca pode ser altera por sombra, transparência, etc.

E uma pergunta: o cliente pediu essa fonte de texto ou podemos usar `Roboto`?

**Comment by lcaimi** [comment]
O cliente não especificou fonte.

**Comment by vini2reis** [comment]
> Achei bem melhor! Só tem um problema ainda: o logo da UFFS (canto inferior esquerdo) não pode ser sombreado. A marca de UFFS nunca pode ser altera por sombra, transparência, etc.
> 
> E uma pergunta: o cliente pediu essa fonte de texto ou podemos usar `Roboto`?

Tirei o sombreado da logo
E a fonte: no shotcut existe uma fonte cujo o nome é `Universal` e foi a que eu usei pq pela descrição me pareceu que era a fonte q teria q ser usada. Precisa trocar para a `Roboto`?

**Comment by Dovyski** [comment]
Obrigado! Eu acho que com a Roboto vai ficar mais bonito.

**Comment by vini2reis** [comment]
Adicionei as versões com a fonte `Roboto`.

**Comment by Dovyski** [comment]
"Mestrado em edução" (canto inferior esquerdo) dá uma pulo de posição entre `0:06` a 0:08`. Sobre a fonte, ficou ótimo!

**Comment by vini2reis** [comment]
> "Mestrado em edução" (canto inferior esquerdo) dá uma pulo de posição entre `0:06` a 0:08`. Sobre a fonte, ficou ótimo!

Probleminha na transiçao que nao tinha percebido. Ja corrigido!

**Comment by lcaimi** [comment]
Resposta do solicitante:

Para a vinheta final, escolhemos a Vinheta-final-versão1 -  só é necessário ajustar a palavra "mestrado" (está com a grafia errada);
Para a vinheta inicial, escolhemos a vinheta-inicio_versao 2-3

Quanto Ok avisem aqui na Issue. Deixar apenas a versão final na pasta saída.
Avisar aqui quando finalizado.

**Comment by vini2reis** [comment]
> sar aqui quando finalizado.

Corrigido o erro de grafia e tudo pronto na pasta

**Comment by lcaimi** [comment]
Versões aprovadas pelo solicitante.

Parabéns @vini2reis .
