### ISSUE TITLE
Texto para RECUSAR LIVES

### ISSUE THREAD

**Issue by robisonjose** [practice-uffs/programa#1163]
Devemos fazer um texto para recusar lives. O texto deve conter possíveis contatos para buscar ajuda para isso (dentro da UFFS tem o setor de eventos - telefones.uffs.edu.br nesse site a pessoa acha todo contato que ela precisar), vídeos que o PRACTICE produziu para ajudar alguém que quer fazer live e o motivo de não estarmos aceitando (estamos focando em outros projetos e estamos com um número reduzido de pessoas trabalhando com transmissões ao vivo).

A princípio esse texto seria enviado diretamente pelo mural, mas nada impede que nós façamos um documento em PDF e enviarmos o link desse documento no mural. 

O texto não deve ser muito grande.

@con-midia

**Comment by MariaLuizaReviliau** [comment]
Ficarei responsável por essa tarefa, está sendo desenvolvida na pasta de [entrada](https://drive.google.com/drive/u/2/folders/1atEp26OettFmo9Kw3_TzebfoSAYsZOZz).

**Comment by robisonjose** [comment]
Fiz alguns comentários e sugestões, mas acho que era exatamente isso que tinhamos que fazer.

**Comment by luizatonial** [comment]
revisei tbm

**Comment by luizatonial** [comment]
- Infelizmente sua solicitação de transmissão ao vivo **não** poderá ser realizada. No momento, nos encontramos com um baixo número de bolsistas responsáveis pela realização das transmissões ao vivo, os quais já estão ocupados com outras demandas para a data do evento. 

- Recomendamos que entre em contato com o Setor de Eventos da UFFS, referente ao seu campus, clicando [**aqui**](https://telefones.uffs.edu.br/). Eles podem lhe ajudar! 

- Além disso, caso decida fazer a transmissão de forma independente, pode assistir a nossa série de vídeos no canal [**PRACTICE UFFS**](https://youtube.com/playlist?list=PLiSr_qvZsIJfknsLflH5pWiBZjlSG0Pne) no YouTube, onde ensinamos como usar o OBS Studio (software utilizado para realizar transmissões ao vivo),  e também ao minicurso realizado pelo Practice: [**”Aprendendo a fazer transmissões ao vivo com o OBS Studio”**](https://youtube.com/playlist?list=PLfEcBpWMma54B1gkfsERDRrHiVM5prbz4).

- Agradecemos a sua solicitação e esperamos que na próxima possamos lhe ajudar!

**Comment by luizatonial** [comment]
O TEXTO FINALIZADO SERÁ INCLUIDO EM UM ÚNICO ARQUIVO NA PASTA DE DOCUMENTOS DO MÍDIA
