### ISSUE TITLE
Vídeo narrado do Aplicativo Boas-Vindas

### ISSUE THREAD

**Issue by robisonjose** [practice-uffs/programa#1165]
<h1 align="center" >Informações Produção do Vídeo</h1>

Deve ser feito um vídeo narrado do Aplicativo Boas-Vindas utilizando a narração que está na pasta de entrada. 

Antes de tudo deve ser feito um roteiro em conjunto com a @brendaellen. 

**[Planilha de Vídeos Internos](https://docs.google.com/spreadsheets/d/1b7sNcCTQxXXZr4FtC6GtYyAxpd3cPin3ZjUeckLphOI/edit?usp=sharing)**

**[Planilha de Vídeos Externos](https://docs.google.com/spreadsheets/d/17fyR7tVs16PX9SGJ8ghkU4jM8W9UoSqlCE3hm2FrOzk/edit?usp=sharing)**

**[Padronização de Vídeos](https://drive.google.com/drive/folders/1ttrKgWsKRtd5yAaKdYSaVkoj7qTJYYuO)**

**[TeleCurso 2000](https://drive.google.com/drive/folders/1r_Gea2VxB3J-4VfIXr9jqXa2NgStNvCs?usp=sharing)**

CC: @con-midia / vídeos

**Comment by robisonjose** [comment]
O QR code no fim do vídeo deve ser desse link:  https://uffs.cc/practice-app-boas-vindas

**Comment by MariaLuizaReviliau** [comment]
Amanda, eu achei que os vídeos utilizados de fundo ficaram bons, também gostei da música, na tela de 0:28 eu achei que está um pouco desalinhado, mas eu sei que isso ainda é só um esboço hehehe
![image](https://user-images.githubusercontent.com/83495990/163444018-9a65727f-3613-4b13-bd76-ee19fa7d47b3.png)
e depois em 0:30 some o "auxílio estudntil" e "canais de contato", mas o "procedimentos" permanece, eu acho que ele também deveria sumir, porque parece q a gente fica esperando que ele suma e ele fica meio perdido ali, ou então nenhum deles sumir, apenas a trocar a tela como um todo. 
No mais, eu acho que está ficando muito bomm

**Comment by luizatonial** [comment]
Achei interessante o esboço também, a música está um pouco alta tem relação à voz da Maria em algumas partes e existe a questão dos alinhamentos que já foi comentada, mas como é um esboço acho que tudo isso será ajustado… gostei dos vídeos, me pergunto se não poderia ter sempre algum vídeo atrás das escritas já que você tá usando umas tarjas coloridas pra destacar ela? Mas aí vc vê o que fica mais legal

**Comment by robisonjose** [comment]
Concordo com o que foi falado até agora, acredito que colocar os vídeos atrás das escritas vai ficar mais legal. E acho que poderia dar destaques em palavras chave, assim como nos vídeos de propaganda. Ademais, tem que aumentar o áudio da Maria e diminuir a música. Ai creio que vai ser necessário algum tratamento no áudio, mas pode ser que não. No mais eu acho que vai ficar bem legal.

**Comment by amandasegattob** [comment]
Oi gente! Tem muita coisa pra arrumar ainda hahaha, era mais para saber o que vocês acham dos elementos (vídeos reais, escrita...), fiquei com receio dele ficar muito parecido com o outro, mas vou trabalhar com esses elementos e seguir as sugestões. Obrigada!

**Comment by amandasegattob** [comment]
Oi gente! Fiz uma primeira versão do vídeo, está na pasta de entrada. 

Segui as sugestões e o mesmo padrão do outro vídeo. Aguardo feedback. 

@practice-uffs/con-midia @brendaellen

**Comment by robisonjose** [comment]
@Dovyski @practice-uffs/ger-comunicacao @practice-uffs/ger-auxilio 

Por favor, revisem os vídeos até quarta (27/04).

**Comment by luizatonial** [comment]
acho que a voz da Maria poderia estar mais alta ainda… tirando isso achei o vídeo bem legal.

Essa única parte final com a logo e a tarja me incomodou um pouco mas não pensei em nada pra melhorar kk talvez deixar o vídeo mais claro não sei 
![85B0A079-84DC-4441-8B89-E7FA4361421F](https://user-images.githubusercontent.com/71669357/165204004-a2026be9-04bc-496b-b994-04d8110f7f6f.png)

**Comment by morgana-mo** [comment]
O vídeo está muito bom @amandasegattob ,gostei bastante da narração da @MariaLuizaReviliau  mas acredito que ela poderia estar mais alta.
Tenho algumas sugestões que ao meu ver deixariam o vídeo ainda melhor do que já está:
Sugestão 1: Padronização do tamanho da fonte nesse trecho do vídeo, acho que assim como está fica um pouquinho estranho.
![Screenshot_20220425-225949](https://user-images.githubusercontent.com/71781124/165204723-29556257-b035-4a66-ab92-3a1bd6b5b717.png)
Sugestão 2: Tentar padronizar a "tamanho" que fica o verde em volta das letras nesse trecho (acho que isso dá pra acertar nas configurações do texto mesmo)
![Screenshot_20220425-230101](https://user-images.githubusercontent.com/71781124/165204993-6276aea9-e580-425d-a516-b68e4f005988.png)
Sugestão 3: Deixar o fundo dessa tela mais opaco (branco) pra destacar melhorou o nome do app.
![Screenshot_20220425-230131](https://user-images.githubusercontent.com/71781124/165205075-0db42bcf-3cf0-49c5-b90f-7ff785f60e61.png)

**Comment by brendaellen** [comment]
Na minha opnião o vídeo ficou maravilhoso, e super dentro da proposta. Concordo com todas as observações que foram faladas até aqui, mas pelo que vi, as alterações já estão sendo feitas, então tá tudo certo.
A única observação que tenho a fazer, é em relação a narração que realmente está baixa, porém não sei se ficaria melhor diminuindo a música, pois a vivacidade do vídeo ficaria comprometida.

**Comment by amandasegattob** [comment]
Boa noite, pessoal! Fico feliz que gostaram!

Fiz as alterações sugeridas. Em relação à música, era dela mesmo e não consegui alterar, porque ela era muito curtinha, então fiz duas versões com músicas diferentes. Os vídeos estão na pasta de entrada.

**Comment by robisonjose** [comment]
Gostei mais da versão 1.

**Comment by luizatonial** [comment]
Tbm gostei mais da 1

**Comment by robisonjose** [comment]
O vídeo finalizado está na pasta de saída. Portanto, essa tarefa está concluída.

**Comment by morgana-mo** [comment]
[Postado](https://fb.watch/dfzxcOoFVr/)
