### ISSUE TITLE
Desenvolver template de flyer

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#117]
Desenvolver, conforme acordado em reunião (08/09) um template base para flyer, adicionando todas as informações necessárias à descrição de produtos já existentes.

**Comment by estelavilasboas** [comment]
Foram criados 3 templates para diferentes usos, tendo em vista que flyers serão necessários em diferentes ocasiões.

**Comment by Dovyski** [comment]
Eu achei eles excelentes, parabéns, pessoal! Por mim, podemos colocá-los na pasta de documentos/templates para uso futuro de todas as outras equipes/programas.

**Comment by alessandrapedrotti** [comment]
> Eu achei eles excelentes, parabéns, pessoal! Por mim, podemos colocá-los na pasta de documentos/templates para uso futuro de todas as outras equipes/programas.

Não seria melhor criar uma pasta "divulgação" e reunir esse tipo de material lá? E deixar na pasta templates só o esqueleto?

**Comment by Dovyski** [comment]
Sim, foi isso que eu quis dizer, @alessandrapedrotti . Colocar esse esqueleto na pasta de templates que temos. Os flyers com conteúdo mesmo (os que serão usados para divulgação), esses podem ir para uma pasta especial (divulgação é um bom nome) dentro da pasta de documentos do programa.

**Comment by alessandrapedrotti** [comment]
Os templates estão na pasta [FLYERS - Templates ](https://drive.google.com/drive/u/0/folders/1t30y9uPM0L5iQ1GRl6omnA6VopQRe9NP)na pasta "materiais"  do programa.
