### ISSUE TITLE
Manual Github

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#118]
Desenvolver manual do github para os novos bolsistas do PRACTICE.
O manual deve ser completo e detalhado, considerando que muitos dos novos integrantes não conhecem a plataforma.

**Comment by isabelirk** [comment]
Boa tarde

@Dovyski já temos uma primeira versão do manual, por favor de uma olhada para ter certeza que não foi deixado nenhum detalhe para trás. Segue o link abaixo:

https://drive.google.com/drive/folders/19T6d_TRkJyvi4o5zscg3dJjpfJ0buSp3

Atenciosamente.

**Comment by isabelirk** [comment]
OBS: desconsiderar os últimos slides

**Comment by Dovyski** [comment]
O conteúdo está excelente, Isa. Em relação às figuras, talvez elas pudessem ser maiores, mas podemos deixar isso para uma segunda versão. Pode fechar a tarefa e colocar o manual na pasta de documentos do programa.

**Comment by isabelirk** [comment]
Aguardando revisão final da @alessandrapedrotti para finalizar a issue.

**Comment by alessandrapedrotti** [comment]
Primeira leitura de revisão finalizada. @isabelirk deixei alguns comentários no manual que gostaria que você resolvesse, são coisas bem simples e pontuais.

Pra primeira versão, o texto já está muito bom.

Depois de ajustados os comentários que deixei, @mariagelain pode fazer a revisão da diagramação.

**Comment by isabelirk** [comment]
@mariagelain pronto para diagramação.

**Comment by mariagelain** [comment]
Diagramação feita. Peço para a @estelavilasboas faça as alterações de design necessárias.

**Comment by mariagelain** [comment]
@Dovyski o manual está pronto para ser usado na reunião de introdução dos novos bolsistas.

**Comment by Dovyski** [comment]
Fantástico, obrigado pelo trabalho maravilhoso, meninas!

**Comment by alessandrapedrotti** [comment]
A versão final do manual pode ser acessada [nesta pasta](https://drive.google.com/drive/u/0/folders/1qiWTGn99_oKKl4qHFPEFTgGvFVYyhYzW).
