### ISSUE TITLE
Panfleto com material educativo para produtores rurais (Polícia Militar Ambiental Chapecó)

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#1181]
O objetivo dessa tarefa é diagramar um panfleto, feito com folhas A4 impressas frente e verso, dobradas em 3 partes, para ser utilizado como material educativo distribuído pelas guarnições da Polícia Ambiental de Chapecó nas propriedades rurais do município.

**A Polícia Ambiental forneceu 4 elementos que precisam estar no panfleto/cartilha:**

* Logo do projeto (que provavelmente guiará como será o design/arte geral do panfleto)
* Texto "UTILIZAÇÃO DE MADEIRA E LENHA POR PEQUENOS PRODUTORES RURAIS."
* Texto "Orientação Fauna e Caça"
* Texto "Pesca e Poluição"

O panfleto/cartilha aborda vários temas ambientais (madeira, fauna e caça, pesca e poluição), sendo que todos esses devem estar na cartilha. 

**Observações importantes que recebemos:**

* O material é oficial da Polícia Militar Ambiental Chapecó, então ele precisa ter um "tom visual" profissional e sóbrio/sério (não pode ser algo cartoon, por exemplo).
* Eles já nos forneceram os textos para uso, então não precisamos elaborar nada nesse sentido. Eles autorizam, entretanto, revisões e eventuais melhoramentos textuais (lembrando que o público alvo sào produtores rurais)
* O logo da Polícia Militar Ambiental de Chapecó deve estar no panfleto, assim como a logo do Practice e da UFFS.

Os materiais recebidos estão na pasta entrada da issue. O contato para comunicação com o cliente é a **Ten Cel PM Andréia Cristina Fergitz** (me procure no Telegram para passar o e-mail e whatsapp deles para comunicação).

*OBS:* como esse é um projeto de parceria, não vamos tramitar a solicitação pelo mural, faremos tudo aqui pelo github.

**Comment by minieradka** [comment]
iniciei os esboços no [figma](https://www.figma.com/file/LRy42hR3hNv4GItaM1tiQ7/Panfleto-Policia-Ambiental-de-Chapeco?node-id=0%3A1)

**Comment by minieradka** [comment]
prévia do folder enviado ao solicitante e disponível na pasta de saída

**Comment by mariagelain** [comment]
A @brendaellen está revisando os textos dessa issue

**Comment by brendaellen** [comment]
A revisão foi finalizada, e os textos estão na pasta [DOCS REVISADOS](https://drive.google.com/drive/folders/1Ewbr2DmzEF06gUDvySxApmC5NcOAKXf3). Os arquivos com o texto original permanecem na pasta de entrada, caso precisem consultar.

**Comment by kamila-rosa** [comment]
Certo! Obrigada @brendaellen ! Daremos continuidade ao layout  [no figma](https://www.figma.com/file/LRy42hR3hNv4GItaM1tiQ7/Panfleto-Policia-Ambiental-de-Chapeco?node-id=0%3A1) com os textos revisados.

**Comment by kamila-rosa** [comment]
Olá! A _versão para revisão geral_ do folder está [nesta página do figma](https://www.figma.com/file/LRy42hR3hNv4GItaM1tiQ7/Panfleto-Policia-Ambiental-de-Chapeco?node-id=0%3A1), trata-se da versão que deverá ser avaliada por todos do programa e admite alterações, sugestões, etc. @minieradka  , se achar necessário efetuar mais alterações antes da revisão geral, sinta-se a vontade para fazer. Assim que der o ok, adiciono as versões na pasta de saída dessa issue. :D

**Comment by minieradka** [comment]
eu irei revisar aindaaaa

**Comment by kamila-rosa** [comment]
Olá, @minieradka como está a revisão do folder? Lembrando que segundo a reunião com a Elis, o prazo para revisão geral pelo PRACTICE era 23/08 e para mandar ao solicitante é amanhã, 30/08. Se precisar de ajuda, é só avisar.

**Comment by minieradka** [comment]
o folder já está disponível na pasta de saída, ressalvo que iremos enviar com a logo que conseguimos (porém está errada e iremos alterar assim que enviar essa versão a solicitante) peço que todos olhem o material e se tiverem sugestões comentar aqui no github @practice-uffs/todos

**Comment by minieradka** [comment]
já que não obtivemos feedback de ninguém, enviado ao solicitante através do e-mail aguardamos feedback agr pra finalizar essa solicitação

**Comment by morgana-mo** [comment]
Apontamentos da solicitante:
Por gentileza, solicitamos que sejam alterados os seguintes pontos:

Na capa:

Título: POLUIÇÃO, FLORA, PESCA, FAUNA E CAÇA

Retirar Chapecó, 2022 (será utilizado o panfleto em outros municípios além de Chapecó)


No texto pesca:

Retirar a frase: Em 2022, esse período tem início em 01 de outubro, seguindo até 31 de janeiro de 2023. (isso porque queremos utilizar os panfletos em vários anos).


No texto sobre madeira:

Na parte que fala: Vale ressaltar que, de acordo com as listas federal e estadual, a utilização da madeira não se aplica para espécies ameaçadas de extinção, como por exemplo o pinheiro araucária, o cedro e a imbuia. (retirar a vírgula entre pinheiro e araucária, tendo em vista que é a mesma árvore).

**Comment by morgana-mo** [comment]
Mais alterações:
Prezados boa tarde

Solicito outra alteração no texto do folder da PMA onde trata sobre a fauna. 

Onde está escrito:
Faça contato com o Instituto do Meio Ambiente (IMA), que é o órgão responsável pela gestão da fauna no Estado. O atendimento via Whatsapp acontece de segunda a sexta-feira, das 13h às 17h, através do número (48) 9.8808-3372.

Colocar:
Faça contato com o Instituto do Meio Ambiente (IMA) mais próximo de sua cidade ou com a Polícia Militar Ambiental através do 190 ou na unidade mais próxima.

**Comment by kamila-rosa** [comment]
Como já estava responsável por esta issue, farei as alterações. ;))

**Comment by kamila-rosa** [comment]
Fiz as alterações sugeridas pela solicitante. @minieradka estou te marcando caso queira fazer mais alguma revisão ou apontamento (a princípio dê uma olhadinha em como ficou o texto da capa do folder). Feito isto, insiro o trabalho na pasta de saída e podemos fazer este segundo envio à solicitante. ;) 
[Aqui está a página do folder no figma](https://www.figma.com/file/LRy42hR3hNv4GItaM1tiQ7/Panfleto-Policia-Ambiental-de-Chapeco?node-id=0%3A1).

**Comment by kamila-rosa** [comment]
Olá! Verifiquei que o último parágrafo do texto sobre "Fauna" (contido no frame "segundo envio") precisa de alguns ajustes na escrita. Peço que a @Eweline faça essa revisão se possível. Deixei um comentário na parte que precisa de revisão pontuando o que deve ser alterado. ;)) 
[Aqui está a página do folder no figma](https://www.figma.com/file/LRy42hR3hNv4GItaM1tiQ7/Panfleto-Policia-Ambiental-de-Chapeco?node-id=0%3A1).

**Comment by minieradka** [comment]
gente a solicitante não mandou o logo né? não podemos finalizar o envio com aquele logo gritante de errado, irei solicitar aqui, olhando agr o arquivos com mais calma (e com espirito livre rs ), achei outros detalhes que precisam de pequenos ajustes. Irei arrumando enquanto aguardamos q ela enviar a logo dai podemos finalizar

**Comment by kamila-rosa** [comment]
> gente a solicitante não mandou o logo né? não podemos finalizar o envio com aquele logo gritante de errado, irei solicitar aqui novamente, olhando agr os arquivos com mais calma (e com espirito livre rs ), achei outros detalhes que precisam de pequenos ajustes. Irei arrumando enquanto aguardamos q ela enviar a logo dai podemos finalizar

Concordo contigo @minieradka . Vamos aproveitar esse tempo em que a solicitante leva para mandar a logo e revisar os detalhes do folder. Eu e a a @Eweline já fizemos a alteração do parágrafo sobre a fauna e isso deve ser relatado à solicitante, pra que ela verifique se está de acordo (mas acredito que concordar). 
Também estamos vendo como referenciar as imagens nesse tipo de layout e levando em conta o design do folder. @minieradka peço apenas que me dê um auxílio com a transposição das cores para cymk, caso a referência das fotos leve mais tempo do que o planejado. :D

**Comment by morgana-mo** [comment]
Coloquei o logo na pasta de entrada @kamila-rosa

**Comment by minieradka** [comment]
> Coloquei o logo na pasta de entrada @kamila-rosa

tive que pedir pra alguem abrir no corel drawn e salvar pra gente kkk vou finalizar pra enviar

**Comment by minieradka** [comment]
> > Coloquei o logo na pasta de entrada @kamila-rosa
> 
> tive que pedir pra alguem abrir no corel drawn e salvar a gente kkk vou finalizar pra enviar

com o as arquivos editáveis que a solicitante enviou conseguimos identificar os fontes e cores oficiais da identidade, estou editando com as respectivas informações. Ficou bem melhor pq seguiu a identidade visual do projeto.

**Comment by kamila-rosa** [comment]
Já inseri todas as referências das imagens no folder.

**Comment by kamila-rosa** [comment]
Olá pessoal! Trocamos as fontes do folder e arrumamos mais algumas coisas. Peço a última revisão da @minieradka para então enviarmos ao solicitante. Ficou muito lindo, valeu toda dedicação! s2

**Comment by minieradka** [comment]
disponível na pasta de saída e finalmente enviado a solicitante. Obrigada @kamila-rosa pela dedicação e pelo trabalho final, vamos aguardar o feedback final para encerrar essa issue <3

**Comment by minieradka** [comment]
o material foi aprovado por email, parabéns aos envolvidos no projeto
