### ISSUE TITLE
ETAPA 0: Criação de formulário para professores

### ISSUE THREAD

**Issue by robisonjose** [practice-uffs/programa#1186]
Precisamos saber se os professores tem interesse em utilizar o estúdio do PRACTICE para gravação de vídeo aulas ou materiais que poderiam ser disponibilizados no canal do FAROL. 

Para conseguir observar isso, faremos um formulário que deverá ser respondido, em primeiro momento, presencialmente (os bolsistas da equipe mídia que ficarão encarregados a fazer essa pesquisa), e depois online via google forms. 

Posteriormente essa pesquisa pode ser incluída no projeto escrito.

**Comment by luizatonial** [comment]
Também encontrei essa dificuldade, fiz algumas modificações no arquivo... Mais tarde, com mais ideias, volto a trabalhar no arquivo.

**Comment by luizatonial** [comment]
@robisonjose dei continuidade ao documento, com certa dificuldade no item que marquei como 2, caso você consiga me ajudar nesse e verificar o restante...

**Comment by robisonjose** [comment]
Acho que tá tomando uma forma boa... Semana que vem a gente continua trabalhando nesse documento

**Comment by luizatonial** [comment]
achei que o material ficou bem interessante, por enquanto não teria outras ideias.

**Comment by MilenaPaz2020** [comment]
Olá, pessoal! Tomei a liberdade de fazer algumas contribuições no formulário que já está tomando um formato bem bacana. Analisem o que for pertinente.

**Comment by robisonjose** [comment]
@amandasegattob @MariaLuizaReviliau @MaNegrao 

Não esqueçam de fazer a revisão (até segunda 16/05) e nos ajudar a montar esse material.

**Comment by amandasegattob** [comment]
Fiz a revisão e deixei alguns comentários no documento. No geral, achei que está completo e que supre bem nossa demanda.

**Comment by MariaLuizaReviliau** [comment]
Revisão finalizada, o material está bem completo e explícito.

**Comment by luizatonial** [comment]
verifiquei as revisões e fiz alguns comentários

**Comment by robisonjose** [comment]
Essa issue está praticamente finalizada, então passei o formulário para a pasta do projeto e vou finalizar a issue.
