### ISSUE TITLE
Incrementos estéticos no Maker

### ISSUE THREAD

**Issue by GuilhermeGraeff** [practice-uffs/programa#1188]
Esta issue provém da issue #1068 

Responsáveis por esta issue: @GuilhermeGraeff e @minieradka 

Gerando a diagramação e o PDF de um dos manuais do PRACTICE, que está disponível na pasta de saída da issue #1068, notamos que algumas alterações podem ser feitas quanto à estética do material.

Objetivo da issue: conversar sobre o design do material, possíveis incrementos estéticos e a ferramenta a ser utilizada nesse processo.

O Maker se utiliza da ferramenta [Ibis](https://github.com/themsaid/ibis) para a geração do Livro Digital, ela é bastante flexível, mas só até certo ponto, acredito que ainda podemos melhorar na parte da estética.

**Comment by minieradka** [comment]
Olá Guilherme

Pesquisando e olhando a ferramenta ibis. Surgiram algumas ideias, dá pra disponibilizar grupos de letras para serem escolhidos. Podemos montar esses pacotes com fontes que combinam para títulos e subtítulos, como também fontes mais usadas para o texto todo.  

Olhando a maker, tem a opção de escolher o fundo acho que seria interessante colocar opção de fundo light ou dark. Assim como também dar a opção de escolher a cor do texto.

Seria interessante também se fosse possível adicionar imagem como logotipos dentro do arquivo, as vezes o solicitante tem esse logotipo.

Outro ponto que notei no arquivo do laravel é que nas partes do texto o código fica em outra cor, seria interessante que essas palavras em negritos pudesse ser escolhido a cor tbm, dando destaque a palavra.

Outro ponto, será que seria possível ter modelos de capa para os livros e inserir para serem selecionados. Acredito que a capa é oq chama atenção e o texto pode ser normal mesmo padrão abnt.  Os modelos poderiam ser desenvolvidos pela equipe 

essas foram algumas ideias que a equipe pensou na ultima reunião, além de pacotes de ícones e texturas que talvez não seriam viáveis.

**Comment by GuilhermeGraeff** [comment]
Boa tarde, tudo certo? Aqui vão as minhas considerações

```Pesquisando e olhando a ferramenta ibis. Surgiram algumas ideias, dá pra disponibilizar grupos de letras para serem escolhidos. Podemos montar esses pacotes com fontes que combinam para títulos e subtítulos, como também fontes mais usadas para o texto todo.```

 - Vou verificar mais a fundo a utilização de diferentes fontes, para disponibilizar como opção de uso.

```Olhando a maker, tem a opção de escolher o fundo acho que seria interessante colocar opção de fundo light ou dark. Assim como também dar a opção de escolher a cor do texto.```

 - A issue para desenvolvimento já foi criada no próprio repositório do Maker: [issue 68](https://github.com/practice-uffs/maker/issues/68)

```Seria interessante também se fosse possível adicionar imagem como logotipos dentro do arquivo, as vezes o solicitante tem esse logotipo.```

 - Tem as possibilidade de colocar uma imagem que foi compartilhada no google drive. 
"Imagens: semelhante ao texto-âncora, porém utiliza a exclamação![alt ou nome](link/URL da imagem)
Você pode hospedar a imagem no google drive e gerar o link de compartilhamento para todos com o link e utilizar este link."

```Outro ponto que notei no arquivo do laravel é que nas partes do texto o código fica em outra cor, seria interessante que essas palavras em negritos pudesse ser escolhido a cor tbm, dando destaque a palavra.```

 -  Acho que eu não entendi o que você quis dizer com 'arquivo do laravel', vou assumir que foi a diagramação da cartilha desenvolvida na outra issue e as palavras em negritos seriam os títulos, acredito que além dos padrões do Ibis de notice, warning e quote fica meio dificil de alterar a cor do texto, mas certamente vou dar mais uma olhada a fundo.

```Outro ponto, será que seria possível ter modelos de capa para os livros e inserir para serem selecionados. Acredito que a capa é oq chama atenção e o texto pode ser normal mesmo padrão abnt. Os modelos poderiam ser desenvolvidos pela equipe```

 - Acho que diferentes capas também seria bom, mas isto deve ser estudado mais a fundo, pois que pelo o que eu desenvolvi até agora acho que ficaria meio difícil de fazer isso acontecer. Mas vale dar uma olhada e ver mais possibilidades além das que eu vi...
