### ISSUE TITLE
Formação - Texto e escrita

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#119]
Tratar de questões gerais de elaboração e interpretação de textos.

Leituras interessantes:
[DICAS PARA ESCREVER UM BOM TEXTO.pptx.pdf](https://github.com/practice-uffs/programa/files/5190633/DICAS.PARA.ESCREVER.UM.BOM.TEXTO.pptx.pdf)
[gêneros textuais - Marcuschi.pdf](https://github.com/practice-uffs/programa/files/5190635/generos.textuais.-.Marcuschi.pdf)

**Comment by alessandrapedrotti** [comment]
Link para votação da data da formação para os interessados:
https://doodle.com/poll/cdx52z9vn9yrrdgx

**Comment by Dovyski** [comment]
Novamente precisamos de um integrante de cada equipe para participar dessa capacitação. Ela é importante para que todos entendam o que cada material representa em termos de conteúdo, exigências, linguagem, etc.

cc: @practice-uffs/todos

**Comment by MaNegrao** [comment]
Eu me disponibilizo para participar pelo mídia, meus horários já estão no doodle :D

**Comment by isabelirk** [comment]
Eu posso representar a equipe de conteúdo.

**Comment by isabelirk** [comment]
OBS: no arquivo produzido pela equipe de conteúdo que vc disponibilizou @alessandrapedrotti, meu sobrenome esta escrito errado, é sem o "i" no final

**Comment by VIF-Franca** [comment]
Doodle respondido...

**Comment by CleissonVieira** [comment]
Eu me disponibilizo para participar pelo dev

**Comment by alessandrapedrotti** [comment]
Considerando que já temos um representante de cada equipe e considerando também as datas que foram colocadas no doodle, criei esse novo para decidirmos a data final (baseado nas opções te tiveram mais votos no doodle anterior).

-> link para a nova votação: https://doodle.com/poll/2mu3rednpei28x9h
limitei para que os participantes possam escolher apenas uma opção para chegarmos a uma data definitiva.

**Comment by Dovyski** [comment]
@alessandrapedrotti eu gostaria de participar, mas teremos uma capacitação de Ciência da Computação nas 3 datas escolhidas. Existe a possibildiade de fazermos na semana seguinte às datas escolhidas?

**Comment by alessandrapedrotti** [comment]
Acredito que sim. Vamos fazer o seguinte, assim que todos os interessados votarem no doodle atual, mantemos o dia da semana escolhido e só passamos para a próxima semana. Ficou claro?

> @alessandrapedrotti eu gostaria de participar, mas teremos uma capacitação de Ciência da Computação nas 3 datas escolhidas. Existe a possibildiade de fazermos na semana seguinte às datas escolhidas?

Acredito que sim. Vamos fazer o seguinte, assim que todos os interessados votarem no doodle atual, mantemos o dia da semana escolhido e só passamos para a próxima semana. Ficou claro?

**Comment by VIF-Franca** [comment]
@alessandrapedrotti doodle respondido...

**Comment by alessandrapedrotti** [comment]
Pela votação no doodle fica definido que na quarta-feira (23/09) às 14 h teremos nossa formação de texto e escrita. 

vocês podem acessar a apresentação que eu preparei para a formação [aqui](https://docs.google.com/presentation/d/1r3v4jE3I-lYFQOEnSO0aXiE0V-n32ooX6hrMYd5qrec/edit#slide=id.p).
