### ISSUE TITLE
Elaboração dos post Con-Mídia - NOVEMBRO

### ISSUE THREAD

**Issue by MariaLuizaReviliau** [practice-uffs/programa#1194]
Essa issue tem por objetivo o desenvolvimento dos post da equipe Con-mídia para divulgação no instagram no mês de agosto.

**Comment by MariaLuizaReviliau** [comment]
Material pronto para revisão na pasta de entrada 
@practice-uffs/con-midia

**Comment by luizatonial** [comment]
fiz revisões no arquivo

**Comment by MariaLuizaReviliau** [comment]
Obrigada a todos pelas revisões! Resumi o máximo que consegui e removi os links. Acredito que agora está tudo ok!

**Comment by robisonjose** [comment]
fiz só mais uns comentários, mas acredito que esteja basicamente pronto. Acho que depois da correção da @luizatonial estará 100%.

**Comment by luizatonial** [comment]
verifiquei novamente acho que esta ok

**Comment by MariaLuizaReviliau** [comment]
muito obrigada a todos pelas revisões!
Material pronto para ser encaminhado para o design @JuliaGaboardiB

**Comment by robisonjose** [comment]
eu acredito que esse post vai ficar melhor se for um vídeo

o que acha @luizatonial @amandasegattob @MariaLuizaReviliau?

**Comment by amandasegattob** [comment]
Eu gostei da forma que ele está, não conheço muito dessas extensões e tal para dizer se seria mais "proveitoso" ser um vídeo. Acho que a Maria e a Luiza podem falar com mais prioridade.

**Comment by MariaLuizaReviliau** [comment]
Eu acredito que ficaria bem interessante se fosse em formato de vídeo, daria para fazer captura de vídeo da tela mostrando como utilizar a extensão e fazer narração no texto enquanto passa o vídeo de cada extensão. Em formato de post também fica muito bom e o conteúdo vai ser basicamente o mesmo, a diferença é que em reels talvez chame mais a atenção.

**Comment by julia-zanini** [comment]
revisado.
fiz umas propostas de alterações de texto, mas apenas para deixar o conteúdo mais fluido. achei muito bom!

**Comment by MariaLuizaReviliau** [comment]
Oii pessoal, fiz uma simples adequação no texto. Como vai ser narrado, deixei de uma forma que pareça mais uma conversa do que uma leitura. Se puderem dar uma revisadinha rápida, eu agradeço, pois pretendo fazer a gravação da narração hoje para a Amanda editar o vídeo amanhã.
@practice-uffs/con-midia

**Comment by julia-zanini** [comment]
pra mim ta ótimo

**Comment by luizatonial** [comment]
fiz comentários para deixar mais fluído

**Comment by MariaLuizaReviliau** [comment]
Muito obrigada a todos pelas revisões! A narração já está na pasta de entrada.

**Comment by amandasegattob** [comment]
A Maria colocou a gravação de tela na pasta. Vou dar início à edição amanhã e pretendo finalizar até segunda.

**Comment by amandasegattob** [comment]
@kamila-rosa vc faz a capa para esse vídeo também? O título é "EXTENSÕES, SITES E PLUGINS QUE AUXILIAM NA LIVE".

**Comment by kamila-rosa** [comment]
Capas criadas e inseridas na[ pasta de saída](https://drive.google.com/drive/folders/1Q3LErrce6XEufh9MgKSTBwyhO-B0uIux) da issue. @amandasegattob

**Comment by julia-zanini** [comment]
é para escolher uma das capas? se sim, eu gostei mais da capa 2, depois da 1

**Comment by MariaLuizaReviliau** [comment]
idem a Júlia kkkk gostei mais da capa 2

**Comment by kamila-rosa** [comment]
Olá! As capas com os títulos que irão aparecer no vídeo estão [nesta pasta](https://drive.google.com/drive/folders/1-rNro86p00ogSfCW7FgZusMOoAhI69Yp) do drive. Coloquei duas versões de layout para que vocês decidam qual fica melhor no vídeo (1-9 primeiro layout, 10-18 segundo layout). O mesmo vale para as outras capas criadas. :)) 
@amandasegattob

**Comment by amandasegattob** [comment]
Oi gente,fiz uma primeira versão do reels, vejam o que acham. O vídeo está na pasta de entrada. @practice-uffs/con-midia

**Comment by julia-zanini** [comment]
eu gostei bastante!

**Comment by robisonjose** [comment]
Eu acho que vai ter que mudar a forma da apresentação desse vídeo. Não da pra ver nada do que está sendo mostrado pois a gravação de tela fica muito pequena. 

Eu sugiro aumentar a tela para os locais que você quer demonstrar. Como se seguisse o ponteiro do mouse ou as partes principais que devem ser mostradas no vídeo. 

Um exemplo do que eu quero dizer é em 2:38, 3:22, 7:46 [desse vídeo.](https://www.youtube.com/watch?v=q8soabOr67E&t=1s&ab_channel=LetrasUFFSCampusChapec%C3%B3).

**Comment by amandasegattob** [comment]
Fiz as alterações, está a pasta de entrada. Vejam o que acham @practice-uffs/con-midia

**Comment by luizatonial** [comment]
eu não tinha revisado antes, mas acho que essa ideia de aproximar o vídeo do @robisonjose é interessante, só que achei que ficou meio estranho essa coisa de ir e voltar a visualização, tipo esse revezamento entre o aproximado e o menor. 
não sei exatamente o que fazer para melhorar ou contribuir para o vídeo... talvez se ele pudesse ser postado na horizontal ajudaria, não sei kkkkkkkk vamos esperar o comentário do resto do pessoal @practice-uffs/con-midia

**Comment by robisonjose** [comment]
Isso que você fez de aproximar o vídeo em alguns momentos deveria ser feito em todo o vídeo. Sempre tentanto mostrar na tela o que está sendo falado, ou seja, focando na parte importante da gravação da tela do PC.

**Comment by robisonjose** [comment]
Muitas partes do vídeo podem ser aproximadas, por exemplo quando está sendo procurado opções. Tem que tentar pensar em como fazer isso. Na verdade, da pra ficar com a tela aproximada sempre, sem ficar indo e vindo. Só mexendo na horizontal e vertical, e não no zoom. 

Posta uma versão dessa forma que eu falei pra gente ver como fica, pois do jeito que está não tá bom.

**Comment by MariaLuizaReviliau** [comment]
Olá, realmente fica complicado porque não bate as proporções do computador com o celular. Acredito que uma alternativa seja isso que o Robison citou, de deixar zoom sempre e ir apenas arrastando horizontal, vertical e tals. Outra opção seria fazer outra gravação com a câmera traseira do celular mostrando a tela do notebook, deixar o celular fixo, mas daí teria que gravar tudo novamente e acredito que a qualidade do vídeo não ficaria tão boa como captura de tela, não sei se daria para ler as coisas da tela do computador....

**Comment by julia-zanini** [comment]
eu concordo com todos... mas de fato dará bem mais trabalho ter que refazer a gravação...

**Comment by robisonjose** [comment]
@MariaLuizaReviliau acho que gravando a tela do computador vai ficar pior ainda. Acredito que fazendo esse lance do zoom seja melhor.

**Comment by amandasegattob** [comment]
Bom dia, coloquei uma terceira versão na pasta de entrada. Não consegui fazer o zoom em rolagem, então usei uma transição.

**Comment by robisonjose** [comment]
Opa, agora sim, ficou bem melhor. Parabéns. A ideia foi bem boa. 

Não sei quem fez a gravação, mas agora vendo mais de perto, dá pra ver que tem uma notificação de gravação bem no meio da tela. Dá proxima vez que não for utilizar o OBS para a gravação da tela, cuidar para não deixar essa notificação na tela (tem o botão de ocultar).

@luizatonial @MariaLuizaReviliau @julia-zanini revisem para a gente encerrar essa demanda.

**Comment by julia-zanini** [comment]
Eu gostei bastante! Para mim está ótimo. Parabéns!

**Comment by luizatonial** [comment]
achei BEMMM MELHOR! Parabéns meninas

**Comment by robisonjose** [comment]
A parte do mídia dessa issue está finalizada. @JuliaGaboardiB @morgana-mo podem colocar no calendário de postagem

**Comment by amandasegattob** [comment]
@morgana-mo @JuliaGaboardiB posso encerrar a issue?
