### ISSUE TITLE
Materiais para o site

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#120]
Nessa pasta -> https://drive.google.com/drive/u/0/folders/1HQ8xXPLlBfsx5XI6WaRl-3PfbsgzKCie, vocês encontrarão as versões finalizadas das cartilhas produzidas até então. Elas estão em PDF e prontas para irem para o site.

@Dovyski

**Comment by Dovyski** [comment]
Precisamos atualizar as cartilhas que estão no site. Vamos colocar elas em `cdn.uffs.cc`, não no repositório do site (arquivos binários ocupam muito espaço no git). @CleissonVieira, se estiver usando Windows, instalar o [WinSCP](https://winscp.net/eng/download.php) (se for Linux não precisa fazer nada) e me contatar no Telegram para receber instruções de acesso ao `cdn.uffs.cc`.

**Comment by CleissonVieira** [comment]
Cartilhas atualizadas e alocadas no `cdn.uffs.cc`.
