### ISSUE TITLE
Mapeamento de funções dos bolsistas

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#121]
É necessário criar um documento que contenha as descrições de funções de cada um dos bolsistas do PRACTICE.

**Comment by Dovyski** [comment]
@VIF-Franca vou precisar da tua supervisão nessa tarefa. [Esse arquivo] já lista os nomes de cada integrante do programa e suas equipes. Por favor, criar uma coluna nova `Descrição função` e alimentar ela com as informações que cada integrante postará nessa issue.

cc: @practice-uffs/todos postar nessa issue uma breve descrição de sua função na equipe (algo em torno de uma ou duas linhas).  Por exemplo, **"gerente de roteiro, responsável por organizar demandas de clientes em roteiros para outras equipes produzirem materiais"**. Acho que só a @practice-uffs/con-conteudo deve ter uma descrição completa, então podemos discutir o assunto para as demais equipes nessa própria issue.

**Comment by VIF-Franca** [comment]
Ok, @Dovyski. Creio que o arquivo é esse: *[Equipes](https://docs.google.com/spreadsheets/d/15kGGrER8UTGQhPIvGm2jHhs3pEO6f7gqISZgRyqpMKE/edit#gid=0)*

Vou incluindo conforme a galera ir comentando.

**Comment by CleissonVieira** [comment]
Desenvolvedor de software, um dos responsáveis pelo desenvolvimento de sites, aplicativos e sistemas para atender a demando do público em geral.

**Comment by alessandrapedrotti** [comment]
Líder da equipe con-material e responsável pela revisão textual dos materiais do programa (incluindo todas as produções de todas as equipes).

**Comment by MaNegrao** [comment]
Responsável de produção, principal operador das lives apoiadas e realizadas pelo PRACTICE, além de auxiliar operacional do estúdio e editor de áudio.

**Comment by isabelirk** [comment]
Trabalha com animação, produtora de conteúdo e redatora.

**Comment by estelavilasboas** [comment]
Membro da equipe do con-design, encarregada pela criação de artes, logos e outros materiais gráficos utilizados pelas demais equipes do programa. Presta apoio de revisão gráfica para con-material.

**Comment by andrewmsilva** [comment]
Membro da equipe dev, atuando como desenvolvedor de softwares, websites e aplicativos, além de liderar o projeto App PRACTICE.

**Comment by mariagelain** [comment]
Responsável pela diagramação dos produtos e triagem de material.

**Comment by Dovyski** [comment]
@mariagelain acho que tu pode colocar também "roterista", porque acho que a triagem inevitalmente envolverá uma organização material para a melhor mídia.

**Comment by vini2reis** [comment]
Trabalha com edição de vídeo e edição áudio

**Comment by VIF-Franca** [comment]
> Ok, @Dovyski. Creio que o arquivo é esse: _[Equipes](https://docs.google.com/spreadsheets/d/15kGGrER8UTGQhPIvGm2jHhs3pEO6f7gqISZgRyqpMKE/edit#gid=0)_
> 
> Vou incluindo conforme a galera ir comentando.

@Dovyski acabei de tentar editar novamente e agora não estou mais liberado para edição, apenas visualização...

**Comment by VIF-Franca** [comment]
Realiza atividades vinculados ao auxílio organizacional tais como: a) postagens e manutenção das redes sociais; b) apoio na organizar das issues; c) elaboração de cartilhas, guias e manuais. Também desempenha tarefas juntamente a con-midia, sendo as seguintes: a) edição e gravação de vídeo; b) edição de áudios e c) apoio operacional em lives vinculadas ao programa.

**Comment by lucasgalize** [comment]
Produtor de conteúdo (elaboração de vídeo e tutorial, imagem, cartilha, manual),  auxilio nas gravações do laboratório de mídias _campus_ Laranjeiras do Sul. Atendendo as demandas do con-material e con-mídia.

**Comment by VIF-Franca** [comment]
Todos já inclusa na planilha.
