### ISSUE TITLE
Criação dos cards do mês de julho

### ISSUE THREAD

**Issue by JuliaGaboardiB** [practice-uffs/programa#1210]
Essa issue tem como objetivo a criação da parte gráfica das postagens do mês de julho.

**Comment by JuliaGaboardiB** [comment]
Boa noite! Tem conteúdo novo para produção dos cards na pasta de entrada. @minieradka quando puder designar alguém para fazer. :D

**Comment by minieradka** [comment]
> Boa noite! Tem conteúdo novo para produção dos cards na pasta de entrada. @minieradka quando puder designar alguém para fazer. :D

ok Julia muito obrigada. Temos uma postagem já pronta, de transmissões ao vivo que pode ser postada agr ou na próxima semana, enquanto produzimos as postagens

**Comment by JuliaGaboardiB** [comment]
Boa tarde! Claro, @minieradka, vou adicionar no cronograma de postagens. :)

**Comment by Saene99** [comment]
Boa noite! @minieradka finalizei a primeira postagem e gostaria das suas considerações e revisão.

**Comment by kamila-rosa** [comment]
@JuliaGaboardiB Os cards sobre transmissões ao vivo estão na [pasta de saída](https://drive.google.com/drive/folders/1k0fdkngWvsBGL0-kTTfrE_Q9jdf0FEQ7) desta issue. Lembrando que ele era um post de maio que foi realocado para julho, com capa nova e, portanto, não consta no cronograma de postagens de julho que vocês colocaram na pasta de entrada. :))

**Comment by amandasegattob** [comment]
Oi gurias, os cards estão ficando lindos, parabéns pelo trabalho!
Só comentei ali no roteiro para ser feito qr code dos links, acho que fica mais acessível, pq na imagem não tem como clicar no link.

**Comment by kamila-rosa** [comment]
Olá pessoal! Os cards da postagem das _transmissões ao vivo_ já estão com os QR Codes inseridos ao invés dos links. Peço a revisão da @JuliaGaboardiB e da equipe @practice-uffs/con-midia [nesse link do Figma](https://www.figma.com/file/vKsmv9TiwF1RFERsOEs31T/Issues---Instagram?node-id=1085%3A312). Após a revisão eu insiro os cards na pasta de saída dessa issue. Notem que optei por retirar o link e deixar apenas o QR Code dos links, assim os cards não ficam tão poluídos... Caso achem necessário a inserção dos links + QR Codes, me avisem e faço a alteração. :D

**Comment by luizatonial** [comment]
podemos esperar a opinião da @amandasegattob e da @MariaLuizaReviliau que são responsáveis pelo projeto, mas acredito que fica bem melhor assim sem os links e com os qr codes, parabéns!

**Comment by JuliaGaboardiB** [comment]
Boa noite! Perfeito, @kamila-rosa! Ficou muito bom. Aguardo a @amandasegattob e a @MariaLuizaReviliau visualizarem também.

**Comment by amandasegattob** [comment]
Ficou ótimo!!! Parabéns pelo trabalho mais uma vez!

**Comment by MariaLuizaReviliau** [comment]
Revisado! Ficou muito melhor com o QR Code. Arrasou @kamila-rosa !!

**Comment by minieradka** [comment]
> Boa noite! @minieradka finalizei a primeira postagem e gostaria das suas considerações e revisão.

Estou revisando para ficar similar com os demais post do insta, ficou muito bomm @Saene99 parabéns

**Comment by robisonjose** [comment]
Ficou show

**Comment by morgana-mo** [comment]
Como sugerido pela Elis na reunião de líderes devem ser realizadas a adaptação dos conteúdos dos infográficos de fluxo de serviços em posts, eu os coloquei na pasta de entrada, e também deixei no gabarito dos posts, qualquer dúvida podem me chamar

**Comment by minieradka** [comment]
> Como sugerido pela Elis na reunião de líderes devem ser realizadas a adaptação dos conteúdos dos infográficos de fluxo de serviços em posts, eu os coloquei na pasta de entrada, e também deixei no gabarito dos posts, qualquer dúvida podem me chamar

oi alguém irá readaptar o texto ou a equipe pode fazer isso?

**Comment by minieradka** [comment]
> > Como sugerido pela Elis na reunião de líderes devem ser realizadas a adaptação dos conteúdos dos infográficos de fluxo de serviços em posts, eu os coloquei na pasta de entrada, e também deixei no gabarito dos posts, qualquer dúvida podem me chamar
> 
> eu acho melhor fazer uma issue específica para isso

vou criar

**Comment by minieradka** [comment]
post novo disponível na pasta peço que @practice-uffs/con-midia deem uma olhada

**Comment by julia-zanini** [comment]
Achei muito bom, parabéns!
só fiquei com uma dúvida, nos slides 6 e 7 tem a imagem do ícone do practice cortadinha e continuada no outro slide, mas eles não vão ficar seguidos um do outro no feed não é? vão ficar todos em uma postagem, certo? não entendi porque a imagem começa em um slide e termina no outro. eu sei que quando a pessoa passar de um slide ao outro da a impressão de continuidade do slide, mas não sei se gostei assim

**Comment by minieradka** [comment]
> Achei muito bom, parabéns! só fiquei com uma dúvida, nos slides 6 e 7 tem a imagem do ícone do practice cortadinha e continuada no outro slide, mas eles não vão ficar seguidos um do outro no feed não é? vão ficar todos em uma postagem, certo? não entendi porque a imagem começa em um slide e termina no outro. eu sei que quando a pessoa passar de um slide ao outro da a impressão de continuidade do slide, mas não sei se gostei assim

é efeito pra dar continuidade do carrossel, mas da trocar eu tinha tirado essa parte

**Comment by robisonjose** [comment]
Eu gostei de como ficou, não consigo imaginar como vai ficar no carrosel pra saber se vai ficar bom ou não o que vocês comentaram. 

Só tenho uma pergunta: em relação ao "slice 8", o conteudo não estar centralizado é proposital? 

No geral, achei o trabalho muito bom, parabéns!

**Comment by minieradka** [comment]
alterei novamente agr está na pasta

**Comment by robisonjose** [comment]
ué, mas agora não tem mais o slice 8

**Comment by julia-zanini** [comment]
> ué, mas agora não tem mais o slice 8

tem sim... ta lá. e parece estar centralizado sim

**Comment by robisonjose** [comment]
então fechou

**Comment by Saene99** [comment]
@minieradka o segundo card está finalizado no Figma, gostaria da sua revisão :)

**Comment by minieradka** [comment]
> @minieradka o segundo card está finalizado no Figma, gostaria da sua revisão :)

excelente trabalho! fiz alterações e adicionei na pasta de saída. @practice-uffs/con-midia se tiverem alguma consideração.

Senão, acredito que podemos fechar essa issue e migrar os posts prontos para issue de agosto para entrarem no cronograma visto que nenhuma das três foram postadas.

**Comment by robisonjose** [comment]
Eu já me perdi nos posts. Estamos falando do post de como gravar áudio? 

Se sim, só pediria para colocar letras maiscúlas em cada início de frase (ex: sempre que é colocado uma dica, a palavra "dica" é colocada com letra minúscula).

**Comment by minieradka** [comment]
> Eu já me perdi nos posts. Estamos falando do post de como gravar áudio?
> 
> Se sim, só pediria para colocar letras maiscúlas em cada início de frase (ex: sempre que é colocado uma dica, a palavra "dica" é colocada com letra minúscula).

ok eu que mudei isso tava maiúscula antes kkk

**Comment by robisonjose** [comment]
no slice 10 ainda tem uma frase em minúsculo. Deixei um comentário na imagem para que fique mais fácil de ver onde

**Comment by robisonjose** [comment]
o slice foi postado com a frase em minúsculo, não entendi o motivo
