### ISSUE TITLE
Criação do "guia" de curadoria para o App de Boas-Vindas

### ISSUE THREAD

**Issue by morgana-mo** [practice-uffs/programa#1223]
Essa tarefa tem como objetivo a elaboração de um "guia" para que sejam feitas revisões periódicas no app de Boas-Vindas, é preciso:

- [x] Catalogar quais informações que se tornam obsoletas semanal e mensalamente
- [x]  Catalogar quais informações que se tornam obsoletas semestralmente
- [x]  Catalogar quais informações que se tornam obsoletas anualmente.

Eu e a @JuliaGaboardiB cuidaremos dessa tarefa

**Comment by robisonjose** [comment]
Essa tarefa parece ter sido finalizada mas não foi fechada, então, movi o guia para a pasta "Projeto UFFS Boas Vindas" e fecharei a issue.
