### ISSUE TITLE
Correção de nomes

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#127]
Corrigir, em *TODAS* as ocorrências erros de digitação dos nomes dos colegas, tanto nos arquivos de trabalho, quanto nos que estão na pasta https://drive.google.com/drive/u/0/folders/1uSbwV0EYRQywqVKjY95EsDSd-kT9UmqS do drive, que correspondem aos documentos que estão disponíveis no site.

@mariagelain, depois de concluída, sinalizar nessa postagem para que os colegas da @practice-uffs/dev-web consigam colocar no site os arquivos corretos.

**Comment by CleissonVieira** [comment]
Assim que finalizado me marquem nessa Issue que verifico e altero essas informações do site, aguardo <3

**Comment by mariagelain** [comment]
Materiais devidamente corrigidos.
@CleissonVieira pode fazer a substituição dos materiais no site, quando finalizar pode fechar a issue.
->Link: https://drive.google.com/drive/folders/1uSbwV0EYRQywqVKjY95EsDSd-kT9UmqS

**Comment by CleissonVieira** [comment]
@mariagelain quais dos arquivos você editou e quais posso manter o mesmo? Ou foram todos que se encontram dentro dessas pastas?

![image](https://user-images.githubusercontent.com/29258164/92960837-a582fd00-f444-11ea-8215-dc89007ffc0b.png)

**Comment by mariagelain** [comment]
@CleissonVieira foi necessário alterar todos os arquivos que já estão dentro da pasta cartilhas.

**Comment by CleissonVieira** [comment]
Concluído, porém não existe no site criado sobre esses temas na imagem abaixo, as cartilhas estão apenas armazenadas.
@alessandrapedrotti avisa caso precise criar para os usuários verem no site essas cartilhas também

![image](https://user-images.githubusercontent.com/29258164/92965341-03671300-f44c-11ea-888c-cdbe3160f78c.png)

**Comment by Dovyski** [comment]
Sim, @CleissonVieira, esses dois materiais precisam ser colocados no site. Tu pode colocar subseções na página de "Recursos". Por exemplo, "Cartilhas" com os arquivos das cartilhas, e "Dicas" com eses dois arquivos do comentário acima.

A @alessandrapedrotti ou a @mariagelain podem sugerir um nome (ou organização melhor) para as seções.

**Comment by alessandrapedrotti** [comment]
> Sim, @CleissonVieira, esses dois materiais precisam ser colocados no site. Tu pode colocar subseções na página de "Recursos". Por exemplo, "Cartilhas" com os arquivos das cartilhas, e "Dicas" com eses dois arquivos do comentário acima.
> 
> A @alessandrapedrotti ou a @mariagelain podem sugerir um nome (ou organização melhor) para as seções.

Acredito que as seções podem ser nomeadas dessa maneira mesmo, aí conforme vamos adicionando novos materiais, criamos mais seções se for necessário.

**Comment by CleissonVieira** [comment]
Sim, conversei com a Ale, logo acrescentarei no site essas duas cartilhas que ainda não se encontram

**Comment by CleissonVieira** [comment]
Já está no site. Mas está me dando gatilho uma coisa hehe
Ignorem se acham que é frescura hehhe

Na `Cartilha de edição de imagem: ferramenta Photopea` o `PRACTICE` e Título está um pouco acima do padrão das demais. 

![image](https://user-images.githubusercontent.com/29258164/93115996-115aa500-f693-11ea-9363-025aa4a9e8a9.png)

Quem poderia arrumar isso? 

Mas a princípio essa ISSUE está concluída. Só preciso saber se vai ser alterado isso para então alterar no site ou mantemos assim e fechamos a ISSUE
