### ISSUE TITLE
Gravação no estudio Chapecó (15/09) - 9h - 11h30m

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/programa#128]
Gravação com o prof. Fabrício Maia do curso de Administração
e com a profa. Tatiane Maia do curso de Administração

Peço que @MaNegrao, @mariagelain e @alessandrapedrotti  combinem quem pode atender a demanda.

**Comment by lcaimi** [comment]
O professor pode dar carona. Saida em frente ao BB do centro (próximo a Havan).

**Comment by MaNegrao** [comment]
Eu creio que posso ir, a Ale a Maria foram da ultima vez.

**Comment by alessandrapedrotti** [comment]
> Eu creio que posso ir, a Ale a Maria foram da ultima vez.

Se for necessário, eu posso acompanhar.

**Comment by lcaimi** [comment]
Vou passar o teu contato para o professor @MaNegrao. Para combinarem certinho.

**Comment by MaNegrao** [comment]
Fechado então, creio que se a Ale puder me acompanhar vai ser melhor, sabendo as configurações e tudo mais utilizado na ultima gravação :D

**Comment by lcaimi** [comment]
Pode ser @alessandrapedrotti ?

**Comment by alessandrapedrotti** [comment]
> Pode ser @alessandrapedrotti ?

Pode. Combinado.

**Comment by vini2reis** [comment]
Uma sugestão:
Vocês podem gravar o áudio um pouquinho mais alto

**Comment by MaNegrao** [comment]
Gravações concluídas, o professor irá dar continuidade nas aulas em novo agendamento.
