### ISSUE TITLE
Habilitar computador para acesso remoto e auxílio em Lives

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/programa#129]
Habilitar computador do Programa para acesso remoto e lives

- [x] Instalar plugin do Chrome @phdmauricio 
- [x] Passar credenciais de acesso @phdmauricio para @MaNegrao 
- [x] Instalação dos programas e templates para lives do Practice @MaNegrao 
- [x] Fazer teste de Live com vários participantes para verificar sincronismo e qualidade

**Comment by MaNegrao** [comment]
O PC está com todos os programas e o template instalado para execução das lives :). Estou utilizando ele em todas desde então

**Comment by lcaimi** [comment]
Plugin disponível no link: https://remotedesktop.google.com/?pli=1

**Comment by phdmauricio** [comment]
Fazemos isso amanhã cedo. Hoje estou envolvido com gravação das minhas aulas.

**Comment by phdmauricio** [comment]
DESKTOP-REMOTO-CASA-MAURICIO
150620

**Comment by MaNegrao** [comment]
@lcaimi podemos usar essa issue e se o mauricio puder, o computador que está lá, para os testes remoto de quarta de manhã?

**Comment by MaNegrao** [comment]
O teste será realizado na quarta-feira dia 30/09 as 10h

**Comment by MaNegrao** [comment]
Testamos o obs com materiais e sincronia no youtube, a principio está tudo operante e funcionando de forma extremamente satisfátoria, poderiamos até tentar gerenciar uma live de menor porte via remoto.

**Comment by lcaimi** [comment]
O link e as credenciais de acesso são fixas?
Poderia colocar as informações de acesso no arquivo de acessos do Practice?

**Comment by MaNegrao** [comment]
Pelo remote desktop do google, as credenciais não são fixas, tem que ser gerado toda vez que inicia um acesso remoto, a gente pode estudar uma outra plataforma que tenha as credenciais fixas se for o caso

**Comment by lcaimi** [comment]
Acho que vale a pena encontrar uma alternativa permanente. Credenciais por acesso são boas para segurança, mas serão uma dor de cabeça no dia a dia. Uma credencial fiza permitirá a realização de eventos mesmo que não houver ninguem no local. Apena o PC ligado e conectado.

**Comment by MaNegrao** [comment]
Vou estudar alguma ferramenta que possibilite isso

**Comment by MaNegrao** [comment]
Então, há algumas ferramentas, mas todas são pagas, e tem a da própria Microsoft. 
Primariamente eu não tinha conseguido usar ela, mas tem um passo a passo correto pra se fazer. A única coisa necessária pra usar essa ferramenta da Microsoft é que o PC tenham Windows 10 pro, e no caso dos 3 PCs de Chapecó, eles tem :D Eu fiz o teste com meu notebook pessoal e deu tudo certo, nessa ferramenta podem ser criados usuários com senha e e-mail etc e realizar o acesso por ele.

Acho que vale a gente fechar essa isue como estudo e abrir uma pra fazer um videozinho curto explicando como conectar remotamente.

**Comment by MaNegrao** [comment]
A conexão e o teste foram concluídos, como disse no ultimo comentário, seguimos em uma nova issue para criação de um material simples de instrução de como conectar através do Remote Desktop da Microsoft
