### ISSUE TITLE
[Cartilha] Ferramentas de edição de imagens

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/programa#13]
É necessário montar uma cartilha documentando explicando as ferramentas e tecnologias que utilizamos e recomendamos. Ferramentas de edição de imagens são necessárias e existem várias possibilidades. Elas devem ser adicionadas à cartilha devidamente explicadas (download, instalação, uso, etc).

Dentre elas, estão:

- [Photopea](https://www.photopea.com/)
- [Pixlr](https://pixlr.com/)
- [Google Slides](https://www.google.com/slides/about/)
- [Google Drawing](https://docs.google.com/drawings)

**Comment by lucasgalize** [comment]
Olá Andrew, sobre está tarefa, fazer uma cartilha em forma de imagem? (sendo autoexplicativo?)
 Ou uma cartilha no formato DOC?

**Comment by lucasgalize** [comment]
Cartilha de edição de imagens em andamento.

**Comment by lucasgalize** [comment]
Cartilha edição de imagem - Photopea
[Ferramenta de edição de imagem.pdf](https://github.com/practice-uffs/programa/files/4861454/Ferramenta.de.edicao.de.imagem.pdf)

[Ferramenta de edição de imagem.docx](https://github.com/practice-uffs/programa/files/4861455/Ferramenta.de.edicao.de.imagem.docx)

**Comment by lucasgalize** [comment]
Cartilha feita, peço revisão e avaliação @Dovyski.

**Comment by lcaimi** [comment]
> Cartilha feita, peço revisão e avaliação @Dovyski.

@lucasgalize, converte para o GoogleDocs dentro do repositório no Drive, nos moldes discutidos na reunião de 02/07/2020.

**Comment by Dovyski** [comment]
O conteúdo está ótimo, parabéns! Minhas requisições:

- [ ] Utilizar fonte textual `Roboto` para todo o documento, não `Arial` ou `Times New Roman`.
- [ ] O rodapé e cabeçalho atuais estào ótimos com a logo, mas precisamos de algum texto, em tamanho bem pequeno, com algo como:

```
Universidade Federal da Fronteira Sul - UFFS
Programa de Ampliação e Consolidação de Tecnologias e Inovação no Contexto Educacional - PRACTICE
https://practice.uffs.edu.br
```

**Comment by lucasgalize** [comment]
Ok Professor @Dovyski

**Comment by Dovyski** [comment]
Transformar o documento para `.pptx` (Power Point), não `.docx` (Word).

**Comment by lucasgalize** [comment]
Todos os requezitos:
- [ ] Documento em pptx;
- [ ] Rodapé;
- [ ] Fonte.

**Comment by alessandrapedrotti** [comment]
**Primeira leitura de revisão textual feita no dia 15/07.**

Apontamentos
[] A cartilha precisa ter o esquema de cores do programa;
[] Sugestão: Seria interessante seguir o desing da tarefa #28, elaborada pelo Vinícius França, assim todos os materiais desse tipo do programa ficarão padronizados.
[] Sugestão: Não sei se é obrigatório, porém acho que o material vai ficar muito mais legal estiver em formato vertical. Dessa forma as imagens e textos ficarão melhor distribuídos na página e poderemos reduzir o número de páginas.

**Comment by elisribas** [comment]
Revisão pedagógica realizada hoje. 
@lucasgalize veja as solicitações de alterações diretamente no arquivo.

Minhas considerações gerais. 
- Podemos usar os slides na horizontal, mas vamos padronizar para que todos sejam do mesmo tamanho. Para tanto, ao abrir um novo arquivo de Apresentação do Google, ir no Menu Arquivo > Configuração da Página > Na caixa de opções, selecionar "Padrão 4:3". Assim todos os slides de todos os materiais criados neste recurso, serão do mesmo tamanho.
- Sempre criar arquivos de textos, slides e, quando possível, de imagem, diretamente no Google Drive, conforme reunião de 10.07;
- Padronizar o tipo de seta utilizado, em alguns momentos aparecem mais finas, outros mais espessas, dá para criar uma seta apenas e depois copiar e colar sempre que precisar usá-la novamente. Aí é necessário apenas posicioná-la (girá-la) para posição desejada. Fica mais padronizado. 
- Concordo que as cartilhas devam seguir o modelo já criado pelo Vinicius. Nós da @practice-uffs/con-material trabalharemos em modelos para disponibilizar para vocês ainda essa semana.

No mais, está excelente. 

❥❥

**Comment by alessandrapedrotti** [comment]
Revisão textual finalizada no dia 21/07.

Deixei um comentário no documento que eu gostaria que o @lucasgalize veja.

@mariagelain você pode dar uma olhada e fazer teus apontamentos para que o material se enquadre no modelo de cartilha que você desenvolveu?

O material está bem explicativo, acredito que será muito útil.

**Comment by mariagelain** [comment]
Material revisado conforme os templates que foram produzidos.

Peço para que o @lucasgalize troque as imagens que não estão em uma boa resolução e acredito que após essa alteração podemos encaminhar para que a gerência aprove.

**Comment by alessandrapedrotti** [comment]
Agora sim o texto está 100%. Fiz uma leitura rápida a pedido da Maria e consertei alguns errinhos que tinha  deixado passar na leitura anterior.

Acredito que a única pendencia desse material é a alteração das imagens que já foi solicitada.

**Comment by lucasgalize** [comment]
Imagem alteradas.
