### ISSUE TITLE
Roteirização da Serie de Vídeos tutoriais sobre Shotcut

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#130]
Essa issue está relacionada à roteirização da série de vídeos tutoriais sobre o software de edição Shotcut. O tutorial é, basicamente, uma recriação em português desse tutorial disponível em inglês:

https://www.youtube.com/watch?v=4bcw9_zXEuA&feature=youtu.be

Acho que podemos replicar o mesmo modelo: 6 vídeos, cada um deles apresentando uma das funcionalidades do shotcut (igual o tutorial de referência). Não precisamos filmar a pessoas que fala, apenas mostrar a tela e um audio de narração. Também não acho que precisamos de toda a "energia" do apresentador original (afinal ele é Youtuber). Podemos ter uma narração mais calma e focada, do tipo "Clica aqui, depois aqui, e isso acontece. (pausa). Seguindo, se fizermos tal...".

Os bolsistas podem ir ajustando em conjunto a roteirização dos pontos importantes do vídeo, quando tivermos os roteiros finalizados podemos dar inicio a produção desses vídeos. Os vídeos não necessariamente precisam esperar todos os roteiros ficarem prontos, logo se o roteiro do vídeo 1 já estiver pronto, mas os demais não, o trabalho pode ser feito em paralelo, a produção dos vídeos e a continuidade da roteirização. 

O modelo de roteiro já está na pasta de Entrada.

- [x] #131 - Vídeo 1
- [x] #132 - Vídeo 2
- [x] #133 - Vídeo 3
- [x] #134 - Vídeo 4
- [x] #337 - Vídeo 5
- [x] #338 - Vídeo 6

[Pasta Drive](https://drive.google.com/drive/folders/1H2IjtUFoiP322VrNZxF5hxC9AxZqEP-B)

**Comment by Dovyski** [comment]
Qual o status dessa tarefa?

**Comment by MaNegrao** [comment]
@vini2reis tu pode dar continuidade à series de vídeo do shotcut, se preferir pode refazer o primeiro também.

**Comment by MaNegrao** [comment]
@rafaguilman divide com o Vinicius e vocês dois em conjunto podem definir o tema e a continuidade desses vídeos

**Comment by Dovyski** [comment]
> se preferir pode refazer o primeiro também.

Concordo sobre isso. O Lucas (autor original do vídeo) e eu conversamos sobre isso quando ele fez essa versão. A narração não está tão fluída e o vídeo ficou um pouco longo. A ideia é ser calmo na narração, mas bem mais direto. Talvez seja legal a @practice-uffs/con-conteudo ajudar com  a objetividade do roteiro.

**Comment by rafaguilman** [comment]
Opa Legal vou fazer aqui  e ja repasso algo

**Comment by alessandrapedrotti** [comment]
> > se preferir pode refazer o primeiro também.
> 
> Concordo sobre isso. O Lucas (autor original do vídeo) e eu conversamos sobre isso quando ele fez essa versão. A narração não está tão fluída e o vídeo ficou um pouco longo. A ideia é ser calmo na narração, mas bem mais direto. Talvez seja legal a @practice-uffs/con-conteudo ajudar com a objetividade do roteiro.

Podemos trabalhar em conjunto sim! Nesse caso, acho que vai ficar melhor se os meninos @rafaguilman e @vini2reis trabalharem em um roteiro e nós da con con refinarmos ele.

**Comment by MaNegrao** [comment]
Vou converter essa issue para roteirização desses vídeos e depois quando os vídeos tiverem separados por roteiros e tópicos damos continuidade à produção dos vídeos.

**Comment by rafaguilman** [comment]
Nesse caso primeiro os roteiros e após isso a produção dos vídeos?

**Comment by MaNegrao** [comment]
Essa é a ideia, montar um roteiro pra cada vídeo definindo o que vai ser abordado no vídeo etc. Vocês podem olhar os roteiro da issue #212 como base de como organizar etc. Mesclando o vídeo de 40 min original e o roteiro de vocês.

**Comment by rafaguilman** [comment]
Nesse caso faremos os roteiros e depois revisados isso??

**Comment by MaNegrao** [comment]
Isso, vocês fazem os roteiros, o pessoal do con-con revisa e daí pode
começar a gravação e edição dos vídeos

Em ter, 17 de nov de 2020 22:18, rafaguilman <notifications@github.com>
escreveu:

**Comment by vini2reis** [comment]
Coloquei a vinheta de abertura e a animação de créditos que serão usados nos vídeos na pasta dessa issue.

**Comment by MaNegrao** [comment]
Roteiros concluidos,, a produção continua nas issues referentes
