### ISSUE TITLE
Criar animação base para ilustrar conteúdo de ensino

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#135]
Utilizar o WickEditor para criar uma animação semelhante a do tempo `36s` [desse vídeo](https://www.renderforest.com/gallery/2092):

![image](https://user-images.githubusercontent.com/512405/92925354-c598c900-f410-11ea-95d0-611891ea7330.png)

A ideia não é criar todos os detalhes dessa animação, mas sim o seguinte:

* Um personagem à esquerda da tela, fazendo qualquer tipo de movimento. Ver guia do PRACTICE na parte de artes para isso. Sugiro usar os personagens do [Kenney Assets](https://www.kenney.nl/assets).

* À direita, um quadro ou moldura em branco, que pode ser utilizada pela equipe no futuro para "injetar" conteúdo durante a edição de outros vídeos.

**Comment by isabelirk** [comment]
Olá, temos uma versão da animação pronta. Aguardo homologação ou possíveis ajustes.

![My Project10-1-2020_6-39-53PM](https://user-images.githubusercontent.com/31291959/94866431-b3a9b500-0415-11eb-93ff-5dcbb5f9b2e2.gif)

**Comment by Dovyski** [comment]
Está ótimo, Isa! A ideia era utilizar o software e se ambientar com ele para possível capacitação do resto da equipe.
