### ISSUE TITLE
Gravação estúdio Chapecó - Prof Aline C. Cavalheiro - Letras - (18/09) - 14h

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/programa#136]
Gravação no Estúdio Chapecó para profa. Aline Cassol Daga Cavalheiro do curso de Letras.

@MaNegrao, @alessandrapedrotti , @mariagelain

**Comment by alessandrapedrotti** [comment]
Eu gostaria de ir nessa gravação, porque preciso conversar com a profª Aline a respeito dos produtos que serão feitos para o curso de Letras.

@MaNegrao você pode me acompanhar? Não me garanto a lidar com o estúdio sozinha.

**Comment by MaNegrao** [comment]
Creio que consigo ir sim Ale. Tranquilo

**Comment by lcaimi** [comment]
O prof. @phdmauricio vai com os bolsistas até o Campus.
Acertem os detalhes da logística. 
@alessandrapedrotti, @MaNegrao

**Comment by lcaimi** [comment]
Gravação cancelada pelo solicitante.
