### ISSUE TITLE
Vinheta - Curso de Letras

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#137]
Criar vinheta padrão para os materiais do Curso de Letras.

Serviço solicitado pela coordenação do curso de letras - campus Chapecó.

A vinheta deve estar de acordo com a identidade visual da tarefa #138 

Pasta do drive -> https://drive.google.com/drive/u/0/folders/1CEudMw1CpPV83rESgIgeJyQKNvDOeROU

Ferramenta: WickEditor.

**Comment by alessandrapedrotti** [comment]
Após reunião com a coordenação do curso, ficou decidido que:

- [ ] A vinheta deve ter o símbolo do curso, já elaborado pela @practice-uffs/con-design, preenchido pela cor lilás. A Profª Morgana deu a ideia de que na vinheta as letras que formam as palavras "Curso de Letras - Português e Espanhol" estivessem inicialmente embaralhadas e fossem se organizando para a ordem correta.

- [ ] Além dessa ideia, podemos apresentar a opção com uma mão segurando uma caneta que vai escrevendo o nome do curso (não sei se expliquei da melhor forma).

- [ ] Também será necessária a elaboração de uma página de créditos para os vídeos, seguindo o esqueleto das páginas de créditos do PRACTICE, mas que vá lentamente desaparecendo.

Ademais, as vinhetas produzidas devem estar de acordo com as seguintes exigências:
 - Cores: lilás, branco, cinza e prata;
 - Fontes limpas e fortes (evitar fontes cursivas ou floreadas);
 - Evitar símbolos marcados ou caricatos, como por exemplo: corujas.

**Comment by MaNegrao** [comment]
@vini2reis e @estelavilasboas Eu conversei com a @alessandrapedrotti e nos decidimos que por conta da nossa equipe extremamente reduzida de midia no momento e a nossa falta de experiencia com animações, poderiamos fazer uma animação de vinheta mais simples para os videos iniciais e deixarmos a vinheta elaborada ser desenvolvida com mais pessoal. 

Portanto, eu queria saber de voces como pode ser essa vinheta mais simples e como a gente pode fazer ela

**Comment by alessandrapedrotti** [comment]
Após reunião com a solicitante, ficou decidido que:
A vinheta produzida será mais simples, aos moldes da vinheta do PRACTICE, porque por questões de tempo, não será possível a produção da ideia original.
Será utilizado o site [LottieFiles ](https://lottiefiles.com/)para facilitar o processo de animação.

**Comment by estelavilasboas** [comment]
Primeira versão disponível na [pasta](https://drive.google.com/drive/u/0/folders/1CEudMw1CpPV83rESgIgeJyQKNvDOeROU).

**Comment by MaNegrao** [comment]
Com a aprovação realizada, já posso repassar para inclusão nos videos

**Comment by alessandrapedrotti** [comment]
> Com a aprovação realizada, já posso repassar para inclusão nos videos

Já pode mandar inserir!

**Comment by MaNegrao** [comment]
beleza, já foi passado para os membros do midia a vinheta.
