### ISSUE TITLE
Identidade visual - curso de Letras Chapecó

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#138]
Nos foi solicitado, pela coordenação do curso de Letras - Campus Chapecó: uma arte/identidade visual para os materiais do Curso de Letras, a exemplo da que foi desenvolvida para o Curso de Ciências da Computação.

Pasta do drive -> https://drive.google.com/drive/u/0/folders/1Mxtm8ygvNWXX3Z6BsOi3XQ-EndqZ1OJ5

Informações do cliente:

> O Curso não possui nada definido, apenas o conjunto de assinaturas visuais disponível em: https://www.uffs.edu.br/institucional/reitoria/diretoria_de_comunicacao_social/identidade_visual, na pasta do Curso de Letras, Campus Chapecó. 
> 
> Acho que podemos manter algum elemento nos tons da UFFS, como manifestação que tivemos na reunião. Nenhum outro registro foi feito quanto a cores. Mas também podemos pensar em usar uma assinatura do Curso que está no link acima, o que já mantém a identidade visual institucional, e, na identidade do curso, podemos trabalhar com a cor lilás (com branco), que costuma ser associada às Letras - é uma identidade de área. Outro elemento que identifica o curso de Letras é a flor de lis.
> 
> Acredito que a equipe pode ficar livre para uma proposta, considerando essas informações.

**Comment by Dovyski** [comment]
Solicitei do cliente algumas informações sobre cores e um eventual logo que exista. Informo assim que obtiver resposta.

**Comment by Dovyski** [comment]
Atualizei a issue com a informação recebida do cliente.

**Comment by alessandrapedrotti** [comment]
Após reunião com a coordenação do curso, informo que:

 - O símbolo já desenvolvido foi aprovado;
 - A paleta de cores desenvolvida foi recusada.

Será necessário:

- [ ] Desenvolver uma nova paleta de cores com tons de lilás, branco, cinza e prata. 

- [ ] Escolher fontes que sejam limpas e fortes, sem letras cursivas ou floreios.

- [ ] Elaborar uma pequena descrição do processo criativo do símbolo elaborado. Basicamente uma explicação do porquê os elementos presentes (flor de lis e caneta tinteiro) foram escolhidos. Ps: vou ajudar nessa tarefa.

Ademais, a coordenadora do curso também pediu que evitássemos o uso de elementos marcados ou caricatos, como corujas ou a imagem de autores famosos.

**Comment by mariagelain** [comment]
A resposta da coordenação do curso ao formulário de identidade visual:

-> Estilo de logomarca:

- [ ] Moderno e simples

-> Características do logotipo:

- [ ] Moderna, elegante e formal

-> Simbolo que representa o curso

- [ ] Flor de lis 

-> Paleta de cores

- [ ] Cores suaves e frias 

-> Cor que lembre o curso

- [ ] Lilás

-> Opcionais 

- [ ] Marca d'água

- [ ] Padrão com o símbolo e/ou logomarca 

O que não ter:

- Logotipo com características conservadora, delicada, retrô extravagante e romântica

- símbolo que não deve estar na logomarca: coruja

**Comment by alessandrapedrotti** [comment]
Reunião de apresentação do progresso com a solicitante no dia 08/10 às 18h, via Google Meet.

**Comment by estelavilasboas** [comment]
A [apresentação](https://docs.google.com/presentation/d/1PRbCb7aLxuRuwT9Vkp8SzjUQ_SjzSZdwUubB1DYr48k/edit#slide=id.g53b5cab132_0_0) da segunda versão já está finalizada e na pasta.

**Comment by alessandrapedrotti** [comment]
Identidade aprovada em reunião com a solicitante.

**Comment by alessandrapedrotti** [comment]
Como a ID foi aprovada pela solicitante e seus elementos serão disponibilizados para uso, essa issue será fechada assim que a @estelavilasboas disponibilizar os elementos na pasta saída da pasta da tarefa no drive.

**Comment by estelavilasboas** [comment]
Todos as imagens exportadas já estão disponíveis na pasta saída.
