### ISSUE TITLE
Criar template de slide - curso de letras

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#139]
Desenvolver templates de capa, um slide de conteúdo e um slide de finalização baseado no modelo já existente de manual do PRACTICE em concordância com a identidade visual que será criada para o curso de letras de chapecó.

@mariagelain seria interessante se você desenvolvesse também um template com a identidade visual do PRACTICE para necessidades futuras.

Pasta do drive -> https://drive.google.com/drive/u/0/folders/13sFE1Q_t-8nkXAKBbKpj0oKvc64vFM8L

**Comment by alessandrapedrotti** [comment]
Conforme discutido em reunião, o template seguirá a estrutura da identidade visual da universidade, em concordância com as cores e fontes escolhidas para o curso de letras.

**Comment by mariagelain** [comment]
Resposta da coordenação do curso ao formulário de identidade visual:

-> Criar templates para:

- [ ] Slide

- [ ] Cartaz

- [ ] Panfleto

-> Informações que devem constar no template

- [ ] Nome do curso

- [ ] Símbolo do curso

- [ ] Nome da universidade

**Comment by alessandrapedrotti** [comment]
Reunião de apresentação do progresso com a solicitante no dia 08/10 às 18h, via Google Meet.

**Comment by alessandrapedrotti** [comment]
Os templates que foram aprovados (e consequentemente) serão disponibilizados à solicitante são: template de capa, template de créditos (com a adição do logo da UFFS), template de página 02 e template de página 05.
Assim que a alteração na página de créditos for feita e os materiais disponibilizados na pasta de saída da pasta da tarefa no drive pela @mariagelain , essa issue será fechada.

**Comment by mariagelain** [comment]
Template está pronto para uso.

Instruções de uso para salvar e editar o template:

- Use uma cópia do arquivo para que caso tenha algum erro ou desconfiguração você terá o arquivo original com a formatação original.

- Use o google apresentações para manusear o template, pois nele já há espaços para inserir o texto.

- Para abrir a página de capa do template selecione o layout: Capa.

- Para abrir página de conteúdo do template selecione o layout: Título e corpo e/ou Título e corpo 2.

- Para abrir a página de créditos do template selecione o layout: Créditos. 

O template está nesta [pasta](https://drive.google.com/drive/folders/1iwYpgiueBn5YNPwZIx0esebi3Ej8pSip) no formato apresentações google e também em pptx.
