### ISSUE TITLE
Postar equipe nas redes sociais 

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#140]
Conforme criado na issue #62 será necessário postagem de cada membro conforme o documento do Drive [.](https://docs.google.com/spreadsheets/d/1N4GFZxmLwfqiL3chCGzS4x5fzd9WFcc5D8eUCdMzAPc/edit#gid=0)

- [x] Criar cronograma @practice-uffs/ger-auxilio ;

- [x] Editar imagem de todos os membros @practice-uffs/con-design e/ou @practice-uffs/con-conteudo; 

<img width="415" alt="92922383-240f7880-f40c-11ea-9541-ad9d7828fd27" src="https://user-images.githubusercontent.com/66980370/93161340-c10e3200-f6e8-11ea-8799-6bff15df48b1.png">

**Comment by VIF-Franca** [comment]
CRONOGRAMA

- [ ] Maurício Fernando Bozatski -----> 16/09
- [ ] Fernando Bevilacqua -------------> 18/09
- [ ]  Luciano Lores Caimi -------------> 21/09
- [ ] Alessandra Pedrotti --------------> 23/09
- [ ] Andrew M. Silva ------------------> 25/09
- [ ] Cleisson Vieira Raimundi --------> 28/09
- [ ] Estela Vilas Boas -----------------> 30/09
- [ ] Isabeli R. Reik --------------------> 02/10
- [ ] Lucas Ferreira --------------------> 05/10
- [ ] Maria Gelain ---------------------> 07/10
- [ ] Matheus D. Negrão -------------> 09/10
- [ ] Vinicius dos Reis ----------------> 12/10
- [ ] Vinícius França Alves -----------> 14/10

**Comment by estelavilasboas** [comment]
[Pasta](https://drive.google.com/drive/folders/1sj2UYI8D5qwyqzz9-l5pPkHN8BrWhDF6)

**Comment by VIF-Franca** [comment]
Link com o texto: https://docs.google.com/spreadsheets/d/1PvuDG2VYJPXou-BsCPy_KgsX7Y-sf2GyemNaSdinB1g/edit#gid=0

**Comment by VIF-Franca** [comment]
- [ ]  Amanda Segatto Bisognin  ----> 

- [ ] Ana Carolina Morigi da Cruz Silveira

- [ ] Brenda Ellen de Sousa Reis

- [ ] Claudineia Vieira Raimundi

- [ ] Gessica Tagliapietra Zanon

- [ ] Luiz Eduardo Dameda

- [ ] Luiza Dall Bosco Tonial

- [ ] Milena Sávio Pastorini Paz

- [ ] Morgana Maciél Oliveira

- [ ] Raphael Borges Dos Santos Filho

- [ ] Ricardo Patrik Manfro

- [ ] Robison José Santos da Silva

- [ ] Taynara Chayane Christmann

- [ ] Thalía Lopes Friedrich

- [ ] Rafael Guilman

- [ ] Junior Vitor Ramisch

- [ ] Jean Carlo Hilger

- [ ] Vinícius França Alves

**Comment by morgana-mo** [comment]
- [ ]  1-Amanda Segatto Bisognin  ---------------> 06/11/20 
- [ ] 2- Ana Carolina Morigi da Cruz Silveira -----> 09/11/20
- [ ] 3- Brenda Ellen de Sousa Reis ---------------> 13/11/20
- [ ] 4- Claudineia Vieira Raimundi ---------------> 16/11/20
- [ ] 5- Gessica Tagliapietra Zanon ---------------> 20/11/20
- [ ] 6- Luiz Eduardo Dameda --------------------> 23/11/20
- [ ] 7- Luiza Dall Bosco Tonial -------------------> 27/11/20
- [ ] 8-Milena Sávio Pastorini Paz ----------------> 04/12/20
- [ ] 9- Morgana Maciél Oliveira -----------------> 07/12/20
- [ ] 10- Raphael Borges Dos Santos Filho ------> 11/12/20
- [ ]  11-Ricardo Patrik Manfro ------------------> 14/12/20
- [ ] 12- Robison José Santos da Silva ----------> 18/12/20
- [ ] 13- Taynara Chayane Christmann ----------> 21/12/20
- [ ] 14-Thalía Lopes Friedrich -------------------> 25/12/20
- [ ] 15-Rafael Guilman --------------------------> 28/12/20
- [ ] 16-Junior Vitor Ramisch --------------------> 01/01/21
- [ ] 17-Jean Carlo Hilger ------------------------> 04/01/21
- [ ] 18-Vinícius França Alves --------------------> 08/01/21

**Comment by VIF-Franca** [comment]
Ficou SHOW DE BOLA!!!

Parabéns meninas!!!

**Comment by morgana-mo** [comment]
Closed #140
