### ISSUE TITLE
Live NAP Chapecó - 23/09/2020 - 9h

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/programa#141]
Organização: NAP - Chapecó

Contato: Elisângela Ribas

Titulo: Avaliação da aprendizagem online na UFFS

Palestrante: Elisângela Ribas (UFFS)
Dariane Carlesso - UFFS

Data: 23.09.2020

Horário: 9h - 11h

Apoio NAP: Igor Catalão
Julyane Felipe

A atividade têm previsão para início às 9:00h, mas conectaremos para testes às 8:30h na sala: https://uffs.webex.com/meet/elisangela.santos

**Comment by VIF-Franca** [comment]
Tenho algumas dúvidas sobre essa live que foi indicada para a condução, 

Haverá interpretes de libras ?
Tenho que criar evento no Youtube? é no canal do Practice ?

Informações para criar o roteiro..

**Comment by VIF-Franca** [comment]
Roteiro enviado pela Elisângela Ribas e Imagem. Adicionados no drive

**Comment by VIF-Franca** [comment]
Link da live: https://youtu.be/38YMOu_zFgY
