### ISSUE TITLE
Edição de 5 Videoaulas do professor Fabrício de ADM 

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#142]
Editar as 5 videoaulas do Prof. Fabrício (ADM)

- [ ] Iniciar com a vinheta do Practice
- [ ] Usar modelo com slides + video do professor
- [ ] colocar créditos no final: 
- Nome do professor 
- Disciplina 
- Curso
- Gravação
- Edição
- Arte

Arquivos estão na [Pasta do Drive](https://drive.google.com/drive/folders/1XEPhNXWIGwLRqQAzwmZmBfv3183eSz5t)

Professor irá enviar os slides

**Comment by lcaimi** [comment]
Slides das aulas disponibilizados para a edição colocados na pasta da Issue.

**Comment by vini2reis** [comment]
O professor poderia subir os slides da aula 3 novamente? o arquivo zip que esta lá não esta sendo possivel de usar

**Comment by lcaimi** [comment]
Solicitei para o professor Fabrício enviar novamente.

**Comment by lcaimi** [comment]
Aula 3 já está na pasta de entrada.

**Comment by vini2reis** [comment]
O vídeo da aula 1 esta pronto e na pasta. Estou no aguardo do retorno do solicitante

**Comment by vini2reis** [comment]
Aula 2 também ja esta pronta e editada

**Comment by vini2reis** [comment]
Aula 3 concluida!!

**Comment by lcaimi** [comment]
Qual a tua previsão para as demais @vini2reis?

**Comment by vini2reis** [comment]
> Qual a tua previsão para as demais @vini2reis?

A 4 subi hj lana issue e a 5 amanha ja estara na pasta

**Comment by vini2reis** [comment]
> > Qual a tua previsão para as demais @vini2reis?
> 
> A 4 subi hj la na issue e a 5 amanha ja estara na pasta

**Comment by vini2reis** [comment]
> > > Qual a tua previsão para as demais @vini2reis?
> > 
> > 
> > A 4 subi hj la na issue e a 5 amanha ja estara na pasta

**Comment by vini2reis** [comment]
A 5 falta o final para terminar a edição entao acho que so amanha mesmo pra eu conseguir subir na pasta

**Comment by vini2reis** [comment]
Aula 5 concluida!

**Comment by lcaimi** [comment]
Aprovado e elogiado pelo cliente.
