### ISSUE TITLE
Inserir legenda em videos institucionais 

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/programa#143]
As legendas estão parcialmente feitas.

Contato: Lilian -ASSCOM -CH
               lilian@uffs.edu.br

[Pasta do Drive](https://drive.google.com/drive/folders/1AptWSbzrXw3HsvJoCMkyBVBnZBq9RqKW?usp=sharing) com o arquivo.

**Comment by Dovyski** [comment]
@lucasgalize essa é uma demanda de urgência que recebemos e é de suma importância para a instituição em relação à volta às aulas. Precisamos desse vídeo com legenda o quanto antes.

@VIF-Franca se possível, ajudar o Lucas com esse trabalho.

**Comment by Dovyski** [comment]
O prazo que o cliente pediu é **15/09/2020**.

**Comment by Dovyski** [comment]
O cliente conseguiu ajuda para a realização da tarefa. Ufa! \o/ Não precisa mais fazer ela, @lucasgalize e @VIF-Franca.
