### ISSUE TITLE
Agenda de lives da semana

### ISSUE THREAD

**Issue by patitrev** [practice-uffs/programa#1433]
imagem no link: https://drive.google.com/drive/folders/1w0LOLceU8pNGoLTqTtikMQSRFwEPIlhx?usp=share_link

**Comment by Saene99** [comment]
Olá. Gostaria de ressaltar que a agenda de lives deve ser passada para mim **no mínimo com 24 horas de antecedência** das lives.

É muito improvável que eu veja a issue que foi aberta 2 horas antes do evento começar, como ocorreu hoje (e não foi a primeira vez).
