### ISSUE TITLE
Criação de declaração de todos os bolsistas que já saíram do programa

### ISSUE THREAD

**Issue by robisonjose** [practice-uffs/programa#1434]
Criação de declaração dos bolsistas que saíram do programa no último mês.

**Comment by robisonjose** [comment]
@zorteaadriano preciso que seja feita a autenticação das declarações que estão nessa pasta: 

https://drive.google.com/drive/folders/14u-gaP7w0C0wJWyPGB4rvwkGy5nLyXYo?usp=sharing

assim que finalizado, avise nessa issue, por favor.

**Comment by robisonjose** [comment]
@zorteaadriano preciso de alguma atualização em relação a essa tarefa.

**Comment by robisonjose** [comment]
@zorteaadriano quem é o responsável por essa tarefa? Já passou mais de um mês e nada foi feito..

**Comment by zorteaadriano** [comment]
@robisonjose não tinha conhecimento dessa tarefa, vou dar uma atenção à ela hoje
