### ISSUE TITLE
Live NAP Laranjeiras do Sul - 22/09/2020 - 9h

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/programa#144]
Contato: Lucimara Lemiechek
               ASSAC/NAP-LS

Horário não definido pelo cliente.

**Comment by lcaimi** [comment]
Roteiro disponibilizado na [pasta do Drive](https://drive.google.com/drive/folders/1de5JYNPVivuzdFVW4bzr0CdgrMCvGZxe?usp=sharing).

**Comment by VIF-Franca** [comment]
Elaborar tais tarefas: 
- [ ] Criar evento no Youtube no Campus LS;

- [ ] Criar sala de reunião Webex e enviar para Lucimara; 

- [ ] Adicionar miniatura no Youtube Campus LS;

**Comment by VIF-Franca** [comment]
LINK para o Youtube: https://youtu.be/uM2e84Pvnd8

LINK para o Webex: https://uffs.webex.com/meet/vinicius.alves

**Comment by VIF-Franca** [comment]
Confirmado para realizar os testes as 8:30

**Comment by VIF-Franca** [comment]
Live realizada com sucesso!!!

Segue link para repositório:
https://youtu.be/uM2e84Pvnd8
