### ISSUE TITLE
Relação das informações/ mapa - Laranjeiras do Sul 

### ISSUE THREAD

**Issue by ghost** [practice-uffs/programa#1440]
https://practice.uffs.edu.br/tour-virtual/ls

informações para o mapa: https://docs.google.com/document/d/1hMAx1_8WRB2y1dIlLXwEM9MKMGW4utYNE-nvWMy7Xmw/edit

**Comment by ghost** [comment]
A relação foi feita.

As informações deste mapa é a referência base para os demais mapas.

É necessário a avaliação, pelo grupo do Projeto do Tour Virtual, a respeito de quais informações manter e quais tirar. Após a definição disso, a issue pode ser concluída.

**Comment by ghost** [comment]
@luizatonial @robisonjose @zorteaadriano @marconiryan poderiam revisar o [conteúdo do mapa](https://practice.uffs.edu.br/tour-virtual/ls) e dizerem se acham que algo deve ser suprimido ou acrescentado? esse mapa será a nossa base para os demais, então o que achamos necessário constar, ou não, em todos os mapas vai ser a partir de o que mantivermos neste.

**Comment by robisonjose** [comment]
assim que possível eu reviso e aviso aqui

**Comment by luizatonial** [comment]
Fiz algumas alterações diretamente no mapa, aguardo as revisões dos demais. 

Recomendo não começar as descrições dos blocos com frases do tipo "onde estão localizados". Enquanto não conseguimos formatar o texto da mesma maneira que acontece por ai, coloquei "-" no início da descrição de cada espaço do bloco, para criar tópicos. Vou revisar os demais também, mas por enquanto dá para seguir este padrão.

Na minha opinião está pronto para ser implementado.

**Comment by robisonjose** [comment]
acho que o mapa está ok

uma coisa que poderia ser padronizada é a formatação do texto. Alguns textos estão centralizados, outros justificados, outros estranhos.

**Comment by ghost** [comment]
@zorteaadriano ou @marconiryan conseguem arrumar isso? eu gosto da forma como está o Laboratório 3. não sei o que os outros acham

**Comment by luizatonial** [comment]
@julia-zanini @robisonjose isso foi algo que comentamos nas últimas reuniões, acredito que o pessoal esteja trabalhando nisso e na questão da formatação do texto conforme fazemos aqui no github... 

Caso o dev va padronizar de alguma forma específica, os tópicos prefiro que fiquem alinhados à esquerda (com o nome das salas/setores) e acredito que a descrição inicial poderia ser alinhada a esquerda e justificada (que fica parecido com o que a julia falou).

**Comment by julia-zanini** [comment]
alinhada a direita ou esquerda?

**Comment by luizatonial** [comment]
As revisões referentes a esta issue estão finalizadas. Da parte do conteúdo e do mapa o campus laranjeiras está pronto para implementação.
