### ISSUE TITLE
Relação das informações/ mapa - Chapecó

### ISSUE THREAD

**Issue by ghost** [practice-uffs/programa#1441]
https://practice.uffs.edu.br/tour-virtual/ch

informações para o mapa: https://docs.google.com/document/d/1eRck4RLvSSaCN6RsQQN2ms7QRdjbO68i3bq1q06EwA4/edit

**Comment by ghost** [comment]
A relação foi feita. 

É necessário que um bolsista do campi analise as informações e apresente os erros e as informações faltantes. A correção e adição de informações deve ser colocada no [arquivo do drive](https://docs.google.com/document/d/1eRck4RLvSSaCN6RsQQN2ms7QRdjbO68i3bq1q06EwA4/edit) com o conteúdo novo/ corrigido grifado. Se necessário, utilize de comentários para facilitar o trabalho.

Utilize o [mapa](https://practice.uffs.edu.br/tour-virtual/ch) como material para levantar as correções, mas anote essas correções no arquivo do drive.

**Comment by ghost** [comment]
@marconiryan poderia fazer essa correção dos conteúdos?

**Comment by marconiryan** [comment]
Vou pedir para o @gustavoSutil fazer isso. Ele está tirando as fotos 360 do campus

**Comment by luizatonial** [comment]
@gustavoSutil Se tu puder revisar as informações enquanto faz as fotos 360º seria muito importante! Além disso, no site utilizamos o modelo em que há uma foto do bloco, o nome e a descrição das salas ou setores presentes no mesmo... Então se possível, enquanto anda pelo campus para fazer o 360º, já tira uma foto das entradas dos blocos que são interativos e confere as descrições posteriormente.

**Comment by gustavoSutil** [comment]
Ótimo @luizatonial, aqui estão as algumas fotos caso de para aproveitar mas vou tirar mais.
![IMG_20230306_112408](https://user-images.githubusercontent.com/85875309/225681523-64cfd7f6-877c-454d-86c2-f8b99f432a8f.jpg)
![IMG_20230306_112402](https://user-images.githubusercontent.com/85875309/225681545-26feeb23-d231-4611-b0e1-adfc7b52680a.jpg)
![IMG_20230306_110532](https://user-images.githubusercontent.com/85875309/225681560-01ec3720-dc3c-40eb-a9c5-b9307cfb9193.jpg)
![IMG_20230306_110526](https://user-images.githubusercontent.com/85875309/225681576-72012438-2c96-4e12-8f34-72251870756e.jpg)
![IMG_20230306_110508](https://user-images.githubusercontent.com/85875309/225681586-82171bf4-c38d-4a21-88a7-3a5894b2e629.jpg)
![IMG_20230306_110504](https://user-images.githubusercontent.com/85875309/225681599-c43f803d-07df-4679-9f35-f7e912b7e396.jpg)
![IMG_20230306_110454](https://user-images.githubusercontent.com/85875309/225681618-4ab0ef98-1b62-4d6d-99c0-d4af3547d252.jpg)
![IMG_20230306_110309](https://user-images.githubusercontent.com/85875309/225681625-618577e8-1050-4e14-9722-e772ef19b66e.jpg)
![IMG_20230306_110258](https://user-images.githubusercontent.com/85875309/225681635-b4096e1e-4d61-4bfb-9597-c5f64d555d01.jpg)
![IMG_20230306_110146](https://user-images.githubusercontent.com/85875309/225681641-66c2a84f-7673-46af-acf9-7f9b2f81e552.jpg)
![IMG_20230306_102416](https://user-images.githubusercontent.com/85875309/225681661-a4451ac3-6787-4575-adc3-b98f22db1322.jpg)
![IMG_20230306_102400](https://user-images.githubusercontent.com/85875309/225681672-6bd5ae67-e189-4b1d-a806-43cbae2fd7e1.jpg)
![IMG_20230306_102356](https://user-images.githubusercontent.com/85875309/225681686-e12b61b3-c3aa-4172-959d-a7a334d5761a.jpg)
![IMG_20230306_102152](https://user-images.githubusercontent.com/85875309/225681704-1cea5ddb-2bfe-4c7b-a39e-8f2bde4bd5cb.jpg)
![IMG_20230306_102150](https://user-images.githubusercontent.com/85875309/225681726-78292261-0adc-4938-85d1-58f2ee386cf6.jpg)
![IMG_20230306_102116](https://user-images.githubusercontent.com/85875309/225681744-fe26eae8-1981-43da-bf54-54c67a461a4f.jpg)
![IMG_20230306_102100](https://user-images.githubusercontent.com/85875309/225681775-1bdd8116-e75d-4d38-a372-f6e316a77f29.jpg)
![IMG_20230306_102038](https://user-images.githubusercontent.com/85875309/225681806-f10ff220-444a-4a55-bc31-c5595318adcf.jpg)

**Comment by luizatonial** [comment]
Revisões do Campus Chapecó:
* Adicionei as fotos do comentário acima, mas percebi que elas demoram um pouco para carregar
_(acho que vc pegou elas das panorâmicas? @gustavoSutil, talvez tirando dos blocos em si elas vão ficar com formato melhor e tamanho menor)_
* Neste sentido todos os espaços, descrições e fotos precisam ser revisados por pessoas do campus _(revisei as alterações da @julia-zanini e acho que estão ok)_
* Ainda existem alguns pontos sem nomenclatura
_(peço que o @gustavoSutil também revise isso depois de tirar as fotos 360º e nos avise o que são esses espaços - caso sejam locais de lixo energia etc, que você acha que não precisam ser clicáveis, nos avise para retirarmos da lista)_
![image](https://user-images.githubusercontent.com/71669357/226396449-05d41f22-f3b2-4529-bb58-5fad071c67b9.png)

**Comment by gustavoSutil** [comment]
# Segue as fotos faltantes:

## Estação tratamento de esgoto
![IMG_20230403_104610](https://user-images.githubusercontent.com/85875309/229545514-97a3e68f-8795-4cbd-9d31-cd0a9eb2f1ea.jpg)
![IMG_20230403_104229](https://user-images.githubusercontent.com/85875309/229545528-a8b4a841-be6e-4e16-8c6a-d416cc7145a4.jpg)
## Estufas
![IMG_20230331_164955](https://user-images.githubusercontent.com/85875309/229545603-bc6a453e-5ed6-495f-bc8f-6c42e8dbc339.jpg)
![IMG_20230331_164946](https://user-images.githubusercontent.com/85875309/229545839-5aac3663-01e8-4f4f-b17e-907b19821671.jpg)
![IMG_20230331_164944](https://user-images.githubusercontent.com/85875309/229545847-1c766625-c879-4b97-bdac-f91b33591037.jpg)
## Galpão agrícula
![IMG_20230331_164308](https://user-images.githubusercontent.com/85875309/229546161-a7cc363e-3cfc-4461-8577-fb2c6052ec12.jpg)
![IMG_20230331_164251](https://user-images.githubusercontent.com/85875309/229546234-e1bf27b0-1dfe-441b-9609-6294d5b97f7a.jpg)
## Bloco dos professores
![IMG_20230323_144833](https://user-images.githubusercontent.com/85875309/229546874-85bcff00-7746-44e7-a31d-b1d6242fb995.jpg)
## central de residuos
![IMG_20230323_144007](https://user-images.githubusercontent.com/85875309/229547018-1811d9b2-8547-422b-b4d3-e66d00e74711.jpg)
## Bloco c
![IMG_20230323_142920](https://user-images.githubusercontent.com/85875309/229547402-e5dace51-2435-4250-9fb9-a71c3c8d7302.jpg)
![IMG_20230323_142928](https://user-images.githubusercontent.com/85875309/229547413-ab433a9e-4b2d-4f6b-aa60-33ddd1e65bb7.jpg)
## Bloco b
![IMG_20230323_142601](https://user-images.githubusercontent.com/85875309/229547741-284a7c77-802c-41b0-8205-dd2445d0da07.jpg)
## Almoxarifado
![IMG_20230331_173251](https://user-images.githubusercontent.com/85875309/229549458-190c370c-a358-4f14-b84a-2dd5c6bf5f1a.jpg)
![IMG_20230331_173219](https://user-images.githubusercontent.com/85875309/229549467-37fa8ac9-f52c-4800-b57c-6ce7d8dcf349.jpg)
![IMG_20230331_173216](https://user-images.githubusercontent.com/85875309/229549470-ebc19174-1a91-4b8a-b27e-541cb540ab91.jpg)
![IMG_20230331_173212](https://user-images.githubusercontent.com/85875309/229549476-6e0a7acc-997a-4b3f-aaa3-ace761680378.jpg)
![IMG_20230331_173253](https://user-images.githubusercontent.com/85875309/229549479-a47bd1d6-b1f6-4b63-8c21-31d1fea77049.jpg)
## Quadra de volei de areia
![IMG_20230331_173907](https://user-images.githubusercontent.com/85875309/229549632-9f5ee4df-a866-45d4-a647-80ab0c126628.jpg)
![IMG_20230331_173852](https://user-images.githubusercontent.com/85875309/229549645-c0aa31a1-0f87-464b-bc98-64bfea3697ba.jpg)
![IMG_20230331_173849](https://user-images.githubusercontent.com/85875309/229549648-893baf12-adfe-47e9-814a-69a90dace6c2.jpg)
![IMG_20230331_173914](https://user-images.githubusercontent.com/85875309/229549656-11c4781b-429c-42ad-8f19-77eef168ba93.jpg)
## Campo de futebol 
![IMG_20230331_174026](https://user-images.githubusercontent.com/85875309/229549811-a0a4ceba-5728-427e-b88a-e02378c0f5a4.jpg)
![IMG_20230331_174024](https://user-images.githubusercontent.com/85875309/229549816-ccc32860-b2a6-42cc-b6d0-513d810bb8db.jpg)
![IMG_20230331_174021](https://user-images.githubusercontent.com/85875309/229549820-05ab80fc-5469-4815-9dfb-ac9acd0c89ed.jpg)
![IMG_20230331_174017](https://user-images.githubusercontent.com/85875309/229549823-c3ae88ce-aa08-4118-8e09-fd5b841275b0.jpg)
![IMG_20230331_174013](https://user-images.githubusercontent.com/85875309/229549825-e4c907e7-bf7f-402a-8042-8d0d9816846f.jpg)
## usina fotovoltaica
![IMG_20230331_180225](https://user-images.githubusercontent.com/85875309/229550133-b0c60ce7-eb3b-4db6-aad9-2c9f44cd41f2.jpg)
![IMG_20230331_180220](https://user-images.githubusercontent.com/85875309/229550146-ea8b0789-12f0-4967-81e2-f3b4514b2405.jpg)
![IMG_20230331_180203](https://user-images.githubusercontent.com/85875309/229550150-23072303-da6f-472f-8981-6812cbfa84df.jpg)
![IMG_20230331_180159](https://user-images.githubusercontent.com/85875309/229550155-c7b51f4e-6b6a-4f1d-a20d-da7733112180.jpg)
![IMG_20230331_180143](https://user-images.githubusercontent.com/85875309/229550159-23550bfb-88b9-46ab-9f28-263c07f3d541.jpg)

**Comment by gustavoSutil** [comment]
## R U
![IMG_20230403_130104](https://user-images.githubusercontent.com/85875309/229571122-52da1819-dea0-4f04-9810-62c8cc41a64f.jpg)
![IMG_20230403_130057](https://user-images.githubusercontent.com/85875309/229571171-66bf666e-5cf4-49b1-90cc-1aa9d7a1e283.jpg)
![IMG_20230403_130045](https://user-images.githubusercontent.com/85875309/229571194-938402ac-56ab-4fd0-b7e6-0381427fd29c.jpg)
![IMG_20230403_130122](https://user-images.githubusercontent.com/85875309/229571212-c4374295-3fb9-49a1-940b-2a06ab51f8bc.jpg)
![IMG_20230403_130120](https://user-images.githubusercontent.com/85875309/229571228-331cbe4f-d4f9-4d91-9f03-5460f010730f.jpg)

**Comment by marconiryan** [comment]
@gustavoSutil nao precisa postar todoas as fotos na issue. Poste no drive que fica melhor

**Comment by luizatonial** [comment]
coloquei elas lá por enquanto e achei q não mudou tanto a qualidade. mas se conseguir posta lá tbm para compararmos @gustavoSutil.

vou deixar a issue aberta por enquanto até o momento em que você terminar a revisão das informações, acho que falta principalmente o Bloco C e a conferência dos demais.

**Comment by luizatonial** [comment]
a @julia-zanini está com as informações e irá fazer a revisão das salas/setores
