### ISSUE TITLE
Relação das informações/ mapa - Erechim

### ISSUE THREAD

**Issue by ghost** [practice-uffs/programa#1442]
https://practice.uffs.edu.br/tour-virtual/er

informações para o mapa: https://docs.google.com/document/d/1W5T497Uma0Ny6F4iAZnEWVxuB-ovJl7L/edit

**Comment by ghost** [comment]
A relação foi feita.

É necessário que um bolsista do campi analise as informações e apresente os erros e as informações faltantes. A correção e adição de informações deve ser colocada no [arquivo do drive](https://docs.google.com/document/d/1W5T497Uma0Ny6F4iAZnEWVxuB-ovJl7L/edit) com o conteúdo novo/ corrigido grifado. Se necessário, utilize de comentários para facilitar o trabalho.

Utilize o [mapa](https://practice.uffs.edu.br/tour-virtual/er) como material para levantar as correções, mas anote essas correções no arquivo do drive.

**Comment by ghost** [comment]
@luizatonial poderia fazer a correção das informações?

**Comment by luizatonial** [comment]
iniciado na #1416, caso precise de alguma outra revisão adicional eu realizo posteriormente

**Comment by ghost** [comment]
@luizatonial fiz algumas alterações, se você poder ver

**Comment by luizatonial** [comment]
as informações iniciais de erechim foram realizadas, quando eu for tirar as fotos para os cards eu verifico novamente se existem informações faltando.

**Comment by luizatonial** [comment]
atualizei algumas imagens (todos os blocos tem imagens provisórias do campus) e informações sobre o campus, ainda não terminei e revisarei tudo novamente antes de ir pro ar.

**Comment by luizatonial** [comment]
@julia-zanini acredito que está tudo correto e atualizado. Fiz uma revisão geral, mas caso queira pode dar uma olhada ver se não escrevi algo errado ou alguma coisa que você consiga ver que está diferente do padrão.
