### ISSUE TITLE
Relação das informações/ mapa - Cerro Largo

### ISSUE THREAD

**Issue by ghost** [practice-uffs/programa#1443]
https://practice.uffs.edu.br/tour-virtual/cl

informações para o mapa: https://docs.google.com/document/d/1fWuYK9tDP8Z771P1FupaI7IheFA5ztVzKEOaOlyTaTE/edit

**Comment by ghost** [comment]
fiz a relação entre as informações. vou perguntar se a morgana não faria o favor de analisar as informações e os mapas e dizer se está correto e o que é necessário mudar

**Comment by luizatonial** [comment]
Acredito que todas as informações que poderíamos acrescentar ao mapa neste momento já estão implementadas. Portanto vou encerrar a issue.
