### ISSUE TITLE
Relação das informações/ mapa - Passo Fundo

### ISSUE THREAD

**Issue by ghost** [practice-uffs/programa#1444]
https://practice.uffs.edu.br/tour-virtual/pf

informações para o mapa: https://docs.google.com/document/d/1x_YZ-RT6Ki2KkUqWZ82gUwjeTizgBfCbp6gkF7ZOHIs/edit

**Comment by luizatonial** [comment]
estou em contato com nosso ex-membro luiz para ajustar o mapa kkkk, já atualizei algumas informações e ele vai tentar fazer as fotos dos cards para auxiliar

**Comment by luizatonial** [comment]
acho que está pronto o que podemos fazer até o momento
