### ISSUE TITLE
Relação das informações/ mapa - Realeza

### ISSUE THREAD

**Issue by ghost** [practice-uffs/programa#1445]
https://practice.uffs.edu.br/tour-virtual/re

informações para o mapa em: https://docs.google.com/document/d/1tHWC0DiV1cyz1bco3Sf4tEEYSZNBoIUw3FT2kk_t2w0/edit

**Comment by ghost** [comment]
comecei a fazer a relação entre as informações e o mapa, mas no open street view não tem praticamente nada indicando o que fica onde. preciso que alguém do campus me indique essas informações para eu poder implementar no sistema.
@robisonjose teria como você ver isso? além de ver se as informações estão certas.

**Comment by robisonjose** [comment]
fiz alguns comentários no documento, porém eu não sei muita coisa sobre o campus.

**Comment by ghost** [comment]
implementei as informações que o @robisonjose passou, no mapa. teria como você indicar quais os locais do GALPÃO ÁREA EXPERIMENTAL; ESTUFA ÁREA EXPERIMENTAL; e SUPERINTENDÊNCIA UNIDADE HOSPITALAR VETERINÁRIA UNIVERSITÁRIA (SUHVU)?
e a Clinica Escola de Nutrição é um espaço para aplicação do curso de nutrição?

**Comment by robisonjose** [comment]
quando der eu vou lá na uffs ver onde fica cada coisa

**Comment by robisonjose** [comment]
@julia-zanini 

Fui ao campus de Realeza para obter informações dos blocos e coloquei todas as informações que consegui encontrar no documento.

**Comment by ghost** [comment]
atualizei no mapa as informações novas que o @robisonjose colocou. precisamos ainda achar a descrição sobre aquelas áreas de clínicas animais para completar de vez o conteúdo.
sobre os prédios faltantes, sinalizei a @luizatonial e ela vai acrescentar eles

**Comment by robisonjose** [comment]
Estou em contato com alguns professores de veterinária para mais informações sobre o campus e estou realizando algumas pesquisas. Assim que tiver mais informações compartilho aqui.

**Comment by luizatonial** [comment]
Os blocos estão finalizados e todos permitindo a interatividade, criei descrições básicas para os blocos que ainda não temos informações. Faltam daí as fotos destes lugares nos cards.

**Comment by robisonjose** [comment]
![Captura de Tela (41)](https://user-images.githubusercontent.com/71669689/229521615-41b6e987-f911-4a19-afa4-3b9ffcb9afb3.png)

*Superintendência Unidade Hospitalar Veterinária Universitária*: A Superintendência Unidade Hospitalar Veterinária Universitária (SUHVU) é uma unidade de apoio às atividades de ensino, pesquisa e extensão do Campus Realeza, especialmente, aquelas ligadas à saúde animal. Várias são as atividades desenvolvidas pelos mais diversos componentes curriculares, principalmente do Curso de Medicina Veterinária. Existem diversos setores que compõem a SUHVU e que contribuem para a prestação de serviços em saúde animal à comunidade regional, sendo eles: Clínica Médica de Animais de Companhia, Clínica Médica de Animais de Produção, Clínica Cirúrgica Veterinária, Laboratórios de: Anatomia Veterinária, Análises Clínicas Veterinárias, Diagnóstico por Imagem Veterinária, Doenças Infecciosas Veterinárias, Imunologia e Doenças Parasitárias Veterinárias, Patologia Veterinária, Reprodução Animal e ainda Biotério para alojamento de roedores. Vários projetos de extensão e pesquisa ligados à saúde animal são desenvolvidos nesse espaço, sempre com a participação de acadêmicos de graduação e pós-graduação.

*FUNCIONAMENTO E CONTATOS*

O atendimento ao público e os serviços à comunidade pela SUHVU é oferecido de segunda-feira a sexta-feira, das 8h às 12h e das 13h às 17h.

Endereço: Complexo Hospitalar Veterinário – CHV. Universidade Federal da Fronteira Sul – UFFS Campus Realeza. Av. Edmundo Gaivski, 1000, Realeza-PR.

Telefones: Recepção (Informações sobre consultas): (46) 3543-8400; Administração: (46) 3543-8403

E-mails: recepcao.suhvu@uffs.edu.br; administracao.suhvu@uffs.edu.br

__________________________________________________________


Bloco 1 - Setor Recepção:

- Superintendência: setor responsável pela Direção Geral da SUHVU e Coordenação Administrativa. Comporta o planejamento institucional, a organização setorial, avaliação e aprimoramento dos processos e fluxos de trabalho, observando as diretivas legais concernentes ao ambiente hospitalar veterinário, entre outras atividades de base como: gestão de compras, de pessoal, manutenção, etc.

Bloco 2 - Setor Apoio: 

- Apoio: setor responsável por dar suporte as atividades médico veterinárias hospitalares, as atividades de aulas práticas, as atividades de pesquisa, de logística, ambiência e convivência aos técnicos, professores e servidores da SUHVU. No Setor de Apoio estão incluídos os serviços de: Recepção e Arquivo; Central de Materiais e esterilização; Farmácia Central; Dispensatório; Lavanderia; e Copa Central.

- Biotério: setor responsável pela manutenção e criação de animais (inicialmente roedores) para uso experimental ou em aulas práticas da SUHVU e da UFFS. (Setor em implantação).

Bloco 3 - Setor de Clínica médica e Cirurgia:

- Anestesiologia Veterinária: setor que oferece serviços de contenção química, controle da dor, sedação, bloqueios anestésicos e anestesia geral aos animais, em atividades de ensino, pesquisa e extensão da SUHVU.

- Clínica Médica de pequenos animais: setor responsável pelos atendimentos clínicos, tratamentos hospitalares e prescrições de medicamentos, solicitação e encaminhamentos de exames, recebimento e interpretação de examesde animais de companhia, em atividades de ensino, pesquisa e extensão na SUHVU. Possui atendimento de especialidade em Cardiologia Veterinária.

- Clínica Cirúrgica de pequenos animais: setor responsável pelos atendimentos clínicos cirúrgicos, tratamentos hospitalares e prescrições de medicamentos, solicitação e encaminhamentos de exames, recebimento e interpretação de exames de animais de companhia, realização de tratamentos cirúrgicos invasivos ou conservadores em atividades de ensino, pesquisa e extensão na SUHVU. Possui atendimento de especialidade em Obstetrícia Veterinária, Oncologia Veterinária, Oftalmologia Veterinária, Ortopedia Veterinária e Neurologia Veterinária.
 
- Clínica e Cirurgia de Grandes Animais: setor responsável pelos atendimentos clínicos, tratamentos hospitalares e prescrições de medicamentos, solicitação e encaminhamentos de exames, recebimento e interpretação de exames de animais de produção, em atividades de ensino, pesquisa e extensão na SUHVU.

Bloco 4 - Setor de Diagnóstico:

- Análises Clínicas Veterinárias: setor responsável pelo processamento de amostras e realização de exames laboratoriais de análises clínicas veterinárias, atendendo as demandas de atividades de ensino, pesquisa e extensão da SUHVU nessa área. São realizados os seguintes exames: hemogramas, exames diversos de bioquímica clínica, urinálise, provas de hemostasia e avaliação de líquidos cavitários.

- Diagnóstico por Imagem Veterinária: setor responsável pelo recebimento de solicitações de exames por imagem em animais, obtenção de imagens e produção de laudos em atividades de ensino, pesquisa e extensão da SUHVU. Atende solicitações de exames de radiografia simples, radiografias contrastadas e ultrassonografias simples e Doppler.

- Doenças Infecciosas Veterinárias: setor responsável por receber amostras e processá-las, de modo a se obter diagnóstico de doenças infecciosas veterinárias em atividades de ensino pesquisa e extensão da SUHVU (Setor em implantação).

- Doenças parasitárias Veterinárias: setor responsável por receber amostras e processá-las, de modo a se obter diagnóstico de doenças parasitárias veterinárias em atividades de ensino, pesquisa e extensão da SUHVU.

- Serviço de diagnóstico de Leucose Enzoótica Bovina: setor responsável pelo diagnóstico sorológico de Leucose Enzoótica Bovina (LEB). Realiza análises de amostras de sangue de bovinos localizados em propriedades rurais em Realeza e região.

Bloco 5 - Setor de Reprodução:

- Reprodução Animal: setor responsável por realizar exames reprodutivos de machos e fêmeas das diversas espécies animais, com objetivos de diagnóstico e tratamento de afecções reprodutivas, melhoria nas técnicas de reprodução, desenvolvimento e aplicação de novas tecnologias para a reprodução animal. Atendendo as demandas em atividades de ensino, pesquisa e extensão na SUHVU (Setor em implantação).

Bloco 6 - Setor de Anatopatologia:

- Anatomia Veterinária: setor responsável por produzir material didático, de extensão, e de pesquisa na área de morfologia veterinária e morfologia aplicada.

- Patologia Veterinária: setor responsável por receber amostras e processá-las de modo a se obter diagnóstico anatomopatológico e/ou histopatológico de afecções que acometem os animais. Atuando em atividades de ensino, pesquisa e extensão na SUHVU.

Bloco 7 - Áreas Experimentais: 

As Áreas Experimentais do Campus Realeza foram criadas para atender as atividades de ensino, pesquisa e extensão da comunidade acadêmica. As atividades envolvem os cursos de Medicina Veterinária, Nutrição, Biologia, dentre outros, que desenvolvem atividades didáticas e experimentos de campo com animais e plantas.

Localizada às margem da PR-182, a área ocupa aproximadamente de 22,5 ha de terreno agricultável. Possuí solo fértil, nascentes, curso de água e Área de Preservação Ambiental, entre seus principais recursos naturais.

A infraestrutura envolve um galpão agrícola e uma estufa para cultivo, ambos em fase de construção. O galpão abriga basicamente implementos e insumos agrícolas, dentre eles, semeadora, adubadora, pulverizador, ensiladora, adubos e sementes.

- Galpão: galpão que abriga basicamente implementos e insumos agrícolas.

- Estufa: estufa para cultivo.

Bloco 8 - Clínica de Grandes animais:

Área em construção. Abrigará o setor de Clínica e Cirurgia de Grandes Animais que hoje está alocado no bloco 3 (Clínica médica e Cirurgia). 

__________________________________________________________


Todas as descrições dos blocos 1 ao 6 eu peguei [dessa página](https://www.uffs.edu.br/campi/realeza/hospital_veterinario) (inclusive o início, com as informações sobre funcionamento e contato). Do bloco 7 peguei [dessa daqui](https://www.uffs.edu.br/campi/realeza/areas_experimentais).

Consegui um mapa de implantação do hospital veterinário (que tem coisas que ainda nem foram construídas). Onde posso colocar esse material @luizatonial?

E por último, o bloco em construção (bloco 8 - se usar a imagem que coloquei como referência) está muito grande no mapa. Acho que vocês utilizaram os limites mais aparentes para fazer o mapa, mas, na verdade, aqueles limites são só o cercado. Acredito que o bloco terá mais ou menos o mesmo tamanho dos que estão acima dele.

![Captura de Tela (42)](https://user-images.githubusercontent.com/71669689/229530392-c7a1cceb-4e21-4e4f-9f93-a4cf0dd9efe9.png)

**Comment by robisonjose** [comment]
Isso foi o máximo de informações que consegui, conversando com alunos, professores, técnicos e com as vozes da minha cabeça.

**Comment by robisonjose** [comment]
Última coisa. No mapa está "Central de resíduos sólidos" mas aqui em Realeza é apenas "Central de resíduos".

**Comment by luizatonial** [comment]
@robisonjose coloca aqui na pasta do campus por enquanto kk dps organizo melhor https://drive.google.com/drive/u/1/folders/1YklQsN-rr6xaPWTSqJgEaPV848x9uJ38

**Comment by luizatonial** [comment]
@julia-zanini consegue revisar o mapa de realeza com as novas informações do robison?

**Comment by robisonjose** [comment]
@luizatonial coloquei na pasta de realeza. O pdf é bem pesado, então não estranhe se ele demorar muito pra abrir ou abrir com uma qualidade péssima. Ele demora um pouco pra ficar 100%

**Comment by luizatonial** [comment]
beleza!

> Última coisa. No mapa está "Central de resíduos sólidos" mas aqui em Realeza é apenas "Central de resíduos".

sobre isso, em todos os campi acho que está escrito no bloco sem o sólidos... mas é a função... podemos decidir como padronizar

**Comment by luizatonial** [comment]
e sobre o tamanho do novo bloco, diminui um pouco

**Comment by ghost** [comment]
coloquei os apontamentos do robison no mapa, mas precisa aprimorar mais, avaliar melhor como vai deixar essas informações

**Comment by luizatonial** [comment]
foi feita a atualização final das informações. @robisonjose quando puder, de uma olhada rápida... e se estiver tudo ok pode fechar a issue. em seguida vou criar outra para as fotos dos espaços e para as fotos 360º.

**Comment by robisonjose** [comment]
Acho que está tudo ok. Só falta especificar (e separar) o galpão e a estufa, pois provavelmente vai ter uma foto de cada (bloco 7 - Áreas experimentais).

Tirando isso, me parece que foi colocado tudo o que descrevi no comentário ali em cima. Se tivermos errados, o site tá errado.

**Comment by robisonjose** [comment]
Uma coisa que eu tiraria é a parte do "...que é uma unidade de apoio às atividades de ensino, pesquisa e extensão do Campus Realeza, especialmente, aquelas ligadas à saúde animal." 

tiraria isso de todos os blocos com exceção do bloco I (recepção). Acho que ficou muito repetitivo.

E também poderia adicionar que no bloco I tem um auditório e algumas salas de aula.

**Comment by luizatonial** [comment]
> Acho que está tudo ok. Só falta especificar (e separar) o galpão e a estufa, pois provavelmente vai ter uma foto de cada (bloco 7 - Áreas experimentais).
> 
> Tirando isso, me parece que foi colocado tudo o que descrevi no comentário ali em cima. Se tivermos errados, o site tá errado.

sobre o galpão e a estufa, a gente tava padronizando os nomes pra ficar tudo igual e eu apaguei errado KKKKKK ja estavam separados e acho que agora está correto

**Comment by luizatonial** [comment]
obrigada! acrescentei o auditório e as salas de aula e vou falar com a julia sobre a outra parte das descrições.
