### ISSUE TITLE
Organização Tour Virtual - Relação das informações dos campi com o mapa interativo

### ISSUE THREAD

**Issue by ghost** [practice-uffs/programa#1446]
Relacionar as informações dos campi levantadas previamente com o mapa interativo criado. Após a relação inicial das informações, é necessário que bolsistas de cada campus revise as relações e proponha mudanças.

- [x] #1440 
- [x] #1441 
- [x] #1442 
- [x] #1443 
- [x] #1444 
- [x] #1445

**Comment by luizatonial** [comment]
Esta issue busca relacionar:

**Mapas**
- #1415 
- #1414 
- #1413 
- #1374 
- #1365
- #1363

**Informações**
- #1419
- #1418
- #1417
- #1416
- #1400
- #1362

**Comment by luizatonial** [comment]
Peço que o @gustavoSutil e o @robisonjose possam revisar as informações dos campi de Realeza e de Chapecó, para verificar se as descrições dos blocos e as salas/setores presentes em cada um destes estão corretas. E, assim que possível, dar o retorno nas issues #1441 e #1445. Farei o mesmo com Erechim (#1442).

**Comment by ghost** [comment]
padronizei as informações de todos os mapas a partir de como foi escrito em Laranjeiras do Sul, nosso mapa protótipo

**Comment by robisonjose** [comment]
Eu vou ir essa semana dar uma pesquisada nas coisas no campus, pq eu não sei nada sobre a parte de medicina veterinária

**Comment by luizatonial** [comment]
@julia-zanini peço que tu revise todos os lugares (de todos os campi) onde tem tópico e altere o traço que tínhamos usado (ou acrescente nos que eu já tinha apagado o traço) por esse símbolo:  •
Conforme o ryan comentou na #1466 vamos ter que inserir manualmente

**Comment by ghost** [comment]
> @julia-zanini peço que tu revise todos os lugares (de todos os campi) onde tem tópico e altere o traço que tínhamos usado (ou acrescente nos que eu já tinha apagado o traço) por esse símbolo: • Conforme o ryan comentou na #1466 vamos ter que inserir manualmente

inserido

**Comment by luizatonial** [comment]
Conferi todas as informações do campus de Chapecó, comparando com Laranjeiras, e acredito que da nossa parte está ok! Todos os blocos tem títulos e descrições básicas. 

Peço que o @gustavoSutil revise as informações para verificar se estão certas, acrescente os tópicos do que está presente no Bloco C e acrescente as fotos de cada bloco. Pode armazenar [nessa pasta](https://drive.google.com/drive/folders/1Y9riWYZfN0cO7QQmUSBkwHlIODtnqLsE?usp=sharing) e colar o link diretamente na página: https://practice.uffs.edu.br/tour-virtual/admin/information?filter=CH.

**Comment by luizatonial** [comment]
Fiz uma revisão básica em Passo Fundo e Cerro Largo em que não temos bolsistas... Mas as informações precisam ser corrigidas e novas fotos precisam ser acrescentadas.

**Comment by ghost** [comment]
revisei todos os mapas padronizando algumas questões de nomes e siglas

**Comment by luizatonial** [comment]
assim que o @gustavoSutil finalizar a revisão de chapecó encerramos esta etapa.

**Comment by luizatonial** [comment]
acredito que com as informações que temos, até o momento, esta issue está finalizada... farei apenas uma revisão
