### ISSUE TITLE
Planfleto de divulgação de serviços do PRACTICE

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#145]
É necessário adaptar o texto desenvolvido na tarefa #106 para o template desenvolvido na tarefa #117.

O texto pode ser apenas adaptado ou escrito do zero, a depender do julgamento das responsáveis pela tarefa.

Além do panfleto geral, elaborar um panfleto para os serviços da con-material e um panfleto para os serviços da con-midia.
Utilizar os textos disponíveis na aba serviços do site para elaborar os panfletos de cada serviço.

[Pasta do drive](https://drive.google.com/drive/u/0/folders/1gtPKQf0KwnsnK3CknxPruj00egpXNEkK).

**Comment by estelavilasboas** [comment]
Texto adaptado e dividido em [duas páginas](https://docs.google.com/presentation/d/19V1EShUWn3eKSL6rXFt1Sey2QPG-k9pgVzU0Vj_srEg/edit). Aguardando revisão técnica.

**Comment by Dovyski** [comment]
Ficou maravilhoso, parabéns, pessoal! ❤️ Eu fiz apenas uma alteração no texto dos estúdios para dizer que eles estão em implantação nos demais campi.

**Comment by alessandrapedrotti** [comment]
A versão em PDF do panfleto encontrasse na pasta [divulgação ](https://drive.google.com/drive/u/0/folders/1Treo222l1pcTDXZGQrebaQ0BgY5MTz-9)na pasta "materiais"  do programa.
