### ISSUE TITLE
Corrigir os nomes do Street View do Tour Virtual de Laranjeiras do Sul

### ISSUE THREAD

**Issue by luizatonial** [practice-uffs/programa#1451]
Corrigir a denominação de cada bloco/espaço que aparece na barra lateral da visão panorâmica de Laranjeiras do Sul: 
https://practice.uffs.edu.br/tour-virtual/ls/panorama

- Utilizar nomes completos
- Alterar para: Nome do Bloco (Interno) e Nome do Bloco (Externo)
- Criar padronização para utilizar nos demais campi

**Comment by luizatonial** [comment]
@julia-zanini pode criar a lista aqui mesmo, use, por exemplo:
NOME ANTIGO > NOME NOVO
para o ryan se localizar depois

**Comment by ghost** [comment]
Campus Laranjeiras do Sul
Nas imagens do Tour

Docente Fora > Bloco Docente (externo)
Docente Dentro > Bloco Docente (interno)
Docente Centro > Bloco Docente (interno)
CVT > Centro Vocacional Tecnológico (CVT)
A Fora > Bloco A (externo)
A Dentro > Bloco A (interno)
A Centro > Bloco A (interno)
Laboratório 3 Dentro > Laboratório 3 (interno)
Laboratório 2 Dentro > Laboratório 2 (interno)
Laboratório 1 Dentro > Laboratório 1 (interno)
RU Fora > Restaurante Universitário (externo)
RU Dentro > Restaurante Universitário (interno)

@marconiryan

**Comment by luizatonial** [comment]
Troca o entrada pra exterior pra padronizar

Enviado do meu iPhone

Em 9 de mar. de 2023, à(s) 11:16, julia-zanini ***@***.***> escreveu:

﻿

Campus Laranjeiras do Sul
Nas imagens do Tour

Docente Fora > Bloco Docente (exterior)
Docente Dentro > Bloco Docente (entrada)
Docente Centro > Bloco Docente (interior)
CVT > Centro Vocacional Tecnológico (CVT)
A Fora > Bloco A (exterior)
A Dentro > Bloco A (entrada)
A Centro > Bloco A (interior)
Laboratório 3 Dentro > Laboratório 3 (interior)
Laboratório 2 Dentro > Laboratório 2 (interior)
Laboratório 1 Dentro > Laboratório 1 (interior)
RU Fora > Restaurante Universitário (exterior)
RU Dentro > Restaurante Universitário (interior)

@marconiryan<https://github.com/marconiryan>

**Comment by luizatonial** [comment]
acho que entrada não é muito bonito kkkk evitamos na arquitetura pelo menos
usamos tudo "EXTERNO"/"INTERNO" ou talvez "ACESSO"

**Comment by luizatonial** [comment]
fui conferir no tour e acho que pode ser "interno" mesmo @julia-zanini mesmo que fique repetido

**Comment by ghost** [comment]
Ajeitei. Veja o que acha

**Comment by luizatonial** [comment]
Acho que agora está ok! Ryan pode atualizar.

**Comment by marconiryan** [comment]
Ao meu ver fica estranho colocar interno e externo na lista. Ao inves disso, por que nao adotar um padrão que somente as partes externas vão ficar nessa lista? Se nao fica muita coisa repetida
![image](https://user-images.githubusercontent.com/86175804/225178043-6059b331-bfe9-4453-a923-f355b6a27d1f.png)

**Comment by marconiryan** [comment]
@luizatonial Vai manter do jeito que está ou vai ser alterado?

**Comment by luizatonial** [comment]
@marconiryan acho que deixamos (interior) em todos que forem dentro dos blocos e os demais sem nada quando for externo. No caso deixamos todos os nomes na lista e tiramos o termo "(externo)".

**Comment by luizatonial** [comment]
como sugestão da coordenação em reunião utilizar, por exemplo:

BLOCO A:
> externo
> acesso
> interno

no caso, selecionar o bloco e acessar qual a vista... caso não de certo voltamos à ideia acima.

**Comment by luizatonial** [comment]
vou finalizar essa issue já que o dev tem a sua para realização dos ajustes.
