### ISSUE TITLE
Fotos 360° - UFFS Campus Chapecó

### ISSUE THREAD

**Issue by luizatonial** [practice-uffs/programa#1452]
Tirar as fotos 360° da UFFS campus Chapecó e criar um tour no marzipano com as mesmas.

**Comment by gustavoSutil** [comment]
Fotos dos ambientes externos prontas.

**Comment by gustavoSutil** [comment]
ajustando detalhes dos laboratórios ( criando mais fotos).

**Comment by luizatonial** [comment]
aguardo retorno do @gustavoSutil para finalização da issue

**Comment by gustavoSutil** [comment]
fotos ja tiradas e tour ja feito!
