### ISSUE TITLE
Divulgação do app UFFS Boas-Vindas 2023

### ISSUE THREAD

**Issue by brendaellen** [practice-uffs/programa#1459]
Essa issue foi criada com o objetivo de reunir todos os materiais de divulgação do app UFFS-Boas Vindas.
Todos os materiais estarão na [pasta de entrada](https://drive.google.com/drive/folders/1f6VK4AqatyzTD6jZtqQhfqhhKDfvejRt), sendo que na issue #1165 já existem alguns materiais que serão utilizados como base.

**Comment by Saene99** [comment]
Inseri na pasta os ícones do app para serem usados na criação do reel de divulgação. O único ícone que não consegui colocar é o "sobre a cidade", que está diferente no app e no [Figma](https://www.figma.com/file/UsbungQKrKyxKpF4TVNX7t/S%C3%ADmbolos-APP-Boas-vindas?node-id=902-2&t=PcgyA538S3lOqQS4-0). Não sei o que houve.

**Comment by Saene99** [comment]
Coloquei a capa do reel na pasta

**Comment by ghost** [comment]
coloquei na pasta de entrada cards de divulgação do app. vejam o que acham

**Comment by amandasegattob** [comment]
Coloquei o meme com o vídeo na pasta.

**Comment by amandasegattob** [comment]
Coloquei o reels na pasta.

**Comment by ghost** [comment]
coloquei na pasta de entrada o carrossel que eu e a saene fizemos para ficar passando na TV em chapecó.

**Comment by elisribas** [comment]
Cartaz impresso e fixado no campus Chapecó;
Carrossel enviado para divulgação na TV SAE Chapecó.

**Comment by elisribas** [comment]
Pessoal do SAE-CH me retornou e pediu alguns ajustes no carrossel para ficar mais adequado para passar na TV.
Peço que ajustem a arte para que fique em 1920x1080 px, ok? 
Peço ainda que façam uma animaçãozinha, no canva, 
Obrigada.

**Comment by elisribas** [comment]
*animação do tipo transição de slide, ok? é assim o padrão do SAE-CH

**Comment by Saene99** [comment]
Está na pasta, @elisribas

**Comment by Saene99** [comment]
O último material da divulgação do app foi postado. Acho que fizemos um bom trabalho de divulgação e essa issue pode ser finalizada. Bom trabalho, pessoal!
