### ISSUE TITLE
Roteiro - dicas para a produção de videoaula

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#146]
Roteirizar o texto elaborado na tarefa #100.

O roteiro deve conter:

- [x] Narração dividida por partes do vídeo (margem de tempo estipulada);

- [x] Marcações de narração, legenda e possíveis recursos necessários.

[Pasta do drive.](https://drive.google.com/drive/u/0/folders/1HQd6eBfyYUJMFM6dVOZjQkgGqFXbh1nB)

**Comment by alessandrapedrotti** [comment]
A primeira versão do roteiro está pronta.

Seria ótimo se algum bolsista da @practice-uffs/con-midia olhasse o texto e fizesse sugestões de pontos que podem ser melhorados.

**Comment by MaNegrao** [comment]
Pode deixar, eu vou dar uma olhada no roteiro

**Comment by MaNegrao** [comment]
@alessandrapedrotti eu terminei de ler o roteiro e a parte da narração e organização está excelente haha. Eu tenho uma sugestão quanto ao que vai aparecer na tela. Seria interessante deixar claro como esses recursos devem ser e onde devem aparecer, por ex: Aparece o número 10 em tela cheia e em seguida há uma transição para o video exemplo da forma correta. 

São apenas esses detalhes que ao final deixa as coisas mais claras para o editor

**Comment by isabelirk** [comment]
Boa tarde,
Os novos ajustes no roteiro sobre dicas para produção de videoaula foi finalizado. Peço que o responsável verifique o mesmo.
Atenciosamente.

**Comment by alessandrapedrotti** [comment]
@MaNegrao acredito pode ser atribuído um bolsista da equipe de mídia para desenvolver o vídeo.

**Comment by MaNegrao** [comment]
> @MaNegrao acredito pode ser atribuído um bolsista da equipe de mídia para desenvolver o vídeo.

Beleza, irei repassar

**Comment by MaNegrao** [comment]
@alessandrapedrotti acho que o interessante agora é irmos afinando o roteiro com o @luizdameda e dai assim que tiver pronto encerramos essa issue e abrimos uma de vídeo, o que acha?

**Comment by alessandrapedrotti** [comment]
> @alessandrapedrotti acho que o interessante agora é irmos afinando o roteiro com o @luizdameda e dai assim que tiver pronto encerramos essa issue e abrimos uma de vídeo, o que acha?

Concordo.

**Comment by luizdameda** [comment]
Certo! Entre hoje a noite e amanhã vou começar a esquematizar o vídeo. Ao longo do processo vou informando aqui sobre alterações que acho pertinente fazer

**Comment by luizdameda** [comment]
Estava falando com a @amandasegattob e como nesse issue e no issue dela consta a animação numérica para ordenar as dicas e fazer a transição, pensamos em criar essa animação de forma padrão para que possa ser utilizada a mesma em todos os vídeos.

O que acham, @MaNegrao @alessandrapedrotti ?

**Comment by MaNegrao** [comment]
> Estava falando com a @amandasegattob e como nesse issue e no issue dela consta a animação numérica para ordenar as dicas e fazer a transição, pensamos em criar essa animação de forma padrão para que possa ser utilizada a mesma em todos os vídeos.
> 
> O que acham, @MaNegrao @alessandrapedrotti ?

Não entendi exatamente o que é essa animação, é tipo uma transição? Se sim, não vejo problema em termos um padrão, ainda mais esses vídeos instrucionais.

**Comment by alessandrapedrotti** [comment]
> > Estava falando com a @amandasegattob e como nesse issue e no issue dela consta a animação numérica para ordenar as dicas e fazer a transição, pensamos em criar essa animação de forma padrão para que possa ser utilizada a mesma em todos os vídeos.
> > O que acham, @MaNegrao @alessandrapedrotti ?
> 
> Não entendi exatamente o que é essa animação, é tipo uma transição? Se sim, não vejo problema em termos um padrão, ainda mais esses vídeos instrucionais.

Concordo com o @MaNegrao. Acho que seria muito interessante ter essas transições com as cores do programa.

**Comment by luizdameda** [comment]
Certo! Já selecionei boa parte das imagens e já gravei a narração. Assim que terminar, mando a primeira versão aqui para vocês olharem e para irmos moldando as alterações necessárias no vídeo

**Comment by luizdameda** [comment]
Criei um modelo básico, bem simples para fazer a transição de cada tópico de dica. Coloquei o primeiro [nesta pasta](https://drive.google.com/drive/folders/1-4pxm6iZ4l_3f_ZgH6nP59QRy9QFGf1T)

Se puderem olhar e ver se está ok, dai já faço os outros 9 e libero os mesmos para os outros vídeos que também precisam desse tipo de transição de tópicos

**Comment by robisonjose** [comment]
@luizdameda Eu achei bem interessante essa transição. Mas será que não ficaria melhor se aqueles três risquinhos que aparecem por último aparecessem um por um com um intervalo curto de tempo entre a aparição de cada? Parece que aquela aparição ficou meio deslocada do resto. É só uma ideia mesmo.

**Comment by luizdameda** [comment]
> @luizdameda Eu achei bem interessante essa transição. Mas será que não ficaria melhor se aqueles três risquinhos que aparecem por último aparecessem um por um com um intervalo curto de tempo entre a aparição de cada? Parece que aquela aparição ficou meio deslocada do resto. É só uma ideia mesmo.

Acho que ficaria legal mesmo, mas não sei fazer isso kkkk. Peguei os risquinhos prontos do drive já....

**Comment by luizdameda** [comment]
A primeira versão do vídeo encontra-se [nesta pasta](https://drive.google.com/drive/u/1/folders/1Flf863wQg9K5sRrZAxXZKGVeEK3xiOL0)

- Tentei seguir o roteiro ao mais pé da letra possível.

- Optei por trabalhar com uma linha menos formal e mais descontraída, usando GIF's e imagens mais informais, mas isso pode ser completamente mudado.

- Não sou uma pessoa com intonação muito boa, se acharem pertinente regravar alguma parte (ou escolher outra pessoa para gravar), podem falar. Particularmente, o finalzinho eu não gostei e se eu permanecer como narrador já irei alterar isso. 

- O tópico 9 está sem imagem porque, por hora, não encontrei nada para representar o que é narrado.

- Depois que finalizei, assisti novamente e acho que seria interessante colocar a transição também após o tópico 10, antes da frase "não tenha vergonha de gravar!". Da forma que está, ficou meio parecendo que é um continuidade do último tópico, mas na verdade é para ser um encerramento. 


Aguardado retorno e feedbacks, fiz ele para termos uma noção e agora é só trabalhar em cima e ir moldando.

**Comment by alessandrapedrotti** [comment]
> Criei um modelo básico, bem simples para fazer a transição de cada tópico de dica. Coloquei o primeiro [nesta pasta](https://drive.google.com/drive/folders/1-4pxm6iZ4l_3f_ZgH6nP59QRy9QFGf1T)
> 
> Se puderem olhar e ver se está ok, dai já faço os outros 9 e libero os mesmos para os outros vídeos que também precisam desse tipo de transição de tópicos

Eu gostei da fonte que tu usou e da musiquinha. É possível fazer uma versão em que os elementos surgem do meio da tela? Não sei se expliquei bem a ideia, mas acho que vai ficar legal.

**Comment by luizdameda** [comment]
> > Criei um modelo básico, bem simples para fazer a transição de cada tópico de dica. Coloquei o primeiro [nesta pasta](https://drive.google.com/drive/folders/1-4pxm6iZ4l_3f_ZgH6nP59QRy9QFGf1T)
> 
> > 
> 
> > Se puderem olhar e ver se está ok, dai já faço os outros 9 e libero os mesmos para os outros vídeos que também precisam desse tipo de transição de tópicos
> 
> 
> 
> Eu gostei da fonte que tu usou e da musiquinha. É possível fazer uma versão em que os elementos surgem do meio da tela? Não sei se expliquei bem a ideia, mas acho que vai ficar legal.

Acho que entendi a ideia!! Vou tentar fazer isso... inclusive, se souberem de algum aplicativo ou software que faça coisas assim, aceito indicações, estou fazendo bem Canva mesmo, mas não tem tantos recursos 😅

**Comment by luizdameda** [comment]
Fiz essa nova versão conforme a @alessandrapedrotti sugeriu. Ignorem o som porque coloquei o primeiro que apareceu só pra teste kk

[Pasta drive](https://drive.google.com/file/d/174Is6Wi9RTddlHDfTQ2WWXaGuZgS6CW4)

**Comment by mariagelain** [comment]
> A primeira versão do vídeo encontra-se [nesta pasta](https://drive.google.com/drive/u/1/folders/1Flf863wQg9K5sRrZAxXZKGVeEK3xiOL0)
> 
> * Tentei seguir o roteiro ao mais pé da letra possível.
> * Optei por trabalhar com uma linha menos formal e mais descontraída, usando GIF's e imagens mais informais, mas isso pode ser completamente mudado.
> * Não sou uma pessoa com intonação muito boa, se acharem pertinente regravar alguma parte (ou escolher outra pessoa para gravar), podem falar. Particularmente, o finalzinho eu não gostei e se eu permanecer como narrador já irei alterar isso.
> * O tópico 9 está sem imagem porque, por hora, não encontrei nada para representar o que é narrado.
> * Depois que finalizei, assisti novamente e acho que seria interessante colocar a transição também após o tópico 10, antes da frase "não tenha vergonha de gravar!". Da forma que está, ficou meio parecendo que é um continuidade do último tópico, mas na verdade é para ser um encerramento.
> 
> Aguardado retorno e feedbacks, fiz ele para termos uma noção e agora é só trabalhar em cima e ir moldando.

gostei muito da primeira versão usando conteúdos mais informais de imagem e de video, só peço para que você se atente a resolução e a qualidade dos materiais usados

**Comment by alessandrapedrotti** [comment]
> Fiz essa nova versão conforme a @alessandrapedrotti sugeriu. Ignorem o som porque coloquei o primeiro que apareceu só pra teste kk
> 
> [Pasta drive](https://drive.google.com/file/d/174Is6Wi9RTddlHDfTQ2WWXaGuZgS6CW4)

Eu gostei bastante! Acho que a @estelavilasboas pode ter dicas de softwares pra essas coisas

**Comment by luizdameda** [comment]
Fiz a alteração das transições, arrumei algumas partes da narração, alterei algumas imagens que estavam com a qualidade muito ruim e adicionei algumas novas. Acredito que esteja ok agora, mas qualquer alteração que acharem pertinente fazer, podem falar que faço. 

Após a revisão, pretendo já adicionar a legendar e finalizar essa issue. 

[Pasta Drive](https://drive.google.com/drive/u/1/folders/1-4pxm6iZ4l_3f_ZgH6nP59QRy9QFGf1T)

**Comment by alessandrapedrotti** [comment]
@luizdameda ficou muito legal!!! Eu adorei a montagem com vídeos engraçadinhos que tu fez.

**Comment by luizdameda** [comment]
Para melhor organização do fluxo de trabalho, criei uma issue específica para o vídeo. Acredito que essa issue referente ao roteiro pode ser fechada @MaNegrao

**Comment by MaNegrao** [comment]
Tarefa Finalizada :D
