### ISSUE TITLE
Cards postagens março 2023

### ISSUE THREAD

**Issue by Saene99** [practice-uffs/programa#1461]
Nessa issue criaremos os cards das postagens do mês de Março de 2023.

**Comment by amandasegattob** [comment]
Criei as pastas dessa issue no Google Drive:

 [Pasta da issue] (https://drive.google.com/drive/folders/1K727DZLU4tuxNVP81BDUU9sVJtwzW2O7?usp=share_link)
🔽 [Entrada] (https://drive.google.com/drive/folders/1bh4EadBGOtHfTnRg4itcGD-L1Y77jLMC?usp=share_link)
🔼 [Saída] (https://drive.google.com/drive/folders/1x99Blc7yse87uKYZ7mRdaiV7cXjA5PQ5?usp=share_link)

**Comment by amandasegattob** [comment]
Criei as pastas dessa issue no Google Drive:

[Pasta da issue](https://drive.google.com/drive/folders/1K727DZLU4tuxNVP81BDUU9sVJtwzW2O7?usp=share_link)
🔽 [Entrada](https://drive.google.com/drive/folders/1bh4EadBGOtHfTnRg4itcGD-L1Y77jLMC?usp=share_link)
🔼 [Saída](https://drive.google.com/drive/folders/1x99Blc7yse87uKYZ7mRdaiV7cXjA5PQ5?usp=share_link)

**Comment by ghost** [comment]
coloquei os cards das dicas de volta às aulas na pasta de entrada. fiz o card bem simples, com elementos que eu mesma fiz, então vejam se está bom mesmo ou nada a ver. também fiz alterações no roteiro, então é necessário fazer revisão textual do conteúdo nos cards

**Comment by Saene99** [comment]
> coloquei os cards das dicas de volta às aulas na pasta de entrada. fiz o card bem simples, com elementos que eu mesma fiz, então vejam se está bom mesmo ou nada a ver. também fiz alterações no roteiro, então é necessário fazer revisão textual do conteúdo nos cards

Estão bem legais, Júlia. Fiz minhas sugestões lá no Figma, olha lá o que acha

**Comment by ghost** [comment]
coloquei na pasta de entrada a versão 2 do card de volta as aulas, com as alterações da saene.

**Comment by amandasegattob** [comment]
Oi gurias, fiz os cards de dicas para escrever roteiro, ta no [figma](https://www.figma.com/file/vKsmv9TiwF1RFERsOEs31T/Issues---Instagram?node-id=2760-633&t=sFcXgyiOdX64w0ev-0) (eu ainda não sei como baixar as imagens separadas kkk). 
Também comecei o card da editora UFFS, que a gente tinha combinado que não ia mais fazer reels. Eu pensei em gravar a tela do catálogo, e colocar passando no mokcup do notebook. O que acham?

**Comment by Saene99** [comment]
> Oi gurias, fiz os cards de dicas para escrever roteiro, ta no [figma](https://www.figma.com/file/vKsmv9TiwF1RFERsOEs31T/Issues---Instagram?node-id=2760-633&t=sFcXgyiOdX64w0ev-0) (eu ainda não sei como baixar as imagens separadas kkk). Também comecei o card da editora UFFS, que a gente tinha combinado que não ia mais fazer reels. Eu pensei em gravar a tela do catálogo, e colocar passando no mokcup do notebook. O que acham?

Eu baixo e coloco aqui, Amanda. Sobre o da editora, é uma boa ideia, mas no Figma não tem como colocar vídeo, ou pelo menos até onde eu sei não tem. Daria de fazer o carrossel no Figma, deixando o slide que colocará o vídeo apenas com a arte de fundo e inserir o mockup e o vídeo por outra plataforma.

**Comment by amandasegattob** [comment]
Fiz isso pelo capcut. Coloquei na pasta.

**Comment by ghost** [comment]
fiz algumas propostas de mudança no card da editora uffs da amanda e comecei a fazer propostas para os cards de escrever roteiro, mas não acho que ta ficando bom. não sei kk a saene que é melhor em revisar essas coisas

**Comment by Saene99** [comment]
> fiz algumas propostas de mudança no card da editora uffs da amanda e comecei a fazer propostas para os cards de escrever roteiro, mas não acho que ta ficando bom. não sei kk a saene que é melhor em revisar essas coisas

kkkkk vou revisar assim que possível :D

**Comment by Saene99** [comment]
Fiz a revisão da editora lá no Figma, amanhã faço do sobre escrever roteiro

**Comment by amandasegattob** [comment]
Coloquei a segunda versão do post da editora na pasta.

**Comment by Saene99** [comment]
@amandasegattob fiz a revisão do post sobre roteiro de vídeo lá no Figma

**Comment by ghost** [comment]
Escrevi um card para a cartilha do Moodle, não sei muito bem se o que escrevi é o que tinham pensado, mas aceito sugestões

**Comment by amandasegattob** [comment]
Coloquei a segunda versão do post sobre roteiro de vídeo na pasta.

**Comment by Saene99** [comment]
> Escrevi um card para a cartilha do Moodle, não sei muito bem se o que escrevi é o que tinham pensado, mas aceito sugestões

Vamos falar do conteúdo na #1421 kkkkkk
