### ISSUE TITLE
Reels postagens março 2023

### ISSUE THREAD

**Issue by amandasegattob** [practice-uffs/programa#1462]
Nessa issue criaremos os reels do mês de Março de 2023.

**Comment by amandasegattob** [comment]
Criei as pastas dessa issue no Google Drive:

[Pasta da issue](https://drive.google.com/drive/folders/1O4CiM57_vsVFKRYipdzoKBhf9PAq3izQ?usp=share_link)
🔽 [Entrada](https://drive.google.com/drive/folders/1EAdR8hFjnQnW_W1eHfziHXpdMcXdfPuE?usp=share_link)
🔼 [Saída](https://drive.google.com/drive/folders/1-9LMrARLB00Akos5NfLLEKolnYLfxcJh?usp=share_link)

**Comment by ghost** [comment]
coloquei o reels da scielo na pasta de entrada. ficou com 1 min e 10s. muito comprido? tenho que falar mais rápido?

**Comment by Saene99** [comment]
Eu achei muito bom, Júlia. Na minha opinião está ótimo assim :D 
Lembrando que tem que colocar a vinheta no final do vídeo e legendar

**Comment by ghost** [comment]
> Eu achei muito bom, Júlia. Na minha opinião está ótimo assim :D Lembrando que tem que colocar a vinheta no final do vídeo e legendar

simmm tenho que fazer uma capa para ele também. vou mexer nisso agora

**Comment by amandasegattob** [comment]
Eu tenho uns apontamentos p edição:

- No início do vídeo (até 00:05) talvez seria legal deixar o vídeo um pouco opaco e colocar uma capa com título.
- Eu deixaria o que aparece 00:18 até 00:23, quando tu para de falar dos índices
- Em 00:58, eu cortaria essa parte e deixaria só a tela que aparece "filtros, ordenar por.."
![image](https://user-images.githubusercontent.com/71669953/227365852-56ffe70b-0101-483e-b65c-1cedffdbfae0.png)

Outra coisa que eu acho legal a gente se atentar, é manter um padrão de como a gente grava a tela do celular, se no modo escuro ou no modo claro, eu acho no modo claro mais bonito, mas aí é de gosto.

No resto eu achei muito bom, super simples e útil, bem como tem que ser!

**Comment by Saene99** [comment]
Eu concordo sobre padronizar com o modo claro

**Comment by ghost** [comment]
fiz uma proposta de capa para o reels da scielo, vejam o que acham. está na pasta de entrada

**Comment by ghost** [comment]
coloquei o reels com alterações. de fato ficaria mais bonito no tema claro... vejam o que acham. se acharam ruim eu gravo de novo, se estiver bom, eu legendo

**Comment by ghost** [comment]
coloquei o reels do email institucional na pasta de entrada. a imagem preta no começo vou substituir pela capa, que ainda não fiz. o fim achei que fica muito tempo mostrando a vinheta, mas eu não sabia o que mais colocar. aceito sugestões!

**Comment by amandasegattob** [comment]
Oie!
No reels da Scielo tem um barulinho em 00:04, eu não identifiquei o que é, mas talvez com a música de fundo não dê p notar. Na parte inicial eu acho que só deixaria o título, sem a imagem de livros e o ícone, talvez. 

No reels do email, na parte inicial eu colocaria um vídeozinho acessando o site da uffs e deixaria rolando até 00:09, e depois colocaria a parte acessando o gmail, p ficar sincronizado enquanto digita e fala. Nas partes digitando os logins eu colocaria mais rapidinho também, p sincronizar. Na parte que surge o drive, a transição ficou meio deslocada, acho que daria p cortar de 00:31 a 00:33. No final, a fala ficou um pouquinho cortada, talvez daria p congelar alguma partezinha do vídeo p ganhar tempo. Ah, o vídeo tá na proporção de reels? Em cima tá meio cortado, talvez desse p ver disso. De resto achei ótimo, ficou bem dinâmico!

**Comment by Saene99** [comment]
Desculpa a demora para revisar, Júlia.

**Scielo**: Sei que foi uma sugestão da Amanda em colocar uma capa com título no início, mas eu acho que o início da primeira versão tinha ficado melhor rsrs. É que era mais dinâmico, já iniciava "colocando a mão na massa" e mostrava qual era o site. Mas de qualquer forma, se vocês gostam mais do início da segunda versão, eu acho que deveria ser um pouco mais dinâmico, talvez surgir as frases conforme a narração, tipo "como fazer pesquisa avançada" surgindo da esquerda para direita e "no site da scielo" surgindo da direita para esquerda e o ícone aparecendo um pouco depois, não sei... é uma ideia para não ficar uma imagem parada no início.

**Email**: Eu também acho que não precisa iniciar com uma capa, pelos mesmos motivos de ficar muito parado e não despertar tanta atenção. Eu acho que uma ideia legal seria substituir a parte preta do início por um videozinho da UFFS, filmando algum bloco, o totem do "I <3 UFFS" ou algo assim (eu mesma poderia gravar algo se acharem interessante). E talvez algo no mesmo sentido para encerrar... daria de gravar o saguão do bloco A do ponto de vista do último andar, com o pessoal nos pufs, sofás, remeteria aos estudantes conversando com os amigos (talvez eu tenha viajado aqui kkkk).
Uma última coisa é que eu não gostei muito da parte que falou do drive, eu achei estranho mostrar nossas planilhas lá kkkk mas não tenho sugestão de alteração ou melhoria :/

**Comment by ghost** [comment]
postei o reels da versão três do scielo, penei para fazer assim kk me digam se está bom ou se edito novamente

**Comment by Saene99** [comment]
Eu gostei, Júlia. Só faltou a vinheta no final kkkkk

**Comment by ghost** [comment]
vídeo da scielo legendado na pasta de entrada!!

**Comment by Saene99** [comment]
Por mim está ótimo, Júlia.
Coloquei uns vídeos da UFFS na pasta, se achar que fica legal colocar no reels do email

**Comment by ghost** [comment]
coloquei o vídeo do email institucional na pasta de entrada, vejam se está bom. só consegui finalizar ele segunda agora porque estava guardando os vídeos do tutorial google ser postado no canal.

**Comment by amandasegattob** [comment]
Oie! Eu acho que dá pra corrigir algumas coisas da legenda, como pontos finais e início de frase com letra maiúscula. Talvez daria pra colocar ela na fonte roboto, não sei se ela já tá, só pra termos um padrão mesmo.

**Comment by brendaellen** [comment]
Revisei o roteiro sobre validação de accs e deixei comentários. Se tiver mais algum roteiro para revisar, podem me marcar aqui na issue.

**Comment by ghost** [comment]
reels legendado do e-mail institucional e a capa estão na pasta de entrada

**Comment by ghost** [comment]
alterei o roteiro do reels de validação do ACC de acordo com as propostas da brenda. alguém quer fazer a narração desse reels?

**Comment by brendaellen** [comment]
Elaborei o conteúdo para os stories de engajamento sobre os estúdios.

**Comment by brendaellen** [comment]
Criei o conteúdo para os stories sobre accs.
