### ISSUE TITLE
Sequência de posts sobre o CapCut

### ISSUE THREAD

**Issue by amandasegattob** [practice-uffs/programa#1464]
Essa issue tem como objetivo a criação de posts (reels, cards) sobre o app CapCut.

**Comment by amandasegattob** [comment]
Criei as pastas dessa issue no Google Drive:

[Pasta da issue](https://drive.google.com/drive/folders/1mVA_NcQw991rnu7JTlAOWSArZcA553tn?usp=sharing) 
🔽 [Entrada](https://drive.google.com/drive/folders/1tyq5HvAEy-4RKW5ZjjBqRXkpl-wHDnP_?usp=share_link)
🔼 [Saída](https://drive.google.com/drive/folders/1ILaPAgHKEsLTM22_VtayshwDNSxlqyx6?usp=share_link)

**Comment by amandasegattob** [comment]
Oi gurias! Escrevi os roteiros inicias sobre o CapCut. Peço que revisem e vejam o que acham. Escrevi sobre o básico, para depois começarmos a fazer vídeos mais específicos. 
Fiquem a vontade para alterarem o documento, acrescentar coisas etc.

**Comment by ghost** [comment]
fiz algumas sugestões no roteiro, amanda. mas ficou muito legal. eu não conheço o capcut então achei bem interessante

**Comment by Saene99** [comment]
Eu achei os conteúdos muito legais, Amanda. Será que não seria melhor colocar o último reels como segundo? Pois ele fala sobre tamanhos e camadas, acho que seria bom falar das camadas antes de falar de colocar texto e áudio. E assim também já pegaria a onda de: primeiro falar das funcionalidades básicas e depois ir dando dicas, tipo colocar áudio, texto, legenda, alterar fundo, fazer transição, algo assim

**Comment by amandasegattob** [comment]
Fiz as alterações sugeridas e alterei a ordem, fica melhor mesmo. @brendaellen consegue revisar?

**Comment by brendaellen** [comment]
Revisei quatro dos cinco roteiros, e criei duas legendas.  Fiquei em dúvida se o último roteiro está finalizado ou em andamento.

**Comment by amandasegattob** [comment]
@MariaLuizaReviliau @robisonjose @brendaellen aqui estão os roteiros daqueles reels para serem narrados que tinha falado na reunião. Coloquei o nome de cada um como comentário.

**Comment by robisonjose** [comment]
Qual é o prazo para envio da narração?

**Comment by amandasegattob** [comment]
> Qual é o prazo para envio da narração? 

Acredito que pode ser até o fim da semana, tu consegue?

**Comment by robisonjose** [comment]
Beleza, consigo sim!

**Comment by robisonjose** [comment]
Narração feita e postada na pasta de entrada.

**Comment by amandasegattob** [comment]
coloquei o primeiro reels na pasta de entrada

**Comment by amandasegattob** [comment]
coloquei os cards na pasta de saída

**Comment by ghost** [comment]
gostei do reels! parabens!
acho que no começo poderia ter outro conteúdo e aparecer o aplicativo apenas quando é falado "logo que abrimos o aplicativo..."
na narração fala "editar, som e camada" mas na verdade é "editar, áudio e camada", o que acham?
e no fim, quando ele fala "como você pode ver, o capcut..." será se não seria levar deixar o vídeo que foi todo editado durante o reels rodar um pouco?

**Comment by brendaellen** [comment]
Inseri a narração do reels na pasta de entrada. 
Tem algum conteúdo nesta issue para revisar?

**Comment by amandasegattob** [comment]
> Inseri a narração do reels na pasta de entrada. 
> 
> Tem algum conteúdo nesta issue para revisar?

Oie, acho que não. Se tu quiser dá pra fazer a legenda dos outros reels.

**Comment by amandasegattob** [comment]
Coloquei o primeiro reels na pasta de saída e já comecei a editar os outros.

**Comment by ghost** [comment]
vídeo 1 foi postado!

**Comment by amandasegattob** [comment]
Os 3 reels estão na pasta de entrada, tinha esquecido de registrar aqui.
