### ISSUE TITLE
Divulgação do Tour Virtual

### ISSUE THREAD

**Issue by ghost** [practice-uffs/programa#1465]
Essa issue é destinada para toda a campanha de divulgação do tour virtual

**Comment by amandasegattob** [comment]
Criei as pastas dessa issue no Google Drive:

 [Pasta da issue](https://drive.google.com/drive/folders/1uoEggj0nJT5a7iLMIUzw4rNFaF9NBl0B?usp=share_link)
🔽 [Entrada](https://drive.google.com/drive/folders/1tmXHMEiCVbYgEy7ft3CFavuDL4RNRG0_?usp=share_link)
🔼 [Saída](https://drive.google.com/drive/folders/1tmXHMEiCVbYgEy7ft3CFavuDL4RNRG0_?usp=share_link)

**Comment by ghost** [comment]
escrevi algumas propostas de divulgação do tour, mas detestei todas kkk

**Comment by amandasegattob** [comment]
Deixei alguns comentários, mas achei as ideias muito boas!

**Comment by Saene99** [comment]
Vi essa issue por acaso rsrsr
@julia-zanini  quando criar a issue, deve colocar as participantes no "assignees" e selecionar "redes sociais" no projeto. Caso contrário não recebemos email sobre a issue :D 
Coloquei a Luiza também, acho que ela pode contribuir muito com as ideias da divulgação.

Eu gostei dos materiais, Júlia, e também gostei dos apontamentos da Amanda. Eu só tenho uma sugestão: falar mais sobre o quão importante é o Tour para uma pessoa de longe que quer estudar na UFFS. Sei que dificilmente esse possível estudante será nosso seguidor, mas talvez falar assim "conhece alguém que queira estudar na uffs" ou algo assim.

**Comment by Saene99** [comment]
Deixando registrado [aqui](https://www.youtube.com/watch?v=2uh7p5f7HOE) a inspiração de vídeo que a Elis deu, onde uma pessoa fala sobre o conteúdo e algumas cenas vão passando.

**Comment by ghost** [comment]
escrevi outra proposta de reels, dessa vez pensando como se a luiza estivesse narrando, bem no estilo no vídeo que a elis passou. vejam o que acham

**Comment by Saene99** [comment]
Eu achei muito bom, Júlia. Deixei algumas sugestões no documento

**Comment by amandasegattob** [comment]
Eu gostei bastante!! Também deixei algumas sugestões no documento.

**Comment by ghost** [comment]
conclui as revisões das sugestões! @luizatonial poderia ler os roteiros que estamos trabalhando e opinar?

**Comment by luizatonial** [comment]
fiz umas pequenas alterações de algumas palavras... além de que fiquei na dúvida sobre a:
- divulgação 1: será que não precisava citar "UFFS" em algum lugar?
- divulgação 2: deixei sugestões no doc
- divulgação 3: deixei no doc

**Comment by ghost** [comment]
acrescentei as sugestões da luiza. @brendaellen poderia fazer a revisão final do material?

**Comment by brendaellen** [comment]
> acrescentei as sugestões da luiza. @brendaellen poderia fazer a revisão final do material?

@julia-zanini revisei os materiais, e deixei dois comentários com sugestões de ajustes para que você verifique se concorda ou não.
Vi que todos os roteiros estão sem legenda, e acabei não criando pois não não sei qual será a finalidade de cada um ou onde será postado, mas se precisar que eu crie, é só me marcar novamente;)

**Comment by luizatonial** [comment]
estou colocando as gravações na pasta @julia-zanini @amandasegattob vou deixar as duas que considero melhores logo na pasta de entrada e outras em uma subpasta pra caso precisem pra edição

**Comment by amandasegattob** [comment]
Acabei não avisando aqui, mas o reels está na pasta. Também já estou trabalhando no cartaz para os campi e na apresentação para a TV do SAE, em Chapecó.

**Comment by ghost** [comment]
os cards de divulgação do tour estão na pasta de entrada

**Comment by ghost** [comment]
cartaz para divulgação em laranjeiras e chapecó na pasta de entrada

**Comment by ghost** [comment]
coloquei na pasta de entrada o cartaz para a TV do SAE de Chapecó

**Comment by ghost** [comment]
arrumei o cartaz para a TV do SAE Chapecó

**Comment by amandasegattob** [comment]
@elisribas coloquei o vídeo para a TV na pasta. Eu tinha feito e esqueci de colocar aqui, perdão!!

**Comment by elisribas** [comment]
Divulgado na TV do SAE Chapecó. 💯

**Comment by brendaellen** [comment]
Elaborei o texto para o e-mail de divulgação do tour nos demais campi.

**Comment by amandasegattob** [comment]
Eu esqueci completamente do email, revisei agora e deixei algumas sugestões. Algo que pensei agora, é de colocar algo sobre mandar p algum amigo interessado em fazer ingressar na uffs, já que logo começa o SISU.

**Comment by ghost** [comment]
> Eu esqueci completamente do email, revisei agora e deixei algumas sugestões. Algo que pensei agora, é de colocar algo sobre mandar p algum amigo interessado em fazer ingressar na uffs, já que logo começa o SISU.

Eu tinha a impressão de que o email seria enviado para os servidores, não alunos

**Comment by amandasegattob** [comment]
Envia para o setor que divulga as coisas na UFFS, pra eles divulgarem pra todos (servidores e estudantes), não?

**Comment by elisribas** [comment]
> Elaborei o texto para o e-mail de divulgação do tour nos demais campi.

Não localizei o e-mail, @brendaellen, pode me indicar o caminho de onde está?

**Comment by ghost** [comment]
> > Elaborei o texto para o e-mail de divulgação do tour nos demais campi.
> 
> Não localizei o e-mail, @brendaellen, pode me indicar o caminho de onde está?

está no fim deste arquivo: https://docs.google.com/document/d/1AlAJgM8cVyOKMqu3sj8H9bPQ1fALP7Dp--kxkuvs2-A/edit

**Comment by ghost** [comment]
fiz algumas propostas no texto

**Comment by brendaellen** [comment]
Verifiquei todos os comentários e sugestões no texto do e-mail de divulgação do tour, e também fiz alguns ajustes. Se não houver nenhuma objeção, o texto está pronto para ser encaminhado.

**Comment by amandasegattob** [comment]
O email foi enviado, acredito que essa issue pode ser finalizada.
