### ISSUE TITLE
Testes Iniciais - Tour Virtual

### ISSUE THREAD

**Issue by luizatonial** [practice-uffs/programa#1466]
Issue destinada à testagem da **Fase 1 do Projeto Tour Virtual,** que corresponde à:
- página inicial do site: https://practice.uffs.edu.br/tour-virtual/
- mapa do campus de Laranjeiras do Sul: https://practice.uffs.edu.br/tour-virtual/ls
- street view (visão panorâmica) do campus de Laranjeiras do Sul: https://practice.uffs.edu.br/tour-virtual/ls/panorama

Caso encontrem problemas e algum ajuste que precisa ser feito, deixe nos comentários. Quem tem permissão de administrador também recomendo testar a inserção e modificação das informações dos blocos.

**Comment by luizatonial** [comment]
Na tela inicial:
- colocar todos os campi com nome e foto (na rolagem)
- colocar todos os mapas dos campi

No mapa de Laranjeiras do Sul:
- o alinhamento dos tópicos deu algum problema (mas o texto está ficando em tópicos, negrito e itálico)
![image](https://user-images.githubusercontent.com/71669357/227208245-ff152b86-3d5c-4b0e-8da1-f9d9b20d5f05.png)

**Comment by robisonjose** [comment]
Fiz uma pasta com o nome de "[Revisões e testes](https://drive.google.com/drive/u/0/folders/17pN_TKWq6G7-9W1JBQrBA9Z-L0e71KUe)" dentro da pasta do projeto Tour Virtual. 

Lá coloquei o vídeo que gravei fazendo os testes iniciais.

**Comment by robisonjose** [comment]
Em 08:15 até 09:33 eu faço alguns comentários em relação aos ícones.

@luizatonial e @julia-zanini

**Comment by ghost** [comment]
Meus apontamentos a respeito de coisas que o robison colocou no vídeo:

ali na parte que fica rolando os campi (que por enquanto tem 3, mas que vão ser todos os 6), não seria interessante se fosse possível rolar para o campus que a pessoa quer ver e poder clicar nele e abrir o mapa? além da possibilidade de abrir os mapas a partir dos mesmos na parte inferior da tela. (igual o robison indicou no vídeo dele)

eu discordo do robison de que não deveria poder mexer no mapa que não está pronto, eu acho que tem que deixar essa possibilidade sim, mesmo com informações incompletas e faltando, não vejo problema em mostrar o processo da produção, em vez de apenas o produto final. eu acho legal deixar os mapas incompletos clicáveis, mesmo sem os nomes corretos etc.

também acho, como o robison, que os mapas têm que estar centralizado na tela, quando clicamos nele. já tinha falado sobre isso com o ryan e ele falou que ia comentar com o adriano.

no tutorial eu acho que tem que ter a opção de encerrar sim, diferente da opinião do robison. mas concordo com os apontamentos sobre a lupa na barra de pesquisa e também sobre a legenda.

concordo com o que o robson disse sobre destacar mais os blocos visualmente quando estamos com as informações dele aberto na lateral. concordo a respeito da opção de abrir a foto e não a panorâmica, na barra de informações, e ver a panorâmica apenas pelo botão "visão panorâmica"

sobre os ícones, eu acho que eles deveriam aparecer apenas quando a gente der zoom no mapa. quando for aproximando vai aparecendo os ícones que estão nas construções pequenas (acho que o ícone no RU é o único que tem que ficar constante). sobre os ícones dos esportes, eu acho que deveria ter um tipo genérico só, então descordo do robison, porque se não fica muita informação, e a pessoa fica tentando adivinhar que esporte é aquele (como por exemplo do slackline), enfim, prefiro com um ícone genérico de esporte como está.

sobre o tour, tinha os nomes de "caminho" mas tínhamos combinado de tirar e deixar sem nada. mas acho que dá para testar com os nomes caminho. mas não sei se ficaria muito melhor não...

Sobre apontamentos que o robison não fez no vídeo dele mas eu estou fazendo:

naquele primeiro logo da UFFS que aparece na tela inicial, achei ele muito embaçado, teria como fazer ele ficar mais nítido?

no mapa, no conteúdo do livro, que tem as instruções, precisa corrigir o segundo balão: "Clique **aqui abrir** o menu lateral e entenda o que representa cada elemento presente no mapa." está faltando o PARA ali na parte que deixei em negrito.

ainda no mapa, não entendi a funcionalidade no olho no canto direito. ele deveria fazer algo?

**Comment by marconiryan** [comment]
### Pagina Inicial
Sobre o video eu concordo sobre tudo o que foi comentado sobre a pagina inicial.
##
### Mapa

Sobre a centralização do mapa existe uma  complexidade em relação ao tamanho da tela do dispositivo e também como é implementado o mapa no Figma.

Se eu usar a referencia do meio no meu dispositivo, talvez dê problemas em dispositivos com telas maiores e menores que a minha. Posso deixar mais ou menos centralizado, mas isso não garante nada.

Em relação a construção do mapa, não necessariamente que o meio da imagem é o meio do mapa.  Ai não existe alguma referencia que eu posso usar como meio.  Como por exemplo:
![image](https://user-images.githubusercontent.com/86175804/227424758-da0e823b-9cb5-4ef5-930d-ad12e7e67924.png)

##

Sobre o zoom eu vou dar um jeito de deixar isso Ok. Acontece esse bug pq do jeito que está implementado, o zoom entra em conflito com o limite do mapa. Ai no caso não acontece nada e fica travado

## 

Aquele problema com o  botão de "arrastar e entrar no tour" acontece em blocos pequenos. Acontece uma intersecção entre o bloco e o icone. Acontece que quando o bloco é muito pequeno, isso as vezes não é detectado. Vou tentar aumentar a area disso

## 
O que a Julia comentou   "_eu acho que eles deveriam aparecer apenas quando a gente der zoom no mapa_". No momento se torna inviável fazer isso pela complexidade

##

No resto, acho que é tudo possivel e válido de ser implementado sobre o mapa

##
### Tour

Sobre não ter nada escrito nos "caminhos"  foi decidido numa reunião que não teria nenhum nome. Foi dado a sugestão de mudar o icone quando é caminho.

##

**Comment by marconiryan** [comment]
Sobre o tutorial, peço para que a @julia-zanini faça um roteiro do que deve ser escrito.

_"não entendi a funcionalidade no olho no canto direito. ele deveria fazer algo?"_ Foi mudado o icone, mas ela serve para voltar ao estado original do mapa. Ou seja, sem zoom e centralizado (deveria)  como na primeira vez que se entra no mapa.

**Comment by marconiryan** [comment]
Sobre o alinhamento com o ponto, a principio foi resolvido. No caso, foi tirado o ponto e isso terá que ser feito manualmente, caso queira.  Esse [site](https://www.symbolspy.com/dot-symbol.html) pode ajudar

Peço para que testem com Ctrl + f5, para nao haver cache do navegador. (Nas proximas issues vou resolver esse problema de cache do navegador tambem)

![image](https://user-images.githubusercontent.com/86175804/227428576-22e722c5-e68f-4354-afc1-38a20a1c0aad.png)

**Comment by luizatonial** [comment]
Certo, já que todos já contribuíram vou deixar algumas opiniões também... (meio que tentando resumir tudo)

**PAGINA INICIAL**
- [x] na rolagem: colocar todos os campi com seu nome e fotos
- [ ] na rolagem: alterar fotos com escritos ou elementos estranhos
- [x] no início da página (tirar link para a página do practice do logo do tour)
- [x] colocar todos os mapas dos campi (sem legenda e talvez sem caminhos) - vou ajudar verificar como fica melhor esse aqui
- [x] ajustar largura da imagem com os logos do practice
- [x] na parte do "explore o tour" verificar se as três caixinhas serão clicáveis ou não
- [x] permitir que o usuário selecione o campus que deseja visualizar, seja clicando nos mapas ou lá em cima na rolagem selecionando seu campus
- [x] colocar ícones clicáveis redirecionando para as redes do practice e da uffs no fim da página

**Comment by marconiryan** [comment]
Criei uma [issue](https://github.com/practice-uffs/tour-virtual/issues/97) no repositório do tour.

**Comment by luizatonial** [comment]
Dando sequência às outras telas:

**MAPA DE LARANJEIRAS**
- [x] Tela inicial com o mapa centralizado na tela em um tamanho que dê para visualizar todos os campi (se precisar de algum ajuste no figma podem me avisar pq anteriormente tinha nome e legenda então ele está um pouco deslocado mesmo em alguns casos, não sei se precisa mexer na imagem ou conseguem ajustar direto no site).
- [x] Verificar problema no zoom in/out/centralizar no mapa
- [x] Abrir os mapas sempre com a "legenda" aberta 
- [x] Alterar a posição do icone do livro, de instruções, para o lado direito, junto aos outros ícones
- [x] Fazer as instruções abrirem na primeira vez que o usuário abre a página
- [x] Colocar uma lupa para pesquisa na barra de pesquisa
- [ ] Destacar os blocos em que tem visão panorâmica
- [ ] Destacar no mapa o bloco que foi selecionado ou pesquisado
- [x] Sobre os textos em tópico já pedi para a júlia inserir as marcações manualmente
- [ ] Verificar questão de tópico aparecer como elemento clicável e não ser

**Comment by luizatonial** [comment]
> Sobre o tutorial, peço para que a @julia-zanini faça um roteiro do que deve ser escrito.
> 
> _"não entendi a funcionalidade no olho no canto direito. ele deveria fazer algo?"_ Foi mudado o icone, mas ela serve para voltar ao estado original do mapa. Ou seja, sem zoom e centralizado (deveria) como na primeira vez que se entra no mapa.

![image](https://user-images.githubusercontent.com/71669357/227588022-eac5fe30-5376-409b-945e-529a01f2d398.png)

**Comment by zorteaadriano** [comment]
Ajustes sugeridos na reunião 27/03:
- Foto do meu lateral abrir popup com a foto.
- Ícone do livro ficar fora da barra de pesquisa.
- Abrir as explicações ao abrir a página pela primeira vez.
- Editar botão de centralizar: https://icons8.com.br/icon/48096/centralizar

**Comment by luizatonial** [comment]
* Remover acesso (no sentido de poder clicar/interatividade) dos campi que não estão prontos, deixar somente liberado para chapecó e laranjeiras do sul.
* Mais adiante criar um modo em que as legendas apareçam com o zoom (etapas futuras)

**Comment by luizatonial** [comment]
### TESTES 31/03
@marconiryan @zorteaadriano 
Conversei com o @robisonjose e a @julia-zanini, além do que foi dito no telegram, e vou listar algumas possíveis alterações:

**TELA INICIAL**
- talvez podemos cortar a borda superior das imagens pra tirar o logo da UFFS (que está nos vídeos onde retiramos as fotos), além disso, a escrita com o nome do campus está bem em cima da seta
![image](https://user-images.githubusercontent.com/71669357/229188410-65e2471c-8992-4cb6-8366-36d716e27f48.png)
_(como ajustes menos prioritários da pra deixar mais uns segundinhos de tempo pra cada campi e eu não se tem como fazer ir do último pro primeiro campus?)_

- quando clicamos em acessar o tour, pode abrir a caixa para selecionarmos qual campus desejamos ver
![image](https://user-images.githubusercontent.com/71669357/229188642-d2a492c9-4124-43c6-bd58-a21513ddbb07.png)

- aqui foi comentado na outra revisão que tava meio distorcido... 
![image](https://user-images.githubusercontent.com/71669357/229188791-ec44340a-c805-48cb-820b-a4ab4b6563b4.png)

- daria pra por o nome dos campus tipo assim?
![image](https://user-images.githubusercontent.com/71669357/229189123-21d551dd-2f22-48b9-b5b7-e4d9c831f57e.png)

**Comment by luizatonial** [comment]
**VISTA PANORÂMICA**

- Este botão poderia voltar para o mapa e não para a tela inicial... se for possível
- @marconiryan consegue trocar para "Bloco dos Professores"? (a gente mudou pq aq em erechim tava pintado esse nome no bloco)
![image](https://user-images.githubusercontent.com/71669357/229190047-2c3c8be9-a04c-4db4-9737-85795a8a10cd.png)

**Comment by luizatonial** [comment]
**MAPA CAMPUS**

- uma sugestão sobre o destaque nos blocos:
![image](https://user-images.githubusercontent.com/71669357/229190397-1160fa1a-c98f-4c17-aeef-ea14b5ede11a.png)
- não sei se é pq eu ja entrei mil vezes no site kkkkkkkk mas as instrução tão aparecendo na tela na primeira vez?
- _o robison achou alguns problemas na hora q ele colocava o bonequinho no mapa... tipo coisas próximas (acho que isso depende do usuário não sei se conseguem mexer nisso ou não >>> ISSO É MENOS PRIORITÁRIO)_

**Comment by ghost** [comment]
me incomodou a forma como, na página inicial, o nome do campus muda de lugar quando é dos campi com nomes grandes

![image](https://user-images.githubusercontent.com/106833148/229194887-931f74ce-14d9-4ce3-8575-9ad23b42b663.png)


![image](https://user-images.githubusercontent.com/106833148/229195016-d17fd4ab-3a5f-4f1c-85cc-d5b45260e5b4.png)


todos os campi com nome menor o escrito fica no mesmo lugar, mas com laranjeiras e passo fundo fica mais pra cima, acho que teria bom o nome do campus ficar todo em uma só linha, inclusive os campi com nomes grandes

**Comment by luizatonial** [comment]
- Dropdown na tela inicial para escolher o campus em "acessar o tour"
- Remover icone do twitter
- Local para receber sugestões/feedback dos usuários
- Alterar o destaque dos blocos
