### ISSUE TITLE
Conteúdo postagens maio 2023

### ISSUE THREAD

**Issue by Saene99** [practice-uffs/programa#1468]
Nessa issue criaremos os conteúdos para as postagens do mês de Maio de 2023

- [x] Cartilha Moodle
- [ ] Dicas para escrever um bom texto
- [ ] Principais órgãos da UFFS e suas funções (cartilha)
- [x] Dicas de iluminação, ângulo e áudio
- [x] MORE - Mecanismo Online para Referências
- [ ] Dicas para saúde mental (cartilha)

**Comment by amandasegattob** [comment]
Criei as pastas dessa issue no Google Drive:

[Pasta da issue](https://drive.google.com/drive/folders/11zkqgyVFyks6r8zqfV-W7F1Xzn_UR7NY?usp=share_link)
🔽 [Entrada](https://drive.google.com/drive/folders/1Bk1l8FZ0wTKAgIO0LdKnn9FTozJSoSTR?usp=share_link)
🔼 [Saída](https://drive.google.com/drive/folders/1Ptr82SPFzpKM7tjR70RdsmkcSaMK4ZPK?usp=share_link)

**Comment by amandasegattob** [comment]
Escrevi o conteúdo de "Dicas de Iluminação, ângulo e áudio". Vejam o que acham @brendaellen @julia-zanini

**Comment by brendaellen** [comment]
@amandasegattob revisei o conteúdo e gostei bastante. Fiz algumas modificações na estrutura, deixei comentários e comecei a legenda. Quando os comentários forem resolvidos, finalizo a revisão.

**Comment by brendaellen** [comment]
@julia-zanini finalizei a revisão e criei a legenda do conteúdo sobre o Moodle. Incluí algumas informações para que o conteúdo ficasse mais completo, então dê uma olhada, e qualquer dúvida pode me perguntar.

**Comment by ghost** [comment]
escrevi o conteúdo do MORE, fiz ele pensando em ser card, certo? se puderem dar palpites no gabarito!

**Comment by amandasegattob** [comment]
Deixei minhas sugestões no documento.

**Comment by ghost** [comment]
escrevi o roteiro do card para bolsa de pesquisa e extensão. revisem?

**Comment by ghost** [comment]
fiz algumas propostas de mudanças no card de organização e planejamento. está no figma embaixo da arte criada inicialmente
