### ISSUE TITLE
Cards postagens maio 2023

### ISSUE THREAD

**Issue by Saene99** [practice-uffs/programa#1469]
Nessa issue criaremos os cards das postagens do mês de Maio de 2023.

**Comment by amandasegattob** [comment]
Criei as pastas dessa issue no Google Drive:

[Pasta da issue](https://drive.google.com/drive/folders/1j5-hMjO9MIXmUBNCj15uwaylFG7LUZ7F?usp=share_link)
🔽 [Entrada](https://drive.google.com/drive/folders/1gsckob7-UFqv5-vwBi9r5ccF7PkhhyJ3?usp=share_link)
🔼 [Saída](https://drive.google.com/drive/folders/1-byL5RzE33ggBAtmjpHA-KTHiu7JnxV-?usp=share_link)

**Comment by amandasegattob** [comment]
Oie! Fiz o card de dicas de iluminação, ângulo e áudio. Preciso de ajuda com a capa, tentei colocar elementos, mas não ficou bom. Está no [figma](https://www.figma.com/file/vKsmv9TiwF1RFERsOEs31T/Issues---Instagram?type=design&node-id=2947-759&t=iHjFjpKRjtdvVYU0-0).

**Comment by brendaellen** [comment]
@amandasegattob dei uma olhada nos cards, e tenho as seguintes considerações:
A parte do design, cores e elementos ficou muito boa, mas aquele tipo de fonte dos títulos me incomoda um pouco, talvez por ser muito estilizada e já termos utilizado demais. Acho que dessa vez poderíamos tentar algo diferente e mais simples;
Como mencionei no roteiro, o post não deixa claro qual a finalidade dessas dicas, então isso deve ser alterado, seja com a inclusão de uma introdução, ou complementando o título na capa;
Como o roteiro foi adaptado diretamente no figma, os cards terão que passar por uma nova revisão textual.
Assim que o material estiver finalizado, criarei a legenda e os stories.

**Comment by amandasegattob** [comment]
Coloquei os cards de dicas de iluminação, ângulo e áudio na pasta.

**Comment by ghost** [comment]
Achei os cards bem bonito! Mas alguns elementos fogem da nossa ID visual, eu achei... mas ficou bom

**Comment by amandasegattob** [comment]
Oie, fiz o card de dicas de planejamento e organização. Preciso de ideia para a capa. Está no figma.

**Comment by ghost** [comment]
card do MORE postado na pasta de entrada. podem revisar e propor alterações?

**Comment by ghost** [comment]
> Oie, fiz o card de dicas de planejamento e organização. Preciso de ideia para a capa. Está no figma.

fiz a revisão dos cards no figma, veja o que acha!

**Comment by ghost** [comment]
coloquei na pasta de entrada os cards para participar de bolsas. esqueci de postar antes. vejam e me digam o que acham

**Comment by brendaellen** [comment]
> Oie, fiz o card de dicas de planejamento e organização. Preciso de ideia para a capa. Está no figma.

@amandasegattob o que você acha de fazer similar a capa sobre dicas para melhorar a perfomance do computador? daí só troca os elementos.

**Comment by brendaellen** [comment]
> card do MORE postado na pasta de entrada. podem revisar e propor alterações?

Eu dei uma olhada e achei o design bem bonito, parabéns! Tenho algumas sugestões:

Na capa alterar para Mecanismo On-line para Referências;

Particularmente, acho um post com dois cards de conteúdo um tanto desinteressante, então sugiro fazer mais um card com o penúltimo bloco de texto (pode ser utilizado para ...);

Tirar "e-mail..." e colocar "entre outros";

Aumentar um pouquinho ou colocar em negrito a fonte do segundo bloco de texto (Desenvolvido pela Universidade...).

Seriam estas as sugestões, mas qualquer dúvida podem me perguntar;)

**Comment by ghost** [comment]
alterei a capa de dicas de organização como a brenda falou pelo telegram. está na pasta de entrada

**Comment by ghost** [comment]
fiz as alterações no conteúdo do MORE como a brenda indicou. me digam o que acham!

**Comment by amandasegattob** [comment]
Oie, eu fiz a revisão dos cards no figma. Copiei em baixo com as alterações que eu faria.
