### ISSUE TITLE
Postar vídeo do app do practice no Youtube e redes sociais

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#147]
O video abaixo deve ser postado em: 

* [x] Youtube
* [x] Instagram (colocar ele nos stories)
* [x] Twitter
- [x] Facebok

Link para o vídeo: https://drive.google.com/file/d/1VLY_Grgq49cU1kWTKHFZYg3UAwpO6YZU/view?usp=sharing

Texto que acompanhará o vídeo (exceto para stories do Insta):

O desenvolvimento do aplicativo do PRACTICE está a todo vapor. Nosso aplicativo permitirá que todos da comunidade acadêmica tenham acesso a tecnologias educacionais do programa na palma da mão. Confira nesse vídeo o atual de desenvolvimento do app, que ainda não está com todas funcionalidades nem seu visual final. Independente da caminhada de desenvolvimento de nosso aplicativo, uma coisa é certa: nosso usuário é a prioridade, e facilidade é a linguagem. O app foi criado para ajudar sua vida, não complicá-la.

O aplicativo do PRACTICE é desenvolvido com tecnologias open-source. Inclusive, o aplicativo também é open source. Acompanhe o desenvolvimento em https://github.com/practice-uffs/app-practice

**Comment by VIF-Franca** [comment]
Link do vídeo no Youtube: https://youtu.be/InaJakm04Dg

**Comment by Dovyski** [comment]
O conteúdo foi postado em todas as redes sociais? Youtube e Instagram eu vi, mas no Twitter e Facebook?

**Comment by VIF-Franca** [comment]
Também foi postado no Twitter e Facebook, nos "story" de cada plataforma.

**Comment by Dovyski** [comment]
Fantástico, obrigado!
