### ISSUE TITLE
Stories postagens maio 2023

### ISSUE THREAD

**Issue by Saene99** [practice-uffs/programa#1471]
Nessa issue criaremos os stories das postagens do mês de Maio de 2023.

**Comment by amandasegattob** [comment]
Criei as pastas dessa issue no Google Drive:

[Pasta da issue](https://drive.google.com/drive/folders/1sCm4BKKb7rxdj5ThSkbmf6XHa6kM-zS9?usp=share_link)
🔽 [Entrada](https://drive.google.com/drive/folders/1BGXsmTVdHhGaT-iOcyqYMF8UykYV38qx?usp=share_link)
🔼 [Saída](https://drive.google.com/drive/folders/1BekpX3aeKdcXUXXIxvBQbWpdJ5eSPWD8?usp=share_link)

**Comment by amandasegattob** [comment]
Oie, coloquei os templates dos debates dos candidatos à reitoria na pasta de entrada.

**Comment by brendaellen** [comment]
Criei o conteúdo para os stories sobre accs.

**Comment by brendaellen** [comment]
Elaborei os conteúdos para stories sobre:
Edição de podcast;
Políticas de licença;
Dicas para escrever um bom texto;
Dicas de iluminação, ângulo e áudio.

**Comment by brendaellen** [comment]
Elaborei os stories de engajamento sobre planejamento e organização.

**Comment by ghost** [comment]
os stories de museus virtuais passei para a issue de junho #1511
