### ISSUE TITLE
Agenda de lives

### ISSUE THREAD

**Issue by patitrev** [practice-uffs/programa#1477]

**Comment by patitrev** [comment]
https://drive.google.com/drive/folders/17xFcJGBQC8TvGMmEmusadQuo4IewF7I4?usp=share_link
a imagem está no link

**Comment by Saene99** [comment]
as imagens estão sendo criadas em alguma pasta que não tenho acesso

**Comment by MariaLuizaReviliau** [comment]
Acesso liberado

**Comment by Saene99** [comment]
Postado
