### ISSUE TITLE
Live PROPEPG - Pesquisa com Café - 18/09/2020 - 10h 

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/programa#148]
Solicitante: PROPEPG - Diretoria de Pesquisa
Contato: Suianny Francini Luiz Michelon
Email: dir.dpe@uffs.edu.br

Webex:     https://uffs.webex.com/meet/dir.dpe
transmissão: Facebook

Solicitei preenchimento do roteiro. Assim que o solicitante retornar eu coloco na pasta do drive.

**Comment by lcaimi** [comment]
As servidoras Elis Gorett Lemos da Fonseca e Claudia Cristina de Oliveira Soares participam do evento na condição de intérpretes em libras.

**Comment by lcaimi** [comment]
Roteiro disponível na [pasta do Drive](https://drive.google.com/drive/folders/12mLw-9AgN3AahklnTcrFVebyiwK7ZGqS?usp=sharing).

@MaNegrao assume a interlocução com o solicitante por favor.

**Comment by MaNegrao** [comment]
Live concluida, Flyer e Link na pasta saida do Drive
