### ISSUE TITLE
Edição de vídeo: Autismo

### ISSUE THREAD

**Issue by amandasegattob** [practice-uffs/programa#1483]
Essa issue tem como objetivo a edição do material gravado no Estúdio Chapecó. Consiste em cortar algumas partes do vídeo, conforme for necessário e sincronizar com a apresentação de slides.

**Comment by amandasegattob** [comment]
Criei as pastas dessa issue no Google Drive:

 [Pasta da issue](https://drive.google.com/drive/folders/1NR8S72zKkrdcEr8wMUTentamgWPzM5ax?usp=share_link)
🔽 [Entrada](https://drive.google.com/drive/folders/1jkN_GsUCJ27sxPisA04k1NVp6SPbPhep?usp=share_link)
🔼 [Saída](https://drive.google.com/drive/folders/1J8Gt8IhWWi2n6C-xspvafZnwogVwjcFP?usp=share_link)

**Comment by amandasegattob** [comment]
Coloquei os materiais na pasta de entrada. Assim que eu tiver a informação sobre o layout do vídeo, sinalizo aqui.

**Comment by MariaLuizaReviliau** [comment]
Completo!
