### ISSUE TITLE
Conjunto de lives dos debates de cada Campus

### ISSUE THREAD

**Issue by MariaLuizaReviliau** [practice-uffs/programa#1494]
- [x] Campus Erechim - 18/04, as 19h30min
Debate Reitoria
Link da transmissão: https://youtube.com/live/bLunlTYk-ww?feature=share
Responsável: @patitrev 

- [x] Campus Passo Fundo - 20/04, as 8h30min.
Debate Reitoria
Link transmissão: https://youtube.com/live/bz4DMxGCUjQ?feature=share
Responsável: @patitrev 

- [x] Campus Cerro Largo - 26/04, as 8h30min
Debate Reitoria
Link transmissão: https://youtube.com/live/idM5Fjr_NE4?feature=share
Responsável: @patitrev 

- [x] Campus Erechim - 26/04/2023, as 19h30 min
Debate Direção
Link transmissão: https://youtube.com/live/-Fwr16LuNQs?feature=share
Responsável: @luizatonial 

- [x] Campus Laranjeiras do Sul - 03/05, as 19h30min
Debate Reitoria
Link transmissão: https://youtube.com/live/Bs1c3B6IYvE?feature=share
Responsável: @patitrev 
Suplente: @MariaLuizaReviliau 

- [x] Campus Chapecó - 03/05/2023, as 8h30min
Debate Direção
Link transmissão: https://youtube.com/live/JlbKtWKyzTw?feature=share
Responsável: @julia-zanini 
Suplente: @patitrev 

- [x] Campus Erechim - 04/05/23, as 8h30min
Debate Direção 
Link da transmissão: https://youtube.com/live/rE1N3uVVg38?feature=share
Responsável: @julia-zanini 
Suplente: 

- [x] Campus Chapecó - 04/05/2023, as 19h
Debate Direção
Link transmissão: https://youtube.com/live/vVYJFTrkmmA?feature=share
Responsável: @MariaLuizaReviliau 
Suplente: @luizatonial 

- [x] Realeza - 05/05, as 8h30min
Debate Reitoria
Link transmissão: https://youtube.com/live/L4lpATXJixQ?feature=share
Reponsável: @julia-zanini 
Suplente: @patitrev 

- [x] Chapecó - 08/05, as 19h30min
Debate Reitoria
Link transmissão: https://youtube.com/live/kLafKaYMWwc?feature=share
Responsável: @luizatonial 
Suplente: @MariaLuizaReviliau

**Comment by MariaLuizaReviliau** [comment]
[PASTA DO DRIVE](https://drive.google.com/drive/u/1/folders/1fieEYwqN6ZAoHjj0M5BYfgsAWAIKmxAw)

[CAPAS DAS LIVES](https://github.com/practice-uffs/programa/issues/1493) #1493

**Comment by elisribas** [comment]
Orientações gerais repassadas à Comissão Eleitoral Geral.

- As transmissões serão realizadas pelo canal criado para os debates, chamado de Consulta Prévia UFFS: 
- https://www.youtube.com/channel/UCkiCh370skDX29O4lyWQllA 
- Desativar o chat do YouTube, portanto não haverá participação online.
- A transmissão online é de responsabilidade do Practice, para tanto o espaço físico precisa estar configurado de tal forma que permita a captura de áudio e vídeo dos participantes.
- Para os auditórios que possuem câmeras afixadas no teto, não precisaremos de nenhum recurso extra para as imagens, mas precisaremos de microfones sem fio, preferencialmente, três ou mais.
- Todas as solicitações de transmissão precisam ser registradas no Mural do Practice: https://practice.uffs.edu.br/mural/
- Os solicitantes que gerarem as demandas no Mural do Practice - solicitação de serviços - informarão se haverá ou não interpretação em Libras na transmissão. Para os casos em que houver previsão deste serviço, o solicitante precisará realizar o agendamento junto ao setor responsável no campus em que for realizado o debate.
- Após a confirmação do atendimento da demanda, o solicitante terá acesso ao formulário para preenchimento das informações sobre o evento.
- Os candidatos precisam chegar com antecedência (pré-definida pela comissão) no local, para que seja possível realizar os testes de áudio e vídeo.
- Acertamos que o tempo de fala, organização da fala e demais questões ligadas à organização do debate são de responsabilidade da comissão local.

Contato de WhatsApp do Practice divulgado: 42 3635-0038
