### ISSUE TITLE
[Mídias sociais] Canal no Youtube

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/programa#15]
É necessário criar e configurar um canal no YouTube para o PRACTICE, o qual será utilizado para veicular algumas de nossas postagens. Mais informações serão devidamente adicionadas posteriormente (como nome padronizado, imagens, descrição, etc).

**Comment by oigor** [comment]
Canal criado ✔️

Dados de acesso através do Google Drive do projeto.



Segue o esquema para acesso:

Gerência > Documentos > Acesso a redes sociais.

**Comment by oigor** [comment]
Link para o Canal: https://www.youtube.com/channel/UCu3jAl8MTMPkaxb3u0_xESw


[Vídeo promocional](https://youtu.be/MBX_Ij4qSPc):
