### ISSUE TITLE
Instalações campus Laranjeiras do Sul

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#150]
Deverá ser atendido as demandas solicitadas para o campus de Laranjeiras do Sul, caberá aos dois bolsistas @lucasgalize e @VIF-Franca, segue abaixo listagem:

- [x] Organizar o ambiente que os três bolsistas poderão utilizar para as gravações, realizações de lives e afins --> @VIF-Franca e @lucasgalize;

- [x] Instalação dos computadores --> @lucasgalize e @VIF-Franca ; 

- [x] Instalação dos equipamentos Som e Imagem para as gravações --> @VIF-Franca e @lucasgalize; 

- [x] Testar os equipamentos de Som e Imagem para as gravações --> @lucasgalize;

- [x] Teste da conexão de internet incluindo a transmissão de uma lives teste;

- [x] Configuração dos computadores com o OBS Studio --> @VIF-Franca e @lucasgalize ; 

- [ ] Elaboração de arte sobre a divulgação do evento "live de inauguração" --> @lucasgalize ; 

- [ ] Criar evento no Youtube sobre a "live de inauguração" --> @VIF-Franca .

**Comment by VIF-Franca** [comment]
Crie uma pasta no drive e adicionei as fotos que tiramos hoje pela manhã, [drive](https://drive.google.com/drive/folders/1TApZM4JB9f7sJq-44-uQkpBw8NsUJdBP?usp=sharing).

**Comment by lucasgalize** [comment]
Sobre a "Elaboração de arte sobre a divulgação do evento live de inauguração", preciso saber da data e horário da divulgação @VIF-Franca para eu poder realizar o material.

**Comment by lucasgalize** [comment]
Sobre esta tarefa "Testar os equipamentos de Som e Imagem para as gravações", os testes de som foram realizados e estão ok. Porém o teste de imagem, solicitamos um cabo que estava faltando para poder realizar completamente o teste de imagem (câmeras). O servidor responsável ficou de adquirir o cabo.

**Comment by VIF-Franca** [comment]
Feedback sobre a internet do campus: funcionou super bem nas duas lives que realizei.
Já sobre as instalações creio que está pronta para o momento, futuramente precisaremos fazer alguns ajustes com a chegada de alguns materiais.
