### ISSUE TITLE
Conteúdo de postagens de Junho 2023

### ISSUE THREAD

**Issue by ghost** [practice-uffs/programa#1510]
Issue destinada para o registro do conteúdo dos posts de Junho (cards e reels)

[Pasta da issue](https://drive.google.com/drive/folders/1NryYWpF69P-7ytszwcrvTX3yf-vzc0s4?usp=drive_link)
🔽 [Entrada](https://drive.google.com/drive/folders/1TyE6nTrZkeyfIb65bRoE41rJVITX8LLT?usp=drive_link)
🔼 [Saída](https://drive.google.com/drive/folders/1-7E-428buLIyWzQ39i-ZjxeWvVCKwkGo?usp=drive_link)

**Comment by brendaellen** [comment]
Revisei o conteúdo sobre banner e criei a legenda.

**Comment by brendaellen** [comment]
O conteúdo sobre museus virtuais e sua respectiva legenda estão no gabarito.

**Comment by brendaellen** [comment]
O roteiro com dicas para escrever um bom texto e sua respectiva legenda estão no gabarito.

**Comment by amandasegattob** [comment]
Criei os cards dos museus virtuais, está no [figma](https://www.figma.com/file/vKsmv9TiwF1RFERsOEs31T/Issues---Instagram?type=design&node-id=3189-817&t=3zT4rse2YaDy6Pou-0).

**Comment by amandasegattob** [comment]
Criei o conteúdo dos principais órgãos da UFFS, está na pasta de entrada.

**Comment by brendaellen** [comment]
> Criei o conteúdo dos principais órgãos da UFFS, está na pasta de entrada.

@amandasegattob , texto revisado e legenda feita. Deixei um comentário com uma observação, e notei que falta finalizar o post (caso tenha pensado em finalizar no figma, desconsidere).

**Comment by ghost** [comment]
também li o material, mas achei muito comprido. o que acham de tentarmos diminuir o mesmo?

**Comment by amandasegattob** [comment]
Então, eu também achei, porém não sei o que é melhor "desconsiderar". Vou começar os cards, aí dá pra ir vendo como fica, e ir tirando coisas lá no figma.
E eu não finalizei ele porque o máximo de cards no Instagram é 10. Talvez poderíamos tirar algum órgão.

**Comment by ghost** [comment]
quanto à colaboração com o @escolhiseruffs através do conteúdo de principais órgãos da uffs, falaram que não publicam coisas assim sem antes pedir para cada setor ler e avaliar o que foi escrito e corrigir, porque pode dar problema, setores se sentirem danados etc. mas falaram que se nós publicarmos, podemos marcar eles que repostam nos stories

**Comment by ghost** [comment]
além disso, proposta de passar o conteúdo de "dicas de escrever um bom texto" para cards em vez de reels

**Comment by ghost** [comment]
os conteúdos que não foram postados ainda, passei para a issue #1521
