### ISSUE TITLE
Stories de Junho de 2023

### ISSUE THREAD

**Issue by ghost** [practice-uffs/programa#1511]
[Pasta da issue](https://drive.google.com/drive/folders/19A8fH4yJjgzmbiQGPYxwOE8yl0V85ABg?usp=drive_link)
🔽 [Entrada](https://drive.google.com/drive/folders/1C2wLWCUMkagk-9qOgNHCC1BxhwnufEoE?usp=drive_link)
🔼 [Saída](https://drive.google.com/drive/folders/1RTtOSnLk7ES_pyv1pgPjS8aC53GL947l?usp=drive_link)

**Comment by brendaellen** [comment]
O conteúdo para os stories sobre museus virtuais está no gabarito.

**Comment by brendaellen** [comment]
O conteúdo para os stories sobre museus virtuais e dicas para um bom texto, está no gabarito.

**Comment by brendaellen** [comment]
O conteúdo para os stories de engajamento sobre museus virtuais e dicas para um bom texto, também já está no gabarito.

**Comment by brendaellen** [comment]
@amandasegattob onde se encontra o conteúdo sobre Shotcut, para que eu possa criar os stories de engajamento?

**Comment by amandasegattob** [comment]
> @amandasegattob onde se encontra o conteúdo sobre Shotcut, para que eu possa criar os stories de engajamento?
> 
> 
> 
> 
> 
> 

oie, é sobre o CapCut, estão na issue #1464

**Comment by brendaellen** [comment]
O stories de engajamento e de divulgação sobre os principais órgãos da UFFS, já estão em seus respectivos gabaritos.
