### ISSUE TITLE
banner: divulgação projeto química para o enem

### ISSUE THREAD

**Issue by MariaLuizaReviliau** [practice-uffs/programa#1514]
Descrição da solicitante: 
Olá. A ideia é fazer algo que possa ser utilizado em qualquer atividade do projeto. Portanto, sugiro que seja utilizado o logotipo do projeto, titulo e numa parte mais inferior, o logo da universidade ( campus CL), bem como logo da PROEC ( se existir)...

Titulo do projeto " QUÍMICA PARA O ENEM: ATIVIDADES VOLTADAS PARA O ENSINO E APRENDIZAGEM DE QUÍMICA COM ENFOQUE AO EXAME NACIONAL DO ENSINO MÉDIO"

pode ser adicionado o QR code do perfil do intagram do projeto... e o que mais vocês acharem interessante, podem ficar à vontade para criação

**Comment by ghost** [comment]
[Pasta da issue](https://drive.google.com/drive/folders/1EPpLaab6yPEZqrYJ_SLA3R928eAsEy7G?usp=drive_link)
🔽 [Entrada](https://drive.google.com/drive/folders/1drhFDG-B1UMEpHVMpOfi8LJWDRkGn_1t?usp=drive_link)
🔼 [Saída](https://drive.google.com/drive/folders/1m9CHhm2IlRRoHnodSnn9Wzm4s5jfZ6Yu?usp=drive_link)

**Comment by ghost** [comment]
coloquei na pasta de entrada as primeiras 3 propostas para serem enviadas para o solicitante como primeiro envio
