### ISSUE TITLE
Live “Oficinas temáticas no Ensino de Ciências.” 29/06/23 - 14h

### ISSUE THREAD

**Issue by MariaLuizaReviliau** [practice-uffs/programa#1517]
<h1 align="center" >Informações da Transmissão Ao Vivo</h1>

**Titulo**: “Oficinas temáticas no Ensino de Ciências.”  

**Data e Hora**: 29/06/23 - 14h

**Evento Geral** (se houver): II Roda de Conversa - PIBID.PRP.UFFS

**Solicitante**: Eduardo Luiz Tomasini 

**Realizador(es)**: PROGRAD/DPGRAD

**Palestrante Principal**: 

**Solicitação no Mural**: https://practice.uffs.edu.br/mural/servico/202 

**Link Transmissão**: https://youtube.com/live/nAc_-Ch0Hf4?feature=share

**Sala webex**: https://uffs.webex.com/uffs/j.php?MTID=m99cb986d5d277091eee6a4ac15c4db12 

Com os dados e roteiro em mãos, o responsável pela Live deve seguir os padrões do PRACTICE e estabelecer contato com o solicitante, enviando inicialmente o Protocolo de Execução de Lives.

**[Planilha de Lives](https://drive.google.com/drive/folders/16h-YVwTnRF49eqBYBRONKyLqPbisCIbH)**

**[Protocolo de Execução de Lives](https://drive.google.com/file/d/1KQ9vI1gKECqWHi4xwb3LrnuWCgKEHWyd/view?usp=sharing)**

**[TeleCurso 2000](https://drive.google.com/drive/folders/1r_Gea2VxB3J-4VfIXr9jqXa2NgStNvCs?usp=sharing)**

CC: @con-midia / lives

**Comment by MariaLuizaReviliau** [comment]
Pasta do drive: https://drive.google.com/drive/u/2/folders/1irSZIxOPS6gHVhnnbReng8nQwPrqRSvb

**Comment by ghost** [comment]
https://forms.gle/tHWSC7LpRcGybtBy7
