### ISSUE TITLE
Identidade visual Vozes da Fronteira - Coral da UFFS Cerro Largo

### ISSUE THREAD

**Issue by MariaLuizaReviliau** [practice-uffs/programa#1518]
O projeto "Vozes da Fronteira - Coral da UFFS Cerro Largo" tem como objetivo geral estabelecer um programa de educação musical com vistas à criação
de um coral que, em suas apresentações, coloque em evidência canções em português e espanhol, promovendo o resgate de
valores culturais próprios da região das Missões, com a integração de duas das principais línguas presentes nesta fronteira,
viabilizando a construção da cidadania, o desenvolvimento de habilidades socioeducativas e a descoberta de talentos ao integrar a
música ao processo interdisciplinar.
A região das Missões, localizada na fronteira entre Brasil, Argentina e Paraguai, é conhecida por sua rica história e cultura, com
influências indígenas, jesuíticas e coloniais. O projeto surge como uma iniciativa para resgatar e valorizar a cultura local, utilizando a
música, tanto em língua portuguesa como em língua espanhola como ferramenta pedagógica e artística.
Trata-se de um coral com vistas a integrar uffs e comunidade.

**Comment by MariaLuizaReviliau** [comment]
Drive: https://drive.google.com/drive/u/1/folders/18eJpsBAe9ptThEKMRShx-sqIOLfIldDt

**Comment by ghost** [comment]
por falta de resposta da solicitante a issue foi finalizada
