### ISSUE TITLE
Readequação do Roteiro de Lives para Ficar Claro e Objetivo

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#152]
O Objetivo dessa tarefa é reescrever partes do modelo de roteiro de lives para que os clientes não se confundam e as não fique faltando informações

[Pasta Drive](https://drive.google.com/drive/folders/1hhrrYk0EHRRjMKxAPc0IlL25cnch5ep4)

**Comment by lcaimi** [comment]
Fiz algumas alterações pontuais.

Acho que pode ser colocada em Materiais se estiver de acordo @MaNegrao.

**Comment by MaNegrao** [comment]
Por mim está tudo ok, Em qual pasta dos Materiais eu coloco? na Documentos? @lcaimi

**Comment by lcaimi** [comment]
Criei uma nova pasta dentro de [Materiais -> Roteiro para Lives Template](https://drive.google.com/drive/folders/1uSbwV0EYRQywqVKjY95EsDSd-kT9UmqS?usp=sharing). Já coloquei o arquivo lá.
