### ISSUE TITLE
Postagens Agosto 2023

### ISSUE THREAD

**Issue by ghost** [practice-uffs/programa#1521]
[Pasta](https://drive.google.com/drive/folders/1nL1KnQ3bKIc3TjGpoEnY3zZ9SYwUD7sP?usp=drive_link)
[Entrada](https://drive.google.com/drive/folders/1pBwJGuqfuwFIMR7MPopXDbTDcs20hr4Z?usp=drive_link)
[Saída](https://drive.google.com/drive/folders/1pNv6hbeHWGqhrSbfabMkZCPLjmnB5Xiv?usp=drive_link)

Issue para as postagens de Agosto de 2023. Aqui contém:

Gabaritos de cards, reels e stories
Os cards feitos (ou em construção)
Os reels feitos (ou em construção)

**Comment by elisribas** [comment]
Olá, @MariaLuizaReviliau @julia-zanini @amandasegattob .
Ainda para julho/2023, solicito a criação de postagens para divulgação dos seguintes editais:
- https://www.uffs.edu.br/atos-normativos/edital/gr/2023-0555  SELEÇÃO DE ESTAGIÁRIOS PARA ESTÁGIO NÃO OBRIGATÓRIO 
- https://www.uffs.edu.br/UFFS/atos-normativos/edital/gr/2023-0554 SELEÇÃO DE BOLSISTAS 
Colocar todos os dias nos stories, até o último dia de inscrição.

**Comment by MariaLuizaReviliau** [comment]
Arte para divulgação dos editais está na pasta de entrada, na pasta "divulgação editais"

**Comment by elisribas** [comment]
Atualizei as artes para stories, coloquei na pasta @julia-zanini @amandasegattob 
Por favor, divulguem todos os dias nos stories.

**Comment by ghost** [comment]
Reels "como fazer banner no canva" na pasta de entrada

**Comment by ghost** [comment]
coloquei cards de Dicas para escrever um bom texto na pasta de entrada. não sei se não ficou muito simples. o que acham?

**Comment by amandasegattob** [comment]
Eu achei a capa um pouco simples, talvez dê pra trabalhar mais o título, não sei. O resto achei lindo!!

**Comment by ghost** [comment]
cards alterados na pasta de entrada
