### ISSUE TITLE
Live PIBID Residência Pedagógica - 06/10/2020 - 15h

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/programa#154]
Evento: Lançamento do PIBID Residência Pedagógica na UFFS (Editais 2020)
Data: 06/10/2020
Horário: 15h às 16h30min
Programação:
Abertura (PROGRAD, Coordenações Institucionais, Representantes da Educação Básica)
Palestra “Escola contemporânea e docência em tempos de BNCC” (Clarice Salete Traversini – UFRGS)
Transmissão: Pode ser no canal do Practice (se possível, indicar o link no convite)

**Comment by MaNegrao** [comment]
@lcaimi Fiz uma primeira versão do convite, tentei agregar todas as informações necessarias. Aguardo feedback e alterações desejadas

@Dovyski podemos utilizar o link uffs.cc/practice-live para essa live?

![Convite-V1](https://user-images.githubusercontent.com/31110971/94193841-3b784800-fe87-11ea-8a74-646fcc08b6a8.jpg)

**Comment by Dovyski** [comment]
Amei o banner! Sobre o `/practice-live`, claro que podemos usar. Quando tiver o link do youtube da live, me bipa que eu atualizo o link.

**Comment by lcaimi** [comment]
@MaNegrao Cria o evento no canal do Youtube do Practice com o convite (V2) de capa.

Em seguida passa o link para o Fernando fazer o redirecionamento do /practice-live.

**Comment by MaNegrao** [comment]
@Dovyski segue link https://youtu.be/GjQsJNcLEiE. Valeu :D

**Comment by Dovyski** [comment]
Online e tinindo para uso 😄: [uffs.cc/practice-live](https://uffs.cc/practice-live)

**Comment by lcaimi** [comment]
Avisei o solicitante que o link está operacional.

**Comment by lcaimi** [comment]
Roteiro da Live incluído na [pasta da Issue](https://drive.google.com/drive/folders/1vP9Ni9M6DiHHMXZTeAKbFfuD1OuMipa9).

Informação do solicitante:
Agendei a atividade no Webex, a sala será organizada a partir do link https://uffs.webex.com/uffs/j.php?MTID=mb24442a4fceece1bac21120775ec887d.
Se precisar, atribuo a função de organizadores a vocês no início da atividade.

**Comment by lcaimi** [comment]
Reunião para teste e ajustes da Live:

Data: 05/10
Horário: 10:15 - 10:45
Link: [https://uffs.webex.com/uffs/j.php?MTID=m1ef7c250fea10b6eb2d94c67933488d4](https://uffs.webex.com/uffs/j.php?MTID=m1ef7c250fea10b6eb2d94c67933488d4)
Número da reunião (código de acesso): 173 126 0950
Senha da reunião: BuPeZmJm323

**Comment by MaNegrao** [comment]
Reunião de teste concluida

**Comment by VIF-Franca** [comment]
Conforme enviado via e-mail por Joel Bavaresco, segue:


Número da reunião (código de acesso): 173 502 1221

Senha da reunião: WUqfPAT3N33

Link da reunião : https://uffs.webex.com/uffs/j.php?MTID=m9ded04504bdc05db1062e4ad44525571

**Comment by VIF-Franca** [comment]
Recebemos o e-mail com o roteiro atualizado, já adicionei no drive.  
SEGUE A SEGUIR O E-MAIL:

> "A conferência foi agendada em https://uffs.webex.com/uffs/j.php?MTID=mb24442a4fceece1bac21120775ec887d e deve ser acessada a partir das 14h30min, para ajustar questões técnicas (imagem, vídeos, ordem e tempos das falas, etc).
> 
> Será concedida a fala aos convidados sendo que, a princípio, a ordem será essa:
> Rosenei fará a abertura e protocolo inicial (por volta de dez minutos);
> Representantes das Secretarias de Educação (um por campus) terão de três a cinco minutos de fala;
> Inaê (representante da CAPES) fará uma fala de cinco minutos;
> Prof Jeferson fará uma fala por volta de cinco minutos;
> Profa Clarice palestrará por volta de 30 minutos;
> Serão lidos questionamentos e o evento será encerrado.
> 
> Mais detalhes no anexo. Em "Participantes da transmissão", constam os nomes e cargos, para utilização como legenda do vídeo.
> 
> As intérpretes foram avisadas para ingressar com antecedência e ajustamos os slides, de modo às telas de interpretação e da palestrante não sobreporem-se ao texto. Caso achem que algum dos slides precise ser ajustado, favor informar.
> 
> Abrirei a sala por volta das 14:30h para os ajustes necessários, OK?
> 
> 
> Atenciosamente,
> 
> Joel Bavaresco
> PROGRAD/UFFS - Equipe PIBID
> Fone: (49) 2049 3713"

**Comment by MaNegrao** [comment]
Live concluída com sucesso

Link: https://www.youtube.com/watch?v=GjQsJNcLEiE
