### ISSUE TITLE
Convite  para Live do PIBID  - prazo entrega quinta-feira 24/09

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/programa#155]
Seguem dados:
Evento: Lançamento do PIBID Residência Pedagógica na UFFS (Editais 2020)
Data: 06/10/2020
Horário: 15h às 16h30min
Programação:
Abertura (PROGRAD, Coordenações Institucionais, Representantes da Educação Básica)
Palestra “Escola contemporânea e docência em tempos de BNCC” (Clarice Salete Traversini – UFRGS)
Transmissão: Pode ser no canal do Practice (se possível, indicar o link no convite)

Quanto ao formato do convite, pode ser conforme o modelo (se possível, usar cores mais vivas e alguma gravura que remeta a formação de professores).

O convite se refere a Live da Issue #154. Pegar o link da transmissão para colocar no convite com o @MaNegrao ou @VIF-Franca 

Modelo ao qual o solicitante se refere
![image](https://user-images.githubusercontent.com/12415747/93934898-2d48f100-fcfa-11ea-8118-9979f22f23e4.png)

**Comment by MaNegrao** [comment]
Eu não entendi muito bem @lcaimi, devemos fazer um convite parecido com esse do NAP ou um flyer igual aqueles que fizemos pra outras lives?

**Comment by lcaimi** [comment]
Convite para divulgação antes do evento.

**Comment by lcaimi** [comment]
Cliente encaminhou as logos para constar no convite.

As logos estão na [pasta no Drive da Issue](https://drive.google.com/drive/folders/16hT_E0uUkgHT3OnUBrQ7VPT9sYBU-5fR?usp=sharing)

**Comment by lcaimi** [comment]
Ajustar: está faltando acento na palavra "residência".

**Comment by lcaimi** [comment]
Comentários do solicitante:

Gostamos do layout do convite. No entanto, vamos solicitar alguns ajustes para melhor apresentação:

- [ ] Quanto às logomarcas, inverter a posição das logos (PIBID à esquerda; CAPES, manter no meio; RP à direita).

Quanto ao texto:
Achamos que o título ficou muito extenso, melhor adequar para: 

- [ ] Conferência de abertura - PIBID e RP UFFS - 2020;

- [ ] Profa. Dra. Clarice Salete Traversini, 

- [ ]  trazer para antes do título da palestra (alternar local do nome da palestrante com título da palestra).

**Comment by MaNegrao** [comment]
Segue versão alterada:


![Convite-V2](https://user-images.githubusercontent.com/31110971/94303424-29101400-ff44-11ea-95c7-0b039a6be795.png)

**Comment by lcaimi** [comment]
Retorno do solicitante:

Só mais um pequeno ajuste:

- [ ]  trazer o título principal mais abaixo (começar na altura da segunda linha)

- [ ] deixar o nome da palestrante mais próximo do título da palestra

**Comment by MaNegrao** [comment]
Finalizado:

![Convite-V3](https://user-images.githubusercontent.com/31110971/94311964-7abf9b00-ff52-11ea-8a1d-e37e230586b1.png)
