### ISSUE TITLE
Adicionar novos bolsistas ao grupo PRACTICE @todos no Telegram

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#156]
Os números de celular de cada um dos novos bolsistas está na [planilha de membros](https://docs.google.com/spreadsheets/d/15kGGrER8UTGQhPIvGm2jHhs3pEO6f7gqISZgRyqpMKE/edit#gid=0). Se algum bolsista não conseguir ser adicionado (porque não possui Telegram), fazer o contato via e-mail para solicitar que uma conta no Telegram seja criada.

***PRAZO***:  24/09 ou, no mais tardar, 25/09 se houver necessidade de contatar bolsistas por e-mail.

**Comment by Dovyski** [comment]
Alguma atualizaçào dessa tarefa, @VIF-Franca ?

**Comment by VIF-Franca** [comment]
Opa, acabei de ver a issue, já estou adicionando.

**Comment by VIF-Franca** [comment]
@Dovyski pode me tornar admin do grupo por gentileza...

**Comment by VIF-Franca** [comment]
Uma questão: já adicionamos o do campus de Laranjeiras nesse reunião ? Caso sim, poderia adicionar o contato dele.

**Comment by VIF-Franca** [comment]
@Dovyski apenas a Morgana Maciél Oliveira não tem telegram, assim que ela criar já adiciono.

**Comment by Dovyski** [comment]
> Uma questão: já adicionamos o do campus de Laranjeiras nesse reunião ? Caso sim, poderia adicionar o contato dele.

Sim, vamos adicionar o Rafael assim que ele responder o e-mail de boas-vindas com os dados que precisamos.

**Comment by VIF-Franca** [comment]
Ok, os demais já estão todos no grupo.
