### ISSUE TITLE
Agendar com bolsistas novos reunião de boas-vindas

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#157]
Todos os bolsistas novos precisam ser apresentados à nossa forma de trabalho e ao programa. Como teremos 15 pessoas, talvez não seja possível fazer isso em uma única reunião. O objetivo dessa issue é coordenar o agendamento dessas reuniões.

Eu sugiro a criação de um doodle com horários nos três turnos (manhã, tarde e noite). Em seguinda, agendamos uma ou duas reuniões que acomodem o horário de todos para participar.

O tempo previsto de reunião é de 1h30min.

**Comment by VIF-Franca** [comment]
Belezinha, criei o doodle para a semana que vem entre os dias 28/09 até 02/10 com os 03 turnos. 

LINK: https://doodle.com/poll/mff8sxfmnm3bxx5r 

@Dovyski posso mandar para os novos membros ?

**Comment by Dovyski** [comment]
Sim, pode tratar do assunto no grupo `@todos` no Telegram.

**Comment by VIF-Franca** [comment]
até as 00:24 apenas o Robison José não havia respondido, rsrsrsrs, os demais responderam, sendo assim os três melhores horários são: 

Quarta-feira --> 10:00 às 11:30 com 09 votos;
Quarta-feira --> 13:00 às 14:30 com 07 votos;
Sexta-feira --> 08:00 às 09:30 com 06 votos;

**Comment by VIF-Franca** [comment]
Após as alterações realizadas pelos novos bolsistas esse foram os dias e horários mais escolhidos: 

30/09 das 10h às 11h30 --> 10 votos;
30/09 das 13h às 14h30 --> 08 votos;
Sobre 30/09 pensou-se em prorrogação pra 07/10. 

01/10 das 10h às 11h30 --> 07 votos;
01/10 das 13h às 14h30 --> 07 vagas;

02/10 das 13h às 14h30 -- 07 votos.


Essas foram as possíveis escolhas,

**Comment by VIF-Franca** [comment]
@Dovyski ja recebemos os dados do novo membro se Laranjeiras ?

**Comment by Dovyski** [comment]
Obrigado pela compilação dos horários. Ainda não recebemos o retorno do novo bolsista de Laranjeiras.

**Comment by Dovyski** [comment]
Reuniões agendadas:

* Sexta-feira - 02/10 - 8:00 às 9:30
* Quarta-feira - 07/10 - 10:00 às 11:30

O link de acesso para as reuniões está no grupo `PRACTICE @todos` no Telegram.
