### ISSUE TITLE
Áudio: pós-graduação na UFFS

### ISSUE THREAD

**Issue by ghost** [practice-uffs/programa#1573]
Solicitação feita em 24/11

Aceita em 27/11

Texto de narração:

DÊ UM PASSO A + NA SUA QUALIFICAÇÃO
Pós-graduação UFFS
Especialização em Planejamento e Gestão de Recursos Hídricos na UFFS — Campus Erechim.
Se você é um profissional inserido nos diversos âmbitos da gestão de recursos hídricos ou que deseja se capacitar profissionalmente para atuar na área, faça a sua inscrição on-line até o dia 4 de fevereiro de 2024!
Curso gratuito, sem mensalidades!
Acesse [www.uffs.edu.br/posgraduacao](http://www.uffs.edu.br/posgraduacao)

**Comment by ghost** [comment]
Pasta no [drive](https://drive.google.com/drive/folders/1WWY6yjQNQ3xdd5BabDLZYS_xkB2boM2O)

**Comment by ghost** [comment]
@amandasegattob está responsável por essa demanda

**Comment by amandasegattob** [comment]
Coloquei o áudio na pasta. Fiz duas versões: uma com música de fundo e outra sem. @julia-zanini se tu puder mandar pro solicitante eu agradeço!
