### ISSUE TITLE
Definir área de atuação para os novos bolsistas

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#158]
Após a apresentação do programa aos novos bolsistas, todos precisarão decidir em quais equipes trabalharão. A distribuição não será meramente por interesse, mas por talentos e número de membros que a equipe realmente precisa.

@practice-uffs/lideres por favor, informem quantos integrantes novos cada equipe gostaria de receber. Lembrem que os novos membros poderão desempenhar funções que estão parcialmente (ou complemente) descobertas, como criação de animação.

**Comment by alessandrapedrotti** [comment]
Acredito que 2 pessoas novas serão suficientes na equipe de conteúdo, considerando que essas duas pessoas trabalharão com revisão textual, redação e desenvolvimento de animações.

**Comment by andrewmsilva** [comment]
Acredito que a definição de número de novos integrantes seja dispensável para a equipe dev, pois há apenas um bolsista novo para a área. Portanto, é evidente que apenas ele entrará 😂

**Comment by Dovyski** [comment]
@alessandrapedrotti acho que podemos ter mais que 2 pessoas novas, se pensarmos que as animações fazem parte da con-conteúdo. Se esse não for o entendimento e animações serão feitas pela con-midia, não vejo problema de termos 2 novos em conteúdo.

**Comment by MaNegrao** [comment]
Considerando animações como parte da con-conteudo, o con-midia precisaria de 2 à 3 membros novos. No momento precisamos de um bolsista de Chapecó que possa ir aos estudios auxiliar nas gravações de videos. Os outros serão direcionados para atender todas as demandas de produção e edição de videos mais rapidamente.

**Comment by alessandrapedrotti** [comment]
> @alessandrapedrotti acho que podemos ter mais que 2 pessoas novas, se pensarmos que as animações fazem parte da con-conteúdo. Se esse não for o entendimento e animações serão feitas pela con-midia, não vejo problema de termos 2 novos em conteúdo.

Podemos discutir essa questão das animações na próxima reunião, para entendermos melhor a extensão desse trabalho na con-conteúdo e na con-midia.

**Comment by Dovyski** [comment]
Até podemos pensar que a con-design será responsável pelas animações, e a con-conteúdo fica encarregada de solicitar esses pedidos ou até coordenação a sua criação (roteiro, materiais, etc).

**Comment by estelavilasboas** [comment]
> Podemos discutir essa questão das animações na próxima reunião, para entendermos melhor a extensão desse trabalho na con-conteúdo e na con-midia.

Concordo que essas questões deveriam ser discutidas na próxima reunião. Também preciso entender quais demandas serão da con-design para determinar o número de bolsistas necessários. No momento, creio que 2 membros novos seria suficiente.

**Comment by alessandrapedrotti** [comment]
Definimos que a estação de animação fará parte dos serviços da @practice-uffs/con-midia.

**Comment by alessandrapedrotti** [comment]
Após as deliberações de duas reuniões de líderes, mudanças de funções de alguns membros e realocação de estações de uma equipe para outra, considero que a @practice-uffs/con-conteudo precisará de 3 novos integrantes, considerando apenas as estações de redação, diagramação e revisão.

**Comment by MaNegrao** [comment]
Considerando todos os serviços cobertos pelo con-midia, precisaremos de 4 à 7 bolsistas, seguindo a necessidade por demandas.

**Comment by MaNegrao** [comment]
@Dovyski alguns bolsistas novos do midia já estão trabalhando, mas eles não tem as permissões do repositório programa, se puder colocá-los no team :D

**Comment by MaNegrao** [comment]
Como todos os bolsistas já foram alocados, podemos fechar essa issue :D
