### ISSUE TITLE
Adicionar novos bolsistas ao fluxo de trabalho

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#159]
Realizar as seguintes ações:

* [x] Incluir no grupo de Telegram `PRACTICE @todos` (#156);
* [x] Dar permissão de acesso ao drive do programa;
* [x] Incluir cada bolsista na sua equipe no github (#158);
* [x] Incluir cada bolsista no grupo de Telegram de sua equipe;

**Comment by VIF-Franca** [comment]
Creio que já concluímos a issue.
