### ISSUE TITLE
[Mídias sociais] Perfil no Instagram

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/programa#16]
É necessário criar e configurar um perfil no Instagram para o PRACTICE, o qual será utilizado para veicular algumas de nossas postagens. Mais informações serão devidamente adicionadas posteriormente (como nome padronizado, imagens, descrição, etc).

**Comment by VIF-Franca** [comment]
Texto postado na bio. 

Usuário: practiceuffs
