### ISSUE TITLE
Live PROAE - 04/11 - 16h - 18h

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/programa#160]
Solicitalão:
No dia 04/novembro, das 16:00 às 18:00, teremos um evento de psicologia, sobre ansiedade no meio acadêmico. 
Solicitamos a interpretação de libras e pra isso precisamos de apoio técnico, para poder dividir a tela em que apareça palestrante e intérprete de Libras. A sala webex que usamos é a minha, https://uffs.webex.com/meet/vanessalago 

Já solicitei o preenchimento do Roteiro para Lives do programa. Assim que o solicitante enviar eu coloco no Drive.

[Pasta Drive](https://drive.google.com/drive/folders/1z-VM1C_zvvKb1_lvJjWM22TI33Q9ObZ7)

**Comment by MaNegrao** [comment]
Como falta mais de um mês para live, será que não conseguimos conversar com os organizadores para que o evento seja direcionado a uma plataforma de transmissão (Facebook ou YouTube) e deixar no Webex somente os palestrantes? Eu fiz uma live recentemente onde a divulgação foi para o Webex e acabou que tinha 360 pessoas lá e no Facebook só 30 e o Webex estava travando e difícil de controlar devido a quantidade de pessoas.

**Comment by lcaimi** [comment]
Com certeza. Já estamos ajustando com o solicitante para usar plataforma de transmissão para o público.

**Comment by VIF-Franca** [comment]
Recebemos o roteiro da live via e-mail, já adicionei no drive.

**Comment by MaNegrao** [comment]
> Recebemos o roteiro da live via e-mail, já adicionei no drive.

Obrigado, assumo a demanda a partir daqui

**Comment by MaNegrao** [comment]
Live finalizada!
