### ISSUE TITLE
Brainstorm para produção de novos materiais pelo Con-Midia

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#161]
A ideia dessa issue é reunir ideias para produção de materiais em video ou audio que serão utéis para o programa e para a comunidade também. Conversamos na reunião de equipe que esses materiais também serão utéis para melhor integração do novos bolsistas. Seguindo também a ideia do @Dovyski de transpor os materiais escritos para video.

As minhas sugestões são:

- Uma serie de videos (semelhante aos do shortcut) para instruções e tutoriais das ferramentas contidas no OBS
- Realizarmos a issue #105 em video e no estudio (Se tivermos o chromakey melhor ainda)

Creio que essa tarefa fica a criterio dos @practice-uffs/lideres, por favor, coloquem suas sugestões aqui na issue

**Comment by alessandrapedrotti** [comment]
Acho que seria muito interessante fazer um tutorial de edição de áudio em formato de podcast. Assim podemos testar se esse formato funciona e aí aplicá-lo em outros produtos também.

**Comment by Dovyski** [comment]
Concordo plenamente com a @alessandrapedrotti. Temos uma infra considerável que pode transformar os materiais tanto para vídeo quanto para audio. Acho que diversos dos nossos materiais podem ser transformados em podcast (como a cartilha de vídeo aulas, por exemplo).

**Comment by MaNegrao** [comment]
as ideias e as produções dessas issues estão sendo disrtribuidas
