### ISSUE TITLE
Trocar o dono das pastas no drive de cada uma das tarefas

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#165]
Atualmente cada uma das [pastas de tarefas](https://drive.google.com/drive/folders/1aBjyA92_IdiPJokAJyBF9HtIKzMIVqvQ) tem um dono diferente no Google Drive. O dono é geralmente quem criou a pasta. O problema é que, se a minha conta (dovyski@gmail.com) não for a dona da pasta, o conteúdo da pasta conta para a cota de espaço para drive de vocês.

Isso fez com que a gente estourasse o limite de armazenamento do drive. Para solicitar esse problema, por favor, se você criou uma pasta de trabalho [aqui](https://drive.google.com/drive/folders/1aBjyA92_IdiPJokAJyBF9HtIKzMIVqvQ), faça o seguinte:

- Clique com o botão direito na pasta em questão e selecione "Share" (ou compartilhar, se estiver em portugues):

![image](https://user-images.githubusercontent.com/512405/94570812-a1791c80-0245-11eb-9ac8-14868c788a21.png)

- Procure o meu usuário na lista, clique na "setinha para baixo" ao lado de `Editor` ou `Ver` e escolha "Make owner" ("Tornar dono"):

![image](https://user-images.githubusercontent.com/512405/94571046-e8671200-0245-11eb-8cce-b3a8a15a6cc6.png)

Pronto, eu passo a ser dono da pasta e o espaço que ela ocupa é contabilizado na minha conta do Google, não na de vocês.

**Comment by Dovyski** [comment]
@practice-uffs/todos por favor, sigam as instruções acima dessa issue para liberarem espaço em seus Google Drives e permitir que as pastas do practice possam ser usadas de novo (atualmente clientes não podem mais colocar arquivos porque não temos espaço; teremos espaço quando todas as pastas de trabalho forem passadas para a minha conta).

**Comment by alessandrapedrotti** [comment]
Feito.

**Comment by isabelirk** [comment]
Feito

**Comment by VIF-Franca** [comment]
Feito
