### ISSUE TITLE
Panfletos de divulgação

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#166]
Utilizem os comentários dessa issue para colocar o texto (ou os textos) que vocês julgam interessantes para estarem nos panfletos de divulgação dos serviços do PRACTICE.

Cada líder pode julgar o que é mais ou menos importante de se estar nesses materiais de divulgação, porém existem alguns aspectos obrigatórios, que são:

- O texto deve ser conciso;
- O texto deve tratar diretamente com o leitor;
- O texto deve ser atrativo;
- Não pode ser uma cópia do que já está no site;
- Os recursos necessários devem estar claros no texto;
- **Os prazos de solicitação e entrega dos serviços devem estar claros e em posição de destaque.**

Após todos os líderes postarem aqui os textos de suas respectivas equipes, os panfletos serão produzidos pela equipe de conteúdo.

@practice-uffs/lideres 

[Pasta Drive](https://drive.google.com/drive/folders/1tNCuwAXn5-j8v5lP3dvbyqQFLauygJKn)

**Comment by MaNegrao** [comment]
Não entendi ao certo, nós vamos criar um panfleto para cada serviço ou um para cada equipe?

**Comment by alessandrapedrotti** [comment]
> Não entendi ao certo, nós vamos criar um panfleto para cada serviço ou um para cada equipe?

Serão panfletos por equipe, mas o objetivo é apresentar os serviços que aquela equipe oferece. Não tem necessidade de colocar no panfleto o que é a con-midia ou a con-conteúdo, por exemplo.
Ficou mais claro agora?

**Comment by MaNegrao** [comment]
Sim, ficou mais claro

**Comment by alessandrapedrotti** [comment]
Reitero que os líderes precisam enviar os textos o mais rápido possível, para que a equipe de conteúdo possa trabalhar na revisão e diagramação dos textos.

**Comment by MaNegrao** [comment]
O texto do panfleto de midia está na pasta

**Comment by estelavilasboas** [comment]
Escrevi uma primeira versão do texto para serviços de identidade visual, está no [arquivo de Serviços de Conteúdo](https://docs.google.com/document/d/1pzbUOoZ93rfCWmSK8flUH6AxtR6P1zW5pOHv5ikKCiI/edit).

**Comment by MaNegrao** [comment]
@practice-uffs/con-conteudo todos os textos de midia foram atualizados e separados conforme reunião e definição de lideres hoje (13/10). Eu separei entre serviços de audio e video, estudio e eventos online

**Comment by thaliafriedrich** [comment]
> @thaliafriedrich peço para que você revise os textos que estão nesta issue.

Revisão dos textos concluída. Deixei um comentário para possível complementação de uma informação sobre os serviços de conteúdo.

**Comment by alessandrapedrotti** [comment]
> > @thaliafriedrich peço para que você revise os textos que estão nesta issue.
> 
> Revisão dos textos concluída. Deixei um comentário para possível complementação de uma informação sobre os serviços de conteúdo (@alessandrapedrotti).

Alteração feita. Também troquei uma palavrinha por outra e adicionei uns sinais de pontuação que estavam faltando.

**Comment by MaNegrao** [comment]
@alessandrapedrotti ficou faltando uma informação no panfleto de estúdio que eu me recordei agora, eu coloquei no arquivo, não sei se precisará de revisão etc. Perdão por ser em cima da hora, mas é algo de suma importância.
