### ISSUE TITLE
Apresentação dos novos bolsistas

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#167]
Cada um dos novos integrantes do projeto deve elaborar um texto de apresentação sobre si mesmo. Esse texto será utilizado para divulgações e posts nas redes sociais do programa e também serve para que os antigos membros do PRACTICE conheçam melhor os novos bolsistas.
É importante que todos **respeitem o limite de 500 caracteres no texto** de apresentação e tenham claro que esse texto poderá sofrer alterações por questões de clareza, concordância e erros gramaticais.

Caso vocês tenham dúvidas de como escrever, confiram as respostas dos membros mais antigos na issue #62.

A apresentação obrigatoriamente deve conter:

- Nome completo ou nome social;
- 1 foto de cada integrante que mostre claramente o rosto da pessoa (sem óculos escuros, chapéus e outros adereços).

@practice-uffs/todos

**Comment by MilenaPaz2020** [comment]
Acadêmica do curso de Licenciatura em Ciências Biológicas da UFFS Realeza, enfatiza que é licencianda, por compreender a importância da profissão docente. Como há de se perceber, ama a educação e ama estudar e falar sobre ela. Gosta de fazer arte, de colocar a mão na massa nos DIY da vida e cozinha por prazer e sobrevivência. É caseira, preza pelo tempo de qualidade com a família e busca uma vida mais sustentável. Naturalmente inquita, está disposta a novos desafios de vez em sempre.

![image](https://user-images.githubusercontent.com/71154460/94683380-d300ef00-02fc-11eb-83f0-a4abfbbf0168.png)

**Comment by brendaellen** [comment]
Brenda Ellen de Sousa Reis, é acadêmica do curso de Engenharia Ambiental e Sanitária na UFFS campus Erechim, voluntária no Laboratório de Qualidade da Água, e vice-presidente do diretório acadêmico de seu curso. É goiana, taurina, e gosta muito de viajar, dançar, e ouvir flashbacks. Também é potterhead, e adora expressar por meio da escrita o modo como observa o mundo e as pessoas.
![brenda](https://user-images.githubusercontent.com/71678514/94691187-617a6e00-0307-11eb-82e6-4a1d95c7a438.jpg)

**Comment by luizatonial** [comment]
Luiza Dall'Bosco Tonial é acadêmica de Arquitetura e Urbanismo na UFFS - Campus Erechim. Integrante do PRACTICE e de outros projetos de pesquisa da universidade, procurando sempre aprender e desenvolver algo novo. É mãe de pet, apaixonada por animais, viagens, fotografia, música e café. No tempo livre, gosta de desenhar e de assistir documentários, séries, filmes de suspense ou um programinha de reforma/construção. Também é Técnica em Agrimensura pela UTFPR - Pato Branco.

![042 - Copia](https://user-images.githubusercontent.com/71669357/94699196-6f80bc80-0310-11eb-91ac-d39125e137b7.JPG)

**Comment by ricardopatrik** [comment]
Ricardo Patrik Manfro é acadêmico do curso de Engenharia Ambiental e Sanitária do campus Cerro Largo/RS. Sempre que possível, está em contato com a natureza. Seja acampando, fazendo trilha, visitando cachoeiras entre outros. Optou pelo curso pois acredita que dessa maneira pode contribuir de modo positivo para a preservação do meio ambiente. Extrovertido, gosta de encontrar amigos para bater um papo. O estilo musical é bastante eclético, de Falcão à Megadeth e Gremista, é claro.



![eu](https://user-images.githubusercontent.com/71683219/94706173-419f7600-0318-11eb-94c3-b873f5d28eaa.JPG)

**Comment by thaliafriedrich** [comment]
Thalía Lopes Friedrich é acadêmica de Engenharia Ambiental e Sanitária da UFFS _Campus_ Cerro Largo. Participou de projetos de pesquisa relacionados à energia solar, monitoramento ambiental e _machine learning_. Atualmente, é integrante do Programa PRACTICE e voluntária em um projeto sobre sistemas hidropônicos e fitorremediação. Nas horas de lazer, gosta de estar em contato com a natureza e animais, ler, ouvir músicas, assistir filmes e documentários.
![foto](https://user-images.githubusercontent.com/71574882/94718110-9dbdc680-0327-11eb-968b-4fa2ff7c9df3.jpg)

**Comment by morgana-mo** [comment]
Morgana Maciél Oliveira é acadêmica do curso de Química Licenciatura da UFFS-Campus Cerro Largo, diretora de divulgação marketing do diretório acadêmico de seu curso. Já atuou em projetos de pesquisa sobre Educação Ambiental,Co-digestão anaeróbia de dejetos suínos e políticas educacionais, atualmente é integrante do PRACTICE. Nas horas vagas  é aspirante a escritora em um blog, gosta de ler livros de ficção, ouvir música, é entusiasta de futebol (vamo Inter!) e de uma boa conversa com os amigos.
![78968207_1904316013047015_2700274934319415296_n](https://user-images.githubusercontent.com/71781124/94728132-27749080-0336-11eb-817a-1741ff6adaf8.jpg)

**Comment by juliagaio** [comment]
Julia Gaio é acadêmica do décimo semestre do curso de Medicina do campus Passo Fundo. Catarinense em solo gaúcho. Mãe da Pedrita. Adoro viajar, ler e assistir séries!

<img width="237" alt="selfi" src="https://user-images.githubusercontent.com/71721103/94731025-83411880-033a-11eb-9c04-bd53fa72c4be.png">

**Comment by Claudineia-VR** [comment]
Claudinéia V. Raimundi é acadêmica do curso de Engenharia Ambiental e Sanitária da UFFS Chapecó. Nas horas vagas gosta de assistir séries e animes, ouvir música, ler e principalmente sair para interagir com a família e amigos. Apaixonada por plantas, fotografia, viagens, conhecer novos lugares, naturezas e culturas.
![IMG-6642](https://user-images.githubusercontent.com/71708078/94728973-6bb46080-0337-11eb-83c3-88233248fb8e.JPG)

**Comment by robisonjose** [comment]
Robison José, acadêmico do curso de Física - Licenciatura na UFFS de Realeza no Paraná. Divulgador científico nas horas vagas, possui um canal no YouTube chamado Garoa de ideias e um Podcast de mesmo nome. Não gosta de nada específico, mas gosta de ciência. E joguinhos eletrônicos. 

![20200918_110701](https://user-images.githubusercontent.com/71669689/94741376-6d3b5400-034a-11eb-9122-16d8d2500a19.jpg)

**Comment by luizdameda** [comment]
Luiz Eduardo Dameda é acadêmico do curso do curso de Medicina da UFFS - Campus Passo Fundo. É presidente fundador da Liga Acadêmica Passo-Fundense de Otorrinolaringologia e membro da Liga Acadêmica de Dermatologia da UFFS. Atuou também como produtor audiovisual e design gráfico no projeto de extensão “Histórias desenhadas: uma abordagem consciente e efetiva de prevenção”. Considera-se uma pessoa proativa e dinâmica, que está em constante evolução e que procura dar o seu melhor em tudo que faz. Nas horas vagas gosta de assistir séries, de ler e de passar o tempo com amigos. 
![image](https://user-images.githubusercontent.com/71671053/94743679-2baca800-034e-11eb-9555-c00382fd2161.jpeg)

**Comment by amandasegattob** [comment]
Amanda Segatto Bisognin é acadêmica do curso de Medicina da UFFS, _campus_ Chapecó, diretora de marketing da atlética do seu curso e integrante de outros projetos da universidade. Sagitariana inquieta, está sempre buscando novas experiências. Ama viajar, sair com os amigos, ouvir músicas, assistir séries e ler.![Uploading 94751542...]

**Comment by amandasegattob** [comment]
Amanda Segatto Bisognin é acadêmica do curso de Medicina da UFFS, campus Chapecó, diretora de marketing da atlética do seu curso e integrante de outros projetos da universidade. Sagitariana inquieta, está sempre buscando novas experiências. Ama viajar, sair com os amigos, ouvir músicas, assistir séries e ler.

![image](https://user-images.githubusercontent.com/71669953/94751579-771b8200-035f-11eb-9bdc-a55f852754b7.jpeg)

**Comment by amandasegattob** [comment]
Amanda Segatto Bisognin é acadêmica do curso de Medicina da UFFS, campus Chapecó, diretora de marketing da atlética do seu curso e integrante de outros projetos da universidade. Sagitariana inquieta, está sempre buscando novas experiências. Ama viajar, sair com os amigos, ouvir músicas, assistir séries e ler.

![image](https://user-images.githubusercontent.com/71669953/94751737-9fa37c00-035f-11eb-8712-48f4736659aa.jpeg)

**Comment by anacarolinamorigi** [comment]
Ana Carolina Morigi da Cruz Silveira, acadêmica de Medicina da UFFS do Campus Passo Fundo. Atua como responsável pelo marketing do diretório acadêmico do seu curso e, atualmente está responsável pelo marketing da V Semana Acadêmica Interinstitucional de Medicina de Passo Fundo - IMED e UFFS. Apaixonada pelas áreas de fotografia e de escrita, se arrisca nelas a mais de 6 anos. Acredita que todas as experiências vividas trazem aprendizados importantes para a vida. Está sempre buscando aprender algo novo e se aprimorar naquilo que gosta. ARMY fervorosa, acredita que a música pode mudar o mundo e fazer com que sua voz seja ouvida. 

![image](https://user-images.githubusercontent.com/71719917/94756053-d5029680-036c-11eb-87eb-a9913702b6d0.jpeg)

**Comment by VIF-Franca** [comment]
Raphael Borges Dos Santos Filho
Gessica Tagliapietra Zanon
Taynara Chayane Christmann

**Comment by oraphaBorges** [comment]
Raphael Borges um paulistano Gay e graduando de Ciência da Computação da UFFS Chapecó, apaixonado por idiomas, Desenvolvimento de Software, Inteligência Artificial e Pokémon.
Foi Vice-presidente do Centro Acadêmico de Computação, coordenador do CVUFFS grupo de estudos de Visão Computacional e trabalhou no setor de TI da UFFS como estagiário e bolsista, desenvolvendo, gerenciando e participando de vários projetos e agora traz toda essa bagagem pro PRACTICE em prol da Ciência e da Educação!

![20191228_154551](https://user-images.githubusercontent.com/22224088/94852826-d4b3db00-0400-11eb-8eb7-47d195f45c1b.jpg)

**Comment by GessicaZanon** [comment]
Meu nome é Gessica Tagliapietra Zanon e curso Física-Licenciatura pela UFFS-Realeza. Sou diretora e tesoureira do Centro Acadêmico ALFA e gosto de estar sempre envolvida no que a UFFS e o curso podem proporcionar. Sou apaixonada pela docência e por estar inovando em sala de aula. Gosto de estar perto da minha família e das pessoas que amo. Sou leonina, gremista e tento estar sempre alegre. Apaixonada pelos animais e
 gosto muito de séries, filmes e música.
![IMG_0004](https://user-images.githubusercontent.com/71669230/94914843-294b6a80-0482-11eb-8f9f-096802915beb.jpg)

**Comment by alessandrapedrotti** [comment]
Favor @TaynaraCh, @arufonsekun @JeanCHilger adicionar suas respectivas descrições.

**Comment by TaynaraCh** [comment]
Meu nome é Taynara,  sou estudante do curso de Arquitetura e Urbanismo na UFFS Erechim. Sou muito apaixonada por tudo que envolva arte, processos criativos e trabalhos em grupo, por isso fico muito feliz em fazer parte do PRACTICE. Além disso, amo viajar, e mais do que conhecer lugares, amo conhecer culturas diferentes das minhas, amo o verão, a brisa do mar, bares, roles e principalmente quando junta tudo.
![WhatsApp Image 2020-10-07 at 09 20 44](https://user-images.githubusercontent.com/71676790/95330367-d6592500-087e-11eb-8161-2c1448004e99.jpeg)

**Comment by arufonsekun** [comment]
Junior Vitor Ramisch é acadêmico de Ciência da Computação da UFFS Campus Chapecó. Está iniciando sua jornada na pesquisa nas áreas de Visão Computacional e Inteligência Artificial. Nas horas vagas, e nem tão vagas, assiste anime, vê memes, joga Minecraft, ouve nerdcast, rock/metal e eventualmente alguns J-POPs. Sua comida preferida é CupNoodles e biluzitos de churrasco. Gosta de contribuir com projetos open-source, por isso atua como voluntário no programa Practice, seu grande sonho é fazer um cosplay de Naruto.
OBS: se o texto estiver muito esquisito eu arrumo, sem problemas, e desculpa pela demora.
![trash-2](https://user-images.githubusercontent.com/19571204/95362946-31057780-08a5-11eb-8d6d-4cf20f64a173.jpg)

**Comment by alessandrapedrotti** [comment]
Favor @rafaguilman, agora que foi inserido na organização do programa, fazer sua apresentação de acordo com a descrição dessa issue.

**Comment by rafaguilman** [comment]
Rafael Guilman, Academico do Curso de Agronomia, Campus Larajeiras do Sul. Bolsista do Programa PRACTICE,foi monitor de Saúde do Campus,  apaixonado por Música,e apaixonado por Jesus e por fazer o seu nome Conhecido.
![Rafa](https://user-images.githubusercontent.com/72272438/95661045-87bbbd00-0b02-11eb-9ef8-ec6f1fae41b8.jpg)

**Comment by alessandrapedrotti** [comment]
@VIF-Franca favor adicionar os textos dos colegas a planilha já existe (criada para a tarefa #62) para que assim possamos revisar os textos e colocá-los na ordem de postagem das redes sociais. Após isso, essa issue será fechada.

**Comment by VIF-Franca** [comment]
@alessandrapedrotti , todos os colegas foram inseridos na planilha pode revisar o texto.

**Comment by alessandrapedrotti** [comment]
O que está posto na planilha foi revisado.

Aguardamos o voluntário @JeanCHilger postar sua apresentação para finalizarmos a tarefa.

**Comment by VIF-Franca** [comment]
@practice-uffs/con-design  

Podem elaborar as imagens para serem inclusas no cronograma de postagem.

**Comment by alessandrapedrotti** [comment]
> @practice-uffs/con-design
> 
> Podem elaborar as imagens para serem inclusas no cronograma de postagem.

Essa tarefa é da @practice-uffs/ger-comunicacao

**Comment by estelavilasboas** [comment]
> > @/ practice-uffs/con-design
> > Podem elaborar as imagens para serem inclusas no cronograma de postagem.
> 
> Essa tarefa é da @practice-uffs/ger-comunicacao

As bases com transparência estão na [pasta da issue #140](https://drive.google.com/drive/folders/1FBf6smy2vFT2yOBFcW_8JmsNAYibTGUS)

**Comment by VIF-Franca** [comment]
@practice-uffs/ger-comunicacao , aguardo as artes para adicionar no cronograma de postagem.

**Comment by JeanCHilger** [comment]
Jean Carlo Hilger é acadêmico de Ciência da Computação pela UFFS campus Chapecó. Possui um grande carinho pela vida acadêmica, buscando sempre estar participando de projetos de pesquisa ou ensino. É apaixonado por Star Wars e por qualquer filme do Tarantino. Adora auxiliar em qualquer iniciativa de cunho educacional, e portanto ser voluntário no PRACTICE está sendo maravilhoso.

![lixo](https://user-images.githubusercontent.com/19687197/97364359-b36cd000-1882-11eb-869c-00cac8f2bd6a.jpeg)

**Comment by alessandrapedrotti** [comment]
@VIF-Franca adicionar o último voluntário na planilha e encerrar a issue. Será aberta uma nova com o cronograma de postagens.

**Comment by VIF-Franca** [comment]
Feito e encerrada!
