### ISSUE TITLE
[Mídias sociais] Perfil no Twitter

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/programa#17]
É necessário criar e configurar um perfil no Twitter para o PRACTICE, o qual será utilizado para veicular algumas de nossas postagens. Mais informações serão devidamente adicionadas posteriormente (como nome padronizado, imagens, descrição, etc).

**Comment by franca20** [comment]
@PracticeProjeto. e-mail e senha em arquivo interno.

**Comment by franca20** [comment]
Logo adicionada

**Comment by VIF-Franca** [comment]
Texto  postado na descrição do perfil.
