### ISSUE TITLE
Gravação e Transmissão LIVE 14/10

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#170]
Realizar a live do Observatório Social de Laranjeiras do Sul, será utilizada o laboratório de mídias para a transmissão e filmagem.

**Comment by VIF-Franca** [comment]
Solicitação de roteiro enviado.

@lucasgalize  irá tocar ao vivo.

**Comment by VIF-Franca** [comment]
Apresentação do Observatório Social inserida no Drive.

**Comment by MaNegrao** [comment]
@VIF-Franca essa live foi concluída? caso sim podemos fechar essa issue.

**Comment by VIF-Franca** [comment]
Estou aguardando informações sobre o evento, no dia e horário da live houve queda de energia no campus. Solicitei informações se ainda acontecerá a live.

**Comment by VIF-Franca** [comment]
A UFFS não foi utilizada para a transmissão da Live. A issue pode ser fechada.
