### ISSUE TITLE
Revisão do fluxograma dos serviços de conteúdo

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#173]
Rever e melhorar o fluxograma já existente dos serviços da equipe de conteúdo, conforme o conversado em reunião.

**Comment by mariagelain** [comment]
O novo fluxograma irá abordar três diferentes seções dentro da @practice-uffs/con-conteudo dado que cada parte da equipe trabalha com um tempo de produção diferente, sendo assim as seções são:

-  roteiro

-  conteúdo

-  imagem/design

**Comment by isabelirk** [comment]
Boa tarde,
referente a parte de conteúdo sobre tempo estimado: da parte interno, acredito que entre 4 a 6 dias, e externa entre 6 a 8 dias (considerando a troca de mensagem com os solicitantes na questão de duvidas sobre a demanda).
Atenciosamente.

**Comment by mariagelain** [comment]
O [fluxo de trabalho](https://docs.google.com/document/d/1HgJIxk3M9TfI7iLMW1FHsXTgC6Zb1ApIay_dqlVTyA0/edit) está finalizado.
