### ISSUE TITLE
Descrição dos serviços de imagem

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#174]
Produzir textos de descrição para os serviços de imagem que serão ofertados pela equipe de conteúdo/desing.

Descrever:
 - ID simples

- [x] Logo;
- [x] Símbolo;
- [x] Paleta;

 - ID completa

- [x] Logo;
- [x] Símbolo;
- [x] Paleta;
- [x] Marca d'água;
- [x] Padronagem.

**Comment by estelavilasboas** [comment]
Em andamento. [Pasta](https://drive.google.com/drive/folders/1MbvSNsuyD1oxWZK3SnydpfIbmqLfHolR).

**Comment by alessandrapedrotti** [comment]
O texto está promissor, sugiro a adição de:

- [ ] Um parágrafo introdutório, explicando que serão apresentados os 5 elementos principais de uma ID;
- [ ] Um parágrafo de conclusão, orientando o leitor de que ele pode optar ou pelo pacote simples (que contém símbolo, logo e paleta) ou pelo pacote completo (que contém os 5 elementos já descritos).

**Comment by estelavilasboas** [comment]
Adicionei uma pergunta no início, assim como nos serviços de estúdio e de evento virtual, e uma breve introdução como a dos serviços de texto.
Adicionei uma seção chamada pacotes.
Também adicionei imagens da identidade visual do PRACTICE para exemplificar.

**Comment by alessandrapedrotti** [comment]
Texto pronto para ir para o site.
Sugiro que dividam [a página de serviços de conteúdo](https://practice.uffs.cc/servico/conteudo/) em duas sessões, a primeira com o título "Texto" e com o texto que já está no site e um segundo título "Imagem" com as informações do documento elaborado pela Estela.

@practice-uffs/dev-web

**Comment by Dovyski** [comment]
Criei a issue https://github.com/practice-uffs/website-programa/issues/62 para a @practice-uffs/dev-web para colocar no site a alteração. Se quiser fechar essa issue aqui, @alessandrapedrotti , pode fechar.
