### ISSUE TITLE
Reestruturação da equipe ger-aux

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#175]
A equipe ger-aux tem o objetivo de garantir que a gerência do programa, seus membros e suas equipes consigam trabalhar com o mínimo de ruído de comunicação e da forma mais fluída possível. Ela é encarregada, por exemplo, de criar e gerir as tarefas que afetam mais de uma equipe, como coordenar reuniões, publicação de materiais em redes sociais, elo entre cliente e equipe, etc. Geralmente os membros da ger-aux também desempenham papel em outras equipes, então o trabalho não é limitado à ger-aux sozinha. 

Na última reunião de líderes, decidimos reestruturar essa equipe para melhor atender o programa.

A nova composição da equipe passa a ser de 3 bolsistas, sendo um deles líder, conforme o seguinte:

Líder: @alessandrapedrotti 
Integrante: @VIF-Franca 
Ingrante: _(vacante)_

Precisamos de mais um integrante para ocupar a posição vacante na equipe ger-aux. Essa issue é para tratarmos quem será essa pessoa.

cc: @practice-uffs/todos

**Comment by alessandrapedrotti** [comment]
Acredito que um bom caminho para encontrarmos esse novo integrante seja a leitura das cartas de intenções e a leitura das apresentações que os novos bolsistas estão escrevendo na issue #167. Assim teremos uma visão geral de quem tem as características e habilidades que seriam interessantes para a equipe.

Posso assumir essa função se não houver nenhum impeditivo.


Gostaria de deixar em aberto a possibilidade de termos uma reunião/conversa, depois que o novo bolsista for colocado na equipe, para definirmos qual é o papel de cada um.

**Comment by VIF-Franca** [comment]
Ok!

**Comment by alessandrapedrotti** [comment]
Analisei os textos dos novos bolsistas e cheguei a uma possível candidata para integrar a equipe. Também desenvolvi algumas ideias para a reestruturação da equipe.

De acordo com os horários que o @Dovyski me informou ter disponíveis, elaborei esse [doodle](https://doodle.com/poll/wzp4r4kvbshcehsz) para votarmos um dia para a reunião de organização da equipe.

@Dovyski @VIF-Franca

**Comment by alessandrapedrotti** [comment]
De acordo com a votação, a reunião ocorrerá hoje (05/10) às 16h.
@VIF-Franca @Dovyski
