### ISSUE TITLE
Edição de vídeo Letras CH (PTA E LPT): 1º vídeo - Texto e Discurso. Prof Eric

### ISSUE THREAD

**Issue by vini2reis** [practice-uffs/programa#176]
Essa issue em questão refere-se ao vídeo 1 - Texto e Discurso. Prof Eric.  **O vídeo está [nesta pasta](https://drive.google.com/drive/folders/1vNaBz54zgz37hUMSEGTvHRPxugklUifW?usp=sharing)** 

> Essa série de issues são relacionadas a issue #151, cada uma delas representa um vídeo a ser editado. Todas as edições seguem o mesmo padrão (**[que pode ser visto aqui](https://drive.google.com/file/d/10zu3aqn9TuRuyDK-IlqgNJHCcIV91ZEY/view?usp=sharing)**) e são feitas no software ShotCut. 

> Os materiais do programa podem ser encontrados na [pasta de materiais](https://drive.google.com/drive/u/3/folders/1uSbwV0EYRQywqVKjY95EsDSd-kT9UmqS) e as ferramentas no [guia do programa](https://guia.practice.uffs.cc)

As etapas de edição desses vídeos são:

- **Primeira etapa:**

- [x] Realizar edição inicial do vídeo seguindo orientações do respectivo professor e agregar slide enviado (arquivos na pasta). Os slides devem ser baixados em formato de imagem, para serem mais facilmente utilizados na edição.
- [x] Caso tenha imagens que precisem de áudio descrição deve-se gravar e agregar ao vídeo.
- [x] Criar uma pasta no link dessa issue chamada _Em progresso_ e armazenar todo conteúdo e o andamento da edição nela.
- [x] Criação da pagina dos créditos seguindo o [template](https://drive.google.com/drive/u/0/folders/1qIai8gugPK9OydUx8P5lcpK4D8vA6n1E) feito pela equipe de conteúdo.
- [x] Inserção das vinhetas e da pagina de créditos com a seguinte ordem:  
[Vinheta de Letras](https://drive.google.com/file/d/1Eiq7A1TRdhYRLFUdVpFPX-CSWwF6M8v_/view?usp=sharing) - Vinheta PRACTICE - Vídeo - Vinheta Letras - Créditos - Vinheta PRACTICE

- **Segunda etapa:**

Com a edição inicial concluída, deve ser feita a legenda do vídeo.

- [x] Upar vídeo editado no YouTube para criação da legenda automática (Para saber como fazer isso, veja o vídeo [deste link](https://drive.google.com/file/d/1Xr-v-E0nF7YHpjiVx94QOUlUhKh9Qu8C/view?usp=sharing))
- [x] Corrigir as palavras erradas da legenda automática gerada e baixar o arquivo .srt (seguindo o vídeo do tópico anterior)
- [x] Com a legenda finalizada, disponibilizar o arquivo e marcar a equipe de conteúdo para revisão textual.
- [x] Ao final da revisão as legendas devem ser adicionadas ao vídeo através do software Format Factory (Veja como fazer [aqui](https://drive.google.com/file/d/1X4H8jWbZ9jNN8j6kFaZ1u9N-JECNTdga/view?usp=sharing))
- [x] Com o vídeo finalizado e com as legendas, enviar ao professor para revisão e apontar possíveis ajustes.
- [ ] Caso tenha, realizar os ajustes solicitados.

**Comment by MorganaCambrussi** [comment]
Oi! Eric colocou os arquivos dele na pasta: https://www.dropbox.com/sh/jl2l4c009db7qqh/AABamlN89EU2RGWe0mCz9SEPa?dl=0
Ele disse não ter conseguido add ao drive. Obrigada!

**Comment by alessandrapedrotti** [comment]
Responsável: @GessicaZanon 
É necessário fazer a transposição dos slides disponibilizados pelo(a) professor(a) referente a esse vídeo. 
Para fazer a transposição você deve:

- [ ] Localizar o template elaborado para o curso [nesta pasta](https://drive.google.com/drive/u/0/folders/13sFE1Q_t-8nkXAKBbKpj0oKvc64vFM8L);
Os templates utilizados serão os de capa, créditos 02 e 05; Sendo o 02 para trechos com título e texto e o 05 para trechos com imagem;
- [ ] **Copiar** o template e **transferi-lo** para a pasta dessa tarefa (edição) em questão (que está posta na descrição dessa tarefa);
- [ ] Adicionar títulos, textos, imagens e referências em sua totalidade;
- [ ] Conferir se margens, fontes, tamanhos das fontes e parágrafos estão padronizados em toda a apresentação;
- [ ] Conferir erros de digitação.

**Comment by alessandrapedrotti** [comment]
Responsável: @thaliafriedrich 
Para a revisão textual das legendas:

- [ ] Assistir ao vídeo concomitantemente a leitura da transcrição com a minutagem;
- [ ] Fazer alterações de pontuação e ortografia;
- [ ] Mudar palavras caso elas não estiverem na fala do prof (as vezes a legenda automática coloca umas palavras nada a ver com o que está sendo dito);
- [ ] Rever o vídeo e reler a transcrição da legenda, para ter certeza que nenhum trecho ficou errado.

Observações:
Não há necessidade de deixar no texto da legenda vícios de linguagem, como "tipo", "né" ou similares.

**Comment by thaliafriedrich** [comment]
Aguardando a disponibilização das legendas para revisão.

**Comment by GessicaZanon** [comment]
Transposição dos slides finalizada. Disponível [nessa pasta.](https://drive.google.com/drive/folders/1aORRqPPOZhsQH1J6ZEHFwuEsR7VKjH0f)

**Comment by MaNegrao** [comment]
@thaliafriedrich As legendas estão disponíveis na pasta Em Progresso

**Comment by thaliafriedrich** [comment]
> @thaliafriedrich As legendas estão disponíveis na pasta Em Progresso

Revisão das legendas finalizada.

**Comment by MaNegrao** [comment]
@rafaguilman As legendas finalizadas e revisadas em .srt estão na pasta em progresso, basta agora trocar os slides pelos slides finais colocar a legenda com o format factory

**Comment by MaNegrao** [comment]
vídeo finalizado!
