### ISSUE TITLE
Resumo da reunião de boas-vindas (02/10/2020)

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#178]
A primeira reunião de boas-vindas com os novos bolsistas foi feita. Segue aqui um resumo do que foi tratado:

* Boas-vindas novos bolsistas
* Apresentação do programa (com [esses slides](https://docs.google.com/presentation/d/1QfNSkFke1lDLNVAQQawnM1-YmgpFU-aIv3UC4Cxq-Xo/edit#slide=id.g81e6cb5a66_3_0))
* Capacitação básica no github

Para aqueles que participaram da reunião, por favor, postem nessa issue algo como "Eu participei da reunião", para termos registro de quem estava. Além disso, podem postar em seguida qualquer dúvida que ainda tenham. Isso é uma boa oportunidade de ambientar vocês mais um pouco com o github.

Para saber um pouco mais sobre o github, nossa equipe fez um [manual de consulta rápido](https://drive.google.com/file/d/1QrP-AZ2dbRMB4oYVbN-ksCu5xJdlYKvw/view?usp=sharing).

cc: @practice-uffs/todos

**Comment by brendaellen** [comment]
Eu participei da reunião.

**Comment by thaliafriedrich** [comment]
Eu participei da reunião.

**Comment by luizatonial** [comment]
Participei da reunião

**Comment by oraphaBorges** [comment]
Eu participei da reunião

**Comment by juliagaio** [comment]
Eu participei da reunião

**Comment by estelavilasboas** [comment]
Eu participei da reunião

**Comment by MilenaPaz2020** [comment]
Eu participei da reunião.
