### ISSUE TITLE
[Mídias sociais] Página no Facebook

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/programa#18]
É necessário criar e configurar uma Página no Facebook para o PRACTICE, o qual será utilizado para veicular algumas de nossas postagens. Mais informações serão devidamente adicionadas posteriormente (como nome padronizado, imagens, descrição, etc).

**Comment by franca20** [comment]
Facebook criado, informações para tornar-se administrador da pagina em arquivo interno.

**Comment by franca20** [comment]
Logo adicionado

**Comment by VIF-Franca** [comment]
Texto adicionado.

**Comment by elisribas** [comment]
@VIF-Franca criamos a página juntos, apenas não informei aqui no Github.
Criei uma conta e uma página para o Practice no Face.
Por favor, migrar as publicações, caso já existam, para essa conta que eu criei, pois vinculei ao e-mail do Practice.
Infos de acesso no drive.
https://docs.google.com/document/d/1ZTdpl25dCmZ-E6QWiivqmHvp6XytJhI44II9AAoYVug/edit

**Comment by elisribas** [comment]
Dados de acesso no Face disponíveis em:
https://docs.google.com/document/d/1aPWinXbLsKCjPzu458YfRT4N9fIAc36vrlH-267bTlE/edit 
@VIF-Franca

**Comment by VIF-Franca** [comment]
Perfeito, Obrigado

**Comment by elisribas** [comment]
@VIF-Franca pode ajudar a fazer com o que o nome da página do Face seja practiceuffs ? 
Obrigada

**Comment by VIF-Franca** [comment]
> @VIF-Franca pode ajudar a fazer com o que o nome da página do Face seja practiceuffs ?
> Obrigada

Ainda não é possível, assim que a plataforma permitir será realizada.
