### ISSUE TITLE
ATUALIZAÇÃO - mapeamento de funções

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#183]
Retomada da tarefa #121 com a atualização das funções atuais dos líderes de equipe, assim como a inserção dos novos bolsistas e adição do tempo de serviço de cada um dos atuais e antigos membros do programa.

Estamos retomando essa tarefa para atualizar a página de equipe do site, assim como prestar os devidos créditos a todas as pessoas que já trabalharam ( e as que ainda trabalham) no programa.

Após a inserção dos novos bolsistas aos fluxos de trabalho de suas respectivas equipes, também serão adicionadas suas disponibilidades de horários. 

@VIF-Franca preciso que você permita meu acesso ao [documento](https://docs.google.com/spreadsheets/d/15kGGrER8UTGQhPIvGm2jHhs3pEO6f7gqISZgRyqpMKE/edit#gid=1145326100).

**Comment by VIF-Franca** [comment]
@alessandrapedrotti acesso permitido.

**Comment by alessandrapedrotti** [comment]
Favor @mariagelain @CleissonVieira @estelavilasboas @vini2reis conferir a página horários da planilha e informar aqui nos comentários quais seriam seus respectivos horários disponíveis.

**Comment by CleissonVieira** [comment]
Agora que iniciou as aulas eu refiz rotina, meus horários são:

| Dia   |     Horário      |
|----------|:-------------:|
| Segunda-feira |  16h às 19h |
| Terça-feira |    16h às 19h |
| Quarta-feira | 13h às 16h |
| Quinta-feira | 13:30h às 17:30h e 18h às 22h |
| Sexta-feira | 13h às 16h |

**Comment by alessandrapedrotti** [comment]
Favor, informem seus turnos disponíveis

@amandasegattob
@anacarolinamorigi
@brendaellen
@Claudineia-VR
@GessicaZanon
@juliagaio
@luizdameda
@luizatonial
@MilenaPaz2020
@morgana-mo
@rafaguilman
@oraphaborges
@ricardopatrik
@robisonjose
@TaynaraCh
@thaliafriedrich

**Comment by robisonjose** [comment]
Todas as manhãs das 08:00 - 12:00.

**Comment by Claudineia-VR** [comment]
Dia | Horário
-- | --
Segunda-feira | 14h às 18h
Terça-feira | 17:30h às 19:30h
Quarta-feira | 14h às 18h
Quinta-feira | 14h às 18h 
Sexta-feira | 14h às 20h e

**Comment by Claudineia-VR** [comment]
Dia | Horário
-- | --
Segunda-feira | 14h às 18h
Terça-feira | 17:30h às 19:30h
Quarta-feira | 14h às 18h
Quinta-feira | 14h às 18h
Sexta-feira | 14h às 20h

**Comment by estelavilasboas** [comment]
> Favor @/mariagelain @/CleissonVieira @/estelavilasboas @/vini2reis conferir a página horários da planilha e informar aqui nos comentários quais seriam seus respectivos horários disponíveis.



Dia | Horário
-- | --
Terça-feira | 7:30h às 12h  
Quarta-feira | 7:30h às 12h  
Quinta-feira | 7:30h às 12h e 13h às 15:30h
Sexta-feira | 8h às 12h

**Comment by ricardopatrik** [comment]
Segunda, Terça e Quinta-Feira: **08:00 - 12:00**
Sexta-Feira: **08:00 - 12:00** / **13:30 - 17:30**

**Comment by GessicaZanon** [comment]
**Segunda:** 8h às 9h30 / 18h30 às 22h
**Terça:** 8h às 9h30 / 13h30 às 17h
**Quarta:** 8h às 9h30 / 18h30 às 22h
**Quinta:** 13h30 às 17h
**Sexta:** 8h às 9h30

**Comment by thaliafriedrich** [comment]
Segunda-feira: 8h às 12h
Terça-feira: 8h às 12h
Quarta-feira: 13:30h às 17:30h
Quinta-feira: 8h às 12h
Sexta-feira: 8h às 12h

**Comment by luizatonial** [comment]
Dia | Horário
-- | --
Segunda-feira | 18:30 às 22:00
Terça-feira | 18:30 às 22:00
Quinta-feira | 18:30 às 22:00
Sexta-feira | 13:30 às 22:00

**Comment by MaNegrao** [comment]
> Favor @mariagelain @CleissonVieira @estelavilasboas @vini2reis conferir a página horários da planilha e informar aqui nos comentários quais seriam seus respectivos horários disponíveis.

Eu não fui mencionado, mas acho que tenho que atualizar os horários também hahah

Os meus horários são os seguintes:

Dia | Horário
-- | --
Terça-feira | 8h às 12h  
Quarta-feira | 8h às 12h
Quinta-feira | 8h às 12h e 13h às 17h 
Sexta-feira | 8h às 12h

**Comment by mariagelain** [comment]
Meus horários de disponibilidade:

Dia | Horário
-- | --
Segunda-feira | 13:30 às 17:30
Terça-feira | 09:30 às 11:00 e 13:30 às 17:30
Quarta-feira | 09:30 às 11:00 e 13:30 às 17:30
Quinta-feira | 13:30 às 17:30
Sexta-feira | 13:30 às 17:30

**Comment by luizdameda** [comment]
Nós do campus Passo Fundo estamos tendo aula desde agosto, portanto vou mandar aqui a grade de disponibilidade baseada até o fim desse semestre (15/11). No início do próximo semestre atualizo.

Segunda-feira: 9h - 17h (quinzenalmente)
Terça-feira: 13:30h - 17h
Quarta-feira: 18h - 23h
Quinta-feira: 20h - 23h
Sexta-feira: 18h - 23h
Sábado e Domingo: tarde e noite (flexibilidade conforme o calendário de provas)

**Comment by morgana-mo** [comment]
Segunda-feira: 13:30 - 17:30
Terça-feira: 13:30h - 17:30
Quarta-feira: 13:30 - 17:30
Quinta-feira: 13:30-17:30
Sexta-feira:13:30-17:30
Sábado e Domingo: tarde e noite (flexibilidade conforme o calendário de provas)
Em 25 de novembro vai haver o encerramento de alguns CCRs que iniciaram antes (quarta e quinta-feira) provavelmente passe a exercer meus horários no turno da noite nos referidos dias.

**Comment by TaynaraCh** [comment]
Segunda e Quarta-Feira 08:00 - 12:00
Sexta-Feira o dia inteiro 
Todas as noites

**Comment by Claudineia-VR** [comment]
Dia | Horário
-- | --
Segunda-feira | 15h às 18h
Terça-feira | 17:30h às 19:30h
Quarta-feira | 15h às 18h
Quinta-feira | 15h às 18h
Sexta-feira | 15h às 20h

**Comment by brendaellen** [comment]
Meus horários noturnos só estarão disponíveis a partir do dia 16/10, pois estou tendo aulas na auto escola. 

Segunda-feira: 09:00h às 12:00h e 18:30h às 22:00h
Terça-feira: 18:00h às 22:00h 
Quarta-feira: 18:00h às 22:00h
Sexta-feira: 07:00h às 10:00h e 18:30h às 22:00h
Domingo: Tarde e Noite.

**Comment by MilenaPaz2020** [comment]
Todas as manhãs: 7:30 às 11:30.

**Comment by amandasegattob** [comment]
Segunda-feira: 18h - 22h
Terça-feira: 18h - 22h
Quinta-feira: 8h - 14h e 19h - 22h
Sexta-feira: 14h - 22h
Sábado e Domingo: tarde e noite (flexibilidade conforme o calendário de provas)

**Comment by oraphaBorges** [comment]
| Dia | Horários|
|---|----|
|Segunda| 8h às 17h |
|Terça| 8h à 12h |
|Quarta| 8h às 17h |
|Quinta| 18h às 21h |
|Sexta| 8h às 12h|

**Comment by anacarolinamorigi** [comment]
Como o @luizdameda comentou antes, esses seriam os horários disponíveis para esse semestre, que vai até dia 15/11. Logo, quando tiver acesso ao próximo, atualizo estes horários.

Segunda-feira: 9h às 17h (quinzenalmente)
Terça-feira: 19h às 23h
Quarta-feira: sem disponibilidade 
Quinta-feira: 14h às 19h
Sexta-feira: 19h às 23h 
Sábado e Domingo: tarde e noite (dependendo do calendário de provas).

**Comment by VIF-Franca** [comment]
@anacarolinamorigi @juliagaio @luizdameda @luizatonial @MilenaPaz2020 @morgana-mo @rafaguilman @oraphaBorges @TaynaraCh @thaliafriedrich 

Faltam vocês para preencherem a planilha de disponibilidade.

**Comment by luizdameda** [comment]
> @anacarolinamorigi @juliagaio @luizdameda @luizatonial @MilenaPaz2020 @morgana-mo @rafaguilman @oraphaBorges @TaynaraCh @thaliafriedrich 
> 
> 
> 
> Faltam vocês para preencherem a planilha de disponibilidade.

Respondi logo acima, tem mais algum lugar que devo preencher?

**Comment by luizdameda** [comment]
> @anacarolinamorigi @juliagaio @luizdameda @luizatonial @MilenaPaz2020 @morgana-mo @rafaguilman @oraphaBorges @TaynaraCh @thaliafriedrich 
> 
> 
> 
> Faltam vocês para preencherem a planilha de disponibilidade.

Respondido! Tinha comentado aqui, logo acima, com as minhas disponibilidades, mas tinha esquecido de preencher a tabela 😅

**Comment by anacarolinamorigi** [comment]
> @anacarolinamorigi @juliagaio @luizdameda @luizatonial @MilenaPaz2020 @morgana-mo @rafaguilman @oraphaBorges @TaynaraCh @thaliafriedrich
> 
> Faltam vocês para preencherem a planilha de disponibilidade.

Preenchido!

**Comment by MilenaPaz2020** [comment]
> @anacarolinamorigi @juliagaio @luizdameda @luizatonial @MilenaPaz2020 @morgana-mo @rafaguilman @oraphaBorges @TaynaraCh @thaliafriedrich
> 
> Faltam vocês para preencherem a planilha de disponibilidade.

Feito!

**Comment by rafaguilman** [comment]
> @anacarolinamorigi @juliagaio @luizdameda @luizatonial @MilenaPaz2020 @morgana-mo @rafaguilman @oraphaBorges @TaynaraCh @thaliafriedrich
> 
> Faltam vocês para preencherem a planilha de disponibilidade.

Segunda Feira 07:30 as 80:30 - 13:15 as 16:00 20:00 as 22:00
Terça-feira  07:30 as 08:30-   16:00 as 18:00
Quarta-Feira  16:00 as 18:00
Quinta-Feira 16:00 as 18:00
Sexta-Feira 16:00 as 18:00

**Comment by alessandrapedrotti** [comment]
@juliagaio e @vini2reis favor preencher a planilha de disponibilidade.

**Comment by vini2reis** [comment]
Segunda-feira: 14h às 18h
Terça-feira: 14h às 18h
Quarta-feira: 14:00h às 18:00h
Quinta-feira: 14h às 18h
Sexta-feira: 14h às 18h

**Comment by VIF-Franca** [comment]
Creio que podemos fechar a issue.
