### ISSUE TITLE
Elaboração de documento de prazos

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#184]
Conforme o debatido em reunião, os líderes de equipe devem elaborar um texto (ou tabela) sobre os prazos de solicitação e entrega de produtos.
Esses textos devem considerar os prazos em dias úteis, assim como a complexidade de cada tarefa envolvida nas produções. 

Essa tarefa é necessária para que assim a @practice-uffs/ger-auxilio possa respaldar a aceitação ou negação de uma demanda. E essas informações também integrarão as páginas de serviços do site, futuramente.

Sei que as equipes já possuem documentos com a descrição dos produtos e fluxogramas, portanto serão necessárias apenas adaptações desses textos. Os líderes, se quiserem, podem comentar aqui os links dos referidos arquivos, para debatermos o que ainda precisa ser adicionado.

@practice-uffs/lideres

**Comment by MaNegrao** [comment]
Eu fiz uma primeira versão dos prazos dos produtos do midia resumidos pela complexidade, seguindo a nossa definição de produtos das issues #42 e #44. 

As gravações em estúdio eu estimo que o agendamento deve ser feito com no mínimo 8 dias úteis de antecedência.

![Tabela de Produtos de Audio-1](https://user-images.githubusercontent.com/31110971/96151458-ce822c00-0ee1-11eb-81a4-268f4b5db499.jpg)
![Tabela de Produtos de Transmissão-1](https://user-images.githubusercontent.com/31110971/96151468-cfb35900-0ee1-11eb-8491-cd5a32627d3a.jpg)
![Tabela de Produtos de Video-1](https://user-images.githubusercontent.com/31110971/96151476-d04bef80-0ee1-11eb-90f9-1edff2dec3f8.jpg)

**Comment by alessandrapedrotti** [comment]
@estelavilasboas @mariagelain podemos elaborar uma tabela similar a feita pelo Matheus para os serviços da con-conteúdo.

@Claudineia-VR você ficará responsável pela sintetização dessas informações em um único texto.

**Comment by mariagelain** [comment]
Os prazos dos produtos produzidos pela Con-Conteúdo estão na última página do documento da issue #173.

**Comment by Claudineia-VR** [comment]
Testando

**Comment by alessandrapedrotti** [comment]
> Testando

Funcionou?

**Comment by Claudineia-VR** [comment]
@practice-uffs/dev  por favor, mandem as informações sobre os prazos de solicitações e entregas de produtos que consideram pertinentes.

**Comment by Dovyski** [comment]
@Claudineia-VR no momento o único serviço que a equipe de dev disponibilizará externamente é a criação de aplicativos para dispositivos móveis (app), com prazo de produção de 3 a 6 meses.

**Comment by alessandrapedrotti** [comment]
Os documentos em elaboração podem ser encontrados [nesta pasta](https://drive.google.com/drive/u/0/folders/19QHroCIhwDCuKZGd0otcI6PI5X0Dvnxn).

**Comment by alessandrapedrotti** [comment]
Revisão feita. Fiz apenas pequenas alterações em elementos textuais.

No geral, achei um trabalho muito bem feito e sugiro a utilização da tabela nº 2, pois considero mais fácil de localizar as informações nela.

Solicito que a tabela nº 2 seja convertida em PDF. 

Salvo isso, já podemos pensar em como adicionar o texto produzido ao site.

**Comment by Claudineia-VR** [comment]
A tabela número 2 foi convertida em PDF.

**Comment by alessandrapedrotti** [comment]
Adicionar, a tabela nº 2 uma coluna com o título "prazo de avaliação do pedido" e nessa coluna colocar as seguintes informações:

- [ ] No que compete às transmissões ao vivo, colocar os prazos que estão na tabela 1;
- [ ] Para os produtos de áudio, colocar 3 dias úteis;
- [ ] Para os produtos de vídeo, colocar 5 dias úteis (e uma nota explicando que, a depender da complexidade do projeto, tanto o período de avaliação quanto o de produção pode aumentar);
- [ ] Para os produtos de texto, colocar 5 dias úteis;
- [ ] Para os produtos de imagem, colocar 5 dias úteis;
- [ ] No dev, colocar que cada demanda será avaliada individualmente com o solicitante.

**Comment by alessandrapedrotti** [comment]
Os elementos solicitados para essa tarefa foram concluídos, favor disponibilizar na pasta de saída a versão atualizada da tabela 2 em PDF, assim como o texto escrito, com o nome de "texto para site".

Criar na pasta [Tabelas de produtos](https://drive.google.com/drive/u/0/folders/1O9qdB8hdM0iutFjaH2g7IIDzJv9L87OJ) (contida na pasta materiais), uma nova pasta com o título "tabela de prazos" e mover uma cópia da tabela elaborada para lá, para acesso rápido (em versão editável e PDF).

Após esses passos, essa tarefa será fechada e será aberta uma nova issue no repositório website-programa para a inserção dessas informações no site.
