### ISSUE TITLE
Edição de vídeo Letras CH (PTA E LPT): 7º vídeo - Coerencia. Profª Ani.

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#186]
Essa issue em questão refere-se ao vídeo 7 - Coerência. Professora Ani.  **O vídeo está na pasta [deste link](https://drive.google.com/drive/folders/1JbLRzEjTkT5aHQkJJq3qfnSDtX8uQLRx)**

> Essa série de issues são relacionadas a issue #151, cada uma delas representa um vídeo a ser editado. Todas as edições seguem o mesmo padrão (**[que pode ser visto aqui](https://drive.google.com/file/d/1QvqT4eQkqFvJXLbCJsWAII3UcSEzwbx9/view?usp=sharing)**) e são feitas no software [ShotCut](https://shotcut.org/).

> Os materiais do programa podem ser encontrados na [pasta de materiais](https://drive.google.com/drive/u/3/folders/1uSbwV0EYRQywqVKjY95EsDSd-kT9UmqS) e as ferramentas no [guia do programa](https://guia.practice.uffs.cc)
As etapas de edição desses vídeos são:

- **Primeira etapa:**

- [x] Realizar edição inicial do vídeo seguindo orientações do respectivo professor e agregar slide enviado (arquivos na pasta). Os slides devem ser baixados em formato de imagem, para serem mais facilmente utilizados na edição.
- [x] Caso tenha imagens que precisem de áudio descrição deve-se gravar e agregar ao vídeo.
- [x] Criar uma pasta no link dessa issue chamada _Em progresso_ e armazenar todo conteúdo e o andamento da edição nela.
- [x] Criação da pagina dos créditos seguindo o [template](https://drive.google.com/drive/u/0/folders/1qIai8gugPK9OydUx8P5lcpK4D8vA6n1E) feito pela equipe de conteúdo.
- [x] Inserção das vinhetas e da pagina de créditos com a seguinte ordem:  
[Vinheta de Letras](https://drive.google.com/file/d/1Eiq7A1TRdhYRLFUdVpFPX-CSWwF6M8v_/view?usp=sharing) - Vinheta PRACTICE - Vídeo - Vinheta Letras - Créditos - Vinheta PRACTICE

- **Segunda etapa:**

Com a edição inicial concluída, deve ser feita a legenda do vídeo.

- [x] Upar vídeo editado no YouTube para criação da legenda automática (Para saber como fazer isso, veja o vídeo [deste link](https://drive.google.com/file/d/1Xr-v-E0nF7YHpjiVx94QOUlUhKh9Qu8C/view?usp=sharing))
- [x] Corrigir as palavras erradas da legenda automática gerada e baixar o arquivo .srt (seguindo o vídeo do tópico anterior)
- [x] Com a legenda finalizada, disponibilizar o arquivo e marcar a equipe de conteúdo para revisão textual.
- [x] Ao final da revisão as legendas devem ser adicionadas ao vídeo através do software Format Factory (Veja como fazer [aqui](https://drive.google.com/file/d/1X4H8jWbZ9jNN8j6kFaZ1u9N-JECNTdga/view?usp=sharing))
- [x] Com o vídeo finalizado e com as legendas, enviar ao professor para revisão e apontar possíveis ajustes.
- [ ] Caso tenha, realizar os ajustes solicitados.

**Comment by alessandrapedrotti** [comment]
Responsável: @brendaellen 
É necessário fazer a transposição dos slides disponibilizados pelo(a) professor(a) referente a esse vídeo. 
Para fazer a transposição você deve:

- [ ] Localizar o template elaborado para o curso [nesta pasta](https://drive.google.com/drive/u/0/folders/13sFE1Q_t-8nkXAKBbKpj0oKvc64vFM8L);
Os templates utilizados serão os de capa, créditos 02 e 05; Sendo o 02 para trechos com título e texto e o 05 para trechos com imagem;
- [ ] **Copiar** o template e **transferi-lo** para a pasta dessa tarefa (edição) em questão (que está posta na descrição dessa tarefa);
- [ ] Adicionar títulos, textos, imagens e referências em sua totalidade;
- [ ] Conferir se margens, fontes, tamanhos das fontes e parágrafos estão padronizados em toda a apresentação;
- [ ] Conferir erros de digitação.

**Comment by alessandrapedrotti** [comment]
Responsável: @isabelirk 
Para a revisão textual das legendas:

- [ ] Assistir ao vídeo concomitantemente a leitura da transcrição com a minutagem;
- [ ] Fazer alterações de pontuação e ortografia;
- [ ] Mudar palavras caso elas não estiverem na fala do prof (as vezes a legenda automática coloca umas palavras nada a ver com o que está sendo dito);
- [ ] Rever o vídeo e reler a transcrição da legenda, para ter certeza que nenhum trecho ficou errado.

Observações:
Não há necessidade de deixar no texto da legenda vícios de linguagem, como "tipo", "né" ou similares.

**Comment by morgana-mo** [comment]
Adicionei a pasta em progresso o vídeo com a edição prévia e o arquivo para correção das legendas

**Comment by morgana-mo** [comment]
@thaliafriedrich 
Adicionei a pasta em progresso o vídeo com a edição prévia e o arquivo para correção das legendas

**Comment by thaliafriedrich** [comment]
> @thaliafriedrich
> Adicionei a pasta em progresso o vídeo com a edição prévia e o arquivo para correção das legendas

Revisão concluída.

**Comment by morgana-mo** [comment]
@MaNegrao a primeira versão do vídeo já se encontra na pasta do drive para envio ao cliente

**Comment by morgana-mo** [comment]
@brendaellen creio que os apontamentos relativos aos slides sejam por conta das recomendações da professora que não foram atendidas, eles se encontram no arquivo deste link [https://drive.google.com/drive/folders/1JbLRzEjTkT5aHQkJJq3qfnSDtX8uQLRx](url) aqui

**Comment by morgana-mo** [comment]
@thaliafriedrich  foram feitos alguns apontamentos quanto as legendas:
Ajuste 1-Em todos os pontos da legenda e dos slides em que aparece a
palavra "Charolles", fazer a correção, pois apareceu escrito de diversos
modos. A professora se confundiu nos slides.

Ajuste 2 - Repassar as legendas, arrumando a falta de espaço entre
palavras, palavras e pontos e, ainda, maiúsculas e minúsculas.
Se puder fazer a revisão novamente fico grata,algumas palavras Charolles eu já corrigi!

**Comment by thaliafriedrich** [comment]
@morgana-mo, revisei novamente e fiz as correções. Vi que no vídeo falta espaço em algumas partes, mas no texto não estava faltando em todos, então talvez seja por causa da minutagem. Se preferir, posso fazer o texto da legenda sem a minutagem para melhorar isso.

**Comment by morgana-mo** [comment]
> @morgana-mo, revisei novamente e fiz as correções. Vi que no vídeo falta espaço em algumas partes, mas no texto não estava faltando em todos, então talvez seja por causa da minutagem. Se preferir, posso fazer o texto da legenda sem a minutagem para melhorar isso.

Creio que seja a melhor opção fazer sem a minutagem

**Comment by thaliafriedrich** [comment]
@morgana-mo, a versão das legendas sem a minutagem está pronta.

**Comment by morgana-mo** [comment]
@MaNegrao  adicionei a pasta de saída o arquivo com as correções da legenda. Mas fiquei em dúvida quanto ao comentário da Prof Morgana se a grafia correta é Charolles ou Charroles. No vídeo upado agora está Charolles

**Comment by morgana-mo** [comment]
@MaNegrao  upei o vídeo na pasta de saída com a grafia correta da palavra Charolles,pode enviar para revisão do cliente e fico no aguardo das considerações para correção

**Comment by brendaellen** [comment]
> @brendaellen creio que os apontamentos relativos aos slides sejam por conta das recomendações da professora que não foram atendidas, eles se encontram no arquivo deste link [aqui](https://drive.google.com/drive/folders/1JbLRzEjTkT5aHQkJJq3qfnSDtX8uQLRx)

Conferi as recomendações em todas as issues, e fiz as alterações solicitadas.

**Comment by MaNegrao** [comment]
@brendaellen @thaliafriedrich e @morgana-mo a professora retornou os erros que devem ser corrigidos, tanto nas legendas, como slide e vídeo. O arquivo está na pasta do link https://drive.google.com/drive/folders/1SaN-6I3FfzjDTDzcD9cN3Txj68aoOdec

**Comment by brendaellen** [comment]
> @brendaellen @thaliafriedrich e @morgana-mo a professora retornou os erros que devem ser corrigidos, tanto nas legendas, como slide e vídeo. O arquivo está na pasta do link https://drive.google.com/drive/folders/1SaN-6I3FfzjDTDzcD9cN3Txj68aoOdec

Fiz as alterações.

**Comment by thaliafriedrich** [comment]
> @brendaellen @thaliafriedrich e @morgana-mo a professora retornou os erros que devem ser corrigidos, tanto nas legendas, como slide e vídeo. O arquivo está na pasta do link https://drive.google.com/drive/folders/1SaN-6I3FfzjDTDzcD9cN3Txj68aoOdec

Fiz as correções solicitadas na legenda. É o arquivo "Legenda sem minutagem", na pasta de entrada.

**Comment by morgana-mo** [comment]
@MaNegrao coloquei o arquivo para renderização na pasta do link [https://drive.google.com/drive/folders/1HxTUXeKjvyTSjOjlke-1a0HkKgEHWjsz

**Comment by MaNegrao** [comment]
vídeo finalizado!
