### ISSUE TITLE
Edição de vídeo Letras CH (PTA E LPT): 3º vídeo - Norma Culta. Profª Claudia

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#188]
Essa issue em questão refere-se ao vídeo 3 - Norma Culta, Profa Claudia.  **O vídeo está [nessa pasta](https://drive.google.com/drive/folders/1cqC86mSL5gmc74D3fxcXPrv-dK1oD7iy?usp=sharing)**

> Essa série de issues são relacionadas a issue #151, cada uma delas representa um vídeo a ser editado. Todas as edições seguem o mesmo padrão (**[que pode ser visto aqui](https://drive.google.com/file/d/1QvqT4eQkqFvJXLbCJsWAII3UcSEzwbx9/view?usp=sharing)**) e são feitas no software [ShotCut](https://shotcut.org/).

> Os materiais do programa podem ser encontrados na [pasta de materiais](https://drive.google.com/drive/u/3/folders/1uSbwV0EYRQywqVKjY95EsDSd-kT9UmqS) e as ferramentas no [guia do programa](https://guia.practice.uffs.cc)
As etapas de edição desses vídeos são:

- **Primeira etapa:**

- [x] Realizar edição inicial do vídeo seguindo orientações do respectivo professor e agregar slide enviado (arquivos na pasta). Os slides devem ser baixados em formato de imagem, para serem mais facilmente utilizados na edição.
- [x] Caso tenha imagens que precisem de áudio descrição deve-se gravar e agregar ao vídeo.
- [x] Criar uma pasta no link dessa issue chamada _Em progresso_ e armazenar todo conteúdo e o andamento da edição nela.
- [x] Criação da pagina dos créditos seguindo o [template](https://drive.google.com/drive/u/0/folders/1qIai8gugPK9OydUx8P5lcpK4D8vA6n1E) feito pela equipe de conteúdo.
- [x] Inserção das vinhetas e da pagina de créditos com a seguinte ordem:  
[Vinheta de Letras](https://drive.google.com/file/d/1Eiq7A1TRdhYRLFUdVpFPX-CSWwF6M8v_/view?usp=sharing) - Vinheta PRACTICE - Vídeo - Vinheta Letras - Créditos - Vinheta PRACTICE

- **Segunda etapa:**

Com a edição inicial concluída, deve ser feita a legenda do vídeo.

- [x] Upar vídeo editado no YouTube para criação da legenda automática (Para saber como fazer isso, veja o vídeo [deste link](https://drive.google.com/file/d/1Xr-v-E0nF7YHpjiVx94QOUlUhKh9Qu8C/view?usp=sharing))
- [x] Corrigir as palavras erradas da legenda automática gerada e baixar o arquivo .srt (seguindo o vídeo do tópico anterior)
- [x] Com a legenda finalizada, disponibilizar o arquivo e marcar a equipe de conteúdo para revisão textual.
- [x] Ao final da revisão as legendas devem ser adicionadas ao vídeo através do software Format Factory (Veja como fazer [aqui](https://drive.google.com/file/d/1X4H8jWbZ9jNN8j6kFaZ1u9N-JECNTdga/view?usp=sharing))
- [x] Com o vídeo finalizado e com as legendas, enviar ao professor para revisão e apontar possíveis ajustes.
- [x] Caso tenha, realizar os ajustes solicitados.

**Comment by robisonjose** [comment]
Onde eu acompanho o progresso dos slides que serão utilizados nos vídeos?

**Comment by MaNegrao** [comment]
> Onde eu acompanho o progresso dos slides que serão utilizados nos vídeos?

Creio que quando eles estiverem prontos alguém da equipe de conteúdo irá avisar aqui na issue e disponibilizar na pasta. Por ora a gente fica com os sem formatação...

**Comment by robisonjose** [comment]
Certo, outra coisa. Os roteiros devem ser seguidos fielmente ou podem ser alterados (alterações pequenas, nada muito fora do que está nele)?

**Comment by MaNegrao** [comment]
> Certo, outra coisa. Os roteiros devem ser seguidos fielmente ou podem ser alterados (alterações pequenas, nada muito fora do que está nele)?

Eu não sei dizer, creio que a @alessandrapedrotti pode dizer com mais certeza sobre os roteiros.

**Comment by alessandrapedrotti** [comment]
> Certo, outra coisa. Os roteiros devem ser seguidos fielmente ou podem ser alterados (alterações pequenas, nada muito fora do que está nele)?

Você poderia explicar melhor quais seriam essas alterações que você gostaria de fazer?

**Comment by robisonjose** [comment]
Momentos em que o professor aparece, basicamente. Tinha ideia de colocar algumas partes em destaque, como palavras chave, mas isso não tinha no roteiro então pode ser que o professor não ache interessante. Então seria, por exemplo: No roteiro está que o professor e o slide devem aparecer por 5 minutos seguidos, e talvez em um desses minutos ficaria interessante se só o professor aparecesse, ou que fosse feito um foco em alguma parte do texto, coisas desse tipo.

**Comment by alessandrapedrotti** [comment]
> Momentos em que o professor aparece, basicamente. Tinha ideia de colocar algumas partes em destaque, como palavras chave, mas isso não tinha no roteiro então pode ser que o professor não ache interessante. Então seria, por exemplo: No roteiro está que o professor e o slide devem aparecer por 5 minutos seguidos, e talvez em um desses minutos ficaria interessante se só o professor aparecesse, ou que fosse feito um foco em alguma parte do texto, coisas desse tipo.

Você pode fazer essas alterações, desde que tu deixe um comentário ou no próprio roteiro oferecido pelo prof ou em um documento separado na mesma pasta, assim podemos fazer o acompanhamento dessas mudanças. Só lembre de que o conteúdo deve ser 100% acessível, então considere se essas mudanças não vão dificultar leitura, interpretação ou o acompanhamento do vídeo.
Se tu ainda tiver dúvidas, pode fazer um trecho com essas alterações e solicitar que teu líder de equipe ou eu olhemos.

**Comment by robisonjose** [comment]
A transcrição do vídeo e o link para a primeira versão dele está [nessa pasta](https://drive.google.com/drive/folders/1avyPA_egosntseYmI-5JVRrxbvt2ql89). @practice-uffs/con-conteudo. Vou fazer a segunda versão quando os slides normatizados forem disponibilizados.

**Comment by alessandrapedrotti** [comment]
Responsável: @GessicaZanon 
É necessário fazer a transposição dos slides disponibilizados pelo(a) professor(a) referente a esse vídeo. 
Para fazer a transposição você deve:

- [ ] Localizar o template elaborado para o curso [nesta pasta](https://drive.google.com/drive/u/0/folders/13sFE1Q_t-8nkXAKBbKpj0oKvc64vFM8L);
Os templates utilizados serão os de capa, créditos 02 e 05; Sendo o 02 para trechos com título e texto e o 05 para trechos com imagem;
- [ ] **Copiar** o template e **transferi-lo** para a pasta dessa tarefa (edição) em questão (que está posta na descrição dessa tarefa);
- [ ] Adicionar títulos, textos, imagens e referências em sua totalidade;
- [ ] Conferir se margens, fontes, tamanhos das fontes e parágrafos estão padronizados em toda a apresentação;
- [ ] Conferir erros de digitação.

**Comment by alessandrapedrotti** [comment]
Responsável: @thaliafriedrich 
Para a revisão textual das legendas:

- [ ] Assistir ao vídeo concomitantemente a leitura da transcrição com a minutagem;
- [ ] Fazer alterações de pontuação e ortografia;
- [ ] Mudar palavras caso elas não estiverem na fala do prof (as vezes a legenda automática coloca umas palavras nada a ver com o que está sendo dito);
- [ ] Rever o vídeo e reler a transcrição da legenda, para ter certeza que nenhum trecho ficou errado.

Observações:
Não há necessidade de deixar no texto da legenda vícios de linguagem, como "tipo", "né" ou similares.

**Comment by GessicaZanon** [comment]
A transposição dos slides está finalizada e pronta para uso. Está disponível [nessa pasta](https://drive.google.com/drive/folders/1avyPA_egosntseYmI-5JVRrxbvt2ql89)

**Comment by MaNegrao** [comment]
@luizdameda Eu tava revisando o vídeo e percebi que câmera da professora na mascara redonda ficou muito pra direita. Nessa ultima edição que você vai fazer com os slides finais tu pode ajustar a mascara pra que a prof fique mais centralizada, por favor?

**Comment by robisonjose** [comment]
@GessicaZanon Eu preciso que o terceiro slide original seja feito da mesma maneira. Vi que tu separou os dois, e provavelmente eu usarei eles separados também, porém ela comenta deles juntos, então preciso de um igual do slide original.

**Comment by GessicaZanon** [comment]
> @GessicaZanon Eu preciso que o terceiro slide original seja feito da mesma maneira. Vi que tu separou os dois, e provavelmente eu usarei eles separados também, porém ela comenta deles juntos, então preciso de um igual do slide original.

@robisonjose está feito! Transcrevi o terceiro slide original exatamente do mesmo jeito, como pedido. Mantive em dois slides separados também, pois pelo que entendi você usará em algum momento desse modo.

**Comment by MaNegrao** [comment]
vídeo finalizado!
