### ISSUE TITLE
Edição de vídeo Letras CH (PTA E LPT): 5º vídeo - Gêneros Textuais. Profª Aline

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#190]
Essa issue em questão refere-se ao vídeo 5 - Gêneros Textuais. Prof Aline.  **O vídeo está na [pasta do drive](https://drive.google.com/drive/folders/1P6E4i87z4-l-4dcyLAH4JyJ3wOon7nzN?usp=sharing)**

> Essa série de issues são relacionadas a issue #151, cada uma delas representa um vídeo a ser editado. Todas as edições seguem o mesmo padrão (**[que pode ser visto aqui](https://drive.google.com/file/d/1QvqT4eQkqFvJXLbCJsWAII3UcSEzwbx9/view?usp=sharing)**) e são feitas no software [ShotCut](https://shotcut.org/).

> Os materiais do programa podem ser encontrados na [pasta de materiais](https://drive.google.com/drive/u/3/folders/1uSbwV0EYRQywqVKjY95EsDSd-kT9UmqS) e as ferramentas no [guia do programa](https://guia.practice.uffs.cc)
As etapas de edição desses vídeos são:

- **Primeira etapa:**

- [x] Realizar edição inicial do vídeo seguindo orientações do respectivo professor e agregar slide enviado (arquivos na pasta). Os slides devem ser baixados em formato de imagem, para serem mais facilmente utilizados na edição.
- [x] Caso tenha imagens que precisem de áudio descrição deve-se gravar e agregar ao vídeo.
- [x] Criar uma pasta no link dessa issue chamada _Em progresso_ e armazenar todo conteúdo e o andamento da edição nela.
- [x] Criação da pagina dos créditos seguindo o [template](https://drive.google.com/drive/u/0/folders/1qIai8gugPK9OydUx8P5lcpK4D8vA6n1E) feito pela equipe de conteúdo.
- [x] Inserção das vinhetas e da pagina de créditos com a seguinte ordem:  
[Vinheta de Letras](https://drive.google.com/file/d/1Eiq7A1TRdhYRLFUdVpFPX-CSWwF6M8v_/view?usp=sharing) - Vinheta PRACTICE - Vídeo - Vinheta Letras - Créditos - Vinheta PRACTICE

- **Segunda etapa:**

Com a edição inicial concluída, deve ser feita a legenda do vídeo.

- [x] Upar vídeo editado no YouTube para criação da legenda automática (Para saber como fazer isso, veja o vídeo [deste link](https://drive.google.com/file/d/1Xr-v-E0nF7YHpjiVx94QOUlUhKh9Qu8C/view?usp=sharing))
- [x] Corrigir as palavras erradas da legenda automática gerada e baixar o arquivo .srt (seguindo o vídeo do tópico anterior)
- [x] Com a legenda finalizada, disponibilizar o arquivo e marcar a equipe de conteúdo para revisão textual.
- [x] Ao final da revisão as legendas devem ser adicionadas ao vídeo através do software Format Factory (Veja como fazer [aqui](https://drive.google.com/file/d/1X4H8jWbZ9jNN8j6kFaZ1u9N-JECNTdga/view?usp=sharing))
- [x] Com o vídeo finalizado e com as legendas, enviar ao professor para revisão e apontar possíveis ajustes.
- [x] Caso tenha, realizar os ajustes solicitados.

**Comment by alessandrapedrotti** [comment]
Responsável: @GessicaZanon 
É necessário fazer a transposição dos slides disponibilizados pelo(a) professor(a) referente a esse vídeo. 
Para fazer a transposição você deve:

- [ ] Localizar o template elaborado para o curso [nesta pasta](https://drive.google.com/drive/u/0/folders/13sFE1Q_t-8nkXAKBbKpj0oKvc64vFM8L);
Os templates utilizados serão os de capa, créditos 02 e 05; Sendo o 02 para trechos com título e texto e o 05 para trechos com imagem;
- [ ] **Copiar** o template e **transferi-lo** para a pasta dessa tarefa (edição) em questão (que está posta na descrição dessa tarefa);
- [ ] Adicionar títulos, textos, imagens e referências em sua totalidade;
- [ ] Conferir se margens, fontes, tamanhos das fontes e parágrafos estão padronizados em toda a apresentação;
- [ ] Conferir erros de digitação.

**Comment by alessandrapedrotti** [comment]
Responsável: @isabelirk 
Para a revisão textual das legendas:

- [ ] Assistir ao vídeo concomitantemente a leitura da transcrição com a minutagem;
- [ ] Fazer alterações de pontuação e ortografia;
- [ ] Mudar palavras caso elas não estiverem na fala do prof (as vezes a legenda automática coloca umas palavras nada a ver com o que está sendo dito);
- [ ] Rever o vídeo e reler a transcrição da legenda, para ter certeza que nenhum trecho ficou errado.

Observações:
Não há necessidade de deixar no texto da legenda vícios de linguagem, como "tipo", "né" ou similares.

**Comment by MaNegrao** [comment]
@practice-uffs/con-midia O video foi enviado para a professora, então já pode entrar na ilha de edição, quem não estiver responsável por algum dos mais prioritários pode assumir este.

**Comment by robisonjose** [comment]
A transcrição do vídeo e o link para a primeira versão dele está [nessa pasta](https://drive.google.com/drive/folders/1-3ogCxV88ACGnOJNY560Mr1ANE1WjfsW) @practice-uffs/con-conteudo.

**Comment by thaliafriedrich** [comment]
> A transcrição do vídeo e o link para a primeira versão dele está [nessa pasta](https://drive.google.com/drive/folders/1-3ogCxV88ACGnOJNY560Mr1ANE1WjfsW) @practice-uffs/con-conteudo.

Revisão da legenda concluída.

**Comment by GessicaZanon** [comment]
A transposição dos slides foi finalizada e está pronta para uso. Está disponível [nessa pasta](https://drive.google.com/drive/folders/1-3ogCxV88ACGnOJNY560Mr1ANE1WjfsW)

**Comment by robisonjose** [comment]
@practice-uffs/con-conteudo É necessário deixar o primeiro e o último slides normalizados em todas as issues. Em alguns dos primeiros slides que tem parte l e ll os títulos estão escritos de maneiras diferentes; No último slide alguns estão escritos professor e em outros professora, em alguns está o nome inteiro do docente e em outros não, em alguns está com o título acadêmico e outros não, etc..

**Comment by alessandrapedrotti** [comment]
> @practice-uffs/con-conteudo É necessário deixar o primeiro e o último slides normalizados em todas as issues. Em alguns dos primeiros slides que tem parte l e ll os títulos estão escritos de maneiras diferentes; No último slide alguns estão escritos professor e em outros professora, em alguns está o nome inteiro do docente e em outros não, em alguns está com o título acadêmico e outros não, etc.. Edit: O Caps Lock também é algo não normalizado.

Esses são todos aspectos que a @GessicaZanon, que é a responsável pela tarefa, pode resolver.

**Comment by GessicaZanon** [comment]
> @practice-uffs/con-conteudo É necessário deixar o primeiro e o último slides normalizados em todas as issues. Em alguns dos primeiros slides que tem parte l e ll os títulos estão escritos de maneiras diferentes; No último slide alguns estão escritos professor e em outros professora, em alguns está o nome inteiro do docente e em outros não, em alguns está com o título acadêmico e outros não, etc.. Edit: O Caps Lock também é algo não normalizado.

Acredito que agora está tudo ok nos meus slides @robisonjose . O nome dos professores eu fui informando conforme o solicitado. Nos da Prof. Cláudia por exemplo, ela inseriu nos slides: "Profa. Dra..." então mantive desse jeito em todos os dela. Qualquer coisa estou a disposição. Mas irei rever todos novamente.

**Comment by MaNegrao** [comment]
vídeo finalizado!
