### ISSUE TITLE
Edição de vídeo Letras CH (PTA E LPT): 11º vídeo - Resenha parte 1. Profª Morgana

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#195]
Essa issue em questão refere-se ao vídeo 11 - Resenha parte 1. Profª Morgana.  **O vídeo está na pasta [deste link](https://drive.google.com/drive/folders/1DsDgO2AVZ-fSHkcylvC0czA4IYYtZIiM?usp=sharing)**

> Essa série de issues são relacionadas a issue #151, cada uma delas representa um vídeo a ser editado. Todas as edições seguem o mesmo padrão (**[que pode ser visto aqui](https://drive.google.com/file/d/1QvqT4eQkqFvJXLbCJsWAII3UcSEzwbx9/view?usp=sharing)**) e são feitas no software [ShotCut](https://shotcut.org/).

> Os materiais do programa podem ser encontrados na [pasta de materiais](https://drive.google.com/drive/u/3/folders/1uSbwV0EYRQywqVKjY95EsDSd-kT9UmqS) e as ferramentas no [guia do programa](https://guia.practice.uffs.cc)
As etapas de edição desses vídeos são:

- **Primeira etapa:**

- [x] Realizar edição inicial do vídeo seguindo orientações do respectivo professor e agregar slide enviado (arquivos na pasta). Os slides devem ser baixados em formato de imagem, para serem mais facilmente utilizados na edição.
- [x] Caso tenha imagens que precisem de áudio descrição deve-se gravar e agregar ao vídeo.
- [x] Criar uma pasta no link dessa issue chamada _Em progresso_ e armazenar todo conteúdo e o andamento da edição nela.
- [x] Criação da pagina dos créditos seguindo o [template](https://drive.google.com/drive/u/0/folders/1qIai8gugPK9OydUx8P5lcpK4D8vA6n1E) feito pela equipe de conteúdo.
- [x] Inserção das vinhetas e da pagina de créditos com a seguinte ordem:  
[Vinheta de Letras](https://drive.google.com/file/d/1Eiq7A1TRdhYRLFUdVpFPX-CSWwF6M8v_/view?usp=sharing) - Vinheta PRACTICE - Vídeo - Vinheta Letras - Créditos - Vinheta PRACTICE

- **Segunda etapa:**

Com a edição inicial concluída, deve ser feita a legenda do vídeo.

- [x] Upar vídeo editado no YouTube para criação da legenda automática (Para saber como fazer isso, veja o vídeo [deste link](https://drive.google.com/file/d/1Xr-v-E0nF7YHpjiVx94QOUlUhKh9Qu8C/view?usp=sharing))
- [x] Corrigir as palavras erradas da legenda automática gerada e baixar o arquivo .srt (seguindo o vídeo do tópico anterior)
- [x] Com a legenda finalizada, disponibilizar o arquivo e marcar a equipe de conteúdo para revisão textual.
- [x] Ao final da revisão as legendas devem ser adicionadas ao vídeo através do software Format Factory (Veja como fazer [aqui](https://drive.google.com/file/d/1X4H8jWbZ9jNN8j6kFaZ1u9N-JECNTdga/view?usp=sharing))
- [x] Com o vídeo finalizado e com as legendas, enviar ao professor para revisão e apontar possíveis ajustes.
- [x] Caso tenha, realizar os ajustes solicitados.

**Comment by alessandrapedrotti** [comment]
Responsável: @brendaellen 
É necessário fazer a transposição dos slides disponibilizados pelo(a) professor(a) referente a esse vídeo. 
Para fazer a transposição você deve:

- [ ] Localizar o template elaborado para o curso [nesta pasta](https://drive.google.com/drive/u/0/folders/13sFE1Q_t-8nkXAKBbKpj0oKvc64vFM8L);
Os templates utilizados serão os de capa, créditos 02 e 05; Sendo o 02 para trechos com título e texto e o 05 para trechos com imagem;
- [ ] **Copiar** o template e **transferi-lo** para a pasta dessa tarefa (edição) em questão (que está posta na descrição dessa tarefa);
- [ ] Adicionar títulos, textos, imagens e referências em sua totalidade;
- [ ] Conferir se margens, fontes, tamanhos das fontes e parágrafos estão padronizados em toda a apresentação;
- [ ] Conferir erros de digitação.

**Comment by robisonjose** [comment]
É bom lembrar que os slides devem estar em 1920x1080 (16x9). Pois os slides que a professora disponibilizou estão em 4x4

**Comment by robisonjose** [comment]
A transcrição do vídeo e o link para a primeira versão dele está [nesta pasta](https://drive.google.com/drive/folders/1qPPBDIdTr5ojlK1RW0OrYT6ZyBh3tVPC), @practice-uffs/con-conteudo. Irei fazer a segunda versão do vídeo quando os slides normatizados e a revisão textual estiverem prontos.

**Comment by alessandrapedrotti** [comment]
Responsável: @thaliafriedrich 
Para a revisão textual das legendas:

- [ ] Assistir ao vídeo concomitantemente a leitura da transcrição com a minutagem;
- [ ] Fazer alterações de pontuação e ortografia;
- [ ] Mudar palavras caso elas não estiverem na fala do prof (as vezes a legenda automática coloca umas palavras nada a ver com o que está sendo dito);
- [ ] Rever o vídeo e reler a transcrição da legenda, para ter certeza que nenhum trecho ficou errado.

Observações:
Não há necessidade de deixar no texto da legenda vícios de linguagem, como "tipo", "né" ou similares.

**Comment by thaliafriedrich** [comment]
> A transcrição do vídeo e o link para a primeira versão dele está [nesta pasta](https://drive.google.com/drive/folders/1qPPBDIdTr5ojlK1RW0OrYT6ZyBh3tVPC), @practice-uffs/con-conteudo. Irei fazer a segunda versão do vídeo quando os slides normatizados e a revisão textual estiverem prontos.

@robisonjose, estou sem acesso ao vídeo contido na pasta que você mencionou. O link direciona para um vídeo indisponível (ou privado). Peço que permita o acesso para eu revisar a legenda. O mesmo ocorre na issue #196. Obrigada.

**Comment by robisonjose** [comment]
@thaliafriedrich Realmente, havia colocado privado, mas agora alterei a privacidade nos dois. Creio que agora está dando para acessar.

**Comment by thaliafriedrich** [comment]
Revisão da legenda finalizada.

**Comment by robisonjose** [comment]
Acho que quando finaliza tem que colocar "texto:ok" nas labels.

**Comment by robisonjose** [comment]
Só faltam os slides para que eu possa iniciar a versão final do vídeo @brendaellen @practice-uffs/con-conteudo. Isso vale para a issue #196 também.

**Comment by robisonjose** [comment]
@brendaellen @practice-uffs/con-conteudo Será que seria possível, onde as professoras utilizam imagens, pegar imagens da "fonte" com uma qualidade melhor para refazer os slides? Tem algumas imagens com uma qualidade bem ruim que as professoras utilizaram para fazer os slides.. Isso também acontece na issue #196.

**Comment by brendaellen** [comment]
> @brendaellen @practice-uffs/con-conteudo Será que seria possível, onde as professoras utilizam imagens, pegar imagens da "fonte" com uma qualidade melhor para refazer os slides? Tem algumas imagens com uma qualidade bem ruim que as professoras utilizaram para fazer os slides.. Isso também acontece na issue #196.

Alterei todas as imagens em todas a issues, para aquelas que possuíam qualidade melhor em sua origem. Os slides que continuam com as imagens de qualidade ruim, é porque não encontrei uma segunda opção melhor em minha pesquisa (principalmente as charges).

**Comment by robisonjose** [comment]
@MaNegrao o link para a versão do vídeo a ser corrigido está [aqui](https://drive.google.com/drive/folders/1d2uY8aXKU7r4SD8IJEqHIaXhY6_GTuqM). 

Obs: Em torno do minuto 27:20 o vídeo começa a ficar com um pequeno problema de atualização que foi causado pela má renderização do Format Factory, isso será corrigido nas próximas versões.

**Comment by MaNegrao** [comment]
@robisonjose A professora mandou as alterações necessárias para esse vídeo e o 12 na issue #151.
