### ISSUE TITLE
Edição de vídeo Letras CH (PTA E LPT): 12º vídeo - Resenha parte 2. Profª Morgana

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#196]
Essa issue em questão refere-se ao vídeo 12 - Resenha parte 2. Profª Morgana.  **O vídeo está na pasta [deste link](https://drive.google.com/drive/folders/12DbDJ2_1HtxNSxNHOpSM69tyjSwGzf5D?usp=sharing)**

> Essa série de issues são relacionadas a issue #151, cada uma delas representa um vídeo a ser editado. Todas as edições seguem o mesmo padrão (**[que pode ser visto aqui](https://drive.google.com/file/d/1QvqT4eQkqFvJXLbCJsWAII3UcSEzwbx9/view?usp=sharing)**) e são feitas no software [ShotCut](https://shotcut.org/).

> Os materiais do programa podem ser encontrados na [pasta de materiais](https://drive.google.com/drive/u/3/folders/1uSbwV0EYRQywqVKjY95EsDSd-kT9UmqS) e as ferramentas no [guia do programa](https://guia.practice.uffs.cc)
As etapas de edição desses vídeos são:

- **Primeira etapa:**

- [x] Realizar edição inicial do vídeo seguindo orientações do respectivo professor e agregar slide enviado (arquivos na pasta). Os slides devem ser baixados em formato de imagem, para serem mais facilmente utilizados na edição.
- [x] Caso tenha imagens que precisem de áudio descrição deve-se gravar e agregar ao vídeo.
- [x] Criar uma pasta no link dessa issue chamada _Em progresso_ e armazenar todo conteúdo e o andamento da edição nela.
- [x] Criação da pagina dos créditos seguindo o [template](https://drive.google.com/drive/u/0/folders/1qIai8gugPK9OydUx8P5lcpK4D8vA6n1E) feito pela equipe de conteúdo.
- [x] Inserção das vinhetas e da pagina de créditos com a seguinte ordem:  
[Vinheta de Letras](https://drive.google.com/file/d/1Eiq7A1TRdhYRLFUdVpFPX-CSWwF6M8v_/view?usp=sharing) - Vinheta PRACTICE - Vídeo - Vinheta Letras - Créditos - Vinheta PRACTICE

- **Segunda etapa:**

Com a edição inicial concluída, deve ser feita a legenda do vídeo.

- [x] Upar vídeo editado no YouTube para criação da legenda automática (Para saber como fazer isso, veja o vídeo [deste link](https://drive.google.com/file/d/1Xr-v-E0nF7YHpjiVx94QOUlUhKh9Qu8C/view?usp=sharing))
- [x] Corrigir as palavras erradas da legenda automática gerada e baixar o arquivo .srt (seguindo o vídeo do tópico anterior)
- [x] Com a legenda finalizada, disponibilizar o arquivo e marcar a equipe de conteúdo para revisão textual.
- [x] Ao final da revisão as legendas devem ser adicionadas ao vídeo através do software Format Factory (Veja como fazer [aqui](https://drive.google.com/file/d/1X4H8jWbZ9jNN8j6kFaZ1u9N-JECNTdga/view?usp=sharing))
- [x] Com o vídeo finalizado e com as legendas, enviar ao professor para revisão e apontar possíveis ajustes.
- [x] Caso tenha, realizar os ajustes solicitados.

**Comment by alessandrapedrotti** [comment]
Responsável: @brendaellen 
É necessário fazer a transposição dos slides disponibilizados pelo(a) professor(a) referente a esse vídeo. 
Para fazer a transposição você deve:

- [ ] Localizar o template elaborado para o curso [nesta pasta](https://drive.google.com/drive/u/0/folders/13sFE1Q_t-8nkXAKBbKpj0oKvc64vFM8L);
Os templates utilizados serão os de capa, créditos 02 e 05; Sendo o 02 para trechos com título e texto e o 05 para trechos com imagem;
- [ ] **Copiar** o template e **transferi-lo** para a pasta dessa tarefa (edição) em questão (que está posta na descrição dessa tarefa);
- [ ] Adicionar títulos, textos, imagens e referências em sua totalidade;
- [ ] Conferir se margens, fontes, tamanhos das fontes e parágrafos estão padronizados em toda a apresentação;
- [ ] Conferir erros de digitação.

**Comment by robisonjose** [comment]
A transcrição do vídeo e o link para a primeira versão dele está [nesta pasta](https://drive.google.com/drive/folders/1QWm8k6_hXIVyMpXuirQrvQ50G47dsQSl) @practice-uffs/con-conteudo. Irei fazer a segunda versão do vídeo quando os slides normatizados e a revisão textual estiverem prontos.

**Comment by thaliafriedrich** [comment]
Revisão da legenda concluída. Deixei um comentário para verificar uma parte que está repetida (não removi para não prejudicar a minutagem).

**Comment by robisonjose** [comment]
@thaliafriedrich Você consegue fazer uma versão sem a minutagem, ou seja, a transcrição? Pois eu postei o vídeo sem os cortes necessários para que vocês tivessem mais tempo de mexer com o texto, porém, como vou fazer algumas modificações a minutagem fica toda bugada, e ai se eu tiver a transcrição, eu coloco a versão final do vídeo no YouTube, coloco a transcrição e ele faz a minutagem de maneira automática. Isso seria para todos os textos que você revisou (#188, #190, #194, #195 e esse daqui(#196)). Peço desculpas, por não ter explicado direito que deveria ser feito a transcrição e não a legenda com minutagem.

**Comment by thaliafriedrich** [comment]
> @thaliafriedrich Você consegue fazer uma versão sem a minutagem, ou seja, a transcrição? Pois eu postei o vídeo sem os cortes necessários para que vocês tivessem mais tempo de mexer com o texto, porém, como vou fazer algumas modificações a minutagem fica toda bugada, e ai se eu tiver a transcrição, eu coloco a versão final do vídeo no YouTube, coloco a transcrição e ele faz a minutagem de maneira automática. Isso seria para todos os textos que você revisou (#188, #190, #194, #195 e esse daqui(#196)). Peço desculpas, por não ter explicado direito que deveria ser feito a transcrição e não a legenda com minutagem.

Tudo bem, vou fazer.

**Comment by thaliafriedrich** [comment]
@robisonjose, uma dúvida: você ainda não havia feitos os cortes no vídeo, então assim que fizer, você vai conferir as partes que foram retiradas do vídeo e remover do texto da legenda, certo?

**Comment by robisonjose** [comment]
@thaliafriedrich Isso mesmo. E eu dei uma olhada na transcrição do vídeo, está certo sim. Muito obrigado.

**Comment by robisonjose** [comment]
@MaNegrao o link para a versão do vídeo a ser corrigido está [aqui](https://docs.google.com/document/d/1QW4FQ-_QqXYjQn8IIp25c4X406Puw79U1Sgv4bk6rRs/edit).
