### ISSUE TITLE
Edição de vídeo Letras CH (PTA E LPT): 14º vídeo - Artigo parte 2. Profª Tamiris

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#198]
Essa issue em questão refere-se ao vídeo 14 - Artigo parte 2. Prof Tamiris.  **O O vídeo está [nesta pasta](https://drive.google.com/drive/folders/1E_krIgAZjlW-1jsw41SfViDYpSzztTfh?usp=sharing)**

> Essa série de issues são relacionadas a issue #151, cada uma delas representa um vídeo a ser editado. Todas as edições seguem o mesmo padrão (**[que pode ser visto aqui](https://drive.google.com/file/d/1QvqT4eQkqFvJXLbCJsWAII3UcSEzwbx9/view?usp=sharing)**) e são feitas no software [ShotCut](https://shotcut.org/).

> Os materiais do programa podem ser encontrados na [pasta de materiais](https://drive.google.com/drive/u/3/folders/1uSbwV0EYRQywqVKjY95EsDSd-kT9UmqS) e as ferramentas no [guia do programa](https://guia.practice.uffs.cc)
As etapas de edição desses vídeos são:

- **Primeira etapa:**

- [x] Realizar edição inicial do vídeo seguindo orientações do respectivo professor e agregar slide enviado (arquivos na pasta). Os slides devem ser baixados em formato de imagem, para serem mais facilmente utilizados na edição.
- [x] Caso tenha imagens que precisem de áudio descrição deve-se gravar e agregar ao vídeo.
- [x] Criar uma pasta no link dessa issue chamada _Em progresso_ e armazenar todo conteúdo e o andamento da edição nela.
- [x] Criação da pagina dos créditos seguindo o [template](https://drive.google.com/drive/u/0/folders/1qIai8gugPK9OydUx8P5lcpK4D8vA6n1E) feito pela equipe de conteúdo.
- [x] Inserção das vinhetas e da pagina de créditos com a seguinte ordem:  
[Vinheta de Letras](https://drive.google.com/file/d/1Eiq7A1TRdhYRLFUdVpFPX-CSWwF6M8v_/view?usp=sharing) - Vinheta PRACTICE - Vídeo - Vinheta Letras - Créditos - Vinheta PRACTICE

- **Segunda etapa:**

Com a edição inicial concluída, deve ser feita a legenda do vídeo.

- [x] Upar vídeo editado no YouTube para criação da legenda automática (Para saber como fazer isso, veja o vídeo [deste link](https://drive.google.com/file/d/1Xr-v-E0nF7YHpjiVx94QOUlUhKh9Qu8C/view?usp=sharing))
- [x] Corrigir as palavras erradas da legenda automática gerada e baixar o arquivo .srt (seguindo o vídeo do tópico anterior)
- [x] Com a legenda finalizada, disponibilizar o arquivo e marcar a equipe de conteúdo para revisão textual.
- [x] Ao final da revisão as legendas devem ser adicionadas ao vídeo através do software Format Factory (Veja como fazer [aqui](https://drive.google.com/file/d/1X4H8jWbZ9jNN8j6kFaZ1u9N-JECNTdga/view?usp=sharing))
- [x] Com o vídeo finalizado e com as legendas, enviar ao professor para revisão e apontar possíveis ajustes.
- [x] Caso tenha, realizar os ajustes solicitados.

**Comment by luizdameda** [comment]
Dúvida: após o final do vídeo, no roteiro fala para disponibilizarmos o artigo modelo em PDF. Não entendi como fazer isso, eu salvo cada página no formato imagem e deixo rodando no final do vídeo ou só vamos anexar o arquivo PDF na descrição do vídeo mesmo?

**Comment by MaNegrao** [comment]
> Dúvida: após o final do vídeo, no roteiro fala para disponibilizarmos o artigo modelo em PDF. Não entendi como fazer isso, eu salvo cada página no formato imagem e deixo rodando no final do vídeo ou só vamos anexar o arquivo PDF na descrição do vídeo mesmo?

Ao meu ver seria pra apenas estar anexado ao vídeo, não no vídeo, mas também não entendi muito bem, a descrição da prof é um pouco aberta. @alessandrapedrotti pode dar um help pra gente?

**Comment by alessandrapedrotti** [comment]
> > Dúvida: após o final do vídeo, no roteiro fala para disponibilizarmos o artigo modelo em PDF. Não entendi como fazer isso, eu salvo cada página no formato imagem e deixo rodando no final do vídeo ou só vamos anexar o arquivo PDF na descrição do vídeo mesmo?
> 
> Ao meu ver seria pra apenas estar anexado ao vídeo, não no vídeo, mas também não entendi muito bem, a descrição da prof é um pouco aberta. @alessandrapedrotti pode dar um help pra gente?

No meu entendimento, seria disponibilizar o PDF do modelo na descrição do vídeo ou similar (o link que dá acesso ao PDF, por exemplo).

**Comment by luizdameda** [comment]
@practice-uffs/con-conteudo legenda do issue #198 disponível para a correção na pasta "em progresso".

**Comment by alessandrapedrotti** [comment]
Responsável: @thaliafriedrich 
Para a revisão textual das legendas:

- [ ] Assistir ao vídeo concomitantemente a leitura da transcrição com a minutagem;
- [ ] Fazer alterações de pontuação e ortografia;
- [ ] Mudar palavras caso elas não estiverem na fala do prof (as vezes a legenda automática coloca umas palavras nada a ver com o que está sendo dito);
- [ ] Rever o vídeo e reler a transcrição da legenda, para ter certeza que nenhum trecho ficou errado.

Observações:
Não há necessidade de deixar no texto da legenda vícios de linguagem, como "tipo", "né" ou similares.

**Comment by luizdameda** [comment]
@thaliafriedrich adicionei a legenda [nesta pasta](https://drive.google.com/drive/folders/1rdOkSlG3--ZWdfzZLgCDtnIIccdZd6En). Está nomeada como "Legenda Editável", verifica pra mim se agora está certo.

**Comment by thaliafriedrich** [comment]
Revisão da legenda finalizada.

**Comment by luizdameda** [comment]
A versão final do vídeo está [nesta pasta](https://drive.google.com/drive/folders/1pnzsoexTyjKJb-COCiIlEFc2mEmVzEHU).

Prof.ª @MorganaCambrussi , solicito que encaminhe o vídeo à professora Tamiris para que seja feita a revisão e aprovação do produto.

**Comment by MaNegrao** [comment]
Eu tenho duas sugestões quanto a esse vídeo. Acho que podemos cortar essa parte em vermelho e expandir o vídeo que a professora está mostrando. Fazendo com que o word fique em tela cheia. E podemos manter a camera dela enquanto ela está mostrando o vídeo (se for possível), semelhante aos slides.
![Captura de Tela (37)](https://user-images.githubusercontent.com/31110971/96449161-d6481600-11ea-11eb-9ca1-925d7c9b9cff.png)

**Comment by luizdameda** [comment]
> Eu tenho duas sugestões quanto a esse vídeo. Acho que podemos cortar essa parte em vermelho e expandir o vídeo que a professora está mostrando. Fazendo com que o word fique em tela cheia. E podemos manter a camera dela enquanto ela está mostrando o vídeo (se for possível), semelhante aos slides.
> 
> ![Captura de Tela (37)](https://user-images.githubusercontent.com/31110971/96449161-d6481600-11ea-11eb-9ca1-925d7c9b9cff.png)
> 
> 

Certo! Acho que dá pra fazer sim!! Só não entendi a parte de manter a câmera dela. Essa parte a professora gravou pelo webex, acredito eu, e só tem o áudio e a tela mesmo

**Comment by MaNegrao** [comment]
> Certo! Acho que dá pra fazer sim!! Só não entendi a parte de manter a câmera dela. Essa parte a professora gravou pelo webex, acredito eu, e só tem o áudio e a tela mesmo

Ah, tudo certo então, eu achei que ela tinha enviado o vídeo do webex e o vídeo dela a parte, perdão. Então mantemos só a primeira parte mesmo, que é aplicar o filtro de corte hehe

**Comment by luizdameda** [comment]
a versão final do vídeo com as correções solicitadas pela professora encontram-se [nesta pasta](https://drive.google.com/drive/folders/1pnzsoexTyjKJb-COCiIlEFc2mEmVzEHU)

Prof.ª @MorganaCambrussi peço que envie a versão final à docente responsável. Também peço que verifique com ela se é possível ela mandar a complementação da errata do vídeo 13 até segunda-feira. Obrigado!

**Comment by MorganaCambrussi** [comment]
Boa noite, obrigada!
Ela disse que vai retornar em breve!
Boa semana

Em sáb., 24 de out. de 2020 às 17:24, Luiz Eduardo Dameda <
notifications@github.com> escreveu:

**Comment by MorganaCambrussi** [comment]
Oi, pessoal, sobre o vídeo 13 - Artigo Parte 1

professora Tamiris editou a legenda no arquivo que está postado em:
https://drive.google.com/drive/folders/1FV0W3lRVtdYZpRrbFimvi7SzGB1SP9vk
(ela disse que não achou mais o vídeo na pasta, então, ajustou direto no
arquivo - alteração de 23 de out)

Em dom., 25 de out. de 2020 às 21:14, MORGANA FABIOLA CAMBRUSSI <
morganacambrussi@gmail.com> escreveu:

**Comment by MorganaCambrussi** [comment]
Sobre o vídeo 14, a professora colocou a errata na pasta
https://drive.google.com/drive/folders/1E_krIgAZjlW-1jsw41SfViDYpSzztTfh
(em 23 de out, mas ela esqueceu de me avisar).
Ela mexeu também na legenda deste vídeo, editando o arquivo que está na
pasta
https://drive.google.com/drive/folders/1rdOkSlG3--ZWdfzZLgCDtnIIccdZd6En



Em seg., 26 de out. de 2020 às 15:58, MORGANA FABIOLA CAMBRUSSI <
morganacambrussi@gmail.com> escreveu:

**Comment by MaNegrao** [comment]
O vídeo 14 já foram concluidas as alterações da errata :D. Apenas precisa ser confirmado a finalização

**Comment by MorganaCambrussi** [comment]
Certo, vídeo 14 finalizado! Obrigada!


Em seg., 26 de out. de 2020 às 17:25, Matheus Negrão <
notifications@github.com> escreveu:

**Comment by luizdameda** [comment]
> O vídeo 14 já foram concluidas as alterações da errata :D. Apenas precisa ser confirmado a finalização

Isso, o vídeo 14 já foi finalizado e ainda hoje a noite mandarei o 13 com as correções!

**Comment by MaNegrao** [comment]
Finalizado.
