### ISSUE TITLE
Resumo da reunião de boas-vindas (07/10/2020)

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#199]
A segunda reunião de boas-vindas com os novos bolsistas foi feita. Segue aqui um resumo do que foi tratado:

* Boas-vindas novos bolsistas
* Apresentação do programa (com [esses slides](https://docs.google.com/presentation/d/1QfNSkFke1lDLNVAQQawnM1-YmgpFU-aIv3UC4Cxq-Xo/edit#slide=id.g81e6cb5a66_3_0))
* Capacitação básica no github

Participantes: @alessandrapedrotti, @mariagelain, @amandasegattob , @anacarolinamorigi , @andrewmsilva , @estelavilasboas , @luizdameda , @Claudineia-VR, @MaNegrao , @morgana-mo , @ricardopatrik , @robisonjose.

Se alguém participou e não está listado acima, por favor, postem nessa issue algo como "Eu participei da reunião", para termos registro de quem estava. Além disso, podem postar em seguida qualquer dúvida que ainda tenham. Isso é uma boa oportunidade de ambientar vocês mais um pouco com o github.

Para saber um pouco mais sobre o github, nossa equipe fez um [manual de consulta rápido](https://drive.google.com/file/d/1QrP-AZ2dbRMB4oYVbN-ksCu5xJdlYKvw/view?usp=sharing).

cc: @practice-uffs/todos

**Comment by robisonjose** [comment]
Testando os comentários apenas para falar que você errou meu nome. É Robison :c

**Comment by Claudineia-VR** [comment]
Eu participei da reunião! :)

**Comment by mariagelain** [comment]
Eu participei da reunião.

**Comment by Dovyski** [comment]
Obrigado, pessoal! Nomes devidamente atualizado.

>Testando os comentários apenas para falar que você errou meu nome. É Robison :c

Desculpe! Agora está certo 😉
