### ISSUE TITLE
Criar site do projeto

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#2]
Essa tarefa se refere à criação de um site básico para o projeto. O site será inteiramente baseado no atual layout do [site do curso de Ciência da Computação](https://github.com/ccuffs/cc.uffs.edu.br). Por essa razão, pode-se fazer o seguinte:

- [x] Copiar o conteúdo do repositório [ccuffs/cc.uffs.edu.br](https://github.com/ccuffs/cc.uffs.edu.br) para dentro do repositório [https://github.com/practice-uffs/website-programa](practice-uffs/website-programa)

- [x] Remover e/ou ajudar os links (e páginas relacionadas)  do cabeçalho para conter apenas "O programa" , "Serviços" e "Parcerias".

- [x] Atualizar o rodapé com as informações de contato do programa, incluside direção.

- [x] Disponibilizar o site como Github Pages por enquanto.

**Comment by CleissonVieira** [comment]
@Dovyski Sobre "Contato do programa" e "Direção", quais os dados exatos precisos no rodapé? 

(https://docs.google.com/spreadsheets/d/15kGGrER8UTGQhPIvGm2jHhs3pEO6f7gqISZgRyqpMKE/edit#gid=0) 

nesse link acima não tem as informações da gerência, encontrei nesse abaixo, porém não todos os dados:

(https://docs.google.com/document/d/1aMopCgF0AoFv0ZEzYmEsWk4TSwDG4M2ETV4XKpL-zss/edit)

**Comment by Dovyski** [comment]
> @Dovyski Sobre "Contato do programa" e "Direção", quais os dados exatos precisos no rodapé?

Contato: practice@uffs.edu.br

"Direção" trocar para "Coordenação Geral"
- Maurício
- Fernando

Criar "Coordenação Técnico-pedagógica":

- Caimi
- Elis

> No momento cabeçalho está como a imagem abaixo:
> ![image](https://user-images.githubusercontent.com/29258164/86504479-28297500-bd8f-11ea-88c6-469948c4fc4c.png)

Ok. 

> E rodapé está como a imagem abaixo:
> ![image](https://user-images.githubusercontent.com/29258164/86504489-48593400-bd8f-11ea-811d-f3b4a864eeb1.png)
> 

Ok.

> O conteúdo entre cabeçalho e rodapé continuam o mesmo do site de [Ciência da Computação](https://cc.uffs.edu.br/)

Ok por agora.

> Outra questão, como posso fazer para realizar commits no repositório: practice-uffs/website-programa.git
> Não tenho permissão no momento.
> 
> Criei [esse repositório](https://github.com/practice-uffs/practice-uffs.github.io) para realizar a tarefa dessa Issue no momento.

O repositório website-programa está pronto para uso. Por favor, migre os trabalhos para lá (apenas os arquivos alterados). No repositório website-programa, o site está dentro da pasta `src`, não mais na raiz do projeto (como nesse repositório aqui).

**Comment by CleissonVieira** [comment]
Último check-box cancelado, @Dovyski  informou que será colocado em um servidor externo.
Demais tarefas concluídas.
