### ISSUE TITLE
[Estúdios] Instalação dos equipamentos em Laranjeiras do Sul

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/programa#20]
O título desta issue é auto-explicativo. É necessário que um grupo de pessoas pegue os equipamentos, leve-os para a campus e instale-os.

**Comment by MaNegrao** [comment]
@VIF-Franca essa está na mesma situação da issue #22, podemos fechar também?

**Comment by VIF-Franca** [comment]
@MaNegrao as instalações e testes já foram realizados no laboratório de mídias do campus Laranjeiras do Sul.
