### ISSUE TITLE
Escolha da equipe de trabalho para os novos bolsistas

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#200]
Agora que todos os novos bolsistas estão ambientados com o programa, cada um precisa escolher uma equipe para atuar (como equipe principal). Lembrando que vocês podem escolher uma equipe principal (sua "tribo", seu foco principal) e uma equipe secundária (para ajudar quando a equipe principal não tiver demandas).

Aos novos bolsistas, coloquem as equipes que vocês gostariam de atuar nas colunas "Equipe principal" e "Equipe Secundária" [nessa planilha](https://docs.google.com/spreadsheets/d/1v6MwH98DghBLEkZP1_NkuJmr325V7IXED2UqX4eqxZE/edit#gid=0). 

Prazo: até as 23:59 de 07/10/2020

**Comment by Dovyski** [comment]
@practice-uffs/todos  Novos bolsistas, por favor, atentem para essa tarefa. @practice-uffs/ger-auxilio podemos alocar todo mundo nas equipes amanhã, inclusive discutir eventuais atuações em duas equipes se julgarmos pertinente.

**Comment by VIF-Franca** [comment]
@rafaguilman @GessicaZanon @juliagaio 

Faltam apenas vocês para preencher as colunas de equipe principal e secundária.

**Comment by luizatonial** [comment]
Gostaria de lembrar para tomarem cuidado com a planilha... Alguém havia alterado as equipes que eu escolhi.

**Comment by rafaguilman** [comment]
Solicitei acesso a planilha

**Comment by alessandrapedrotti** [comment]
> Solicitei acesso a planilha

acesso permitido.

**Comment by Dovyski** [comment]
@practice-uffs/ger-auxilio na nossa [planilha oficial de membros e equipes](https://docs.google.com/spreadsheets/d/15kGGrER8UTGQhPIvGm2jHhs3pEO6f7gqISZgRyqpMKE/edit#gid=0), eu coloquei em vermelho as equipes dos bolsistas novos. Por favor, confirmem a equipe final da pessoa e coloquem a cor do texto em pretato. Os que sobrarem em cor vermelha são aqueles que ainda não tem equipe certa.

**Comment by Dovyski** [comment]
@practice-uffs/lideres façam uma checagem da [planilha oficial de membros e equipes](https://docs.google.com/spreadsheets/d/15kGGrER8UTGQhPIvGm2jHhs3pEO6f7gqISZgRyqpMKE/edit#gid=0) com os novos integrantes junto com @practice-uffs/ger-auxilio. Eu acho que todos que solicitaram design e que colocam colocados na mídia, podem trabalhar com animação (já que anim é da mídia agora, e não tínhamos ninguem nessa ilha na con-midia).

**Comment by alessandrapedrotti** [comment]
Conferência feita e os novos (não mais novos) membros foram alocados para suas respectivas equipes e também já foram adicionados aos seus respectivos grupos no telegram.
Existe ainda alguma pendência?

**Comment by MaNegrao** [comment]
Conferencia Realizada!
