### ISSUE TITLE
Padronização Nomes e e-mails das redes sociais do PRACTICE

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#201]
No inicio do programa algumas contas foram criadas com nomes e e-mails diferentes, por ex: eu uso o Youtube para as transmissões, mas o e-mail do canal não é o practiceuffs@gmaill.com, e sim outro gmail, além de que nosso canal não tem uma URL personalizada, mas está disponível para criação. 

É possível alterar o e-mail do YouTube nesse caso, mas há uma verificação de duas etapas de alguém. 
E outro caso são os nomes, se eu não me engano a ideia era ser padronizado, na época não era possível alterar, creio que agora é possível.

Agora com a nova equipe de comunicação as redes vão ficar movimentadas, então seria interessante a gente fazer isso. 

CC: @practice-uffs/ger-auxilio e @practice-uffs/ger

**Comment by alessandrapedrotti** [comment]
Favor @VIF-Franca se internar da situação e resolver as questões que forem necessárias.

**Comment by VIF-Franca** [comment]
Facebook --> Practice UFFS --> https://www.facebook.com/Practice-UFFS-104348284683285
Instagram --> Practice UFFS --> https://www.instagram.com/practiceuffs/
Youtube --> Url personalizado --> https://www.youtube.com/c/PRACTICEUFFS
Twiter --> Practice UFFS --> https://twitter.com/PracticeUffs

**Comment by VIF-Franca** [comment]
Creio que todos estão padronizados.
