### ISSUE TITLE
Edição de Vídeo - Homenagem aos Docentes UFFS Chapecó - 14/10/2020

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#202]
Edição de vídeo para Homenagem do dia do professor, entrega para dia 14/10 (demanda do campus Chapecó): 
Se atentar ao Script enviado por eles com as informações que se encontram na [pasta](https://drive.google.com/drive/folders/1XrOCWDvI-s8LVFbdgViO_MAsgcAxAqS7?usp=sharing) 

1) Inserir a logo da UFFS e escrever campus Chapecó ou escrever em verde: UFFS/Campus Chapecó, 2020
2) juntar todos os vídeos em 1 só
3) inserir a mensagem que eles elaboraram conforme o script 
4) Inserir legenda
5) inserir a melodia ao fundo do vídeo que encontra-se na pasta

@luizatonial, como proposto por você no Telegram, segue a demanda acima. Qualquer dúvida tire com o @MaNegrao

**Comment by luizatonial** [comment]
O vídeo já finalizado encontra-se na [pasta](https://drive.google.com/drive/folders/1p3M-IAqYk-l2isAB-8T38dA0kwnxvbi3). Aguardo revisão e possíveis alterações. 😉

**Comment by MaNegrao** [comment]
@VIF-Franca pode enviar o link para o solicitante revisar?

**Comment by VIF-Franca** [comment]
Link enviado ao solicitante, assim que receber um feedback aviso.

**Comment by VIF-Franca** [comment]
Cliente aprovou o vídeo, @luizatonial Parabéns!!!
