### ISSUE TITLE
Criar panfletos de divulgação do PRACTICE - Serviços de áudio e vídeo

### ISSUE THREAD

**Issue by mariagelain** [practice-uffs/programa#203]
Conforme a produção dos textos na issue #166, devemos criar os panfletos de divulgação de cada serviço do programa. 
O texto dos serviços de áudio de vídeo está disponível  [nesse arquivo](https://docs.google.com/document/d/1ejmPGoR9g33l8_63Z7SLizuwm5SmWx_OSPUMlw3D_yw/edit). 
Deve conter entre 1 e 2 páginas, conforme a quantidade de conteúdo a ser inserido;
Deve seguir o padrão dos demais [panfletos divulgados](https://docs.google.com/presentation/d/19V1EShUWn3eKSL6rXFt1Sey2QPG-k9pgVzU0Vj_srEg/edit#slide=id.g98045de9e1_0_12) e dos [templates](https://drive.google.com/drive/u/0/folders/1t30y9uPM0L5iQ1GRl6omnA6VopQRe9NP);

**Comment by estelavilasboas** [comment]
A revisão dos textos para os panfletos não foi concluída. Portanto, neste primeiro momento, vamos construir o panfleto no Apresentações, assim como os [panfletos divulgados](https://docs.google.com/presentation/d/19V1EShUWn3eKSL6rXFt1Sey2QPG-k9pgVzU0Vj_srEg/edit#slide=id.g98045de9e1_0_12) e os [templates](https://drive.google.com/drive/u/0/folders/1t30y9uPM0L5iQ1GRl6omnA6VopQRe9NP).
As imagens podem ser construídas em um editor de imagem e devem ser colocadas na [pasta do drive dessa issue](https://drive.google.com/drive/folders/10DPDSM38tw-12q3jKYN1szEzB8Om2LT8). A diagramação e ajustes restantes devem ser realizados no Apresentações. Dessa forma, o restante dos integrantes da con-conteúdo podem editar o texto facilmente durante a revisão.

**Comment by alessandrapedrotti** [comment]
Fiz algumas alterações no texto do panfleto por questões de volume de texto. Também deixei 2 comentários no material com sugestões de alterações.

**Comment by ricardopatrik** [comment]
@alessandrapedrotti alterado

**Comment by estelavilasboas** [comment]
Panfleto revisado. Aguardando aprovação.
Versão final em pdf disponível na [pasta saída](https://drive.google.com/drive/folders/1GvUmBG2aEdHd6xBo9ig4RcNjyAAYMwOL).

**Comment by estelavilasboas** [comment]
Versão final inserida na pasta de divulgação.
