### ISSUE TITLE
Criar panfletos de divulgação do PRACTICE - Serviços de realização de eventos online

### ISSUE THREAD

**Issue by mariagelain** [practice-uffs/programa#204]
Conforme a produção dos textos na issue #166, devemos criar os panfletos de divulgação de cada serviço do programa. 
O texto dos serviços de realização de eventos online está disponível [nesse arquivo](https://docs.google.com/document/d/18I86GwDb_CAeaNEI2a0zFVOF7_e3CUPqqwp9xE7VjgU/edit). 
Deve conter entre 1 e 2 páginas, conforme a quantidade de conteúdo a ser inserido;
Deve seguir o padrão dos demais [panfletos divulgados](https://docs.google.com/presentation/d/19V1EShUWn3eKSL6rXFt1Sey2QPG-k9pgVzU0Vj_srEg/edit#slide=id.g98045de9e1_0_12) e dos [templates](https://drive.google.com/drive/u/0/folders/1t30y9uPM0L5iQ1GRl6omnA6VopQRe9NP);

**Comment by estelavilasboas** [comment]
A revisão dos textos para os panfletos não foi concluída. Portanto, neste primeiro momento, vamos construir o panfleto no Apresentações, assim como os [panfletos divulgados](https://docs.google.com/presentation/d/19V1EShUWn3eKSL6rXFt1Sey2QPG-k9pgVzU0Vj_srEg/edit#slide=id.g98045de9e1_0_12) e os [templates](https://drive.google.com/drive/u/0/folders/1t30y9uPM0L5iQ1GRl6omnA6VopQRe9NP).
As imagens podem ser construídas em um editor de imagem e devem ser colocadas na [pasta do drive dessa issue](https://drive.google.com/drive/folders/1NKUk2uAyQmP6hm99h9GQ_yiMygdrO-kw). A diagramação e ajustes restantes devem ser realizados no Apresentações. Dessa forma, o restante dos integrantes da con-conteúdo podem editar o texto facilmente durante a revisão.

**Comment by TaynaraCh** [comment]
Terminei!

**Comment by alessandrapedrotti** [comment]
O @MaNegrao adicionou um trecho no [texto original](https://docs.google.com/document/d/1aGGE-U5E-A-YsMN-wZOANsG3CZN_KprWV0rJnXYjFX8/edit). Favor atualizar o panfleto.

Seria interessante deixar esse panfleto no mesmo estilo (duas páginas) que os outros que também estão sendo produzidos, assim fica tudo padronizado.

**Comment by TaynaraCh** [comment]
Estou refazendo toda a diagramação, mas para poder seguir um padrão, seria interessante que houvesse uma padronização na elaboração dos textos também.

**Comment by TaynaraCh** [comment]
Está pronto!

**Comment by estelavilasboas** [comment]
Panfleto revisado. Aguardando aprovação.
Versão final em pdf disponível na [pasta saída](https://drive.google.com/drive/folders/1iqHo-2AYOUKu0hpGGqrOkz5NdPtg3Sgl).

**Comment by estelavilasboas** [comment]
Versão final já disponível na pasta de divulgação.
