### ISSUE TITLE
Criar panfletos de divulgação do PRACTICE -  Serviços de conteúdo

### ISSUE THREAD

**Issue by mariagelain** [practice-uffs/programa#205]
Conforme a produção dos textos na issue #166, devemos criar os panfletos de divulgação de cada serviço do programa. 
O texto dos serviços de conteúdo está disponível [nesse arquivo](https://docs.google.com/document/d/1pzbUOoZ93rfCWmSK8flUH6AxtR6P1zW5pOHv5ikKCiI/edit). 
Deve conter entre 1 e 2 páginas, conforme a quantidade de conteúdo a ser inserido;
Deve seguir o padrão dos demais [panfletos divulgados](https://docs.google.com/document/d/1pzbUOoZ93rfCWmSK8flUH6AxtR6P1zW5pOHv5ikKCiI/edit) e dos [templates](https://drive.google.com/drive/u/0/folders/1t30y9uPM0L5iQ1GRl6omnA6VopQRe9NP);

**Comment by estelavilasboas** [comment]
A revisão dos textos para os panfletos não foi concluída. Portanto, neste primeiro momento, vamos construir o panfleto no Apresentações, assim como os [panfletos divulgados](https://docs.google.com/presentation/d/19V1EShUWn3eKSL6rXFt1Sey2QPG-k9pgVzU0Vj_srEg/edit#slide=id.g98045de9e1_0_12) e os [templates](https://drive.google.com/drive/u/0/folders/1t30y9uPM0L5iQ1GRl6omnA6VopQRe9NP).
As imagens podem ser construídas em um editor de imagem e devem ser colocadas na [pasta do drive dessa issue](https://drive.google.com/drive/folders/1aFCHQaHi2wlfVa6jDP9iMW_-EOZatQaz). A diagramação e ajustes restantes devem ser realizados no Apresentações. Dessa forma, o restante dos integrantes da con-conteúdo podem editar o texto facilmente durante a revisão.

**Comment by TaynaraCh** [comment]
Está pronto!

**Comment by alessandrapedrotti** [comment]
Fiz uma pequena alteração no [texto original](https://docs.google.com/document/d/1pzbUOoZ93rfCWmSK8flUH6AxtR6P1zW5pOHv5ikKCiI/edit?ts=5f861796). São apenas dois pontos (o primeiro é a mudança das palavras "por exemplo" pra "sendo eles" e o segundo é a adição do tempo de entrega dos serviços de texto). Acredito que essa mudança ainda possa ser feita no panfleto também.

**Comment by TaynaraCh** [comment]
Correções ajustadas no panfleto

**Comment by estelavilasboas** [comment]
Panfleto revisado. Aguardando aprovação.
Versão final em pdf disponível na [pasta saída](https://drive.google.com/drive/folders/1oSoeMuO9L5k0Cg__V7e1w5C0VICXJANd).

**Comment by estelavilasboas** [comment]
Versão final disponível na pasta de divulgação.
