### ISSUE TITLE
Criar panfletos de divulgação do PRACTICE - Serviços de Estúdio

### ISSUE THREAD

**Issue by mariagelain** [practice-uffs/programa#206]
Conforme a produção dos textos na issue #166, devemos criar os panfletos de divulgação de cada serviço do programa. 
O texto dos serviços de estúdio está disponível [nesse arquivo](https://docs.google.com/document/d/1aGGE-U5E-A-YsMN-wZOANsG3CZN_KprWV0rJnXYjFX8/edit). 
Deve conter entre 1 e 2 páginas, conforme a quantidade de conteúdo a ser inserido;
Deve seguir o padrão dos demais [panfletos divulgados](https://docs.google.com/document/d/1pzbUOoZ93rfCWmSK8flUH6AxtR6P1zW5pOHv5ikKCiI/edit) e dos [templates](https://drive.google.com/drive/u/0/folders/1t30y9uPM0L5iQ1GRl6omnA6VopQRe9NP);

**Comment by estelavilasboas** [comment]
A revisão dos textos para os panfletos não foi concluída. Portanto, neste primeiro momento, vamos construir o panfleto no Apresentações, assim como os [panfletos divulgados](https://docs.google.com/presentation/d/19V1EShUWn3eKSL6rXFt1Sey2QPG-k9pgVzU0Vj_srEg/edit#slide=id.g98045de9e1_0_12) e os [templates](https://drive.google.com/drive/u/0/folders/1t30y9uPM0L5iQ1GRl6omnA6VopQRe9NP).
As imagens podem ser construídas em um editor de imagem e devem ser colocadas na [pasta do drive dessa issue](https://drive.google.com/drive/folders/1WHy1HoJFL4zQMadFL7fev_AW7PQNV2Yj). A diagramação e ajustes restantes devem ser realizados no Apresentações. Dessa forma, o restante dos integrantes da con-conteúdo podem editar o texto facilmente durante a revisão.

**Comment by ricardopatrik** [comment]
Fiz duas pequenas sugestões no texto, onde dizia 8 dias, modifiquei para: "08 (dias)" e em negrito para um destaque maior na data. E onde dizia Chapecó e Laranjeiras do Sul, acrescentei seus respectivos UF, ficando assim: '' Chapecó/SC e Laranjeiras do Sul/PR. Apenas uma sugestão. Em questão do layout utilizei a partir do template proposto. Estou à disposição para alterações.

**Comment by alessandrapedrotti** [comment]
O @MaNegrao adicionou um trecho no [texto original](https://docs.google.com/document/d/1aGGE-U5E-A-YsMN-wZOANsG3CZN_KprWV0rJnXYjFX8/edit). Favor atualizar o panfleto.

Além disso, deixei um comentário no panfleto que gostaria que fosse alterado.

**Comment by estelavilasboas** [comment]
Panfleto revisado. Aguardando aprovação.
Versão final em pdf disponível na [pasta saída](https://drive.google.com/drive/folders/1RQoYkxWVgHu_MljzTxP9NONlPT7Cb5K5).

**Comment by estelavilasboas** [comment]
Versão final disponível na pasta de divulgação.
