### ISSUE TITLE
Organização de Ilhas @con-midia

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#207]
Como conversado na reunião de mídia hoje nós definimos a organização das ilhas da equipe. Então cada bolsista de acordo com suas habilidades e afinidades vão estar direcionados à uma area do midia. 

@practice-uffs/con-midia  Preencham na planilha, que está na pasta, a ilha em que vocês pretendem atuar primariamente.

[Pasta Drive](https://drive.google.com/drive/u/3/folders/12rq_fDB1LMHIrgGKGITfNYVuGASe4Vog)

**Comment by robisonjose** [comment]
Que pasta?

**Comment by MaNegrao** [comment]
> Que pasta?

Na descrição tem o link

**Comment by MaNegrao** [comment]
Por ora essa tarefa está concluída, caso venha entrar alguém no mídia, nós reabrimos e incluímos a pessoa.
