### ISSUE TITLE
[Estúdios] Teste de gravação em Chapecó

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/programa#21]
Assim que todos os equipamentos estiverem devidamente instalados, é necessário realizar um teste de gravação para verificar se está tudo funcionando corretamente.

**Comment by lcaimi** [comment]
Montagem e teste para sexta-feira 21/08/2020 9h
@Dovyski 
@phdmauricio 
@lcaimi 
@MaNegrao
