### ISSUE TITLE
Melhorias no template de cartilha simples

### ISSUE THREAD

**Issue by estelavilasboas** [practice-uffs/programa#211]
Na issue #46, nos propomos a produzir templates de cartilhas e manuais do PRACTICE. Hoje vemos que melhorias precisam ser feitas.
A ideia não é refazer os templates do zero, é melhorar o seu design. 
Pode-se utilizar formas e ilustrações a sua escolha. As ondas dos templates de panfleto, por exemplo, foram feitas em desenhos vetorial. Vocês podem se divertir criando esses detalhes para podermos aprimorar as formas padrão, cor de fundo, e até página de créditos presentes no template atual.
Uma cópia do template de cartilha simples será deixado na [pasta dessa issue](https://drive.google.com/drive/u/0/folders/1ML5vlrmsXss1y2LUvuomQRXjJzvZrOjK).
Peço que criem o tema do template, para facilitar o trabalho dos redatores e o nosso na revisão gráfica e de diagramação.
Caso queriam e/ou tenham ideias para reformular completamente o template, sintam-se livres para sugerir inserindo o arquivo na pasta.
Após a melhoria do template de cartilha simples, avançaremos para os templates de cartilha moderada e complexa, e para o template de manual.

**Comment by TaynaraCh** [comment]
Finalizamos!

**Comment by estelavilasboas** [comment]
Alguns apontamentos foram levantados, após discussão com con-conteúdo:
* As orientações devem estar como primeira página. Elas são orientações básicas para os redatores, apenas para uso interno. Nós detalharemos mais as orientações em um manual em um projeto futuro.
* A página de créditos deve estar em penúltimo como o template de cartilha anterior e deve ser dividida em duas páginas: A primeira contendo realização, redator, revisão textual e gráfica, e a segunda com os nomes de cada integrante do PRACTICE. A lista de integrantes deve ser atualizada conforme o [site](https://practice.uffs.cc/equipe/), sem divisão de equipes.
* Sugestão para criar novas ondas e menores para os rodapés. As cartilhas e manuais produzidos contêm muitas imagens e, com o padrão de ondas atual, pode acontecer de uma página ficar extremamente colorida por conta das cores em si. Uma sugestão é a utilização apenas dos tons azuis, talvez acompanhados de tons de cinza, em busca de maior neutralidade. Seria interessante uma versão sem este rodapé para páginas com muitas ou apenas com imagens.

Tenham em mente que algumas das características da identidade do PRACTICE é ser moderno e limpo, apesar de ter cores complementares. Por este motivo, debemos pensar bem na utilização das cores.
Não tenham medo de inovar ou de criar algo que pense se distanciar da identidade visual. Tudo o que é criado é passível de aprovação.

**Comment by TaynaraCh** [comment]
Alterações concluídas

**Comment by estelavilasboas** [comment]
Favor criar uma pasta chamada "imagens" dentro da pasta da issue e colocar as ondas azuis e cinzas. Elas podem ser utilizadas em outras partes do projeto.

**Comment by TaynaraCh** [comment]
Pasta criada

**Comment by TaynaraCh** [comment]
Alterações feitas! O nome do arquivo está como Teste.

**Comment by estelavilasboas** [comment]
Ajustes de margem realizados.

**Comment by estelavilasboas** [comment]
[Logo da capa atualizada](https://docs.google.com/presentation/d/1rqDILGaTS6bQI1_GAeJBTJ96aQFkt0B1mb6BPmI6gNM/edit#slide=id.ga239f8379f_0_22) conforme identidade visual. Os três riscos do símbolo devem estar visíveis.

**Comment by estelavilasboas** [comment]
@TaynaraCh, conseguimos fazer versões espelhadas das páginas como na [página 3](https://docs.google.com/presentation/d/1rqDILGaTS6bQI1_GAeJBTJ96aQFkt0B1mb6BPmI6gNM/edit#slide=id.ga239f8379f_0_27) e [página 4](https://docs.google.com/presentation/d/1rqDILGaTS6bQI1_GAeJBTJ96aQFkt0B1mb6BPmI6gNM/edit#slide=id.ga239f8379f_0_78) ?

**Comment by TaynaraCh** [comment]
Alterações concluídas.

**Comment by estelavilasboas** [comment]
Com a finalização dessa issue, serão criadas outras duas issues para a transposição para templates de cartilha complexa e de manual.

**Comment by estelavilasboas** [comment]
Melhorias concluídas. Ambas as versões de templates definidas estão na [pasta da issue](https://drive.google.com/drive/u/0/folders/1KTzmSpCcDy0NAyRk567MqmcGc3lFXdVL). Serão abertas outras issues para a transposição para template de cartilha complexa e template de manual.
