### ISSUE TITLE
Produção dos roteiros da série de Vídeos do OBS 

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#212]
Essa issue tem como objetivo produzir os roteiros e estudar a quantidade de vídeos que serão produzidos na serie de tutoriais sobre o OBS e a realização de transmissões ao vivo. Eu pensei no formato onde será gravada a tela e a cam do interlocutor no canto.

Devemos usar o [modelo de roteiro de vídeos](https://docs.google.com/document/d/1MlC1k-KU98ihFSUJu-G5NpQ3JPZdOgkfKUd5Lk8XZTk/edit?usp=sharing) 

Nós iremos abordar nos vídeos os seguintes tópicos:

- Como baixar e instalar o OBS
- Como agendar uma transmissão no Facebook e no Youtube
- Configurações iniciais
- Como configurar o software para transmissão
- Como configurar o software para gravação
- Como importar o template padrão do programa
- Como localizar e adicionar fontes de entrada
- Como compor as cenas da transmissão
- Como usar filtros de cor e recorte

Creio que a ilha de lives fica responsável pelos roteiros. Caso julguem necessário algum ponto que está faltante, podem comentar aqui.

CC: @practice-uffs/con-midia 

[Pasta Drive](https://drive.google.com/drive/folders/1XCaKr9EYQ6Y-KfhyX3IvSWQWS_sgx65m)

**Comment by luizatonial** [comment]
Listei e dividi alguns tópicos iniciais, por enquanto, e vou esperar a capacitação de sexta-feira para tomar como base e dar continuidade à produção do roteiro.

**Comment by luizatonial** [comment]
A versão inicial do roteiro está finalizada. Os roteiros dos 5 vídeos estão no mesmo documento.

Adicionei alguns comentário em relação ao conteúdo do vídeo que trata sobre a importação do template padrão do programa e outro sobre as configurações das lives, se você conseguir dar uma olhada @MaNegrao.

Peço que alguém da @practice-uffs/con-conteudo revise o texto dos roteiros.

**Comment by alessandrapedrotti** [comment]
@thaliafriedrich favor tratar da revisão desses roteiros.

**Comment by MaNegrao** [comment]
Eu achei os textos excelentes em questão de clareza no conteúdo e tudo mais, coloquei alguns comentários lá. 

Eu tenho duas sugestões mais gerais, uma é em relação aquele cadeado que temos no OBS, pra travar a posição dos elementos (eu posso ter deixado passar esse no texto)
E a outra que eu acho bem interessante é a interligação entre o webex e o OBS, como configurar a visualização do OBS tanto para interpretes quanto para os apresentadores na composição das cenas.

**Comment by luizatonial** [comment]
Certo, vou aguardar a primeira revisão do texto e já adiciono essas novas informações também.

**Comment by thaliafriedrich** [comment]
> Certo, vou aguardar a primeira revisão do texto e já adiciono essas novas informações também.

Primeira revisão feita. Os roteiros estão ótimos! Quanto ao conteúdo, não tenho conhecimento no assunto para fazer sugestões, então só fiz correções textuais de algumas palavras e vírgulas, e deixei uns comentários no texto para você conferir.  

Após essas alterações e a inserção das informações sugeridas pelo @MaNegrao, posso fazer uma nova revisão textual.

**Comment by luizatonial** [comment]
@MaNegrao, você havia sugerido que na parte da importação do template de lives, eu demonstrasse como acessar o template. 
Tem duas coisas que fiquei em dúvida sobre isto. 

Primeiro, direcionamos as pessoas para o [último template ](https://drive.google.com/drive/folders/10rRXLCNkY4bBaWlzciepf9-hm47RZdvI) que estamos utilizando ou para este [aqui](https://drive.google.com/drive/folders/19x_vS7ZEZHhJtzjCYgdT3gF9ij2B0yz9)? Percebi que o mais recente não está em uma pasta pública, então se postarmos no youtube o público externo não conseguiria acessar.
E por onde eu começaria a direcionar as pessoas, do [guia](https://guia.practice.uffs.cc/#/?id=github-e-controle-de-projetos) até a pasta geral do drive, por exemplo, e então para uma pasta específica que conteria um desses arquivos?

**Comment by MaNegrao** [comment]
Podemos fazer o seguinte: redirecionar o pessoal para a pasta que está na pasta de materiais, podemos gerar um link publico dele sem problemas, e dai quando for saindo os overlays vamos substituindo, só teria que upar a ultima versão lá, ela está em zip atualmente. E dai no vídeo tu indica e fala que a pasta toda tem que ser baixada etc

**Comment by luizatonial** [comment]
Acredito que seja importante apresentar a questão de como programar o bate papo, já que ele irá compor nossas transmissões. Vou dar uma pesquisada sobre isso e adicionar ao roteiro, junto com a parte da programação do webex que faltava.

**Comment by MaNegrao** [comment]
Perfeito, eu usei o streamlabs pra configurar, tu pode dar uma procurada, é bem simples, tem apenas umas configurações de tamanho de texto e fonte que tem que fazer

**Comment by luizatonial** [comment]
@thaliafriedrich finalizei as modificações nos roteiros, você já pode fazer a nova revisão.

**Comment by thaliafriedrich** [comment]
> @thaliafriedrich finalizei as modificações nos roteiros, você já pode fazer a nova revisão.

Ficou ótimo, só fiz algumas correções textuais.
Não sendo necessário mais alterações, a revisão textual está finalizada.

**Comment by luizatonial** [comment]
Finalizada a montagem do roteiro. Vou começar a criar as issues para gravação e edição, @MaNegrao acho que já pode encerrar esta.

**Comment by MaNegrao** [comment]
Beleza, issue finalizada
