### ISSUE TITLE
Roteiro - Produção de vídeo tutorial de edição de áudio no formato de Podcast

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#213]
Seguindo a ideia apresentada pela @alessandrapedrotti, vamos produzir um ou dois vídeos de no máx 10min dando dicas e explicando como fazer a edição de áudio no formato de podcast. Usaremos o software Audacity.

Alguns dos pontos que podemos abordar:

- Redução de ruído
- Quais cortes realizar
- Seleção de trilhas gratuitas
- Separação em blocos.
- Edição de múltiplas faixas.

Creio que precisamos de mais ideias para produção do roteiro e dos vídeos propriamente ditos.

CC: @practice-uffs/con-midia 

[Pasta Drive](https://drive.google.com/drive/folders/1Zk8JfogcZiNdUy9qOjmqR2XfeszOADhM?usp=sharing)

**Comment by robisonjose** [comment]
Comecei a escrever o roteiro, ainda estou colocando os pontos importantes que a gente deve abordar, quem quiser ajudar elencando mais pontos o roteiro está [aqui](https://drive.google.com/drive/u/1/folders/1Zk8JfogcZiNdUy9qOjmqR2XfeszOADhM).

**Comment by MaNegrao** [comment]
> Comecei a escrever o roteiro, ainda estou colocando os pontos importantes que a gente deve abordar, quem quiser ajudar elencando mais pontos o roteiro está [aqui](https://drive.google.com/drive/u/1/folders/1Zk8JfogcZiNdUy9qOjmqR2XfeszOADhM).

Eu esqueci de anexar à tarefa, mas temos um modelo de roteiro, caso queira usar. Está na [pasta de modelos](https://drive.google.com/drive/u/0/folders/1RcRmRPTb4pWNUevF-A3vXcjuDq_0aMaQ) do PRACTICE.

**Comment by robisonjose** [comment]
Preciso que seja feito a revisão textual do meu [monólogo](https://docs.google.com/document/d/1IcdliSN0sqKSSLSPRtKj5tG8tOV975KG0V0HSRd3TSw/edit) para o vídeo tutorial.
@practice-uffs/con-conteudo

**Comment by robisonjose** [comment]
Preciso que seja feito a revisão textual do meu [monólogo](https://drive.google.com/drive/folders/1Zk8JfogcZiNdUy9qOjmqR2XfeszOADhM) para o vídeo tutorial.
@practice-uffs/con-conteudo

**Comment by thaliafriedrich** [comment]
Revisão concluída! Fiz a correção de algumas vírgulas e alteração ou inserção de uma ou outra palavra, que deixei destacado em azul para verificar. Achei o conteúdo do roteiro muito bom e bem escrito, por isso, acredito que a parte de revisão textual já está finalizada.

**Comment by robisonjose** [comment]
Decidi fazer uma [issue](https://github.com/practice-uffs/programa/issues/341) específica para o vídeo.
