### ISSUE TITLE
Adaptação cartilha de dicas para produzir um bom texto em formato de vídeos

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#214]
O objetivo dessa issue é estudar e produzir os roteiros da adaptação da [cartilha de dicas para produzir um bom texto](https://drive.google.com/file/d/1q-7FWZlD72-t68jZgd-mgc0d4mXQ6Xrz/view?usp=sharing). 

Penso que podemos fazer uma serie de vídeos em animações simples com narração, mas precisamos decidir quantos vídeos serão e quais os principais tópicos que precisamos abordar. 

Acho que a equipe de @practice-uffs/con-conteudo pode ajudar nessa adaptação.

CC: @practice-uffs/con-midia 

[Pasta Drive](https://drive.google.com/drive/folders/19fVvLZDr_oM9kHxAjkhXstPlv1f5j7mB)

**Comment by MaNegrao** [comment]
A @MilenaPaz2020 assume a frente desse projeto.

**Comment by alessandrapedrotti** [comment]
A @isabelirk também trabalhará nessa tarefa, liderando a roteirização do material textual.

**Comment by isabelirk** [comment]
Boa tarde,

Uma primeira versão já esta finalizada. Porém não faço ideia de como seria essa adaptação dessa cartilha para uma animação, como sugerido na descrição, por isso a coluna descrição do documento ainda se encontra em branco. Ao meu ver, esta adaptação seria mais interessante a realização de um vídeo com uma pessoa explicando, já que estamos falando de algo mais abstrato. Segue abaixo o link da pasta com o roteiro. 

https://drive.google.com/drive/folders/19fVvLZDr_oM9kHxAjkhXstPlv1f5j7mB

Atenciosamente.

**Comment by alessandrapedrotti** [comment]
> Boa tarde,
> 
> Uma primeira versão já esta finalizada. Porém não faço ideia de como seria essa adaptação dessa cartilha para uma animação, como sugerido na descrição, por isso a coluna descrição do documento ainda se encontra em branco. Ao meu ver, esta adaptação seria mais interessante a realização de um vídeo com uma pessoa explicando, já que estamos falando de algo mais abstrato. Segue abaixo o link da pasta com o roteiro.
> 
> https://drive.google.com/drive/folders/19fVvLZDr_oM9kHxAjkhXstPlv1f5j7mB
> 
> Atenciosamente.

Concordo com a Isabeli, acho que faz mais sentido ser uma pessoa explicando. @MaNegrao podes explicar melhor tua ideia?

**Comment by MaNegrao** [comment]
A minha ideia seria fazer animações pequenas mostrando e ampliando o texto, sublinhando, destacando, conforme a explicação na narração. No caso não deixará de ser explicado por uma pessoa em uma narração, mas o vídeo em si eu pensei em animado, ao invés do uso de slides estáticos ou apenas a gravação do texto etc. Creio que estamos falando da mesma coisa, apenas olhando de ângulos diferentes.

**Comment by MaNegrao** [comment]
@MilenaPaz2020 tu pode dar uma olhada no roteiro e decidir em conjunto com o pessoal todas as questões relacionadas :smiley:

**Comment by alessandrapedrotti** [comment]
> A minha ideia seria fazer animações pequenas mostrando e ampliando o texto, sublinhando, destacando, conforme a explicação na narração. No caso não deixará de ser explicado por uma pessoa em uma narração, mas o vídeo em si eu pensei em animado, ao invés do uso de slides estáticos ou apenas a gravação do texto etc. Creio que estamos falando da mesma coisa, apenas olhando de ângulos diferentes.

Agora eu entendi! Achei uma ótima ideia, assim conseguimos demonstrar o certo e o errado de uma maneira diferente. Meninas @isabelirk e @MilenaPaz2020 voc~es tem alguma ideia de como adicionar isso no roteiro?

**Comment by luizdameda** [comment]
Certo! Já selecionei boa parte das imagens e gravei a narração, assim que finalizar a primeira versão, mando aqui para vocês darem uma olhada e começarmos refinar o vídeo

**Comment by MilenaPaz2020** [comment]
> > A minha ideia seria fazer animações pequenas mostrando e ampliando o texto, sublinhando, destacando, conforme a explicação na narração. No caso não deixará de ser explicado por uma pessoa em uma narração, mas o vídeo em si eu pensei em animado, ao invés do uso de slides estáticos ou apenas a gravação do texto etc. Creio que estamos falando da mesma coisa, apenas olhando de ângulos diferentes.
> 
> Agora eu entendi! Achei uma ótima ideia, assim conseguimos demonstrar o certo e o errado de uma maneira diferente. Meninas @isabelirk e @MilenaPaz2020 vocês tem alguma ideia de como adicionar isso no roteiro?

Eu gosto muito da ideia de um vídeo animado, apesar de não ser uma ferramenta que eu tenha domínio ainda. Então, não descarto a possibilidade. 
Sobre a narração, fica por minha conta?

**Comment by MaNegrao** [comment]
> > > A minha ideia seria fazer animações pequenas mostrando e ampliando o texto, sublinhando, destacando, conforme a explicação na narração. No caso não deixará de ser explicado por uma pessoa em uma narração, mas o vídeo em si eu pensei em animado, ao invés do uso de slides estáticos ou apenas a gravação do texto etc. Creio que estamos falando da mesma coisa, apenas olhando de ângulos diferentes.
> > 
> > 
> > Agora eu entendi! Achei uma ótima ideia, assim conseguimos demonstrar o certo e o errado de uma maneira diferente. Meninas @isabelirk e @MilenaPaz2020 vocês tem alguma ideia de como adicionar isso no roteiro?
> 
> Eu gosto muito da ideia de um vídeo animado, apesar de não ser uma ferramenta que eu tenha domínio ainda. Então, não descarto a possibilidade.
> Sobre a narração, fica por minha conta?

Ao meu ver sim, a narração fica por tua conta. Em relação as animações, podemos pedir uma mão pro pessu @practice-uffs/con-midia e ver quais ideias podemos usar pra esse processo ficar mais facil

**Comment by isabelirk** [comment]
> 
> 
> > A minha ideia seria fazer animações pequenas mostrando e ampliando o texto, sublinhando, destacando, conforme a explicação na narração. No caso não deixará de ser explicado por uma pessoa em uma narração, mas o vídeo em si eu pensei em animado, ao invés do uso de slides estáticos ou apenas a gravação do texto etc. Creio que estamos falando da mesma coisa, apenas olhando de ângulos diferentes.
> 
> Agora eu entendi! Achei uma ótima ideia, assim conseguimos demonstrar o certo e o errado de uma maneira diferente. Meninas @isabelirk e @MilenaPaz2020 vocês tem alguma ideia de como adicionar isso no roteiro?

podemos deixar no documento, na coluna descrição, um exemplo de cada caso. Depois, quem fará a animação, faz os ajustes necessários.

**Comment by robisonjose** [comment]
> > > > A minha ideia seria fazer animações pequenas mostrando e ampliando o texto, sublinhando, destacando, conforme a explicação na narração. No caso não deixará de ser explicado por uma pessoa em uma narração, mas o vídeo em si eu pensei em animado, ao invés do uso de slides estáticos ou apenas a gravação do texto etc. Creio que estamos falando da mesma coisa, apenas olhando de ângulos diferentes.
> > > 
> > > 
> > > Agora eu entendi! Achei uma ótima ideia, assim conseguimos demonstrar o certo e o errado de uma maneira diferente. Meninas @isabelirk e @MilenaPaz2020 vocês tem alguma ideia de como adicionar isso no roteiro?
> > 
> > 
> > Eu gosto muito da ideia de um vídeo animado, apesar de não ser uma ferramenta que eu tenha domínio ainda. Então, não descarto a possibilidade.
> > Sobre a narração, fica por minha conta?
> 
> Ao meu ver sim, a narração fica por tua conta. Em relação as animações, podemos pedir uma mão pro pessu @practice-uffs/con-midia e ver quais ideias podemos usar pra esse processo ficar mais facil

Eu acredito que consigo fazer essas "animações" que o Matheus propõe. Não entendi direito como elas se encaixariam mas posso fazer.

**Comment by MaNegrao** [comment]
@robisonjose tu pode usar animações prontas que já estão no guia do programa etc. a ideia é não ser um texto estático e sim algumas animações etc. Acho que tu pegou a ideia hahah

**Comment by robisonjose** [comment]
Não consegui encontrar essas animações prontas @MaNegrao

**Comment by MaNegrao** [comment]
> Não consegui encontrar essas animações prontas @MaNegrao

Talvez eu tenha usado a nomenclatura errada, mas são icones (?) animados etc. como o que tem no site do programa. Acho que são do https://lottiefiles.com/

**Comment by robisonjose** [comment]
Certo, então quando a @MilenaPaz2020 fizer a narração, edito o áudio dela e tento fazer o vídeo.

**Comment by MilenaPaz2020** [comment]
> Certo, então quando a @MilenaPaz2020 fizer a narração, edito o áudio dela e tento fazer o vídeo (isso se ela me liberar para fazer, talvez ela queira ficar com essa issue).

Certo! Vai mais uns dias para eu fazer a narração, tenho outras tarefas na fila.

**Comment by robisonjose** [comment]
Se você quiser eu posso fazer a narração também @MilenaPaz2020, o que acha?

**Comment by isabelirk** [comment]
Boa tarde,

Eu preciso de informações um pouco mais claras sobre essa sugestão de animação, para finalizar o roteiro. Ficaria muito grata se alguém pudesse colocar mais detalhes sobre ela. Finalizando o roteiro com esses ajustes, vai facilitar e muito, o trabalho para a gravação e a animação das pessoas que irão assumir esta parte. Eu dei a ideia de fazer um exemplo comparando a forma correta com a forma errada de cada item, isso se encaixa na ideia de animação que foi sugerido aqui? Se não, como deveria ser a animação? Teriam algum vídeo como referencia  ou para exemplificar?
Atenciosamente.

**Comment by robisonjose** [comment]
> Boa tarde,
> 
> Eu preciso de informações um pouco mais claras sobre essa sugestão de animação, para finalizar o roteiro. Ficaria muito grata se alguém pudesse colocar mais detalhes sobre ela. Finalizando o roteiro com esses ajustes, vai facilitar e muito, o trabalho para a gravação e a animação das pessoas que irão assumir esta parte. Eu dei a ideia de fazer um exemplo comparando a forma correta com a forma errada de cada item, isso se encaixa na ideia de animação que foi sugerido aqui? Se não, como deveria ser a animação? Teriam algum vídeo como referencia ou para exemplificar?
> Atenciosamente.

Eu bem que queria te responder, mas também não entendi 100%. Acho que o @MaNegrao vai te responder melhor.

**Comment by MilenaPaz2020** [comment]
> Se você quiser eu posso fazer a narração também @MilenaPaz2020, o que acha?

Pode ser. Eu vi que os Podcast do Garoa de Ideias ficam com o áudio bem bacana! Como você faz a captação?

**Comment by robisonjose** [comment]
Com o celular mesmo, deixo ele paradinho, coloco uma espuma no microfone pra não ficar dando sopro e depois edito no audacity. Mas agora peguei um microfone de fato, espero que fique bom também (o que é difícil, em geral os microfones dos celulares são melhores que esses microfones baratos que eu compro).

**Comment by MaNegrao** [comment]
Sim, a animação seria basicamente isso entre comparações de formas de escrita só que animados, um vídeo base pode ser esse https://www.youtube.com/watch?v=vqikPT3oH8o&ab_channel=Lisa%27sStudyGuides

**Comment by robisonjose** [comment]
Fiz algumas sugestões de alteração no roteiro. Acho que ficaria melhor na hora da gravação. Aguardo feedback.

**Comment by isabelirk** [comment]
Boa tarde,

Conforme as orientações passadas acima, fiz novos ajustes no roteiro, incluindo a parte da descrição do vídeo. Peço que verifiquem o mesmo.
Atenciosamente.

**Comment by thaliafriedrich** [comment]
Fiz a revisão textual do roteiro, conforme solicitado. Está muito bom, tanto o texto de narração quanto as descrições para o vídeo (bem detalhadas e criativas). Fiz apenas algumas correções gramaticais e deixei uma sugestão.

**Comment by robisonjose** [comment]
Criei uma nova issue, agora para a realização do vídeo propriamente dito.

Uma última pergunta antes de fechar essa, é necessário colocar legenda no vídeo?

**Comment by MaNegrao** [comment]
Tarefa Finalizada
