### ISSUE TITLE
Ajustar termo de direitos autoriais dos clientes baseado no retorno da procuradoria

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#215]
O termo de direitos autorais que os clientes utilizarão precisa seguir o parecer da Procuradoria Geral Federal. A gerência precisa analisar o parecer e definir o que precisa ser alterado no nosso formulário.

Mais informações serão dadas conforme desdobramento. Essa issue é para monitorarmos essas atividades.

**Comment by VIF-Franca** [comment]
#54 texto base

**Comment by Claudineia-VR** [comment]
Estou com duvidas. Se quisermos mantê-la por tempo superior a 5 anos isso precisa estar expresso no termo de sessão, porém, não sei qual tempo seria adequado.

**Comment by Dovyski** [comment]
Eu acho que podemos colocar um valor bem alto, por exemplo, 20 anos. Um número dessa magnitude deixa implícito que poderemos fazer vários usos do material. Como está no parecer da procuradoria, precisamos apenas informar um valor (ou dizer que é indefinido, que eu não gosto; prefiro 20 anos, por exemplo).

**Comment by Claudineia-VR** [comment]
Fiz uma [cópia](https://docs.google.com/document/d/1AE3XlV16hpDOv65sJ6f4g-fah_px6ZvnDMd4YBGol_o/edit) para ajustar o termo, deixei em vermelho as partes ajustadas para ficar mais fácil de encontra, aguardo feedbacks.

**Comment by Dovyski** [comment]
O documento ficou excelente, parabéns, @Claudineia-VR 👏 Eu fiz alguns pequenos ajustes. Podemos considerar essa issue finalizada.

O encaminhamento agora é colocar uma cópia desse documento em alguma pasta de documentos do programa para uso futuro. A partir de agora, todas as solicitações serão precedidas pelos solicitantes assinarem esse documento via sistema SIPAC da UFFS.

**Comment by Claudineia-VR** [comment]
Uma cópia do documento foi movida para a pasta **Materiais** na subpasta [Documentos (uso futuro)](https://drive.google.com/drive/folders/1F8wuYpllC_u4_8dJFRv_DYZgE6KA92KW).
