### ISSUE TITLE
Criação de identidade visual - Masculinidades e Saúde Entre Homens da Fronteira Sul - I

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#216]
**Demandante:** Jeferson Araujo do curso de enfermagem da UFFS

**Projeto de pesquisa guarda-chuva** --> Masculinidades e Saúde Entre Homens da Fronteira Sul - I

________________________________________________
DESCRIÇÃO DO PROJETO - Masculinidades e Saúde Entre Homens da Fronteira Sul - I

Este projeto, configurado no formato guarda-chuva, contempla diferentes projetos de pesquisa em pós-graduação (strictu e lato-sensu), bem como de iniciação científica, trabalhos de conclusão de curso e de outras naturezas que serão orientados pelo proponente. Tem por fundamentação como grande área a Enfermagem frente a discussão de cuidados a população masculina. A pesar da temática sobre homens e cuidados de saúde encontrar-se em constante expansão, evidências sobre a região da fronteira sul são escassas. A fornteira sul do pais apresenta uma cultura diversificada que reforça diversas praticas masculinizantes em relação a saúde. As identidades masculinas sofrem alterações com o fluxo de vida, a incorporação de determinados preceitos hegemônicos como a crença de ser forte, invulnerável, detentor de um corpo que não adoece, entre outros, configuram-se como ideologias que ameaçam a promoção de saúde dessa população. Portanto, conhecer as masculinidades vivenciadas pelos homens que residem nesta região de fronteira e analisar as suas relações com a promoção de saúde, certamente é um ponto de partida para a avaliação de saúde e o fortalecimento de programas aos homens como Política Nacional de Atenção Integral à Saúde do Homem e Politica Nacional de Promoção da Saúde. Destacamos a importância dos profissionais de Enfermagem no apreendizado a atenção a saúde do homem e seu contexto, numa perspectiva ampla que relacione agravos de saúde da população residente em zonas de fronteira, as politicas de saúde, suas masculinidades, sua cultura e seus significados. Assim, este projeto gurada-chuva tem por objetivo investigar as manifestações das masculinidades em homens residentes na fronteira sul do Brasil, visando analisar as relações estabelecida por estes no processo saúde e doença. Sua execução ocorrerá durante outo anos e será desenvolvido por múltiplas metodologias. Espera-se que esta pesquisa produza resultados efetivos que corroborem para o crescimento científico dos alunos, profissionais, comunidade em geral e dos membros do Grupo de Pesquisa EDUFES. Que as evidências venham subsidiar conhecimentos as demandas enfrentadas no cuidado a saúde dos homens potencializando a tomada de decisões.

Palavras-chave: Masculinidade; Saúde do Homem; Pesquisa em Enfermagem; Saúde na Fronteira; Educação em Saúde.
______________________________

O professor tem interesse que o PRACTICE crie a identidade visual para o projeto guarda-chuva, @estelavilasboas já solicitei para o demandante responder o formulário, qualquer dúvida podemos enviar e-mail para tal.

**Comment by estelavilasboas** [comment]
[Pasta.](https://drive.google.com/drive/folders/1iKLTwLrfrcxgy18do6i-1YFbi-NIic8P)

**Comment by estelavilasboas** [comment]
Primeiro esboço concluído pela @TaynaraCh . @VIF-Franca favor verificar para o envio ao solicitante.

**Comment by VIF-Franca** [comment]
Aguardando feedback do cliente.

**Comment by VIF-Franca** [comment]
`FEEDBACK DO CLIENTE `

> "...Gostei bastante da paleta de cores e a ideia adotada para a construção da identidade visual é bem significativa. Contudo, para termos opções de escolha será que teria como no lugar do lenço nós adicionarmos um chimarrão, um homem gaucho ou mesmo outro vetor simbólico da região, pois assim poderíamos ampliar o olhar para outros horizontes que envolvem a temática. O lenço é bem interessante mas ao apresentarmos em forma de laço, o conflitamos com uma identidade visual já nichada/criada pelo INCA e bem conhecida, como vc mesmo comentou, do novembro azul (o qual arremete a prevenção do câncer de próstata). Assim, se tivermos outras opções poderíamos tentar escolher uma que expressasse uma identidade única ao nosso trabalho. 
> Desde já agradeço a atenção e vós parabenizo pelo trabalho e pela excelente criatividade..."

**Comment by TaynaraCh** [comment]
sendo assim, já podemos voltar a elaborar outras alternativas, certo?

**Comment by estelavilasboas** [comment]
Sim, temos que elaborar mais alternativas para esta identidade. Lembrando que temos limite de propostas a serem enviadas, nesse caso são três.

**Comment by estelavilasboas** [comment]
@TaynaraCh acha que consegue elaborar mais uma proposta com a [paleta de cores](https://drive.google.com/file/d/1EZIcDoTBOFRIpAtvwte3_5XOgPeFItD3/view) que o solicitante aprovou? Talvez se basear nas ideias  da #223 ([pasta](https://drive.google.com/drive/folders/18wMqh9UturxHUaiSdtIw8AA9JN6t4r4g)) ?

**Comment by alessandrapedrotti** [comment]
Estou de intrometida aqui

Gostei muito da terceira opção da pasta da issue #223, a com a silhueta de uma cuia de chimarrão, ficou muito elegante.

**Comment by TaynaraCh** [comment]
> @TaynaraCh acha que consegue elaborar mais uma proposta com a [paleta de cores](https://drive.google.com/file/d/1EZIcDoTBOFRIpAtvwte3_5XOgPeFItD3/view) que o solicitante aprovou? Talvez se basear nas ideias da #223 ([pasta](https://drive.google.com/drive/folders/18wMqh9UturxHUaiSdtIw8AA9JN6t4r4g)) ?

Consigo sim!

**Comment by estelavilasboas** [comment]
Lembrando que as respostas do solicitante estão na pasta entrada dessa issue.   :)

**Comment by TaynaraCh** [comment]
Adicionei mais dois exemplos na pasta do Drive, [https://drive.google.com/drive/folders/15dLiY57tpGYe6eLZoSIbkeNbC3XMfaYx](pasta)

**Comment by alessandrapedrotti** [comment]
> Adicionei mais três exemplos na [pasta](https://drive.google.com/drive/folders/1iKLTwLrfrcxgy18do6i-1YFbi-NIic8P)

O que eu mais gostei foi o ex2-03, porém acho que pra logo redonda ficar legal, seria necessário completar a silhueta no centro, pois assim cortada passa a impressão de estar incompleta.

**Comment by estelavilasboas** [comment]
O ex3-04 e 2-03 foram os que mais gostei. E concordando com a Alessandra, eu digo que a silhueta cortada me dá um pouco de agonia :sweat_smile:

**Comment by TaynaraCh** [comment]
Corrigi a silhueta e adicionei na pasta o arquivo corrigido

**Comment by mariagelain** [comment]
conforme solicitado foram realizadas alterações na [segunda versão](https://drive.google.com/drive/folders/1bs5SC3jtXDMqczI5gTzWAnWX5MtBVmQq) e uma das opções poderá ser escolhida para ajustes finais. @VIF-Franca tu já podes encaminhar para o solicitante o arquivo.

**Comment by VIF-Franca** [comment]
@mariagelain, os arquivos já foram enviados para o cliente, aguardamos o feedback dele

**Comment by VIF-Franca** [comment]
`FEEDBACK DO CLIENTE`

> Boa noite Vinícius, Obrigado pelo retorno.
> Gostei bastante da arte que apresenta o homem gaucho com o chimarrão, acredito que representa bem o trabalho. Escolho então esta para os ajustes finais.
> Desde já agradeço pela "praticidade" e auxilio.
> Com os melhores cumprimentos,
> Jeferson S. Araújo.

**Comment by VIF-Franca** [comment]
`feedback do cliente`

> No momento, não consigo vislumbrar criativamente mudanças. Contudo se a equipe conseguir observar algo que fortaleça a criação da identidade visual, ficaria muito feliz, pois é sempre bom.

**Comment by estelavilasboas** [comment]
@TaynaraCh já pode exportar as versões em diferentes resoluções, juntamente da apresentação explicativa, e colocar na pasta saída.

**Comment by TaynaraCh** [comment]
Tudo finalizado na [pasta](https://drive.google.com/drive/u/0/folders/1FuboQob-eX9e2wSvolNMXYZcrFoZsd4d)!

**Comment by VIF-Franca** [comment]
Enviado para o CLIENTE !!!

**Comment by VIF-Franca** [comment]
Pessoal, reabria a issue segundo uma demanda do cliente. 

> Se possível, teria como você me encaminhar essa marca d'água em um arquivo em formato diferente do PDF pois ao transformar em imagem, pra divulgação em mídias sociais, o mesmo acaba perdendo a qualidade.
Com muitas felicidades pelo trabalho, cumprimento todos os colegas que colaboraram de forma direta e indireta na criação.

**Comment by TaynaraCh** [comment]
@VIF-Franca já está na pasta!

**Comment by VIF-Franca** [comment]
Enviado.
