### ISSUE TITLE
[Estúdios] Teste de gravação em Laranjeiras do Sul

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/programa#22]
Assim que todos os equipamentos estiverem devidamente instalados, é necessário realizar um teste de gravação para verificar se está tudo funcionando corretamente.

**Comment by MaNegrao** [comment]
@VIF-Franca pelo que vi esses testes foram feitos na issue #150 , logo, podemos fechar essa issue aqui?

**Comment by VIF-Franca** [comment]
@MaNegrao as instalações e testes já foram realizados no laboratório de mídias do campus Laranjeiras do Sul.
