### ISSUE TITLE
Revisão de equipamento

### ISSUE THREAD

**Issue by mariagelain** [practice-uffs/programa#220]
O monitor que eu uso está com problemas, peço para que isso seja revisado @Dovyski @lcaimi

**Comment by Dovyski** [comment]
@lcaimi @phdmauricio precisamos fazer um levantamento sobre máquinas disponíveis para uso no programa. O Nedilso não comentou que teríamos algumas máquinas à disposição?

**Comment by VIF-Franca** [comment]
@mariagelain seu monitor está melhor? Podemos fechar essa issue ?

**Comment by mariagelain** [comment]
não mas acho que podemos fechar mesmo assim.
