### ISSUE TITLE
Edição de vídeo de Apresentação - PPGE

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#221]
O vídeo está na [pasta do drive](https://drive.google.com/drive/folders/1k3SDwRCB_eQ99vV-xPEUWqRGm8I28FTI)

O solicitante quer que o video tenha os seguintes passos

- [x] Edição básica
- [x] Inserir vinhetas da PPGE antes e depois ([Link aqui](https://drive.google.com/drive/folders/1sx34HeEbVhIiPdrw-xbfuolkhxUI7cWO))
- [x] Produzir e Inserir legendas

**Comment by luizatonial** [comment]
Devo inserir a vinheta do PRACTICE também?

**Comment by MaNegrao** [comment]
> Devo inserir a vinheta do PRACTICE também?

Sim, coloca semelhante aos videos de letras

**Comment by luizatonial** [comment]
O vídeo já finalizado encontra-se na [pasta](https://drive.google.com/drive/folders/1wKUupERnWDX79dGmmjqBLkFaQnted0qD). 
Peço que encaminhem ao solicitante para revisão.

**Comment by MaNegrao** [comment]
> O vídeo já finalizado encontra-se na [pasta](https://drive.google.com/drive/folders/1wKUupERnWDX79dGmmjqBLkFaQnted0qD).
> Peço que encaminhem ao solicitante para revisão.

Retornarei aos solicitantes para que façam revisão ;)

**Comment by MaNegrao** [comment]
@luizatonial Eu enviei ao solicitante para as alterações, mas já quero acrescentar um erro meu.

Onde tá escrito "Tema do Vídeo" na vinheta, é pra ter o tema do vídeo, que nesse caso é "Conhecendo o Programa". 

Perdão pelo vacilo hehe.

@vini2reis tu pode enviar na pasta da vinheta ou na pasta dessa issue aqui mesmo, o vídeo editável da vinheta?

**Comment by vini2reis** [comment]
> @luizatonial Eu enviei ao solicitante para as alterações, mas já quero acrescentar um erro meu.
> 
> Onde tá escrito "Tema do Vídeo" na vinheta, é pra ter o tema do vídeo, que nesse caso é "Conhecendo o Programa".
> 
> Perdão pelo vacilo hehe. Assim que chegar as alterações do cliente (Caso houver), já soluciona esse probleminha
> 
> @vini2reis tu pode enviar na pasta da vinheta ou na pasta dessa issue aqui mesmo, o vídeo editável da vinheta?

Inclusive ia comentar isso e tinha esquecido
Vou colocar o arquivo do shotcut la na pasta e tbm a vinheta editada ja com o tema para a luiza so colocar no vídeo

**Comment by vini2reis** [comment]
Os arquivos Shotcut estão na pasta saída da issue #116 
E a vinheta para ser usada nesse vídeo está na pasta entrada dessa issue

**Comment by MaNegrao** [comment]
O cliente retornou com os seguintes ajustes (um deles é aquele que já tínhamos comentado)

> Vamos precisar de 2 ajustes:
> 1º inserir o tema do vídeo na vinheta inicial...Substituir a escrita "tema do vídeo" por "Conhecendo o Programa"
> 2º Tirar a divulgação do PRACTICE após a vinheta inicial...ficou estranho. Ela já consta no final do vídeo....pode ser?

**Comment by luizatonial** [comment]
@MaNegrao utilizo o vídeo que o @vini2reis havia finalizado, com o título "Apresentação - PPGE" ou troco por "Conhecendo o Programa", que foi sugerido?

**Comment by MaNegrao** [comment]
> @MaNegrao utilizo o vídeo que o @vini2reis havia finalizado, com o título "Apresentação - PPGE" ou troco por "Conhecendo o Programa", que foi sugerido?

Faz como o cliente pediu, pra evitarmos ter que trocar novamente

**Comment by vini2reis** [comment]
> O cliente retornou com os seguintes ajustes (um deles é aquele que já tínhamos comentado)
> 
> > Vamos precisar de 2 ajustes:
> > 1º inserir o tema do vídeo na vinheta inicial...Substituir a escrita "tema do vídeo" por "Conhecendo o Programa"
> > 2º Tirar a divulgação do PRACTICE após a vinheta inicial...ficou estranho. Ela já consta no final do vídeo....pode ser?

@MaNegrao acho que esse segundo ponto tem q perguntar pata o Caimi, nao?

**Comment by luizatonial** [comment]
> > O cliente retornou com os seguintes ajustes (um deles é aquele que já tínhamos comentado)
> > > Vamos precisar de 2 ajustes:
> > > 1º inserir o tema do vídeo na vinheta inicial...Substituir a escrita "tema do vídeo" por "Conhecendo o Programa"
> > > 2º Tirar a divulgação do PRACTICE após a vinheta inicial...ficou estranho. Ela já consta no final do vídeo....pode ser?
> 
> @MaNegrao acho que esse segundo ponto tem q perguntar pata o Caimi, nao?

Alguns outros vídeos que eu fiz seguiam este modelo, com a vinheta do PRACTICE no fim do vídeo, apenas.

**Comment by luizatonial** [comment]
Caso não existam mais revisões, o vídeo finalizado encontra-se na [pasta de saída.](https://drive.google.com/drive/folders/1wKUupERnWDX79dGmmjqBLkFaQnted0qD)

**Comment by MaNegrao** [comment]
> > O cliente retornou com os seguintes ajustes (um deles é aquele que já tínhamos comentado)
> > 
> > > Vamos precisar de 2 ajustes:
> > > 1º inserir o tema do vídeo na vinheta inicial...Substituir a escrita "tema do vídeo" por "Conhecendo o Programa"
> > > 2º Tirar a divulgação do PRACTICE após a vinheta inicial...ficou estranho. Ela já consta no final do vídeo....pode ser?
> 
> @MaNegrao acho que esse segundo ponto tem q perguntar pata o Caimi, nao?

Na minha visão não tem problema, mas por via das dúvidas enviei a dúvida no grupo

**Comment by MaNegrao** [comment]
eu mandei um e-mail para o solicitante pra verificar se podemos encerrar ou não

**Comment by MaNegrao** [comment]
Vídeo aprovado e finalizado
