### ISSUE TITLE
Criação de tutorial simples para conexão remota

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#222]
O objetivo dessa issue é produzir um video curto interno que explique como baixar o [Remote Desktop](remotedesktop.google.com) do Googe para conectar-se remotarmente nos PC's do PRACTICE. Seguindo a issue #129 
Devemos usar a conta do PRACTICE do gmail para fazer esse login

O vídeo deve conter:

- Instruções de downlaod e instalação do software
- Como criar e requisitar um login para acesso ao pc
- Como acessar e utilizar o pc remotamente.

As etapas são: 

- [x] Criar um roteiro simples com cada parte e cada instrução do video

- [x] Gravar o video com tela e cam

- [x] Editar o vídeo, inserindo vinheta do practice, créditos, etc.

[Pasta Drive](https://drive.google.com/drive/folders/1eRT976CJzolEUKmrPX1KxpL1IDQQGH3M)

**Comment by MaNegrao** [comment]
Eu e @luizatonial fomos colocar em prática esse metodo de conexão, mas não conseguimos fazer funcionar, portanto precisamos definir ainda qual vai ser a ferramenta usada, nós usamos o anydesk, mas ele só tem uma versão gratuita. Eu vou tentar solucionar essa questão do microsoft remote desktop, caso não conseguir a gente vai pensando em outra forma de realizar.

**Comment by robisonjose** [comment]
@practice-uffs/con-midia Caso alguém se disponha a fazer o roteiro eu posso fazer o vídeo.

**Comment by MaNegrao** [comment]
Eu vou demonstrar como usa na capacitação, basicamente vamos usar o remote desktop da google, então no tutorialzinho só vamos ensinar como baixar, configurar no pc e tá tudo ótimo

**Comment by robisonjose** [comment]
@MaNegrao tu faz o roteirinho pra eu gravar o vídeo? Ou se tu quiser tu mesmo gravar e eu edito.

**Comment by MaNegrao** [comment]
> @MaNegrao tu faz o roteirinho pra eu gravar o vídeo? Ou se tu quiser tu mesmo gravar e eu edito.

Vou fazer o roteirinho e dai tu toca, eu acho que não vou conseguir gravar.

**Comment by MaNegrao** [comment]
@robisonjose  Eu fiz um roteiro inicial, mas é bem nesses moldes simples, não necessariamente as falas tem que ser dessa forma, então é bem tranquilo. Vê e me diz o que tu acha?

**Comment by robisonjose** [comment]
Essa issue vai ser postada em algum lugar? Achei que seria um vídeo totalmente interno @manegrao

**Comment by MaNegrao** [comment]
A ideia é ser multifuncional, se tu acha que não precisa ser externo tudo certo.

**Comment by robisonjose** [comment]
Por mim tanto faz, é que gravei sem a cam pensando que seria interno, ai teria que refazer.

**Comment by MaNegrao** [comment]
É um vídeo curtinho, acho que não tem problema se não tiver cam. Se tu não curtir o resultado final e quiser refazer tudo certo, mas também tá tudo certo se não tiver. O importante é a clareza nas informações e no passo a passo

**Comment by robisonjose** [comment]
Primeira versão do vídeo está [aqui](https://drive.google.com/drive/folders/1pqlfmYMS0uGY84-lZZUUq_EFl5uwW6cj). Aguardo feedback.

**Comment by MaNegrao** [comment]
Eu achei excelente, não tem segredo, o vídeo era pra ser simples mesmo. Acho que podemos finalizar

**Comment by robisonjose** [comment]
Fechou então.

**Comment by MaNegrao** [comment]
O vídeo está na pasta "Vídeos" dentro da pasta "Materiais" e pode ser linkado em qualquer tarefa quando precisar. Além disso deve entrar no nosso calendario de publicações curtas

**Comment by robisonjose** [comment]
Eu fui comentar desse vídeo para outro bolsista e percebi que os créditos estavam com a qualidade baixa. Já editei o vídeo para melhorar isso e postei nas pastas.

**Comment by MaNegrao** [comment]
Eu to com dificuldades com os serviços do google, mas assim que eu cosneguir eu altero sim. Além de te dar permissão na pasta.

**Comment by MaNegrao** [comment]
feito e organizado, iremos usar a pasta "biblioteca de conteudos"
