### ISSUE TITLE
Brainstorm de logomarca - Identidade Visual de Masculinidades e Saúde Entre Homens da Fronteira Sul - I

### ISSUE THREAD

**Issue by estelavilasboas** [practice-uffs/programa#223]
Recebemos a demanda de criar uma identidade visual para o projeto Masculinidades e Saúde Entre Homens da Fronteira Sul - I. A criação dessa issue tem como objetivo agrupar ideias sobre o estilo e símbolo que iremos inserir na logomarca. Devem ser feitos esboços da logomarca seguindo as seguintes características selecionadas pelo solicitante no formulário de identidade visual:
* Conter um símbolo, compondo ou não a escrita;
* Preferência por fontes médias e mais grossas;
* Popular, extrovertida, formal, vibrante, séria;
* características que NÃO descrevem: Delicada, leve, romântica;
* "Imagens que lembre características masculinas regionais (talvez um chimarrão)";
* Preferência por cores contrastantes/complementares e cores frias;

Os esboços devem ser colocados na [pasta do drive da issue](https://drive.google.com/drive/folders/18wMqh9UturxHUaiSdtIw8AA9JN6t4r4g). Podem ser desenhados em um papel e a foto anexada na pasta, ou em um software de desenho de sua preferência. Lembrando que é um esboço de uma issue "brainstorm", feita para reunir ideias e diferentes visões sobre o projeto. Não deve ser criado algo elaborado que demore horas para ser feito. Após a formulação dessas ideias, elas serão avaliadas e discutidas pela equipe, para então produzir o esboço que será enviado para aprovação do cliente. O que será realizado nessa issue não será enviado para o cliente, pois o que é produzido tem como objetivo a discussão interna. 
As respostas do formulário preenchido pelo solicitante estão [disponíveis nesse arquivo](https://drive.google.com/drive/folders/1awwgiXwuBcZBlLiDifookkWGUNQveG0f).

**Comment by TaynaraCh** [comment]
Adicionei algumas ideias na pasta

**Comment by ricardopatrik** [comment]
Adicionei algumas alternativas.
