### ISSUE TITLE
Manual de Identidade Visual do PRACTICE - Seção I

### ISSUE THREAD

**Issue by estelavilasboas** [practice-uffs/programa#224]
Tendo em vista que o programa possui uma grande quantidade e diversidade de materiais, reconhecemos a necessidade de um manual de identidade visual. 
O manual será realizado em partes se baseando no [Manual de Identidade Visual da UFFS](https://drive.google.com/file/d/1hyF2RGJ91PWw649JcJQ-oGmkPwJbFZxh/view) que já está na pasta da [issue](https://drive.google.com/drive/u/0/folders/1VZ1fYMIuxQfJq2bt430bVuUb_Hkgv6B9).
Nessa primeira seção, vamos abordar a **utilização da logomarca, símbolo, marca d'água e cores**. Devemos detalhar como e quando utilizar cada uma, margens padrão e a utilização das cores.
Toda a equipe trabalhará nesse manual em conjunto, de modo que todos possam, devam sugerir e adicionarcomponentes que possam estar faltando ou estejam mal especificados na identidade visual.
O manual será realizado da mesma forma que os panfletos e cartilhas que já produzimos, pois em breve o projeto terá a contribuição dos demais integrantes da con-conteúdo.

**Comment by ricardopatrik** [comment]
Coloquei algumas informações, sobre o texto de apresentação a gente cria ou o pessoal da redação?

**Comment by estelavilasboas** [comment]
> Coloquei algumas informações, sobre o texto de apresentação a gente cria ou o pessoal da redação?

Somos nós vamos escrever todos os textos. Posteriormente, o que for escrito será enviado para revisão.

**Comment by estelavilasboas** [comment]
- Deixei considerações novas nos comentários.
- Cuidem com as nomenclaturas "logomarca", "logotipo" e "símbolo".

**Comment by estelavilasboas** [comment]
- Descrever a utilização do padrão cromático conforme informado nos comentários do documento;
- Manter o padrão definido no mestre do arquivo em todas as páginas;
- Refazer as imagens da página 2 do padrão cromático conforme o descrito nos comentários, assim como descrever usa utilização;
- Pensar em opções de rediagramação da página de paletas de cores. Vocês podem duplicar a página várias vezes e deixar várias propostas, e posteriormente a melhor será selecionada;
- Por favor, verificar os arquivos da pasta. Há duas cópias do Manual de Identidade Visual da UFFS na [pasta da issue](https://drive.google.com/drive/u/0/folders/1VZ1fYMIuxQfJq2bt430bVuUb_Hkgv6B9) e não vejo a necessidade de tantas cópias do mesmo arquivo (nesse caso).

**Comment by ricardopatrik** [comment]
Entendido.
Tem a logo do practice em arquivo editável?

**Comment by estelavilasboas** [comment]
> Entendido.
> Tem a logo do practice em arquivo editável?

Infelizmente não temos ainda. Não precisa se preocupar muito com a qualidade da imagem em si no momento, pois essa vai apenas para o manual. Logo a logomarca será exportada com as variações certas e em alta qualidade.

**Comment by ricardopatrik** [comment]
Coloquei uma alternativa onde tinha a onda na numeração das páginas, pois a anterior achei que pegava muito espaço.

**Comment by estelavilasboas** [comment]
É ótimo que sintam essa vontade de adaptar o que foi feito e de expressar a criatividade, fico muito feliz com isso, no enquanto gostaria de salientar que esta não é a proposta da issue.  A proposta é coompreender a identidade visual do programa durante a produção do manual. _Assim como dito no comentário anterior, deve-se manter o padrão definido no mestre do arquivo do Apresentações._ 
Este mestre possui três opções principais de paginação: numeração inferior direita, numeração inferior esquerda e sem numeração. Isso foi criado justamente para melhor se adequar com a quantidade de conteúdo. 
A ideia é que o manual seja sucinto e direto, de forma que imagens ilustrativas sejam o foco principal.

**Comment by thaliafriedrich** [comment]
Fiz a revisão textual. Deixei comentários no arquivo.

**Comment by estelavilasboas** [comment]
Eu simplifiquei a parte da paleta de cores, pois, após uma rápida releitura, achei que as descrições eram desnecessárias.
Também alterei os pontos comentados.

**Comment by thaliafriedrich** [comment]
Fiz uma nova leitura de revisão e mais algumas pequenas alterações, modificando umas palavras. Podem conferir novamente e, então, a revisão textual está concluída.

**Comment by estelavilasboas** [comment]
Revisões concluídas.
Serão realizados ajustes na [Seção I ](https://drive.google.com/drive/u/0/folders/11_gxt7m1hence7Rs1TLQXYK3QHQF8rai)com o início da Seção II. Esses ajustes também serão realizados devido a problemas de coloração abordados pela equipe con-mídia, compreendendo assim uma pequena revisão na identidade visual.
