### ISSUE TITLE
Criar nova página de créditos para materiais

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#227]
É necessário desenvolver uma nova página de créditos para os materiais textuais ( e talvez uma página padrão para vídeos) contendo os nomes de todos os atuais integrantes do programa.

Pode ser feita uma divisão por equipes ou função, desde que se mantenha tudo em uma única página.

**Comment by estelavilasboas** [comment]
[Pasta do drive](https://drive.google.com/drive/folders/19dBrnh9Y8-5wc9i30A9BbQ8n4rvgZ0_j)

**Comment by estelavilasboas** [comment]
Feita nova página de créditos para os materiais textuais.
No arquivo, encontra-se duas versões, sendo que nas duas primeiras "páginas" os únicos elementos editáveis são os nomes dos integrantes.

**Comment by alessandrapedrotti** [comment]
As duas opções ficaram muito bonitas, porém acho que a primeira vai nos servir melhor. Ela ficou mais clean e como temos muitos nomes pra por na página, acho que a borda grossa da segunda opção deixa a página muito carregada.

**Comment by estelavilasboas** [comment]
Conversando com a @mariagelain, nos questionamos sobre a necessidade do nome completo de todos os integrantes e a possibilidade de utilização de nome social.  Por exemplo, ao invés de "Estela Maris Vilas Boas" seria "Estela Vilas Boas". Dessa forma, também otimizamos espaço.
Se assim for possível, creio que devemos criar uma issue em que os integrantes possam dizer como preferem seus nomes na página de créditos.

**Comment by alessandrapedrotti** [comment]
> Conversando com a @mariagelain, nos questionamos sobre a necessidade do nome completo de todos os integrantes e a possibilidade de utilização de nome social. Por exemplo, ao invés de "Estela Maris Vilas Boas" seria "Estela Vilas Boas". Dessa forma, também otimizamos espaço.
> Se assim for possível, creio que devemos criar uma issue em que os integrantes possam dizer como preferem seus nomes na página de créditos.

Issue para os nomes sociais criada #245.

**Comment by mariagelain** [comment]
página de créditos está finalizada e na [pasta](https://drive.google.com/drive/folders/1Xq1EN0L1Je7ZpWNmX0q3S-xPsaPMcy-Q)

**Comment by VIF-Franca** [comment]
#245 está finalizada
