### ISSUE TITLE
Edição vídeo curto - Homenagem aos Servidores UFFS - Chapecó - 27/10

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#228]
Como conversamos, vamos analisar a possibilidade de realizar a demanda, nesse caso eu já inseri todos os materiais enviados na pasta de entrada, creio que é possível fazer. @luizatonial o veredito é teu.

[Pasta Drive](https://drive.google.com/drive/folders/1ayDoAyi8HhS_eo_-eNjeNdb-IkSM3ffb)

**Comment by luizatonial** [comment]
O vídeo finalizado encontra-se na [pasta de saída.](https://drive.google.com/drive/folders/1cJzMtrj48j2qQ46QSFClo98uAd-t6KqN)

**Comment by MaNegrao** [comment]
Enviei para o solicitante para revisão

**Comment by MaNegrao** [comment]
O vídeo foi aprovado pelo cliente. :D

**Comment by Dovyski** [comment]
Parabéns pela conclusão desse vídeo em um tempo tão curto! 🥳🚀
