### ISSUE TITLE
Live Liga de Investimentos da UFFS - 28/10 - 17h

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#229]
Live solicitada pela liga de investimentos em laranjeiras do sul

Ministrante(s) | Matheus 			Andrade Ataide (aluno do campus Laranjeiras do Sul/PR),  			 			Vinicius 			França Alves (aluno do campus Laranjeiras do Sul/PR) e Igor 			Matheus da Silva Pinto (aluno do campus Laranjeiras do Sul/PR)
-- | --
Mediador | Matheus 			Andrade Ataide (aluno do campus Laranjeiras do Sul/PR),  			 			Vinicius 			França Alves (aluno do campus Laranjeiras do Sul/PR) e Igor 			Matheus da Silva Pinto (aluno do campus Laranjeiras do Sul/PR)

O Vinicius França assume a demanda

**Comment by VIF-Franca** [comment]
Perfeito irei participar como apoio técnico.

**Comment by VIF-Franca** [comment]
Link da live realizada. 

https://youtu.be/J6Z0x_Zx9C0

**Comment by VIF-Franca** [comment]
OBSERVAÇÃO SOBRE QUALIDADE

Tive uma experiência horrível com a o Google Meet, travou muito, baixou muito a qualidade da live. Deixaria como sugestão nunca mais usar o meet para live rsrsrs.

**Comment by MaNegrao** [comment]
> OBSERVAÇÃO SOBRE QUALIDADE
> 
> Tive uma experiência horrível com a o Google Meet, travou muito, baixou muito a qualidade da live. Deixaria como sugestão nunca mais usar o meet para live rsrsrs.

Como eu havia comentado, o meet capa muuuuuuito a qualidade hahaha. o webex tem uma consistência bem mais razoável

**Comment by VIF-Franca** [comment]
Sim, o problema é que o palestrante não tinha o webex baixado.
