### ISSUE TITLE
[Labels] Labels para as issues

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/programa#23]
Todas as issues terão uma certa prioridade de acordo com a urgência da tarefa a ser executada. Essas prioridades devem ser criadas em forma de labels que são associadas às issues e permitem que as prioridades sejam facilmente visualizadas. A labels a serem criadas estão a seguir:

- P0 - prioridade imediata (pare o que está fazendo e foque nisso)
- P1 - prioridade alta
- P2 - prioridade regular
- P3 - prioridade baixa
- P4 - prioridade muito baixa

Cada label também possui uma cor, então aconselha-se que as cores sigam uma escala e que também se remetam à urgência daquela tarefa. Por exemplo, P0 poderia ser vermelho ou preto, enquanto P4 poderia ser azul claro.

Além disso, também é necessário criar labels para cada equipe de trabalho ou área de atuação, como texto-imagem, audio-video, etc. Nesse caso, as cores não importam muito, mas é conveniente não repetí-las.

**Comment by MaNegrao** [comment]
Labels já estão criadas e em utilização
