### ISSUE TITLE
Formulário pesquisa de satisfação do cliente 

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#230]
Conforme o debatido em reunião, deverá ser elabora um formulário para controle de qualidade dos produtos e serviços do PRACTICE.  Penso em fazermos ou um formulário com diferentes sessões para cada serviço ou um formulário para cada serviço. De qualquer modo, é necessário que o formulário considere:

- [x] Serviços de edição de áudio;
- [x] Serviços de edição de vídeo;
- [x] Suporte de transmissões ao vivo;
- [x] Elaboração de identidade visual;
- [x] Revisão e diagramação de textos;
- [x] Espaço para sugestões;

O formulário pode abordar questões de sim ou não, notas para os serviços, prazos e revisão. Acredito que, para os nossos interesses, seria melhor que os "clientes" pudessem classificar a satisfação deles com os produtos, assim fica mais fácil de visualizarmos os resultados (e eventualmente transformar essas respostas em gráficos, etc).

Vale ressaltar que já foram criados formulários de solicitação tanto para os serviços da equipe de mídia, como para a elaboração de identidades visuais, é importante que, no formulário de qualidade, seja possível estabelecer relações com esses questionários anteriores.

**Comment by VIF-Franca** [comment]
Irei criar um documento doc para irmos desenhando o escopo do questionário.

[Link do documento. ](https://docs.google.com/document/d/1KvNg_ivjvX4YW2_YbVChPzPRO8ommY5moVZN4xTfT6c/edit)

**Comment by VIF-Franca** [comment]
Realizei uma prévia do questionário sobre o `PRIMEIRO BLOCO` (questões genéricas, que deverá conter em todos os questionários) e o `SEGUNDO BLOCO` (já criei sobre os produtos e serviços ofertados pela equipe do con-midia), neste ne segundo bloco são questões especificas do produto e serviço. 

@alessandrapedrotti  caso queria dar alguma sugestão pode deixar na issue.

**Comment by alessandrapedrotti** [comment]
Já fiz a primeira leitura e está muito bom! Fiz apenas algumas adições (que deixei em vermelho) de opções de voto.
Se for necessário, podes consultar a @mariagelain para construir o questionário dos serviços de conteúdo.

**Comment by VIF-Franca** [comment]
Pessoal, finalizei a primeira versão do instrumentos de pesquisa de satisfação, deixo uma breve explicação:

Na `PRIMEIRA PARTE` encontra-se questões genéricas, que deverá conter em todos os questionários e todas as respostas serão obrigatórias; 

Já na `SEGUNDA PARTE` deve contemplar os nossos produtos e serviços em especifico, nesse bloco o cliente deverá receber apenas as questões que convergem com os produtos e serviços executados pelo PRACTICE;

Por fim a `TERCEIRA PARTE` que são alguns aspectos que irá nos auxiliar para elaborar "número" para apresentar para a comunidade acadêmica em nosso relatório trimestral.

Pediria que, @alessandrapedrotti @estelavilasboas @mariagelain @MaNegrao @Dovyski @lcaimi @phdmauricio avaliem e deixe suas sugestões.

**Comment by alessandrapedrotti** [comment]
Documento lido. Fiz algumas alterações textuais (principalmente pontuação).
Achei o texto muito bom e completo, acredito que possas passar para a etapa de transposição para o google forms.

Minha única questão é com a pergunta 20. Não sei se é uma pergunta adequada, pois deixa em aberto uma questão bastante problemática. Gostaria que os coordenadores opinassem sobre ela.

**Comment by mariagelain** [comment]
fiz apontamentos quanto as duas primeiras questões e também quanto a questão 10 da identidade visual, e acho que ficaria mais coeso se as avaliações fossem em apenas uma ordem, ex: + positivo para o - positivo, em todas as questões de avaliação.

**Comment by VIF-Franca** [comment]
Perfeito, realizei as alterações propostas pela @alessandrapedrotti @mariagelain  e @Dovyski.

@MaNegrao e @estelavilasboas poderiam dar uma olhada sobre as devidas ilhas

**Comment by VIF-Franca** [comment]
> fiz apontamentos no documento quanto as duas primeiras questões e também quanto a questão 10 da identidade visual, e acho que ficaria mais coeso se as avaliações fossem em apenas uma ordem, ex: + positivo para o - positivo, em todas as questões de avaliação.

@mariagelain em relação à sua ultima sugestão sobre a sequência das alternativas da "mais positiva" para a "menos positiva" gostaria que sanasse uma dúvida: você sugestionou que todas as questões possuam alternativas padrão ?

>1) Ex: Muito bom - bom - indiferente - ruim - muito ruim

   2) Ou seria apenas para alocar as alternativas já existentes nessa ordem: da "mais positiva" para "menos positiva" ?

Caso seja a opção 1), entendo e essa ordem já consta em algumas questões, porém, em outras questões fez-se necessário inserir alternativas que façam alusão a situações reais que podem ocorrer nos eventos, para que caso o respondente se identifique com tal situação consiga responder adequadamente. Entretanto todas as questões terão cinco alternativas, seguindo assim a metodologia de escala likert. 

Caso seja a opção 2), irei revisá-las e colocá-las nessa ordem da "mais positiva" para a "menos positiva".

**Comment by MaNegrao** [comment]
Tenho alguns apontamentos:

Acho que ao invés de _transmissao de evento ao vivo_ pode ser só _transmissao ao vivo_

Na questão de internet ao invés de conexão do PRACTICE pode ser: _Estabilidade da conexão da live_

**Comment by estelavilasboas** [comment]
Após as alterações realizadas (principalmente na questão 10) e após uma conversa com o design, creio que, no momento, não tenhamos mais sugestões para serem feitas.

**Comment by VIF-Franca** [comment]
Irei adicionar as perguntas em um google forms...

**Comment by alessandrapedrotti** [comment]
Assim que o formulário for concluído, pensaremos na estratégia de disparada para os 'clientes'.

**Comment by VIF-Franca** [comment]
Elaborei o texto abaixo para incluir na descrição do questionário:

Você acabou de receber um formulário produzido pelo  Programa de Ampliação e Consolidação de Tecnologias e Inovação no Contexto Educacional - PRACTICE, o objetivo desse questionário é captar algumas informações sobre suas primeiras experiências com o programa, captar informações com o produto e/ou serviço que recebeu de nossa equipe e por fim, captar algumas informações sobre sugestões e melhorias. 

Destacamos que sua resposta é imprescindível para que o PRACTICE permaneça em evolução constante aprimorando os produtos e serviços prestados atualmente e vislumbrando novas frentes de atuação, lembre-se que você faz parte da nossa amada comunidade acadêmica da UFFS. 

Ao iniciar a resposta do questionário você encontrará três blocos a serem respondidos, sendo eles: 
O primeiro INFORMAÇÕES GERAIS contendo 10 questões de múltiplas escolhas, no segundo bloco serão perguntas ESPECIFÍCAS sobre o produto ou o serviço que foi solicitado por você com 04 questões de múltipla escolha e 01 questão discursiva e por fim na terceira seção SUGESTÕES DE MELHORIAS com apenas 01 questão dissertativa e 03 questões de múltiplas escolhas.

*As respostas serão analisadas em conjunto e não individualmente, onde serão utilizadas apenas para a apresentação dos resultados obtidos ao longo do período de existência do PRACTICE.
** Estima-se que levará cerca de 8 minutos para concluir a resposta do questionário.
*** Não haverá forma de identificar o respondente, garantindo assim o sigilo total.

**Comment by VIF-Franca** [comment]
`PESSOAS QUE RESPONDERÃO O QUESTIONARIO COMO PRÉ-TESTE`


Link para acessar o questionário: https://forms.gle/aN1rpCHDCt18reNYA 


Preciso que algumas pessoas respondam ao questionário, a respostas de vocês serão cruciais para nos apresentar um _feedback_ e realizar algum ajustes antes de enviar para os clientes, peço para os seguintes bolsistas responderem: 

> @pedroamaximowski 
> @MilenaPaz2020 
> @luizatonial 
> @robisonjose 
> @morgana-mo 
> @anacarolinamorigi 
> @TaynaraCh 
> @thaliafriedrich 
> @ricardopatrik

 
Deixem o feedback de vocês aqui na issue. 

OBS: Lembre-se vocês serão clientes fictícios!!!

**Comment by alessandrapedrotti** [comment]
> **Elaborei o texto abaixo para incluir na descrição do questionário:**
> 
> Você acabou de receber um formulário produzido pelo Programa de Ampliação e Consolidação de Tecnologias e Inovação no Contexto Educacional - PRACTICE, o objetivo desse questionário é captar algumas informações sobre suas primeiras experiências com o programa, captar informações com o produto e/ou serviço que recebeu de nossa equipe e por fim, captar algumas informações sobre sugestões e melhorias.
> 
> Destacamos que sua resposta é imprescindível para que o PRACTICE permaneça em evolução constante aprimorando os produtos e serviços prestados atualmente e vislumbrando novas frentes de atuação, lembre-se que você faz parte da nossa amada comunidade acadêmica da UFFS.
> 
> Ao iniciar a resposta do questionário você encontrará três blocos a serem respondidos, sendo eles:
> O primeiro INFORMAÇÕES GERAIS contendo 10 questões de múltiplas escolhas, no segundo bloco serão perguntas ESPECIFÍCAS sobre o produto ou o serviço que foi solicitado por você com 04 questões de múltipla escolha e 01 questão discursiva e por fim na terceira seção SUGESTÕES DE MELHORIAS com apenas 01 questão dissertativa e 03 questões de múltiplas escolhas.
> 
> *As respostas serão analisadas em conjunto e não individualmente, onde serão utilizadas apenas para a apresentação dos resultados obtidos ao longo do período de existência do PRACTICE.
> ** Estima-se que levará cerca de 8 minutos para concluir a resposta do questionário.
> *** Não haverá forma de identificar o respondente, garantindo assim o sigilo total.
> 
> **@alessandrapedrotti o que você acha?**

Fiz algumas alterações no texto:


Você acaba de receber um formulário produzido pelo Programa de Ampliação e Consolidação de Tecnologias e Inovação no Contexto Educacional - PRACTICE, com o objetivo de captar algumas informações sobre suas primeiras experiências com o programa, sua experiência com o produto e/ou serviço que recebeu de nossa equipe e, também, possíveis sugestões de melhorias.
Destacamos que sua resposta é imprescindível para que o PRACTICE permaneça em evolução constante, aprimorando os produtos e serviços prestados atualmente e vislumbrando novas frentes de atuação. Lembre-se que você faz parte da nossa amada comunidade acadêmica da UFFS, portanto, sua opinião sempre será importante!
Ao iniciar a resposta ao questionário, você encontrará três blocos a serem respondidos, sendo eles:
O primeiro bloco contém 10 questões de múltipla escolha a respeito de informações gerais; o segundo bloco contém perguntas especificas sobre o produto ou o serviço que você solicitou, com 04 questões de múltipla escolha e 01 questão discursiva e, por fim, temos a terceira seção, que é o espaço para sugestões de melhorias com apenas 01 questão dissertativa e 03 questões de múltipla escolha.
*As respostas serão analisadas em conjunto e não individualmente e serão utilizadas apenas para a apresentação dos resultados obtidos ao longo do período de existência do PRACTICE.
** Estima-se que levará cerca de 8 minutos para concluir a resposta do questionário.
*** Não haverá forma de identificar o respondente, garantindo assim o sigilo total.

**Comment by robisonjose** [comment]
**GERAL**

Acredito que poderia ser padronizado a ordem das opções. Talvez iniciando com a "melhor" opção e indo para a "pior". Também poderia ser padronizado quantas opções de números aparecem quando há a possibilidade de escolher uma "nota". Creio que de 0 a 5 seja melhor pois de 0 a 10 fica desconfigurado quando é usado no celular.

**PRIMEIRO BLOCO**

PERGUNTA 5: Está escrito "muito insatisfeitos", acredito que deveria ser "muito insatisfeito".
PERGUNTA 8: Parece que faltou um pedaço da pergunta, pois as respostas não batem com a "finalização" da pergunta.
PERGUNTA 10: Será que não seria interessante marcar mais de uma opção? Principalmente quando a demanda é de um projeto grande, como foram os vídeos de letras.

**SEGUNDO BLOCO** 

**APOIO TÉCNICO EM TRANSMISSÃO DE EVENTO AO VIVO:**

PERGUNTA 2: Acredito que poderia trocar o "05" para "5" para que fique padronizado.

**EDIÇÃO DE VÍDEO:**

PERGUNTA 1: O amador é pior que péssimo? Não entendi. 
PERGUNTA 3: Acho que seria interessante trocar "amador" para "ruins" e adicionar a opção "bons".

**EDIÇÃO DE ÁUDIO:**

PERGUNTA 1: O amador é pior que péssimo? Não entendi. E aqui não deveria ser material "audiovisual", pois estamos trabalhando apenas com áudio. 
PERGUNTA 3: Acho que seria interessante trocar "amador" para "ruins" e adicionar a opção "bons".
PERGUNTA 5: Na opção 4 está falando sobre sincronia entre falas e telas, como estamos trabalhando com áudio, essa opção não faz sentido.

**CRIAÇÃO DE PANFLETO:**

PERGUNTA 4: Na opção 4 deveria estar escrito "Perfeito, havia harmonia e compasso entre os elementos". E na opção 5 acredito que poderia ter apenas "Satisfatório".

**CRIAÇÃO DE IDENTIDADE VISUAL:**

PERGUNTA 3: Na opção 4 deveria estar escrito "O volume **de** alterações permitidas foram extremamente suficientes".

**CRIAÇÃO DE CARTAZ:**

PERGUNTA 4: Na opção 4 deveria estar escrito "Perfeito, havia harmonia e compasso entre os elementos". E na opção 5 acredito que poderia ter apenas "Satisfatório".

**CRIAÇÃO DE MANUAL:**

PERGUNTA 4: Na opção 4 deveria estar escrito "Perfeito, havia harmonia e compasso entre os elementos". E na opção 5 acredito que poderia ter apenas "Satisfatório".

**DESENVOLVIMENTO DE APLICATIVO:**

O formulário vai direto para o bloco 3.

**Comment by morgana-mo** [comment]
**Apresentação/ descrição do questionário**
Nesse parágrafo: "Ao iniciar a resposta ao questionário, você encontrará três blocos a serem respondidos, sendo eles:
O primeiro bloco contém 10 questões de múltipla escolha a respeito de informações gerais; o segundo bloco contém perguntas especificas sobre o produto ou o serviço que você solicitou, com 04 questões de múltipla escolha e 01 questão discursiva e, por fim, temos **a terceira seção**, que é o espaço para sugestões de melhorias com apenas 01 questão dissertativa e 03 questões de múltipla escolha."
Onde destaquei em negrito não seria mais interessante por uma questão de padronização com o que é dito anteriormente utilizar o termo **terceiro bloco**?

**BLOCO 1**
-Quando há itens de múltipla escolha considero que  estes devem estar em ordem alfabética por uma questão de padronização do questionário. 
**- Pergunta 5**: Onde se lê "muito insatisfeitos", deve-se ler _muito insatisfeito_;
**- Pergunta 8**: Deve estar faltando uma parte;
**- Pergunta 9**:  Essa frase está confusa "**O prazo é para elevado**, porém compreensível devido ao volume e a qualidade do trabalho" bem como, sugiro o uso do termo _longo_ no lugar de elevado;
**- Pergunta 10**: Permitir a marcação de mais de uma opção.

**BLOCO 2**

**Elaboração de Identidade Visual (logomarca)**
**-Pergunta 2**: não permite a escolha de mais de uma opção;
**-Pergunta 3**: "O volume **de** alterações permitidas foram extremamente suficientes;
**-Pergunta 4**: Por uma questão de padronização sugiro utilizar apenas 3 ao invés de 03;
- A pergunta dissertativa está como obrigatória

**Edição de vídeos  e/ou aúdio**
**-Pergunta 1**: Fiquei confusa com o uso dos termos amador e péssimo

O meu questionário foi desses dois tópicos  direto para as sugestões de melhorias

** Sugestões de melhorias**
**Pergunta 1**: Consta como obrigatória, não julgo que seja necessário;
**Pergunta 2**: Por uma questão de padronização utilizar os valores de 0 até 5;

**Comment by MilenaPaz2020** [comment]
Descrição:
- A apresentação dos blocos poderia ser em forma de tópicos, acho que facilita a leitura.

Bloco 1: "Informações gerais"
- Questão 5: rever o termo "muito insatisfeitos" no enunciado.
- Questão 7: as alternativas poderiam ser colocadas em ordem de "satisfação", por exemplo: Ruins ou inadequadas, Confusas, não me recordo, adequada e clara e eficientes.
- Questão 9: terceira alternativa está escrito: "O prazo é para elevado, porém..."

Bloco 2: "Apoio técnico em Lives"
- Questão 2: onde está "de 0 a 05", acho que pode retirar o zero à esquerda.
- Questão 4: colocar as alternativas em ordem de satisfação.

Bloco 2: "Edição de vídeos"
- Questão 3: outros termos poderiam ser acrescentados, como por exemplo: "bom" ou "regular". Colocar em ordem de satisfação as alternativas, apenas fico em dúvida de "suficientes" está, em uma escala decrescente, abaixo de amador. A mesma dúvida surge com o termo "básicos", pois efeitos básicos pode não ser algo ruim.

Na última questão do bloco 2, diz: "Caso queira apresentar", mas está marcada como obrigatória. Não seria melhor alterar para: "Por gentileza, apresente..."?

No mais, parabéns pelo trabalho! É um importante instrumento de feedback e foi muito bem elaborado!

**Comment by luizatonial** [comment]
Várias sugestões já foram feitas e concordo com a maioria delas...

**Na apresentação:** 
- Se possível colocar a descrição sobre os blocos de perguntas em tópicos, ou de uma maneira visual, para tornar mais fácil a assimilação.

**Bloco 1 - Informações Gerais:** 
No geral, em relação à escrita:
- Existem alguns '**;**' e '**.**' perdidos no fim de algumas das opções de resposta, acho que poderíamos padronizar sem nenhum tipo de pontuação.
- Existem alguns espaços a mais entre as interrogações e o fim das frases.

- Na pergunta 7 que pergunta sobre a clareza das respostas, acho que ou todas as opções de resposta deveriam estar no singular ou no plural, existe uma mistura.
- Na pergunta 8 realmente parece estar faltando o fim da frase e talvez uma padronização maior na resposta... Talvez poderíamos dividir esta pergunta em duas:
                     1. Uma questionando em relação à quantidade de informações, utilizando as respostas: "quantidade de informações excessivas", "quantidade de informações adequada" e "quantidade de informações insuficientes".
                    2. Outra questionando em relação à qualidade dessas informações, utilizando a opção restante "Houve dificuldade em responder os dados pela sua complexidade", junto à alguma outra opção que diga que as informações estavam claras e não houve dificuldade.

**Bloco 2:**
No geral, também acredito que deve haver uma padronização e utilizar de "0 a 5" ao invés de "05" na pergunta de atribuição de notas.

**_Apoio técnico em Lives_**
- Na pergunta 4, as opções me parecem um pouco confusas... Elencou-se duas respostas relacionadas à queda de internet e falta de sincronia entre telas e as outras duas respostas apresentam opções como "foi satisfatória" e "superou minhas expectativas", me parece que não é uma escala tão linear e clara para resposta...
Como já avaliamos a satisfação do solicitante na pergunta 2, esta pergunta poderia conter respostas sobre se houveram problemas ou não durante a live, talvez transformando-a em uma pergunta aberta, para que o solicitante possa informar o problema ocorrido ou se ocorreu de maneira adequada sem complicações.
- No geral, concordo com a @MilenaPaz2020 acho que seria interessante avaliar o atendimento do membro do PRACTICE, porque realizamos o atendimento antes e durante a live. Talvez poderíamos perguntar como foi avalia a experiência e o contato...

**_Edição de Vídeos/Áudios_**
- Também me confundi um pouco em relação ao péssimo e ao amador... Acho que todas as perguntas em todas as categorias deveriam seguir uma ordem do melhor para o pior por exemplo.
- Na pergunta 5, acho que esta poderia ser substituída por uma pergunta de nota, de 0 a 5, assim como existem para as lives, avaliando a satisfação. Além disso, assim como comentei sobre a pergunta 4 das lives, esta poderia vir junto a uma outra pergunta descritiva a fim do solicitante apresentar os problemas que teve.


Como não conheço muito bem o processo de trabalho das outras equipes, tentarei ajudar minimamente em relação às opções.

**_Criação de panfleto/Cartaz/Manual_**
- Na pergunta 4 há uma opção "Julgou satisfatório", acho que poderia ser reescrita para se adequar à pergunta.

**_Criação de identidade visual_**
- A pergunta 2 não permite marcar mais de uma opção.
- Acredito que deveria haver uma maior padronização nas resposta da pergunta 4.

**_OBS/DÚVIDAS:_** 
- A opção no bloco inicial de "Desenvolvimento de aplicativo" não leva para uma segunda página? Vai direto para o terceiro bloco?
- A opção no bloco inicial de "Outro" leva para a página de lives? Acredito que deveria haver uma página "genérica" ou ir direto para o terceiro bloco, assim como a de "Desenvolvimento de aplicativo".

**Bloco 3:**
No geral, também acredito que deve haver uma padronização e utilizar de "0 a 5" ao invés de '0 a 10'.


Parabéns pelo ótimo trabalho! Vai ser ótimo obtermos os feedback, acho que está bem completo!

**Comment by thaliafriedrich** [comment]
Diversos pontos já foram mencionados, porém, vou deixar o meu feedback completo sobre as questões.

**ITENS GERAIS:**
- Acho que seria interessante numerar as perguntas em cada bloco. Também sugiro colocar a descrição em tópicos e padronizar os finais das frases/opções, deixando todos com “;” ou todos sem pontuação. Retirar espaços entre frases e pontos de interrogação. 

**PRIMEIRO BLOCO:** 

- **Pergunta 1:** Está com caixa de marcação diferente das demais (poderia padronizar para todas serem círculos). Além disso, ela permite várias marcações, porém, acredito que deveria ser apenas uma, sendo a primeira forma pela qual a pessoa tomou conhecimento do programa. 
- **Pergunta 4:** Acho que poderia ser alterado para “Você já teve...”.
- **Pergunta 5:** Inserir uma vírgula depois de “nesse caso”. Na minha opinião, não precisaria explicar na questão que 0 é “muito insatisfeito” e 5 é “muito satisfeito”, considerando que isso está claramente aparecendo no próprio local de assinalar.
- **Pergunta 7:** A opção “Adequadas” está fora de ordem. Poderia ser trocada de ordem com a opção “Confusas”. Além disso, apenas a opção “Clara e eficiente” está no singular. Também fiquei um pouco em dúvida se há uma diferença significativa entre “clara e eficiente” para “adequadas”. Talvez essa útlima possa ser alterada para “Suficientes”, por exemplo.
- **Pergunta 8:** Parece incompleta. A frase “Excesso de informações solicitadas para ser atendido” parece estar sem concordância. Na outra opção, poderia ser alterado “Quantidade inadequada” para “Quantidade insuficiente”. 
- **Pergunta 9:** Corrigir “O prazo é para elevado”.
- **Pergunta 10:** Permitir mais de uma alternativa, considerando que, às vezes, mais de um serviço são realizados na mesma demanda. Aí acredito que a pessoa deveria ser redirecionada para o Bloco 2 de forma a respoder separadamente para cada produto/serviço que assinalou. E acho que há algum erro na opção “Outro”, pois, por exemplo, eu digitei “Criação de banner” e depois “Criação de cartilha”, e nas duas vezes fui direcionada para “Apoio Técnico em Lives” no segundo bloco. 

**SEGUNDO BLOCO:**

**Apoio Técnico em Lives**
- **Pergunta 2:** Corrigir para 0 a 5. Também acho que não precisa explicar as notas, pois está aparecendo claramente nas alternativas. Colocar em letra maiúscula a primeira palavra de “completamente” em: “completamente insatisfeito” e completamente satisfeito” (ao lado das opções).
- **Pergunta 3:** Particularmente, achei algumas opções muito parecidas, por exemplo: fácil, adequado, sem dificuldades... 
- **Pergunta 4:** Colocar as opções em ordem.
- **Pergunta 5:** Não há necessidade de ser obrigatória.

**Edição de vídeos e/ou áudios**
- **Pergunta 1:** Sugiro colocar uma opção do tipo “regular” e revisar a opção “amador”.
- **Pergunta 2:** Talvez seria bom inserir uma opção do tipo “Importante, porém, as alterações que solicitei não foram totalmente realizadas”.
- **Pergunta 3:** Nesse caso, fiquei em dúvida do que significa a opção “amador”;

**Revisão, elaboração e diagramação de textos e imagens**
- **Pergunta 1:** A terceira opção (Houve dificuldade de compreender a minha solicitação) parece incompleta. Ela é parecida com a primeira opção, mas não conclui como ficou o resultado (sendo que as outras opções concluem sobre o resultado). Então, poderia ser revisada.
- **Pergunta 2:** Acho que não há necessidade de ser obrigatória. Ou colocar alternativas: SIm e Não. Se sim, pedir para explicar.
- **Pergunta 4:** Corrigir “Perfeito havia”. Colocar vírgula ou dois pontos “:”. “Julgou satisfatório” para “Satisfatório”.
- **Pergunta 6:** Não há necessidade de ser obrigatória.

**Elaboração de Identidade Visual (logomarca)**
- **Pergunta 1:** Colocar as opções em ordem.
- **Pergunta 2:** Informa que pode marcar mais de uma alternativa, mas não está sendo possível.
- **Pergunta 3:** Corrigir “O volume alterações”;
- **Pergunta 4:** Corrigir “03 modelos” para “3 modelos”. A primeira (quantidade insuficiente...) e segunda opção (poucos modelos) são muito similares. Também pode ser alterado “O volume de modelos” para “A quantidade de modelos”.

**Desenvolvimento de aplicativo**
- Não há perguntas.

**TERCEIRO BLOCO:**

- **Pergunta 1:** Pode ser adicionadas opções “Sim” e “Não”. Se sim, descrever.
- **Pergunta 2:** Novamente, na minha opinião, não seria necessário explicar as notas. Caso permaneça, corrigir o “é” no meio da frase e colocar o “S” em letra maiúscula.

Parabéns aos envolvidos!!
Apesar desses detalhes, achei o formulário muito bem elaborado e bem completo, com certeza vai ser uma ferramenta muito importante para o programa.

**Comment by anacarolinamorigi** [comment]
Complementado o que já foi muito bem salientado pelo pessoal, gostaria de fazer alguns mínimos apontamentos.

**Bloco 1:** Informações Gerais

- Poderia ser alterado a ordem da pergunta número 3 e 4, colocado anteriormente a pergunta 4, ao meu ver apresentaria uma melhor compreensão do que está sendo posto
- Pergunta 10: abrir para mais de uma resposta, pois creio que alguns dos clientes utilizaram mais de um serviço pelo programa, o que levaria eles a terem que responder mais de uma vez a pesquisa.

No geral creio que precisaria mesmo cuidar a parte ortográfica de algumas frases, pois há falta de pontuação nessas. Mas no restante ficou muito bem desenvolvido e bem completo, vai proporcionar ótimos feedbacks para o andamento do programa. 
Parabéns aos envolvidos, arrasaram demais! 👏🏻👏🏻👏🏻👏🏻

**Comment by VIF-Franca** [comment]
Primeiramente quero AGRADECER MUITO as respostas de todos vocês, @robisonjose, @morgana-mo, @MilenaPaz2020, @luizatonial, @thaliafriedrich e @anacarolinamorigi. Foram importantes as considerações. 

Realizei majoritariamente todas as alterações, entretanto algumas por questões metodologias não foram alteradas. 

@alessandrapedrotti poderia nos tirar uma dúvida em relação ao termo _"amador"_, compreendo que o termo amador é se refere à alguém que não é profissional ou sem experiência no que está sendo proposto a fazer.  Pois houve consonância entre o pessoal em substituir "amador" por "péssimo ou ruim"

**Comment by alessandrapedrotti** [comment]
> Primeiramente quero AGRADECER MUITO as respostas de todos vocês, @robisonjose, @morgana-mo, @MilenaPaz2020, @luizatonial, @thaliafriedrich e @anacarolinamorigi. Foram importantes as considerações.
> 
> Realizei majoritariamente todas as alterações, entretanto algumas por questões metodologias não foram alteradas.
> 
> @alessandrapedrotti poderia nos tirar uma dúvida em relação ao termo _"amador"_, compreendo que o termo amador é se refere à alguém que não é profissional ou sem experiência no que está sendo proposto a fazer. Pois houve consonância entre o pessoal em substituir "amador" por "péssimo ou ruim"

Seria melhor mudar as ocorrências do termo "amador"  para "péssimo ou ruim", pois a palavra "amador" faz alusão a um nível profissional nos produtos a que se refere e dado a todo o contexto do practice, utilizar esse tipo de terminologia abre espaço para que cada solicitante defina o que é o seu nível de "produção profissional". É mais seguro utilizar adjetivos mais genéricos.

**Comment by alessandrapedrotti** [comment]
As últimas alterações foram feitas? Podemos fechar a issue? @VIF-Franca

**Comment by VIF-Franca** [comment]
Já haviam sido realizada, esqueci de fechar a issue.
