### ISSUE TITLE
Brainstorm - Produtos de Texto

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#232]
Essa issue serve como espaço para os membros do PRACTICE, em especial para os membros da @practice-uffs/con-conteudo, deixarem suas ideias de produtos textuais que podem ser produzidos.

Sintam-se livres para deixar sugestões!

@practice-uffs/todos

**Comment by GessicaZanon** [comment]
Pensei em elaborar uma cartilha sobre a utilização do Moodle, dicas e orientações de como utilizá-lo. O que acham? Talvez mais voltado para os acadêmicos.. Ou fazer para acadêmicos e professores?

**Comment by alessandrapedrotti** [comment]
> Pensei em elaborar uma cartilha sobre a utilização do Moodle, dicas e orientações de como utilizá-lo. O que acham? Talvez mais voltado para os acadêmicos.. Ou fazer para acadêmicos e professores?

Acho mais adequado que seja voltado aos acadêmicos.
