### ISSUE TITLE
Produção de cartilha com dicas para um melhor aproveitamento das aulas remotas 

### ISSUE THREAD

**Issue by brendaellen** [practice-uffs/programa#233]
A issue refere-se ao que foi discutido na reunião da equipe de conteúdo (27/10/2020), na qual ficou estabelecido que eu ficaria responsável por desenvolver uma cartilha, contendo dicas de como aproveitar melhor as aulas em formato remoto. 
O material produzido estará disponível [nessa pasta.](https://drive.google.com/drive/u/0/folders/1lmkhrQdDESjx_A_cuEFESjpmxT2A3Ucv)

**Comment by brendaellen** [comment]
Finalizei a primeira versão do texto da cartilha, o qual precisa de revisão @practice-uffs/con-conteudo .
Ele está inserido na pasta de entrada.

**Comment by alessandrapedrotti** [comment]
Primeira leitura de revisão feita. No geral, o texto ficou muito bom, deixei alguns comentários no documento para a redatora resolver.
Salvo isso, destaco que um dos problemas recorrentes na escrita foi o uso inadequado da vírgula. Recomendo uma recapitulação das regras ortográficas desse tópico.

**Comment by brendaellen** [comment]
Fiz as alterações que foram solicitadas, e a segunda versão da cartilha já está no template, disponível [nessa pasta.](https://drive.google.com/drive/u/0/folders/1rAST1Y8eL98jbsJToZKuxKvsHb_ifE0b) Solicito a revisão gráfica @practice-uffs/con-design

**Comment by estelavilasboas** [comment]
Revisão realizada. Foi distribuída a quantidade de texto de algumas páginas.

**Comment by brendaellen** [comment]
> Revisão realizada. Foi distribuída a quantidade de texto de algumas páginas.

@estelavilasboas Adorei as ilustrações, ficou exatamente como eu idealizei.
Com a revisão gráfica finalizada, creio que a cartilha está pronta.
@alessandrapedrotti se você quiser dar uma última olhada, que daí eu já irei fechar a issue.

**Comment by estelavilasboas** [comment]
Amei as sugestões para ilustrações, elas ajudaram demais!

**Comment by alessandrapedrotti** [comment]
Última leitura de revisão feita. O texto ficou muito bom, todos que trabalharam nessa cartilha estão de parabéns!
Agora, Brenda, deves converter em PDF uma cópia da apresentação e salvá-la tanto na pasta de saída da tarefa, como na sub-pasta "cartilhas" da parta "materiais" disponível no drive do programa.
Assim que essas tarefinhas forem concluídas podes fechar essa issue.
Depois, deves criar uma issue no repositório website pedindo para que a tua cartilha seja postada no site. Lembre-se de colocar nessa issue o resuminho do material que expliquei no telegram.

@practice-uffs/ger-comunicacao esse material já pode entrar para o calendário de postagens também.

**Comment by brendaellen** [comment]
Cartilha finalizada e pronta para ir para o site. Movida para [a pasta "cartilhas"](https://drive.google.com/drive/u/0/folders/1HQ8xXPLlBfsx5XI6WaRl-3PfbsgzKCie)
