### ISSUE TITLE
Produção de cartilha com dicas para encontrar boas referências bibliográficas

### ISSUE THREAD

**Issue by thaliafriedrich** [practice-uffs/programa#234]
Conforme o que foi discutido na reunião da equipe de conteúdo (27/10/2020), essa issue é destinada à produção de uma cartilha com dicas para encontrar boas referências bibliográficas para trabalhos acadêmicos e pesquisas científicas.

O conteúdo estará disponível [nessa pasta](https://drive.google.com/drive/folders/1E7hsHBapuEjPdoe9e1z7-QQWwxOxPyAK?usp=sharing).

**Comment by Dovyski** [comment]
O curso de Ciência da Computação tem uma página com informações para o TCC. Uma das seções é sobre [como fazer uma revisão bibliográfica](https://ccuffs.github.io/guia-tcc/#/revisao-bibliografica). Talvez seja interessante utilizar esse conteúdo nessa cartilha (ou em outra específica para isso).

**Comment by thaliafriedrich** [comment]
A primeira versão do texto para essa cartilha está concluída. Aguardo revisão da @alessandrapedrotti. Ainda, gostaria de saber se citei a fonte da forma correta nos "prints" (apenas "Foto: Reprodução/PRACTICE") e se podem ser disponibilizados "links úteis" para a pesquisa bibliográfica, por exemplo, os guias de acesso ao VPN e o manual de normas acadêmicas da UFFS.

**Comment by alessandrapedrotti** [comment]
Primeira leitura de revisão feita.

@thaliafriedrich você está de parabéns!! O texto ficou ótimo, muito completo e bem escrito.
Fiz pequenas mudanças em algumas escolhas de palavras e utilização da vírgula apenas. Deixei alguns comentários (principalmente em relação as imagens) que precisam ser resolvidos.

**Comment by thaliafriedrich** [comment]
Fiz os ajustes solicitados no texto e a transposição para o template de cartilha. Aguardo a revisão e possíveis melhorias gráficas, @practice-uffs/con-design.

**Comment by estelavilasboas** [comment]
Revisão gráfica realizada

**Comment by alessandrapedrotti** [comment]
A cartilha está pronta para ir para o site!
@thaliafriedrich favor transformar uma cópia da apresentação em PDF e salvar na pasta saída da tarefa e na sub-pasta "cartilhas" da pasta "Materiais" disponível no drive do programa. 
Fazendo esses passos, essa issue pode ser fechada.
Depois disso, crie uma issue no repositório website solicitando a postagem da cartilha no site.

@practice-uffs/ger-comunicacao já pode adicionar essa cartilha no calendário de divulgação também.

**Comment by thaliafriedrich** [comment]
A versão final da cartilha está em formato PDF na [pasta de saída](https://drive.google.com/drive/folders/1TRCFI2EEVOEjbYFJBWjPjgmuCDrDi4IL) dessa issue e na sub-pasta "Cartilhas" em "Materiais". Também já solicitei a postagem da mesma no site.
Acho que agora a issue pode ser fechada.
