### ISSUE TITLE
Roteirização da Adaptação Cartilha de Edição de Imagens 

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#235]
Como conversamos na reunião de mídia, a Luiza fica responsável pela adaptação da cartilha de edição de imagem. 

O modelo de roteiro de adaptação ainda tá sendo finalizado, mas já dá pra usar bem tranquilo, já inseri o modelo na pasta do Drive.

[Pasta Drive](https://drive.google.com/drive/folders/1uuENNvI_KpEHIUE9AwBCSjqPnSTHKBeB)

**Comment by MaNegrao** [comment]
Esqueci de comentar, mas pode dar uma estudada na cartilha e estimar quantos vídeos serão necessários, dai tu cria um roteiro pra cada vídeo e depois a gente distribui nas issues de gravação.

**Comment by luizatonial** [comment]
Separei alguns tópicos que devem ser abordados inicialmente e o tempo estimado. Na sequência, vou começar o roteiro em si.
Talvez seria interessante também apresentar algumas ferramentas do programa, que não estão tão aprofundadas na cartilha.
A partir disso, acredito que deve ser necessária uma série de uns 3/4 vídeos curtos, com a gravação da tela do computador e narração.

**Comment by MaNegrao** [comment]
> Separei alguns tópicos que devem ser abordados inicialmente e o tempo estimado. Na sequência, vou começar o roteiro em si.
> Talvez seria interessante também apresentar algumas ferramentas do programa, que não estão tão aprofundadas na cartilha.
> A partir disso, acredito que deve ser necessária uma série de uns 3/4 vídeos curtos, com a gravação da tela do computador e narração.

Eu acho interessante abordar outras ferramentas, como o GIMP etc.

**Comment by luizatonial** [comment]
A primeira versão do roteiro está finalizada. Procurei ampliar o conteúdo do vídeo abordando mais ferramentas, como o GIMP, de modo a criar uma série sobre edição de imagens, com aproximadamente 6 vídeos. 
Acabei deixando o roteiro de todos os vídeos juntos no mesmo arquivo, para facilitar na organização da sequência dos vídeos.

Como foi realizada uma grande modificação na cartilha, creio que podemos contar com a ajuda de mais pessoas para revisar o roteiro e sugerir alguns ajustes sobre o conteúdo do mesmo.

Além disso, peço que alguém da @practice-uffs/con-conteudo revise o texto da adaptação.

**Comment by alessandrapedrotti** [comment]
@thaliafriedrich por favor, tratar da revisão desses roteiros.

**Comment by thaliafriedrich** [comment]
Fiz a primeira revisão dos roteiros. O conteúdo está bem completo e bem explicado. Fiz apenas algumas correções sobre a utilização de pontos e vírgulas, e a alteração de algumas palavras. Também deixei comentários onde faz-se necessária a modificação de alguns trechos.

**Comment by luizatonial** [comment]
@thaliafriedrich reescrevi algumas partes que você havia apontado, as quais estão sublinhadas em azul, caso você queira revisar.
Além disso, acabei não reescrevendo uma parte que você sugeriu, porque não consegui pensar numa maneira melhor de escrever aquilo (está em vermelho), se você tiver alguma sugestão será bem-vinda.

**Comment by luizatonial** [comment]
Um outro ponto levantado sobre o roteiro seria se na tela de créditos, ao final dos vídeos, eu deveria citar somente o nome da cartilha que estou adaptando ou também seu autor original?

**Comment by MaNegrao** [comment]
> Um outro ponto levantado sobre o roteiro seria se na tela de créditos, ao final dos vídeos, eu deveria citar somente o nome da cartilha que estou adaptando ou também seu autor original?

@practice-uffs/con-conteudo pode nos dar uma mão?
Na minha visão tu comentaria o nome da cartilha e o redator principal apenas, mas não sei ao certo.

**Comment by thaliafriedrich** [comment]
> @thaliafriedrich reescrevi algumas partes que você havia apontado, as quais estão sublinhadas em azul, caso você queira revisar.
> Além disso, acabei não reescrevendo uma parte que você sugeriu, porque não consegui pensar numa maneira melhor de escrever aquilo (está em vermelho), se você tiver alguma sugestão será bem-vinda.

Ótimo! Verifiquei as alterações e fiz uma sugestão naquela parte que estava em vermelho. Removi os destaques, pois acredito que agora a revisão textual está concluída.

**Comment by alessandrapedrotti** [comment]
> Um outro ponto levantado sobre o roteiro seria se na tela de créditos, ao final dos vídeos, eu deveria citar somente o nome da cartilha que estou adaptando ou também seu autor original?

É muito importante citar o nome da cartilha e o redator original. Os outros elementos dos créditos do material base não precisa.

**Comment by MaNegrao** [comment]
@luizatonial Acho que o roteiro está finalizado certo? Se sim podemos encerrar essa tarefa e abrir uma para as gravações.

Como são vários vídeos poderíamos separar em issues diferentes, mas como tu comentou na reunião que vai fazer um vídeo só e ir cortando acho que não tem necessidade, mas nas edições acho que sim. (espero que não esteja confuso) ;p

**Comment by luizatonial** [comment]
> @luizatonial Acho que o roteiro está finalizado certo? Se sim podemos encerrar essa tarefa e abrir uma para as gravações.
> 
> Como são vários vídeos poderíamos separar em issues diferentes, mas como tu comentou na reunião que vai fazer um vídeo só e ir cortando acho que não tem necessidade, mas nas edições acho que sim. (espero que não esteja confuso) ;p

Acredito que está finalizado sim, @MaNegrao. 
Por mim não tem problema, a princípio pensei em gravar junto, mas não sei até onde vou conseguir gravar de uma vez.
Então, poderíamos separá-los em issues diferentes, tanto para gravação e edição, para manter a organização de maneira individualizada.

**Comment by MaNegrao** [comment]
> > @luizatonial Acho que o roteiro está finalizado certo? Se sim podemos encerrar essa tarefa e abrir uma para as gravações.
> > Como são vários vídeos poderíamos separar em issues diferentes, mas como tu comentou na reunião que vai fazer um vídeo só e ir cortando acho que não tem necessidade, mas nas edições acho que sim. (espero que não esteja confuso) ;p
> 
> Acredito que está finalizado sim, @MaNegrao.
> Por mim não tem problema, a princípio pensei em gravar junto, mas não sei até onde vou conseguir gravar de uma vez.
> Então, poderíamos separá-los em issues diferentes, tanto para gravação e edição, para manter a organização de maneira individualizada.

Beleza, como tu achar melhor. Tu pode criar as issues se quiser então :D

**Comment by MaNegrao** [comment]
Issue finalizada então, os vídeos continuam nas issues referentes
