### ISSUE TITLE
Criar arte padrão para defesa de TCC 

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#236]
Pessoal a professora Morgana realizou a seguinte solicitação, que criássemos uma arte padrão para as defesas de TCC. 

Segue recorte da mensagem: 

"Gostaria que fosse feita a arte padrão para cartaz de defesa de TCC, com espaço para inserirmos apenas os dados de cada trabalho **(acadêmico(a), título, data de defesa, horário, local/link)**. A ideia é termos um mesmo cartaz-convite, para enviarmos aos estudantes e docentes de Letras toda vez que uma defesa é marcada."

**Comment by VIF-Franca** [comment]
Deverá seguir a identidade visual  já criada para o curso, A solicitante destaca que: "Sobre o cartaz, ele pode envolver elementos de pesquisa, de linguagem, de ensino de língua, de literatura etc... (esqueci de comentar antes)."

**Comment by VIF-Franca** [comment]
Olá @mariagelain poderia me dizer como estás o andamento dessa tarefa? Creio que em breve vence nosso prazo com o cliente.

**Comment by mariagelain** [comment]
Boa tarde! A primeira versão da tarefa está pronta. Peço desculpas por não ter informado o andamento.

[Padrão para defesa de TCC](https://drive.google.com/drive/folders/1YcT74T2PAP4vzKEtb_B-jMxj4-wSH0kv)

Criei 3 tipos de padrão, mas tem que ser escolhido apenas um. As cores que utilizei foram as aprovadas na identidade visual. No primeiro padrão optei por colocar apenas um destaque nas informações: data, horário e local em forma de marca-texto para deixar sem muitos floreios, no segundo e no terceiro foi utilizado uma pilha de três livros com um capelo em cima no segundo padrão e no terceiro padrão o capelo está na diagonal. A ideia dos livros seria para representar que é preciso muita leitura e referências para escrever o TCC e o capelo representaria o rito de passagem da graduação.

**Comment by VIF-Franca** [comment]
@mariagelain, segue proposta de alteração nas artes feitas pela Professora Morgana:

- pegar a imagem dos livros com o capelo inclinado da **última proposta** e colocar **na primeira proposta;** ao lado da flor de lis, todos centralizados;

- logo abaixo, substituir **DEFESA DE TCC** por **DEFESA DE TCC EM LETRAS**;

- buscar uma nova fonte, **mais atrativa** para cartaz.

**Comment by mariagelain** [comment]
a segunda versão está em andamento.

**Comment by VIF-Franca** [comment]
Segue e-mail da professora Morgana quanto às artes:

> Temos uma previsão de resposta? Pergunto porque teremos, em breve, várias divulgações.

**Comment by mariagelain** [comment]
Aqui está a [pasta com a segunda versão](https://drive.google.com/drive/folders/1qCx2CwMPJrQ_FAsFL8Osmi4tvzdRuhVG) do padrão para defesa de TCC.

Nessa segunda versão possui três modelos distintos, sendo o primeiro deles a versão com as alterações solicitadas pela professora Morgana e os outros dois variações feitas pela equipe de design.

**Comment by VIF-Franca** [comment]
Enviado para a solicitante. 

`AGUARDANDO FEEDBACK`

**Comment by VIF-Franca** [comment]
> Boa tarde, tudo bem, sim. E com vocês?
> 
> Escolhemos a 1a opção, página 1.
> 
> Obrigada!
> 


`FEEDBACK`

**Comment by mariagelain** [comment]
A versão aprovada pela solicitante se encontra [nesta pasta](https://drive.google.com/drive/folders/11759Qu1V9heGwJw3hOrZit0OgUOP_UsG). 

Na pasta, há 2 arquivos com a versão final. Um deles é a versão preenchida com um exemplo e o outro é para o preenchimento da solicitante.

**Comment by VIF-Franca** [comment]
Ok! As artes foram enviadas para a solicitante.
