### ISSUE TITLE
Roteiro - Politica de Licenças 

### ISSUE THREAD

**Issue by mariagelain** [practice-uffs/programa#237]
Roteirizar o texto da issue #60 para que seja um video curto.

O roteiro deve conter:

- [x] Narração dividida por partes do vídeo (margem de tempo estipulada);

- [x] Marcações de narração, legenda e possíveis recursos necessários.

- [x] Usar como base o modelo da issue #146 

[Pasta do drive](https://drive.google.com/drive/folders/1Vc2tpriHq_TVX1nHt7Hhx2tyFqqdvlLq)

**Comment by brendaellen** [comment]
A primeira versão do roteiro de Política de Licenças foi finalizada. Solicito a revisão do mesmo.
@practice-uffs/con-conteudo

**Comment by alessandrapedrotti** [comment]
O roteiro, em linhas gerais está pronto. @MaNegrao podes atribuir alguém da equipe de mídia para a realização deste vídeo.

**Comment by MaNegrao** [comment]
@practice-uffs/con-midia Pessu, alguém da ilha de vídeos pode assumir a tarefa, é um vídeo curto então é mais tranquilo

**Comment by luizdameda** [comment]
Eu pego! Estou fazendo os últimos ajustes e alterações da issue #146, acredito que ainda hoje a noite já mando ela para a revisão final e amanhã já inicio a organização desse vídeo aqui.

**Comment by luizdameda** [comment]
! Dúvida !

Na segunda parte do vídeo (apresentação do tema), pede para que eu exiba progressivamente os símbolos correspondentes aos tipos licenças, mas não entendi se são símbolos que representem os atributos citados (o produto pode ser copiado, distribuído, editado, remixado ou utilizado como base para a criação de outro produto) ou se são os símbolos do CC propriamente dito mesmo (BY, NC, ND, SA...). Na terceira parte do vídeo entendi que é para apresentar cada CC individualmente, por isso fiquei com dúvida quando a essa primeira parte, tenho a impressão que ficaria um pouco repetitivo...

**Comment by brendaellen** [comment]
> ! Dúvida !
> 
> Na segunda parte do vídeo (apresentação do tema), pede para que eu exiba progressivamente os símbolos correspondentes aos tipos licenças, mas não entendi se são símbolos que representem os atributos citados (o produto pode ser copiado, distribuído, editado, remixado ou utilizado como base para a criação de outro produto) ou se são os símbolos do CC propriamente dito mesmo (BY, NC, ND, SA...). Na terceira parte do vídeo entendi que é para apresentar cada CC individualmente, por isso fiquei com dúvida quando a essa primeira parte, tenho a impressão que ficaria um pouco repetitivo...

Em relação aos símbolos, de fato seriam os símbolos do CC. Talvez não fui muito clara, mas a ideia é que nessa parte do vídeo, todos os símbolos fossem exibidos rapidamente, assim que for mencionado que "as licenças apresentam diferentes formas de autorização". Talvez, formando um círculo em torno do nome "LICENÇAS CC", ou algo do tipo. Porém, caso realmente fique repetitivo, não há necessidade de apresentar esses símbolos nessa parte do vídeo, já que eles irão surgir posteriormente.

**Comment by luizdameda** [comment]
> > ! Dúvida !
> 
> > 
> 
> > Na segunda parte do vídeo (apresentação do tema), pede para que eu exiba progressivamente os símbolos correspondentes aos tipos licenças, mas não entendi se são símbolos que representem os atributos citados (o produto pode ser copiado, distribuído, editado, remixado ou utilizado como base para a criação de outro produto) ou se são os símbolos do CC propriamente dito mesmo (BY, NC, ND, SA...). Na terceira parte do vídeo entendi que é para apresentar cada CC individualmente, por isso fiquei com dúvida quando a essa primeira parte, tenho a impressão que ficaria um pouco repetitivo...
> 
> 
> 
> Em relação aos símbolos, de fato seriam os símbolos do CC. Talvez não fui muito clara, mas a ideia é que nessa parte do vídeo, todos os símbolos fossem exibidos rapidamente, assim que for mencionado que "as licenças apresentam diferentes formas de autorização". Talvez, formando um círculo em torno do nome "LICENÇAS CC", ou algo do tipo. Porém, caso realmente fique repetitivo, não há necessidade de apresentar esses símbolos nessa parte do vídeo, já que eles irão surgir posteriormente.

Beleza! Vou montar pra vermos como fica

**Comment by MaNegrao** [comment]
A parte de roteirização tá concluída, certo? podemos fechar essa issue?

**Comment by brendaellen** [comment]
> A parte de roteirização tá concluída, certo? podemos fechar essa issue?

   Sim, tá tudo certo. Pode fechar :)

**Comment by MaNegrao** [comment]
Tarefa Finalizada :D
