### ISSUE TITLE
Panfleto - divulgação de estúdio para alunos

### ISSUE THREAD

**Issue by mariagelain** [practice-uffs/programa#238]
Conforme foi discutido em reunião, é necessário elaborar um texto explicando que os alunos também podem utilizar os serviços de estúdio.
Após o texto estar pronto a @estelavilasboas irá designar alguém do design para realizar a parte gráfica da tarefa.

[Pasta do drive](https://drive.google.com/drive/folders/1ZBd8Bvwh_s1aT1CMRIoWT-azyw1s4AYU)

**Comment by GessicaZanon** [comment]
Onde posso conseguir os materiais para pesquisa? (equipamentos do estúdio, utilização do serviço e afins)

**Comment by Dovyski** [comment]
[Esse documento](https://docs.google.com/presentation/d/1Llr7LVX6AHYKt_2QBksz7EmX97KqVB2yb_jzo8m-g_A/edit#slide=id.p) foi usado para explicar o estúdio aos órgãos da UFFS. Talvez seja um bom material para começar.

**Comment by GessicaZanon** [comment]
@MaNegrao consegue me indicar algum documento ou similar para eu me informar sobre o horário de uso, como é a utilização desse estúdio e afins; Para consegui escrever o texto para o panfleto.

**Comment by MaNegrao** [comment]
> @MaNegrao consegue me indicar algum documento ou similar para eu me informar sobre o horário de uso, como é a utilização desse estúdio e afins; Para consegui escrever o texto para o panfleto.

Até onde eu sei ainda não foi montado um documento com essas informações relacionadas aos estúdios. Nós temos o [fluxo de tramitação da demanda](https://drive.google.com/drive/folders/1VJ3L3KDKo84Y_2wss3h0j4qksQb-_PQz) e temos os [vídeos e áudio](https://drive.google.com/drive/folders/10lhrk_vhDuUJ2kQYn-yFeIKnq7RKukyC) que podem ser praticamente todos gravados em estudio. Eu não tenho certeza em relação aos horários, mas creio que seja da seguinte forma: 

7:30 à 11:00 e 13:30 à 17:00 com intervalos de gravação de 50 minutos, sendo possível duas gravações em seguida apenas. @lcaimi pode me ajudar se alguma informação ficou faltando

**Comment by Dovyski** [comment]
@GessicaZanon o estúdio do programa tem a filosofia de ser o mais acessível possivel, sem burocracia para usos. Você pode colocar na forma de utilização que todo o agendamento sera feito pelo aplicativo do PRACTICE, sem que seja necessário pedir autorização para alguém. É agendar e usar.

Qualquer pessoa da UFFS pode usar o estúdio para qualquer fim relacionado direta ou indiretamente a UFFS. Depois que o estúdio estiver consolidado, disponibilizaremos o uso para qualquer atividade (inclusive externa à UFFS, se possivel).

**Comment by GessicaZanon** [comment]
@Dovyski @MaNegrao muitíssimo obrigada pelos esclarecimentos.

**Comment by GessicaZanon** [comment]
O texto do panfleto está pronto para revisão.

**Comment by alessandrapedrotti** [comment]
Primeira leitura de revisão feita.
Fiz algumas alterações e cortes no texto original e também deixei alguns comentários no documento para a redatora resolver.

**Comment by GessicaZanon** [comment]
> Primeira leitura de revisão feita.
> Fiz algumas alterações e cortes no texto original e também deixei alguns comentários no documento para a redatora resolver.

Alterações solicitadas foram feitas! Segunda versão do texto pronta para revisão.

**Comment by alessandrapedrotti** [comment]
Fiz a segunda leitura de revisão e o texto ficou muito bom!!

Agora falta resolver a questão do link do formulário e aí passar pra o desing transpor. Depois disso, eu e Géssica faremos mais uma leitura para a aprovação.

**Comment by GessicaZanon** [comment]
> Fiz a segunda leitura de revisão e o texto ficou muito bom!!
> 
> Agora falta resolver a questão do link do formulário e aí passar pra o desing transpor. Depois disso, eu e Géssica faremos mais uma leitura para a aprovação.

Inseri as informações corretas em relação a solicitação de estúdio. Acredito que agora está ok.

**Comment by alessandrapedrotti** [comment]
@practice-uffs/con-design favor trabalhar na transposição para o modelo de panfleto.

**Comment by estelavilasboas** [comment]
Peço que @ricardopatrik fique encarregado da transposição.
Tendo em mente que o [texto](https://docs.google.com/document/d/1VLYXFeGBVjTjGHoPbgFA4QkXQyCwUaFHeD5-lxSd_mk/edit) é extenso, sinta-se livre para adaptar os [templates de panfleto](https://drive.google.com/drive/folders/1t30y9uPM0L5iQ1GRl6omnA6VopQRe9NP) conforme a demanda dessa tarefa. Caso seja necessária a adição de páginas, pode ser feita a adição desde que, como sempre, mantenha/continue a composição da(s) página(s) anteriores.
[Pasta# 238](https://drive.google.com/drive/folders/1ZBd8Bvwh_s1aT1CMRIoWT-azyw1s4AYU)

**Comment by ricardopatrik** [comment]
Fiz em 2 páginas, vejam se esta bom, qualquer coisa adiciono outra pagina.

**Comment by estelavilasboas** [comment]
> Observação: este comentário está considerando o conteúdo a partir da segunda página [desse arquivo](https://docs.google.com/presentation/d/1HVZUadA1AzJgTWUf8ioJw29DMkmvDUR4wc8aaoH9S4U/edit#slide=id.ga77ea44f68_0_140). O restante pode ser removido.

Conforme discutido na reunião (01/12), o texto da [segunda página](https://docs.google.com/presentation/d/1HVZUadA1AzJgTWUf8ioJw29DMkmvDUR4wc8aaoH9S4U/edit#slide=id.ga77ea44f68_0_68) deve ser dividido em duas páginas, visando melhorar o espaçamento e compreensão do leitor.

Algumas sugestões de ajustes:
- Aumentar o espaçamento de linhas (para pelo menos 1,15) e adicionar recuos após os parágrafos para facilitar a leitura e compreensão. O mesmo é válido para as listas de itens;
- O [rodapé da primeira página](https://docs.google.com/presentation/d/1HVZUadA1AzJgTWUf8ioJw29DMkmvDUR4wc8aaoH9S4U/edit#slide=id.ga77ea44f68_0_140) ainda contém as informações do template. Caso não tenha observações a serem adicionadas na páginas, por favor retirar.
- Lembre-se de tomar cuidado ao utilizar o "justificado" do apresentações. Diferente da ferramenta de softwares de imagem, o apresentações não separa as palavras, ele apenas aumenta o espaçamento entre as palavras. Exemplo ilustrativo:
 <img src="https://user-images.githubusercontent.com/30927758/100910063-38fc2500-34ac-11eb-9955-b259bda59a6d.png" width="480">

> Grande espaçamento entre palavras (esquerda) e separação de palavras (direita).

**Comment by ricardopatrik** [comment]
terminando

**Comment by ricardopatrik** [comment]
alterado

**Comment by estelavilasboas** [comment]
- Como temos que pensar no fluxo de leitura, a [primeira página](https://docs.google.com/presentation/d/1HVZUadA1AzJgTWUf8ioJw29DMkmvDUR4wc8aaoH9S4U/edit#slide=id.ga77ea44f68_0_140)  e a [terceira](https://docs.google.com/presentation/d/1HVZUadA1AzJgTWUf8ioJw29DMkmvDUR4wc8aaoH9S4U/edit#slide=id.gb051dc24a7_0_0) devem conter um espaço entre parágrafos;
- Talvez um pequeno espaço entre os subtítulos/perguntas e o texto nas páginas [2](https://docs.google.com/presentation/d/1HVZUadA1AzJgTWUf8ioJw29DMkmvDUR4wc8aaoH9S4U/edit#slide=id.ga77ea44f68_0_68) e [3](https://docs.google.com/presentation/d/1HVZUadA1AzJgTWUf8ioJw29DMkmvDUR4wc8aaoH9S4U/edit#slide=id.gb051dc24a7_0_0) fosse interessante, assim como um pequeno espaço entre os itens;
- Lembrando de adicionar recuos nos parágrafos.

**Comment by ricardopatrik** [comment]
Feito

**Comment by alessandrapedrotti** [comment]
Estou acompanhando o processo e no geral, estou gostando bastante do produto.
Tenho alguns apontamentos apenas: o recuo de parágrafo não foi ajustado em todas as páginas do projeto, gostaria que isso fosse colocado, pois não podemos manter o recuo em uma página e em outras não. Além disso, nas duas últimas páginas, que tem a faixa em azul escuro, tendo apenas 1 ícone em cada, parece meio vazio... Não sei o que poderia ser feito para contornar isso, mas é uma coisa que fica um pouco esquisita na visão geral das páginas.

**Comment by alessandrapedrotti** [comment]
@ricardopatrik como está o andamento dessa tarefa?

**Comment by estelavilasboas** [comment]
A @mariagelain está realizando os ajustes necessários, conforme acordado na reunião do dia 09/02.

**Comment by mariagelain** [comment]
os ajustes foram feitos, gostaria que a @estelavilasboas e que o @Dovyski olhassem o arquivo para aprovar o mesmo.

**Comment by estelavilasboas** [comment]
As alterações ficaram ótimas e amei a inserção de novos ícones.

**Comment by mariagelain** [comment]
Creio que o panfleto tenha sido aprovado, portanto o mesmo se encontra disponível em pdf na pasta de [saída](https://drive.google.com/drive/folders/1dwKqCgIniq-iOiG0uhZfG1tPdPbhUlnP) e também na pasta de divulgação.

Peço para que a @practice-uffs/ger-comunicacao se encarregue de criar materiais de divulgação para o Instagram baseados neste panfleto.

**Comment by morgana-mo** [comment]
> Creio que o panfleto tenha sido aprovado, portanto o mesmo se encontra disponível em pdf na pasta de [saída](https://drive.google.com/drive/folders/1dwKqCgIniq-iOiG0uhZfG1tPdPbhUlnP) e também na pasta de divulgação.
> 
> Peço para que a @practice-uffs/ger-comunicacao se encarregue de criar materiais de divulgação para o Instagram baseados neste panfleto.

Bom dia meninas!
[Aqui](https://drive.google.com/drive/folders/1szPK7K39Xcj0JgUL4pIfLHKLb7SJpnWk) está uma ideia para essa divulgação fico no aguardo do feedback de vocês. 

Quanto aos texto da postagem acredito que possamos usar como texto da postagem o seguinte trecho do panfleto:

>O estúdio, assim como todos os serviços do PRACTICE, tem o objetivo de ser acessível a todos com a menor burocracia possível. Pensando nisso, você pode agendar uma demanda de estúdio pelo e-mail do PRACTICE e, futuramente, pelo aplicativo.
 No momento, temos instalados e disponíveis os estúdios no campus Chapecó/SC e em Laranjeiras do sul/PR.
 Os horários de funcionamento são das 7h30 às 11h e das 13h30 às 17h,tendo um intervalo de 50 minutos entre as gravações.
 DETALHE: Ao contrário de outras requisições, você não precisa de uma autorização ou permissão de um supervisor, por exemplo, basta agendar e usar!

**Comment by alessandrapedrotti** [comment]
> > Creio que o panfleto tenha sido aprovado, portanto o mesmo se encontra disponível em pdf na pasta de [saída](https://drive.google.com/drive/folders/1dwKqCgIniq-iOiG0uhZfG1tPdPbhUlnP) e também na pasta de divulgação.
> > Peço para que a @practice-uffs/ger-comunicacao se encarregue de criar materiais de divulgação para o Instagram baseados neste panfleto.
> 
> Bom dia meninas!
> [Aqui](https://drive.google.com/drive/folders/1szPK7K39Xcj0JgUL4pIfLHKLb7SJpnWk) está uma ideia para essa divulgação fico no aguardo do feedback de vocês.
> 
> Quanto aos texto da postagem acredito que possamos usar como texto da postagem o seguinte trecho do panfleto:
> 
> > O estúdio, assim como todos os serviços do PRACTICE, tem o objetivo de ser acessível a todos com a menor burocracia possível. Pensando nisso, você pode agendar uma demanda de estúdio pelo e-mail do PRACTICE e, futuramente, pelo aplicativo.
> > No momento, temos instalados e disponíveis os estúdios no campus Chapecó/SC e em Laranjeiras do sul/PR.
> > Os horários de funcionamento são das 7h30 às 11h e das 13h30 às 17h,tendo um intervalo de 50 minutos entre as gravações.
> > DETALHE: Ao contrário de outras requisições, você não precisa de uma autorização ou permissão de um supervisor, por exemplo, basta agendar e usar!

Na imagem 5 faltou um ponto final ao fim da listagem; Em todas elas é necessário colocar o recuo de parágrafo nos trechos de texto que estão justificados e/ou alinhados a esquerda.

Fora isso, eu gostei muito!

**Comment by morgana-mo** [comment]
> > > Creio que o panfleto tenha sido aprovado, portanto o mesmo se encontra disponível em pdf na pasta de [saída](https://drive.google.com/drive/folders/1dwKqCgIniq-iOiG0uhZfG1tPdPbhUlnP) e também na pasta de divulgação.
> > > Peço para que a @practice-uffs/ger-comunicacao se encarregue de criar materiais de divulgação para o Instagram baseados neste panfleto.
> > 
> > 
> > Bom dia meninas!
> > [Aqui](https://drive.google.com/drive/folders/1szPK7K39Xcj0JgUL4pIfLHKLb7SJpnWk) está uma ideia para essa divulgação fico no aguardo do feedback de vocês.
> > Quanto aos texto da postagem acredito que possamos usar como texto da postagem o seguinte trecho do panfleto:
> > > O estúdio, assim como todos os serviços do PRACTICE, tem o objetivo de ser acessível a todos com a menor burocracia possível. Pensando nisso, você pode agendar uma demanda de estúdio pelo e-mail do PRACTICE e, futuramente, pelo aplicativo.
> > > No momento, temos instalados e disponíveis os estúdios no campus Chapecó/SC e em Laranjeiras do sul/PR.
> > > Os horários de funcionamento são das 7h30 às 11h e das 13h30 às 17h,tendo um intervalo de 50 minutos entre as gravações.
> > > DETALHE: Ao contrário de outras requisições, você não precisa de uma autorização ou permissão de um supervisor, por exemplo, basta agendar e usar!
> 
> Na imagem 5 faltou um ponto final ao fim da listagem; Em todas elas é necessário colocar o recuo de parágrafo nos trechos de texto que estão justificados e/ou alinhados a esquerda.
> 
> Fora isso, eu gostei muito!

[Aqui ](https://drive.google.com/drive/folders/1oocKHoeOqSOFWZT0oQWpszWxZd-2IyLX) estão as versões corrigidas

**Comment by mariagelain** [comment]
> > > > Creio que o panfleto tenha sido aprovado, portanto o mesmo se encontra disponível em pdf na pasta de [saída](https://drive.google.com/drive/folders/1dwKqCgIniq-iOiG0uhZfG1tPdPbhUlnP) e também na pasta de divulgação.
> > > > Peço para que a @practice-uffs/ger-comunicacao se encarregue de criar materiais de divulgação para o Instagram baseados neste panfleto.
> > > 
> > > 
> > > Bom dia meninas!
> > > [Aqui](https://drive.google.com/drive/folders/1szPK7K39Xcj0JgUL4pIfLHKLb7SJpnWk) está uma ideia para essa divulgação fico no aguardo do feedback de vocês.
> > > Quanto aos texto da postagem acredito que possamos usar como texto da postagem o seguinte trecho do panfleto:
> > > > O estúdio, assim como todos os serviços do PRACTICE, tem o objetivo de ser acessível a todos com a menor burocracia possível. Pensando nisso, você pode agendar uma demanda de estúdio pelo e-mail do PRACTICE e, futuramente, pelo aplicativo.
> > > > No momento, temos instalados e disponíveis os estúdios no campus Chapecó/SC e em Laranjeiras do sul/PR.
> > > > Os horários de funcionamento são das 7h30 às 11h e das 13h30 às 17h,tendo um intervalo de 50 minutos entre as gravações.
> > > > DETALHE: Ao contrário de outras requisições, você não precisa de uma autorização ou permissão de um supervisor, por exemplo, basta agendar e usar!
> > 
> > 
> > Na imagem 5 faltou um ponto final ao fim da listagem; Em todas elas é necessário colocar o recuo de parágrafo nos trechos de texto que estão justificados e/ou alinhados a esquerda.
> > Fora isso, eu gostei muito!
> 
> [Aqui ](https://drive.google.com/drive/folders/1oocKHoeOqSOFWZT0oQWpszWxZd-2IyLX) estão as versões corrigidas

Tenho algumas sugestões: 

- Nas imagens 2, 3, 5 e 6 centralizar o título que está em laranja e o destacar deixando ele um pouco maior que o restante do texto e também deixar com um maior espaçamento entre o título e o texto para que não fique tudo muito junto.
- Na 3 imagem separar o texto em duas partes menores  
- Na imagem 6 o segundo parágrafo está com bastante espaço entre as palavras, tu poderia tentar mudar isso

Mas ficou muito bom :) <3

**Comment by morgana-mo** [comment]
> > > > > Creio que o panfleto tenha sido aprovado, portanto o mesmo se encontra disponível em pdf na pasta de [saída](https://drive.google.com/drive/folders/1dwKqCgIniq-iOiG0uhZfG1tPdPbhUlnP) e também na pasta de divulgação.
> > > > > Peço para que a @practice-uffs/ger-comunicacao se encarregue de criar materiais de divulgação para o Instagram baseados neste panfleto.
> > > > 
> > > > 
> > > > Bom dia meninas!
> > > > [Aqui](https://drive.google.com/drive/folders/1szPK7K39Xcj0JgUL4pIfLHKLb7SJpnWk) está uma ideia para essa divulgação fico no aguardo do feedback de vocês.
> > > > Quanto aos texto da postagem acredito que possamos usar como texto da postagem o seguinte trecho do panfleto:
> > > > > O estúdio, assim como todos os serviços do PRACTICE, tem o objetivo de ser acessível a todos com a menor burocracia possível. Pensando nisso, você pode agendar uma demanda de estúdio pelo e-mail do PRACTICE e, futuramente, pelo aplicativo.
> > > > > No momento, temos instalados e disponíveis os estúdios no campus Chapecó/SC e em Laranjeiras do sul/PR.
> > > > > Os horários de funcionamento são das 7h30 às 11h e das 13h30 às 17h,tendo um intervalo de 50 minutos entre as gravações.
> > > > > DETALHE: Ao contrário de outras requisições, você não precisa de uma autorização ou permissão de um supervisor, por exemplo, basta agendar e usar!
> > > 
> > > 
> > > Na imagem 5 faltou um ponto final ao fim da listagem; Em todas elas é necessário colocar o recuo de parágrafo nos trechos de texto que estão justificados e/ou alinhados a esquerda.
> > > Fora isso, eu gostei muito!
> > 
> > 
> > [Aqui ](https://drive.google.com/drive/folders/1oocKHoeOqSOFWZT0oQWpszWxZd-2IyLX) estão as versões corrigidas
> 
> Tenho algumas sugestões:
> 
> * Nas imagens 2, 3, 5 e 6 centralizar o título que está em laranja e o destacar deixando ele um pouco maior que o restante do texto e também deixar com um maior espaçamento entre o título e o texto para que não fique tudo muito junto.
> * Na 3 imagem separar o texto em duas partes menores
> * Na imagem 6 o segundo parágrafo está com bastante espaço entre as palavras, tu poderia tentar mudar isso
> 
> Mas ficou muito bom :) <3

[Aqui](https://drive.google.com/drive/folders/1yuvIo3yv3o-mjC1cxsx555y6ezMdnsgW) estão as novas versões com as correções!

**Comment by mariagelain** [comment]
Ficou ótimo!! Para mim o material já está apto para ser postado.

**Comment by morgana-mo** [comment]
> Ficou ótimo!! Para mim o material já está apto para ser postado.

Vou postar ele amanhã de manhã então!

**Comment by morgana-mo** [comment]
Postagens:
[Instagram](https://www.instagram.com/p/CLhvxwbFxJt/?igshid=1thenx6ay4q6h)
[Facebook](https://www.facebook.com/104348284683285/posts/243310997453679/)
