### ISSUE TITLE
Produção de cartilha com dicas e orientações sobre o acesso e utilização da plataforma Moodle

### ISSUE THREAD

**Issue by GessicaZanon** [practice-uffs/programa#239]
A issue refere-se ao que foi discutido na reunião da equipe de conteúdo (27/10/2020), na qual ficou estabelecido que eu ficaria responsável por desenvolver uma cartilha. A cartilha terá orientações sobre o acesso e utilização da plataforma Moodle que é utilizada pela UFFS. Tem como intuito instruir os acadêmicos para facilitar a utilização dessa plataforma.
A pasta desta issue está [aqui.](https://drive.google.com/drive/folders/1n0Dk2VX2RKNpbCYNkr9W_ejJnr0RF2JB)

**Comment by GessicaZanon** [comment]
Está pronto a primeira versão do texto para revisão.

**Comment by alessandrapedrotti** [comment]
Primeira leitura de revisão textual feita. Deixei alguns comentários ao decorrer do texto para a redatora @GessicaZanon resolver.
Salvo isso, o conteúdo ficou bem completo, inclusive extrapolando o limite de páginas estipulado para uma cartilha (mas tudo bem, porque foram utilizadas muitas imagens e isso toma espaço).

**Comment by GessicaZanon** [comment]
> Primeira leitura de revisão textual feita. Deixei alguns comentários ao decorrer do texto para a redatora @GessicaZanon resolver.
> Salvo isso, o conteúdo ficou bem completo, inclusive extrapolando o limite de páginas estipulado para uma cartilha (mas tudo bem, porque foram utilizadas muitas imagens e isso toma espaço).

As alterações indicadas foram feitas. Segunda versão do texto pronta para revisão!

**Comment by alessandrapedrotti** [comment]
> > Primeira leitura de revisão textual feita. Deixei alguns comentários ao decorrer do texto para a redatora @GessicaZanon resolver.
> > Salvo isso, o conteúdo ficou bem completo, inclusive extrapolando o limite de páginas estipulado para uma cartilha (mas tudo bem, porque foram utilizadas muitas imagens e isso toma espaço).
> 
> As alterações indicadas foram feitas. Segunda versão do texto pronta para revisão!

Mudanças avaliadas e aprovadas, podes transpor para o template de cartilha!

**Comment by GessicaZanon** [comment]
Transposição para o template finalizado. Aguardo revisão de gráfico.

**Comment by GessicaZanon** [comment]
> Transposição para o template finalizado. Aguardo revisão de gráfico.

@practice-uffs/con-design

**Comment by alessandrapedrotti** [comment]
Leitura de revisão feita. Tem só 1 comentário de um elemento textual que precisa ser visto pela redatora, de resto, falta apenas a revisão gráfica.

**Comment by estelavilasboas** [comment]
@ricardopatrik, favor iniciar a revisão de diagramação. Vamos usar como base o [template (antigo) de cartilhas moderadas e complexas](https://docs.google.com/presentation/d/1o1xsna5nHDkIa7kTnVi-zcWQfilWNZXV/edit#slide=id.g8d2063f94b_0_2), uma vez que esta cartilha possui mais de 10 páginas.

**Comment by GessicaZanon** [comment]
> Leitura de revisão feita. Tem só 1 comentário de um elemento textual que precisa ser visto pela redatora, de resto, falta apenas a revisão gráfica.

Alteração solicitada feita! Acredito que esteja tudo ok agora.

**Comment by alessandrapedrotti** [comment]
Revisão textual 100%, agora falta só a revisão gráfica.

**Comment by ricardopatrik** [comment]
Revisão gráfica feita, no aguardo de possiveis alterações.

**Comment by alessandrapedrotti** [comment]
> Revisão gráfica feita, no aguardo de possiveis alterações.

@GessicaZanon @estelavilasboas vamos finalizar possíveis apontamentos para aprovar a cartilha.

**Comment by GessicaZanon** [comment]
> > Revisão gráfica feita, no aguardo de possiveis alterações.
> 
> @GessicaZanon @estelavilasboas vamos finalizar possíveis apontamentos para aprovar a cartilha.

De minha parte está tudo ok. A @estelavilasboas comentou que os últimos retoques gráficos seria dividir alguma página que tivesse muito texto e acrescentar algumas figuras em páginas que ficassem com pouco texto.

**Comment by estelavilasboas** [comment]
- As páginas que possuem muito texto e muitas imagens devem ser divididas em duas páginas. Após essa divisão, se uma página ficar com pouco conteúdo, podem ser inseridas ilustrações do undraw.com [Exemplo](
https://docs.google.com/presentation/d/1SHfJa30-HziNuz2jCebPulPqiNGc7EO4/edit#slide=id.p2)
- o sumário deve estar como o do template, uma vez que temos este padrão já definido;
@ricardopatrik

**Comment by ricardopatrik** [comment]
Terminei essas alterações, poré, falta arrumar a numeração das páginas. Estou tentando saber como que faz sem ser manualmene.

**Comment by ricardopatrik** [comment]
@estelavilasboas terminei a nueração. Peço que por gentileza você de mais uma revisada, qualquer alteração que vir a ter só me comunicar.

**Comment by estelavilasboas** [comment]
Apenas alguns detalhes finais: 
- O sumário não precisa conter todos os subtítulos. Deve conter apenas os títulos das seções;
- Alguns títulos e subtítulos não estão na mesma altura nas páginas;
- Observei que tem duas páginas com a mesma ilustração, não sei se foi de propósito ou não. Seria legal fazer um variação nas cores em destaque das ilustrações, sendo as cores do programa ou do moodle por exemplo.

**Comment by ricardopatrik** [comment]
Feito.

**Comment by GessicaZanon** [comment]
@ricardopatrik e @estelavilasboas está finalizado a parte do design então?

**Comment by alessandrapedrotti** [comment]
Olhei a cartilha e tenho alguns apontamentos:

1. Por mais que a versão de capa com ilustração tenha ficado linda, não poderemos utilizá-la no momento, pois ela iria destoar das outras no site. Podemos manter essa capa arquivada para uma segunda versão do texto;
2. A página 31 pode ser excluída;
3. Acho que as páginas que já tem imagens do moodle também terem ilustrações pode ter ficado um pouco carregado (exemplos: pag 18, 21 e  28). Nessas páginas, poderíamos manter sim as ilustrações, mas deixá-las como nas páginas 05 e 07 da cartilha com dicas para escrever um bom texto (a ilustração ficaria no canto superior esquerdo), acredito que dessa maneira a página siga com todos os elementos, porém mais organizada.


Já alterei a versão do texto para 2020-12.

Feitas essas alterações, acredito que a cartilha será liberada.

**Comment by ricardopatrik** [comment]
Onde consigo ver essa cartilha "cartilha com dicas para escrever um bom texto"? Não consegui encontrar.

**Comment by GessicaZanon** [comment]
Dei uma última olhada na cartilha para conferir se estava tudo ok, pois o @ricardopatrik fez as últimas alterações solicitadas. @alessandrapedrotti e @estelavilasboas, possuem mais algum apontamento ou posso fechar a issue?

**Comment by alessandrapedrotti** [comment]
Dado que todos os comentários no documento foram resolvidos, a cartilha está liberada para ir ao site. @GessicaZanon por favor, faça o procedimento padrão e informa a equipe de dev que o material está pronto.

PS: Não esqueça do pequeno resumo e de fechar essa issue quando tudo estiver concluído.
