### ISSUE TITLE
Montagem flyers de lives passadas

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#240]
[Pasta da issue no Drive](https://drive.google.com/drive/folders/13ijFJRZltWPKTcSVFhhefXKss-YpLSMI)

No passado fizemos uma série de flyers para fins de portfólio do programa. Porém após isso várias lives foram realizadas e não foram feitos os flyers referentes à elas.

Creio que a equipe de @practice-uffs/ger-comunicacao fica responsável por essa montagem e posteriormente podem encaminhar para o @practice-uffs/dev incluir em nosso portfólio no site

Vocês podem ver os flyers produzidos no [site do practice](https://practice.uffs.cc/portfolio/lives/) e também no nosso [acervo](https://drive.google.com/drive/folders/1c6EQQFJ3XA4xk3bFrGpx8o_9mfRvwMXm)

Para montar é só coletar as informações nos roteiros das lives e passá-las para o [modelo de flyer](https://drive.google.com/file/d/1EXqDKtrSb-bbXOubdjgHVb2ZN1iWermc/view?usp=sharing)

Para gerar o qr-code siga os passos do [vídeo de instruções](https://drive.google.com/file/d/1NvFC9PCTKiKra_zrr0kkSKwglWFYqVKB/view?usp=sharing) utilizando o site [qrcodemonkey](https://www.qrcode-monkey.com/) 

As lives que precisam ter os flyers montados são (essas lives já ocorreram):

- [x] #144
- [x] #154
- [x] #160 
- [x] #163 
- [x] #168 
- [x] #171 
- [x] #208 
- [x] #217  
- [x] #218 
- [x] #219    
- [x] #225 
- [x] #226 
- [x] #229

**Comment by CleissonVieira** [comment]
Assim que concluído favor marcar a equipe de Dev novamente na Issue, dessa forma começamos a atualizar os novos flyers no site.

**Comment by anacarolinamorigi** [comment]
Flyers já se encontram na [pasta Entrada](https://drive.google.com/drive/folders/1bYLVHbQo7dBHbnMZifag0FLdkJABYJLy?usp=sharing) do Drive e aguardo primeira revisão para possíveis alterações. 

Na montagem desses tive dúvida com dois flyers, que foram os #172 e #208, como proceder?
- No #172 devo seguir o modelo já finalizado? Visto que na issue não encontram-se o link da live e nem a data com o horário da realização.
- Os dados da #208 não encontram-se na pasta sinalizada e está vazia.

**Comment by MaNegrao** [comment]
Atualizei as informações. Seria a #171 e não a #172, erro meu. E a #208 eu coloquei agora lá na pasta da todas as informações, também foi erro meu. Perdão

**Comment by anacarolinamorigi** [comment]
Sem problemas @MaNegrao! 

A montagem dos flyers que faltavam já está pronta e encontra-se com os demais na pasta de entrada do drive. Aguardando revisão para possíveis alterações.

**Comment by MaNegrao** [comment]
Num geral os flyers estão todos corretos, só tenho duas ressalvas.

No flyer da #226 tu pode ajustar o link do youtube pra ele ficar em uma linha só. 

Nas #168, #171 e #229 podemos verificar qual subtítulo pode ser colocado ali, @VIF-Franca tu fez essas lives, poderia nos ajudar?

**Comment by anacarolinamorigi** [comment]
> Num geral os flyers estão todos corretos, só tenho duas ressalvas.
> 
> 
> 
> No flyer da #226 tu pode ajustar o link do youtube pra ele ficar em uma linha só. 
> 
> 
> 
> Nas #168, #171 e #229 podemos verificar qual subtítulo pode ser colocado ali, @VIF-Franca tu fez essas lives, poderia nos ajudar?

Okay! Fico no aguardo do retorno do @VIF-Franca para fazer finalizar as alterações necessárias!

**Comment by VIF-Franca** [comment]
Opa pessoal, 

Sobre os subtítulo, pode ser os seguintes:

#168  --> Novas regras sobre a campanha eleitoral físicas e online e prestação de conta da campanha; 
#171 --> Papel do(a) Vereador(a) 
#229 --> Como saber o seu perfil de investidor ?

**Comment by anacarolinamorigi** [comment]
Olá! As alterações realizadas encontram-se na [pasta de saída](https://drive.google.com/drive/folders/1z3_VUiOBba3dGgIEvnHHY7Fvt7_jRiUm?usp=sharing), qualquer outra modificação que deve ser realizada só avisar!

**Comment by MaNegrao** [comment]
@CleissonVieira Os flyers estão prontos para irem ao site

**Comment by CleissonVieira** [comment]
@MaNegrao só lembrando, conforme conversamos nos últimos flyers criados, para manter o padrão de nome com a data que a live foi realizada e uma identificação no final caso haja duas lives na mesma data, conforme exemplos abaixo:

![image](https://user-images.githubusercontent.com/29258164/99717817-af4e5f80-2a88-11eb-8773-20ecfb211595.png)

**Comment by MaNegrao** [comment]
Sim, perdão, foi erro de comunicação meu, perdão, eu havia esquecido.

@anacarolinamorigi você pode fazer a gentileza de organizar como o cleisson demonstrou pra nós?

**Comment by anacarolinamorigi** [comment]
> Sim, perdão, foi erro de comunicação meu, perdão, eu havia esquecido.
> 
> @anacarolinamorigi você pode fazer a gentileza de organizar como o cleisson demonstrou pra nós?

Claro, sem problemas! Organizo como solicitado ainda hoje!

**Comment by CleissonVieira** [comment]
Para essas não há necessidade alterar @MaNegrao e @anacarolinamorigi , já estou finalizando as alterações no site e altero dentro da pasta do drive também. Apenas as próximas demandas de flyers.

Outra questão, que seria mais um pedido meu se há possibilidade disponibilizar um arquivo com as URL (link) do youtube que fica introduzida na cartilha, imagino que pegam de algum local para inserir no Flyer.
Nesse processo de passar para o site eu preciso ler e digitar URL por URL, pois não há como copiar da imagem, isso demanda um bom tempo de trabalho, se conseguem disponibilizar isso de maneira que não roube tanto tempo eu serei grato!

**Comment by anacarolinamorigi** [comment]
> Para essas não há necessidade alterar @MaNegrao e @anacarolinamorigi , já estou finalizando as alterações no site e altero dentro da pasta do drive também. Apenas as próximas demandas de flyers.
> 
> 
> 
> Outra questão, que seria mais um pedido meu se há possibilidade disponibilizar um arquivo com as URL (link) do youtube que fica introduzida na cartilha, imagino que pegam de algum local para inserir no Flyer.
> 
> Nesse processo de passar para o site eu preciso ler e digitar URL por URL, pois não há como copiar da imagem, isso demanda um bom tempo de trabalho, se conseguem disponibilizar isso de maneira que não roube tanto tempo eu serei grato! 
> 
> 

Ah bem tranquilo então. Sobre as URL pode deixar que disponibilizo elas em um arquivo de word, mas qualquer coisa para essas eu deixei disponibilizado, na pasta de entrada, o PowerPoint onde os flyers foram desenvolvidos, creio que lá você consiga pegar os links sem precisar digitar todos.

**Comment by CleissonVieira** [comment]
> > Para essas não há necessidade alterar @MaNegrao e @anacarolinamorigi , já estou finalizando as alterações no site e altero dentro da pasta do drive também. Apenas as próximas demandas de flyers.
> > Outra questão, que seria mais um pedido meu se há possibilidade disponibilizar um arquivo com as URL (link) do youtube que fica introduzida na cartilha, imagino que pegam de algum local para inserir no Flyer.
> > Nesse processo de passar para o site eu preciso ler e digitar URL por URL, pois não há como copiar da imagem, isso demanda um bom tempo de trabalho, se conseguem disponibilizar isso de maneira que não roube tanto tempo eu serei grato!
> 
> Ah bem tranquilo então. Sobre as URL pode deixar que disponibilizo elas em um arquivo de word, mas qualquer coisa para essas eu deixei disponibilizado, na pasta de entrada, o PowerPoint onde os flyers foram desenvolvidos, creio que lá você consiga pegar os links sem precisar digitar todos.

Isso teria salvado meia hora do meu dia hehehe 
Que nada, nas próximas eu sei agora, muito obrigado! =D
Já conclui, lives disponíveis [aqui](https://practice.uffs.cc/portfolio/lives/):

![image](https://user-images.githubusercontent.com/29258164/99723678-40c1cf80-2a91-11eb-9f1f-1828c667cadc.png)

Acredito que Issue possa ser fechada.

**Comment by MaNegrao** [comment]
Beleza, obrigado Ana e Cleisson 😁
