### ISSUE TITLE
Criação de overlay para lives do PRACTICE

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#241]
Essa issue tem como objetivo a discussão e criação de um tema do OBS para as lives do PRACTICE. Até o momento só utilizamos temas improvisados e feitos as pressas, creio que podemos criar com calma e produzir algo bem massa para as lives. 

Eu penso em algo como os exemplos abaixo em termos de diagramação e organização, mas também há a possibilidade de fazer somente algumas moldurinhas para câmera do apresentador por exemplo. 

[Exemplo 1](https://www.behance.net/gallery/103340345/Free-Download-Stream-Overlay?tracking_source=search_projects_recommended%7Cfree%20stream%20overlay)
[Exemplo 2](https://www.behance.net/gallery/90074541/DOWNLOAD-BEST-FREE-STREAM-OVERLAY-TEMPLATE-2020?tracking_source=search_projects_recommended%7Cfree%20stream%20overlay)

Eu acho interessante a gente conseguir fazer algo onde possa ter a interprete, a camera do interlocutor e o slide sem sobrepor um ao outro, podemos pensar também nas legendas e como elas são dispostas, podendo ter alguns modelos dependendo do que for aparecer (Nome de pessoa, assunto, etc).

Então listando só pra não ficar jogado:

- Pensar em duas telas de apresentação, uma com slide e interlocutor e outra adicionando uma janela de interprete.
- Pensar em algo para as legendas
- Tela de espera e encerramento.
.
.
.

Seria bem legal a contribuição de todo mundo, pra criarmos algo bem conciso, estou só dando uma ideia bem ambiciosa haha.
Comentem aqui as suas ideias, por favor.

@practice-uffs/con-design 

CC: @practice-uffs/todos

**Comment by luizatonial** [comment]
Achei a ideia bem interessante, assim conseguimos padronizar nossas transmissões e fica mais fácil também para quem tem menos experiência com as lives. 

Acredito que para começar poderia ser algo mais básico, seguindo a parte mais central de um dos exemplo que você sugeriu:

![image](https://user-images.githubusercontent.com/71669357/98034736-3ac3c180-1df6-11eb-84da-fc63a3042deb.png)

Poderíamos inserir a tela da apresentação em destaque, com a janela superior lateral para o interlocutor (com espaço para seu nome logo abaixo) e no lugar do que era o chat, a janela de interprete.

**Comment by MaNegrao** [comment]
> Achei a ideia bem interessante, assim conseguimos padronizar nossas transmissões e fica mais fácil também para quem tem menos experiência com as lives.
> 
> Acredito que para começar poderia ser algo mais básico, seguindo a parte mais central de um dos exemplo que você sugeriu:
> 
> ![image](https://user-images.githubusercontent.com/71669357/98034736-3ac3c180-1df6-11eb-84da-fc63a3042deb.png)
> 
> Poderíamos inserir a tela da apresentação em destaque, com a janela superior lateral para o interlocutor (com espaço para seu nome logo abaixo) e no lugar do que era o chat, a janela de interprete.

Ótima ideia, concordo contigo que precisamos de algo padrão, tudo que foi feito agora foi ou improvisado ou feito pra outro fim. Podemos também fazer embaixo dessa tela central um espaço para "Legenda", que não fique feio quando não tem nome algum, mas também faça parte do layout. 

Além disso podemos usar a mesma base para duas telas, uma onde não tem slide e outra onde tem

**Comment by estelavilasboas** [comment]
Eu amei a ideia. Acho que já podemos começar a desenhar algumas propostas. 
Só gostaria de saber quais dimensões a imagem deve ter para que possamos começar.

**Comment by estelavilasboas** [comment]
Podemos começar detalhando as três opções propostas:
- Duas telas de apresentação, uma com slide e interlocutor e outra adicionando uma janela de interprete (pensando nas observações feitas nos comentários);
- Espaço para as legendas;
- Tela de espera e encerramento.

@ricardopatrik já poderia começar a projetar essas telas. E mais uma pregunta, @MaNegrao saberia me dizer se há algum formato específico necessário para aplicar temas no OBS?

**Comment by MaNegrao** [comment]
O OBS captura em 1080p60 e transmite a 720p60. Pelo menos é a configuração padrão que utilizamos até agora e acho que é a mais indicada pra boa imagem e não gargalar o pc que vai fazer a live (Claro, nada impede que alguém faça uma live de um pc que tenha resolução de 720).

Falei falei falei, mas enfim. As imagens teriam que ser 1920x1080 creio eu

**Comment by MaNegrao** [comment]
Um ponto legal que eu havia esquecido de falar é que a gente passa créditos e normalmente entramos com a live antes do horario previsto, então uma tela básica para créditos e uma de countdown, seria legal, só não sei como poderíamos fazer, ai fica pela criatividade do pessoal.

**Comment by luizatonial** [comment]
> Podemos começar detalhando as três opções propostas:
> 
> * Duas telas de apresentação, uma com slide e interlocutor e outra adicionando uma janela de interprete (pensando nas observações feitas nos comentários);
> * Espaço para as legendas;
> * Tela de espera e encerramento.
> 
> @ricardopatrik já poderia começar a projetar essas telas. E mais uma pregunta, @MaNegrao saberia me dizer se há algum formato específico necessário para aplicar temas no OBS?

Acho que seria importante uma tela de apresentação, no mesmo padrão, mas só com a imagem do interlocutor, para quando não tem slides.

**Comment by ricardopatrik** [comment]
Olá, fiz um esboço da pagina de espera para saber se +- isso que vocês querem.

![offline](https://user-images.githubusercontent.com/71683219/98375161-83f75980-2020-11eb-87e4-2f0af6dedd9a.png)

**Comment by ricardopatrik** [comment]
Esboço do overlay.
![OVERLAY](https://user-images.githubusercontent.com/71683219/98376964-008b3780-2023-11eb-8a3e-0e0aee908ab1.png)

**Comment by luizatonial** [comment]
Gostei da proposta, @ricardopatrik, mas na minha opinião, na tela de espera seria mais interessante trocar o "estamos off-line" por algo como: começará em breve, aguardando início, etc. 
O @MaNegrao havia comentado sobre uma _tela de countdown_, não sei se ele se referia somente à tela de espera ou ao fato de inserirmos realmente um cronômetro com a contagem regressiva para o início da live. 
Mas se for a segunda opção, seria legal deixar um espaço um pouco maior entre o "estamos off-line" e as redes sociais do PRACTICE, para que no OBS pudéssemos inserir a contagem ali.

Já sobre a tela com o interlocutor e o slide, acredito que talvez seria necessário um espaço para uma legenda abaixo da imagem do interlocutor, e acima do chat, para identificarmos quem está falando.

**Comment by robisonjose** [comment]
Concordo com a @luizatonial. Mas a arte ficou bem boa. 

Porém eu estava pensando, não sei o quão relevante é o chat para as lives. Que eu me recordo são poucos os momentos que há uma interação com o chat, então talvez seja meio desnecessário ter esse espaço exclusivo. 

Também acho que seria interessante se tivesse uma tela de apresentação em que a imagem do interlocutor fica sobre o material que está sendo mostrado, com a imagem do interlocutor mais ou menos daquele tamanho que está no esboço mas em um canto. E ai fazer de 4 maneiras diferentes, só mudando os cantos que a imagem do interlocutor fica, para que possa mudar o local dele quando a câmera ficar em cima de algo importante dos slides. E ai claro, embaixo do interlocutor deixar aquele espaço para a identificação.

**Comment by estelavilasboas** [comment]
Uma sugestão: se a ideia era o fundo ser como uma estampa, talvez você queira usar [o padrão (de estamparia)](https://drive.google.com/file/d/1RGo9ogf6BuwBkBaTPsIenA8tq3_bIHNX/view) que nós já temos.  :)

**Comment by MaNegrao** [comment]
Eu concordo com a @luizatonial e o @robisonjose. 

Acho que precisamos desse espaço para as legendas, e a ideia do countdown era colocar um cronometro regressivo mesmo, muito provavelmente tenha um plug-in do OBS que faça isso, então só questão de pesquisa e termos o fundo pra colocar o cronometro por cima.

Essa questão do chat eu acho que como eu e a Luiza comentamos antes, é mais interessante que a interprete fique ali enquanto tenha apresentação de slide, se não houver, apenas tiramos e colocamos as rede sou informações ali etc. Mas eu acho valido termos o chat em momentos de interação, então podemos ter várias telas e dai no OBS separamos pelas cenas, o que acham?

**Comment by luizatonial** [comment]
> Eu concordo com a @luizatonial e o @robisonjose.
> 
> Acho que precisamos desse espaço para as legendas, e a ideia do countdown era colocar um cronometro regressivo mesmo, muito provavelmente tenha um plug-in do OBS que faça isso, então só questão de pesquisa e termos o fundo pra colocar o cronometro por cima.
> 
> Essa questão do chat eu acho que como eu e a Luiza comentamos antes, é mais interessante que a interprete fique ali enquanto tenha apresentação de slide, se não houver, apenas tiramos e colocamos as rede sou informações ali etc. Mas eu acho valido termos o chat em momentos de interação, então podemos ter várias telas e dai no OBS separamos pelas cenas, o que acham?

Concordo, poderíamos fechar um modelo e seguir com as variações do mesmo, assim conseguimos essa diversidade de telas, tanto as que o @robisonjose sugeriu, como esta questão de manter o chat em momentos específicos.

Sobre o countdown @MaNegrao, é bem simples de inserir, consigo programar se for preciso, só precisamos desse espaço para colocar depois.

**Comment by andrewmsilva** [comment]
> Esboço do overlay.
> ![OVERLAY](https://user-images.githubusercontent.com/71683219/98376964-008b3780-2023-11eb-8a3e-0e0aee908ab1.png)

Eu gostei do overlay, só tem alguns detalhezinhos que incomodaram meu TOC: as bordas. A borda da seção principal é bem grossa, a da seção da câmera é bem fina e a do chat é ainda mais fina e tem um degradê de rosa e roxo bem deslocado da paleta. Eu sugeriria fazer todas as bordas seguindo o mesmo padrão :D

**Comment by MaNegrao** [comment]
Achei todas as sugestões bem legais :D. Acho que vamos chegar em resultados incríveis. Eu tenho só uma sugestão/correção o link do youtube do practice é /practiceuffs, então pode ficar igual

**Comment by ricardopatrik** [comment]
Nesse modelo está mais perto do solicitado?

![em-breve](https://user-images.githubusercontent.com/71683219/98411077-2977f080-2054-11eb-8301-58c04ff8966e.png)

**Comment by luizatonial** [comment]
em relação ao texto e layout acredito que seria neste estilo, mas eu tinha gostado muito do seu primeiro fundo 🙃 achei que estava bem legal e mais limpo do que a estampa do practice

**Comment by estelavilasboas** [comment]
Eu concordo com a @luizatonial , o anterior estava mais limpo. Acho que podemos melhorar a composição e diagramação. 
Talvez mudar a ordenação do nomes das redes no rodapé, ou mudar o fundo, e/ou criar algo novo com as ondinhas, ou até mesmo  esquecer as ondinhas e criar algo diferente com as cores. Essas foram apenas ideias aleatórias, sem ordem nenhuma. Acho que o que queria dizer é "Crie!".
Lembrando que a identidade do PRACTICE tem uma pegada de simplicidade e modernidade, o famoso "menos é mais".

**Comment by ricardopatrik** [comment]
Só pra eu entender, eu uso os padrões ou eu crio, só pra eu ter uma ideia aqui.

**Comment by ricardopatrik** [comment]
vou fazer novas alternativas mais clean, amanha eu posto aqui

**Comment by ricardopatrik** [comment]
Boa noite, segue nova opção da tela de espera. 


![offline2_c_logo2](https://user-images.githubusercontent.com/71683219/98453909-12f99400-213d-11eb-909d-5ca6a49e91f7.png)


![offline2_c_icone](https://user-images.githubusercontent.com/71683219/98453887-f3626b80-213c-11eb-8677-0f93a2727ce5.png)
![offline2_c_logo](https://user-images.githubusercontent.com/71683219/98453889-f52c2f00-213c-11eb-9a38-1c2b3284330b.png)


![offline2](https://user-images.githubusercontent.com/71683219/98453886-ee9db780-213c-11eb-87e3-7a52541ffbdf.png)

**Comment by ricardopatrik** [comment]
Segue nova proposta para Overlay.
![OVERLAY2](https://user-images.githubusercontent.com/71683219/98483913-93c29980-21ea-11eb-94dc-c6580a01bd36.png)

**Comment by ricardopatrik** [comment]
Boa tarde pessoal, como ficou essas novas opções? Oque precisa mudar ou adicionar?

**Comment by alessandrapedrotti** [comment]
> Boa tarde pessoal, como ficou essas novas opções? Oque precisa mudar ou adicionar?

É possível apresentar opções da tela de espera com a fonte Caviar Dreams? Na minha opinião (e é bem opinião mesmo, porque não tenho muito conhecimento da área), a fonte que tu utilizou até agora tem um aspecto mais forte e eu gostaria de ver uma opção mais delicada.

**Comment by luizatonial** [comment]
> Boa tarde pessoal, como ficou essas novas opções? Oque precisa mudar ou adicionar?

Eu gostei dos últimos modelos, só acho que talvez fosse interessante deixar a barra do nome do interlocutor um pouco mais comprida, para adaptarmos a alguns nomes maiores.

Acho que seria válido também você fazer uma versão sem o chat agora, colocando a janela para a intérprete no lugar dele, para termos uma ideia geral.

**Comment by MaNegrao** [comment]
Eu concordo com a @alessandrapedrotti e a @luizatonial, acho que vale fazer alem dessa versão que a luiza comentou, uma onde a legenda está no vídeo maior, que comporte o formato da imagem, um interlocutor maior, a interprete no local atual do chat e na camzinha o chat ou o vídeo de marketing etc.

![image](https://user-images.githubusercontent.com/31110971/98571513-5a923400-2293-11eb-960a-a64cb72e2b60.png)

Além disso um espaço ou imagem ou transição (não sei qual a melhor opção, para fazer a barra de nome dinâmica) eu gostei muito da barra que o @Dovyski fez na [live do curso de CC](https://www.youtube.com/watch?v=ZgWojT5qlpc&t=146s), mas não sei muito como podemos fazer isso.

**Comment by ricardopatrik** [comment]
Onde diz o nome do Mateus sera a barra de transição.
![OVERLAY3](https://user-images.githubusercontent.com/71683219/98587977-b667b780-22a9-11eb-913f-661ffa100abe.png)

**Comment by luizatonial** [comment]
> Onde diz o nome do Mateus sera a barra de transição.
> ![OVERLAY3](https://user-images.githubusercontent.com/71683219/98587977-b667b780-22a9-11eb-913f-661ffa100abe.png)

seria interessante a borda na imagem da intérprete também

**Comment by ricardopatrik** [comment]
![offline2_1](https://user-images.githubusercontent.com/71683219/98595279-8c67c280-22b4-11eb-8ed7-0d4cc125481a.png)
![offline2_2](https://user-images.githubusercontent.com/71683219/98595293-91c50d00-22b4-11eb-91ae-cf3f148a7943.png)


> > Boa tarde pessoal, como ficou essas novas opções? Oque precisa mudar ou adicionar?
> 
> É possível apresentar opções da tela de espera com a fonte Caviar Dreams? Na minha opinião (e é bem opinião mesmo, porque não tenho muito conhecimento da área), a fonte que tu utilizou até agora tem um aspecto mais forte e eu gostaria de ver uma opção mais delicada.

**Comment by ricardopatrik** [comment]
> > Onde diz o nome do Mateus sera a barra de transição.
> > ![OVERLAY3](https://user-images.githubusercontent.com/71683219/98587977-b667b780-22a9-11eb-913f-661ffa100abe.png)
> 
> seria interessante a borda na imagem da intérprete também

![OVERLAY4](https://user-images.githubusercontent.com/71683219/98595263-870a7800-22b4-11eb-8094-0c8e445b053e.png)
