### ISSUE TITLE
Estruturação da Ger-comunicação

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#242]
O PRACTICE precisa utilizar melhor as redes sociais, para estabelecer uma comunicação com a comunidade acadêmica e divulgar melhor seus serviços e materiais. Para isso, a equipe @practice-uffs/ger-comunicacao  existe e a partir de agora devemos explorar melhor os recursos que temos a disposição.

Num primeiro momento, as integrantes da equipe (@Claudineia-VR @morgana-mo @anacarolinamorigi) devem se apropriar das redes sociais do programa, assim como conhecer a fundo as informações nelas dispostas (para isso, elas podem contatar o @VIF-Franca);

**A equipe será responsável pela manutenção dos conteúdos nessas plataformas em sua totalidade, ou seja, será responsável pela elaboração dos elementos textuais e gráficos que forem necessários as postagens;**

A equipe também será responsável pela constante conferência das informações dispostas no site do programa e poderá fazer sugestões de alterações (para isso, é fundamental ter uma noção geral do PRACTICE, suas equipes de trabalho e atividades);

A equipe também será responsável pela redação de notícias que alimentarão o site (é interessante imaginar que a aba de notícias do site também é uma plataforma de divulgação, portanto, pode ser alimentada na mesma frequência que as outras redes).

A partir dessas informações, seguem as tarefas necessárias (torna-se de responsabilidade das integrantes da equipe criar as issues para cada tarefa):

1. Criar um calendário de divulgações:
Cada produto desenvolvido pelo practice e/ou realizado com o apoio do programa pode ser divulgado nas redes (instagram, twitter, youtube e site), para isso, cada um desses produtos deve ser avaliado pela equipe de comunicação e assim será traçado o plano de divulgação daquele produto (se serão feitos post no instagram, se será elaborada uma notícia para o site, etc).
Para que isso funcione, a equipe de comunicação deve elaborar uma agenda, quais dias da semana terão posts, quais serão os materiais divulgados naquela semana, quantos posts (ou vídeos, ou notícias, etc) cada material ou atividade deve receber.

2. Além da questão organizacional, precisamos que sejam desenvolvidos alguns elementos visuais para melhor atender as movimentações da equipe de comunicação (confiram a pasta de identidade visual do programa, assim como os elementos que já foram produzidos para esses fins);
Para o instagram:
Elaborar uma imagem base para ser utilizada no feed e uma nos stories;
Uma imagem que indique novo post;
Uma imagem para divulgação de eventos (nossos ou de parcerias);
Uma imagem que indique novidades no site e/ou app;
Para youtube:
Criar uma tumbnail padrão (que contenha o título do vídeo e logo do PRACTICE);
PS: Cada uma das solicitações acima deve ter sua própria issue.

Sugestões de assuntos para divulgação:
- Serviços ofertados (podem ser seguidos os exemplos dos panfletos de divulgação);
- Prazos de solicitação e entregas;
- Deve ser dada sequência as postagens dos membros da equipe, conforme já está sendo feito;
- Página de recursos (site);
- “prestação de contas” (portifólio);
- Contatos.

**Comment by VIF-Franca** [comment]
Instagram: 

- Poderia tornar a página do Instagrama mais “humana” onde a equipe responsável poderia alimentar diariamente os Storys, pois isso ajuda no engajamento;

- Como também utilizar ferramentas como: Reels e IGTV para vídeos rápidos ex: mostrando o conteúdo de alguma cartilha;

- Convidar os líderes de cada equipe para falar rapidamente sobre a função e o que é desenvolvido por cada equipe;

- Organizar os “destaques” do Instagram ex: “quem somos”, “lives”, “produtos” etc...

- Utilizar um calendário de Posts ex: Canva 

- fazer uso das #Hashtags

Twitter:

OBS: é necessário estarmos no Twitter?

**Comment by morgana-mo** [comment]
Conforme reunião realizada no dia 30/10 ficaram definidos algumas  prioridades quanto a reestruturação da equipe.
1°- Criar uma agenda de divulgação de postagens nas redes sociais (Instagram, Twitter, YouTube, Facebook e o próprio site do PRACTICE), a Issue criada para o desenvolvimento desta tarefa é a. #248;
2°- Elaboração de imagens base para serem usadas nas publicações nas redes sociais;
3°- Nos comprometemos em ler atentamente a todo material que há no site para possíveis sugestões de mudanças e reorganização;
4°- Definiu-se que as reuniões de equipe ocorrerão quinzenalmente e que devemos buscar manter contato sempre que possível através do grupo do Telegram.

Acredito que com o diálogo que estabelecemos as sugestões feitas pelo Vinícius anteriormente sejam interessantes de serem exploradas, e que a partir do momento em que tivermos um calendário definido ficará mais fácil gerir as redes sociais do PRACTICE como um todo.

**Comment by Claudineia-VR** [comment]
Como já dito, de acordo com a reunião do dia 30/10 preestabelecemos que:

-A prioridade será criar um calendário com datas definidas para realizar divulgações nas redes sociais incluindo o site do Practice. Eu e a @morgana-mo ficamos responsáveis por essa tarefa, #248 ;
-Deverá ser organizado a elaboraração  de elementos visuais que irão compor essas divulgações;
-Nós, novas bolsistas que participamos da reunião, ficamos com a tarefa de estudar o Practice como um todo nos atentando ao site, para assim poder contribuir com feedbacks e novas ideias. Além disso, nos comprometemos também a fazer comentários nesta issue falando a respeito desta reunião;
-Combinamos que nossas reuniões de equipe aconteceriam em um intervalo de 15 dias, mas manteríamos também contato constante pelo Telegram; 
-Foi explanado na reunião áreas que necessitariam de atenção específica e constante, como o Instagram e outras redes sociais, o site e a ilustração dos elementos visuais. Eu, se for de acordo com a vontade de todos, posso me responsabilizar por manter e revisar o site;

A reunião foi ótima para sanar algumas dúvidas a respeito da equipe e da issue, a partir disso acredito que será mais fácil organizar e realizar as demandas que temos e teremos daqui em diante.

**Comment by anacarolinamorigi** [comment]
Como colocado e salientado anteriormente, conforme a reunião do dia 30/10, foi apontado com a equipe que:

- Após apresentação das tarefas da issues #242, que a prioridade é o desenvolvimento de um calendário para a realização das divulgações nas redes sociais do programa, incluindo o site do PRACTICE, a fim de tornar público o que é desenvolvido neste. Os responsáveis para a realização desses, majoritariamente, foram a @Claudineia-VR e a @morgana-mo, com o auxílio dos demais membros. A tarefa já encontra-se em desenvolvimento na #248;
- Nas divisões de tarefas, fiquei responsável pela montagem de flyers das lives passadas, conforme issues #240, e Vinícius ficou responsável pelo desenvolvimento de um organograma;
- Após finalização dessas primeiras tarefas, caberá a nós a organização do desenvolvimento de elementos visuais que irão compor essas divulgações;
- Necessidade de atenção específica e constante em áreas como o Instagram e outras redes sociais mais utilizadas, assim como o site e a ilustração dos elementos visuais.
- Foi designado, também, a tarefa de estudar completamente o site do PRACTICE, atentando se há algum erro ou alterações que devem ser realizadas, para assim poder contribuir com melhoramento desse;
- Como combinado, nossas reuniões de equipe aconteceriam em um intervalo de 15 dias, visto que manteríamos um contato contínuo pelo Telegram;
- Por fim, as novas integrantes do grupo se comprometeram a fazer comentários e um breve resumo nesta issue falando sobre a reunião.

Creio que a reunião foi bem esclarecedora sobre o funcionamento da equipe e da organização das issues, uma vez que não sabíamos por onde começar. Além disso, acredito que com a organização do calendário e com o que foi apontado pela Alessandra e o Vinícius, respectivamente, o gerenciamento passará a ser mais fácil e poderemos melhor explorar as sugestões colocadas.
