### ISSUE TITLE
Brainstorm - produtos "enlatados" de design

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#243]
Eu tive uma ideia hoje que eu acho que podemos discutir ou explorar em relação ao design. Apesar da @practice-uffs/con-design ter oficialmente 3 membros, vários dos bolsistas chamados são da área de design. Logo, temos muita criatividade e excelentes capacidades disponíveis.

Eu acho que um dos principais problemas em qualquer universidade é a falta de "personalidade visual" nos projetos. Por exemplo, vários projetos (pesquisa, extensão, ensino), grupos, etc não tem uma logo. Eu sei que fazer uma logo é algo complexo, mas poderíamos unir o útil ao agravável nesse aspecto.

O que vocês acham da ideia de montarmos tipo um mês da logomarca da equipe PRACTICE? Ficaríamos abertos para criação de logos com base nas seguintes condições:

* O cliente informa o nome da marca, uma descrição de 2 linhas sobre ela e até 3 cores de preferência;
* Após 3 dias, entregamos uma logo, sendo que o cliente não pode opinar em ajustes;
* A criação está limitada por projeto/marca: se uma logo for criada para algo, não criaremos outra depois.

Algo bem enlatado. Dessa forma, damos uma melhorada visual em diversos projetos e cursos da UFFS, as pessoas conhecem o programa, a já penetramos um pouco no marketing. Quem sabe a @practice-uffs/ger-comunicacao possa contribuir também.

cc: @practice-uffs/lideres

**Comment by MaNegrao** [comment]
Eu acho super massa, podemos talvez planejar esse período com algumas formas/paletas padrão (visão de leigo) pra que consigamos encaixar essas marcas nos padrões e dê menos trabalho

**Comment by alessandrapedrotti** [comment]
Acho a proposta do Matheus bem interessante. Podemos desenvolver uns 3 modelos base e só mudar as palavras ou ícones específicos, assim além do trabalho ficar mais fácil, também entregaremos produtos que, apesar de diferentes, ainda carregam uma identidade coerente com os outros produtos entregue pelo programa.

**Comment by TaynaraCh** [comment]
Então, achei a intenção muito boa e seria realmente uma forma interessante de divulgar o trabalho do programa, porém, gostaria de trazer alguns pontos para discussão.
A identidade visual é utilizada para transmitir a imagem/ideia de um serviço/produto... e deve ser de característica própria, então não considero coerente haver uma replicação, tudo vai ficar muito parecido, e sem transmitir sua real função.
Outro ponto, é extremamente importante que quem solicita o serviço, consiga se reconhecer no que lhe é entregue, logo, o feedback é necessário para que sejam feitas as alterações cabíveis no projeto, agradando ao máximo o solicitante. 

Sendo assim, acredito que possamos pensar em outras estratégias, a partir dessa ideia inicial, tornando as logos mais representativas.

Por último, uma dúvida, a ideia é realmente que tudo se pareça e reflita uma única identidade visual entregue pelo PRACTICE, como a Alessandra mencionou?

**Comment by ricardopatrik** [comment]
Bem legal a ideia, podíamos fazer da PRACTICE a logo mãe e as demais derivadas dessa logo. Para que nas demais logos tenha um pouco do PRACTICE e que o pessoal perceba isso. E quando o Manual de Identidade visual estiver pronto, isso será mais perceptível aos solicitantes. Um exemplo abaixo.
![image](https://user-images.githubusercontent.com/71683219/98021244-dc411800-1de2-11eb-8e14-2a467277fc06.png)

**Comment by estelavilasboas** [comment]
É uma ideia interessante, mas creio que seja problemática. 

Primeiramente, não acho que uma breve descrição consiga nos dar uma noção do que o solicitante espera e deseja em sua identidade visual. Nesse caso, a criação de uma identidade visual pode ser muito bem comparada ao desenvolvimento de um software: o solicitante possivelmente não sabe o que quer e cabe a nós descobrir isso.
Com isso, posso dizer que não creio que a criação limitada para apenas uma logomarca seja ideal. Temos que considerar, caso fizessemos isso, que o solicitante poderia recusar e não usar o que foi criado sem pensar duas vezes.
Por mais que estejamos em uma equipe de três pessoas e que vários bolsistas tenham sido chamados para design, não creio que seria possível criar uma identidade visual com a qualidade desejada em 3 dias. Tudo leva tempo, até a escolha de cores para uma paleta. Porém, de fato, criatividade para desenvolver ideias para estes projetos não seriam um problema.
Também penso que logos padronizadas, modelos base e/ou com paletas pré-definidas limitam a criatividade e interferem na personalidade singular de cada projeto.

Talvez seja possível colocar essa ideia em funcionamento, mas creio que necessite de vários ajustes.
