### ISSUE TITLE
Vídeo - Dicas para Interpretes (Adaptação de Cartilha)

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#244]
Com o [documento escrito](https://drive.google.com/file/d/1Ukia8hMi2PAX7zn-3aQu0gLWB2mg_a2q/view?usp=sharing) concluído, podemos iniciar a transposição para vídeo. Penso eu que apenas um vídeo é necessário, nós unimos gravações com um pouco de animação. Eu havia conversado com a @amandasegattob na reunião de mídia sobre nós utilizarmos o estúdio de CH para gravar, se estiver disponível utilizarmos um fundo verde para demonstrarmos alguns aspectos da cartilha.

Por hora podemos começar roteirizando esse vídeo e pensando em como iremos faze-lo. Creio que podemos contar com a ajuda da @practice-uffs/con-conteudo para a roteirização e a equipe @practice-uffs/ger-comunicacao com o @practice-uffs/con-midia para dar ideias.

CC: @practice-uffs/ger 

[Pasta Drive](https://drive.google.com/drive/folders/1Ft1zRwobBIBLTaIvlnHV8TckJRHEyZJR)

**Comment by alessandrapedrotti** [comment]
@brendaellen você pode trabalhar nessa roteirização. Acesse a tarefa #146 para encontrar o modelo base de roteiro.

**Comment by amandasegattob** [comment]
Bom dia, como está a roteirização dessa tarefa? @practice-uffs/con-conteudo

**Comment by brendaellen** [comment]
> Bom dia, como está a roteirização dessa tarefa? @practice-uffs/con-conteudo

Boa noite, desculpe a demora em retornar. Comecei a trabalhar hoje na roteirização da tarefa, e creio que até amanhã terei finalizado.

**Comment by alessandrapedrotti** [comment]
> Bom dia, como está a roteirização dessa tarefa? @practice-uffs/con-conteudo

Podes marcar diretamente a pessoa que foi indicada como responsável da tarefa, assim evitamos muitos emails e notificações para o restante da equipe que não está envolvida com esse projeto.

**Comment by brendaellen** [comment]
Finalizei a primeira versão do roteiro, o qual precisa ser revisado.

**Comment by alessandrapedrotti** [comment]
Fiz a primeira leitura de revisão do roteiro e, do ponto de vista textual, fiz poucos ajustes, apenas de usos da vírgula.
Agora, cabe a @amandasegattob ler e fazer as mudanças do ponto de vista da montagem/edição.

**Comment by amandasegattob** [comment]
Boa noite! 
O vídeo dessa tarefa está nessa [pasta](https://drive.google.com/drive/folders/1Mzl0Y6KoUYMBUpnakb_CIMEucaiiSKoH).
Segui o roteiro bem como se refere o texto, no entanto, usei mais vídeos e gifs, diferentemente do que estava na descrição. Aguardo retorno. O que precisar mudar, é só avisar. Estou aberta a críticas e sugestões.

**Comment by alessandrapedrotti** [comment]
@amandasegattob gostei bastante do vídeo, tenho algumas sugestões:

1. Alguns vídeos que tu usou ficaram com uma qualidade ruim (não sei se é por causa da renderização ou por causa da qualidade das imagens em si), seria interessante conferir pra trocar pra outros com qualidade melhor;
2. Tem uma partezinha no fim que na tua narração a palavra "forma" fica parecendo "foda", eu sugiro regravar essa parte pra evitar essa cacofonia;
3. Seria interessante que todos esses vídeos com numeração que estão sendo feitos utilizassem a mesma fonte, a equipe mídia tem que padronizar isso.

Salvo esses pontos, na minha opinião teu vídeo ficou muito bom, gostei muito da tua voz pra narração, tens uma dicção muito boa.

**Comment by amandasegattob** [comment]
@alessandrapedrotti oie!
Acredito que os vídeos com a qualidade ruim sejam das lives que encontrei no canal do PRACTICE no Youtube, como estava no roteiro. Pensei em talvez cortar a imagem do vídeo de forma que apareça o título da live, para ficar mais claro que é uma live feita pelo PRACTICE, o que vc acha? Na minha opinião, a ideia de mostrar as lives no vídeo é muito boa.

Posso mudar a parte do enquadramento da intérprete, pegar um vídeo com uma resolução melhor, sem, necessariamente, ser de uma live nossa.

Quanto às outras alterações, faço rapidinho.

**Comment by MaNegrao** [comment]
> @alessandrapedrotti oie!
> Acredito que os vídeos com a qualidade ruim sejam das lives que encontrei no canal do PRACTICE no Youtube, como estava no roteiro. Pensei em talvez cortar a imagem do vídeo de forma que apareça o título da live, para ficar mais claro que é uma live feita pelo PRACTICE, o que vc acha? Na minha opinião, a ideia de mostrar as lives no vídeo é muito boa.
> 
> Posso mudar a parte do enquadramento da intérprete, pegar um vídeo com uma resolução melhor, sem, necessariamente, ser de uma live nossa.
> 
> Quanto às outras alterações, faço rapidinho.

Eu achei muito legal a ideia de pegar as lives pra demonstrar, infelizmente a qualidade fica inferior por conta da câmera e o envio desses vídeos via webex. Uma live que tu pode usar que ficou bem legal é essa https://www.youtube.com/watch?v=7Ls-Z-F0iFo. as interpretes estão usando chroma-key (e a gente sabia operacionalizar eles).

**Comment by alessandrapedrotti** [comment]
> @alessandrapedrotti oie!
> Acredito que os vídeos com a qualidade ruim sejam das lives que encontrei no canal do PRACTICE no Youtube, como estava no roteiro. Pensei em talvez cortar a imagem do vídeo de forma que apareça o título da live, para ficar mais claro que é uma live feita pelo PRACTICE, o que vc acha? Na minha opinião, a ideia de mostrar as lives no vídeo é muito boa.
> 
> Posso mudar a parte do enquadramento da intérprete, pegar um vídeo com uma resolução melhor, sem, necessariamente, ser de uma live nossa.
> 
> Quanto às outras alterações, faço rapidinho.

Assim, apesar a qualidade não estar perfeita, acho muito importante utilizar as lives do practice, pra mostrar como estamos fazendo um bom trabalho, sabe? Talvez nessa parte colocar algum texto indicando isso na tela ou deixar uma borda ao redor do vídeo fique legal.
podes colocar ao fim do vídeo a lista de todas as lives que foram utilizadas no vídeo?

**Comment by amandasegattob** [comment]
@alessandrapedrotti oie!

O vídeo com as alterações está nessa [pasta].(https://drive.google.com/drive/folders/1Mzl0Y6KoUYMBUpnakb_CIMEucaiiSKoH)

Tentei colocar uma bordinha nos vídeos das lives e na própria imagem uma legendinha, aí como já está ao longo do vídeo, não coloquei quais live usamos no final, mas posso acrescentar também, se achar necessário. 

Se precisar de mais alterações, só falar!

**Comment by amandasegattob** [comment]
@alessandrapedrotti oie!

O vídeo com as alterações está nessa [pasta].(https://drive.google.com/drive/folders/1Mzl0Y6KoUYMBUpnakb_CIMEucaiiSKoH) 

Tentei colocar uma bordinha nos vídeos das lives e na própria imagem uma legendinha, aí como já está ao longo do vídeo, não coloquei quais live usamos no final, mas posso acrescentar também, se achar necessário.

Se precisar de mais alterações, só falar!

**Comment by amandasegattob** [comment]
Oie! 

O vídeo com as alterações está nessa pasta https://drive.google.com/drive/folders/1Mzl0Y6KoUYMBUpnakb_CIMEucaiiSKoH
(não consegui escrever ''nessa pasta'' bonitinho kkkk)

Coloquei uma bordinha nos vídeos das lives e uma legendinha, então por isso não coloquei quais lives foram usadas no fim do vídeo, mas caso ache necessário, eu coloco. 

Quaisquer outras alterações necessárias, só me falar que eu faço!

**Comment by MaNegrao** [comment]
Cara, eu achei o vídeo incrivel, parabéns!!! Ficou realmente muito legal as imagens e tudo mais, sem falar na narração que também ficou muuuito massa. 

Eu tenho apenas uma sugestão: talvez colocar uma musiquinha de fundo, apenas pra não ficar no vazio. Tu pode usar biblioteca de áudios do youtube ou o que tiver no guia do practice.

pra fazer o link da pasta é assim: (Ou clicar no iconezinho no editor)
`[Nessa pasta](link da pasta)`

**Comment by amandasegattob** [comment]
Oie, o vídeo com as alterações está [nessa pasta](https://drive.google.com/drive/folders/1Mzl0Y6KoUYMBUpnakb_CIMEucaiiSKoH).

Não sei se era bem esse tipo de musiquinha (e se era durante o vídeo todo), posso tentar achar outra, caso seja necessário.

**Comment by MaNegrao** [comment]
Sim, é bem assim mesmo. Eu adorei. Só uma sugestão: tenta abaixar um pouco o volume da trilha, de resto tá maravilhoso, parabens!

**Comment by robisonjose** [comment]
Boa noite,

Eu estava dando uma olhada no vídeo, e tem uma parte que é utilizado um [vídeo](https://www.youtube.com/watch?v=R1-Efd_t-aI&ab_channel=PortadosFundos) do Porta dos Fundos, será que isso não vai dar problema? 

E no final do vídeo, depois dos créditos, tem uma parte só com a sua fala. Era para ter aquela parte mesmo? Eu não entendi.

**Comment by amandasegattob** [comment]
@robisonjose boa noite!

Então, essa questão do vídeo era algo que ia ver amanhã na reunião, porque ainda não sei bem como funciona essa coisa de licença. 

E sobre a fala, não era pra ter, coloquei o vídeo errado,  ainda bem que tu viu! kkkkk

**Comment by amandasegattob** [comment]
Bom dia! Fiz as alterações que foram comentadas e mais algumas que achei que melhorariam o vídeo, está [nessa pasta](https://drive.google.com/drive/folders/1Mzl0Y6KoUYMBUpnakb_CIMEucaiiSKoH). 

Aguardo resposta para, então, colocar as legendas e finalizá-lo.

**Comment by amandasegattob** [comment]
@robisonjose caso tu queira dar uma olhada.

**Comment by robisonjose** [comment]
Bom dia @amandasegattob. 

Algumas alterações: 

1. Em 0:22 tem um corte que aparece só o fundo, pode ser retirado;
2. Em 2:11 é o único momento em que é utilizado um vídeo com tamanho diferente dos outros, se tu conseguir encontrar outro para colocar no lugar seria bem bom; 
3. Em 3:06 tu coloca um símbolo de wifi. Ele está com a qualidade bem ruim em relação ao resto do vídeo, se conseguir trocar seria ótimo, ou diminuir o tamanho para que ele não fique serrilhado;
4. Deve ser colocado nos créditos onde você pegou as imagens, vídeos e a trilha sonora. E não precisa necessariamente colocar o nome da trilha sonora, mas colocar de onde foi pego. Ficar atenta a isso, pois em algumas músicas é necessário creditar autoria completa, como o nome da música e do artista; 
5. Acredito que seja interessante colocar todas as palavras que aparecem centralizadas, tanto na vertical quanto na horizontal, e também acredito que ficaria mais interessante, esteticamente, se as palavras aparecessem em fade in ou sem nenhum efeito de transição. A não ser no "cores contrastantes" que o efeito combinou bastante. 

De resto está muito bom, gostei muito dessa versão. Tu usou muito bem os vídeos. Ótimo trabalho.

**Comment by amandasegattob** [comment]
Boa tarde! O vídeo está na pasta. Fiz as alterações que o @robisonjose apontou e mais algumas que achei que ficariam melhores.  Se não tiver mais alterações, o próximo passo é colocar as legendas, correto?

**Comment by robisonjose** [comment]
Boa noite @amandasegattob 

O vídeo está muito bom, parabéns. Algumas ultimas modificações para então inserir as legendas:

1. Em 00:49, no vídeo que você gravou, tem uma barrinha preta do lado esquerdo e direito, ou seja, o seu vídeo está um pouquinho menor que os outros, sugiro que apenas aumente um pouco o tamanho do seu vídeo para que essas barrinhas desapareçam;
2. Em 1:27 tem uma respirada um pouquinho alta que o microfone capta, acredito que ela possa ser facilmente retirada (só cortando a parte da respiração);
3. Em 2:14 - 2:16 aparece no vídeo as barrinhas pretas laterais, aumentar o tamanho do vídeo para que isso não aconteça;
4. Em 2:45 os "risquinhos" do número 5 aparecem antes do número 5, isso não acontece nas outras numerações. Seguir o padrão das numerações anteriores;
5. O "Estabilidade e qualidade" que aparece em 3:12 não está com o texto centralizado. A caixa de texto está relativamente centralizada no vídeo, mas o texto em si não está centralizado, a parte do "e qualidade" deveria estar um pouquinho para a esquerda;
6. Em 3:25 seria interessante colocar o site do PRACTICE (talvez junto com a logo) na tela e só depois os créditos, quando a sua narração já tiver acabado. E a vinheta deve vir depois dos créditos.  

Eu fiquei em dúvida sobre o áudio da narração. Você gravou ele todo de uma só vez? Pois parece que em alguns momentos o áudio está muito bom, enquanto em outros momentos ele está um pouquinho pior (em relação ao primeiro). Durante alguns períodos não tem nenhum "PUF" no áudio, enquanto em outros tem alguns. 

No geral o vídeo está muito bom, são só alguns detalhes que tornarão ele ainda melhor.

**Comment by amandasegattob** [comment]
Bom dia! Fiz as alterações. Decidi regravar a narração, acho que ficou melhor assim. Quanto aos risquinhos do número 5 não consegui alterar pois já peguei os vídeos prontos. 

O vídeo está nessa [pasta](https://drive.google.com/drive/folders/1Mzl0Y6KoUYMBUpnakb_CIMEucaiiSKoH).

**Comment by robisonjose** [comment]
Bom dia @amandasegattob.

O vídeo ficou maravilhoso, todas as modificações sugeridas foram feitas e a tua narração ficou impecável, além do áudio que está muito bom. 

Só tenho mais duas sugestões: 

1. Diminuir um pouquinho o volume da música de fundo;
2. Ir atrás de quem fez esses vídeos prontos dos números e pedir para a pessoa editar para ficar padronizado igual os outros. Você tem alguma ideia de quem fez essas transições? Lembro que em algum momento o @luizdameda fez algo parecido com isso, porém, não sei se foi esses que tu utilizou. 

Mais uma vez, parabéns. Ficou show.

**Comment by amandasegattob** [comment]
Boa noite! Fiz as alterações do [vídeo](https://drive.google.com/drive/folders/1Mzl0Y6KoUYMBUpnakb_CIMEucaiiSKoH).
@robisonjose aguardo teu ok para fazer a legenda dele.

**Comment by robisonjose** [comment]
Bom dia @amandasegattob. 

O vídeo está ótimo. Pode ser legendado sim. 

Depois de legendado é interessante marcar o pessoal que trabalhou no roteiro para que eles possam revisar a legenda inserida no vídeo.

**Comment by amandasegattob** [comment]
Fiz as alterações e acrescentei a legenda. @alessandrapedrotti @brendaellen vocês podem fazer a revisão da legenda?
O vídeo está nessa [pasta](https://drive.google.com/drive/folders/1Mzl0Y6KoUYMBUpnakb_CIMEucaiiSKoH).

**Comment by robisonjose** [comment]
Bom dia @amandasegattob. 

Acho que tu esqueceu de trocar os slides de créditos para outros com qualidade de imagem maior. Se puder, faça isso depois da revisão da legenda.

**Comment by amandasegattob** [comment]
Oi @robisonjose eu fiz exatamente o que foi falado, não sei o que pode ter acontecido.

**Comment by robisonjose** [comment]
Bah, acho que tu já está em seu período de férias. Quando tu voltar, tenta falar com o @luizdameda, acho que ele consegue te explicar o que pode ser feito. Mas se não der pra arrumar, sem problemas, o vídeo está muito bom e não é isso que vai deixar ele ruim. 

Bom descanso!

**Comment by alessandrapedrotti** [comment]
**Revisão da legenda**

0:21 - mudar na legenda de "intérpretes de libras" para "interpretes em libras", para estar de acordo com a narração;

0:32 - Sugiro alterar na narração a pronúncia da sigla da UFFS de _ufis_ para a fala de cada letra da sigla. Se não for possível fazer isso nesse vídeo, vamos adotar essa pronúncia para os próximos que forem produzidos.

Notei que em alguns momentos é possível ouvir um chiado na narração, é possível tratar o áudio para removê-lo? 

A qualidade do vídeo está muito boa, @amandasegattob meus parabéns!!!

**Comment by amandasegattob** [comment]
Bom dia! Fiz as alterações. 
- Acredito que a qualidade dos créditos esteja bem melhor agora @robisonjose 
- Não consegui mudar a narração da pronúncia UFFS, mas para os próximos vídeos cuidarei isso.
- Tentei tratar o áudio da forma que consegui (nunca tinha feito isso), mas acredito que agora está mais ''uniforme'' e com menos chiado. Quando revisei ele, ouvi pelo áudio do próprio notebook, aí não percebi. Mas com o fone deu para notar. Obrigada @alessandrapedrotti pela dica.

**Comment by robisonjose** [comment]
Bom dia @amandasegattob.

Acredito que apenas deve ser feito a alteração sugerida pela Alessandra, de mudar de "interpretes de libras" para "interpretes em libras" em 00:21. Sobre a qualidade dos créditos, elas ainda não estão em 1080p, como eu disse, na issue #295 eu falo sobre essa questão e o Luiz conseguiu melhorar a qualidade das imagens. Não sei se você falou com ele, mas acredito que ele possa te ajudar.

Todavia, a única alteração que deve ser feita de fato é a mudança da legenda. A mudança dos créditos para uma qualidade melhor vai de você. 

Lembre-se sempre de inserir os dados dos vídeos na [planilha de mapeamento](https://drive.google.com/drive/folders/1VcmKBMSxMSzJ3ZtnezOktPdMNhj_qm75) e estar sempre atualizando.

**Comment by robisonjose** [comment]
Ah, na real, tem mais uma coisa. Algumas vezes na legenda aparece "interprete" e "intérprete". Rever todas as vezes que aparece essa palavra e colocar sempre "intérprete".

**Comment by robisonjose** [comment]
E mais outra coisa: Tem momentos que tu coloca letras maiúsculas, como se fosse um "título" daquela parte, acho que isso ocorre em todas as transições, isso deve ser retirado, isto é, colocar a frase normalmente. Acredito que as letras maiúsculas devem ser utilizadas apenas em siglas, como é o caso de LIBRAS e UFFS.

**Comment by robisonjose** [comment]
Os créditos com qualidade superior estão postados na pasta de entrada.

**Comment by amandasegattob** [comment]
Vídeo na pasta. Acredito que, agora, com todas as alterações feitas.

**Comment by robisonjose** [comment]
Cara, o vídeo ficou maravilhoso. Meus parabéns pelo trabalho.

Uma mudança que poderia ser feita, não no vídeo, mas na legenda: Será que nos "títulos" (momento em que ocorre as transições e aparece o número da dica na tela) que foram colocados sem as letras maiúsculas, não seria interessante colocar dois pontos no final? 

@alessandrapedrotti se puder nos ajudar nessa questão, seria bom.

**Comment by alessandrapedrotti** [comment]
> Cara, o vídeo ficou maravilhoso. Meus parabéns pelo trabalho.
> 
> Uma mudança que poderia ser feita, não no vídeo, mas na legenda: Será que nos "títulos" (momento em que ocorre as transições e aparece o número da dica na tela) que foram colocados sem as letras maiúsculas, não seria interessante colocar dois pontos no final?
> 
> @alessandrapedrotti se puder nos ajudar nessa questão, seria bom.

Olha, pode ser colocado sim.

**Comment by amandasegattob** [comment]
Boa tarde! Fiz a alteração e decidi colocar a legenda em cor branca, achei que combinou mais. O vídeo está na [pasta](https://drive.google.com/drive/folders/1Mzl0Y6KoUYMBUpnakb_CIMEucaiiSKoH).

**Comment by MaNegrao** [comment]
Eu curti mais também, parabéns pelo excelente trabalho Amanda

**Comment by robisonjose** [comment]
Bom dia @amandasegattob.

O vídeo ficou show. E realmente, a legenda em branco ficou melhor. 

O vídeo pode ser finalizado, assim como a issue; E a planilha de vídeos internos deve ser atualizada.

**Comment by amandasegattob** [comment]
Planilha atualizada.
