### ISSUE TITLE
Nome social dos integrantes do PRACTICE

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#245]
Conforme questão levantada na issue #227, é necessário que todos nós informemos nossos nomes sociais (ou abreviação do nome) para que o template da página de créditos dos materiais textuais fique mais clean, com uma melhor utilização do espaço.

Portanto, colegas, utilizem os comentários dessa issue para informar como querem ser chamados.

@practice-uffs/todos 

OBS: Coloquei a label P2 para terminarmos isso rápido.

**Comment by alessandrapedrotti** [comment]
O meu nome pode manter Alessandra Pedrotti, pois já é a versão abreviada.

**Comment by mariagelain** [comment]
O meu pode continuar como Maria Gelain, pois já é a versão mais curta do meu nome.

**Comment by MaNegrao** [comment]
O meu é Matheus Negrão

**Comment by morgana-mo** [comment]
O meu é Morgana Oliveira

**Comment by MilenaPaz2020** [comment]
O meu é Milena Paz.

**Comment by Dovyski** [comment]
Fernando Bevilacqua

**Comment by luizatonial** [comment]
Luiza Tonial

**Comment by estelavilasboas** [comment]
Estela Vilas Boas

**Comment by luizdameda** [comment]
Luiz Eduardo Dameda

**Comment by TaynaraCh** [comment]
Taynara Christmann

**Comment by oraphaBorges** [comment]
Raphael Borges

**Comment by anacarolinamorigi** [comment]
Ana Carolina Morigi da C. S.

**Comment by thaliafriedrich** [comment]
Thalía Friedrich

**Comment by brendaellen** [comment]
Brenda Ellen Reis

**Comment by GessicaZanon** [comment]
Gessica Zanon

**Comment by robisonjose** [comment]
Robison José

**Comment by VIF-Franca** [comment]
O meu: Vinícius França Alves

**Comment by CleissonVieira** [comment]
Cleisson V. Raimundi

**Comment by Claudineia-VR** [comment]
Claudinéia Raimundi

**Comment by vini2reis** [comment]
Vinicius dos Reis

**Comment by rafaguilman** [comment]
Meu Rafael Guilman

**Comment by amandasegattob** [comment]
Amanda Segatto Bisognin

**Comment by andrewmsilva** [comment]
Andrew Malta

**Comment by ricardopatrik** [comment]
Ricardo Manfro

**Comment by alessandrapedrotti** [comment]
> Ana Carolina Morigi da C. S.

Podemos manter Ana Carolina Morigi apenas?

**Comment by mariagelain** [comment]
@lcaimi @phdmauricio @JeanCHilger @arufonsekun aguardamos o retorno de vocês para finalizar a issue.

**Comment by JeanCHilger** [comment]
Jean C. Hilger

**Comment by lcaimi** [comment]
Luciano L. Caimi

**Comment by arufonsekun** [comment]
Junior V. Ramisch

**Comment by VIF-Franca** [comment]
@phdmauricio  havia dito em reunião que seria apenas Mauricio Bozatsk,

**Comment by VIF-Franca** [comment]
Sendo assim temos todos os devidos nomes sociais.

**Comment by MaNegrao** [comment]
falta o @pedroamaximowski

**Comment by mariagelain** [comment]
após o @pedroamaximowski responder a issue com o seu nome social, podemos fechar a issue.

**Comment by pedroamaximowski** [comment]
O meu pode ser Pedro Augusto

**Comment by robisonjose** [comment]
Tem algum lugar que esses nomes estão organizados (planilha, ou algo do tipo, pro pessoal que for entrando for preenchendo)?
