### ISSUE TITLE
Logo para o web-feedback

### ISSUE THREAD

**Issue by mariagelain** [practice-uffs/programa#247]
Foi solicitado pela equipe de dev, que a equipe da @practice-uffs/con-design crie uma logo para o web-feedback.

**Comment by Dovyski** [comment]
Dando um pouco mais de contexto sobre o projeto, o web-feedback é um projeto do PRACTICE que centraliza toda nossa infra-estrutura digital. É nele que os clientes farão interação, inclusive o acompanhamento do status do seus serviços. Além disso, esse sistema também é responsável por prover nosso aplicativo móvel com dados.

**Comment by estelavilasboas** [comment]
[Pasta do drive](https://drive.google.com/drive/folders/1sp94g948CQ9IcKEv1rJFsM-kikc9SsHi)

**Comment by estelavilasboas** [comment]
Finalizada e disponível em 4 resoluções na [pasta saída](https://drive.google.com/drive/folders/1SLuYscoyrseQy-mJzNKvjI0yAgFv7R4H).
