### ISSUE TITLE
Calendário de divulgações

### ISSUE THREAD

**Issue by Claudineia-VR** [practice-uffs/programa#248]
Conforme solicitado na issue #242  e também discutido em reunião, essa serve para melhorar organização da @practice-uffs/ger-comunicacao . O calendário deve ser feito e adicionado a pasta [programa#248](https://drive.google.com/drive/u/0/folders/1Lallb5NHpX-oT-dL-0LJ70U-a35W_7VB)

**Comment by Claudineia-VR** [comment]
O Calendário foi feito de acordo com o solicitado, definimos principalmente as divulgações que irão ocorrer agora em novembro e dezembro e deixamos para adicionar o restante de acordo com as demandas e solicitações. Aceitamos ideias e sugestões de mudanças e/ou divulgações interessantes que poderiam ser adicionadas, além das atividades já previstas.

**Comment by alessandrapedrotti** [comment]
Meninas, ficou muito bom e bem organizado!! Amei que deixaram uma data fixa no mês para tratar do site.
Vocês podem, a partir dessa organização inicial já começar a postar nas redes. Acredito que quem tem o acesso mais direto é o @VIF-Franca e ele pode olhar o calendário e fazer sugestões também.

Da parte textual não a muito que revisar, pois são apenas pequenas frases de orientação, portanto vou remover a label de texto dessa tarefa.

Se o Vinícius não tiver sugestões de alteração, a issue poderá ser fechada e o calendário pode ser movido para a pasta "materiais" e lá criem uma sub-pasta com o nome "comunicação" e deixem uma cópia do calendário salva lá.

Depois disso, organizem-se para criar os elementos que comentei na issue #242.

**Comment by Claudineia-VR** [comment]
Coloquei o label de texto:revisar porque não encontrei outra que se adequasse melhor, mas era para a revisão do calendário em geral mesmo. A cópia já está salva na pasta "materias" na sub-pasta "comunicação". Aguardo o @VIF-Franca se manifestar para então concluir e fechar a issue.

**Comment by alessandrapedrotti** [comment]
> Coloquei o label de texto:revisar porque não encontrei outra que se adequasse melhor, mas era para a revisão do calendário em geral mesmo. A cópia já está salva na pasta "materias" na sub-pasta "comunicação". Aguardo o @VIF-Franca se manifestar para então concluir e fechar a issue.

Podemos pensar, como equipe, em um conjunto de labels que sirva a nossos propósitos.

**Comment by Dovyski** [comment]
Esse calendário ficou incrível, parabéns! Eu tomei um choque (no bom sentido) quando abri o calendário e vi a qualidade gráfica do processo já ali. ❤️🚀 

A Ale já escreveu qualquer comentário que eu poderia fazer. Apenas como sugestão, gostaria que vocês fizessem algumas das postagens especiais como sendo as "visões de futuro" do PRACTICE. Temos vários projetos ambiciosos em desenvolvimento, então temos que fazer a comunidade conhecer eles.

**Comment by alessandrapedrotti** [comment]
Eu e o @MaNegrao adicionaremos a esse calendário um cronograma referente a postagem de vídeos no instagram e no youtube do practice e, para isso, criaremos uma nova issue. Esta será fechada.
