### ISSUE TITLE
Criar PDF da gerência informando que a comunicação de demandas do programa é por e-mail

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#249]
Para melhorar o fluxo de comunicação entre clientes e bolsistas, precisamos criar um documento documento timbrado do PRACTICE para informar os fluxos e afins. Esse documento deve ser assinado pelos coordenadores e será usado pelos bolsistas para direcionar a comunicação dos clientes.

**Comment by Dovyski** [comment]
O @VIF-Franca está encarregado dessa tarefa, mas a equipe responsável é a @practice-uffs/ger-auxilio

**Comment by VIF-Franca** [comment]
@Dovyski , @lcaimi , @alessandrapedrotti e @phdmauricio 

Temos a primeira versão do documento que já se encontra no [drive](https://drive.google.com/drive/u/1/folders/13_ZBCrNMiWcp0ctLs4q-R6ifBfAbQsUE)

Qualquer sugestão de alteração só falar

**Comment by alessandrapedrotti** [comment]
Fiz minha leitura do texto e mudei algumas partes por questões de clareza e etc.

**Comment by VIF-Franca** [comment]
Perfeito! 

@lcaimi @Dovyski e @phdmauricio agora precisamos da assinatura de vocês logo disponibilizaremos para todos os membros do PRACTICE.

**Comment by Dovyski** [comment]
Coloquei a minha assinatura e fiz uns pequenos ajustes no texto. De minha parte, está pronto.

**Comment by alessandrapedrotti** [comment]
Favor @phdmauricio e @lcaimi assinar o doc para podermos encerrar a issue.

**Comment by Dovyski** [comment]
Eu vou adicionar as assinaturas deles digitalizadas, @alessandrapedrotti, assim que conseguir elas (eles estão providenciando).

**Comment by Dovyski** [comment]
O documento está assinado e pronto.

**Comment by alessandrapedrotti** [comment]
A versão em PDF do documento foi salva [nesta pasta](https://drive.google.com/drive/folders/1UhywLOcXAnOplX8CiOExw8Yz3igAatB2) para qualquer um que precisar utilizá-lo, em especial os colegas da @practice-uffs/con-midia que lidam com as lives.

Essa issue será fechada.
