### ISSUE TITLE
Boas vindas ao novo bolsista

### ISSUE THREAD

**Issue by Claudineia-VR** [practice-uffs/programa#250]
A presente issue é referente a reunião de boas vindas do novo bolsista. Respondam o Doodle para a definição do horário: https://doodle.com/poll/24t6uan743hqfzpi?utm_source=poll&utm_medium=link

**Comment by Dovyski** [comment]
Eu acho que o Pedro marcou no doodle apenas o dia que ele gostaria, não os dias que ele pode. @practice-uffs/ger-auxilio acho que é legal mandar uma mensagem no telegram para informar sobre isso.

**Comment by alessandrapedrotti** [comment]
Documentos necessários:

[Apresentação - o que é PRACTICE](https://docs.google.com/presentation/d/1lZAYBmpdQsrJKBgqmdPe2UXVT4oIq0dJxHQN73uOdPU/edit#slide=id.g89d1ca047c_0_501)

[Manual do github](https://drive.google.com/drive/u/0/folders/1qiWTGn99_oKKl4qHFPEFTgGvFVYyhYzW)

**Comment by Claudineia-VR** [comment]
De acordo com os horários mais votados no doodle, a reunião ficou definida para o dia 06/11, nesta sexta-feira, das 16 às 17h.

**Comment by alessandrapedrotti** [comment]
Enviei aos responsáveis o convite para a reunião via google meet. Favor confirmarem por lá @practice-uffs/lideres 
O único que faltou foi o @VIF-Franca pois não localizei o endereço gmail dele na planilha de contatos.
