### ISSUE TITLE
Elaborar Organograma Organizacional

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#251]
Nessa issue será necessário criar um organograma organizacional para ter um desenho de toda a equipe, desta-se que haverá uma versão inicial e posteriormente a versão final, esse desenho poderá auxiliar na visualização de todos os membros do PRACTICE e também a comunidade acadêmica.

**Comment by VIF-Franca** [comment]
@alessandrapedrotti realizei a primeira versão, veja o que acha e podemos alterar. 

Observação: pensei em não repetir os membros que são apenas auxiliares nas demais equipes, exemplo, eu sou da ger-aux e auxílio na con-midia, sendo assim coloquei apenas na equipe principal. 


Está aqui :)

**Comment by alessandrapedrotti** [comment]
Tenho algumas sugestões:

- [ ] a ilha de design é subordinada a produção de conteúdo, então é necessário, na equipe de conteúdo, fazer a distinção de texto e imagem;
- [ ] colocar "(voluntário)" ao lado do nome dos voluntários;
- [ ] Na equipe mídia, dividir os bolsistas pelas ilhas de atuação;
- [ ] Na equipe de texto dividir as ilhas: redação (brenda, isabeli e gessica) e revisão (thalía e alessandra);
- [ ] Colocar o balãozinho dos líderes de uma cor diferente dos demais;
- [ ] No dev, dividir os bolsistas e voluntários de acordo com as ilhas web e app).

**Comment by VIF-Franca** [comment]
As alterações foram realizadas, caso ainda tenha alguma alteração realizo as alterações finais;

[https://drive.google.com/drive/u/1/folders/1T5Qdehn2SA69j49Jwau_3V6a9JXbJTII](url)

**Comment by alessandrapedrotti** [comment]
O organograma ficou muito bom! 

Tenho apenas algumas pequenas sugestões:
- [ ] O nome do Fernando está escrito errado na parte do desenvolvimento;
- [ ] Na parte do mídia, ao invés de deixar "vídeos" trocaria para "edição".

**Comment by VIF-Franca** [comment]
Alterações realizadas!

link[https://drive.google.com/drive/u/2/folders/1T5Qdehn2SA69j49Jwau_3V6a9JXbJTII](url)

**Comment by alessandrapedrotti** [comment]
Na minha visão, o organograma está pronto. Sugiro apresentarmos na próxima reunião de líderes para possível debate.

**Comment by VIF-Franca** [comment]
Perfeito, @alessandrapedrotti. 

@practice-uffs/lideres, poderiam dar uma olhada no organograma do PROGRAMA, pois, iremos discutir ele na próxima reunião (17/11).

**Comment by MaNegrao** [comment]
Como comentado na reunião de lideres, o @robisonjose e a @luizatonial são responsáveis pela ilha de vídeos e de lives respectivamente.

**Comment by VIF-Franca** [comment]
![Uploading ORGANOGRAMA XML (1) (1).png…]()

**Comment by VIF-Franca** [comment]
![ORGANOGRAMA XML (1) (1)](https://user-images.githubusercontent.com/66980370/100916845-16bad500-34b5-11eb-8e5c-7b1331d984a2.png)

**Comment by VIF-Franca** [comment]
Organograma Finalizado!
