### ISSUE TITLE
Live PROAE - 18/11 - 16:30: Oficina de apoio pedagógico: Escrita acadêmica: Resumo.

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#254]
Live solicitada pela PROAE
Oficina de apoio pedagógico: Escrita acadêmica: Resumo.

Palestrante: Profa. Dra. Tamiris Machado Gonçalves

Roteiro com todas informações na pasta. @practice-uffs/con-midia precisamos de um responsável para auxiliar.

[Pasta Drive](https://drive.google.com/drive/folders/17lJcwd8WNwThCI0ZhOxG_6UIt_CGUT-f)

**Comment by luizdameda** [comment]
@MaNegrao eu havia assumido essa live, mas recebi agora a minha grade horária desse próximo semestre que inicia dia 16/11 e não vou conseguir mais fazer. Se a aula fosse EAD eu acho que até conseguiria conciliar, mas é presencial :/

**Comment by MaNegrao** [comment]
> @MaNegrao eu havia assumido essa live, mas recebi agora a minha grade horária desse próximo semestre que inicia dia 16/11 e não vou conseguir mais fazer. Se a aula fosse EAD eu acho que até conseguiria conciliar, mas é presencial :/

Tudo certo, tu pode organizar as lives em aberto com tua grade agora.

@practice-uffs/con-midia preciso que alguém assuma a tarefa

**Comment by MilenaPaz2020** [comment]
Eu posso pegar essa!

**Comment by MaNegrao** [comment]
Live concluida com sucesso, foi a primeira utilizando o novo overlay e deu super certo, parabéns milena
