### ISSUE TITLE
Live PROAE - 19/11 - 16:30 - Oficina de apoio pedagógico: Informática Básica

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#255]
Live solicitada pela PROAE
Oficina de apoio pedagógico: Informática Básica: Pesquisas na internet e manuseio de PDF.

Palestrante: Neimar Assmann – Analista em T.I. 

Roteiro com todas informações na pasta. @practice-uffs/con-midia precisamos de um responsável para auxiliar.

[Pasta Drive](https://drive.google.com/drive/folders/1MF3Ktx-TPxtgvP37-mk5hHLFlNPtRV1X)

**Comment by MilenaPaz2020** [comment]
Não tenho disponibilidade neste dia.

**Comment by luizatonial** [comment]
> Não tenho disponibilidade neste dia.

eu tbm não

**Comment by rafaguilman** [comment]
Essa eu Faço

**Comment by MaNegrao** [comment]
@rafaguilman teste de notificação

**Comment by MaNegrao** [comment]
Live finalizada no link : https://youtu.be/vbOXz_JrCo4
