### ISSUE TITLE
Live PPGEL-Chapecó - Aula inaugural - 26/11 - 15h

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#256]
Solicitante: Simone Guesser, professora visitante do PPGEL-Chapecó

A aula será ministrada pela Profa. Eliane Silveira, da Universidade Federal de Ouro Preto. 

Eu solicitei o preenchimento do roteiro base, quando ela retornar colocarei na pasta

[Pasta Drive](https://drive.google.com/drive/folders/1SfdUvXotTdnu_NmkmAdYKK-BkZBv9GsU)

**Comment by MaNegrao** [comment]
A solicitante enviou o roteiro, o mesmo já se encontra na pasta

**Comment by MilenaPaz2020** [comment]
Live finalizada com muito sucesso!! As organizadoras elogiaram o programa e agradeceram nossa participação.
