### ISSUE TITLE
Live RP e PIBID II - 30/11 - 16:30

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#257]
Conferência do PIBID e RP

Os detalhes estão no roteiro, caso falte algo, me avisa que eu passo para os solicitantes
O roteiro já tá na pasta do drive

[Pasta Drive](https://drive.google.com/drive/folders/1tSqIgQzpcy9LA2ct1gr1jgsQCrqtrTIU)

**Comment by MilenaPaz2020** [comment]
Finalizada com sucesso! :D
