### ISSUE TITLE
Gravação de evento Online - Dia 07/11/2020

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#258]
O professor Antônio Andrioli solicitou apoio o PRACTICE para auxiliá-lo em um evento em que ele somente irá participar, sendo assim, será necessário a gravação dele no estúdio de Chapecó.

O evento acontecerá dia 07 de novembro às 10 horas da manhã;

A plataforma que será usada para a videoconferência de sábado é o zoom através do link:
https://zoom.us/j/91688809190?pwd=NzNIczNhRU5kc01aeHVMbmZDZ1VSQT09

**Comment by MaNegrao** [comment]
@VIF-Franca o evento ocorreu corretamente? podemos finalizar a tarefa?

**Comment by VIF-Franca** [comment]
Deu tudo certo @MaNegrao, o Mauricio realizou.
