### ISSUE TITLE
Montagem de vídeo com narração - Língua Espanhola

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#259]
Foi nos solicitado pela professora Maria José Laiño, a montagem de uma narração produzida por ela com os slides enviados. Abaixo está relacionado o momento de cada slide. 
A narração e os slides estão na pasta em forma de atalho

Slide 1 até 00:46
Slide 2 a partir de 00:47
Slide 3 a partir de 01:40
Slide 4 a partir de 02:31
Slide 5 a partir de 04:11
Slide 6 a partir de 05:16
Slide 7 a partir de 06:20
Slide 8 a partir de 07:22
Slide 9 a partir de 09:44
Slide 10 a partir de 11:44
Slide 11 a partir de 12:55
Slide 12 a partir de 14:09
Slide 13 a partir de 15:28
Slide 14 a partir de 16:16
Slide 15 a partir de 17:25
Slide 16 a partir de 18:49
Slide 17 a partir de 19:56

[Pasta Drive](https://drive.google.com/drive/folders/1JgmFb0r0Hx79Vib5ea4-j6lDN0DbqnPX)

CC : @practice-uffs/con-midia

**Comment by luizdameda** [comment]
Fico responsável por essa issue! Os slides serão transcritos para algum outro modelo ou será essa versão mesmo? Se for essa, ja pretendo fazer hoje

**Comment by MaNegrao** [comment]
Será esse mesmo

**Comment by luizdameda** [comment]
Duas dúvidas: 
1) Colocar a vinheta do PRACTICE no início e no fim do vídeo, juntamente com os créditos, ou não há necessidade de colocar?

2) Se puder, libera a edição dos slides para mim (solicitei já). Uma das referências está com hiperlink e quero arrumar isso.

**Comment by MaNegrao** [comment]
> Duas dúvidas:
> 
> 1. Colocar a vinheta do PRACTICE no início e no fim do vídeo, juntamente com os créditos, ou não há necessidade de colocar?
> 2. Se puder, libera a edição dos slides para mim (solicitei já). Uma das referências está com hiperlink e quero arrumar isso.

Insere a vinheta do PRACTICE ao final apenas, acho que fica menos invasivo.

Quanto ao slide, ele foi enviado pela professora, não tenho acesso de editor, o que tu pode fazer é criar uma cópia dele no seu drive e editar

**Comment by luizdameda** [comment]
Já fiz a montagem do vídeo, estou dando os últimos ajustes. A professora não falou se quer legenda ou não?

**Comment by MaNegrao** [comment]
> Já fiz a montagem do vídeo, estou dando os últimos ajustes. A professora não falou se quer legenda ou não?

Não, não foi requisitado legenda

**Comment by luizdameda** [comment]
O vídeo finalizado encontra-se [nesta pasta](https://drive.google.com/drive/u/1/folders/1OrGRtjpALzMT1IjBpvSCtbgEaGpiwTwa)

Aguardado a revisão da professora para dar como finalizado o issue

**Comment by MaNegrao** [comment]
Enviei a solicitante

**Comment by MaNegrao** [comment]
Cliente aprovou e parabenizou a equipe :D

Demanda Encerrada
