### ISSUE TITLE
[Serviços básicos] Auxílio em eventos virtuais

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/programa#26]
Um dos serviços que iremos disponibilizar no momento é o auxílio em eventos virtuais. Esse auxílio pode acontecer de muitas formas diferentes, vai depender do evento.  

Assim que mais detalhes surgirem, essa issue será devidamente editada e comentada (@Dovyski e @lcaimi).

**Comment by VIF-Franca** [comment]
Prof @phdmauricio gostaria de algumas informações sobre o evento dessa semana:

a) Data e horário;
b) Quem irá participar? 
c) Podemos utilizar o Google Meet ?  
d) Será transmitida para o canal do Youtube do PRACTICE ?
e) Quanto tempo de duração da live ?

PS.: Sugestão creio que seja necessário se conectar com 30 minutos de antecedência do evento para ajustes técnicos.

**Comment by phdmauricio** [comment]
opa, já proseamos.
