### ISSUE TITLE
Live - A educação necessária para um mundo sem pandemia - 01/12 9h

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#260]
Essa live foi solicitada pela Diretoria de Politicas de Graduação da UFFS
O evento/palestra acontecerá no dia 01/12, das 9h - 11h30min. Será aberto para participação de todos os professores que atuam nas Escolas Interculturais de Fronteira de Dionísio Cerqueira  e Bernardo de Irigoyen (AR)

As informações e o roteiro preliminar estão na pasta do drive

[Pasta Drive](https://drive.google.com/drive/folders/1-92Q7DL3KAcfku7EOah-LHx-72uPfDtQ)

CC : @practice-uffs/con-midia

**Comment by MaNegrao** [comment]
@luizatonial coloquei algumas informações no roteiro, que a solicitante me passou. Ela pediu para que passassemos um vídeo ao final da apresentação, acho tranquilo. O vídeo está na apresentação pptx dentro da pasta da issue. 

Tu pode entrar em contato com a solicitante e ir acertanto todas questões :D

**Comment by luizatonial** [comment]
@MaNegrao os slides serão apresentados pelo palestrante e eu faço somente a transmissão do vídeo, isso?
 Vi que tem uma pergunta sobre as intérpretes no roteiro também, elas já estão com os links das reuniões?

**Comment by MaNegrao** [comment]
Sim, você faz só a parte do vídeo.

Quanto as interpretes, naqueles momentos antes da live você pode passar pra elas a sala do PRACTICE

**Comment by luizatonial** [comment]
a live foi finalizada no link: https://www.youtube.com/watch?v=A1paML2tXi0&ab_channel=PRACTICEUFFS

**Comment by luizatonial** [comment]
> a live foi finalizada no link: https://www.youtube.com/watch?v=A1paML2tXi0&ab_channel=PRACTICEUFFS

fiz algumas edições no vídeo, conforme solicitado pela organização do evento.
