### ISSUE TITLE
Live PROAE - 25/11 - 16:30 - Oficina de apoio pedagógico: Escrita acadêmica: Resenha 

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#261]
Live solicitada pela PROAE
Oficina de apoio pedagógico: Escrita acadêmica: Resenha 

Palestrante: Profa. Dra. Tamiris Machado Gonçalves
Campus Cerro Largo

Roteiro com todas informações e a capa de divulgação estão na pasta do drive. 
@practice-uffs/con-midia Um membro da Ilha de lives pode assumir a tarefa e a comunicação com o solicitante (as informações de contato estão no roteiro).

[Pasta Drive](https://drive.google.com/drive/folders/1-Sa6YBXzH0phWZ-YHDOtt8ZjY0NyW-P8)

**Comment by MilenaPaz2020** [comment]
Eu assumo essa!

**Comment by MilenaPaz2020** [comment]
Live encerrada com sucesso!
