### ISSUE TITLE
Live PROAE - 02/12 - 16:30 - Oficina de apoio pedagógico: Escrita acadêmica: Artigo

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#262]
Live solicitada pela PROAE
Oficina de apoio pedagógico: Escrita acadêmica: Artigo

Palestrante: Profa. Dra. Tamiris Machado Gonçalves
Campus Cerro Largo

Roteiro com todas informações e a capa de divulgação estão na pasta do drive. 
@practice-uffs/con-midia Um membro da Ilha de lives pode assumir a tarefa e a comunicação com o solicitante (as informações de contato estão no roteiro).

[Pasta Drive](https://drive.google.com/drive/folders/1-bEngAT-y4xKH8cueSPZGcyMkQ2oweJn)

**Comment by MilenaPaz2020** [comment]
Assumo essa!

**Comment by MilenaPaz2020** [comment]
Live finalizada com sucesso! :D
