### ISSUE TITLE
Live PROAE - 03/12 - 16:30 - Oficina de apoio pedagógico: Informática Básica: Google Docs.

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#263]
Live solicitada pela PROAE
Oficina de apoio pedagógico: Informática Básica: Google Docs.

Palestrante: Neimar Assmann – mestrando em Ciência da Computação

Roteiro com todas informações e a capa de divulgação estão na pasta do drive. 
@practice-uffs/con-midia Um membro da Ilha de lives pode assumir a tarefa e a comunicação com o solicitante (as informações de contato estão no roteiro).

[Pasta Drive](https://drive.google.com/drive/folders/1-e39YPTN8JWfI2CnrAXmAIvAiGN2t72r)

**Comment by MilenaPaz2020** [comment]
Não tenho disponibilidade para esse dia.

**Comment by luizatonial** [comment]
> Não tenho disponibilidade para esse dia.

tbm não consigo fazer essa

**Comment by robisonjose** [comment]
Essa eu consigo fazer.

**Comment by robisonjose** [comment]
Ta, não consigo, fui ver o roteiro e é até as 18:30. Desculpa.

**Comment by robisonjose** [comment]
Bom dia @rafaguilman, tu conseguiria fazer essa live?

**Comment by VIF-Franca** [comment]
Eu e o @pedroamaximowski vamos tocar essa live. 

@pedroamaximowski  como será sua primeira live, podemos ir para o campus de Laranjeiras do Sul as 13:00 ?

**Comment by MilenaPaz2020** [comment]
@pedroamaximowski e @VIF-Franca, a live de hoje (02/12) era para os mesmos solicitantes. A pessoa responsável pelo apoio geral entrou em férias, desta forma a reunião do Webex não será mais feita na sala pessoal dela e sim na sala do PRACTICE. Alterei os dados no roteiro para o contato com o novo responsável pelo apoio geral.

**Comment by pedroamaximowski** [comment]
Ocorreu tudo certo na live 
https://www.youtube.com/watch?v=CFC6uDYzPx4
