### ISSUE TITLE
Live PROAE - 09/12 - 16:30 - Oficina de apoio pedagógico: Escrita acadêmica:  Apresentações em eventos acadêmicos

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#264]
Live solicitada pela PROAE
Oficina de apoio pedagógico: Escrita acadêmica: Apresentações em eventos acadêmicos

Palestrante: Profa. Dra. Tamiris Machado Gonçalves
Campus Cerro Largo

Roteiro com todas informações e a capa de divulgação estão na pasta do drive. 
@practice-uffs/con-midia Um membro da Ilha de lives pode assumir a tarefa e a comunicação com o solicitante (as informações de contato estão no roteiro).

[Pasta Drive](https://drive.google.com/drive/folders/1-jTNX0mcTfXIa-2NXLzUX6V9XTXfwBps)

**Comment by MilenaPaz2020** [comment]
Posso assumir essa!

**Comment by MilenaPaz2020** [comment]
@MaNegrao, tem duas lives com data para 09/12. Está correto?
Se sim, vou ter que deixar uma delas kkk

**Comment by MaNegrao** [comment]
Sim, e em horarios conflitantes, infelizmente. @pedroamaximowski @VIF-Franca @rafaguilman. Algum de vocês consegue assumir a que ficar em aberto?

**Comment by rafaguilman** [comment]
Quarta eu tenho aula a tarde, e é a tarde inteira

**Comment by VIF-Franca** [comment]
Quarta-feira 09/12 eu não tenho disponibilidade.

**Comment by MaNegrao** [comment]
Eu irei verificar a minha disponibilidade, creio que a principio nenhuma atividade minha bate com o horario, então posso solucionar

**Comment by MilenaPaz2020** [comment]
Encerrada com sucesso!
