### ISSUE TITLE
Gravação e Live no Estúdio - 30/11 às 19:00

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#266]
O professor Antônio Andrioli solicitou apoio à PRÁTICA para auxiliá-lo em um evento em que ele irá participar, sendo assim, será necessário a gravação dele no estúdio de Chapecó.

O evento acontecerá dia 30 de novembro às 19 horas;

**Comment by VIF-Franca** [comment]
@pedroamaximowski  tu poderá me auxiliar nesse evento que ocorrerá no Campus Laranjeiras? É de suma importância tu estás presente para testar os conhecimentos que vou tentar te passar na nossa capacitação.

**Comment by pedroamaximowski** [comment]
@VIF-Franca posso sim, estarei disponível nesse dia.

**Comment by VIF-Franca** [comment]
Perfeito!

**Comment by MaNegrao** [comment]
Evento cancelado pelo solicitante
