### ISSUE TITLE
Criação de banner - PROGRAD 

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#267]
Houve a solicitação de criação de 07 banners com as seguintes dimensões : 90 cm de largura por 1,20 metros.

O solicitante pede que: 

- [ ] As cores precisam ser convertidas em cmyk pois irá para a impressão;

- [ ] dimensões : 90 cm de largura por 1,20 metros;

**01 de 07 banners** 

**Atenção:** As identidades visuais devem seguir o manual de identidade visual da UFFS, o demandante enviou alguns modelos de banners já elaborados.

Dados dos solicitantes: 
Mariah Carraro Smaniotto --> e-mail: "Comunicação Visual" <comunicacao.visual@uffs.edu.br>; 

Arquivos no [DRIVE](https://drive.google.com/drive/u/2/folders/1GlaRQfiyRJM2lXllz1yiEmXc_1G5KsTo)

**Comment by mariagelain** [comment]
@TaynaraCh vamos trabalhar nessa demanda juntas.

**Comment by TaynaraCh** [comment]
Adicionei a imagem convertida em cmyk. Está pronto!

**Comment by TaynaraCh** [comment]
@VIF-Franca [arquivo pronto](https://drive.google.com/drive/u/0/folders/1GlaRQfiyRJM2lXllz1yiEmXc_1G5KsTo) para o feedback

**Comment by VIF-Franca** [comment]
`ARQUIVOS ENVIADOS. `

`AGUARDANDO FEEDBACK.`

**Comment by VIF-Franca** [comment]
`FEEDBACK DO CLIENTE EM DOC`

[BANNERS PROGRAD_rev.docx](https://github.com/practice-uffs/programa/files/5667236/BANNERS.PROGRAD_rev.docx)

**Comment by TaynaraCh** [comment]
Alterações realizadas, o [arquivo](https://drive.google.com/drive/u/0/folders/18coSIKSdkgHAXKISKU_F6hU-iPotUc5U) está na pasta

**Comment by VIF-Franca** [comment]
`ARQUIVOS ENVIADOS`

Qualquer solicitação reabriremos a issue.

**Comment by TaynaraCh** [comment]
[arquivo](https://drive.google.com/drive/u/0/folders/1Gq91KNnuAlzQhMEGrfSxr3OOIvHDDcpj) na pasta

**Comment by VIF-Franca** [comment]
@TaynaraCh  sempre que houver alterações por gentileza reabria a issue e colocar a tag `cliente:revisar`

**Comment by VIF-Franca** [comment]
FEEDBACK ENVIADO
