### ISSUE TITLE
Criação de banner Organograma - PROGRAD 

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#268]
Houve a solicitação de criação de 07 banners com as seguintes dimensões: 90 cm de largura por 1,20 metros.

O solicitante pede que:

- [ ]  As cores precisam ser convertidas em cmyk pois irá para a impressão;

- [ ]  Dimensões: 90 cm de largura por 1,20 metros;

- [ ] Propor um layout mais moderno e atrativo. Utilizar como referência o layout enviado pelo solicitante

**02 de 07 banners**

Atenção: As identidades visuais devem seguir o manual de identidade visual da UFFS, o demandante enviou alguns modelos de banners já elaborados.

**Dados dos solicitantes:**
Mariah Carraro Smaniotto -> e-mail: "Comunicação Visual" comunicacao.visual@uffs.edu.br ;

Arquivos no [DRIVE](https://drive.google.com/drive/u/2/folders/102-slSDJQAp-bN4s7ROGkmUST_R0crU6)

**Comment by mariagelain** [comment]
@TaynaraCh vamos trabalhar nessa demanda juntas.

**Comment by TaynaraCh** [comment]
O arquivo pronto já está na pasta.

**Comment by TaynaraCh** [comment]
@VIF-Franca [arquivo pronto](https://drive.google.com/drive/u/0/folders/102-slSDJQAp-bN4s7ROGkmUST_R0crU6) para o feedback

**Comment by VIF-Franca** [comment]
`ARQUIVOS ENVIADOS. `

`AGUARDANDO FEEDBACK.`

**Comment by VIF-Franca** [comment]
`FEEDBACK DO CLIENTE EM DOC`

[BANNERS PROGRAD_rev.docx](https://github.com/practice-uffs/programa/files/5667230/BANNERS.PROGRAD_rev.docx)

**Comment by TaynaraCh** [comment]
Ajustes concluídos, o [arquivo](https://drive.google.com/drive/u/0/folders/1haTSICEq7_S8VsHr2E48rg1tobBwQm4k) já está na pasta

**Comment by VIF-Franca** [comment]
`ARQUIVOS ENVIADOS`

Qualquer solicitação reabriremos a issue.

**Comment by VIF-Franca** [comment]
Reabrindo Issue por conta de alterações...

> Bom dia, as artes foram aprovadas. 
> 
> Só queria pedir uma pequena alteração no 2_Banner 2 #268. O e-mail está muito junto a margem branca, sugiro reduzir todo o conteúdo dentro do quadro branco para aumentar a margem interna.
> 
> Gostaria de pedir também que enviasse os arquivos em pdf em cmyk para encaminharmos para a impressão do material.

@TaynaraCh

**Comment by TaynaraCh** [comment]
Alterações concluídas, o [arquivo](https://drive.google.com/drive/u/0/folders/1WENwYqUhcpfcrVR2dEKN0a8EWiGoCToP) encontra-se na pasta de saída

**Comment by VIF-Franca** [comment]
FEEDBACK ENVIADO
