### ISSUE TITLE
Criação de banner - DPGRAD

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#269]
Houve a solicitação de criação de 07 banners com as seguintes dimensões: 90 cm de largura por 1,20 metros.

O solicitante pede que:

- [ ] As cores precisam ser convertidas em cmyk pois irá para a impressão;

- [ ]  Dimensões: 90 cm de largura por 1,20 metros;

- [ ]  Informações enviadas pelo solicitante: Logo da UFFS, o nome e sigla do setor, um pouco menor a informação da PROGAD, com o e-mail menor embaixo:
> DPGRAD
> Diretoria de Políticas de Graduação
> PROGRAD - Pró-Reitoria de Graduação
> dir.dpg@uffs.edu.br

**03 de 07 banners**

Atenção: As identidades visuais devem seguir o manual de identidade visual da UFFS, o demandante enviou alguns modelos de banners já elaborados.

Dados dos solicitantes:
Mariah Carraro Smaniotto -> e-mail: "Comunicação Visual" comunicacao.visual@uffs.edu.br ;

Arquivos no [DRIVE](https://drive.google.com/drive/u/2/folders/1xBTJfzEv69AAFX8x-4uV_mhzcBgucAch)

**Comment by mariagelain** [comment]
@TaynaraCh vamos trabalhar nessa demanda juntas.

**Comment by TaynaraCh** [comment]
Adicionei a imagem convertida para cmyk. Está pronto!

**Comment by TaynaraCh** [comment]
@VIF-Franca [arquivo pronto](https://drive.google.com/drive/u/0/folders/1xBTJfzEv69AAFX8x-4uV_mhzcBgucAch) para o feedback

**Comment by VIF-Franca** [comment]
`ARQUIVOS ENVIADOS. `

`AGUARDANDO FEEDBACK.`

**Comment by VIF-Franca** [comment]
`FEEDBACK DO CLIENTE EM DOC`

[BANNERS PROGRAD_rev.docx](https://github.com/practice-uffs/programa/files/5667227/BANNERS.PROGRAD_rev.docx)

**Comment by VIF-Franca** [comment]
`ARQUIVOS ENVIADOS`

Qualquer solicitação reabriremos a issue.

**Comment by TaynaraCh** [comment]
[arquivo](https://drive.google.com/drive/u/0/folders/1BANfMycQ0Xux5XwblKS_QO4B3nBgkLss) está na pasta

**Comment by VIF-Franca** [comment]
@TaynaraCh  sempre que houver alterações por gentileza reabria a issue e colocar a tag `cliente:revisar`

**Comment by VIF-Franca** [comment]
FEEDBACK ENVIADO
