### ISSUE TITLE
Live PROAE - 14/12 - 16:30 - Oficina de apoio pedagógico: Matemática básica: Estudo de funções

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#270]
Live solicitada pela PROAE
Oficina de apoio pedagógico: Matemática básica: Estudo de funções

Leonardo Furtado – Engenheiro Ambiental e Sanitário/UFFS

Roteiro com todas informações e a capa de divulgação estão na pasta do drive. 
@practice-uffs/con-midia Um membro da Ilha de lives pode assumir a tarefa e a comunicação com o solicitante (as informações de contato estão no roteiro).

[Pasta Drive](https://drive.google.com/drive/folders/10RK_oOzL3Od2oA3Sq61hhRHxm_EUUdsI)

**Comment by MilenaPaz2020** [comment]
Eu posso assumir essa! :D

**Comment by luizatonial** [comment]
o @rafaguilman finalizou a live no canal da PROAE https://www.youtube.com/watch?v=GjbcDI9s7vA&ab_channel=Pr%C3%B3-ReitoriadeAssuntosEstudantisUFFS.
