### ISSUE TITLE
Criação de banner sobre Programas - DPGRAD

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#271]
Houve a solicitação de criação de 07 banners com as seguintes dimensões: 90 cm de largura por 1,20 metros.

O solicitante pede que:

- [ ] As cores precisam ser convertidas em cmyk pois irá para a impressão;

- [ ] Dimensões: 90 cm de largura por 1,20 metros;

- [ ] Mapa mental utilizando a referência enviada pelo solicitante

`Texto central do mapa:`
Programas e Políticas da Graduação

`Setas:`

> ●	Estágios
> ●	Monitorias de Ensino
> ●	Tutoria Acadêmica
> ●	Mobilidade Acadêmica
> ●	Programa de Educação Tutorial – PET
> ●	Programa Institucional de Bolsa de Iniciação à Docência – PIBID
> ●	Programa Residência Pedagógica – RP
> ●	Programa de Acesso e Permanência dos Povos Indígenas - PIN
> ●	Programa de Acesso à Educação Superior da UFFS para Estudantes Haitianos – PROHAITI
> ●	Programa de Acesso e Permanência a Estudantes Imigrantes - PRÓ-IMIGRANTE
> ●	Grupos de Estudos
> ●	Política de Acessibilidade

PROGRAD - Pró-Reitoria de Graduação
dir.dpg@uffs.edu.br

**04 de 07 banners**

Atenção: As identidades visuais devem seguir o manual de identidade visual da UFFS, o demandante enviou alguns modelos de banners já elaborados.

Dados dos solicitantes:
Mariah Carraro Smaniotto -> e-mail: "Comunicação Visual" comunicacao.visual@uffs.edu.br ;

Arquivos no [DRIVE](https://drive.google.com/drive/u/2/folders/1AFkDGBoth7qtpTuQBvv1giLmNnQN2-cp)

**Comment by mariagelain** [comment]
@TaynaraCh vamos trabalhar nessa demanda juntas.

**Comment by TaynaraCh** [comment]
O arquivo pronto já está na pasta.

**Comment by TaynaraCh** [comment]
@VIF-Franca [arquivo pronto](https://drive.google.com/drive/u/0/folders/1AFkDGBoth7qtpTuQBvv1giLmNnQN2-cp) para o feedback

**Comment by VIF-Franca** [comment]
`ARQUIVOS ENVIADOS. `

`AGUARDANDO FEEDBACK.`

**Comment by VIF-Franca** [comment]
`FEEDBACK DO CLIENTE EM DOC`

[BANNERS PROGRAD_rev.docx](https://github.com/practice-uffs/programa/files/5667220/BANNERS.PROGRAD_rev.docx)

**Comment by TaynaraCh** [comment]
Alterações concluídas, o [arquivo](https://drive.google.com/drive/u/0/folders/1H5-buZOoBfi7wsyXEOZPlFFTBvIrw3-2) já está na pasta.

**Comment by VIF-Franca** [comment]
`ARQUIVOS ENVIADOS`

Qualquer solicitação reabriremos a issue.

**Comment by TaynaraCh** [comment]
[arquivo](https://drive.google.com/drive/u/0/folders/1WD_jKNzHN_z4hXKMg0h8Mgj2LRwLO42M) na pasta

**Comment by VIF-Franca** [comment]
@TaynaraCh  sempre que houver alterações por gentileza reabria a issue e colocar a tag `cliente:revisar`

**Comment by VIF-Franca** [comment]
FEEDBACK ENVIADO
