### ISSUE TITLE
Criação banner - DOP

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#272]
Houve a solicitação de criação de 07 banners com as seguintes dimensões: 90 cm de largura por 1,20 metros.

- [ ] O solicitante pede que:

- [ ] As cores precisam ser convertidas em cmyk pois irá para a impressão;
 
- [ ] Dimensões: 90 cm de largura por 1,20 metros;

- [ ] Logo da UFFS, o nome e sigla do setor, um pouco menor a informação da PROGAD, com o e-mail menor embaixo 
> DOP
> Diretoria de Organização Pedagógica
> PROGRAD - Pró-Reitoria de Graduação
> dir.dop@uffs.edu.br

 
05 de 07 banners

Atenção: As identidades visuais devem seguir o manual de identidade visual da UFFS, o demandante enviou alguns modelos de banners já elaborados.

Dados dos solicitantes:
Mariah Carraro Smaniotto -> e-mail: "Comunicação Visual" comunicacao.visual@uffs.edu.br ;

Arquivos no [DRIVE](https://drive.google.com/drive/u/2/folders/1RQi2mSP-MZtJTfgln3Bjvzhf1IG0kEVq)

**Comment by mariagelain** [comment]
@TaynaraCh vamos trabalhar nessa demanda juntas.

**Comment by TaynaraCh** [comment]
Adicionei o arquivo convertido em cmyk na pasta. Está pronto!

**Comment by TaynaraCh** [comment]
@VIF-Franca [arquivo pronto](https://drive.google.com/drive/u/0/folders/1RQi2mSP-MZtJTfgln3Bjvzhf1IG0kEVq) para o feedback

**Comment by VIF-Franca** [comment]
`ARQUIVOS ENVIADOS. `

`AGUARDANDO FEEDBACK.`

**Comment by TaynaraCh** [comment]
Alterações concluídas, [arquivo](https://drive.google.com/drive/u/0/folders/1Rgv5K9WM-sQ8_7YHW2JXfXblUcRjN1vH) já está na pasta

**Comment by VIF-Franca** [comment]
`ARQUIVOS ENVIADOS`

Qualquer solicitação reabriremos a issue.

**Comment by TaynaraCh** [comment]
[arqiuvo](https://drive.google.com/drive/u/0/folders/1i-Qlv6k3Axyq3jdyzxZvXVj_N7a_kLMB) na pasta

**Comment by VIF-Franca** [comment]
@TaynaraCh  sempre que houver alterações por gentileza reabria a issue e colocar a tag `cliente:revisar`

**Comment by VIF-Franca** [comment]
FEEDBACK ENVIADO
