### ISSUE TITLE
Criação de banner - DRA 

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#273]
Houve a solicitação de criação de 07 banners com as seguintes dimensões: 90 cm de largura por 1,20 metros.

 O solicitante pede que:

 

- [x] As cores precisam ser convertidas em cmyk pois irá para a impressão;

- [x]  Dimensões: 90 cm de largura por 1,20 metros;

- [x] DRA - Diretoria de Registro Acadêmico
**Departamento de Controle Acadêmico - DCA**
> • Ingresso de estudantes
> • Gestão da permanência dos estudantes

**Divisão de Gerenciamento de Diplomas - DGD**
> • Registro e expedição de diplomas da UFFS
> • Registro de diplomas de IES não universitárias
> • Revalidação de diplomas expedidos no exterior

**PROGRAD - Pró-Reitoria de Graduação**
dir.dra@uffs.edu.br

06 de 07 banners

Atenção: As identidades visuais devem seguir o manual de identidade visual da UFFS, o demandante enviou alguns modelos de banners já elaborados.

Dados dos solicitantes:
Mariah Carraro Smaniotto -> e-mail: "Comunicação Visual" comunicacao.visual@uffs.edu.br ;

Arquivos no [DRIVE](https://drive.google.com/drive/u/2/folders/1almbBdAA04tuWkdEQqzDaTxvqxFZFrZz)

**Comment by mariagelain** [comment]
@TaynaraCh vamos trabalhar nessa demanda juntas.

**Comment by TaynaraCh** [comment]
Para esse banner não está especificado em lugar algum que é para ter/fazer um organograma, mas na pasta tem um exemplo, o que eu faço?

**Comment by TaynaraCh** [comment]
Fiz sem ser um organograma, e adicionei na pasta o arquivo convertido em cmyk

**Comment by TaynaraCh** [comment]
@VIF-Franca [arquivo pronto](https://drive.google.com/drive/u/0/folders/1almbBdAA04tuWkdEQqzDaTxvqxFZFrZz) para o feedback

**Comment by VIF-Franca** [comment]
`ARQUIVOS ENVIADOS. `

`AGUARDANDO FEEDBACK.`

**Comment by VIF-Franca** [comment]
FEEDBACK DO CLIENTE EM DOC

BANNERS PROGRAD_rev.docx

**Comment by TaynaraCh** [comment]
Alterações concluídas, o [arquivo](https://drive.google.com/drive/u/0/folders/1OTXOgvZKQtSn9ryRqSY6FsUhCIbx4oIX) está pronto na pasta

**Comment by VIF-Franca** [comment]
"ARQUIVOS ENVIADO" 

Qualquer solicitação reabriremos a issue.

**Comment by TaynaraCh** [comment]
[arquivo](https://drive.google.com/drive/u/0/folders/1MMF1yCbKIKGGUfLf_L-Yl59TtZyK6FxN) está na pasta

**Comment by VIF-Franca** [comment]
@TaynaraCh  sempre que houver alterações por gentileza reabria a issue e colocar a tag `cliente:revisar`

**Comment by VIF-Franca** [comment]
FEEDBACK ENVIADO
