### ISSUE TITLE
Criação de Banner - PI 

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#274]
Houve a solicitação de criação de 07 banners com as seguintes dimensões: 90 cm de largura por 1,20 metros.

 O solicitante pede que:

- [ ]  As cores precisam ser convertidas em cmyk pois irá para a impressão;

 - [ ] Dimensões: 90 cm de largura por 1,20 metros;

OBS: É um canal de interlocução entre a Instituição e o Ministério da Educação  para as funções de regulação, supervisão e avaliação do Ensino Superior, no âmbito do Sistema Nacional de Avaliação da Educação Superior (SINAES).

Principais ações desenvolvidas:
I. Inserção de informações no Sistema e-MEC;
II. Coordenação da coleta de dados para o Censo da Educação Superior;
III. Colaboração com as coordenações de curso em todas as etapas do Exame Nacional de Desempenho dos Estudantes - ENADE.

--> pi.reitoria@uffs.edu.br

 
**07 de 07 banners**

Atenção: As identidades visuais devem seguir o manual de identidade visual da UFFS, o demandante enviou alguns modelos de banners já elaborados.

Dados dos solicitantes:
Mariah Carraro Smaniotto -> e-mail: "Comunicação Visual" comunicacao.visual@uffs.edu.br ;

**Comment by mariagelain** [comment]
@TaynaraCh vamos trabalhar nessa demanda juntas.

**Comment by TaynaraCh** [comment]
Essa issue está sem pasta.
Se os exemplos enviados forem iguais aos das outras pastas, pode-se dizer que o layout dessa está pronto.

**Comment by VIF-Franca** [comment]
Isso, os exemplos são iguais. 

Poderia por gentileza colocar na pasta a versão para ser enviada ao solicitante.

> Essa issue está sem pasta.
> Se os exemplos enviados forem iguais aos das outras pastas, pode-se dizer que o layout dessa está pronto.

**Comment by TaynaraCh** [comment]
Criei a [pasta](https://drive.google.com/drive/u/0/folders/1y8r1Alucw9jYMsBZGqFgAORakwBYM7LR)

**Comment by VIF-Franca** [comment]
`ARQUIVOS ENVIADOS. `

`AGUARDANDO FEEDBACK.`

**Comment by VIF-Franca** [comment]
`FEEDBACK DO CLIENTE EM DOC NA PASTA`

[BANNERS PROGRAD_rev.docx](https://github.com/practice-uffs/programa/files/5667196/BANNERS.PROGRAD_rev.docx)

**Comment by TaynaraCh** [comment]
Alterações concluídas, o [arquivo](https://drive.google.com/drive/u/0/folders/1RQ0yVGFzTH6hdQjgxFhcu44g0TVRmv9x) está pronto e na pasta.

**Comment by VIF-Franca** [comment]
`ARQUIVOS ENVIADOS`

Qualquer solicitação reabriremos a issue.

**Comment by TaynaraCh** [comment]
[arquivo](https://drive.google.com/drive/u/0/folders/16e4HcCJ2lZGS8mGsCqRlLrIsLT1yMb0U) na pasta

**Comment by VIF-Franca** [comment]
@TaynaraCh  sempre que houver alterações por gentileza reabria a issue e colocar a tag `cliente:revisar`

**Comment by VIF-Franca** [comment]
FEEDBACK ENVIADO
