### ISSUE TITLE
Elaborar uma imagem base para ser utilizada no feed e uma nos stories

### ISSUE THREAD

**Issue by Claudineia-VR** [practice-uffs/programa#275]
Como solicitado na issue #242, devem ser elaborados elementos visuais para melhor atender as movimentações da equipe de comunicação. Entre esses elementos **devem ser elaboradas 2 imagens base para serem utilizadas no instagram, sendo uma para o feed e outra para os stories.** Essas imagens estarão na pasta "tarefas" na sub-pasta [programa#275](https://drive.google.com/drive/u/0/folders/1w02bCHJXlv0xYzTaLYRjCQw8uzyrEPFN) .

**Comment by morgana-mo** [comment]
[https://drive.google.com/drive/u/0/folders/1w02bCHJXlv0xYzTaLYRjCQw8uzyrEPFN](pasta)

**Comment by morgana-mo** [comment]
Elaboramos alguns modelos de base para o feed, precisamos de opiniões....

![1](https://user-images.githubusercontent.com/71781124/98727378-918d4600-2376-11eb-9290-64273c5d5caa.png)
![3](https://user-images.githubusercontent.com/71781124/98727381-93570980-2376-11eb-81ef-d833f7e3f1a0.png)
![5](https://user-images.githubusercontent.com/71781124/98727383-93efa000-2376-11eb-958f-c502d68756c1.png)

**Comment by morgana-mo** [comment]
Seguem os modelos  para history


![1](https://user-images.githubusercontent.com/71781124/98852706-d2e52a80-2436-11eb-98d9-8e2a00cc571d.png)
![2](https://user-images.githubusercontent.com/71781124/98852711-d4165780-2436-11eb-9870-a69d387242b0.png)
![3](https://user-images.githubusercontent.com/71781124/98852713-d4165780-2436-11eb-9f73-31a08e3cb6de.png)

**Comment by morgana-mo** [comment]
@alessandrapedrotti  ou @VIF-Franca quem eu marco pra opinar nessa escolha?
Adicionei um label de Gráfico Revisar

**Comment by alessandrapedrotti** [comment]
> @alessandrapedrotti ou @VIF-Franca quem eu marco pra opinar nessa escolha?
> Adicionei um label de Gráfico Revisar

Acredito que eu mesma, hahaah
Vou pedir ajuda da @estelavilasboas na avaliação meninas, mas na minha opinião, acho que vocês desenvolveram bem, maaaas podem fazer mais, desenvolver alguns modelos mais criativos e diferentes do que foi posto.

**Comment by estelavilasboas** [comment]
Nós já temos algo semelhante na issue #39 ([pasta](https://drive.google.com/drive/folders/1omcXGjV_pfP1I3yTdkTUnG96SOPWNjde)), caso elas queiram dar uma olhada. Explicado a organização dos arquivos: eles estão nomeados com "Carrosel parte 1", "Carrossel parte 2", etc. E os que estão apenas nomeados como "Carrossel", são todas as "partes" juntas.

Agora falando do que foi realizado, eu particularmente prefiro os Modelos 2 e 3 de Stories, e o Modelo 1 da base para o feed, por dois motivos: pela composição dos elemento e por focar mais nos tons de azul, enquanto os tons quentes dão contrastes apenas em uma região específica da imagem. 
Porém, concordo com a Alessandra. Vocês são livres para criar/"dar a louca"/ousar. Não precisam ficar presas nas ondas e elementos já criados.
Por exemplo, no calendário de divulgação, vocês fizeram um trabalho lindo com a utilização de cores, bélissimo mesmo. Ficou simples, limpo, moderno e não tirou a essência (por assim dizer) do programa. 
Vocês podem brincar com formas, sobreposição e tudo além do alcance, desde que mantenha um design moderno e limpo.

Eu diria que estão bem encaminhadas, mas eu gostaria de ver mais opções diferentes.

**Comment by anacarolinamorigi** [comment]
Como solicitado, desenvolvemos [esses modelos](https://drive.google.com/drive/folders/1jbi-7Gdo-nmax3Pv85OSQWRMo9FEBGhZ?usp=sharing) para o feed. 

Pensamos nele como uma sequência de elementos que podem ser alterados, desde a ordem quanto a parte de cores, para ficar algo divertido e sem se tornar repetitivo de se observar. Ficamos no retorno do feedback de vocês para possíveis alterações ou novas criações!

**Comment by alessandrapedrotti** [comment]
> Como solicitado, desenvolvemos [esses modelos](https://drive.google.com/drive/folders/1jbi-7Gdo-nmax3Pv85OSQWRMo9FEBGhZ?usp=sharing) para o feed.
> 
> Pensamos nele como uma sequência de elementos que podem ser alterados, desde a ordem quanto a parte de cores, para ficar algo divertido e sem se tornar repetitivo de se observar. Ficamos no retorno do feedback de vocês para possíveis alterações ou novas criações!

Gostei bastante! Esses modelos tem uma vibe moderna e mais divertida do que os anteriores. Meu preferido foi o modelo 2, mas a ideia de ir alternando a depender do post é muito boa.

**Comment by morgana-mo** [comment]
Elaboramos novos modelos para Stories eles estão [aqui](https://drive.google.com/drive/u/0/folders/1vioetiqTPzEbHuom69wcDUEYOGf6e_yX)Pensamos nele como uma sequência de elementos que podem ser alterados, desde a ordem quanto a parte de cores, para ficar algo divertido e sem se tornar repetitivo de se observar como os modelos criados para o feed. Ficamos no retorno do feedback de vocês para possíveis alterações ou novas criações!

**Comment by morgana-mo** [comment]
Olá elaboramos [novos modelos para os stories](https://drive.google.com/drive/u/0/folders/1vioetiqTPzEbHuom69wcDUEYOGf6e_yX). Pensamos neles como uma sequência de elementos que podem ser alterados, quanto a parte de cores, para ficar algo divertido e sem se tornar repetitivo de se observar e talvez acompanhar as variações que irão ser vistas no feed. Ficamos no retorno do feedback de vocês para possíveis alterações ou novas criações!

**Comment by alessandrapedrotti** [comment]
Meninas, gostei bastante da pegada moderna dos modelos (e eles estão combinandinho com a proposta pro feed que vocês fizeram).
 Acho que agora vale pensarem em um esquema de fontes e elementos (setas e afins) para serem utilizados.

**Comment by estelavilasboas** [comment]
Eu tenho algumas sugestões.

Primeiro, eu acho que seria legal pensar (se já não fizeram isso) como esses modelos ficariam em conjunto, vistos "de cima". Exemplo:
![image](https://user-images.githubusercontent.com/30927758/99289100-48783e80-281b-11eb-9786-235b309622b8.png)

Analisar como as cores dos modelos de vocês ficariam ordenadas. (Espero que tenham conseguido entender o que eu quis dizer)

> Observação: Não estou falando para refazer, pelo contrário, o trabalho ficou maravilhoso. Estou sugerindo que analisem isso.


Segundo, sugestão de cores:  
No fundo amarelo, letra azul escura. 
No fundo azul claro, letra branca.
No fundo branco, letra azul escura.

Lembrando que a fonte principal do programa é Roboto.  😄

**Comment by anacarolinamorigi** [comment]
> Eu tenho algumas sugestões.
> 
> 
> 
> Primeiro, eu acho que seria legal pensar (se já não fizeram isso) como esses modelos ficariam em conjunto, vistos "de cima". Exemplo:
> 
> ![image](https://user-images.githubusercontent.com/30927758/99289100-48783e80-281b-11eb-9786-235b309622b8.png)
> 
> 
> 
> Analisar como as cores dos modelos de vocês ficariam ordenadas. (Espero que tenham conseguido entender o que eu quis dizer)
> 
> 
> 
> > Observação: Não estou falando para refazer, pelo contrário, o trabalho ficou maravilhoso. Estou sugerindo que analisem isso.
> 
> 
> 
> 
> 
> Segundo, sugestão de cores:  
> 
> No fundo amarelo, letra azul escura. 
> 
> No fundo azul claro, letra branca.
> 
> No fundo branco, letra azul escura.
> 
> 
> 
> Lembrando que a fonte principal do programa é Roboto.  😄 
> 
> 
> 
> > Observação 2: Foquem na palavra "sugestão".

Realmente ele organizado em feed não fica com uma aparência muito agradável, vou tentar organizar melhor e talvez só utilizar só alguns dos modelos.

  ![image](https://user-images.githubusercontent.com/71719917/99683448-1fe08680-2a5f-11eb-8c86-6b4e41bb6971.jpeg)

**Comment by morgana-mo** [comment]
Uma ideia que me veio agora, porque a gente não usa por exemplo três postagens seguidas cada base, talvez agrade mais aos olhos.

**Comment by anacarolinamorigi** [comment]
Finalizei as possíveis modificações nas cores, a partir dos modelos já presentes, elas se encontram [nessa pasta](https://drive.google.com/drive/folders/1jbi-7Gdo-nmax3Pv85OSQWRMo9FEBGhZ?usp=sharing). Outra ponto, um dos possíveis modelos de organização de feed, além da ideia da morgana-mo que é ótima, seria essa.

[image](https://user-images.githubusercontent.com/71719917/99752521-40dac300-2ac3-11eb-9e80-cec0cb42e2c5.jpeg)

Fico no aguardo de feedbacks!

**Comment by alessandrapedrotti** [comment]
> Finalizei as possíveis modificações nas cores, a partir dos modelos já presentes, elas se encontram [nessa pasta](https://drive.google.com/drive/folders/1jbi-7Gdo-nmax3Pv85OSQWRMo9FEBGhZ?usp=sharing). Outra ponto, um dos possíveis modelos de organização de feed, além da ideia da morgana-mo que é ótima, seria essa.
> 
> ![image](https://user-images.githubusercontent.com/71719917/99752634-6ec00780-2ac3-11eb-9c6b-944b0320d5f0.jpeg)
> 
> Fico no aguardo de feedbacks!

Gostei muito Ana!! Podemos começar a utilizar esses modelos. Na reunião de semana que vem podemos  discutir mais questões referentes à utilização dos modelos.
