### ISSUE TITLE
Edição de vídeo PPGE - Linhas de Pesquisa

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#276]
Recebemos mais uma demanda de edição de vídeo da PPGE. O solicitante quer que o vídeo tenha os seguintes passos

- [x] Edição básica
- [x] Inserir vinhetas da PPGE antes e depois ([Link aqui](https://drive.google.com/drive/folders/1sx34HeEbVhIiPdrw-xbfuolkhxUI7cWO)), no tema do vídeo deve estar escrito "Linhas de Pesquisa"
- [x] Créditos e vinheta do PRACTICE ao final.
- [x] Produzir e Inserir legendas

O Bruto está linkado na pasta

[Pasta Drive](https://drive.google.com/drive/folders/10k3sou7qS3-aeI3tDbvZ0ZX9ULodgz8o)

CC: @practice-uffs/con-midia

**Comment by luizdameda** [comment]
O que seria edição básica? Seria referente a melhoria de qualidade de iluminação e som? Não entendi muito bem kkkk. 

E a legenda pode ser aos moldes dos vídeos de letras, amarelo com contorno preto, ou a solicitante quer outro modelo?

**Comment by MaNegrao** [comment]
> O que seria edição básica? Seria referente a melhoria de qualidade de iluminação e som? Não entendi muito bem kkkk.
> 
> E a legenda pode ser aos moldes dos vídeos de letras, amarelo com contorno preto, ou a solicitante quer outro modelo?

Sim, é uma edição básica de cortes pequenos e essas coisas!

As legendas podem ser feitas da forma dos vídeos de letras, mas você pode usar o VLC também, tem as duas opções, mas faz em amarelo e preto, visto que já fizemos um outro video da ppge na issue #221

**Comment by luizdameda** [comment]
@MaNegrao tu sabe ou consegue ver pra mim qual é o site oficial do PPGE? Ela falo no finalzinho do vídeo para dispor a página eletrônica no rodapé do vídeo, mas não sei qual é

**Comment by MaNegrao** [comment]
> @MaNegrao tu sabe ou consegue ver pra mim qual é o site oficial do PPGE? Ela falo no finalzinho do vídeo para dispor a página eletrônica no rodapé do vídeo, mas não sei qual é

https://www.uffs.edu.br/campi/chapeco/cursos/mestradoch/mestrado-em-educacao/apresentacao-1 eu acho que é esse

**Comment by luizdameda** [comment]
A legenda e o vídeo estão [nesta pasta](https://drive.google.com/drive/u/1/folders/1mL9Tl_IH3uVu4yz6FdoC6PClzu0yl_uI).

É um vídeo curto, já corrigir alguns erros que vi, mas alguém do @practice-uffs/con-conteudo dá uma revisada, por favor. :)

**Comment by thaliafriedrich** [comment]
> A legenda e o vídeo estão [nesta pasta](https://drive.google.com/drive/u/1/folders/1mL9Tl_IH3uVu4yz6FdoC6PClzu0yl_uI).
> 
> É um vídeo curto, já corrigir alguns erros que vi, mas alguém do @practice-uffs/con-conteudo dá uma revisada, por favor. :)

Revisei! Fiz as correções que faltavam.

**Comment by luizdameda** [comment]
O vídeo finalizado encontra-se [nesta pasta](https://drive.google.com/drive/u/1/folders/1j-ionZObbse7Zx0PPr8WfP-Z-BpoRyce)

@MaNegrao encaminha ele para a solicitante revisar, se for aprovado, pode encerrar a issue.

**Comment by luizdameda** [comment]
O vídeo finalizado encontra-se [nesta pasta](https://drive.google.com/drive/u/1/folders/1j-ionZObbse7Zx0PPr8WfP-Z-BpoRyce)

@MaNegrao encaminha o vídeo para a solicitante revisar, se for aprovado, pode encerrar a issue.

**Comment by MaNegrao** [comment]
Beleza

**Comment by MaNegrao** [comment]
Cliente aprovou, demanda finalizada!
