### ISSUE TITLE
Live PPGEL - Minicurso Introdução à periferia esquerda dia 1 - 07/12 - 9h

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#277]
Solicitante: Simone Guesser, professora visitante do PPGEL-Chapecó

Minicurso Introdução à periferia esquerda (Oferecido pelo do Programa de Pós-graduação em Estudos Linguísticos da UFFS) parte 1. 

O roteiro base está na pasta do drive. @practice-uffs/con-midia Um membro da Ilha de lives pode assumir a tarefa e a comunicação com o solicitante (as informações de contato estão no roteiro).

[Pasta Drive](https://drive.google.com/drive/folders/1k-XhMrnzPYOrqOJIX6iWY0h31EieRt2c)

**Comment by MilenaPaz2020** [comment]
Live encerrada com sucesso.
