### ISSUE TITLE
Live PPGEL - Minicurso Introdução à periferia esquerda dia 2 - 08/12 - 9h

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#278]
Solicitante: Simone Guesser, professora visitante do PPGEL-Chapecó

Minicurso Introdução à periferia esquerda (Oferecido pelo do Programa de Pós-graduação em Estudos Linguísticos da UFFS) parte 1. 

O roteiro base está na pasta do drive. @practice-uffs/con-midia Um membro da Ilha de lives pode assumir a tarefa e a comunicação com o solicitante (as informações de contato estão no roteiro).

[Pasta Drive](https://drive.google.com/drive/folders/1wNavx_tFHCJQXU3NM6pQPRuDwEMCZ9BJ)

**Comment by luizatonial** [comment]
Acho que a descrição está errada, essa seria dia 08/12, certo?

**Comment by MaNegrao** [comment]
> Acho que a descrição está errada, essa seria dia 08/12, certo?

Yep, 8/12, vou corrigir, obrigado ;D

**Comment by luizatonial** [comment]
Live concluída no link: https://www.youtube.com/watch?v=c7DDnxWaBlk&ab_channel=PRACTICEUFFS
