### ISSUE TITLE
Live PPGEL - Mesa Redonda: Desafios da Construção do Conhecimento - 01/12 - 19:30h

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#279]
Live solicitade pela PPGEL

Ministrante(s) 
Profa. Dra. Gesualda dos Santos Rasia (UFPR) 			
Profa. Dra. Maria Cleci Venturini (Unicentro) 			
Profa. Dra. Aline Cassol Daga Cavalheiro (UFFS)

O roteiro está na pasta do drive com todas as informações. A @luizatonial sinalizou que ficará responsável

[Pasta Drive](https://drive.google.com/drive/folders/10msl4CuLbqNKCJteqOAtuPDHv1l-wNoA)

**Comment by luizatonial** [comment]
a apresentação cultural foi cancelada, então a live iniciará as 19:30h

**Comment by luizatonial** [comment]
live finalizada no link: https://www.youtube.com/watch?v=2fS2fTEzoYE&t=1767s&ab_channel=PRACTICEUFFS
