### ISSUE TITLE
[Cartilha] Videoconferências e Lives

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/programa#28]
É necessário criar uma cartilha que explique como realizar uma boa videoconferência em diferentes casos, como aulas ou reuniões transmitidas.

Assim que mais detalhes surgirem, essa issue será devidamente editada e comentada (@Dovyski e @lcaimi).

**Comment by franca20** [comment]
Fase em elaboração...

**Comment by franca20** [comment]
Elaborei uma versão **preliminar** da cartilha, seguindo algumas sugestões do prof Mauricio. Segue em anexo em dois formatos word e pdf, ao realizar alguma sugestão deixar sinalizada. 

[cartilha live 30.06.2020.pdf](https://github.com/practice-uffs/programa/files/4853146/cartilha.live.30.06.2020.pdf)

[cartilha live - 30.06.2020.docx](https://github.com/practice-uffs/programa/files/4853145/cartilha.live.-.30.06.2020.docx)

**Comment by VIF-Franca** [comment]
Boa tarde pessoal da equipe @practice-uffs/con-material.

Postei no drive em formato editável a versão preliminar da cartilha em questão, poderiam dar um help na parte textual ?  Caso tenha alguma sugestão de adicionar item ou retirar fiquem a vontade.

**Comment by VIF-Franca** [comment]
Boa tarde professores, @Dovyski @phdmauricio e @lcaimi poderiam analisar a cartilha por gentileza... abraço

**Comment by phdmauricio** [comment]
@VIF-Franca são estas que estao aqui em pdf? ou estao no drive?

**Comment by VIF-Franca** [comment]
> @VIF-Franca são estas que estao aqui em pdf? ou estao no drive?

estão no drive prof, https://drive.google.com/drive/u/0/folders/10VDtEpDWeidA4trcMRLzjXnz80vbTtrH

**Comment by alessandrapedrotti** [comment]
> Boa tarde pessoal da equipe @practice-uffs/con-material.
> 
> Postei no drive em formato editável a versão preliminar da cartilha em questão, poderiam dar um help na parte textual ? Caso tenha alguma sugestão de adicionar item ou retirar fiquem a vontade.

Você poderia disponibilizar o arquivo em formato editável para a revisão? Ficaria muito mais fácil.

**Comment by VIF-Franca** [comment]
> > Boa tarde pessoal da equipe @practice-uffs/con-material.
> > Postei no drive em formato editável a versão preliminar da cartilha em questão, poderiam dar um help na parte textual ? Caso tenha alguma sugestão de adicionar item ou retirar fiquem a vontade.
> 
> Você poderia disponibilizar o arquivo em formato editável para a revisão? Ficaria muito mais fácil.
> 
> @VIF-Franca

Oii, creio que está em formato editável no drive, link da pasta: https://drive.google.com/drive/u/0/folders/10VDtEpDWeidA4trcMRLzjXnz80vbTtrH

Está em formato de Apresentação Google... Não está conseguindo editar ? Aparece algum erro ?

**Comment by Dovyski** [comment]
@alessandrapedrotti  quando acessar o link do drive, clica com o botão direito do mouse sobre o arquivo do @VIF-Franca e escolhe "Abrir com Google Slides". Ele vai deixar tu abrir e editar o arquivo usando o Google (mesmo que o arquivo seja um PowerPoint do Office).

**Comment by Dovyski** [comment]
Minhas requisições:

- [ ] Utilizar fonte textual `Roboto` para todo o documento, não `Arial` ou `Times New Roman`.
- [ ] Reduzir bastante o tamanho do texto para "edição ..." que tem na esquerda da página
- [ ] Remover o negrito de todos os textos do documento. Somente título e subtítulos em negrito.
- [ ] Colocar um rodapé em todas as páginas, em tamanho bem pequeno e centralizado, com o texto:

```
Universidade Federal da Fronteira Sul - UFFS
Programa de Ampliação e Consolidação de Tecnologias e Inovação no Contexto Educacional - PRACTICE
https://practice.uffs.edu.br
```

- [ ] @practice-uffs/con-material precisa revisar termos do texto para ficar um pouco menos informal.

**Comment by alessandrapedrotti** [comment]
> Minhas requisições:
> 
> * [ ]  Utilizar fonte textual `Roboto` para todo o documento, não `Arial` ou `Times New Roman`.
> * [ ]  Reduzir bastante o tamanho do texto para "edição ..." que tem na esquerda da página
> * [ ]  Remover o negrito de todos os textos do documento. Somente título e subtítulos em negrito.
> * [ ]  Colocar um rodapé em todas as páginas, em tamanho bem pequeno e centralizado, com o texto:
> 
> ```
> Universidade Federal da Fronteira Sul - UFFS
> Programa de Ampliação e Consolidação de Tecnologias e Inovação no Contexto Educacional - PRACTICE
> https://practice.uffs.edu.br
> ```
> 
> * [ ]  @practice-uffs/con-material precisa revisar termos do texto para ficar um pouco menos informal.

**Comment by VIF-Franca** [comment]
> Minhas requisições:
> 
> * [x]  Utilizar fonte textual `Roboto` para todo o documento, não `Arial` ou `Times New Roman`.
> * [x]  Reduzir bastante o tamanho do texto para "edição ..." que tem na esquerda da página
> * [x]  Remover o negrito de todos os textos do documento. Somente título e subtítulos em negrito.
> * [x]  Colocar um rodapé em todas as páginas, em tamanho bem pequeno e centralizado, com o texto:
> 
> ```
> Universidade Federal da Fronteira Sul - UFFS
> Programa de Ampliação e Consolidação de Tecnologias e Inovação no Contexto Educacional - PRACTICE
> https://practice.uffs.edu.br
> ```
> 
> * [ ]  @practice-uffs/con-material precisa revisar termos do texto para ficar um pouco menos informal.


Pessoal realizada as alterações solicitada pelo professor @Dovyski 


**Algumas pontuações:** 
i) qual capa acham melhor a (1) ou a (2)? Coloquei com os dois formatos da nossa logo;
ii) na pág com os créditos de produção gostaria de saber se está OK;
iii) @alessandrapedrotti ajustei os seus comentários que havia deixado no drive, aguardo seu _feedback_;
iv) sobre as imagens que alterei coloquei a fonte é o suficiente ?

**Comment by phdmauricio** [comment]
i) Gostei mais da capa com o nome completo da logo. A primeira.
ii) Sugiro que na página dos crédito coloque o nome do Redator, dos revisores e de toda a Equipe Practice abaixo. Sem descrever tal como esta na portaria do programa. Destaque o Redator, quem contribui na revisão, e abaixo, Equipe PRactice, em ordem alfabética. (Lembre-se que o prof. Odair saiu da Equipe).

**Comment by phdmauricio** [comment]
v) Na última página da cartilha você pode colocar o Logo Marca d'Água, aí teremos os dois.

**Comment by alessandrapedrotti** [comment]
> Minhas requisições:
> 
> * [x]  Utilizar fonte textual `Roboto` para todo o documento, não `Arial` ou `Times New Roman`.
> * [x]  Reduzir bastante o tamanho do texto para "edição ..." que tem na esquerda da página
> * [x]  Remover o negrito de todos os textos do documento. Somente título e subtítulos em negrito.
> * [x]  Colocar um rodapé em todas as páginas, em tamanho bem pequeno e centralizado, com o texto:
> 
> ```
> Universidade Federal da Fronteira Sul - UFFS
> Programa de Ampliação e Consolidação de Tecnologias e Inovação no Contexto Educacional - PRACTICE
> https://practice.uffs.edu.br
> ```
> 
> * [ ]  @practice-uffs/con-material precisa revisar termos do texto para ficar um pouco menos informal.

Revisão do texto será feita no dia 09/07.

**Comment by VIF-Franca** [comment]
> i) Gostei mais da capa com o nome completo da logo. A primeira.
> ii) Sugiro que na página dos crédito coloque o nome do Redator, dos revisores e de toda a Equipe Practice abaixo. Sem descrever tal como esta na portaria do programa. Destaque o Redator, quem contribui na revisão, e abaixo, Equipe PRactice, em ordem alfabética. (Lembre-se que o prof. Odair saiu da Equipe).

Realizada as alterações prof

**Comment by alessandrapedrotti** [comment]
Texto devidamente revisado. Também arrumei a disposição dos créditos na pg 14, para que ficasse tudo alinhado.

**Comment by phdmauricio** [comment]
De minha parte esta ok, apenas analisem se vão ampliar esta cartilha com a nova demanda, ou fazer duas.

**Comment by elisribas** [comment]
Estou realizando a revisão geral da cartilha.

Importante atentarmos **sempre** para algumas questões.
Padronizar em nossos conteúdos termos em inglês. Na cartilha, as vezes aparece em itálico, as vezes sem. Por exemplo _live_ e live. Quando o termo já está convencionado em português, vamos usar sempre sem itálico. Exemplos: live, chat, login, online.

Alterei as orientações para certificação, o mais indicado é que a pessoa disponibilize um link de um form do Drive, criado anteriormente, para facilitar as inscrições dos participantes. 

Videoaula não tem acento. ok? Videoaula e não vídeoaula.

Vamos evitar usar termos computacionais para falar com nosso público, por exemplo: quando o usuário estiver online. Usar termos que identifiquem esse usuário: participante, estudante, professor, organizador. 

Parei de revisar na parte "Possíveis dúvidas técnicas". Volto na segunda. ♡♡

**Comment by VIF-Franca** [comment]
Perfeito @elisribas e @alessandrapedrotti.

Em breve adiciono a ampliação da cartilha.

**Comment by elisribas** [comment]
Estou realizando a revisão geral da cartilha.

Importante atentarmos **sempre** para algumas questões.
Padronizar em nossos conteúdos termos em inglês. Na cartilha, as vezes aparece em itálico, as vezes sem. Por exemplo _live_ e live. Quando o termo já está convencionado em português, vamos usar sempre sem itálico. Exemplos: live, chat, login, online.

Alterei as orientações para certificação, o mais indicado é que a pessoa disponibilize um link de um form do Drive, criado anteriormente, para facilitar as inscrições dos participantes. 

Videoaula não tem acento.

**Comment by elisribas** [comment]
Voltando! Fiz diversas alterações  e descrevo as mais significativas para futuras produções.

Terminei de revisar a cartilha. Como é nossa primeira experiência, quero registrar aqui várias questões, além das já mencionadas anteriormente, que poderão servir de modelo para futuras cartilhas, orientações, dicas, etc... **Não sei se terei condições de revisar sempre os materiais, por isso peço atenção especial de quem for produzir e revisar @VIF-Franca @alessandrapedrotti.**

- Nomes de ferramentas como, Google Meet, Skype, Zoom, não precisam levar itálico, porque embora sejam  descritos em outro idioma, trata-se do nome da ferramenta e não de um termo em inglês.
- No termo "abaixo está a tela", o correto é dizer que "abaixo está a imagem/ ilustração da tela", porque não é a tela real que está aparecendo e sim uma cópia dela. 
- Conferir a numeração dos passos. Exemplo, após o texto "O que fazer no decorrer da reunião?" - estava "2º Ter um mediador é importante". Não havia um 1º passo e com isso toda a numeração a seguir estava equivocada;
- Em outro tópico estava escrito "Ruídos e interação, como resolver?" O título deu a antender que seriam abordados questões sobre ruídos e sobre interação,  contudo o conteúdo abordava apenas questões sobre ruídos, a seguir tinha outro título falando apenas sobre interação. Os títulos precisam remeter ao conteúdo descrito. 

Em relação à descrição "**Realização**", recomendo tirar os nomes do Fernando e Maurício como coordenadores e levar seus nomes para junto da equipe e deixar apenas como destaque as pessoas que produziram esse material. Assim, poderemos ter esse mesmo padrão nas demais produções. Caso venham a manter como está, será preciso inverter os nomes, pois o Coordenador Geral é o Maurício e o Adjunto é o Fernando.

@alessandrapedrotti veja minhas observações para poder fazer esse tipo de correção também (títulos, numeração, créditos etc).

❥❥

**Comment by VIF-Franca** [comment]
Olá adicionei @alessandrapedrotti e @elisribas como havia registrado realizei a ampliação da cartilha, gostaria de pedir um help para vocês apenas nas páginas 14, 15 e 16 (as que adicionei hoje) 

@elisribas e @alessandrapedrotti  muito obrigado pelos apontamentos e ajustes realizados até o momento na cartilha. Vocês são feras nisso rsrsrs.

**Comment by elisribas** [comment]
@VIF-Franca Ótimas dicas! Revisei, ajustei algumas orientações. Veja meu comentário na página 14 sobre o ajuste no brilho.

Agora a @alessandrapedrotti pode fazer a revisão das páginas 14, 15 e 16.

**Comment by Dovyski** [comment]
Eu gostaria de fazer uma revisão final de tipografia da cartilha antes do lançamento dela. Deixo aqui o registro para, quando o conteúdo estiver revisado, me biparem.

**Comment by alessandrapedrotti** [comment]
Revisão textual finalizada no dia 20/07.
No texto ainda existem alguns comentários que não foram fechados, acredito que a @elisribas esteja trabalhando neles.

O produto final ficou muito bom!
@Dovyski

**Comment by VIF-Franca** [comment]
@Dovyski tem alguma sugestão de modificação ou inclusão ?

**Comment by alessandrapedrotti** [comment]
A revisão textual dessa cartilha já está pronta. Basta a ger~encia aprová-la para ela ir para o site.
@practice-uffs/ger

**Comment by lcaimi** [comment]
Comentários da revisão:

- capa: 
Atual: CARTILHA PARA CRIAÇÃO E CONDUÇÃO DE VIDEOCONFERÊNCIA
Sugestão: CARTILHA PARA CRIAÇÃO E CONDUÇÃO DE VIDEOCONFERÊNCIAS E LIVES

- Qual plataforma utilizar:
Sugestão: Indicar qual daquelas ferramentas permite a gravação direta da reunião  - @VIF-Franca

- Haverá registro de presença e certificação? como será?
Comentário: achei estranha a expressão ..., o inglês, live, ... no meio da frase. É assim mesmo?
Sugestão: colocar o link para algum tutorial de criação de formulário de inscrição do Youtube. O ideal seria fazermos um nosso e colocar o link aqui - @VIF-Franca

- Geral
Sugestão: toda vez que aparecer a palavra "live" ou "lives", colocá-la em itálico.

 @practice-uffs/con-conteudo

**Comment by alessandrapedrotti** [comment]
> Comentários da revisão:
> 
> * capa:
>   Atual: CARTILHA PARA CRIAÇÃO E CONDUÇÃO DE VIDEOCONFERÊNCIA
>   Sugestão: CARTILHA PARA CRIAÇÃO E CONDUÇÃO DE VIDEOCONFERÊNCIAS E LIVES
> * Qual plataforma utilizar:
>   Sugestão: Indicar qual daquelas ferramentas permite a gravação direta da reunião  - @VIF-Franca
> * Haverá registro de presença e certificação? como será?
>   Comentário: achei estranha a expressão ..., o inglês, live, ... no meio da frase. É assim mesmo?
>   Sugestão: colocar o link para algum tutorial de criação de formulário de inscrição do Youtube. O ideal seria fazermos um nosso e colocar o link aqui - @VIF-Franca
> * Geral
>   Sugestão: toda vez que aparecer a palavra "live" ou "lives", colocá-la em itálico.
> 
> @practice-uffs/con-conteudo

Alteração do título feita.
Sobre a sugestão do itálico na palavra "live", respondi o comentário no documento com a orientação que nos foi passada pela elis.
Também resolvi outros 2 apontamentos feitos no documento.
Aguardo as alterações de conteúdo que devem ser feitas pelo @VIF-Franca para fazer mais uma leitura de revisão.

**Comment by VIF-Franca** [comment]
@alessandrapedrotti realizada os ajustes, destaco que houve alteração na redação apenas nas páginas 04, 05 e 16.

**Comment by alessandrapedrotti** [comment]
@VIF-Franca Fiz a leitura de revisão só nas páginas citadas acima e deixei alguns comentários para você resolver.
Aguardo o retorno para encerrarmos a tarefa.

**Comment by VIF-Franca** [comment]
Alterações realizadas @alessandrapedrotti

**Comment by alessandrapedrotti** [comment]
Revisão finalizada e versão atualizada na pasta de saída.
