### ISSUE TITLE
Fazer treinamento básico do github com o novo bolsista

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#280]
O novo bolsista do programa, o [pedroamaximowski](https://github.com/pedroamaximowski), precisará ser treinado no github. O treinamento é o mesmo que foi dado para os membros anteriores. Assim como a ger-aux fez a reunião de boas-vindas com o bolsista, esse treinamento será feito por uma equipe do programa (a @practice-uffs/dev, no caso)

O objetivo dessa issue é designar um membro da equipe @practice-uffs/dev que fará esse treinamento com o Pedro. Depois que isso for definido, acertar um horário para que ambos se reúnam online. O Pedro já recebeu a apresentação de boas-vindas. Ele precisa de uns 30 minutos de explicação sobre como o Github funciona (labels, repositórios, como marcar pessoas, como abrir e fechar issues, etc).

**Comment by andrewmsilva** [comment]
Vou conversar com ele no privado para organizarmos isso.

**Comment by andrewmsilva** [comment]
Treinamento feito e, aparentemente, tudo foi compreendido com êxito. @pedroamaximowski já está pronto pra trabalhar 😄
