### ISSUE TITLE
Elaborar imagem para divulgação de eventos (nossos ou de parcerias)

### ISSUE THREAD

**Issue by Claudineia-VR** [practice-uffs/programa#282]
Como solicitado na issue #242, devem ser elaborados elementos visuais para melhor atender as movimentações da equipe de comunicação. Entre esses elementos deve ser elaborada uma imagem para divulgação de eventos (nossos ou de parcerias) para ser utilizada no instagram. Essa imagem estará na pasta "tarefas" na sub-pasta [programa#282](https://drive.google.com/drive/u/0/folders/1kKmMPBlk3bpzTb4CUP9qQbYpx2j6N1gU).

**Comment by Claudineia-VR** [comment]
As possíveis imagens para divulgação de eventos foram elaboradas e se encontram na pasta ''tarefas'', na subpasta [programa#282](https://drive.google.com/drive/u/0/folders/1kKmMPBlk3bpzTb4CUP9qQbYpx2j6N1gU). Aguardo revisão e sugestões de qual ficou melhor e como posso melhora-la.

**Comment by anacarolinamorigi** [comment]
> As possíveis imagens para divulgação de eventos foram elaboradas e se encontram na pasta ''tarefas'', na subpasta [programa#282](https://drive.google.com/drive/u/0/folders/1kKmMPBlk3bpzTb4CUP9qQbYpx2j6N1gU). Aguardo revisão e sugestões de qual ficou melhor e como posso melhora-la.

Gostei muito dos modelos 1 e 5, creio que eles combinam mais com o que está sendo organizado com o feed e os stories!

**Comment by alessandrapedrotti** [comment]
Podemos seguir utilizando o modelo 5, pois acredito que seja o mais de acordo com a nossa identidade atual.

Favor mover uma cópia editável para a pasta materiais, junto com os outros modelos do instagram.
Assim que essa movimentação for concluída, essa issue deve ser fechada.

**Comment by estelavilasboas** [comment]
Meu coração foi conquistado pelo 5. 
Só tenho algumas sugestões:

**Comment by Claudineia-VR** [comment]
Ótimo, já modifiquei de acordo com as sugestões, a issue foi movida para a pasta ''materiais'' subpasta [Imagens para divulgação](https://drive.google.com/drive/u/0/folders/1sSHqn4f9kZBwVyvzjCrmy1daDxhT1QW6)
