### ISSUE TITLE
Elaborar imagem que indique novidades no site e/ou app

### ISSUE THREAD

**Issue by Claudineia-VR** [practice-uffs/programa#283]
Como solicitado na issue #242, devem ser elaborados elementos visuais para melhor atender as movimentações da equipe de comunicação. Entre esses elementos deve ser elaborada uma imagem que indique novidades no site e/ou app, para ser utilizada no instagram. Essa imagem estará na pasta "tarefas" na sub-pasta [programa#283](https://drive.google.com/drive/u/0/folders/1nijyiGJt5rGrZBLG81gyfjMlSOFNiRI6).

**Comment by morgana-mo** [comment]
Uma ideia inicial seria essa, mas acho por bem criar uma no formato de history pra adicionar o link do site e por a opção de arrastar para cima
![Temos novidades no site](https://user-images.githubusercontent.com/71781124/98859958-b7335180-2441-11eb-9c5b-6b2ff07a8800.png)

**Comment by morgana-mo** [comment]
Elaborei essa para os history, o que acham?
![TEMOS NOVIDADES NO NOSSO SITE](https://user-images.githubusercontent.com/71781124/98861143-910eb100-2443-11eb-9a7e-66fb005def60.png)

**Comment by morgana-mo** [comment]
@alessandrapedrotti  @VIF-Franca  olhem estes que eu criei para indicar atualizações no site. Era algo assim ou fugi totalmente da ideia da sugestão?

**Comment by alessandrapedrotti** [comment]
> @alessandrapedrotti @VIF-Franca olhem estes que eu criei para indicar atualizações no site. Era algo assim ou fugi totalmente da ideia da sugestão?

Eu gostei bastante das produções, ficou bem dentro da identidade do programa.

Vocês podem conversar com a @TaynaraCh pra mais ideias (pois ela criou novos templates de cartilha que ficaram lindos demais).

**Comment by andrewmsilva** [comment]
Conforme solicitado, fiz alguns prints da versão atual do app, os quais estão [nessa pasta](https://drive.google.com/drive/u/0/folders/1_GKYMhXBfnethOr25VznTYSKV_A7eLdh). Não precisa usar todas, escolham a que estiver mais legal.

**Comment by VIF-Franca** [comment]
Achei todos lindos, 
Parabéns!!!

**Comment by morgana-mo** [comment]
Criei alguns modelos para stories usando uma das identidades visuais criada na issue #275, eles estão [nessa pasta ](https://drive.google.com/drive/u/0/folders/15zg0CW1sA836SmG5ThKJ_dAsUY4U-ypd)

**Comment by morgana-mo** [comment]
[Nessa pasta](https://drive.google.com/drive/u/0/folders/1fwDHUFR5T2lhQzznYFckWZ4ypTK-BbnO) se encontram alguns testes que eu fiz para o feed.

**Comment by andrewmsilva** [comment]
Eu gostei bastante, só tenho algumas sugestões pra dar. Acho que poderia tem um pouco mais de margem ou talvez os elementos fossem um pouquinho menores. Outra coisa, as imagens com o aplicativo poderiam ser editadas para remover os cantinhos e ajustar com a borda do celular, que é arredondada igual a do notebook nas outras imagens.

**Comment by morgana-mo** [comment]
[Aqui](https://drive.google.com/drive/u/0/folders/1hgFSCS7ROn9qHILWTn7uog6gduKbyE6Y) se encontram as novas versões seguindo as sugestões solicitadas Fico no aguardo de novos feedbacks!

**Comment by alessandrapedrotti** [comment]
Meninas, gostei muito das propostas, acredito que já possamos começar a utiliza-las no instagram. A única que não me agradou muito foi a proposta para stories com a caixa azul escrito "new", acho que esse elemento destoou muito do restante da identidade e tudo mais.

**Comment by morgana-mo** [comment]
> Meninas, gostei muito das propostas, acredito que já possamos começar a utiliza-las no instagram. A única que não me agradou muito foi a proposta para stories com a caixa azul escrito "new", acho que esse elemento destoou muito do restante da identidade e tudo mais.

@alessandrapedrotti também achei que a versão com a caixa azul escrito "new" destoou do restante, as removi das pastas e se não há mais considerações as issue pode ser finalizada. Novos layouts como esses podem ser solicitados na issue de postagens de cada quinzena (vou explicar melhor na reunião essa proposta que é uma forma da gente da @practice-uffs/ger-comunicacao nos organizarmos melhor com as postagens)

**Comment by alessandrapedrotti** [comment]
fecharei a issue e fico no aguardo da sua apresentação de proposta na nossa reunião.
