### ISSUE TITLE
Montagem de vídeo 2 com narração - Língua Espanhola

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#284]
Foi nos solicitado pela professora Maria José Laiño, a montagem de mais uma narração produzida por ela com os slides enviados. Abaixo está relacionado o momento de cada slide.
A narração e os slides estão na pasta em forma de atalho.
Nesse segundo vídeo acho que é necessário um tratamento de ruídos no áudio

Slide 1 até 00:54
Slide 2 a partir de 00:55
Slide 3 a partir de 01:55
Slide 4 a partir de 03:07
Slide 5 a partir de 03:57
Slide 6 a partir de 05:32
Slide 7 a partir de 08:37
Slide 8 a partir de 09:54
Slide 9 a partir de 11:57
Slide 10 a partir de 12:53
Slide 11 a partir de 13:28
Slide 12 a partir de 14:27
Slide 13 a partir de 14:45
Slide 14 a partir de 16:06
Slide 15 a partir de 18:11
Slide 16 a partir de 19:00
Slide 17 a partir de 20:04
Slide 18 a partir de 22:58

[Pasta Drive](https://drive.google.com/drive/folders/1SaF98d326A7sSr5Qw-z83DLlmDpIHbYN)

CC : @practice-uffs/con-midia

**Comment by luizdameda** [comment]
O vídeo finalizado encontra-se [nesta pasta](https://drive.google.com/drive/u/1/folders/17uFbNxYw9uZ1nyTpamCvl1dgcBFAGYmR). Tentei dar uma arrumada no áudio, não sei se mudou muita coisa porque não tenho muita experiência com edição de áudio, a meu ver ficou bom, mas caso seja necessário, posso tentar melhorar ele mais.

@MaNegrao encaminha o vídeo para a professora revisar, por favor!!

**Comment by MaNegrao** [comment]
Foi enviado para prof

**Comment by MaNegrao** [comment]
Vídeo finalizado
