### ISSUE TITLE
Planilha de dados trimestrais

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#285]
É necessário elaborar um modelo de planilha a ser preenchido pelos líderes de equipe que quantifique:

- Vídeos editados;
- Lives realizadas;
- Páginas escritas;
- Páginas revisadas;
- Roteiros criados;
- Áudios editados;
- Horas gastas em projetos.
+ Sugestões

Essa planilha servirá de base para a "prestação de contas" do programa para a comunidade e será alimentada constantemente pela equipe. Ela deve ser separada por equipe de trabalho.

**Comment by Claudineia-VR** [comment]
Você quis dizer que devem ser separadas por área de trabalho? ou é por equipe mesmo? No caso de serem equipes elas precisam ser fixas, caso contrário dificulta bastante adequar isso em uma planilha, eu precisaria saber quais são essas equipes.

**Comment by alessandrapedrotti** [comment]
> Você quis dizer que devem ser separadas por área de trabalho? ou é por equipe mesmo? No caso de serem equipes elas precisam ser fixas, caso contrário dificulta bastante adequar isso em uma planilha, eu precisaria saber quais são essas equipes.

As equipes de trabalho são: con-conteúdo, con desing, con-mídia e dev. Acho que o que tu entende por área é o que estamos acostumados a chamar de equipes.

**Comment by VIF-Franca** [comment]
@Claudineia-VR , qual horário que podemos marcar para alinharmos sobre a planilha de dados trimestrais?

**Comment by Claudineia-VR** [comment]
Desculpem pela demora, eu já estava trabalhando nela, na verdade eu conclui ela ontem, está disponível para revisão na pasta "tarefas" e sub-pasta [programa#285](https://drive.google.com/drive/u/0/folders/1J28DMZhspsWHwK6yNgcqMOYjWCsgL3Fz). Coloquei inicialmente um escopo geral que servirá como a "prestação de contas", e nas demais abas coloquei elas separadas por área e com espaço para descrever as atividades. Aguardo feedbacks!

**Comment by alessandrapedrotti** [comment]
> Desculpem pela demora, eu já estava trabalhando nela, na verdade eu conclui ela ontem, está disponível para revisão na pasta "tarefas" e sub-pasta [programa#285](https://drive.google.com/drive/u/0/folders/1J28DMZhspsWHwK6yNgcqMOYjWCsgL3Fz). Coloquei inicialmente um escopo geral que servirá como a "prestação de contas", e nas demais abas coloquei elas separadas por área e com espaço para descrever as atividades. Aguardo feedbacks!

@practice-uffs/lideres @practice-uffs/ger

**Comment by MaNegrao** [comment]
Tenho duas sugestões. 

O pessoal do mídia também produz roteiros para as produções internas, então acho que seria interessante ter esse também esse serviço no midia. Se eu não me engano todos os vídeos instrucionais técnicos o pessoal do midia fez os roteiros e teve a revisão do con-con. 

Outro ponto é que nós no midia também produzimos alguns vídeos internos no PRACTICE, que envolvem o que eu falei antes, mas também envolvem gravação, pesquisa e posteriormente a edição.  Então ter algo como "vídeos produzidos" seria legal, até para diferenciar os vídeos de clientes com os vídeos que o próprio PRACTICE faz

**Comment by VIF-Franca** [comment]
> Desculpem pela demora, eu já estava trabalhando nela, na verdade eu conclui ela ontem, está disponível para revisão na pasta "tarefas" e sub-pasta [programa#285](https://drive.google.com/drive/u/0/folders/1J28DMZhspsWHwK6yNgcqMOYjWCsgL3Fz). Coloquei inicialmente um escopo geral que servirá como a "prestação de contas", e nas demais abas coloquei elas separadas por área e com espaço para descrever as atividades. Aguardo feedbacks!

Ficou muito bom, deixo algumas ideias de aprimoramento do documento... 

a) adicionar no detalhamento uma coloca, "issue", sendo assim, seria possível adicionar o número da issue e ter como "rastrear" as tarefas; 
b) Creio que podemos adicionar a equipe ger (auxilio e comunicação), creio que o organizacional demanda tempo e membros exclusivos do programa; 
c) apenas para deixar registrado no arquivo (para as próximas gerações), adicionar notas para explicar o que é cada informação em especifico que devem ser inclusas no arquivo; 

Deixo essas sugestões.

**Comment by estelavilasboas** [comment]
"Elementos visuais estabelecidos" me parece muito vago. O design desenvolve identidades visuais, materiais gráficos de divulgação (panfletos, folders, flyers, overlay das Lives), e também tem a revisão gráfica das produções internas da con-conteúdo. 
Não sei se irão optar por descrever o materiais gráficos por página/arquivo ou por trabalho realizado. Penso que depende muito de como serão divididos os demais dados.

Agora vou deixar aqui minha declaração de desenvolvedora de software (e como eu tenho um pézinho no dev), "Aplicativos desenvolvidos" no dev me parece um tanto quanto irrealista, principalmente por se tratar de dados trimestrais. Isso é o @andrewmsilva que vai dizer de certeza.

**Comment by Claudineia-VR** [comment]
@MaNegrao já adicionei suas sugestões na planilha;

@VIF-Franca também adicionei suas sugestões a) e b), quanto a b, preciso de algo breve para citas quais são os tipos de trabalhos prestados, aceito sugestões. Quanto a c), bem, acredito que a parte da descrição já esteja dentro da aba de cada área especifica nas tabelas de detalhamento;

@estelavilasboas concordo que o termo é vago, porém, todos os trabalhos realizados serão descritos na tabela de detalhamento dentro da aba de cada área, penso que desta forma mais resumida do escopo geral seja mais fácil visualizar todos os trabalhos realizados de maneira geral. De qualquer modo se conseguirem pensar em outros nomes para ''os tipos de trabalhos prestados'' de forma ampla eu troco, ou então se acharem que devo mudar o formato da planilha para detalhar mais; 
 
Tenho um pouco de dificuldade ainda para entender os trabalhos específicos de cada área, estou pensando de forma mais ampla e deixando espaço para que estes possam ser descritos, mas todas as sugestões são bem vindas para melhorar este documento. ;)

**Comment by mariagelain** [comment]
> @MaNegrao já adicionei suas sugestões na planilha;
> 
> @VIF-Franca também adicionei suas sugestões a) e b), quanto a b, preciso de algo breve para citas quais são os tipos de trabalhos prestados, aceito sugestões. Quanto a c), bem, acredito que a parte da descrição já esteja dentro da aba de cada área especifica nas tabelas de detalhamento;
> 
> @estelavilasboas concordo que o termo é vago, porém, todos os trabalhos realizados serão descritos na tabela de detalhamento dentro da aba de cada área, penso que desta forma mais resumida do escopo geral seja mais fácil visualizar todos os trabalhos realizados de maneira geral. De qualquer modo se conseguirem pensar em outros nomes para ''os tipos de trabalhos prestados'' de forma ampla eu troco, ou então se acharem que devo mudar o formato da planilha para detalhar mais;
> 
> Tenho um pouco de dificuldade ainda para entender os trabalhos específicos de cada área, estou pensando de forma mais ampla e deixando espaço para que estes possam ser descritos, mas todas as sugestões são bem vindas para melhorar este documento. ;)

creio que para o design de para adicionar identidades visuais, materiais gráficos de divulgação, e revisão gráfica na descrição de atividades da equipe, para que não fique muito vago.

**Comment by andrewmsilva** [comment]
> Agora vou deixar aqui minha declaração de desenvolvedora de software (e como eu tenho um pézinho no dev), "Aplicativos desenvolvidos" no dev me parece um tanto quanto irrealista, principalmente por se tratar de dados trimestrais. Isso é o @andrewmsilva que vai dizer de certeza.

Respondendo a @estelavilasboas, posso dizer com certeza que é quase impossível produzir um app em um trimestre. Além do mais, geralmente nenhum sistema fica 100% pronto, pois sempre há algo a mais pra desenvolver, uma funcionalidade nova, coisas assim. Desenvolvimento é um processo evolutivo. 

Confesso que é realmente difícil estabelecer métricas pra dev, tanto que isso é um tema de pesquisa bem recorrente na área. Pra simplificar, no dev poderia ser por funcionalidades implementadas, issues resolvidas, coisas assim. Mas aí pode ficar simplificado demais. De qualquer forma, é só uma sugestão

**Comment by MaNegrao** [comment]
Eu estava pensando e tenho uma sugestão de métrica que podemos usar no mídia. Que são horas ou minutos de vídeos editados e lives feitas, ia ficar parecido com a questão dos textos que é por página. O que acham?

**Comment by VIF-Franca** [comment]
> @MaNegrao já adicionei suas sugestões na planilha;
> 
> @VIF-Franca também adicionei suas sugestões a) e b), quanto a b, preciso de algo breve para citas quais são os tipos de trabalhos prestados, aceito sugestões. Quanto a c), bem, acredito que a parte da descrição já esteja dentro da aba de cada área especifica nas tabelas de detalhamento;
> 
> @estelavilasboas concordo que o termo é vago, porém, todos os trabalhos realizados serão descritos na tabela de detalhamento dentro da aba de cada área, penso que desta forma mais resumida do escopo geral seja mais fácil visualizar todos os trabalhos realizados de maneira geral. De qualquer modo se conseguirem pensar em outros nomes para ''os tipos de trabalhos prestados'' de forma ampla eu troco, ou então se acharem que devo mudar o formato da planilha para detalhar mais;
> 
> Tenho um pouco de dificuldade ainda para entender os trabalhos específicos de cada área, estou pensando de forma mais ampla e deixando espaço para que estes possam ser descritos, mas todas as sugestões são bem vindas para melhorar este documento. ;)

Ótimo!

Quanto ao item b), seguem as sugestões: 
- **Atendimento ao cliente** (exclusivamente responder os e-mails e informações pertinentes)
- **Construção de balanço de resultados das equipes** (Visa sistematizar as informações brutas de cada equipe para relatórios)
- **Secretariado** (participar das reuniões de todas as equipes e elaboração de documentos internos)

Quanto ao item c), é como no exemplo acima: cada item que consta nas planilhas poderia ser especificado por meio de uma nota de rodapé

Ex:
 Nº DE TRABALHOS CONCLUÍDOS -----> Refere-se ao total de trabalhos entregues ao cliente, que tramitou por todo fluxo de trabalho das equipes, supervisão da gerência e que posteriormente teve aprovação do cliente.

PÁGINAS ESCRITAS -----> Refere-se à todo documento que possua estrutura básica de um texto: introdução, desenvolvimento e conclusão, que contenha no mínimo "xxxx" caracteres.

OBS: De início, parece muitos detalhes desnecessários, porém isso fará uma diferença futuramente quando outros membros precisarem das informações, pois já estarão padronizadas e estará claro o que propõe cada item.

**Comment by Claudineia-VR** [comment]
Certo, na primeira aba da planilha, abaixo da tabela criei uma legenda para descrever cada item e estou descrevendo as que eu sei. Acredito que fique mais fácil se vocês definirem quais são os melhores nomes dos ''tipos de trabalhos'' para cada área se acaso os que eu coloquei não forem adequados.

**Comment by alessandrapedrotti** [comment]
Gostei bastante do que vi até agora @Claudineia-VR. Debateremos os possíveis refinamentos da tabela na reunião da equipe de auxílio gerencial essa semana.

**Comment by Claudineia-VR** [comment]
Aos interessados, mais alguma sugestão de melhoria na planilha? peço que se manifestem para que eu possa concluir e então fechar essa issue.

**Comment by luizatonial** [comment]
> Aos interessados, mais alguma sugestão de melhoria na planilha? peço que se manifestem para que eu possa concluir e então fechar essa issue.

Estávamos conversando na reunião da mídia hoje sobre utilizar alguns dados das lives do PRACTICE, talvez como o número de visualizações e o tempo de exibição... acho que o @robisonjose sabe explicar melhor.

**Comment by Claudineia-VR** [comment]
Acho isso relevante, porém, acredito que nesta planilha o tempo de exibição das lives estará somado ao ''Total de horas dedicadas'', e o número de visualizações pode ser exposto na parte de ''Detalhamento'' na coluna de ''Descrição''. Não sei separa vocês faz sentido, mas no caso de acrescentar uma coluna ou linha para essas informações as das outras atividades do mídia e das demais equipes ficariam com espaços vazios... 

O que acham, da para manter como está e vocês exporem na descrição as informações extras?

**Comment by robisonjose** [comment]
Boa tarde, @Claudineia-VR.

Acredito que daria para fazer como você mencionou.

**Comment by Claudineia-VR** [comment]
A planilha foi concluída e movida para a pasta ''materiais'' na subpasta [Comunicação](https://drive.google.com/drive/u/0/folders/1A4jbR8swV0riz_IXbrWkr1b5rX5uFGZD).
