### ISSUE TITLE
Apresentação do novo bolsista

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#286]
Passada a reunião inicial de apresentação do @pedroamaximowski ao programa, seguem algumas informações:
O bolsista será integrado na equipe @practice-uffs/con-midia e se dedicará a ilha de lives;

**Segue a primeira tarefa:**

O novo integrante do projeto deve elaborar um texto de apresentação sobre si mesmo. Esse texto será utilizado para divulgações e posts nas redes sociais do programa e também serve para que os antigos membros do PRACTICE conheçam melhor o novo bolsista.
É importante que seja respeitado o limite de 500 caracteres no texto de apresentação e que se tenha claro que esse texto poderá sofrer alterações por questões de clareza, concordância e erros gramaticais.

Caso você tenha dúvidas de como escrever, confiram as respostas dos membros mais antigos na issue #167.

A apresentação obrigatoriamente deve conter:

Nome completo ou nome social;
1 foto que mostre claramente o rosto da pessoa (sem óculos escuros, chapéus e outros adereços).

**Comment by alessandrapedrotti** [comment]
Também é necessário o preenchimento da 3ª aba da tabela de membros e equipes - [HORÁRIOS](https://docs.google.com/spreadsheets/d/15kGGrER8UTGQhPIvGm2jHhs3pEO6f7gqISZgRyqpMKE/edit#gid=1145326100).

@VIF-Franca favor conferir as permissões da planilha, para que o Pedro possa inserir as informações dele.

**Comment by pedroamaximowski** [comment]
Pedro Augusto Maximowski é acadêmico do curso de Engenharia de Aquicultura da Universidade Federal da Fronteira SUL (UFFS) Campus de Laranjeiras do Sul, gosta de praticar esportes principalmente ciclismo, voluntario em um projeto de pesquisa, e nas horas vagas gosta de beber ou então assistir uma série ou filme.
![WhatsApp Image 2020-11-13 at 16 05 26](https://user-images.githubusercontent.com/74254374/99113418-fc848a00-25cd-11eb-9b8d-9b52a4fa2542.jpeg)

**Comment by VIF-Franca** [comment]
> Pedro Augusto Maximowski é acadêmico do curso de Engenharia de Aquicultura da Universidade Federal da Fronteira SUL (UFFS) Campus de Laranjeiras do Sul, gosta de praticar esportes principalmente ciclismo, voluntario em um projeto de pesquisa, e nas horas vagas gosta de beber ou então assistir uma série ou filme.
> 
> ![WhatsApp Image 2020-11-13 at 16 05 26](https://user-images.githubusercontent.com/74254374/99113418-fc848a00-25cd-11eb-9b8d-9b52a4fa2542.jpeg)
> 
>   

@practice-uffs/ger-comunicacao creio que podemos adicionar no calendário e seguir os ritos

**Comment by alessandrapedrotti** [comment]
Pedro Augusto Maximowski é acadêmico do curso de Engenharia de Aquicultura da Universidade Federal da Fronteira SUL (UFFS) Campus de Laranjeiras do Sul, gosta de praticar esportes (principalmente ciclismo), é voluntário em um projeto de pesquisa e, nas horas vagas, gosta de beber e assistir séries e filmes.

Fiz a revisão textual aqui mesmo @VIF-Franca adiciona na planilha se tu ainda não adicionou, por favor?

**Comment by VIF-Franca** [comment]
Atualizado,

**Comment by VIF-Franca** [comment]
Creio que podemos finalizar a Issue...
