### ISSUE TITLE
Criação de overlay para lives do PRACTICE 

### ISSUE THREAD

**Issue by ricardopatrik** [practice-uffs/programa#287]
Boa tarde pessoal, conforme conversado na reunião da con-conteudo do dia 10/11/2020, optamos por fazer outra issue para a criação da OVERAY para que seja mais restrito os membros e para uma melhor elaboração e acompanhamento do trabalho.

Obs: minha primeira issue criada, há possibilidades de algo nao estar certo hehe.

**Comment by MaNegrao** [comment]
@luizatonial e @MilenaPaz2020 podem assumir a conversação por parte do mídia :D

**Comment by ricardopatrik** [comment]
Conforme reunião, foi solicitado novas cores de fundo. Então testei algumas cores. A noite postarei mais opções.
![fundo_diferente2](https://user-images.githubusercontent.com/71683219/98950929-5f93f500-24d8-11eb-980f-2fd080dfc06d.png)
![fundo_diferente3](https://user-images.githubusercontent.com/71683219/98950934-60c52200-24d8-11eb-84ed-f399c9f1d83b.png)
![fundo_diferente4](https://user-images.githubusercontent.com/71683219/98950941-61f64f00-24d8-11eb-8fbb-a20cc13829d0.png)



![fundo_diferente1](https://user-images.githubusercontent.com/71683219/98950916-5c006e00-24d8-11eb-8b6f-51debf893f93.png)e

![fundo_diferente5](https://user-images.githubusercontent.com/71683219/98950898-56a32380-24d8-11eb-8d5a-42d917aff59f.png)

**Comment by ricardopatrik** [comment]
Será que é possível fazer vários fundos, várias bordas e a pessoa que vai utilizar escolher qual quer usar naquele determinado momento? Aí deixaria várias opções pra a pessoa escolher.

**Comment by estelavilasboas** [comment]
Ao meu ver, as bordas com todas as cores da paleta deixaram, muita informação visual no overlay. No último modelo, a borda com degradê se encaixou melhor por ser mais suave. 
Também não tem a necessidade de ter tantos elementos no fundo, como a marca d'água e a estampa sobrepostas na imagem a seguir: 
![image](https://user-images.githubusercontent.com/30927758/98990363-20ca6300-2509-11eb-9e6b-26ff77b752f9.png)

Seria interressante termos a logo com as cores dos risquinhos do símbolo, ao invés da opção de monocromia.

Gostaria convidar as representantes do mídia (@luizatonial e @MilenaPaz2020 ) para apresentar suas observações, sendo técnicas ou não, antes do Ricardo aplicar qualquer ajuste. Convido também a @TaynaraCh para opinar, caso assim deseje.

**Comment by luizatonial** [comment]
> Ao meu ver, as bordas com todas as cores da paleta deixaram, muita informação visual no overlay. No último modelo, a borda com degradê se encaixou melhor por ser mais suave.
> Também não tem a necessidade de ter tantos elementos no fundo, como a marca d'água e a estampa sobrepostas na imagem a seguir:
> ![image](https://user-images.githubusercontent.com/30927758/98990363-20ca6300-2509-11eb-9e6b-26ff77b752f9.png)
> 
> Seria interressante termos a logo com as cores dos risquinhos do símbolo, ao invés da opção de monocromia.
> 
> Gostaria convidar as representantes do mídia (@luizatonial e @MilenaPaz2020 ) para apresentar suas observações, sendo técnicas ou não, antes do Ricardo aplicar qualquer ajuste. Convido também a @TaynaraCh para opinar, caso assim deseje.


Uma opinião pessoal, em relação às cores de fundo que foram apresentadas, acabei gostando mais da azul escura, que a princípio era a proposta inicial, achei que ficou mais harmônica que as demais. Também achei um pouco estranha, na última opção, a barra laranja que contém o logo do PRACTICE.

Em relação à questão mais técnica, acredito que seria mais interessante que a legenda, com a logo do PRACTICE e o nome do matheus, fossem retiradas do meio da tela e adaptadas de alguma maneira ao layout. Isto porque como o nome do interlocutor já está embaixo da sua própria janela, outras informações adicionais seriam usadas somente quando necessário. 

Talvez pensar em algo embaixo da tela principal, que fique mais fixo talvez e que também não fique estranho caso não haja nada escrito. Tenho a impressão que o Ricardo colocou ali no meio da tela como algo móvel, mas como não estamos trabalhando com animações ainda nas lives, seria mais interessante algo mais integrado ao layout neste primeiro momento e que fosse mais adaptável.

**Comment by MilenaPaz2020** [comment]
Olá! Em primeiro lugar, parabéns pela qualidade do trabalho!
Particularmente gostei do modelo com o fundo azul escuro, me parece que mais agradável ao olhar do que os fundos com cores mais claras. 
Eu deixaria a borda do modelo 5 e o logo do PRACTICE conforme o modelo 2. Em relação ao nome, como comentado pela Luiza, acho que fica mais interessante tirar da frente dos slides e mantidas abaixo do interlocutor.

**Comment by ricardopatrik** [comment]
Segue nova versão mais clean. Coloquei o degradê em azul nas boradas para nao chamar tanta atenção.
![OVERLAY5](https://user-images.githubusercontent.com/71683219/99002669-8fb0b780-251b-11eb-8317-892cd94a67ee.png)

**Comment by luizatonial** [comment]
Não sei o quanto posso opinar sobre o design, mas já opinando... 

Agora realmente ficou menos chamativo, só que talvez esteja monocromático demais. Acredito que isto torne o overlay um pouco menos interessante, principalmente quando utilizado em transmissões mais longas.

E se você tentasse manter esse azul mais neutro, mas ainda utilizando a cor amarela do PRACTICE para as molduras? 
Pensei na legenda inferior se integrando como parte da própria moldura, para ficar mais discreta quando não há informação.

Fiz uns rabiscos para tentar representar, não sei se ficaria melhor mais reto ou um pouco mais sinuoso na parte em que vai de encontro à moldura retangular. Enfim, só sugestões. Se ficar legal, talvez até fosse interessante seguir um formato semelhante na legenda abaixo da imagem do apresentador, onde está seu nome.

![image](https://user-images.githubusercontent.com/71669357/99011564-2042c400-252b-11eb-8311-4fd299a8e4e6.png)

**Comment by ricardopatrik** [comment]
Segue novas opções. A tela de espera a fonte é a caviar. Na tela principal uma com moldura em degrade e outra cor sólida. Também na tela de espera usei o degradê para um destaque na informação. 

![OVERLAY6](https://user-images.githubusercontent.com/71683219/99105806-f4bee880-25c1-11eb-896e-7a46db211b99.png)
![offline7](https://user-images.githubusercontent.com/71683219/99105825-f9839c80-25c1-11eb-87b8-85753a8c6c89.png)
![offline6](https://user-images.githubusercontent.com/71683219/99105829-fb4d6000-25c1-11eb-8b49-3644e7458791.png)
![offline5](https://user-images.githubusercontent.com/71683219/99105832-fc7e8d00-25c1-11eb-99f5-8d17a0ed758c.png)
![offline4](https://user-images.githubusercontent.com/71683219/99105835-fd172380-25c1-11eb-8009-9c8865d1d8ba.png)
![OVERLAY7](https://user-images.githubusercontent.com/71683219/99105838-fe485080-25c1-11eb-90fc-42fa4862f6ed.png)

**Comment by MaNegrao** [comment]
Eu gostei muito das telas de apresentação e da primeira tela desses últimos, eu só tenho duas sugestãozinhas

- Na tela com apresentação deixar o fundo da mesma cor do fundo da tela de abertura
- Tanto na tela de apresentação, quanto na de espera talvez deixar a marca d'água do PRACTICE menor, eu tenho a impressão que ela está distorcida por conta de estar estendida.

De resto tá incrível, parabéns

**Comment by MilenaPaz2020** [comment]
Sobre a tela de espera: muito bacana! Me agrada mais a com as letras em branco e o cronometro em laranja. Concordo com o Matheus em deixar a marca d'água menor (parece que ela está um pouco achatada) e deixar a tela de apresentação com o mesmo tom de azul da tela de espera.

Dúvidas de quem começou a fazer live agora: Essa overlay vai ser utilizada também quando o apresentador ou o mediador está falando sem apresentação de tela? Em caso afirmativo, deixaríamos a imagem dele em destaque no lugar dos slides? Em caso negativo, haveria uma outra overlay para esse momento sem apresentação?

Mais uma questão. Seria interessante manter os créditos conforme está (fundo branco com as ondas da identidade visual do PRACTICE) ou fazer um novo modelo para os créditos, seguindo essa identidade visual das lives?

**Comment by luizatonial** [comment]
> Sobre a tela de espera: muito bacana! Me agrada mais a com as letras em branco e o cronometro em laranja. Concordo com o Matheus em deixar a marca d'água menor (parece que ela está um pouco achatada) e deixar a tela de apresentação com o mesmo tom de azul da tela de espera.
> 
> Dúvidas de quem começou a fazer live agora: Essa overlay vai ser utilizada também quando o apresentador ou o mediador está falando sem apresentação de tela? Em caso afirmativo, deixaríamos a imagem dele em destaque no lugar dos slides? Em caso negativo, haveria uma outra overlay para esse momento sem apresentação?
> 
> Mais uma questão. Seria interessante manter os créditos conforme está (fundo branco com as ondas da identidade visual do PRACTICE) ou fazer um novo modelo para os créditos, seguindo essa identidade visual das lives?

Concordo com o @MaNegrao e a @MilenaPaz2020, devemos igualar os tons de azul dos planos de fundo.
E também gostei mais da primeira tela de espera, com as letras em branco e cronometro em degrade. E da tela de apresentação que tem o degrade de cores nas molduras.

Não havia pensado nos créditos, mas acho que seria legal fazer uma tela de créditos na mesma linguagem. 
Se você puder fazer um teste @ricardopatrik. Nossa tela de créditos no momento é assim:
![image](https://user-images.githubusercontent.com/71669357/99115447-28553f00-25d1-11eb-91a4-664eb3fae160.png)

**Comment by MaNegrao** [comment]
> Sobre a tela de espera: muito bacana! Me agrada mais a com as letras em branco e o cronometro em laranja. Concordo com o Matheus em deixar a marca d'água menor (parece que ela está um pouco achatada) e deixar a tela de apresentação com o mesmo tom de azul da tela de espera.
> 
> Dúvidas de quem começou a fazer live agora: Essa overlay vai ser utilizada também quando o apresentador ou o mediador está falando sem apresentação de tela? Em caso afirmativo, deixaríamos a imagem dele em destaque no lugar dos slides? Em caso negativo, haveria uma outra overlay para esse momento sem apresentação?
> 
> Mais uma questão. Seria interessante manter os créditos conforme está (fundo branco com as ondas da identidade visual do PRACTICE) ou fazer um novo modelo para os créditos, seguindo essa identidade visual das lives?

Em relação as lives, eu acho que sim, enquanto não tiver apresentação, o apresentador fica na janela maior, eu só não sei o que faremos com a janela menor (na minha cabeça colocaríamos a interprete na janela menos de cima e na de baixo colocaríamos algo como o chat ou algum link informativo, não sei), fica ao teu critério e o da @luizatonial. 

Quanto aos créditos, vocês podem decidir também. Eu sugiro procurar pra ver como faz aquelas que sobem, igual telejornal, ia ficar muito bonito

**Comment by ricardopatrik** [comment]
Beleza, farei as alterações. Sobre o plano de fundo com os mesmos tons, acredito que foi erro meu aqui, era pra ser igual. Irei corrigir.

**Comment by MaNegrao** [comment]
> ![offline7](https://user-images.githubusercontent.com/71683219/99105825-f9839c80-25c1-11eb-87b8-85753a8c6c89.png)

@luizatonial  e @MilenaPaz2020 Acho que batemos o martelo nessa né?

**Comment by ricardopatrik** [comment]
> > Sobre a tela de espera: muito bacana! Me agrada mais a com as letras em branco e o cronometro em laranja. Concordo com o Matheus em deixar a marca d'água menor (parece que ela está um pouco achatada) e deixar a tela de apresentação com o mesmo tom de azul da tela de espera.
> > Dúvidas de quem começou a fazer live agora: Essa overlay vai ser utilizada também quando o apresentador ou o mediador está falando sem apresentação de tela? Em caso afirmativo, deixaríamos a imagem dele em destaque no lugar dos slides? Em caso negativo, haveria uma outra overlay para esse momento sem apresentação?
> > Mais uma questão. Seria interessante manter os créditos conforme está (fundo branco com as ondas da identidade visual do PRACTICE) ou fazer um novo modelo para os créditos, seguindo essa identidade visual das lives?
> 
> Concordo com o @MaNegrao e a @MilenaPaz2020, devemos igualar os tons de azul dos planos de fundo.
> E também gostei mais da primeira tela de espera, com as letras em branco e cronometro em degrade. E da tela de apresentação que tem o degrade de cores nas molduras.
> 
> Não havia pensado nos créditos, mas acho que seria legal fazer uma tela de créditos na mesma linguagem.
> Se você puder fazer um teste @ricardopatrik. Nossa tela de créditos no momento é assim:
> ![image](https://user-images.githubusercontent.com/71669357/99115447-28553f00-25d1-11eb-91a4-664eb3fae160.png)

Sim, apresentarei algumas ideias através do mesmo conceito da tela de apresentação e de espera.

**Comment by MilenaPaz2020** [comment]
> > ![offline7](https://user-images.githubusercontent.com/71683219/99105825-f9839c80-25c1-11eb-87b8-85753a8c6c89.png)
> 
> @luizatonial e @MilenaPaz2020 Acho que batemos o martelo nessa né?

Sim! Ficou bem bacana. Agora a @luizatonial vai ter que fazer um tutorialzinho para a gente colocar esse cronômetro kkkk

**Comment by luizatonial** [comment]
> > > ![offline7](https://user-images.githubusercontent.com/71683219/99105825-f9839c80-25c1-11eb-87b8-85753a8c6c89.png)
> > 
> > 
> > @luizatonial e @MilenaPaz2020 Acho que batemos o martelo nessa né?
> 
> Sim! Ficou bem bacana. Agora a @luizatonial vai ter que fazer um tutorialzinho para a gente colocar esse cronômetro kkkk

concordo também! ficou bem legal! 
o cronômetro posso programar certinho, e colocar em um novo template para as lives, ai já fica tudo certo.

**Comment by ricardopatrik** [comment]
Nessa tela de créditos é sempre essas informações:  ARESENTAÇÃO, APOIO TÉCNICO E GERAL?

**Comment by luizatonial** [comment]
> Nessa tela de créditos é sempre essas informações: ARESENTAÇÃO, APOIO TÉCNICO E GERAL?

acredito que sim, pelo menos na maioria das vezes.

**Comment by MaNegrao** [comment]
Tem a interpretação em LIBRAS também, a gente coloca os nomes das interpretes

**Comment by ricardopatrik** [comment]
Fiz essas duas alternativas agora só para ter uma noção em que caminho seguir, se querem mudar totalmente o layout ou seguir por esse caminho.
![creditos2](https://user-images.githubusercontent.com/71683219/99119434-fe534b00-25d7-11eb-8c3a-e57b1ec2954a.png)

![creditos](https://user-images.githubusercontent.com/71683219/99119358-da900500-25d7-11eb-998e-17f57eb7ca98.png)

**Comment by luizatonial** [comment]
> Fiz essas duas alternativas agora só para ter uma noção em que caminho seguir, se querem mudar totalmente o layout ou seguir por esse caminho.
> ![creditos2](https://user-images.githubusercontent.com/71683219/99119434-fe534b00-25d7-11eb-8c3a-e57b1ec2954a.png)
> 
> ![creditos](https://user-images.githubusercontent.com/71683219/99119358-da900500-25d7-11eb-998e-17f57eb7ca98.png)

Na minha opinião é isto mesmo, bem simples e utilizando o mesmo fundo azul. 
Acredito que seja mais para termos uma ideia, porque provavelmente vamos ter que programar toda a parte escrita dos créditos pelo OBS, em razão da variação dos nomes e também dos outros elementos, como as intérpretes.

**Comment by luizatonial** [comment]
Na minha opinião poderíamos optar por estas. 
E quando você postar a última imagem, da tela de apresentação com o fundo no mesmo tom de azul que os outros elementos, poderia postar também uma versão dela com uma janela de chat, igual havíamos feito na outro issue inicialmente.

![image](https://user-images.githubusercontent.com/71669357/99120137-242d1f80-25d9-11eb-916d-45f0b1ddd711.png)
![image](https://user-images.githubusercontent.com/71669357/99120166-2db68780-25d9-11eb-9bef-0736fdfd50f7.png)
![image](https://user-images.githubusercontent.com/71669357/99120216-3f982a80-25d9-11eb-8d67-071c828e076b.png)

**Comment by ricardopatrik** [comment]
Bom dia, segue novo modelo da tela de apresentação com chat. Apenas simuleia conversa e o layout do chat, não sei como é programado, se é padrão da ferramenta da vídeo chamada. E questão de moldura, acredito que sem o degradê fique melhor.
![OVERLAY_chat](https://user-images.githubusercontent.com/71683219/99147173-8f203a00-265d-11eb-989d-aa6bdc295831.png)
![OVERLAY_chat2](https://user-images.githubusercontent.com/71683219/99147174-91829400-265d-11eb-83b8-66a6d9fc5942.png)
![apresentacao_final](https://user-images.githubusercontent.com/71683219/99147175-934c5780-265d-11eb-9999-577a055afcda.png)

**Comment by MaNegrao** [comment]
Eu gostei muito da primeira, da menos destaque pro chat, que não é uma coisa que a gente quer que tome atenção, acho que como tu disse que é uma simulação. No template final ficaria sem a barra de digitação de mensagem, já que a gente vai captar o chat da transmissão. 

Eu tenho apenas mais uma tela pra pedir, que é uma apenas com o destaque e o chat retangular do lado, abrangendo a área das duas janelas pequenas.

Aaah, lembrei de outra coisa, quando temos chat, não precisamos do nome da pessoa na janela menor, porque ali vai estar a interprete, ficaria estranho colocar o nome dela em uma tela e não colocar na outra. Então ou a gente tira a legenda da janela menor na tela com chat ou a gente coloca a legenda na tela com duas janelas pequenas. @MilenaPaz2020 e @luizatonial qual vocês acham a melhor opção? 

E mais uma vez, parabéns cara, tá bem massa, vai dar uma qualidade pras lives incrível

**Comment by luizatonial** [comment]
> Eu gostei muito da primeira, da menos destaque pro chat, que não é uma coisa que a gente quer que tome atenção, acho que como tu disse que é uma simulação. No template final ficaria sem a barra de digitação de mensagem, já que a gente vai captar o chat da transmissão.
> 
> Eu tenho apenas mais uma tela pra pedir, que é uma apenas com o destaque e o chat retangular do lado, abrangendo a área das duas janelas pequenas.
> 
> Aaah, lembrei de outra coisa, quando temos chat, não precisamos do nome da pessoa na janela menor, porque ali vai estar a interprete, ficaria estranho colocar o nome dela em uma tela e não colocar na outra. Então ou a gente tira a legenda da janela menor na tela com chat ou a gente coloca a legenda na tela com duas janelas pequenas. @MilenaPaz2020 e @luizatonial qual vocês acham a melhor opção?
> 
> E mais uma vez, parabéns cara, tá bem massa, vai dar uma qualidade pras lives incrível

Não sei, mas na minha opinião seria legal apresentar também o nome da intérprete, acho que elas merecem essa "visibilidade" assim como os apresentadores. Teria como você repetir a legenda da tela do interlocutor abaixo desta janela também, para vermos como fica @ricardopatrik?

Só tenho uma pergunta, o azul está igual da tela de espera e dos créditos? achei ele diferente ainda.

**Comment by ricardopatrik** [comment]
Sim o azul é o mesmo, deve ser pela sombra e pela marca d'agua q estão em lugares diferentes. Mas irei conferir de novo, as vezes na hora de exportar o arquivo posso ter alterado algo.
![OVERLAY_chat3](https://user-images.githubusercontent.com/71683219/99147960-af52f780-2663-11eb-87a2-5c75c21e5032.png)

![OVERLAY8](https://user-images.githubusercontent.com/71683219/99147958-ac580700-2663-11eb-9c6b-94bc1fc313c4.png)

**Comment by MaNegrao** [comment]
Concordo @luizatonial. Temos que dar essa visibilidade

**Comment by luizatonial** [comment]
> Sim o azul é o mesmo, deve ser pela sombra e pela marca d'agua q estão em lugares diferentes. Mas irei conferir de novo, as vezes na hora de exportar o arquivo posso ter alterado algo.
> ![OVERLAY_chat3](https://user-images.githubusercontent.com/71683219/99147960-af52f780-2663-11eb-87a2-5c75c21e5032.png)
> 
> ![OVERLAY8](https://user-images.githubusercontent.com/71683219/99147958-ac580700-2663-11eb-9c6b-94bc1fc313c4.png)


@ricardopatrik Não teria como deixar a legenda da intérprete na mesma direção que a do interlocutor? Acho que ficaria mais harmônico. 

@MaNegrao acredito que a legenda na tela de destaque seria mais para quando o apresentador está na janela maior. 
Se vocês acharem melhor, podemos tirar das telas em que o apresentador está na tela lateral. 
Ou poderíamos mantê-la e utilizar para o título da apresentação, por exemplo.

**Comment by MaNegrao** [comment]
@luizatonial sim, concordo com as duas coisas. Acho que não precisamos da legenda da tela em destaque quando estamos na apresentação. Talvez criar só essa legendinha móvel, daí colocamos e tiramos durante a live se precisar. Acho que com essas duas alterações vai ficar bem perfeito

**Comment by ricardopatrik** [comment]
Boa tarde, não entendi a alteração que deve ser feita. Tirar a barra onde vai o nome na tela maior?

**Comment by MaNegrao** [comment]
Sim, tirar a barra de legenda nessa tela na janela maior, e colocar a legenda da interprete na mesma direção da outra janela menor 
![](https://user-images.githubusercontent.com/71683219/99147958-ac580700-2663-11eb-9c6b-94bc1fc313c4.png)

**Comment by ricardopatrik** [comment]
blzzz

**Comment by MaNegrao** [comment]
Só pra ficar organizado. No final serão os seguintes overlays com os ajustes:

## Tela de Espera ## ok 
![](https://user-images.githubusercontent.com/71669357/99120166-2db68780-25d9-11eb-9bef-0736fdfd50f7.png)

## Tela de Fala sem inteprete ##
![](https://user-images.githubusercontent.com/71683219/99147960-af52f780-2663-11eb-87a2-5c75c21e5032.png)

## Tela de Fala com inteprete ## (tirar barra de digitação do chat)
![](https://user-images.githubusercontent.com/71683219/99147173-8f203a00-265d-11eb-989d-aa6bdc295831.png)

## Tela de Apresentação sem inteprete ## (Tirar a legenda na janela maior [Já ta sendo feito])
![](https://user-images.githubusercontent.com/71683219/99147173-8f203a00-265d-11eb-989d-aa6bdc295831.png)

## Tela de Apresentação com inteprete ## (Tirar a legenda na janela maior e ajustar legenda da interprete [Já ta sendo feito])
![](https://user-images.githubusercontent.com/71683219/99147958-ac580700-2663-11eb-9c6b-94bc1fc313c4.png)

## Tela de Créditos sem interpretes ## ok
![](https://user-images.githubusercontent.com/71669357/99120137-242d1f80-25d9-11eb-916d-45f0b1ddd711.png)

## Tela de Créditos com interpretes ## (falta apenas uma versão que tenha as interpretes)
![](https://user-images.githubusercontent.com/71669357/99120137-242d1f80-25d9-11eb-916d-45f0b1ddd711.png)

No caso, no final tem ser 7 imagens com as transparencias e tudo mais pro pessoal utilizar no obs

**Comment by ricardopatrik** [comment]
Arrumei o azul, estava desconfigurado mesmo. PANTONE 264653.



> ## Tela de Espera ## ok
> ![](https://user-images.githubusercontent.com/71669357/99120166-2db68780-25d9-11eb-9bef-0736fdfd50f7.png)

![offline7](https://user-images.githubusercontent.com/71683219/99289601-eff57100-281b-11eb-8b5e-20c6bc7cdfee.png)

**Comment by ricardopatrik** [comment]
> ## Tela de Fala sem inteprete
> ![](https://user-images.githubusercontent.com/71683219/99147960-af52f780-2663-11eb-87a2-5c75c21e5032.png)
![Tela-de-Fala-sem-inteprete_](https://user-images.githubusercontent.com/71683219/99289794-32b74900-281c-11eb-9823-eb9d4a6b7b4e.png)

**Comment by ricardopatrik** [comment]
![Tela-de-Apresentação-sem-inteprete](https://user-images.githubusercontent.com/71683219/99289909-5e3a3380-281c-11eb-8bd3-5ec3ffd13ba0.png)
![Tela-de-Fala-com-inteprete](https://user-images.githubusercontent.com/71683219/99289919-61cdba80-281c-11eb-9a9b-594c0df13dd0.png)
![creditos](https://user-images.githubusercontent.com/71683219/99289925-64301480-281c-11eb-8203-34e63bed483f.png)
![creditos2](https://user-images.githubusercontent.com/71683219/99289929-65f9d800-281c-11eb-99e3-f8f74b54c97e.png)
![Tela-de-Apresentação-com-inteprete](https://user-images.githubusercontent.com/71683219/99289938-672b0500-281c-11eb-8f29-2ad8c07fd69d.png)

**Comment by MilenaPaz2020** [comment]
Trabalho sensacional, @ricardopatrik! Só sugiro ver se não tem uma linha se sobrepondo na moldura da janela da interprete, ficou um cantinho falho.
No mais, parabéns!

**Comment by ricardopatrik** [comment]
Obrigado Milena! Sim, tinha uma linha, não tinha visto. Obrigado. Se tiver mais algo para alterar, só me dizer.
![Tela-de-Apresentação-com-inteprete](https://user-images.githubusercontent.com/71683219/99294614-0e129f80-2823-11eb-8314-b94d6cc80767.png)

**Comment by ricardopatrik** [comment]
Obrigado Milena! Sim, tinha uma linha, não tinha visto. Obrigado. Se tiver mais algo para alterar, só me dizer.
![Tela-de-Apresentação-com-inteprete](https://user-images.githubusercontent.com/71683219/99294919-80837f80-2823-11eb-89e1-36da9ad10077.png)

**Comment by luizatonial** [comment]
Na minha opinião seriam estas as telas mesmo. E ao que me parece você fez todos os ajustes necessários, parabéns 😀

Agora pra finalizarmos e podermos ir configurando no OBS, seria interessante você salvar as versões:
- com transparências ao invés das imagens e sem os nomes
- remover o cronômetro da tela de espera
- remover o nome dos participantes das telas de créditos, deixando só os títulos
- remover a parte da simulação de falas e envio das mensagens no chat

não sei se você está utilizando o amarelo/laranja padrão, então seria interessante você passar o código dessas duas cores para usarmos no cronômetro, bem como o tom de azul das legendas gerais e as fontes.

**Comment by MaNegrao** [comment]
Yep, acho que é isso. Com essas coisas que a @luizatonial comentou podemos montar um template do OBS completo. Eu adoraria ajudar em montar o template, vou dar uma pesquisada em como compactar isso e não ter que importar tudo de uma vez.  

Apenas uma pequena alteração: onde está escrito "interprete" nos créditos, pode ser substituido por "Interpretação em LIBRAS"

**Comment by ricardopatrik** [comment]
Crio uma pasta no drive pala colocar as telas?

**Comment by luizatonial** [comment]
> Crio uma pasta no drive pala colocar as telas?

simm, uma pasta de tarefa da issue

**Comment by MaNegrao** [comment]
Respondendo meu prórpio comentario, eu não cosegui achar nada sobre a importação dos templates ¬¬. Se alguem conseguir, por favor, será de grande ajuda

**Comment by ricardopatrik** [comment]
![COD CORES](https://user-images.githubusercontent.com/71683219/99305157-263deb00-2832-11eb-8506-eacbcfd399ae.jpeg)


> Na minha opinião seriam estas as telas mesmo. E ao que me parece você fez todos os ajustes necessários, parabéns 😀
> 
> Agora para finalizarmos e podermos ir configurando no OBS, seria interessante você salvar as versões:
> 
> * com transparências ao invés das imagens e sem os nomes dos apresentadores/intérpretes
> * remover o cronômetro da tela de espera
> * remover o nome dos participantes das telas de créditos, deixando só os títulos
> * remover a parte da simulação de falas e envio das mensagens no chat
> 
> Não sei se você está utilizando o amarelo/laranja padrão, então seria interessante você passar o código dessas duas cores para usarmos no cronômetro, bem como o tom de azul das legendas gerais e as fontes.
> 
> Acho que é isso? @MaNegrao @MilenaPaz2020

**Comment by estelavilasboas** [comment]
Ótimo trabalho, ficou maravilhoso! 🎉

**Comment by ricardopatrik** [comment]
Estou salvando as imagens e subindo elas no drive.

**Comment by estelavilasboas** [comment]
Apesar de eu supor que o OBS use a codificação em hexadecimal, complemento o envio dos códigos hexadecimal do Ricardo com RGB, CMYK e Pantone. 
![image](https://user-images.githubusercontent.com/30927758/99309706-9d767d80-2838-11eb-8582-8204c0d51266.png)
Espero que contribue na configuração do OBS. 😄

**Comment by ricardopatrik** [comment]
Link da pasta do drive:
https://drive.google.com/drive/folders/1kU7IU1WSxG0uxC27CGuofEv3-6D3NGqF

As telas de espera e créditos coloquei em JPEG e PNG. As demais em PNG.

**Comment by MaNegrao** [comment]
Excelente, só mais uma coisa. As paginas de créditos e de espera tem tipo uma bordinha no canto esquerdo da imagem, acho que ficou acidentalemnte. Outra coisa, a pagina de créditos ainda tem os nomes hehe, o ideal é só os titulos e trocamos os nomes conforme as lives

**Comment by ricardopatrik** [comment]
Atualizado!

**Comment by luizatonial** [comment]
ótimo! só percebi que em uma tela o bate-papo tem a seta e a barra de envio ainda...

**Comment by ricardopatrik** [comment]
Feito

**Comment by ricardopatrik** [comment]
Se possível fazerem um teste, pra ver se os tamanhos ficaram de acordo.

**Comment by luizatonial** [comment]
> Se possível fazerem um teste, pra ver se os tamanhos ficaram de acordo.

ok, vou testar e retorno!

**Comment by luizatonial** [comment]
@ricardopatrik acredito que você tenha esquecido de colocar esta tela na pasta, tem somente a sem legenda.
![image](https://user-images.githubusercontent.com/71669357/99442278-ec371c80-28f7-11eb-8584-bd2f30af6b5b.png)

**Comment by luizatonial** [comment]
> > Se possível fazerem um teste, pra ver se os tamanhos ficaram de acordo.
> 
> ok, vou testar e retorno!

que fonte você utilizou nas telas? Utilizei a caviar que você havia comentado e a roboto, mas não ficou igual

**Comment by luizatonial** [comment]
> > > Se possível fazerem um teste, pra ver se os tamanhos ficaram de acordo.
> > 
> > 
> > ok, vou testar e retorno!
> 
> que fonte você utilizou nas telas e o tamanho? Utilizei a caviar que você havia comentado e a roboto, mas não ficou igual

Colocando no OBS percebi que tem mais alguns pontos desalinhados, a questão dos planos de fundo diferentes e umas bordas com espessuras diferentes... se você puder conferir estes detalhes e padronizar os textos em roboto,

**Comment by MaNegrao** [comment]
Outra coisinha em complemento a isso que a luiza comentou, a tela que tem apenas o destaque e o chat, tem que ter a legendinha embaixo da janela de destaque...

**Comment by MaNegrao** [comment]
> @ricardopatrik acredito que você tenha esquecido de colocar esta tela na pasta, tem somente a sem legenda.
> ![image](https://user-images.githubusercontent.com/71669357/99442278-ec371c80-28f7-11eb-8584-bd2f30af6b5b.png)

Eu tomei a liberdade e fiz essa, pra milena poder usar hoje na live

**Comment by ricardopatrik** [comment]
Desculpe pessoal, irei ajeitar amanhã pois hoje tenho aula nos 3 turnos.

**Comment by luizatonial** [comment]
vendo a transmissão de hoje da @MilenaPaz2020 percebi que precisamos de uma variação da tela, com a moldura mais quadrada para os slides.

![image](https://user-images.githubusercontent.com/71669357/99580387-32ef4a00-29be-11eb-9165-81b64d293dc5.png)

**Comment by ricardopatrik** [comment]
Segue tamanho das fontes e nome. Colocarei na pasta do drive o arquivo da fonte caviar dreams para download.
![tamanho](https://user-images.githubusercontent.com/71683219/99700592-21677a00-2a72-11eb-9204-1ce4e8cc9fec.png)

**Comment by ricardopatrik** [comment]
> > > > Se possível fazerem um teste, pra ver se os tamanhos ficaram de acordo.
> > > 
> > > 
> > > ok, vou testar e retorno!
> > 
> > 
> > que fonte você utilizou nas telas e o tamanho? Utilizei a caviar que você havia comentado e a roboto, mas não ficou igual
> 
> Colocando no OBS percebi que tem mais alguns pontos desalinhados, a questão dos planos de fundo diferentes e umas bordas com espessuras diferentes... se você puder conferir estes detalhes e padronizar os textos em roboto,

estou resolvendo isso agora

**Comment by ricardopatrik** [comment]
> vendo a transmissão de hoje da @MilenaPaz2020 percebi que precisamos de uma variação da tela, com a moldura mais quadrada para os slides 4:3.
> 
> ![image](https://user-images.githubusercontent.com/71669357/99580387-32ef4a00-29be-11eb-9165-81b64d293dc5.png)

Coloquei nno drive os arquivos alterados e tentei fazer um que se enquadre nesse exemplo aqui.

**Comment by luizatonial** [comment]
> > vendo a transmissão de hoje da @MilenaPaz2020 percebi que precisamos de uma variação da tela, com a moldura mais quadrada para os slides 4:3.
> > ![image](https://user-images.githubusercontent.com/71669357/99580387-32ef4a00-29be-11eb-9165-81b64d293dc5.png)
> 
> Coloquei nno drive os arquivos alterados e tentei fazer um que se enquadre nesse exemplo aqui.

achei um pouco estranho o espaço entre os interlocutor/chat e a tela, teria como juntar os dois?

**Comment by alessandrapedrotti** [comment]
Conforme acordado na reunião de líderes, essa issue será fechada e os pontos pendentes serão redirecionados a outras issues.

Se ainda não foi criado, criar uma pastinha na pasta "materiais" do drive do programa com os recursos disponíveis nessa tarefa.

**Comment by MaNegrao** [comment]
@luizatonial elenca os pontos que ficaram em aberto e pode criar uma issue para ajustarmos
