### ISSUE TITLE
Gravação e edição - Vídeo tutorial ângulo e iluminação para transmissões

### ISSUE THREAD

**Issue by MilenaPaz2020** [practice-uffs/programa#294]
Continuação da Issue #47.
Materiais [aqui](https://drive.google.com/drive/folders/100rNKku09RjZvpVdgfAR2_se9mTAgX9D).

Não esquecer de colocar nos créditos finais do nosso vídeo uma referência para o vídeo do The Verge.

**Comment by MilenaPaz2020** [comment]
> Bom dia @MilenaPaz2020. Vi que tu está com várias lives para serem feitas. Tu não quer passar essa issue para que eu edite? Não sei se você já gravou algo, mas se já, eu pegaria seu material e editaria o vídeo.

Oi! Sim, assumi várias lives, mas como não são todos os dias poderei fazer a edição. Agradeço a disponibilidade e conto com sugestões. :D

**Comment by MilenaPaz2020** [comment]
@practice-uffs/con-conteudo, podem indicar alguém para a revisão da legenda? Assim já posso incluir o nome da pessoa nos créditos do vídeo. Obrigada! :D

**Comment by thaliafriedrich** [comment]
> @practice-uffs/con-conteudo, podem indicar alguém para a revisão da legenda? Assim já posso incluir o nome da pessoa nos créditos do vídeo. Obrigada! :D

Eu faço!

**Comment by MilenaPaz2020** [comment]
> > @practice-uffs/con-conteudo, podem indicar alguém para a revisão da legenda? Assim já posso incluir o nome da pessoa nos créditos do vídeo. Obrigada! :D
> 
> Eu faço!

@thaliafriedrich, o vídeo já está no canal interno do PRACTICE. Aguardo as correções de legenda.
@robisonjose, aguardo suas sugestões na edição.

**Comment by robisonjose** [comment]
Bom dia @MilenaPaz2020. 

Eu gostei de como o vídeo está ficando, gostei das suas gravações. Acredito que os seguintes pontos podem ser alterados para melhorar:

1. Diminuir a música. Ela fica muito próxima da tua voz, principalmente no início e no final, quando tem a gravação de você falando;
2. Não é necessário colocar o "disponível em coverr" nos vídeos utilizados. Dá para creditar só no final, assim como tu fez com os outros materiais utilizados; 
3. Deixar um pouco mais na tela o "escolha do ambiente" e também os certos e errados que aparecem nos cantos superiores;
4. Cuidar com o tamanho das imagens e vídeos, alguns tem bordas pretas em baixo, outros do lado. Essa bordas não devem aparecer, a imagem deve cobrir todo o espaço do vídeo;
5. Em relação a qualidade das imagens e vídeos utilizados: Eu não consegui analisar pois no YouTube o vídeo está em 480p. É interessante que ele esteja em 1080p;
6. No instante 0:48 a música parece baixar e subir bruscamente, não sei se você fez alguma edição na música, mas pode ser que o efeito seja da própria música, e parece que é um erro, fica um pouco estranho. Se for possível tirar essa parte, colocar outra música talvez; 
7. Se for possível, utilize a cor de fundo da vinheta do PRACTICE (aquela azul forte) para colocar os textos das transições, tipo em "escolha do ambiente". Ela é mais "viva" que aquela que você utilizou, e também vai combinar com a paleta de cores do próprio vídeo. 

Na próxima versão, tenta fazer o upload em 1080p no YouTube ou na pasta da issue, que ai dá para analisar melhor a qualidade visual do vídeo.

**Comment by thaliafriedrich** [comment]
Legendas corrigidas! 
Também gostei bastante do vídeo, ficou bem legal, parabéns!

**Comment by Dovyski** [comment]
O material ficou maravilhoso, pessoal, parabéns! Uma dica é que vocês não precisam colocar o crédito dos vídeos que usamos na hora que eles aparecem (unsplash, coverr, etc). Pode-se mencionar isso uma única vez no final, nos créditos do video. Eu acho que isso deixa qualquer video nosso mais fluído e com menos "roubo de atenção".

Tenho que fazer o comentário que a @MilenaPaz2020 é muito boa atriz! 😄

**Comment by MilenaPaz2020** [comment]
Pessoal, obrigada pelos elogios e apontamentos! Farei as adequações necessárias!
@Dovyski, se tudo der errado eu tenho um plano B agora! Valeu pela dica kkkkkk

**Comment by MilenaPaz2020** [comment]
@robisonjose, o vídeo corrigido já está na pasta de materiais. Aguardo suas observações.

**Comment by MaNegrao** [comment]
Eu passei dar uma olhada e particularmente eu curti muito a ultima versão, tá incrivel, didatico, sucinto e completo. Parabéns Milena!

**Comment by robisonjose** [comment]
Boa tarde @MilenaPaz2020. 

Ficou muito bom. Parabéns. 

Alguns apontamentos finais:

Nos créditos, poderia (no caso do Coverr deve, pois o link correto é coverr.co) ser mudado de "cover.co" para "Coverr" e de "pexels.com" para "Pexels".

O áudio poderia ter o seu fade out bem no momento que o som da vinheta começa, ou seja, a música termina (suavemente com o fade out) exatamente quando o som da vinheta inicia.

Também acho que poderia ser feito o que disse no item [7], de mudar o fundo que é utilizado nas transições. Acredito que o código da cor (azul) da vinheta é #124255 (ainda não me responderam sobre esse problema em relação a paleta de cores, mas acredito que esse código seja o correto). 

E do item [4] eu vi que você já alterou, porém o teu vídeo continua com as barras pretas (0:38), se for possível aumentar a imagem sem que ela fique com uma qualidade muito ruim, seria perfeito. Mas se ela ficar com uma qualidade muito baixa não tem problema deixar do jeito que está. 

Depois disso acredito que já possa ser colocada a legenda. Dar uma última revisão geral e pronto. Finalizado. 

Bom trabalho, ficou show de bola.

**Comment by MilenaPaz2020** [comment]
Pessoal, HELP!
Vídeo corrigido de acordo com os apontamentos do @robisonjose na pasta, bem como o arquivo das legendas em srt. No entanto, não estou conseguindo adicionar a legenda ao vídeo pelo VLC. Alguém poderia me ajudar??

**Comment by robisonjose** [comment]
Boa noite @MilenaPaz2020.

Trabalho maravilhoso. 

Só vou pedir uma ultima correção (desculpa). Em 00:25 o vídeo ficou com uma bordinha preta em cima, como se o vídeo estivesse sido deslocado um pouco para baixo. Pelo que lembro não tinha isso na outra versão. Peço que resolva isso. 

De resto o trabalho está muito bom. 

Sobre a legenda, tu quer que tenha aquele fundo preto? Se não precisar eu posso colocar pelo format factory, pq pelo VLC eu não sei como faz.

**Comment by robisonjose** [comment]
Acabei de dar uma olhada na legenda, ela está meio desconfigurada. Vou tentar ver o que aconteceu.

**Comment by robisonjose** [comment]
Postei uma legenda nova. Só peguei a que estava lá no YouTube. Tenta ver se com essa nova versão dá certo.

**Comment by MilenaPaz2020** [comment]
@robisonjose, bom dia! Fiz a alteração necessária, contudo não consegui adicionar as legendas. Poderia fazer isso, por gentileza? :)

**Comment by robisonjose** [comment]
Boa tarde @MilenaPaz2020 

Não só posso, como fiz. Está na pasta de entrada com o nome de "tutorial_angulo".

Algumas observações:

Não sei qual estava sendo o problema que estava te ocorrendo ao adicionar as legendas, mas no meu caso também tive muitos problemas (por isso que não postei antes). 

O primeiro dos problemas foi em relação a legenda de fato. Fiz um vídeozinho explicando como o download da legenda deve ser feito (o vídeo está na pasta de entrada com o nome de "telecurso_2000.1").

O segundo dos problemas é que isso estava acontecendo: 

![Captura de Tela (6)](https://user-images.githubusercontent.com/71669689/101530950-5bd97e00-3971-11eb-90f3-57d47e22e8f5.png)

E eu não fazia ideia de como resolver isso, fiquei nisso por muito tempo até descobrir que o vídeo estava com a seguinte proporção: 1092x1080. Ou seja, tu salvou em um formato que é mais ou menos 11x10 em vez de 16x9, que é o que normalmente é utilizado, então a legenda estava com uma proporção diferente da do vídeo. 

Então, quando for salvar um vídeo, salve sempre em 16x9, isto é 1280x720 (720p - HD) ou 1980x1080 (1080p - FullHD). Resoluções maiores que isso provavelmente não serão utilizadas e menores que isso já são ultrapassadas demais.

**Comment by robisonjose** [comment]
Boa tarde @thaliafriedrich.

Peço que revise a legenda do vídeo. Ele está na pasta de entrada com o nome "tutorial_angulo". 

Qualquer alteração deve ser feita no YouTube (lá dá para observar bem como a legenda vai ficar quando for colocada no vídeo). Depois de feitas as alterações, a legenda deve ser publicada.

**Comment by thaliafriedrich** [comment]
> Boa tarde @thaliafriedrich.
> 
> Peço que revise a legenda do vídeo. Ele está na pasta de entrada com o nome "tutorial_angulo".
> 
> Qualquer alteração deve ser feita no YouTube (lá dá para observar bem como a legenda vai ficar quando for colocada no vídeo). Depois de feitas as alterações, a legenda deve ser publicada.

Boa noite. Revisei a legenda novamente e não será preciso fazer nenhuma alteração (já havia feito as correções necessária uns dias atrás).

**Comment by thaliafriedrich** [comment]
> > Boa tarde @thaliafriedrich.
> > Peço que revise a legenda do vídeo. Ele está na pasta de entrada com o nome "tutorial_angulo".
> > Qualquer alteração deve ser feita no YouTube (lá dá para observar bem como a legenda vai ficar quando for colocada no vídeo). Depois de feitas as alterações, a legenda deve ser publicada.
> 
> Boa noite. Revisei a legenda novamente e não será preciso fazer nenhuma alteração (já havia feito as correções necessária uns dias atrás).

**Comment by robisonjose** [comment]
Boa noite @thaliafriedrich

Era mais para ver como tinha ficado no vídeo, se deveria ser alterado alguma minutagem, etc.

**Comment by thaliafriedrich** [comment]
Entendi. Quanto a minutagem, observei no vídeo que está pasta que no tempo 1:12, a legenda inicia antes que a fala (quando ainda está sendo apresentado o exemplo anterior). Porém, no vídeo que está no YouTube isso já estava ajustado. 

No final do vídeo, modifiquei a minutagem para a legenda terminar assim que começa os créditos. Deixei salva e publicada, como você falou.

**Comment by robisonjose** [comment]
Ah, eu sei o que aconteceu. A versão que está no YouTube tem um tempo diferente da última versão, então ocorre esse probleminha.

A nova versão está na pasta com o nome de "tutorial_angulo_v2".

**Comment by thaliafriedrich** [comment]
Nessa nova versão está tudo ok, a fala e a legenda estão bem sincronizadas, com exceção apenas do tempo 0:35, onde tem a tela "Iluminação do ambiente", onde aparece a legenda da próxima fala. Já ajustei lá no YouTube para a legenda começar em 0:36.

**Comment by robisonjose** [comment]
Boa noite @MilenaPaz2020.

Eu estava dando uma olhada no vídeo e em 00:46 a legenda fica em cima da escrita, você poderia colocar a escrita mais para cima para que a legenda não atrapalhe? 

Outra coisa que não havia percebido é quanto a qualidade das imagens dos créditos, sugiro que troque para slides com qualidade maior. Falei um pouco sobre isso na issue #295.

**Comment by MilenaPaz2020** [comment]
Bom dia, @robisonjose!
Fiz as alterações solicitas:
1 - Retirei a frase da iluminação que ficava em cima das legendas, mudar de posição a frase não ficou esteticamente bom, dessa forma resolvi deixar sem.
2 - Baixei os slides de créditos em PDF e depois converti para PNG, creio que agora vai.
3 - Vídeo foi renderizado no formato 16x9 (1980x1080).
O vídeo está na pasta da issue.
Se houver mais alterações a serem feitas, me comunique. As farei sem problemas.

**Comment by robisonjose** [comment]
Boa tarde @MilenaPaz2020 

Por algum motivo as vinhetas do PRACTICE não estão com uma qualidade muito boa, você poderia baixar elas novamente e inseri-las novamente? E outra coisa, o vídeo que aparece em 00:47 agora está com aquela bordinha preta em cima, deve ser retirada. 

Só isso mesmo.

**Comment by MilenaPaz2020** [comment]
> Boa tarde @MilenaPaz2020
> 
> Por algum motivo as vinhetas do PRACTICE não estão com uma qualidade muito boa, você poderia baixar elas novamente e inseri-las novamente? E outra coisa, o vídeo que aparece em 00:47 agora está com aquela bordinha preta em cima, deve ser retirada.
> 
> Só isso mesmo.

Vídeo novo na pasta. Revisei as bordas e não encontrei mais.

**Comment by robisonjose** [comment]
Boa tarde @MilenaPaz2020 

O vídeo ficou ótimo, todas as alterações fizeram com que o trabalho final ficasse muito bom. 

Teve umas coisas que eu mesmo mudei nessa ultima versão:

1. Por algum motivo a vinheta continuou com uma qualidade inferior, alterei para uma qualidade melhor;
2. A imagem que aparece em 00:23 (Escolha do ambiente) estava com uma qualidade inferior ao resto das imagens (não sei por quê), então utilizei esse mesmo pedaço da sua versão anterior e inseri na versão final, também deixei ela um tempinho a mais na tela pois estava desaparecendo mto rapidamente;
3. Em 00:36 quando ocorre a transição do "título" para um vídeo seu, o vídeo começa com uma bordinha azul em cima e em baixo, retirei isso.

Por fim, coloquei a legenda com as alterações que a Thalia apontou anteriormente. Peço que você revise a [versão final e legendada](https://drive.google.com/drive/u/2/folders/1hZxKaoK-axra8k-hUg7uliLkwj4b66Hg). Se estiver tudo ok, fechamos a issue.

**Comment by MilenaPaz2020** [comment]
Versão final e legendas ok! Encerramos essa tarefa.

**Comment by MaNegrao** [comment]
@robisonjose Acho que tu pode mover esses vídeos que estão saindo para pasta Vídeos que tá dentro da pasta Materiais
