### ISSUE TITLE
Vídeo - Políticas de Licença 

### ISSUE THREAD

**Issue by luizdameda** [practice-uffs/programa#295]
Continuação da issue #237 

- [x] Gravar áudio de narração

- [x] Montar vídeo 

- [x] Adicionar legenda

O roteiro do vídeo encontra-se [nesta pasta](https://drive.google.com/drive/folders/1Vc2tpriHq_TVX1nHt7Hhx2tyFqqdvlLq)

O andamento do vídeo está [nesta pasta](https://drive.google.com/drive/u/1/folders/1OK8Qbo7lFpvnqzBPf-m4Ao_Y0BifDJ-r)

[Pasta de Saída](https://drive.google.com/drive/u/1/folders/1YuLg1cYJiqkMhjpGakWrp_yQYyjgo5cd)

**Comment by luizdameda** [comment]
A narração desse vídeo será feito pela @amandasegattob porque estou rouco e a montagem do vídeo será feita por mim.

**Comment by luizdameda** [comment]
A primeira versão do vídeo encontra-se [nesta pasta](https://drive.google.com/drive/u/1/folders/1VxroBpdNp_i5IjNyF0RecWFXL7ucvcNY)

@alessandrapedrotti @brendaellen se puderem, deem uma olhada para ver se condiz com o que foi idealizado pela equipe de comunicação. Tentei ser bem fidedigno ao roteiro, mas qualquer correção ou mudança que seja necessária, podem me avisar que eu faço!!

A legenda irei adicionar após a aprovação final do vídeo

**Comment by brendaellen** [comment]
> A primeira versão do vídeo encontra-se [nesta pasta](https://drive.google.com/drive/u/1/folders/1VxroBpdNp_i5IjNyF0RecWFXL7ucvcNY)
> 
> @alessandrapedrotti @brendaellen se puderem, deem uma olhada para ver se condiz com o que foi idealizado pela equipe de comunicação. Tentei ser bem fidedigno ao roteiro, mas qualquer correção ou mudança que seja necessária, podem me avisar que eu faço!!
> 
> A legenda irei adicionar após a aprovação final do vídeo

Eu achei que ficou um ótimo trabalho. A única observação que tenho a fazer é que, em alguns momentos, a mudança entre as partes do vídeo acontece sem transição, daí meio que vai de um tópico para outro de uma vez. Talvez seja impressão minha, mas acho que seria legal dar uma olhada nessa questão.

**Comment by luizdameda** [comment]
> > A primeira versão do vídeo encontra-se [nesta pasta](https://drive.google.com/drive/u/1/folders/1VxroBpdNp_i5IjNyF0RecWFXL7ucvcNY)
> > 
> > @alessandrapedrotti @brendaellen se puderem, deem uma olhada para ver se condiz com o que foi idealizado pela equipe de comunicação. Tentei ser bem fidedigno ao roteiro, mas qualquer correção ou mudança que seja necessária, podem me avisar que eu faço!!
> > 
> > A legenda irei adicionar após a aprovação final do vídeo
> 
> Eu achei que ficou um ótimo trabalho. A única observação que tenho a fazer é que, em alguns momentos, a mudança entre as partes do vídeo acontece sem transição, daí meio que vai de um tópico para outro de uma vez. Talvez seja impressão minha, mas acho que seria legal dar uma olhada nessa questão.

Sim!! Depois que finalizei também notei isso, vou adicionar alguma transição principalmente entre os tipos de licenças

**Comment by luizdameda** [comment]
@robisonjose se puder dar uma revisada no vídeo, as alterações sugeridas pela Brenda eu já fiz aqui, só não enviei ainda porque pretendo enviar tudo em uma única vez.

**Comment by robisonjose** [comment]
Bom dia @luizdameda 

Vou dar algumas sugestões:

1. Muitas partes o vídeo fica com a mesma imagem por muito tempo, sem nenhum movimento, tipo de 0:10 a 0:30. A figurinha da mulher segurando a plaquinha de CC fica por 20 segundos na tela, sem mais nada, talvez pensar em algo para colocar ai. Talvez algo que faça menção ao que a Amanda está falando. E isso acontece muitas vezes no vídeo, principalmente nos títulos de cada parte (tipos de licença);
2. Em 1:34 - 1:36 tem um barulho muito esquisito, se for possível editar o áudio da Amanda. Caso você não tenha muita familiaridade com edição de áudio eu posso editar. Ai eu já diminuo os ruídos e dou uma trabalhada no áudio todo;
3. Me parece que a imagem em 2:38 está com uma qualidade inferior das utilizadas anteriormente, talvez colocar outra, ou achar essa com uma qualidade melhor; 
4. A imagem que aparece em 2:41 está com efeito de borda, eu não acho muito interessante utilizar isso sendo que em nenhuma outra isso é utilizado;
5. Eu fiquei com um pouco aflição escutando a música de fundo, será que ela combina com o tema? Fica parecendo que licença é algo meio macabro ksdoaskdoasdk.

No geral eu acho que o vídeo poderia ser um pouco mais trabalhado, com mais elementos. Talvez inserir vídeos prontos, palavras chave, etc... Ai vai da criatividade para deixar o negócio bacana. Eu gostei bastante daqueles ícones que você colocou, aqueles em branco e preto. Acredito que seja bem importante.

**Comment by luizdameda** [comment]
Agora que as demandas externas deram uma reduzida, vou retomar esse vídeo. Pra facilitar, vou colocar por itens as sugestões de melhorias feitas pelo Robison.

- [ ] Alterar música de fundo para algo mais animado 

- [ ] Editar áudio de narração - de fato eu também notei alguns sons meio ASMR que me dão agonia kkkkk, mas não sei editar áudio. Se tu conseguir fazer isso, @robisonjose, agradeço (me avisa se pode ser feito isso depois do vídeo finalizado ou se tu precisa dos áudios individuais)

- [ ] Adicionar uma transição entre os tipos de licenças (vou tentar fazer algo similar ao que a Amanda fez no vídeo da semana acadêmica da CC, que combine com esse vídeo)

- [ ] Adicionar mais imagens - esse é um ponto que tive bastante dificuldade quando fui fazer essa primeira versão do vídeo, é bem difícil encontrar imagens que representem o Creative Commons, inclusive as que usei retirei da própria cartilha do programa. Vou tentar olhar alguns vídeo para ter algumas ideias, mas quanto a parte dos tipos de licenças acredito que se adicionar mais coisas ficará um pouco poluído, porque pelo roteiro a ideia é dar foco nos símbolos/ícones que representam cada tipo de licença (que são aqueles em preto e branco, que parecem placas de trânsito kkk), vou tentar adicionar alguma transição bacana entre elas e ver se é suficiente para dar um diferencial.

**Comment by luizdameda** [comment]
Achei esse vídeo bem interessante e acho que podemos usar algumas partes dele. Vê o que tu acha, @robisonjose https://creativecommons.org/about/videos/creative-commons-kiwi/ 

E por ser do próprio CC, tem licença CC-BY e portanto podemos utilizar.

**Comment by robisonjose** [comment]
Cara, eu achei muito bom, principalmente por podermos usar gratuitamente e ser da própria "autoria". 

E sobre o áudio: Eu sempre edito ele antes de começar a editar o vídeo para que ele encaixe certinho com o vídeo depois. Ou seja, eu sempre faço o vídeo em cima do áudio, pq o vídeo é mais fácil de mudar a questão do tempo, encaixe, essas coisas. 

Então acho melhor tu esperar para que eu edite o áudio. Vou tentar postar, se não hoje (30/11), amanhã de manhã (01/12).

**Comment by robisonjose** [comment]
Poderíamos pedir para a @amandasegattob gravar novamente. Tomando cuidado com esses sopros. 

Ele geralmente pode ser resolvido facilmente falando um pouco mais longe do microfone (mas não muito, deve estar a uns 15/20 centímetros do microfone), e colocando uma meia, pano ou espuma entre o microfone e a boca.

**Comment by amandasegattob** [comment]
> Poderíamos pedir para a @amandasegattob gravar novamente. Tomando cuidado com esses sopros. 
> 
> 
> 
> Ele geralmente pode ser resolvido facilmente falando um pouco mais longe do microfone (mas não muito, deve estar a uns 15/20 centímetros do microfone), e colocando uma meia, pano ou espuma entre o microfone e a boca. 
> 
> 
> 
> Vamos esperar ver se ela consegue gravar que dai damos continuidade na issue, pode ser?

Oie! Posso regravar sim. Inclusive, acho que os da @luizatonial também vai precisar. 

Com essas dicas acredito que vai melhorar bastante, mas não sei consigo gravar tudo essa semana.

**Comment by robisonjose** [comment]
Bem tranquilo @amandasegattob. Essas produções internas podem ficar um pouco paradas enquanto trabalhamos nas produções externas.

**Comment by luizdameda** [comment]
A nova versão do vídeo está [nesta pasta](https://drive.google.com/drive/u/1/folders/1VxroBpdNp_i5IjNyF0RecWFXL7ucvcNY)

Depois que salvei, vi que tem uma imagem aleatória durante as transições, irei corrigir isso já. @robisonjose se puder dar uma olhada e ver o que acha.... se estiver ok, eu só vou tirar essa imagem que aparece, colocar a legenda e acho que finaliza o vídeo :)

**Comment by robisonjose** [comment]
Boa tarde @luizdameda.

Algumas coisas que podem ser alteradas:

1. A diminuição de áudio em 00:08 é muuuito brusca, deve mudar isso, colocar uma transição mais sutil;
2. Em 00:47 aparece um frame que não precisaria estar ali, antes do cara desenhando a pessoa. A mesma coisa acontece em 00:59 e 1:06;
3. A transição que aparece em 1:20 é meio desnecessária, poderia seguir só colocando o nome das atribuições normalmente. Mesma coisa em 1:40, 2:08 e 2:31 (nesse poderia ser feito uma transição do tipo "empurrar" ou algo nessa pegada, já que a única coisa que muda é o texto);
4. Em 2:21 me parece que tem o barulho de um carro adoidado passando, se tiver outro take dessa parte, sugiro utilizar, senão, deixe como está mesmo. É quase imperceptível; 
5. Todos os símbolos das atribuições devem ter o mesmo tamanho e estarem posicionadas no mesmo lugar (colocando o vídeo em 2:13 e 2:42 dá para perceber bem a diferença);
6. A imagem que aparece em 2:54 está com a qualidade muito baixa, sugiro trocar ou encontrar ela com qualidade superior;
7. Todos os fundos (onde você coloca o nome das atribuições) estão com qualidade bem baixas, é fácil perceber isso olhando para o "PRACTICE" no canto inferior direito;
8. A parte de créditos também está com uma qualidade muito baixa; 
9. A figura que aparece em 3:04 poderia ter seu fundo branco retirado. Isso é fácil de fazer com algum programa de edição de fotos ou nos próprios editores de vídeo. No shotcut dá para adicionar o filtro de Chroma Key e retirar o branco;
10. Os materiais que começam a aparecer em 3:07 poderiam sair de tela com uma transição do tipo "empurrar". Parecido com a forma que elas entram em tela, mas sem ficar girando;
11. Daria para colocar um efeito simples nos nomes das atribuições toda vez que elas aparecem, talvez o de "empurrar", ou aquele que aparece estilo fade in, algo desse tipo.

O áudio da @amandasegattob ficou muuuito bom, parabéns. O vídeo também está ficando bem bom, são só esses vários detalhes que acredito que deixarão o vídeo ainda melhor.

**Comment by luizdameda** [comment]
> Boa tarde @luizdameda.
> 
> Algumas coisas que podem ser alteradas:
> 
> 1. A diminuição de áudio em 00:08 é muuuito brusca, deve mudar isso, colocar uma transição mais sutil;
> 2. Em 00:47 aparece um frame que não precisaria estar ali, antes do cara desenhando a pessoa. A mesma coisa acontece em 00:59 e 1:06;
> 3. A transição que aparece em 1:20 é meio desnecessária, poderia seguir só colocando o nome das atribuições normalmente. Mesma coisa em 1:40, 2:08 e 2:31 (nesse poderia ser feito uma transição do tipo "empurrar" ou algo nessa pegada, já que a única coisa que muda é o texto);
> 4. Em 2:21 me parece que tem o barulho de um carro adoidado passando, se tiver outro take dessa parte, sugiro utilizar, senão, deixe como está mesmo. É quase imperceptível;
> 5. Todos os símbolos das atribuições devem ter o mesmo tamanho e estarem posicionadas no mesmo lugar (colocando o vídeo em 2:13 e 2:42 dá para perceber bem a diferença);
> 6. A imagem que aparece em 2:54 está com a qualidade muito baixa, sugiro trocar ou encontrar ela com qualidade superior;
> 7. Todos os fundos (onde você coloca o nome das atribuições) estão com qualidade bem baixas, é fácil perceber isso olhando para o "PRACTICE" no canto inferior direito;
> 8. A parte de créditos também está com uma qualidade muito baixa;
> 9. A figura que aparece em 3:04 poderia ter seu fundo branco retirado. Isso é fácil de fazer com algum programa de edição de fotos ou nos próprios editores de vídeo. No shotcut dá para adicionar o filtro de Chroma Key e retirar o branco;
> 10. Os materiais que começam a aparecer em 3:07 poderiam sair de tela com uma transição do tipo "empurrar". Parecido com a forma que elas entram em tela, mas sem ficar girando;
> 11. Daria para colocar um efeito simples nos nomes das atribuições toda vez que elas aparecem, talvez o de "empurrar", ou aquele que aparece estilo fade in, algo desse tipo.
> 
> O áudio da @amandasegattob ficou muuuito bom, parabéns. O vídeo também está ficando bem bom, são só esses vários detalhes que acredito que deixarão o vídeo ainda melhor

Já to alterando aqui, mas tem algumas coisas que não sei como prosseguir. A imagem dos créditos eu fiz como fiz todas as outras vezes, usei o slide padrão e salvei no formal JPEG, não sei o que posso fazer para a qualidade melhorar. Quanto ao item 10, não sei porque eles estão rodando também kkkk, era pra só entrarem, mas já mexi em tudo aqui e não porque continua com esse efeito giratório.

**Comment by robisonjose** [comment]
Boa noite @luizdameda. 

Sobre a qualidade baixa dos slides, na issue #302 o solicitante fala que pode ser baixado em pdf e depois exportado para qualquer resolução. Creio que a conversão de pdf para png pode ser feita por algum site online, eu mesmo uso o "cloudconvert" para quase tudo. Ah, isso é importante também, utilizar PNG em vez de JPEG ou JPG.

E sobre as coisa rodando, não é necessário retirar a "rodadinha", só seria interessante que eles saíssem, assim como entraram, ou seja, com algum efeito de transição.

**Comment by luizdameda** [comment]
O vídeo finalizado e com as correções está [nesta pasta](https://drive.google.com/drive/u/1/folders/1VxroBpdNp_i5IjNyF0RecWFXL7ucvcNY)

Acredito que (finalmente kkk) eu tenha feito tudo o que foi solicitado e que agora o vídeo esteja de fato finalizado. Caso algo tenha passado despercebido e precise ser revisto, posso alterar. Caso contrário, acredito que é só acrescentar as legendas e finalizar a issue.

**Comment by robisonjose** [comment]
Bom dia @luizdameda. 

O vídeo está bom, tenho apenas 2 pequenas sugestões:

1. Se atente às transições das coisas que estão aparecendo na tela, por exemplo, em 2:30 tudo que está na tela sai em momentos diferentes, deveriam sair todos ao mesmo tempo. E isso acontece mais vezes durante o vídeo, se olhar com atenção é possível notar;
2. O "PRACTICE" que aparece em 3:35 está com uma qualidade muito ruim, deve ser alterado. Nesse caso, acredito que seja o mesmo problema de qualidade de imagem, portanto, deverá utilizar os créditos com uma qualidade superior. Ainda sobre qualidade de imagem: O slide de fundo (que aparece boa parte do vídeo), em azul, com a logo do PRACTICE no canto inferior direito e as ondas, tem uma qualidade baixa, deve ser alterado.

**Comment by luizdameda** [comment]
> Bom dia @luizdameda. 
> 
> 
> 
> O vídeo está bom, tenho apenas 2 pequenas sugestões:
> 
> 
> 
> 1. Se atente às transições das coisas que estão aparecendo na tela, por exemplo, em 2:30 tudo que está na tela sai em momentos diferentes, deveriam sair todos ao mesmo tempo. E isso acontece mais vezes durante o vídeo, se olhar com atenção é possível notar;
> 
> 2. O "PRACTICE" que aparece em 3:35 está com uma qualidade muito ruim, deve ser alterado. Nesse caso, acredito que seja o mesmo problema de qualidade de imagem, portanto, deverá utilizar os créditos com uma qualidade superior. Ainda sobre qualidade de imagem: O slide de fundo (que aparece boa parte do vídeo), em azul, com a logo do PRACTICE no canto inferior direito e as ondas, tem uma qualidade baixa, deve ser alterado. 
> 
> 
> 
> 

Beleza! Quanto a essa questão da qualidade da imagem, acho que to com problema kkk... eu fiz o que tu Gabi sugerido, e achei que a qualidade agora estivesse boa, não sei o que fazer para melhor a qualidade ainda mais (ou qual a resolução que é considerada boa)

**Comment by luizdameda** [comment]
> Bom dia @luizdameda. 
> 
> 
> 
> O vídeo está bom, tenho apenas 2 pequenas sugestões:
> 
> 
> 
> 1. Se atente às transições das coisas que estão aparecendo na tela, por exemplo, em 2:30 tudo que está na tela sai em momentos diferentes, deveriam sair todos ao mesmo tempo. E isso acontece mais vezes durante o vídeo, se olhar com atenção é possível notar;
> 
> 2. O "PRACTICE" que aparece em 3:35 está com uma qualidade muito ruim, deve ser alterado. Nesse caso, acredito que seja o mesmo problema de qualidade de imagem, portanto, deverá utilizar os créditos com uma qualidade superior. Ainda sobre qualidade de imagem: O slide de fundo (que aparece boa parte do vídeo), em azul, com a logo do PRACTICE no canto inferior direito e as ondas, tem uma qualidade baixa, deve ser alterado. 
> 
> 
> 
> 

Beleza! Quanto a essa questão da qualidade da imagem, acho que to com problema kkk... eu fiz o que tu tinha sugerido, e achei que a qualidade agora estivesse boa, não sei o que fazer para melhor a qualidade ainda mais (ou qual a resolução que é considerada boa)

**Comment by robisonjose** [comment]
Bah, pior que eu também não sei o que pode ser feito. Mas fizemos assim, faz as edições sugeridas e tenta melhorar a qualidade. Caso não dê certo, tu posta o projeto completo que eu vejo se consigo ajeitar.

**Comment by luizdameda** [comment]
O vídeo com as alterações solicitadas está [nesta pasta](https://drive.google.com/drive/u/1/folders/1VxroBpdNp_i5IjNyF0RecWFXL7ucvcNY)

Acredito que a qualidade das imagens tenha ficado melhor agora, fiz o máximo que conseguia. Se agora estiver ok, posso legendar já?

**Comment by robisonjose** [comment]
Boa noite @luizdameda.

Agora sim, ficou show de bola. As imagens ficaram com uma qualidade muito boa. Pode legendar já sim. 

Só vou pedir uma última coisa em relação ao vídeo: Diminuir um pouco a música de fundo de quando a Amanda começa a falar e cuidar para que essa diminuição (que acontece em 00:08) não seja muito brusca, isto é, tentar fazer uma transição suave no volume da música de fundo. 

Porém, essa modificação pode ser feita juntamente com a inserção da legenda, não precisa renderizar o vídeo novamente apenas para essa modificação tendo em vista que você ainda vai precisar inserir a legenda.

**Comment by luizdameda** [comment]
O vídeo foi finalizado e legendando. Adicionei o acesso à Pasta de Saída na descrição da issue, mas vou coloca-lo também aqui.

[Pasta de Saída](https://drive.google.com/drive/u/1/folders/1YuLg1cYJiqkMhjpGakWrp_yQYyjgo5cd)

issue #295 finalizada!

**Comment by robisonjose** [comment]
Bom dia @brendaellen 

Você poderia fazer a revisão da legenda inserida no [vídeo](https://drive.google.com/drive/u/1/folders/1YuLg1cYJiqkMhjpGakWrp_yQYyjgo5cd)?

**Comment by luizdameda** [comment]
> Bom dia @brendaellen
> 
> Você poderia fazer a revisão da legenda inserida no [vídeo](https://drive.google.com/drive/u/1/folders/1YuLg1cYJiqkMhjpGakWrp_yQYyjgo5cd)? Depois do seu ok podemos encerrar a issue.

eu já fiz a correção das legendas com base no roteiro, pensei que não fosse necessário uma segunda revisão, mas se for necessária, aguardo para fechar a issue

**Comment by robisonjose** [comment]
Boa tarde @luizdameda 

Eu acho sempre bom alguém de "fora" revisar o material produzido. Muitas vezes, por estarmos trabalhando a tanto tempo no mesmo projeto, deixamos passar coisas simples.

**Comment by brendaellen** [comment]
Boa noite. 

Após realizar a revisão da legenda tenho algumas observações, mas que podem ser modificadas apenas se for viável, pois não interferem muito em relação conteúdo:

1:05 - Trocar "Esta licença" por "Essa licença", conforme a narração;
1:28 - Novamente trocar "esta licença" por "essa licença";
1:58 - Inserir uma vírgula após a palavra "crédito", pois ocorreu uma pausa entre uma informação e outra;
2:44 - Trocar "crédito a você" por "créditos a você", conforme a narração;
3:25 - Trocar "e para obter mais informações" por "para mais informações", conforme a narração;
3:33 - Remover o "https://" e deixar apenas "br.creativecommons.org".

Aproveito para dizer que o vídeo ficou ótimo :)

**Comment by robisonjose** [comment]
@brendaellen faz a revisão da nova versão por favor.

**Comment by brendaellen** [comment]
@robisonjose finalizei a revisão e está tudo ok, não tenho nenhuma observação.

**Comment by luizdameda** [comment]
Acredito que a issue já pode ser fechada agora 😊

**Comment by robisonjose** [comment]
Trabalho finalizado! Parabéns @luizdameda, mandou bem.
