### ISSUE TITLE
Vídeo - Dicas para a produção de videoaula

### ISSUE THREAD

**Issue by luizdameda** [practice-uffs/programa#296]
Continuação da issue #146

- [x] Gravar áudio de narração

- [x] Montar vídeo

- [x] Adicionar legenda

O roteiro encontra-se [nesta pasta](https://drive.google.com/drive/u/0/folders/1HQd6eBfyYUJMFM6dVOZjQkgGqFXbh1nB)

O andamento do vídeo está [nesta pasta](https://drive.google.com/drive/u/1/folders/1cY2Wb47x5vzJt1dC1eVPJ0uyVW6bRLYe)

[Versão final do vídeo](https://drive.google.com/drive/u/1/folders/1JCJ4OhoZrqzc8eMun4AMuAHC_TFNislB)

**Comment by robisonjose** [comment]
Viu Luiz, eu dei uma olhada na ultima versão do vídeo. Acho que seria interessante diminuir um pouco o volume nas transições. Elas estão relativamente altas em comparação com a tua narração.

**Comment by luizdameda** [comment]
> Viu Luiz, eu dei uma olhada na ultima versão do vídeo. Acho que seria interessante diminuir um pouco o volume nas transições. Elas estão relativamente altas em comparação com a tua narração.

Beleza! Vou arrumar agora e logo posto e te marco pra ver se melhorou

**Comment by luizdameda** [comment]
vídeo alterado [nesta pasta](https://drive.google.com/drive/u/1/folders/1-4pxm6iZ4l_3f_ZgH6nP59QRy9QFGf1T)

@robisonjose vê o que tu acha, a meu ver melhorou, acho que se baixar mais que isso, vai ficar ruim. Se estiver ok, já vou colocar a legenda e finalizar.

**Comment by robisonjose** [comment]
Melhorou, mas se tu acha que ficou um pouco baixo, daria para aumentar um pouquinho. Mas ao meu ver está melhor que a primeira versão sim.

**Comment by luizdameda** [comment]
O vídeo finalizado e com legenda encontra-se [nesta pasta](https://drive.google.com/drive/u/1/folders/1JCJ4OhoZrqzc8eMun4AMuAHC_TFNislB)

@MaNegrao @alessandrapedrotti não sei quem eu marco para a última revisão, acredito que seja vocês kkk. Caso seja necessário alguma alteração, podem falar. Se não houver novas alterações a issue pode ser encerrada. :D

**Comment by alessandrapedrotti** [comment]
Gostei bastante do vídeo! 
Minha única sugestão é adicionar um campo nos créditos para a narração também.

**Comment by MaNegrao** [comment]
Eu também gostei bastante, achei a montagem excelente, acho que a gente pode ter uma opinião do @practice-uffs/ger já que é o primeiro vídeo interno feito com animação etc.

**Comment by VIF-Franca** [comment]
> Eu também gostei bastante, achei a montagem excelente, acho que a gente pode ter uma opinião do @practice-uffs/ger já que é o primeiro vídeo interno feito com animação etc.

podem me conceder o acesso ao arquivo por gentileza, já pedi acesso.

**Comment by isabelirk** [comment]
Boa tarde,

Eu dei uma olhada no resultado final do vídeo, e quero dar os parabéns a todos os envolvidos, ficou muito bom. Mas como ajudei na finalização do roteiro, queria dar alguma dicas que talvez podem ser ajustados para os próximos vídeo:

-> escolher entre só animação ou só gif de pessoas reais ou apenas fotos,
-> a narração poderia ser feita em um tom mais descontraído, mais leve, sem medo de falar, igual aos youtubers,
-> também é preciso ficar atento que na narração teve alguns erros de dicção e engolir palavras,
-> vendo o resultado final (isto serve para a equipe de @practice-uffs/con-conteudo), poderíamos ter encorpado mais o texto; porque deu a perceber que alguns itens ficaram um pouco vagos na sua explicação durante o vídeo.

Estou muito feliz com o trabalho que estamos realizando.
Atenciosamente.

**Comment by luizdameda** [comment]
> Boa tarde,
> 
> Eu dei uma olhada no resultado final do vídeo, e quero dar os parabéns a todos os envolvidos, ficou muito bom. Mas como ajudei na finalização do roteiro, queria dar alguma dicas que talvez podem ser ajustados para os próximos vídeo:
> 
> -> escolher entre só animação ou só gif de pessoas reais ou apenas fotos,
> -> a narração poderia ser feita em um tom mais descontraído, mais leve, sem medo de falar, igual aos youtubers,
> -> também é preciso ficar atento que na narração teve alguns erros de dicção e engolir palavras,
> -> vendo o resultado final (isto serve para a equipe de @practice-uffs/con-conteudo), poderíamos ter encorpado mais o texto; porque deu a perceber que alguns itens ficaram um pouco vagos na sua explicação durante o vídeo.
> 
> Estou muito feliz com o trabalho que estamos realizando.
> Atenciosamente.

Certo! Essa questão de diferente forma de imagens também me incomodou um pouco, mas tive bastante dificuldade para encontrar todas que sigam um mesmo tipo. Quanto a narração, eu tenho uma certa dificuldade na dicção mesmo, se alguém for bom nisso e quiser gravar, eu altero ele no vídeo para ficar melhor...

**Comment by luizdameda** [comment]
A @amandasegattob irá fazer a nova narração e já começarei a edição solicitada, tentando manter apenas animações

**Comment by MaNegrao** [comment]
@luizdameda e @amandasegattob Como está o andamento do vídeo? percebi que a issue não teve movimentação desde novembro

**Comment by luizdameda** [comment]
> @luizdameda e @amandasegattob Como está o andamento do vídeo? percebi que a issue não teve movimentação desde novembro

Eu tava focado em finalizar a issue das políticas de licença, acredito que agora ela finalmente esteja ok e daí posso focar nesse :)

**Comment by luizdameda** [comment]
> @luizdameda e @amandasegattob Como está o andamento do vídeo? percebi que a issue não teve movimentação desde novembro

Eu tava focado em finalizar a issue das políticas de licença, acredito que agora ela finalmente esteja ok e daí posso focar nesse 😀

**Comment by MaNegrao** [comment]
Perfeitoo! :D

**Comment by luizdameda** [comment]
Eu basicamente remontei o vídeo todo, tentei usar todos os materiais de um mesmo estilo, todos com base em ilustrações e com alguma animação neutra. Salvei todas as imagens na melhor resolução que o site permitia, mas não sei se ficou boa o suficiente.
Já notei um leve atraso na saída da última imagem, irei corrigir em seguida, juntamente com outras alterações que julgarem necessárias. Caso não seja necessário novas alterações, já irei legendar o vídeo.


[Pasta Drive](https://drive.google.com/drive/u/1/folders/1-4pxm6iZ4l_3f_ZgH6nP59QRy9QFGf1T)

**Comment by robisonjose** [comment]
Bom dia @luizdameda 

O vídeo está bom, o único problema (além do atraso na saída da última imagem) são as imagens com qualidade baixa. Será que diminuindo o tamanho das imagens isso não seria resolvido? Ou baixando em outro formato (olhar issue #342)?

Outra coisa que poderia ser mudado são os pontos de exclamação na frase do final do vídeo. Não parece que encaixou direito da forma que está, acho que seria melhor colocar um único ponto de exclamação na mesma fonte que a escrita e logo depois da frase, normalmente.

**Comment by luizdameda** [comment]
> Bom dia @luizdameda
> 
> O vídeo está bom, o único problema (além do atraso na saída da última imagem) são as imagens com qualidade baixa. Será que diminuindo o tamanho das imagens isso não seria resolvido? Ou baixando em outro formato (olhar issue #342)?
> 
> Outra coisa que poderia ser mudado são os pontos de exclamação na frase do final do vídeo. Não parece que encaixou direito da forma que está, acho que seria melhor colocar um único ponto de exclamação na mesma fonte que a escrita e logo depois da frase, normalmente.

As imagens, no formato animação, o Storyset permite baixar somente no formato GIF ou mp4 (800x800, no máximo). O que eu posso fazer é invés de usar a animação, usar somente a imagem, que dai consigo ela em SVG.... mas acho que ficaria tão "morto" o vídeo :/

**Comment by robisonjose** [comment]
Tenta diminuir elas e tirar o fundo com a máscara de fundo verde do ShotCut. Ou fazer o que foi feito no vídeo "[Adicionar efeitos sobre o vídeo](https://drive.google.com/drive/folders/1r_Gea2VxB3J-4VfIXr9jqXa2NgStNvCs)". Ai não precisaríamos tirar as animações.

**Comment by luizdameda** [comment]
o vídeo com as correções está [nesta pasta](https://drive.google.com/drive/u/1/folders/1-4pxm6iZ4l_3f_ZgH6nP59QRy9QFGf1T)

Tentei diminuir as animações, fiz algumas alterações e mudei outras para imagens, eu acredito que tenha melhorado a qualidade. Tentei usar o chroma key pra tirar o fundo, como tu falou, mas não notei diferença na qualidade. Tenta ver e me diz o que tu acha... tem algumas que eu posso diminuir ainda mais, se for necessário, ou tentar procurar outras opções de materiais.

**Comment by robisonjose** [comment]
Bom dia @luizdameda 

Quando eu disse "diminuir" era em relação ao tamanho das animações, e não à quantidade. Desculpa se não me fiz claro. A questão do chroma key era exatamente para isso, tirar o fundo das animações para poder diminuir elas sem que elas ficassem com bordas de cores diferentes. Se for possível diminuir o tamanho delas sem essa máscara, melhor ainda. E sim, as que tu conseguir diminuir mais seria melhor. Talvez achar um meio termo entre tamanho e qualidade.

O esquisito é que tem momentos que a imagem tem uma qualidade boa, por exemplo em 00:49 e 1:35. E ai em outros a qualidade da imagem é muito inferior.  

E agora tem duas correções em relação a saída de imagem da tela. Tem dois momentos que a saída demora para acontecer e uma imagem fica sobre a outra. Vou colocar os prints desses dois momentos.

![Captura de Tela (23)](https://user-images.githubusercontent.com/71669689/105707323-849dde80-5ef1-11eb-8162-8822a89b286a.png)

![Captura de Tela (24)](https://user-images.githubusercontent.com/71669689/105707327-85cf0b80-5ef1-11eb-8b95-b8492efe7ce1.png)

É isso que tem para ser atualizado.

Bom trabalho!

**Comment by luizdameda** [comment]
> Bom dia @luizdameda
> 
> Quando eu disse "diminuir" era em relação ao tamanho das animações, e não à quantidade. Desculpa se não me fiz claro. A questão do chroma key era exatamente para isso, tirar o fundo das animações para poder diminuir elas sem que elas ficassem com bordas de cores diferentes. Se for possível diminuir o tamanho delas sem essa máscara, melhor ainda. E sim, as que tu conseguir diminuir mais seria melhor. Talvez achar um meio termo entre tamanho e qualidade.
> 
> O esquisito é que tem momentos que a imagem tem uma qualidade boa, por exemplo em 00:49 e 1:35. E ai em outros a qualidade da imagem é muito inferior.
> 
> E agora tem duas correções em relação a saída de imagem da tela. Tem dois momentos que a saída demora para acontecer e uma imagem fica sobre a outra. Vou colocar os prints desses dois momentos.
> 
> ![Captura de Tela (23)](https://user-images.githubusercontent.com/71669689/105707323-849dde80-5ef1-11eb-8162-8822a89b286a.png)
> 
> ![Captura de Tela (24)](https://user-images.githubusercontent.com/71669689/105707327-85cf0b80-5ef1-11eb-8b95-b8492efe7ce1.png)
> 
> É isso que tem para ser atualizado.
> 
> Bom trabalho!

Sim, eu tinha entendido! kkkk. A quantidade de animações eu não mexi, só mexi no tamanho mesmo e mudei algumas pra imagem normal... algumas eu diminui mais, outras diminui menos pq ficou muito "vazio". As imagens em 00:49 e em 1:35 são só imagens mesmo, por isso a qualidade ficou boa, o problema está nas animações com movimento, aparentemente, e que eu não sei mais o que fazer pra melhorar....

**Comment by robisonjose** [comment]
Ah, então diminui o máximo do tamanho que der (que faça sentido), faz essas alterações das transições, se ficar bom mude algumas animações por imagens (só se tu achar válido) e segue o baile.

**Comment by luizdameda** [comment]
A versão atualizada do vídeo está [nesta pasta](https://drive.google.com/drive/u/1/folders/1-4pxm6iZ4l_3f_ZgH6nP59QRy9QFGf1T)

Reduzi um pouco o tamanho das imagens e arrumei as transições. Não reduzi mais que isso as imagens porque o quadro, a meu ver, ficaria muito "vazio" e acredito que a qualidade atual esteja boa.

**Comment by robisonjose** [comment]
Bom dia @luizdameda 

Só faltou fazer aquela alteraçãozinha em 2:57, que uma imagem fica sobreposta a outra. Faça isso quando for postar a versão legendada, não precisa postar uma nova versão só com essa alteração. 

Ai depois quando a legenda for inserida, marque alguém da con-con pra revisar a legenda do vídeo.

**Comment by luizdameda** [comment]
A versão final do vídeo encontra-se [nesta pasta](https://drive.google.com/drive/u/1/folders/1JCJ4OhoZrqzc8eMun4AMuAHC_TFNislB)

Fiz a legenda conforme o roteiro, fazendo as alterações necessárias, mas mesmo assim peço que alguém do @practice-uffs/con-conteudo dê uma olhada no vídeo e veja se a legenda está correta.

**Comment by thaliafriedrich** [comment]
Revisão da legenda:
0:12 - corrigir para "devido à", com crase;
2:33 - alterar a vírgula para "dois pontos" ("Lembre-se: entre som...").
O restante está tudo correto.

**Comment by luizdameda** [comment]
O vídeo finalizado e com as correções apontadas encontra-se [nesta pasta](https://drive.google.com/drive/u/1/folders/1JCJ4OhoZrqzc8eMun4AMuAHC_TFNislB)

**Comment by morgana-mo** [comment]
[Link do vídeo no youtube](https://youtu.be/X2Ne7-D4MF0)

**Comment by robisonjose** [comment]
Bom dia @luizdameda 

Lembre de atualizar a planilha de vídeos internos.

**Comment by luizdameda** [comment]
> Bom dia @luizdameda 
> 
> 
> 
> Lembre de atualizar a planilha de vídeos internos. 

Onde eu encontro a planilha? Não localizei ela.

**Comment by robisonjose** [comment]
https://drive.google.com/drive/folders/1VcmKBMSxMSzJ3ZtnezOktPdMNhj_qm75

**Comment by luizdameda** [comment]
> https://drive.google.com/drive/folders/1VcmKBMSxMSzJ3ZtnezOktPdMNhj_qm75

Olhei agora e meus vídeos já estão na planilha, adicionei o externo que entrou hoje. Não havia colocado na planilha porque não sabia que éramos nós que controlávamos isso também, e pelo o que conversei com a @amandasegattob ela tinha entendido o mesmo, então talvez não tenha ficado claro... mas vou controlar isso a partir de agora.

**Comment by robisonjose** [comment]
Sim, eu adicionei ele na planilha, mas tem que adicionar o resto das informações.
