### ISSUE TITLE
Vídeo - Dicas para produzir um bom texto

### ISSUE THREAD

**Issue by robisonjose** [practice-uffs/programa#297]
Essa issue é uma continuação da #214 em que será produzido um vídeo com base na cartilha de dicas para produzir um bom texto.

As etapas são:

- [x] Gravação do [roteiro;](https://docs.google.com/document/d/13K_wFyWs4aoqmRoQzMUGZs33thZe0ANKNnTUXCtyIWc/edit)

- [x] Edição do áudio;

- [x] Edição do vídeo;

- [x] Legenda;

- [x] Roteiro da áudio-descrição;

- [x] Gravação da áudio-descrição;

- [x] Edição da áudio-descrição;

[Pasta drive](https://drive.google.com/drive/u/1/folders/1TeEkbdEwhQXxRVP-BZgpYT2rh6CgXmuh)

**Comment by robisonjose** [comment]
A primeira versão do vídeo está [aqui](https://drive.google.com/drive/u/1/folders/1TeEkbdEwhQXxRVP-BZgpYT2rh6CgXmuh). Peço que seja revisado para que eu possa prosseguir com os próximos passos. Não sei quem eu tenho que marcar para a revisão, então vou marcar as que estão creditadas no vídeo e o Matheus.

@manegrao @isabelirk @alessandrapedrotti

**Comment by MaNegrao** [comment]
Eu achei excelente, meus parabéns, o vídeo tá incrivel. Não tenho nada à acrescentar enquanto vídeo etc.

**Comment by isabelirk** [comment]
Boa tarde,

Eu achei sensacional o resultado, ficou ótimo a narração e as adaptações da animações feitas em relação ao que foi sugerido no roteiro. Eu apenas senti que a trilha sonora colocada na abertura não ficou legal com o corte brusco para outro trecho da trilha sonora logo em seguida, ficou algo um pouco desconexo. Não sei se precisaria de uma "," na frase final, visto que narração é feita com uma pausa. Mas de resto, vejo que o texto do roteiro se encaixou muito bem com o vídeo. Parabéns.
Atenciosamente.

**Comment by robisonjose** [comment]
Boa noite @isabelirk. 

A trilha sonora é a mesma durante todo o vídeo. Talvez minha diminuição do volume tenha sido muito brusca e ai deu esse impressão, vou tentar arrumar. E sobre o "," na frase final, eu acredito que não há necessidade de colocar a vírgula, além de ficar mais "clean" sem, a frase em si não está errada, foi só uma questão de pronuncia mesmo. Porém, deixo em aberto sobre essa questão de colocar a vírgula caso alguém ache que é necessário.

**Comment by robisonjose** [comment]
Como acredito que não haverá mudanças muito grandes, preciso de alguém que escreva e uma guria que grave a áudio-descrição, assim como foi solicitado no roteiro. 

@practice-uffs/con-conteudo @practice-uffs/con-midia

**Comment by alessandrapedrotti** [comment]
Gostei muito do vídeo @robisonjose! Ficou muito legal e tua narração ficou muito boa. 
Uma questão geral: temos que acertar a pronuncia da palavra "practice" pra que fique igual em todos os vídeos.

**Comment by robisonjose** [comment]
De fato @alessandrapedrotti. Eu acho que já ouvi todas as formas possíveis de pronunciar "practice".

**Comment by robisonjose** [comment]
A segunda versão do vídeo está [aqui](https://drive.google.com/drive/u/1/folders/1QpaHm1EG5F3XfRPH_AoRoqhiI0JVFP03). Fiz duas alterações em relação às ilustrações que estavam me incomodando e tentei melhorar a "transição" da trilha sonora. 

Também estou postando a versão legendada, que precisa de revisão.  

Reitero que ainda é necessário fazer a áudio-descrição.

**Comment by alessandrapedrotti** [comment]
> A segunda versão do vídeo está [aqui](https://drive.google.com/drive/u/1/folders/1QpaHm1EG5F3XfRPH_AoRoqhiI0JVFP03). Fiz duas alterações em relação às ilustrações que estavam me incomodando e tentei melhorar a "transição" da trilha sonora.
> 
> Também estou postando a versão legendada, que precisa de revisão.
> 
> Reitero que ainda é necessário fazer a áudio-descrição.

@thaliafriedrich por favor, trate da revisão da legenda.

A @amandasegattob tem uma voz boa, acho que ela pode ajudar com a audio-descrição.

**Comment by thaliafriedrich** [comment]
Revisei a legenda. Só vou pedir uma alteração: retirar a vírgula no tempo 3:21 (vale lembrar, que a escrita é uma habilidade...), pois acho que essa vírgula está sobrando alí. 
No mais, está tudo certo, e o vídeo ficou excelente!!

**Comment by robisonjose** [comment]
@thaliafriedrich Alteração feita. 

Creio que agora só falte a criação de um roteiro para a áudio-descrição e depois sua gravação e edição.

**Comment by alessandrapedrotti** [comment]
> @thaliafriedrich Alteração feita.
> 
> Creio que agora só falte a criação de um roteiro para a áudio-descrição e depois sua gravação e edição.

@thaliafriedrich, já que você já está envolvida nessa atividade com a revisão, tu poderias fazer o roteiro da áudio-descrição?

**Comment by thaliafriedrich** [comment]
Fiz uma primeira tentativa de roteiro para a áudio-descrição. 
Não sei se era bem isso, mas tentei descrever as imagens mais importantes, principalmente quando tinha as animações.
Peço sugestões para melhorar e revisão textual. Está na [pasta](https://drive.google.com/drive/folders/1zZH6QotYYgvkgUrrN1VlsVtWECW89ER8?usp=sharing) de entrada.

**Comment by amandasegattob** [comment]
Oie, boa noite! Posso gravar a áudio-descrição sim! @robisonjose tu quer que eu grave?

**Comment by robisonjose** [comment]
> Oie, boa noite! Posso gravar a áudio-descrição sim! @robisonjose tu quer que eu grave?

Bom dia @amandasegattob 

Se tu se sentir confortável pode gravar sim. A única imposição era de que deveria ser uma voz feminina. Uma dica que eu tenho, caso você for gravar com o celular, é deixar ele parado sempre no mesmo lugar apontado para sua boca e colocar algo entre o microfone e a sua boca, para não ter problemas com "estouros" ao falar certas palavras. Pode ser uma meia (limpa) ou algum outro tecido.

*na verdade pode ser suja também.

**Comment by robisonjose** [comment]
> Fiz uma primeira tentativa de roteiro para a áudio-descrição.
> Não sei se era bem isso, mas tentei descrever as imagens mais importantes, principalmente quando tinha as animações.
> Peço sugestões para melhorar e revisão textual. Está na [pasta](https://drive.google.com/drive/folders/1zZH6QotYYgvkgUrrN1VlsVtWECW89ER8?usp=sharing) de entrada.

Bom dia @thaliafriedrich!

Dei uma revisada no roteiro da audiodescrição e apontei algumas coisas. Eu não tenho muita noção de como uma audiodescrição deve ser feita, mas tentei ajudar. 

Acredito que a parte principal é quando você "explica" algo que apareceu na tela. Acredito que não seja necessário, pois esse entendimento deve vir do ouvinte, creio eu.

**Comment by thaliafriedrich** [comment]
Bom dia @robisonjose. Tem razão, acho que não é necessário a parte das explicações. Só vou aguardar a revisão da @alessandrapedrotti, daí faço as alterações.

**Comment by amandasegattob** [comment]
> > Oie, boa noite! Posso gravar a áudio-descrição sim! @robisonjose tu quer que eu grave?
> 
> 
> 
> Bom dia @amandasegattob 
> 
> 
> 
> Se tu se sentir confortável pode gravar sim. A única imposição era de que deveria ser uma voz feminina. Uma dica que eu tenho, caso você for gravar com o celular, é deixar ele parado sempre no mesmo lugar apontado para sua boca e colocar algo entre o microfone e a sua boca, para não ter problemas com "estouros" ao falar certas palavras. Pode ser uma meia (limpa) ou algum outro tecido.
> 
> 
> 
> *na verdade pode ser suja também.

Tá bem, seguirei essas orientações. Porém, acredito que eu consiga gravar mais perto do fim de semana.

**Comment by robisonjose** [comment]
Bom dia @amandasegattob

Bem tranquilo, essa tarefa é interna e será utilizada bem para frente. Melhor aplicar as forças nas issues externas.

**Comment by alessandrapedrotti** [comment]
roteiro da audiodescrição revisado. Fiz algumas alterações, mas nada muito significativo no conteúdo do texto. Gostei bastante do texto.

**Comment by thaliafriedrich** [comment]
Acredito que agora o roteiro da audiodescrição está pronto para a narração.

**Comment by amandasegattob** [comment]
Oie, coloquei a narração [aqui](https://drive.google.com/drive/folders/1zZH6QotYYgvkgUrrN1VlsVtWECW89ER8). @robisonjose assim que puder dar uma olhada, me diz se precisa fazer alguma alteração ou gravar de novo.

**Comment by robisonjose** [comment]
Bom dia @amandasegattob.

A narração está muito boa, parabéns. 

Só peço que refaça a narração dos créditos, pois eles estavam desatualizados. Já atualizei o roteiro com os créditos corretos.

**Comment by robisonjose** [comment]
Aos envolvidos nessa issue:

Uma nova versão do vídeo está sendo feita. Agora com os créditos atualizados. Então, os vídeos que estão na pasta desta issue não são os produtos finais.

**Comment by robisonjose** [comment]
Pessoal, estamos com um problema. 

Comecei a inserir a audiodescrição no vídeo, porém não nos atentamos na duração das falas. Por exemplo: 

Em 00:30 tem uma fala grande e em 00:36 tem outra fala. Dessa forma, as falas se sobrepõem se formos colocar na minutagem correta. E ai temos que ver o que podemos fazer. 

Talvez possa:

1. Revisar o roteiro da audiodescrição, tentando fazê-lo juntamente com o vídeo rodando, isto é, falando o que foi escrito para ver se encaixa;
2. Falar mais rápido para conter mais informação em menos tempo.

Acredito que podemos encontrar um meio termo entre os dois pontos anteriores.

Precisamos pensar em como resolver isso: @thaliafriedrich, @amandasegattob, @alessandrapedrotti.

**Comment by alessandrapedrotti** [comment]
> Pessoal, estamos com um problema.
> 
> Comecei a inserir a audiodescrição no vídeo, porém não nos atentamos na duração das falas. Por exemplo:
> 
> Em 00:30 tem uma fala grande e em 00:36 tem outra fala. Dessa forma, as falas se sobrepõem se formos colocar na minutagem correta. E ai temos que ver o que podemos fazer.
> 
> Opções que pensei:
> 
> 1. Revisar o roteiro da audiodescrição, tentando fazê-lo juntamente com o vídeo rodando, isto é, falando o que foi escrito para ver se encaixa;
> 2. Falar mais rápido para conter mais informação em menos tempo.
> 
> Acredito que podemos encontrar um meio termo entre os dois pontos anteriores.
> 
> Precisamos pensar em como resolver isso: @thaliafriedrich, @amandasegattob, @alessandrapedrotti.

@thaliafriedrich você poderia fazer a conferência do roteiro da audiodescrição? Ir lendo ela concomitante ao vídeo para conferir o que pode ser cortado do texto.

**Comment by thaliafriedrich** [comment]
Conferi a audiodescrição e tentei resumir bastante. Mesmo assim, talvez algumas falas ainda se sobrepõem. Se precisar resumir mais, poderia retirar a narração das cores, como "em cor laranja" em cada um dos números.

**Comment by robisonjose** [comment]
Bom dia @amandasegattob. 

Essa issue já está parada faz tempo, tu consegue colocar a gravação dessa audiodescrição na sua rotina de gravações?

**Comment by amandasegattob** [comment]
Bom dia @robisonjose! Eu já tinha gravado, mas acabei esquecendo de colocar aqui. A gravação está nessa [pasta](https://drive.google.com/drive/folders/1zZH6QotYYgvkgUrrN1VlsVtWECW89ER8).

Mil desculpas!!

**Comment by robisonjose** [comment]
Bom dia pessoal envolvido nessa issue. 

(@thaliafriedrich @alessandrapedrotti @amandasegattob) 

Tentei de todas as formas inserir a audiodescrição nesse vídeo, mas não vai ter como. Eu assisti vários vídeos com audiodescrição e as mesmas são inseridas nos intervalos das falas, todavia, nesse vídeo, não há intervalos na fala (a não ser na numeração), tendo em vista que o conteúdo importante aqui é a narração, sendo os elementos visuais meramente ilustrativos, sem nenhuma função importante. 

O que poderia ser feito é colocar a audiodescrição apenas nas numerações, ou seja: 

"O número “1”, em cor laranja, surge do canto inferior esquerdo."

Caso fosse colocado a audiodescrição da maneira como está no roteiro, ela sobreporia a narração na maior parte do tempo, e como eu disse, a narração é a parte central do mesmo.

Portanto, tendo em vista todas essas problemáticas, o que sugerem fazer?

**Comment by alessandrapedrotti** [comment]
> Bom dia pessoal envolvido nessa issue.
> 
> (@thaliafriedrich @alessandrapedrotti @amandasegattob)
> 
> Tentei de todas as formas inserir a audiodescrição nesse vídeo, mas não vai ter como. Eu assisti vários vídeos com audiodescrição e as mesmas são inseridas nos intervalos das falas, todavia, nesse vídeo, não há intervalos na fala (a não ser na numeração), tendo em vista que o conteúdo importante aqui é a narração, sendo os elementos visuais meramente ilustrativos, sem nenhuma função importante.
> 
> O que poderia ser feito é colocar a audiodescrição apenas nas numerações (e nos créditos), ou seja:
> 
> "O número “1”, em cor laranja, surge do canto inferior esquerdo."
> 
> Caso fosse colocado a audiodescrição da maneira como está no roteiro, ela sobreporia a narração na maior parte do tempo, e como eu disse, a narração é a parte central do mesmo.
> 
> Portanto, tendo em vista todas essas problemáticas, o que sugerem fazer?

Na minha opinião podemos manter a audiodescrição apenas na numeração.

**Comment by amandasegattob** [comment]
> Bom dia pessoal envolvido nessa issue. 
> 
> 
> 
> (@thaliafriedrich @alessandrapedrotti @amandasegattob) 
> 
> 
> 
> Tentei de todas as formas inserir a audiodescrição nesse vídeo, mas não vai ter como. Eu assisti vários vídeos com audiodescrição e as mesmas são inseridas nos intervalos das falas, todavia, nesse vídeo, não há intervalos na fala (a não ser na numeração), tendo em vista que o conteúdo importante aqui é a narração, sendo os elementos visuais meramente ilustrativos, sem nenhuma função importante. 
> 
> 
> 
> O que poderia ser feito é colocar a audiodescrição apenas nas numerações (e nos créditos), ou seja: 
> 
> 
> 
> "O número “1”, em cor laranja, surge do canto inferior esquerdo."
> 
> 
> 
> Caso fosse colocado a audiodescrição da maneira como está no roteiro, ela sobreporia a narração na maior parte do tempo, e como eu disse, a narração é a parte central do mesmo.
> 
> 
> 
> Portanto, tendo em vista todas essas problemáticas, o que sugerem fazer? 

Concordo com a Alessandra, poderia manter só na numeração, porém precisaria ver se não ficaria algo meio deslocado/perdido no vídeo.

**Comment by thaliafriedrich** [comment]
Concordo, é uma boa ideia manter só na numeração e nos créditos.

Nas próximas vezes que for solicitado audiodescrição, vamos lembrar de fazê-la antes da narração do vídeo, para ter os intervalos nas falas (daí funciona, certo?).

**Comment by robisonjose** [comment]
@thaliafriedrich 

Então, eu acho que funciona. Porém fazer o vídeo pensando na audiodescrição acho que é um caminho meio tortuoso, mas nada impede de fazermos isso.

**Comment by robisonjose** [comment]
Bom dia pessoal. 

Os vídeos finalizados estão na pasta de saída. Peço gentilmente que alguém revise. 

Na pasta tem 3 versões do vídeo. Um legendado, um com audiodescrição e outro "cru".

**Comment by alessandrapedrotti** [comment]
> Bom dia pessoal.
> 
> Os vídeos finalizados estão na pasta de saída. Peço gentilmente que alguém revise.
> 
> Na pasta tem 3 versões do vídeo. Um legendado, um com audiodescrição e outro "cru".

@thaliafriedrich podes tratar da revisão, por favor?

**Comment by thaliafriedrich** [comment]
Achei muito bom o resultado dos vídeos! Não sei avaliar especificamente as questões de edição de vídeo/áudio, mas ao meu ver está tudo correto, pois não há imagens se sobrepondo, a legenda está em sincronia com a fala, e a dicção da narração também está ótima! Nota-se que a audiodescrição se sobrepõe em alguns momentos com a narração do vídeo, mas como já aceitamos que assim é a melhor forma de inseri-la, acredito que foi o melhor que foi possível fazer.

Só algumas sugestões:

- Na minha opinião, nos vídeos em que não há audiodescrição, não precisaria ter os créditos referentes a isso (roteiro e narração);
- A legenda eu já havia revisado, mas ainda gostaria que adicionasse vírgulas no tempo 2:50: "garantindo, assim,".

**Comment by robisonjose** [comment]
Sobre os créditos da audiodescrição: Eu pensei sobre isso de colocar ou não no vídeo que não tem a audiodescrição, acabei optando por colocar por que, por mais que naquela versão não tenha a audiodescrição, o trabalho foi feito, e existe outra versão com ela. Então, a pessoa que assistir o vídeo sem audiodescrição provavelmente vai pensar que por haver os créditos lá, deve existir a versão com audiodescrição. Outra coisa é que geralmente em materiais audiovisuais não há versões diferentes, mas sim a opção de colocar legenda, audiodescrição, dublagem, etc. e por esse motivo os créditos também possuem uma única versão, então resolvi seguir dessa forma. 

Uma coisa que foi comentado é fazer a audiodescrição do título do vídeo (que aparece no vídeo). Então @amandasegattob, preciso que tu grave mais essa parte. :D

**Comment by robisonjose** [comment]
BOM DIA PESSOAL. 

Vídeos corrigidos e postados. A issue pode, FINALMENTE, ser encerrada. 

ALEGRIA!!

**Comment by morgana-mo** [comment]
Adicionado a fila para postagem!
@robisonjose lembra de conferir os crédito na #469

**Comment by robisonjose** [comment]
@morgana-mo 

Atualizado. Só estava diferente o nome do vídeo. Estava "Dicas para produzir um bom texto" (nome da issue), porém o nome no vídeo está como "Dicas para escrever um bom texto". Atualizei o nome da issue também para não causar confusão, bem como o título do doc.
