### ISSUE TITLE
Produção vídeo de abertura gabinete do reitor

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#298]
Foi nos solicitado a produção de um vídeo de abertura do gabinete do reitor (15-30s, à definir) para abertura de lives e eventos transmitidos pelo gabinete.

O solicitante deu as seguintes informações:

> Pensamos em algo ilustrando a UFFS (talvez imagens dos campi, etc) para rodar em loop antes da abertura das lives. apenas imagens com som de fundo.

Podemos usar os vídeos aéreos dos campi e imagens relacionadas, talvez alguns textos com informações da universidade e colocarmos a logo da uffs no começo e no final do vídeo. Podem dar sugestões etc.

Solicitei o acesso ao acervo da universidade desse vídeos aéreos e estou esperando resposta e também mais possíveis detalhes do vídeo. Talvez o @phdmauricio possa nos ajudar nessa.

CC: @practice-uffs/con-midia 

[Pasta Drive](https://drive.google.com/drive/u/0/folders/1MpzpQpUvncXZiihgydqdI0aixk3sPTGv)

**Comment by robisonjose** [comment]
Assim que eu tiver acesso ao acervo começo a fazer o vídeo. Só estou pensando em quais informações que podemos colocar no vídeo. Talvez os cursos de cada um dos campi?

**Comment by MaNegrao** [comment]
O prof Mauricio disse que já pode começar a trabalhar com os vídeos disponivéis no canal da uffs do youtube. Em relação aos textos eu pedi mais detalhes pra ele, pra conseguirmos dar andamento a demanda.

**Comment by robisonjose** [comment]
Baixar os vídeos que estão no YouTube? Acredito que a qualidade vai ficar muito baixa.

**Comment by luizatonial** [comment]
Como o @robisonjose não poderá fazer este vídeo, eu assumi.

Apesar do YouTube diminuir a qualidade dos vídeos, consegui baixar numa resolução que acredito que ficou adequada... 
Então resolvi fazer um vídeo teste [(aqui)](https://drive.google.com/drive/u/1/folders/1c95qqyveG0mTgLv2LNuUBxwv_hwzoj8w), o que vocês acham? Podemos trabalhar em cima do vídeo ou esperamos o vídeo original?

Além disso, acho que como o vídeo é bem curto, seria melhor utilizar textos somente para indicar os campi e as logos na abertura. 
E talvez alguma tela de créditos, pra mencionar a participação do PRACTICE (porque acho que nesse não teria nossa vinheta) e a autoria da música, para não termos problemas com direitos autorais...

**Comment by luizatonial** [comment]
Percebi que no player do drive ele não roda em 1080p......

**Comment by MaNegrao** [comment]
Eu posso enviar para o solicitante e perguntar se mais ou menos o que ele quer, fica a critério de vocês daí

**Comment by robisonjose** [comment]
@luizatonial Ele está em 1080p. É que as vezes demora um pouco para carregar essa resolução. 

Eu gostei das imagens que tu usou, eu só trocaria ali no final, onde aparecem três takes de realeza (eu acho), só que um aparece muito rápido. Acredito que daria para deixar só dois deles. Porém, o tempo pode ser algo que podemos pensar, talvez dedicar uns 8 segundos para cada campus totalizando +-48 segundos. Creio que não seria um problema e ficaria melhor, menos corrido. Mas não sei se o solicitante estipulou um tempo.

De resto, ao meu ver, é só colocar uma músiquinha de fundo (na biblioteca de áudio do YouTube várias faixas não precisam ter nenhuma atribuição, então não precisara colocar a autoria e tal. É só ver, quando for pegar uma faixa por lá, o tipo de licença que é necessária) e inserir em branco o nomes dos campi que estão sendo mostrados e fechou. 

Sobre os créditos, não sei se uma tela de créditos de fato seria interessante. Se não me engano eles querem passar isso em loop. Daria para colocar uma marca d'água em algum canto da tela com a logo do PRACTICE.

E sobre o vídeo original, acho que daria para esperar um pouco mais e talvez conversar com o Caimi para ver se ele vai conseguir os vídeos logo. Se não, acredito que possa ser feito com esses mesmo. Realmente a qualidade não ficou baixa.

**Comment by luizatonial** [comment]
> @luizatonial Ele está em 1080p. É que as vezes demora um pouco para carregar essa resolução.
> 
> Eu gostei das imagens que tu usou, eu só trocaria ali no final, onde aparecem três takes de realeza (eu acho), só que um aparece muito rápido. Acredito que daria para deixar só dois deles. Porém, o tempo pode ser algo que podemos pensar, talvez dedicar uns 8 segundos para cada campus totalizando +-48 segundos. Creio que não seria um problema e ficaria melhor, menos corrido. Mas não sei se o solicitante estipulou um tempo.
> 
> De resto, ao meu ver, é só colocar uma músiquinha de fundo (na biblioteca de áudio do YouTube várias faixas não precisam ter nenhuma atribuição, então não precisara colocar a autoria e tal. É só ver, quando for pegar uma faixa por lá, o tipo de licença que é necessária) e inserir em branco o nomes dos campi que estão sendo mostrados e fechou.
> 
> Sobre os créditos, não sei se uma tela de créditos de fato seria interessante. Se não me engano eles querem passar isso em loop. Daria para colocar uma marca d'água em algum canto da tela com a logo do PRACTICE.
> 
> E sobre o vídeo original, acho que daria para esperar um pouco mais e talvez conversar com o Caimi para ver se ele vai conseguir os vídeos logo. Se não, acredito que possa ser feito com esses mesmo. Realmente a qualidade não ficou baixa.

Vou dar uma olhada nas imagens, a princípio como o @MaNegrao tinha falado de 15'' a 20'', deixei uns 5 segundos para cada campus, e como alguns deles tinham vídeos bem curtos, ficou com mais imagens. Tenho impressão de que tem mais um vídeo desses, vou dar uma procurada se não tem alguma imagem melhor.

Sim, podemos esperar realmente os vídeos originais que ficaria melhor, só havia feito um teste mesmo pois acredito que talvez demore para sair alguma liberação neste sentido e teríamos uma opção.

**Comment by luizatonial** [comment]
Fiz uma primeira versão, seguindo algumas dicas do @robisonjose, está na [pasta](https://drive.google.com/drive/u/1/folders/1MpzpQpUvncXZiihgydqdI0aixk3sPTGv).
Talvez agora fosse interessante enviar ao solicitante @MaNegrao, para ver se seria mais ou menos isso.

**Comment by MaNegrao** [comment]
Envio sim, assim que tiver uma resposta eu envio aqui

**Comment by MaNegrao** [comment]
> Posso fazer duas solicitações:
> 1 - Deixa pelo menos mais um segundo o "UFFS" que aparece no final das imagens aéreas, está muito rápido.
> 2 - Fazer uma segunda versão, deste mesmo vídeo com mais uma tela e um texto: "A transmissão iniciará em instantes" (Algo assim, com a logo ali em verde)
> 
> Ai deixamos um sem esta frase para qualquer outra eventualidade e esse outro para colocar em loop nas aberturas das lives e transmissoes em geral.

Segue a resposta do solicitante

**Comment by luizatonial** [comment]
vou aguardar o @lcaimi conseguir os vídeos originais, para verificar se estão em melhor qualidade, e em seguida faço estas alterações também

**Comment by lcaimi** [comment]
Segue o link para a pasta com o video em alta resolução. Tem uma versão com legendas e outra sem legendas.

[https://drive.google.com/drive/folders/1H4KET-Kk_Dzxcv1KpJhSaIf5hDqySi_i](https://drive.google.com/drive/folders/1H4KET-Kk_Dzxcv1KpJhSaIf5hDqySi_i)

**Comment by luizatonial** [comment]
Alterei as imagens mas me parece que a resolução ficou bem similar à do vídeo inicial. 
Postei as duas versões revisadas na [pasta](https://drive.google.com/drive/u/1/folders/1MpzpQpUvncXZiihgydqdI0aixk3sPTGv).

**Comment by MaNegrao** [comment]
teste @robisonjose

**Comment by robisonjose** [comment]
Bom dia @luizatonial. 

Acredito que ficaria melhor se o "a" de "a transmissão iniciará..." fosse maiúscula. E eu estava pensando, será que não seria mais interessante que o "A transmissão iniciará em breve" ficasse aparecendo durante o vídeo todo? Que ai a pessoa que entrar vai saber que aquilo que ela está assistindo não é a transmissão ainda. Porém, não foi o que os solicitantes pediram. Mas talvez seja uma boa.

**Comment by luizatonial** [comment]
> Bom dia @luizatonial.
> 
> Acredito que ficaria melhor se o "a" de "a transmissão iniciará..." fosse maiúscula. E eu estava pensando, será que não seria mais interessante que o "A transmissão iniciará em breve" ficasse aparecendo durante o vídeo todo? Que ai a pessoa que entrar vai saber que aquilo que ela está assistindo não é a transmissão ainda. Porém, não foi o que os solicitantes pediram. Mas talvez seja uma boa.

vou fazer uma terceira versão aparecendo em todo o vídeo para que o solicitante possa escolher, obrigada @robisonjose.
e sobre a letra minúscula confesso que foi que foi uma certa aversão a ter somente uma letra fora do alinhamento hahaha, mas vou rever.

**Comment by robisonjose** [comment]
> > Bom dia @luizatonial.
> > Acredito que ficaria melhor se o "a" de "a transmissão iniciará..." fosse maiúscula. E eu estava pensando, será que não seria mais interessante que o "A transmissão iniciará em breve" ficasse aparecendo durante o vídeo todo? Que ai a pessoa que entrar vai saber que aquilo que ela está assistindo não é a transmissão ainda. Porém, não foi o que os solicitantes pediram. Mas talvez seja uma boa.
> 
> vou fazer uma terceira versão aparecendo em todo o vídeo para que o solicitante possa escolher, obrigada @robisonjose.
> e sobre a letra minúscula confesso que foi que foi uma certa aversão a ter somente uma letra fora do alinhamento hahaha, mas vou rever.

Da para colocar tuDO EM MAÍSCULO ENTÃO KKKK

**Comment by luizatonial** [comment]
coloquei as versões em CAIXA ALTA e com a frase de transmissão no canto do vídeo.
AGORA TEMOS VÁRIAS VERSÕES PARA O SOLICITANTE!

**Comment by MaNegrao** [comment]
Enviei todas as versões para o SOLICITANTE :D

**Comment by MaNegrao** [comment]
Tarefa finalizada! Parabéns pessoal!
