### ISSUE TITLE
Treinamento para Lives Laranjeiras do Sul

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#299]
A ideia central desta issue é: 

- [x] ensinar o @pedroamaximowski sobre como funciona o laboratório de mídias no campus Laranjeiras do Sul;

- [x] solicitar que adicionem o @pedroamaximowski e o @rafaguilman no grupo do WhatsApp do laboratório de mídias do Campus Laranjeiras do Sul;

- [x] solicitar via e-mail a autorização de acesso ao laboratório de mídias para o servidor responsável 

- [x] Enviar para os seguranças do campus as autorizações;

- [x] @pedroamaximowski pediria para você estudar/assistir vídeos no YouTube que ensine a fazer *live* no _software_ OBS Studio, também já baixe o software em seu notebook; 

- [x]  @pedroamaximowski podemos realizar nossa capacitação pessoalmente no campus Laranjeiras do Sul na semana que vem? Entre os dias 16/11 e 20/11, preferencialmente nos primeiros dias da semana para tu poder auxiliar nas demandas de live do con-midia;

- [x] irei te ensinar os por menores do funcionamento na nossa capacitação presencial.

**Comment by rafaguilman** [comment]
Se conseguir vou também

**Comment by VIF-Franca** [comment]
Podemos alinhar para quarta-feira no período noturno, 19:00?

**Comment by pedroamaximowski** [comment]
Pode ser quarta feira ás 19:00 sem problemas

**Comment by rafaguilman** [comment]
Acho que vou também

**Comment by VIF-Franca** [comment]
Firmado,

**Comment by VIF-Franca** [comment]
Realizei a capacitação com o @pedroamaximowski  e @rafaguilman, estão preparados para as lives rsrsrs
