### ISSUE TITLE
Criação de convite para LIVE PIBID e RP II - 30/11 

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#300]
Foi solicitado o auxilio do PRACTICE na live do PIBID E RP no dia 30/11.
Eles haviam solicitado junto ao auxilio em live a criação de um convite simples para o evento. Porém eu acabei deixando passar despercebido e não vi (perdão). Portanto temos que produzir esse convite.

As informações da live podem ser coletadas na issue #257, no roteiro tem tudo que é necessario. 
Também pode ser utilizado como modelo o convite produzido na issue #155, que foi utilizado na primeira live. Podemos seguir os mesmos moldes de disposição de informações etc. 

Quanto ao QR-code utilizado na live, podemos mudar e fazer o qr code direto para o [link da live](https://youtu.be/LrZJQ0InGaY) (na epoca não sabiamos como funcionava a plataforma do youtube) 

Não sei bem que fica a cargo dessa tarefa, creio que seja a equipe de @practice-uffs/con-conteudo.

[Pasta Drive](https://drive.google.com/drive/folders/1bgbhRgllswr7v_4UtfApNbWelkVf2u0U)

CC: @practice-uffs/con-midia

**Comment by ricardopatrik** [comment]
Coloquei algumas alternativas no drive. Gostaria de saber se vai mais alguma informação no convite.

Link das imagens usadas:
https://unsplash.com/photos/1-YQiOijio8
https://unsplash.com/photos/eMP4sYPJ9x0

**Comment by MaNegrao** [comment]
Creio que tá correto as informações do convite, eu particularmente gostei da primeira versão de ambos, e tá bem lindo cara, parabens. Se me permitir eu vou enviar ao solicitantes pra ver se está de acordo com o que eles querem

**Comment by MaNegrao** [comment]
Vou enviar todas as versões para os solicitantes e com a resposta deles nós tomamos uma decisão

**Comment by ricardopatrik** [comment]
só o qrcode aí é ficticio

**Comment by MaNegrao** [comment]
Você pode fazer com o qr code da live, por favor? Eu já enviei ao solicitante.

**Comment by ricardopatrik** [comment]
blz, já alterei lá

**Comment by MaNegrao** [comment]
Ok!

**Comment by MaNegrao** [comment]
Apenas uma alteração, o solicitante pediu para colocar o link da live embaixo do qr code.

**Comment by ricardopatrik** [comment]
feito

**Comment by MaNegrao** [comment]
Enviado ao solicitante, tarefa finalizada!
