### ISSUE TITLE
Montagem "Vinheta" Programa RP 1 

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#301]
Foi solicitado ao PRACTICE o auxlio na produção de 5 vinhetas para o programa Residencia pedagogica no mês de novembro. e mais 41 no ano que vem.
A solicitante nos deu as seguintes informações. Foi combinado de produzirmos um primeiro para termos uma base para os seguintes, então vamos montar um e afinar com o cliente e depois montamos os outros 4 com base no primeiro. 

> (1) logo da UFFS, do Programa Residência e da CAPES (jingle)
> (2) Apresentação da dupla de residente-estagiário (penso em foto e nome - jingle)
> (3) Apresentação da escola-campo (penso em foto da professora-preceptora e nome da escola-campo - Jingle) 
> (4) Informação na sequência - Sob orientação (foto da orientadora/UFFS com nome - jingle)
> (5) deixar um efeito de transição para os acadêmicos poderem compilarem junto aos vídeos por eles gravados, onde na sequência virá o conteúdo da videoaula, etc.)

As informações para o primeiro vídeo são:

> Ana Maria Rodrigues e Karoline Glayka de Souza Gonçalves, são as redentes que irão fazer a vídeo aula.
> Dirlaine de Oliveira é a preceptora, representante do Colégio Dom Carlos Eduardo
> Rosiane Moreira da Silva Swiderski é a orientadora do Residência Pedagógica, Núcleo Letras, Português, UFFS/Realeza.
> 
> Segue também o logo do Residência, da CAPES e da UFFS, acredito que esses logos poderiam ser a primeira imagem a aparecer, para na sequência vir a das residentes (Ana Maria e Karoline, e num plano de fundo a informação sob orientação de (com imagem da preceptora Dirlaine e a minha).

[Identidade Visual da UFFS](https://www.uffs.edu.br/institucional/reitoria/diretoria_de_comunicacao_social/identidade_visual)

É interessante finalizarmos esse piloto até o final da sprint, para que possamos dar continuidade aos proximos com calma.

Todos os arquivos relacionados estão na pasta de entrada da pasta do drive.

[Pasta Drive](https://drive.google.com/drive/folders/1MSYV3SPSoUF9puOLabmmTQWCbJgfOWFb)

CC: @practice-uffs/con-midia

**Comment by amandasegattob** [comment]
Oie, posso pegar essa tarefa! Só não sei se entendi direito. Seria um vídeo com as imagens passando nessa ordem e uma mesma musiquinha de fundo. Isso?

**Comment by MaNegrao** [comment]
Até onde eu entendi, sim. Eu tentei esmiuçar melhor a ideia, mas não consegui, então sugeri que vizessemos essa primeira versão para termos certeza.

**Comment by amandasegattob** [comment]
Oie, fiz um modelinho conforme está nas descrições, está [aqui](https://drive.google.com/drive/folders/1aMOQ5QNX4DcRG8QtQeerqSlAYjkpVMvm)

Não sei se era bem isso, mas faço as alterações que forem necessárias. Ali ela fala em um plano de fundo e fotos delas, então compreendi que era tudo na mesma imagem. Coloquei os textos com movimento, mas tudo pode ser mudado.

Aceito dicas e críticas para poder melhorar a vinheta.

**Comment by amandasegattob** [comment]
Oie, fiz um modelinho conforme está nas descrições, está [aqui](https://drive.google.com/drive/folders/1aMOQ5QNX4DcRG8QtQeerqSlAYjkpVMvm).

Não sei se era bem isso, mas faço as alterações que forem necessárias. Ali ela fala em um plano de fundo e fotos delas, então compreendi que era tudo na mesma imagem. Coloquei os textos com movimento, mas tudo pode ser mudado.

Aceito dicas e críticas para poder melhorar a vinheta.

**Comment by MaNegrao** [comment]
Eu gostei muito, tá bem legal mesmo. Vou enviar pra prof e ver se era mais ou menos a idea dela.

**Comment by robisonjose** [comment]
Boa tarde, 

Daria para melhorar a qualidade das imagens das logos. [Nesse site](http://www1.capes.gov.br/logomarca) tem as logos com uma qualidade melhor. 

Também daria para fazer com que essas coisas que marquei na imagem não aparecessem. Dá um pouquinho de agonia aparecer essas partezinhas. 

![Captura de Tela (66)_LI](https://user-images.githubusercontent.com/71669689/99584784-2d94fe00-29c4-11eb-982a-a15d52f9003a.jpg)

Acho que seria interessante que as lâmpadas apareçam inteiras ou não apareçam nada (talvez se elas aparecessem exatamente na metade não ficaria ruim também).

E ser der, daria para colocar em 1080p.

E acho que falta a transição que foi pedido. Temos que lembrar que a vinheta virá logo antes de outra parte do vídeo. Apesar de eu achar bem complicado colocar uma transição em comum para todos os vídeos que serão produzidos, talvez daria para colocar algo como uma "virada de página" que talvez encaixaria em qualquer coisa.

De resto a vinheta ficou bem bacana.

**Comment by robisonjose** [comment]
Ah, tem outra coisa também que eu notei. Na hora de aparecer os nomes das pessoas, a do lado esquerdo tem uma transição diferente da do lado direito. Seria bom deixar tudo normatizado.

**Comment by MaNegrao** [comment]
Os solicitantes os retornaram com as seguintes informações

> Penso que poderíamos melhorar, mas diante do tempo talvez não seja possível. Como se trata de videoaula para adolescentes entre 10 a 12 anos, talvez uma música ou recursos visuais voltados a esse público. Contudo, não sei se há tempo hábil para isso. 

Como eu disse na descrição da tarefa, essa vinheta seria experimental, já que os solicitantes deixaram alguns pontos em aberto.
Eu pedi mais detalhes e expliquei que não tinhamos como saber algumas questões, estou no aguardo, por ora podeos trabalhar com essa resposta.

**Comment by amandasegattob** [comment]
> Boa tarde, 
> 
> 
> 
> Daria para melhorar a qualidade das imagens das logos. [Nesse site](http://www1.capes.gov.br/logomarca) tem as logos com uma qualidade melhor (caso não dê para baixar nesse site, é só procurar no google as mesmas logos e baixar com uma qualidade melhor e em PNG).
> 
> 
> 
> Também daria para fazer com que essas coisas que marquei na imagem não aparecessem. Dá um pouquinho de agonia aparecer essas partezinhas. 
> 
> 
> 
> ![Captura de Tela (66)_LI](https://user-images.githubusercontent.com/71669689/99584784-2d94fe00-29c4-11eb-982a-a15d52f9003a.jpg)
> 
> 
> 
> Acho que seria interessante que as lâmpadas apareçam inteiras ou não apareçam nada (talvez se elas aparecessem exatamente na metade não ficaria ruim também).
> 
> 
> 
> E ser der, daria para colocar em 1080p.
> 
> 
> 
> E acho que falta a transição que foi pedido. Temos que lembrar que a vinheta virá logo antes de outra parte do vídeo. Apesar de eu achar bem complicado colocar uma transição em comum para todos os vídeos que serão produzidos, talvez daria para colocar algo como uma "virada de página" que talvez encaixaria em qualquer coisa.
> 
> 
> 
> De resto a vinheta ficou bem bacana.
> 
> 

Boa noite! Vou fazer essas alterações. 

Já é para estar em 1080p, mas vou confirmar. 

Em relação à transição, preciso aprender a fazer, porque sempre que coloquei transição tinha algo depois.

**Comment by amandasegattob** [comment]
> Ah, tem outra coisa também que eu notei. Na hora de aparecer os nomes das pessoas, a do lado esquerdo tem uma transição diferente da do lado direito. Seria bom deixar tudo normatizado. 
> 
> 
> 
> Mas caso a solicitante tenha gostado assim, só ignora tudo que eu disse e poupa trabalho.

Quanto a isso, não sei o que aconteceu. No programa está padronizado.

**Comment by amandasegattob** [comment]
> Os solicitantes os retornaram com as seguintes informações
> 
> 
> 
> > Penso que poderíamos melhorar, mas diante do tempo talvez não seja possível. Como se trata de videoaula para adolescentes entre 10 a 12 anos, talvez uma música ou recursos visuais voltados a esse público. Contudo, não sei se há tempo hábil para isso. 
> 
> 
> 
> Como eu disse na descrição da tarefa, essa vinheta seria experimental, já que os solicitantes deixaram alguns pontos em aberto.
> 
> Eu pedi mais detalhes e expliquei que não tinhamos como saber algumas questões, estou no aguardo, por ora podeos trabalhar com essa resposta.

Boa noite! Vou tentar explorar essa proposta. Acredito que até amanhã eu consigo dar um retorno.

**Comment by amandasegattob** [comment]
Bom dia! Fiz as alterações. Acredito que agora esteja mais próximo da proposta. O vídeo está [nessa pasta](https://drive.google.com/drive/folders/1aMOQ5QNX4DcRG8QtQeerqSlAYjkpVMvm).

Quanto à transição que do final, vou precisar de ajuda nisso, não consegui colocar.

**Comment by MaNegrao** [comment]
Vou enviar à solicitante

**Comment by robisonjose** [comment]
> Bom dia! Fiz as alterações. Acredito que agora esteja mais próximo da proposta. O vídeo está [nessa pasta](https://drive.google.com/drive/folders/1aMOQ5QNX4DcRG8QtQeerqSlAYjkpVMvm).
> 
> Quanto à transição que do final, vou precisar de ajuda nisso, não consegui colocar.

Eu gostei bastante dessa segunda versão. E creio que quanto a transição do final não seja preciso, visto que o vídeo fica apenas com o fundo no finalzinho. E ai é só colocar uma transição quando o vídeo for inserido na vinheta.

**Comment by amandasegattob** [comment]
Bom dia! Nada de resposta ainda, @MaNegrao ?

**Comment by MaNegrao** [comment]
> Bom dia! Nada de resposta ainda, @MaNegrao ?

Acabei de verificar o e-mail e nada, vou confirmar novamente se eu realmente enviei.

**Comment by MaNegrao** [comment]
Eu enviei um e-mail pedindo se esteva tudo certo novamente, e a solicitante aprovou, tudo certo ;D Creio que em breve eles enviem mais vinhetas e dai a ideia é produzir com base nesse
