### ISSUE TITLE
Remontagem de Vídeo - Andamento TCC de Computação - CH

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#302]
O professor Fernando, docente da diciplina de TCC 1 no curso de ciência da computação da uffs nos solicitou a remontagem de um vídeo de apresentação de andamento do trabalho de tcc. 

As instruções são as seguintes:

> O vídeo foi gravado em resolução 360p:
> Eu gostaria que um novo vídeo fosse criado, com resolução 1080p, com base no áudio do vídeo original e uma nova gravação dos slides
> Também gostaria que o vídeo do narrador fosse integrado no vídeo novo (cortar ele do vídeo antigo e colocar no vídeo novo, talvez com um tamnho máximo de 150x150 pixels).

Eu sugiro no vídeo do narrador, colocarem uma mascara circular com uma borda branca. O vídeo original e os slides estão na pasta entrada da pasta do drive em forma de atalhos.

[Pasta do drive](https://drive.google.com/drive/folders/11X5-ZMJNsOLXS4NBekJTxoe3M94S-AfQ)

CC: @practice-uffs/con-midia

**Comment by robisonjose** [comment]
Qual o prazo?

**Comment by MaNegrao** [comment]
Creio que é totalmente plausível a finalização dele até o fim da sprint, visto que já tem o modelo, ele se encaixaria de 4 à 7 dias.

**Comment by robisonjose** [comment]
Primeira versão do vídeo está [aqui](https://drive.google.com/drive/folders/1-gzN9o3jfMooscp9uUcJRdqRP8ui3pNX). Peço que envie ao solicitante. 

Em relação ao que foi feito:

1. Tentei colocar as mesmas transições que as originais;
2. Tentei melhorar a qualidade do áudio;
3. Deixei a logo do curso parado enquanto ocorria as transições, o efeito fica mais bonito (na minha opinião);
4. Coloquei uma borda no vídeo do narrador na mesma cor que o texto (achei melhor que branco); 
5. Peço que se atente à logo do curso, ela ficou um pouco apagada por conta da cor de fundo dos slides, isso não acontece no vídeo original pois a cor base do slide é diferente.

**Comment by MaNegrao** [comment]
Enviei ao solicitante

**Comment by robisonjose** [comment]
Me parece que está demorando demais para aparecer a qualidade 1080 no vídeo do drive. Pode ser que algo tenha dado errado e não tenha renderizado em full HD.

**Comment by robisonjose** [comment]
Estou trabalhando no vídeo ainda, estou tentando resolver esse problema e colocar em 1080p como solicitado.

**Comment by MaNegrao** [comment]
Ok, o solicitante nos retornou com apenas essa ressalva. Caso não seja possivel avisa que eu explico para ele

**Comment by robisonjose** [comment]
@MaNegrao se tu puder, avisa o solicitante que tem uma versão nova na pasta, acredito que consegui melhorar a qualidade.

**Comment by MaNegrao** [comment]
Vou enviar, obrigado!

**Comment by robisonjose** [comment]
> Ok, o solicitante nos retornou com apenas essa ressalva. Caso não seja possivel avisa que eu explico para ele

Bah, ai vai continuar dando ruim, 1080p faz com que algo fique ruim, ou o vídeo do narrador, ou os slides. Nessa última versão foi a mais balanceada que eu achei. Mas, vou fazer outra versão em 1080p e vou colocar lá para o solicitante dar uma olhada.

**Comment by MaNegrao** [comment]
O solicitante nos informou da possibilidade de exportar a apresentação como pdf e apartir dela a possibilidade de exportar a imagem para qualquer resolução.
O mesmo o fez e nos enviou um zip com os slides. Creio que isso pode solucionar nosso problema

**Comment by robisonjose** [comment]
Mas o último vídeo já está em 1080 e acredito que com uma qualidade muito boa.

**Comment by MaNegrao** [comment]
Vou enviar pra ele, mas fica o aprendizado de como fazer para as próximas ;D

**Comment by MaNegrao** [comment]
Tarefa finalizada
