### ISSUE TITLE
Alterações no formulário de Identidade Visual

### ISSUE THREAD

**Issue by mariagelain** [practice-uffs/programa#304]
O formulário criado na issue #149 não se aplica mais as demandas ofertadas pela con-design. Portanto será preciso fazer alterações no corpo do formulário já existente.

**Comment by estelavilasboas** [comment]
Fiz uma cópia do formulário na [pasta da issue](https://drive.google.com/drive/u/0/folders/1U2GyRpxtiaglnfjxnhku8XnGz3lNwMLG) para que não alterar diretamente no formulário que enviamos aos solicitantes.
- Temos que adaptar o formulário para contemplar também projetos e programas que possam solicitar o serviço;
- Toda alteração realizada no formulário deve ser relatada nos comentários dessa issue;
- Podem inserir e alterar perguntas que achem importantes;

**Comment by ricardopatrik** [comment]
Alteração no layout apenas ou na escrita?

**Comment by mariagelain** [comment]
na escrita (creio que na descrição da issue isto não ficou claro o suficiente, me desculpe), temos que reelaborar o texto para que atenda as demandas atuais da con-design.

**Comment by TaynaraCh** [comment]
Fiz algumas alterações no formulário, a partir do que conversamos, deem uma olhada pra ver se tá ok

**Comment by VIF-Franca** [comment]
Podem me passar o link atual do formulário para a criação de identidade visual ?  Preciso enviar para uma cliente :)

**Comment by ricardopatrik** [comment]
Olá, antes de alterar no formulário posto aqui algumas ideias para complementar o briefing de identidade visual:

- Painel semântico: espaço onde o cliente coloca imagens de referencias com o conceito da logomarca.
- Qual mensagem que o cliente quer que a logomarca passe?
- Publico alvo: se é para estudantes, terceirizados, professores, comunidade geral etc..
- Adejetivos que descreveriam a logo.
- Logo possui algum slogan?

**Comment by mariagelain** [comment]
> Podem me passar o link atual do formulário para a criação de identidade visual ? Preciso enviar para uma cliente :)

o fomulário ainda está em reconstrução, mas assim que estiver pronto eu disponibilizo o link pra ti.

**Comment by estelavilasboas** [comment]
> Podem me passar o link atual do formulário para a criação de identidade visual ? Preciso enviar para uma cliente :)
> @VIF-Franca 

O formulário antigo apenas contemplava as demandas de Identidade Visual para os cursos da universidade, pois esta era a informação que tinhamos na época. Logo que vimos que as solicitações seriam realizadas para programas e projetos, passamos adaptá-lo.
O que pode ser feito é enviar o formulário antigo, não o adaptado que ainda está em construção.

**Comment by estelavilasboas** [comment]
> Fiz algumas alterações no formulário, a partir do que conversamos, deem uma olhada pra ver se tá ok

Poderia citar quais foram as alterações? Dessa maneira fica mais rápido e fácil de identificá-las

**Comment by estelavilasboas** [comment]
Seções de vinhetas e templates foram deletadas, pois essas demandas devem ser solicitadas individualmente, tendo em vista que dependem de outras equipes.

**Comment by TaynaraCh** [comment]
> > Fiz algumas alterações no formulário, a partir do que conversamos, deem uma olhada pra ver se tá ok
> 
> Poderia citar quais foram as alterações? Dessa maneira fica mais rápido e fácil de identificá-las

Escrevi sobre o envio de três logos, ajustes e reenvio, no final do formulário

**Comment by ricardopatrik** [comment]
> Olá, antes de alterar no formulário posto aqui algumas ideias para complementar o formulário de identidade visual:
> 
> * Painel semântico: espaço onde o cliente coloca imagens de referencias com o conceito da logomarca.
> * Qual mensagem que o cliente quer que a logomarca passe?
> * Publico alvo: se é para estudantes, terceirizados, professores, comunidade geral etc..
> * Adjetivos que descreveriam a logo.
> * Logo possui algum slogan?

Adicionei algumas informações sobre slogan publico alvo e mensagem que queira passar.

**Comment by estelavilasboas** [comment]
Questões revisadas. Revisão de descrições em andamento.

**Comment by estelavilasboas** [comment]
Realizar separação de pacotes simples e ccomplexo.

**Comment by estelavilasboas** [comment]
- Seção de "Opcionais" foi renomeada para "Adicionais";
- Precisamos de uma pequena descrição na seção de Adicionais. Precisamos explicar que como observamos que alguns solicitantes viram apenas a necessidade de obter a marca d'água e decidiram retirar a padronagem do projeto, optamos em permitir que o formulário apresente essa opção;
- Peço que @ricardopatrik e @TaynaraCh realizem uma leitura de revisão no formulário e testem sua funcionalidade: 

    1.  Se a seção de Adicionais aparece apenas para os que selecionam o pacote completo;
    2.  Se os campos necessários estão com preenchimento obrigatório.

**Comment by TaynaraCh** [comment]
Revisei e tem dois pontos que acredito que possam ser colocados como obrigatório mas não estão:

- "Descreva o projeto e/ou motivo da solicitação", é importantíssimo pra termos ideias e juntar com as respostas do solicitante;

- "Selecione um pacote de identidade visual", para que apareçam as próximas perguntas de maneira coerente.

Não entendi sobre o que tem que ser escrito na seção "Adicionais", mais precisamente qual a informação vamos passar com a descrição kkkk sorry

**Comment by estelavilasboas** [comment]
Houveram solicitações de pacotes de Identidade Visual Complexa antes, porém os solicitantes não acharam que iriam utilizar a padronagem/estampa e não acharam necessária que ela fosse feita. Por este motivo, temos a seção dos adicionais.
Podemos dizer que seria uma maneira de perguntar se a pessoa acha necessário ter aquilo. Não faz muito sentido fazer algo que o próprio solicitante diz que nunca vai utilizar.
Seria isso para explicar  😆

**Comment by TaynaraCh** [comment]
Escrevi a descrição, mas não tenho certeza se era isso rsrs

**Comment by estelavilasboas** [comment]
Perfeito. Era isso mesmo!

**Comment by VIF-Franca** [comment]
Pessoal temos a nova versão do formulário ? Queria enviar para algumas demandantes para o retorno as férias.

**Comment by estelavilasboas** [comment]
Temos. As alterações foram finalizadas.
Link: https://forms.gle/tcMt9AgVsW3kLvWCA
