### ISSUE TITLE
Nova identidade visual para o template do manual

### ISSUE THREAD

**Issue by isabelirk** [practice-uffs/programa#305]
Esta issue esta sendo criada, visto que não temos um template adequado para a produção de manuais aqui do PRACTICE. Em reunião realizada no dia 17/11/2020 com todos os membros, foi acordado que os ajustes seriam os seguintes:

- [ ] Capa, contracapa, página de crédito e página final com uma cor mais viva. De acordo com a nossa identidade demos a sugestão: HEX # 264653 ou HEX # FA8334.

- [ ] Cor da fonte do sumário, número da página e título do texto da mesma cor selecionada no item anterior.

- [ ] Número da página dentro de um círculo, localizado no canto superior direito. E justificado à direito, ao lado do número da página, o nome do manual.

- [ ] A fonte do manual deve ser a mesma do template antigo, nome: "Roboto".

- [ ] Marca d'água com os desenhos das ondas, que já esta presente no template do manual atualmente. Pode ser uma forma de inspiração.

- [ ] Os títulos, descrição e legenda das imagem na mesma cor selecionada no primeiro item.

- [ ] A capa do manual deve possuir um desenho inspirado nas ondas, que já está presente no template do manual atualmente.

- [ ] Título das seções ou capítulos do manual em fonte diferenciada, sugestão na imagem abaixo:

![índice](https://user-images.githubusercontent.com/31291959/99460884-763eaf80-290f-11eb-8b57-c87d4e8607bb.jpg)

- [ ] Deixar a questão dos créditos presente no desenvolvimento do manual na mesma posição que esta no template atualmente. (Créditos referentes ao texto: 
“Universidade Federal da Fronteira Sul - UFFS
Programa de Ampliação e Consolidação de Tecnologias e Inovação no Contexto Educacional - PRACTICE
https://practice.uffs.cc")

- [ ] Criar caixas de texto grandes, exemplos sem imagem e outro com imagem e texto, e o template ser no formato A4.

**Comment by isabelirk** [comment]
Os matérias que devem ser usados como inspiração estão na seguinte pasta: https://drive.google.com/drive/folders/1i9ionDxb5Up9LZnWUrohxY-uxyaG3kom

Qualquer dúvida estou à disposição.

**Comment by TaynaraCh** [comment]
@mariagelain vai me auxiliar com a diagramação :)

**Comment by TaynaraCh** [comment]
o manual está sendo diagramado no [figma.](https://www.figma.com/file/7i0vabuDtfTjhsts0PWou9/Conte%C3%BAdos?node-id=6%3A2), podem deixar comentários lá se quiserem, ideias opiniões...

**Comment by Dovyski** [comment]
Deixo no registro a sugestão que eu fiz na issue do manual interno que é
fazer ele usando o maker.

Dessa forma, toda a diagramação que a con-design está fazendo seria portada
para o template do maker (pela equipe de dev). Acho que isso nos daria
margem para produzir manuais/cartilhas etc de um jeito mais fácil no futuro.

**Comment by TaynaraCh** [comment]
Agora que o manual está com o sumário finalizado, iremos conseguir realizar a diagramação do material. Para melhor nos organizarmos, irei criar uma nova issue.
