### ISSUE TITLE
Edição de vídeo - Gravação da transmissão SIASS (13/11)

### ISSUE THREAD

**Issue by MilenaPaz2020** [practice-uffs/programa#306]
Por problemas técnicos que inviabilizaram o andamento da transmissão, o cliente pediu para que a gravação do evento fosse editada para ser postada no canal do SIASS.

- [x] Aguardar a aprovação para edição;

- [x] Editar gravações, inserindo vinheta PRACTICE, capa da live, gravações e créditos;

- [x] Upar o vídeo para o canal interno do PRACTICE e gerar legendas;

- [x] Revisão textual das legendas;

- [x] Incluir legendas no vídeo;

- [x] Enviar para aprovação do cliente;

- [x] Fazer adequações, caso necessário;

Arquivos[ aqui](https://drive.google.com/drive/folders/19pID2NSkmiN-lhr9iJ8xmv5Rc3IxibJw).

**Comment by MilenaPaz2020** [comment]
@practice-uffs/con-conteudo, poderiam indicar alguém para fazer a revisão das legendas? Assim eu já posso incluir o nome da pessoa nos créditos.

**Comment by thaliafriedrich** [comment]
> @practice-uffs/con-conteudo, poderiam indicar alguém para fazer a revisão das legendas? Assim eu já posso incluir o nome da pessoa nos créditos.

Eu faço.

**Comment by MilenaPaz2020** [comment]
> > @practice-uffs/con-conteudo, poderiam indicar alguém para fazer a revisão das legendas? Assim eu já posso incluir o nome da pessoa nos créditos.
> 
> Eu faço.

Já está no canal interno do PRACTICE.

**Comment by thaliafriedrich** [comment]
@MilenaPaz2020, não encontrei. Talvez eu não tenho acesso ao canal interno do PRACTICE, tem como me enviar o link?

**Comment by MilenaPaz2020** [comment]
> @MilenaPaz2020, não encontrei. Talvez eu não tenho acesso ao canal interno do PRACTICE, tem como me enviar o link?

Fui conferir e você é uma das administradoras do canal. Tenta alterar a conta para o PRACTICE Interno, depois no canto direito da tela abre as opções, vai em "Youtube Studio". No lado esquerdo vai ter a opção "conteúdo do canal", o vídeo está lá.

Qualquer coisa me chama :)

**Comment by thaliafriedrich** [comment]
Finalizei a revisão das legendas.

**Comment by MilenaPaz2020** [comment]
A primeira versão está na pasta, @robisonjose. Aguardo as sugestões! :)

**Comment by robisonjose** [comment]
Boa tarde @MilenaPaz2020. Demorado revisar uma live toda kkkk.

Algumas coisas que podem ser melhoradas: 

1. Será que não seria possível, no banner e no vídeo da mediadora falando, colocar algum fundo que não seja preto? Ficaria mais agradável de assistir. Talvez algum fundo texturizado com a cor do banner, ou até mesmo o fundo do próprio banner, caso fosse possível encontrá-lo;
2. Próximo do minuto 6:56 ocorre uma mudança na posição da tela da palestrante, se fosse possível deixar a tela da mesma forma que fica depois de 6:56 durante o vídeo todo seria bom;
3. Teria como, quando o palestrante está apresentando, colocar a câmera dele sobreposta aos slides? Ficaria mais interessante. Talvez colocar no canto superior direito, e quando atrapalhar algo dos slides colocar em outro canto, mas deixar sempre que der no canto superior direito;
4. Colocar a transição para os créditos um pouquinho antes do que já está. Para terminar no sorriso bonito da mediadora.

**Comment by MilenaPaz2020** [comment]
> Boa tarde @MilenaPaz2020. Demorado revisar uma live toda kkkk.
> 
> Algumas coisas que podem ser melhoradas:
> 
> 1. Será que não seria possível, no banner e no vídeo da mediadora falando, colocar algum fundo que não seja preto? Ficaria mais agradável de assistir. Talvez algum fundo texturizado com a cor do banner, ou até mesmo o fundo do próprio banner, caso fosse possível encontrá-lo;
> 2. Próximo do minuto 6:56 ocorre uma mudança na posição da tela da palestrante, se fosse possível deixar a tela da mesma forma que fica depois de 6:56 durante o vídeo todo seria bom;
> 3. Teria como, quando o palestrante está apresentando, colocar a câmera dele sobreposta aos slides? Ficaria mais interessante. Talvez colocar no canto superior direito, e quando atrapalhar algo dos slides colocar em outro canto, mas deixar sempre que der no canto superior direito;
> 4. Colocar a transição para os créditos um pouquinho antes do que já está. Para terminar no sorriso bonito da mediadora.

Sem problemas, o vídeo é bem longo mesmo. Agradeço os apontamentos! Sobre a mudança, foi por conta da gravação do Webex (os solicitantes não colocaram em tela cheia, quando um novo participante entrou na sala desconfigurou bastante. Tentei "arrumar" de várias formas).

A questão que me preocupa agora é que a solicitante entrou em contato comigo, pedindo se seria possível enviar amanhã de manhã. Não tendo tempo hábil para realizar as mudanças, peço para postergar a entrega ou envio assim mesmo?

**Comment by robisonjose** [comment]
Boa noite @MilenaPaz2020. 

Explica a situação para ela. Se ela precisar com urgência, disponibiliza essa versão e depois faz as alterações. 

Porém, creio que o @MaNegrao sabe como lidar com esse empasse melhor que eu. 

Caso ele não responda a tempo, faça isso que falei. Isso se você já não resolveu com ela.

**Comment by MaNegrao** [comment]
Eu acho que é válido conversar, como o Robison disse, ver se ela acha necessário alterar alguma coisa. Caso não precise, melhor pra todos, já que eles não ficam sem o vídeo e nós não temos que apressar trabalho.

**Comment by MilenaPaz2020** [comment]
> Boa noite @MilenaPaz2020.
> 
> Explica a situação para ela. Se ela precisar com urgência, disponibiliza essa versão e depois faz as alterações.
> 
> Porém, creio que o @MaNegrao sabe como lidar com esse empasse melhor que eu.
> 
> Caso ele não responda a tempo, faça isso que falei. Isso se você já não resolveu com ela.

Enviada para a solicitante. Ela vai compartilhar amanhã na reunião do setor para ver se é necessário alguma adequação.

**Comment by MilenaPaz2020** [comment]
Solicitante aprovou o vídeo, creio que essa issue pode ser encerrada.

**Comment by robisonjose** [comment]
Fechou então. Bom trabalho!
