### ISSUE TITLE
Montagem de vídeo - Semana Academica de CC 2019

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#308]
A coordenação do curso de ciência da computação do campus chapecó nos solicitou a montagem de um vídeo com as imagens feitas durante a semana academica do curso do ano passado. O vídeo não tem minutagem limite, o objetivo é apenas mostrar o evento.

O prazo de entrega final é até o final da sprint 10 - 08/12

O solicitante nos enviou as seguintes orientações:

> Temos diversos vídeos pequenos que precisam ser integrados em uma compilação única, com as seguintes características:
> 
> - Iniciar com a vinheta do curso (na pasta do drive);
> - Arte (que já temos) informando sobre a semana acadêmica;
> - Música ao longo do vídeo
> - Diversos overlays ao longo do vídeo para demonstrar as diferentes atividades (ex.: "Campeonato de e-sports", "Oficina de 
> UI/UX", etc);
> - Várias seções com transições entre elas. [Nesse link](https://drive.google.com/drive/u/0/folders/1Bq9PxEUrxp4Cuw77oiksXNBltWox3Va9), há várias pastas com videos em casa. Com exceção da pasta "Misc", cada uma das pastas pode ser considerada uma seção do vídeo, que terá uma tela/tarja (com o nome da pasta, por exemplo, "Palestras").
> 
> A pasta "Misc" contém vários vídeos gravados ao longo do evento. Esses vídeos podem ser usados ao longo do video para deixar o material mais interessante, como cortes e transições.
> 
> Gostaríamos que o audio dos videos não fosse usado. Uma música de fundo pode tocar ao longo de todo o video, preferencialmente com uma pegada rock.
> Sintam-se livres para fazerem a edição e adicionr efeitos da melhor forma possível para tornar o material interessante de ser visto. A ideia é documentar o evento e mostrar tudo que ele teve a oferecer aos alunos/comunidade.
> 
> Como dica, geralmente os videos do curso tem elementos com esse cunho visual:
> 
> https://docs.google.com/drawings/d/1i_eHZJ9_vJIeXPGaBepqhXCASHJdKsFqzDCLY0stCRg/edit?usp=sharing
> https://docs.google.com/drawings/d/1GeBc3TpUvZYmrugdvoPEW0YspCRD_t9dRoZXOneeYPs/edit?usp=sharing
> https://docs.google.com/drawings/d/1rgq410UZU_OSm9tMA2vIKgr_Ony77uqJZ_AIe32zoYA/edit?usp=sharing

A montagem pode ser bem livre, usem a critatividade e façam um material bem legal e descontraido.

[Pasta Drive](https://drive.google.com/drive/folders/12Dd4YC1JZ-0rIX0cze2s-2nmhM7u1Vi9)

CC: @practice-uffs/con-midia

**Comment by luizdameda** [comment]
Onde está a arte do evento? Não localizei ela nas pastas....

A vinheta do PRACTICE adiciono somente no fim do vídeo?

**Comment by MaNegrao** [comment]
Vou verfificar no e-mail e caso tenha deixado de lado vou pedir para o solicitante e te retorno.

Quanto a vnheta do PRACTICE, sim, somente no final

**Comment by luizdameda** [comment]
@MaNegrao por acaso já te enviaram a arte? Eu já montei o vídeo, só falta a arte e alguns ajustes

**Comment by MaNegrao** [comment]
Ainda não, vou pedir e te retorno em breve

**Comment by MaNegrao** [comment]
Segue 

Claro: https://docs.google.com/presentation/d/1Sa6oe_QAvPc9eQhAcLcnQvFwGPCGTbKXN6nMqHRKqYY/edit?usp=sharing
Essa é a arte que utilizamos para esse evento em específico.


Aqui são algumas artes usadas em videos do curso (em geral):


https://docs.google.com/drawings/d/1i_eHZJ9_vJIeXPGaBepqhXCASHJdKsFqzDCLY0stCRg/edit?usp=sharing
https://docs.google.com/drawings/d/1GeBc3TpUvZYmrugdvoPEW0YspCRD_t9dRoZXOneeYPs/edit?usp=sharing
https://docs.google.com/drawings/d/1rgq410UZU_OSm9tMA2vIKgr_Ony77uqJZ_AIe32zoYA/edit?usp=sharing

**Comment by luizdameda** [comment]
O vídeo finalizado encontra-se [nesta pasta](https://drive.google.com/drive/u/1/folders/1UdpI3j8HC7Wg0JH6qUbnd9DjIdepoZAs)

@MaNegrao encaminha para o solicitante! Acredito que tenha atendido bem o pedido dele, mas caso tenha algum erro ou seja necessária alguma alteração, eu faço!
Nos créditos usei o nosso layout padrão, mas talvez o layout oficial do curso, em cinza, ficaria melhor e combinando mais com o vídeo, se o solicitante desejar, e se for liberado pela nossa gerência, posso refazer o vídeo mudando isso.

**Comment by robisonjose** [comment]
Bom dia @luizdameda 

O vídeo ficou bem bacana, eu gostei. Mas tenho algumas observações: 

1. Nas transições, quando você coloca "palestras, oficinas, etc" tem uma bordinha branca do lado esquerdo que poderia ser retirada;
2. Em 02:58 aparece um frame bem rápido da lâmpada do PRACTICE, deve ser retirado;
3. Realmente ia ficar muito melhor se os créditos tivessem o layout deles;
4. Acredito que nas transições poderia ser retirado o movimento das palavras, ou colocado algo mais simples. Pelo que vejo nos vídeos deles eles são bem minimalistas, talvez algo parecido com [isso](https://docs.google.com/drawings/d/1i_eHZJ9_vJIeXPGaBepqhXCASHJdKsFqzDCLY0stCRg/edit) e ai com um movimento apenas de aparecimento, sem andar pela tela. Acredito que talvez ficaria mais na cara deles. 

De resto está bem bom, gostei de música também, combinou.

**Comment by MaNegrao** [comment]
O solicitante retornou com os seguintes apontamentos:


> A sequência de imagens e encadeamento dos elementos dessa primeira versão está excelente.
> As transições (palestras, etc), porém, não está legal. A demonstração dos conteúdos também está muito linear (nenhuma troca de cenas, câmera lenta, velocidade maior, etc).
> 
> Gostaria que o seguinte fosse alterado:
> 
> 1) Adicionar nos créditos finais do vídeo o seguinte:
> Round Glitch Circle Frame , Strong Contrast Glitch Bundle, Target Animation - Gear by freestockfootagearchive.com
> 
> 2) Refazer as transições/telas da seguinte forma;
> - Não usar a imagem dessa versão 1;
> - Ao invés, colocar o texto no centro, apenas com animação de fade-in, sobreposto a esse vídeo [1], ambos sobrepostos ao vídeo do evento em preto e branco e em câmera lenta (ver esse vídeo para referência [2])
> - Antes de uma transição/tela ser mostrada, colocar por alguns segundos (2 a 3 segundos, por exemplo) algum dos segmentos de glitch desse vídeo [3]
> 
> 3) Para algumas cenas do vídeo, colocar a velocidade em câmera lenta e outras mais rápida, para deixar o conteúdo mais interessante (ver esse material como referência [4])
> 
> 4) Ao longo do vídeo, em algumas partes, e por poucos segundos (2 a 3 segundos), sobrepor as imagens com esse overlay [5] com transparência e ampliado
> 
> ------------------------
> 
> [1] - https://freestockfootagearchive.com/round-glitch-circle-frame-broken-visual-effect-loop/ 
> [2] - https://drive.google.com/file/d/1tYOGGfCd_bPT2DjgyPwm9sEfpbCCMzuA/view?usp=sharing 
> [3] - https://freestockfootagearchive.com/strong-contrast-glitch-bundle-overlays-backgrounds/ 
> [4] - https://www.youtube.com/watch?v=j7F41W3XPhw 
> [5] - https://freestockfootagearchive.com/target-animation-gear-hud-circle-animation-project-file/

**Comment by luizdameda** [comment]
> O solicitante retornou com os seguintes apontamentos:
> 
> > A sequência de imagens e encadeamento dos elementos dessa primeira versão está excelente.
> > As transições (palestras, etc), porém, não está legal. A demonstração dos conteúdos também está muito linear (nenhuma troca de cenas, câmera lenta, velocidade maior, etc).
> > Gostaria que o seguinte fosse alterado:
> > 
> > 1. Adicionar nos créditos finais do vídeo o seguinte:
> >    Round Glitch Circle Frame , Strong Contrast Glitch Bundle, Target Animation - Gear by freestockfootagearchive.com
> > 2. Refazer as transições/telas da seguinte forma;
> > 
> > 
> > * Não usar a imagem dessa versão 1;
> > * Ao invés, colocar o texto no centro, apenas com animação de fade-in, sobreposto a esse vídeo [1], ambos sobrepostos ao vídeo do evento em preto e branco e em câmera lenta (ver esse vídeo para referência [2])
> > * Antes de uma transição/tela ser mostrada, colocar por alguns segundos (2 a 3 segundos, por exemplo) algum dos segmentos de glitch desse vídeo [3]
> > 
> > 
> > 1. Para algumas cenas do vídeo, colocar a velocidade em câmera lenta e outras mais rápida, para deixar o conteúdo mais interessante (ver esse material como referência [4])
> > 2. Ao longo do vídeo, em algumas partes, e por poucos segundos (2 a 3 segundos), sobrepor as imagens com esse overlay [5] com transparência e ampliado
> > 
> > 
> > [1] - https://freestockfootagearchive.com/round-glitch-circle-frame-broken-visual-effect-loop/
> > [2] - https://drive.google.com/file/d/1tYOGGfCd_bPT2DjgyPwm9sEfpbCCMzuA/view?usp=sharing
> > [3] - https://freestockfootagearchive.com/strong-contrast-glitch-bundle-overlays-backgrounds/
> > [4] - https://www.youtube.com/watch?v=j7F41W3XPhw
> > [5] - https://freestockfootagearchive.com/target-animation-gear-hud-circle-animation-project-file/

Vou precisar da ajuda do @robisonjose ou da @amandasegattob para essas alterações porque estão bem além do meu conhecimento, principalmente nessa questão das transições e no tópico 4 que não entendi muito bem :s

**Comment by lcaimi** [comment]
Minuto 1:37
A palavra "Confraternização" precisa ser corrigida pois está faltando um "r"

**Comment by amandasegattob** [comment]
Posso ajudar sim!

**Comment by robisonjose** [comment]
@luizdameda acredito que seria bom você upar no drive o projeto para que a @amandasegattob possa editar. 

E sobre essas transições. 

Você só baixa os vídeos que eles colocaram ali, e ai em vez de usar aquela tela de transição, você deixa um vídeo preto e branco rodando no fundo (do evento), em cima disso você coloca o vídeo (1) que eles pediram, e em cima disso você coloca o texto aparecendo em fade in. Ai antes de aparecer essa tela de transição tu coloca o outro vídeo (3) em cima dos vídeos que já estão aparecendo. 

E ai para fazer isso, acredito que você tenha que adicionar alguma mascará de fundo verde, para tirar a parte preta (fundo preto nesse caso) dos vídeos de "glitch". 

E o tópico 4 é a mesma coisa, tu baixa o vídeo, coloca uma máscara de fundo preto nele, para que apareça só a parte branca, e coloca ele em momentos aleatórios do vídeo, tipo quando alguém está mexendo na câmera, ai tu coloca esse vídeo na lente da câmera, quando aparece um computador, tu coloca na tela do computador, coisas desse tipo. Ai vai da tua criatividade.

**Comment by luizdameda** [comment]
Adicionei o projeto do Shotcut [nesta pasta](https://drive.google.com/drive/u/1/folders/1EVIJXmtHmAcGHQeiQm05Fcw7MLU9_nnE). Eu não lembro se é necessário que a @amandasegattob baixe os arquivos que utilizei no vídeo também, mas se não me engano tem que baixar para que o programa localize os arquivos. Agora tenho aula, mas assim que chegar upo os arquivos que usei.

Obrigado pelas explicações, @robisonjose

**Comment by amandasegattob** [comment]
Bom dia! Fiz as alterações conforme foi pedido, está [nessa pasta](https://drive.google.com/drive/u/0/folders/1UdpI3j8HC7Wg0JH6qUbnd9DjIdepoZAs).

@MaNegrao @robisonjose

**Comment by robisonjose** [comment]
Bom dia @amandasegattob. 

Alterações que podem ser feitas: 

1. Deixar o início do vídeo parecido com o que o Luiz fez até o 00:21 (do vídeo dele), colocando apenas o [5] na primeira imagem após a vinheta do curso. Colocar o efeito em cima do círculo do canto direito;
2. Depois desse passo acima, daria para começar com a sua versão do vídeo, iniciando na vinheta do "palestras", e claro, antes disso, colocar aquele glitch de transição;
3. O efeito que aparece em 00:24 está meio sem sentido, daria para tirar, ou aumentar bastante a transparência dele;
4. Em 00:56 dá para colocar o efeito [5], mas ele deve estar bem transparente, e em algum lugar da tela do computador;
5. Repetir passo 4 no minuto 1:12, colocando o efeito no dinossauro;
6. Repetir passo 4 em 1:57, colocando o efeito no monte de cartas; 
7. O efeito que aparece em 02:12 está meio sem sentido, daria para tirar, ou aumentar bastante a transparência dele;
8. Daria para trocar o "Vídeos" nos créditos por "Materiais" ou "Arte", ou algo do tipo;
9. Deixar todas as palavras que aparecem nas transições centralizadas e trocar a cor, colocar o amarelo ou o azul da paleta de cores deles.

Apesar das alterações que acredito que podem ser feitas, o vídeo está ficando bem legal.

**Comment by amandasegattob** [comment]
@robisonjose fiz as alterações, está na mesma pasta. Tentei seguir o que você falou, mas caso precise de mais alterações, é só falar.

**Comment by robisonjose** [comment]
Bom dia @amandasegattob. 

Eu gostei bastante dessa versão, mas vou pedir desculpas pq realmente as escritas em branco combinaram mais (perdão), então acho que daria para voltar para o branco em vez do laranja. E sobre aqueles efeitos que eles pediram para colocar de vez em quando no vídeo [5]. Não sei você, mas me parece que não está encaixando. Daria para retirar, mandar para eles revisarem e ver o que eles falam.

**Comment by amandasegattob** [comment]
@robisonjose pois é, também achei o branco melhor e, sobre os efeitos, concordo contigo, não encaixa. Vou tirar e podemos mandar as duas versões para eles (com e sem), assim fica mais visual e eles podem nos dar um feedback de como imaginaram.

**Comment by robisonjose** [comment]
Perfeito @amandasegattob.

**Comment by amandasegattob** [comment]
@robisonjose fiz as alterações, está como ''CC ATUALIZADO''.

**Comment by MaNegrao** [comment]
Uma coisa sugerida hoje na reunião de lideres, foi a utilização de color correction, será que rola de usar algum filtro de correção de cor nesses videos? Perdão pelo trabalho a mais hahah

**Comment by amandasegattob** [comment]
> Uma coisa sugerida hoje na reunião de lideres, foi a utilização de color correction, será que rola de usar algum filtro de correção de cor nesses videos? Perdão pelo trabalho a mais hahah

Oie, então, não sei se sei fazer isso kkkk. Seria meio que tratar a imagem, certo?

**Comment by MaNegrao** [comment]
Sim, deixar ela mais bonita

**Comment by Dovyski** [comment]
Geralmente essa funcionalidade de correção de cores está disponível em softwares de edição de vídeo como "color grading" (no shotcut é exatamente esse o nome do filtro):

![image](https://user-images.githubusercontent.com/512405/100875662-1571b400-3485-11eb-91a0-47393efc96ad.png)

Depois geralmente se ajusta um "tom" de cor para as sombras, gamma e ganho para deixar o video mais vívido:

![image](https://user-images.githubusercontent.com/512405/100875746-2f12fb80-3485-11eb-88aa-4713bf6326a0.png)

Por exemplo, em imagens com paisagem verde, pode-se ajudar esses 3 componentes para deixar a grama/árvores mais verde e as sombras mais escuras.

**Comment by amandasegattob** [comment]
Boa tarde, coloquei o vídeo na [pasta do drive](https://drive.google.com/drive/u/0/folders/1UdpI3j8HC7Wg0JH6qUbnd9DjIdepoZAs). 

Não sei se era bem isso, mas tentei deixar as cores mais vivas. Se precisar de novas alterações, é só falar.

**Comment by robisonjose** [comment]
Boa tarde @amandasegattob. 

Parabéns, eu achei o vídeo muito bom. A única coisa que me incomoda um pouco é a qualidade da imagem de 00:05, a qual eu acho muito importante de estar ali, porém ela é a única que tem uma qualidade bem mais ou menos, daria para pedir pro solicitante se eles não têm uma imagem com qualidade melhor.

Mas de resto eu achei muito bom, as cores ficaram bem vivas e contrastantes. Ótimo trabalho.

**Comment by MaNegrao** [comment]
Eu coloquei uma imagem no formato .svg na pasta do drive, talvez ajude a melhorar a qualidade...

**Comment by amandasegattob** [comment]
> Eu coloquei uma imagem no formato .svg na pasta do drive, talvez ajude a melhorar a qualidade...

Eu não encontrei a imagem, vc pode mandar o link da pasta?

**Comment by MaNegrao** [comment]
Eu tinha baixado mas não colocado na pasta haha. Agora tá na pasta entrada

**Comment by amandasegattob** [comment]
O vídeo está na [pasta](https://drive.google.com/drive/u/0/folders/1UdpI3j8HC7Wg0JH6qUbnd9DjIdepoZAs).

**Comment by MaNegrao** [comment]
Resposta do solicitante :D

> O vídeo está incrível, obrigado!
> 
> Só tem uma coisa que ficou "ruim": a parte do efeito de glitch colocado sobre o video.
> Eu acho que o pessoal da edição usou apenas um filtro de chroma key para remover o fundo, mas não mexeu nas propriedades da camada/layer onde o video do glitch está.
> 
> No shotcut, por exemplo, basta clicar com o botão direito no nome da camada, escolher "Properties", e dai escolher o "Blend mode" que fica melhor:
> 
> ![layer-prop](https://user-images.githubusercontent.com/31110971/101408267-f0cd7000-38ba-11eb-8c06-72bd1d58db1c.gif)
> 
> O blend mode é da camada, ou seja, como a camada será "juntada" com as demais camadas. Por exemplo, "Add" adiciona os pixels, "Overlay" coloca eles sobre (com transparência), etc.
> 
> 
> P.S. os créditos no final, com o estilo do curso, ficaram MARAVILHOSOS! Só os créditos e a vinheta final do practice já vale o vídeo hahaha

**Comment by robisonjose** [comment]
Olá @amandasegattob, 

(Continuação da nossa conversa no Telegram) 

Postei um vídeo do que EU ACHO que eles estão pedindo [aqui](https://drive.google.com/drive/u/2/folders/1EVIJXmtHmAcGHQeiQm05Fcw7MLU9_nnE), com o nome de "telecurso2000". 

Enviei aqui pois pode ser que em algum momento alguém tenha a mesma dúvida e pode ser que ajude. 

Eu não tenho muita experiência com o ShotCut mas acredito que seja isso.

**Comment by amandasegattob** [comment]
Boa tarde! Fiz as alterações. Muito obrigada @robisonjose!

**Comment by robisonjose** [comment]
Olá @MaNegrao,

Poderia, por obséquio, enviar ao solicitante?

**Comment by MaNegrao** [comment]
> Olá @MaNegrao,
> 
> Poderia, por obséquio, enviar ao solicitante?

Enviarei senhor

**Comment by MaNegrao** [comment]
Olá pessoal, primeiramente quero parabénizar todos vocês pelo empenho ao vídeo, e agradecer em nome do solicitante o trabalho maravilhoso que foi feito :D 
Por último dizer que estou fechando e encerrando a demanda <3
