### ISSUE TITLE
Live -  Abertura I Jornada de formação de monitores de ensino da UFFS - 09/12 - 15h

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#309]
Live de abertura para jornada de formação de monitoria de ensino na UFFS

Palestra com o tema “Iniciação à docência na monitoria”
Ministrada pela Dra. Prof.ª Dra. Maria Lúcia Marocco Maraschin (Docente da UFFS – Campus Chapecó)
Data: 09 de dezembro de 2020
Horário: 15h às 17h 

O roteiro está na pasta do drive

Precisaremos montar uma arte para esse evento, bem como uma arte apara toda a jornada. Que estarão em issues diferentes

[Pasta Drive](https://drive.google.com/drive/folders/11jkRI993MK0UCl29DLcLS5l431I1Rut9)

CC: @practice-uffs/con-midia

**Comment by pedroamaximowski** [comment]
live finalizada.
 https://youtu.be/odL-thg7bZw
