### ISSUE TITLE
Criação de convite para Live #309 - Abetura I jornada de formação de monitores

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#310]
Foi solicitado o auxilio do PRACTICE na realização do evento: Evento de abertura da I Jornada de formação inicial e continuada de monitores de ensino da UFFS – 2020/2021 e também a criação de um convite de divulgação para esse evento. Com as informações do solicitante:

> Na capa da live para o dia 09/12 precisa constar basicamente as informações abaixo:
> 
> Evento de abertura da I Jornada de formação inicial e continuada de monitores de ensino da UFFS – 2020/2021
> Palestra com o tema “Iniciação à docência na monitoria”
> Ministrada pela Dra. Prof.ª Dra. Maria Lúcia Marocco Maraschin (Docente da UFFS – Campus Chapecó)
> Data: 09 de dezembro de 2020
> Horário: 15h às 17h
> Link live: https://youtu.be/odL-thg7bZw (pode fazer um qrcode)
> Inscrições: não é necessária inscrição prévia, no dia do evento haverá lista de presença para certificação
> Organização: Diretoria de Políticas de Graduação/Pró-Reitoria de Graduação da UFFS (+ logo da UFFS) ([identidade da uffs](https://www.uffs.edu.br/institucional/reitoria/diretoria_de_comunicacao_social/identidade_visual))

Pode se usar o exemplo da issue #300 e também se espelhar no exemplo que está na pasta

[Pasta Drive](https://drive.google.com/drive/folders/1UgBPpBp5FzYkaIdEOQRpkuQ9UuNiUZ8L)

CC: @practice-uffs/con-midia @practice-uffs/con-design @practice-uffs/con-conteudo

**Comment by estelavilasboas** [comment]
Por conta do trabalho realizado na issue #300, peço que o @ricardopatrik fique encarregado.

**Comment by ricardopatrik** [comment]
Coloquei 02 alternativa na pasta

**Comment by MaNegrao** [comment]
O solicitante escolheu a versão em 16:9 e com o fundo com livros, você pode seguir com esse modelo para o folder de divulgaçaõ de todo o evento.

A capa está de fato finalizada? Se sim a issue pode ser encerrada

**Comment by ricardopatrik** [comment]
Coo assim de todo o evento?

**Comment by MaNegrao** [comment]
Tem um exemplo na pasta da issue, da uma olhada lá.

**Comment by ricardopatrik** [comment]
Sim sim, agora eu vi. Ignore a pergunta kk

**Comment by estelavilasboas** [comment]
Passei dando uma olhadinha e gostaria de dizer que ficou muito bom! 😄

**Comment by MaNegrao** [comment]
A solcitante aprovou, pediu para usassemos na issue #311 o mesmo tema de livro utilizada na versão horizontal. Iremos fazer um convite para cada live do evento como um todo, então deixamos como padrão esse tema.

Ps: Eu curti muito, parabéns!
