### ISSUE TITLE
Criação de divulgação I Jornada de formação de monitores UFFS 2020/2021

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#311]
O PRACTICE foi acionado para auxiliar no evento da jornada de formação de monitores. 

Seguindo as issues #309 e #310 devemos fazer um cronograma do evento todo seguindo o modelo enviado pelo solicitante que está na pasta do drive.

As informações dos eventos necessarias também estão na pasta do drive.

Quando tivermos mais informações dos proximos eventos serão necessarias artes para eles individualmente também.

[Pasta Drive](https://drive.google.com/drive/folders/12PpodEx0fuOZDTCBRYWktmwnK7NLvemS)

CC: @practice-uffs/con-design @practice-uffs/con-conteudo

**Comment by alessandrapedrotti** [comment]
@ricardopatrik como já estás trabalhando na issue #310, podes trabalhar nessa tarefa também.
Pelo que eu entendi seria criar um panfleto com a programação do evento, correto @MaNegrao?

**Comment by MaNegrao** [comment]
Exatamente, com as informações do documento da pasta

**Comment by ricardopatrik** [comment]
Fiz a alternativa, mudei um pouco a foto dos livros para se adequar com o texto.

**Comment by MaNegrao** [comment]
Alterações solicitadas pelo cliente:

>  talvez dê para fazer o texto em letras maiores, achei pequeno. Também é importante constar que a programação é da DPGRAD/prograd, como está no convite da atividade do dia 09/12, bem como a informação de que não é necessário inscrição previa, bem como o endereço do canal para acesso. E tirar deste material a expressão "evento de abertura", pois se trata de toda a programação do curso.

Pode colocar os links dos eventos seguintes:

Etapa 1 - https://youtu.be/odL-thg7bZw
Etapa 3 - https://youtu.be/sW1s4SXxgZk
Etapa 4 - https://youtu.be/9HyQpwIhTto
Etapa 5 - https://youtu.be/fsKpGzDQBEg

Creio que de pra colocar um aviso geral também, como: "No canal do PRACTICE no youtube"

A solicitante pediu que se possivel, poder enviar até amanhã

**Comment by ricardopatrik** [comment]
FEITO

**Comment by MaNegrao** [comment]
> FEITO

Valeeu, vou enviar ao solicitante

**Comment by MaNegrao** [comment]
Convite aceito pelo solicitante
