### ISSUE TITLE
Criação de Identidade Visual - Programa de Educação Tutorial (PET)

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#312]
Criação de logomarca institucional para o Programa de Educação Tutorial - PET, onde são 05 grupos distribuídos em 05 campi da UFFS. Usar como exemplo a do site da UNIPAMPA [link](https://sites.unipampa.edu.br/pet/). Prazo dia 10 de dezembro, de acordo com a tabela de prazos.

O formulário para preenchimento já foi enviado à solicitante. Qualquer dúvida sobre a demanda só perguntar.

[Pasta da issue](https://drive.google.com/drive/folders/11DdZfEqNd0pfx7APzgTqu92DdeJ-uu_s)

CONTATO: 
Debora Cristina Costa - e-mail:          debora.costa@uffs.edu.br; 
Técnica em Assuntos Educacionais
Diretoria de Políticas de Graduação - DPGRAD/PROGRAD
Universidade Federal da Fronteira Sul
(49) 2049 3712

**Comment by ricardopatrik** [comment]
Boa tarde, no aguardo do formulário preenchido pela solicitante.

**Comment by ricardopatrik** [comment]
> Criação de logomarca institucional para o Programa de Educação Tutorial - PET, onde são 05 grupos distribuídos em 05 campi da UFFS. Usar como exemplo a do site da UNIPAMPA [link](https://sites.unipampa.edu.br/pet/). Prazo dia 10 de dezembro, de acordo com a tabela de prazos.
> 
> O formulário para preenchimento já foi enviado à solicitante. Qualquer dúvida sobre a demanda só perguntar.

esse link não abriu aqui

**Comment by VIF-Franca** [comment]
> > Criação de logomarca institucional para o Programa de Educação Tutorial - PET, onde são 05 grupos distribuídos em 05 campi da UFFS. Usar como exemplo a do site da UNIPAMPA [link](https://sites.unipampa.edu.br/pet/). Prazo dia 10 de dezembro, de acordo com a tabela de prazos.
> > O formulário para preenchimento já foi enviado à solicitante. Qualquer dúvida sobre a demanda só perguntar.
> 
> esse link não abriu aqui

Bah @ricardopatrik  veja se abre:

https://sites.unipampa.edu.br/pet/

**Comment by VIF-Franca** [comment]
> > > Criação de logomarca institucional para o Programa de Educação Tutorial - PET, onde são 05 grupos distribuídos em 05 campi da UFFS. Usar como exemplo a do site do [link](https://sites.unipampa.edu.br/pet/) UNIPAMPA . Prazo dia 10 de dezembro, de acordo com a tabela de prazos. 
> > > O formulário para preenchimento já enviado à solicitante. Qualquer dúvida sobre a demanda só pergunta.
> > 
> > 
> > esse link não abriu aqui
> 
> Bah @ricardopatrik veja se abre:
> 
> https://sites.unipampa.edu.br/pet/

@ricardopatrik

**Comment by VIF-Franca** [comment]
A cliente já confirmou a resposta no formulário e ressaltou que será apenas uma logomarca para todos os campi!

**Comment by TaynaraCh** [comment]
Eu posso ficar com essa issue

**Comment by VIF-Franca** [comment]
Show,

**Comment by ricardopatrik** [comment]
onde eu posso ver o formulário preeenchido?

**Comment by ricardopatrik** [comment]
Segue alguma opções junto com a logo para usar como referência. usei cores com contraste, useipoucas cores pois pedia algo mais leve. Efeito na palavra PET nas ultimas duas opções como se fosse algo de giz (tentei). Fico aberto para opinião de vocês e criticas.


![LOGO PET_Prancheta 1](https://user-images.githubusercontent.com/71683219/101197421-dc7e3e80-3640-11eb-9ef7-7057d9be2474.jpg)

**Comment by ricardopatrik** [comment]
coloquei na pasta do drive as logo separadas para melhor envio e visualização do soicitatne.

**Comment by ricardopatrik** [comment]
alguma resposta?

**Comment by estelavilasboas** [comment]
- Assim como na [pasta da Identidade de Masculinidades](https://drive.google.com/drive/folders/1iKLTwLrfrcxgy18do6i-1YFbi-NIic8P), deve ser criada uma pasta chamada "primeiro envio". Ela deve conter uma breve explicação sobre o que foi pensado na criação da logo e as imagens das propostas. 
- Seria bom mantermos um padrão com as imagens das propostas. Nesse caso, a proposta deve conter a paleta de cores utilizada.

**Comment by ricardopatrik** [comment]
Está feito

**Comment by estelavilasboas** [comment]
@VIF-Franca já podemos encaminhar para a solicitante

**Comment by VIF-Franca** [comment]
`AGUARDANDO FEEDBACK`

**Comment by VIF-Franca** [comment]
`FEEDBACK DO CLIENTE

> Bom dia!
> 
> Agradecemos o retorno e informamos que socializamos as artes criadas com os tutores do PET, que solicitaram a possibilidade de alterar as cores, colocar cores mais vivas, coloridas, que representem a diversidade. Sobre os círculos, a sugestão é que fossem retirados, porque entenderam que ficaram deslocados. Pediram a possibilidade de fazer uma arte parecida com a do PET Unipampa (que segue anexa).
> Obrigada, mais uma vez, pelo trabalho realizado!
> Estamos à disposição para qualquer dúvida.

**ANEXO**

![Logo PET Unipampa](https://user-images.githubusercontent.com/66980370/102787311-a6022c80-437f-11eb-884d-a6afe2a747e0.jpeg)

**Comment by ricardopatrik** [comment]
Na pasta [Segundo Envio](https://drive.google.com/drive/folders/1fd5pdZ3UaQlHJywC3TAPkBuFp8Ctsyz6) está feita as alterações para mandar para a solicitante.

**Comment by VIF-Franca** [comment]
Material enviado ao cliente!

`AGUARDANDO FEEDBACK
`

**Comment by estelavilasboas** [comment]
@ricardopatrik Favor colocar os editáveis da logo na [pasta da issue](https://drive.google.com/drive/folders/11DdZfEqNd0pfx7APzgTqu92DdeJ-uu_s).

**Comment by VIF-Franca** [comment]
Pessoal o cliente revisou a criação da Logo, segue o e-mail: 

> O pessoal acabou preferindo as artes enviadas anteriormente (essas em anexo). Pedimos se os círculos que tem embaixo fazem parte do desenho ou são apenas a paleta de cores. Se fazem parte, a sugestão é retirá-los.
Na logo 1, se possível ampliar um pouquinho a sigla UFFS.
Na logo 2, completar o círculo.
Agradecemos novamente a atenção e disponibilidade!


[Logo nas pastas](https://drive.google.com/drive/folders/14168VgJMLxJxQZxCEm5VkHRK7sr8YoL3?usp=sharing)

**Comment by estelavilasboas** [comment]
> Pessoal o cliente revisou a criação da Logo, segue o e-mail:
> 
> > O pessoal acabou preferindo as artes enviadas anteriormente (essas em anexo). Pedimos se os círculos que tem embaixo fazem parte do desenho ou são apenas a paleta de cores. Se fazem parte, a sugestão é retirá-los.
> > Na logo 1, se possível ampliar um pouquinho a sigla UFFS.
> > Na logo 2, completar o círculo.
> > Agradecemos novamente a atenção e disponibilidade!
> 
> [Logo nas pastas](https://drive.google.com/drive/folders/14168VgJMLxJxQZxCEm5VkHRK7sr8YoL3?usp=sharing)

Respondendo a parte dos "círculos" abaixo das logos, eles são as representações da paleta utilizada na logo e não fazem parte da logo em si.

**Comment by VIF-Franca** [comment]
Posso firmar a reunião com o cliente para:

`A reunião poderia ser dia 19/02, às 9h?`

Conforme a sugestão do cliente. 


cc: @alessandrapedrotti @estelavilasboas @TaynaraCh

**Comment by alessandrapedrotti** [comment]
> Posso firmar a reunião com o cliente para:
> 
> `A reunião poderia ser dia 19/02, às 9h?`
> 
> Conforme a sugestão do cliente.
> 
> cc: @alessandrapedrotti @estelavilasboas @TaynaraCh

Estou de acordo com o horário. Assim que as meninas confirmarem da parte delas, farei o evento para ser enviado ao solicitante.

**Comment by TaynaraCh** [comment]
> Posso firmar a reunião com o cliente para:
> 
> 
> 
> `A reunião poderia ser dia 19/02, às 9h?`
> 
> 
> 
> Conforme a sugestão do cliente. 
> 
> 
> 
> 
> 
> cc: @alessandrapedrotti @estelavilasboas @TaynaraCh 
> 
> 

Sim! Pode ser esse dia e horário!

**Comment by alessandrapedrotti** [comment]
@VIF-Franca, pode passar para o solicitante a confirmação da reunião, te passarei no telegram o link do googlemeet que deve ser enviado com a confirmação.

**Comment by VIF-Franca** [comment]
E-mail enviado.

**Comment by VIF-Franca** [comment]
Adicionei [na pasta](https://drive.google.com/drive/folders/19IYuA_v9OM3P6oMB_HNEZo6NQ6yVsxeZ?usp=sharing) imagens enviadas pelo solicitante.
