### ISSUE TITLE
Live Editora UFFS - Literatura como transgressão de modelos - 04/12 - 18h

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#313]
Live solicitada pelo conselho editorial da editora uffs.

Data: 27/11/2020
Horário de início: 18h 
Horário de término: 20h 

Ministrantes | Ronald 			Augusto (escritor) 	e Roberta 			Flores Pedroso (Doutoranda UFRGS)
-- | --
Mediador | Professor 			Doutor Demétrio Alves Paz (Presidente do Conselho Editorial da 			Editora UFFS)

Link: https://youtu.be/85cnqj88lI0

[Pasta Drive](https://drive.google.com/drive/folders/1HScyS0P-bQD19zP5Oi3fjbWDhof4EmtD)

CC: @practice-uffs/con-midia

**Comment by luizatonial** [comment]
verifiquei que o Pedro tem horário disponível na sexta pela manhã. @pedroamaximowski você consegue assumir?

**Comment by MaNegrao** [comment]
A live foi alterada para o dia 04/12. O horario ainda será definido.

**Comment by MaNegrao** [comment]
A issue foi atualizada com as novas informações da live, que será no dia 4 as 18

**Comment by luizatonial** [comment]
mesmo alterando a hora não vou conseguir fazer neste dia.
@pedroamaximowski ou @rafaguilman alguém consegue assumir essa live?

**Comment by rafaguilman** [comment]
Dependendo o Horário sim

**Comment by luizatonial** [comment]
> Dependendo o Horário sim

é das 18 às 20h

**Comment by luizatonial** [comment]
o @rafaguilman ficará responsável pela live.

**Comment by pedroamaximowski** [comment]
live finalizada, ocorreu tudo certo na live.
https://www.youtube.com/watch?v=85cnqj88lI0

**Comment by luizatonial** [comment]
@pedroamaximowski se atente para os padrões de lives, principalmente em relação ao bate papo #343

**Comment by pedroamaximowski** [comment]
Desculpa, não vi que tinha mudado.
