### ISSUE TITLE
Criação do manual de apoio aos estudantes

### ISSUE THREAD

**Issue by isabelirk** [practice-uffs/programa#314]
Esta issue esta sendo criada, a partir de uma ideia da equipe de @practice-uffs/con-conteudo, na elaboração de uma manual para os estudantes que abrangeria três seções: táticas de estudo, como fazer tal coisa e facilitadores. Conforme reunião realizada no dia 17/11/2020, foi apresentado o esqueleto do projeto aos demais integrantes da equipe, e com algumas sugestões de melhorias, o mesmo foi aprovado. Logo abaixo, serão listados todos os tópicos a serem desenvolvidos para a construção do manual. E havendo necessidade, cada tópico terá uma issue especifica aberta para acompanhar o seu desenvolvimento. O esqueleto completo do projeto se encontra na pasta desta issue.

- [x] Criação de um planejamento de estudo.

- [x] Criação de um calendário com prioridades.

- [x] Criação de um quadro Kanban.

- [x] Utilização do método pomodoro.

- [x] Criação de fichamento.

- [x] Utilização de mnemônica.

- [x] Utilização de mapa mental.

- [x] Utilização do método robinson (EPL2R).

- [x] Utilização dos testes práticos.

- [x] Texto com dicas bônus sobre a seção 1.

- [x] Como fazer um plano de texto. (Alessandra)

- [x] Facilitador: responde aí.

- [x] Facilitador: mathway.

- [x] Facilitador: google drive (apenas a parte relacionada aos arquivos).

- [x] Facilitadores: issuu.

- [x] Facilitadores: Evernote.

- [x] Facilitadores: trello.

- [x] Facilitadores: photomath.

- [x] Facilitadores: skoob.

- [x] Facilitadores Bônus: flip.

- [x] Facilitadores Bônus: study bunny.

- [x] Facilitadores Bônus: agenda do universitario.

- [x] Facilitadores Bônus: my study life.

- [x] Facilitadores Bônus: passei direto.

- [x] Facilitadores Bônus: appDetox.

- [x] Facilitadores Bônus: i love pdf.

- [x] Facilitadores Bônus: academia.edu

- [x] Facilitadores Bônus: google acadêmico.

- [x] Criação de um infográfico sobre a classificação das táticas de estudo e quantidade de facilitadores apresentados. (Isabeli)

- [x] Criação de um infográfico relacionando os métodos apresentados com os seus aplicativos, será feito depois de todo o desenvolvimento do manual estiver pronto. (Brenda)

- [x] Elaboração da introdução do manual.

- [ ] Finalização do desenvolvimento (juntar todas as partes).

- [x] Elaboração da conclusão do manual.

- [x] Elaboração das referências bibliográficas do manual.

- [ ] Criação do sumário.

**Comment by isabelirk** [comment]
Link da pasta: https://drive.google.com/drive/folders/1G5rRkn-bn7KDlUFZbM_g8P1pALbc7ZPv

**Comment by alessandrapedrotti** [comment]
Moverei essa issue para sprint futura, já que é um projeto bastante extenso.

**Comment by brendaellen** [comment]
Boa tarde. 
Para fins de registro, o template e as ilustrações do manual estão em andamento. Portanto, assim que estiverem prontos, poderá ser aberta uma issue para finalização do manual.

**Comment by elisribas** [comment]
Olá, pessoal!
Fiz uma revisão geral no documento e há necessidade de ajustes. Todos os apontamentos estão em formato de sugestão no texto. Após, revisão e após produção gráfica, material está pronto para publicação.

**Comment by ghost** [comment]
o manual do estudante já foi finalizado e divulgado amplamente.
