### ISSUE TITLE
Desenvolvimento do tópico sobre o método pomodoro

### ISSUE THREAD

**Issue by isabelirk** [practice-uffs/programa#315]
Esta issue esta relacionada com a issue #314; é uma subtarefa referente ao método pomodoro; deve ser realizado o desenvolvimento da seção 1 e 2 do manual de apoio dos estudantes deste tópico, que abrange: o que é o método pomodoro, quais são seus objetivos, como podemos utilizá-lo, como podemos introduzir ele nos estudos, e se for necessário ou interessante, trazer algum exemplo.

**Comment by brendaellen** [comment]
Link da pasta: https://drive.google.com/drive/folders/104Wub6VALd6qjMx1WtvryJPSA78p1fEl

**Comment by brendaellen** [comment]
A primeira versão do texto encontra-se [nessa pasta](https://drive.google.com/drive/folders/104Wub6VALd6qjMx1WtvryJPSA78p1fEl).
@thaliafriedrich você pode fazer a revisão, por gentileza.

**Comment by thaliafriedrich** [comment]
Fiz a primeira revisão. O texto está ótimo e bem completo quanto às aplicações, benefícios e o método em si. Parabéns @brendaellen! 
Fiz correções textuais e deixei alguns comentários. O principal é para verificar o uso dos termos "método" e "técnica" ao longo do texto.

**Comment by brendaellen** [comment]
@thaliafriedrich, realizei as correções que foram sugeridas :) 
Sendo assim, acredito que a issue já pode ser fechada.
