### ISSUE TITLE
Desenvolvimento sobre o tópico do método robison (EPL2R)

### ISSUE THREAD

**Issue by isabelirk** [practice-uffs/programa#316]
Esta issue esta relacionada com a issue #314 ; é uma subtarefa referente ao método robison (EPL2R); deve ser realizado o desenvolvimento da seção 1 e 2 do manual de apoio dos estudantes deste tópico, que abrange: o que é o método, quais são seus objetivos, como podemos utilizá-lo, como podemos introduzir ele nos estudos, e se for necessário ou interessante, trazer algum exemplo.

**Comment by isabelirk** [comment]
link da pasta: https://drive.google.com/drive/folders/1bHsuRhG9jkmoB97tl7G3XWySVY-FKqcr

**Comment by robisonjose** [comment]
Gostei do nome

**Comment by thaliafriedrich** [comment]
Fiz a primeira revisão. Achei o texto excelente, muito bem escrito, parabéns @isabelirk!! O método foi explicado com clareza e com detalhes. 
Deixei dois comentários como sugestões, além de correções textuais e alteração de algumas palavras (pode verificar se acha pertinente ou não).

**Comment by isabelirk** [comment]
Obrigada pelo retorno @thaliafriedrich, os ajustes foram finalizados. Sendo assim, está issue será finalizada.
