### ISSUE TITLE
Avaliação de andamento e rendimento dos bolsistas

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#322]
Conforme o comunicado e explicado nas reuniões de equipe, **todos** os bolsistas do PRACTICE deverão produzir um relatório que é o instrumento de avaliação do percurso dos bolsistas no programa até o momento.

Os bolsistas poderão acessar na pasta [avaliação](https://drive.google.com/drive/folders/1m9diRWTOaFCIFvV1taszsC8q5Ho1UnYf) no drive do programa um documento em PDF com as orientações para a produção do relatório.

**O prazo limite para a entrega do relatório é dia 23/12/2020.**

O período que deve ser tratado no relatório é da data de ingresso no programa até a sprint 10.

Os bolsistas deverão criar, na pasta "avaliação", uma pasta com seu nome contendo uma versão PDF e uma versão editável do seu relatório.

Os comentários dessa issue serão utilizados para sanar possíveis dúvidas da produção do relatório e essa descrição será editada conforme novas informações sobre a correção dos textos  surgirem. 

@practice-uffs/todos 

PS: essa issue está na sprint 11 porque é a que mais se aproxima do prazo final de entrega dos relatórios.

**Comment by luizdameda** [comment]
Eu tenho uma dúvida! No tópico 2 (Síntese das atividades realizadas na equipe designada) eu devo listar TODOS os projetos feitos pela equipe de mídias ou apenas citar os tipos de projetos realizados (foram basicamente somente vídeos e lives)?

Sei que no tópico 3 devo listar quais projetos foram feitos exclusivamente por mim, mas não me ficou muito claro sobre o 2...

**Comment by luizdameda** [comment]
Eu tenho uma dúvida! No tópico 4 (Avaliação de progresso da equipe) eu devo listar TODOS os projetos feitos pela equipe de mídia ou apenas citar os tipos de projetos realizados (foram basicamente somente vídeos e lives) e como avalio eles?

Sei que no tópico 2 devo listar quais projetos foram feitos exclusivamente por mim, mas não me ficou muito claro sobre o 4...

**Comment by alessandrapedrotti** [comment]
> Eu tenho uma dúvida! No tópico 4 (Avaliação de progresso da equipe) eu devo listar TODOS os projetos feitos pela equipe de mídia ou apenas citar os tipos de projetos realizados (foram basicamente somente vídeos e lives) e como avalio eles?
> 
> Sei que no tópico 2 devo listar quais projetos foram feitos exclusivamente por mim, mas não me ficou muito claro sobre o 4...

Tu não precisa listar todos os projetos em nenhum dos tópicos, mas sim falar em linhas gerais de como foi a andamento e qual tua avaliação sobre eles. Cite alguns projetos apenas se quiser dar destaque a algum ou se for importante para a tua avaliação. Mas não é necessário citar projeto por projeto para fazer a avaliação.
