### ISSUE TITLE
Live Aula Aberta Pedagogia do Campus Erechim. - 07/12 - 19:15

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#324]
A live em questão é uma live aberta do CCR de Ed Infantil do curso de Pedagogia do Campus Erechim. 

Título da Transmissão: Os bebês brincam? Contribuições da abordagem Pikler
Dia 07.12, das 19h15 as 21h30.

Ministrante(s) | Prof. 			Rafael Kelleter (Mestre em educação PPGEDU/UFRGS, Educador 			físico, membro da Rede Pikler Brasil)
-- | --
Mediador | Prof. 			Flávia Burdzinski de Souza (Professora do curso de Pedagogia da 			UFFS/Erechim)

Link: -- (será no canal deles)

O roteiro está na pasta do drive

[Pasta Drive](https://drive.google.com/drive/folders/12jwuu9rHtKTLt3OXHaoVED6I3Nr1RsDw)

CC: @practice-uffs/con-midia

**Comment by luizatonial** [comment]
Live finalizada no canal da solicitante: https://www.youtube.com/watch?v=8LyeRxu8qBw&ab_channel=Fl%C3%A1viaBurdzinskideSouza
