### ISSUE TITLE
Edição de vídeos - Aulas de Espanhol (Issue Central)

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#325]
Foi nos solicitado pela professora Maria José Laiño, a montagem de 6 vídeos com narração produzida por ela com os slides enviados. 

São 6 vídeos, serão alocadas em 6 issues. Por ora todas as informações estão na pasta dessa issue.

Conforme forem ficando prontos podemos marcara abaixo:

- [x]  Vídeo 1 - #327
- [x]  Vídeo 2 - #328
- [x]  Vídeo 3 - #329
- [x]  Vídeo 4 - #330
- [x]  Vídeo 5 - #331 
- [x]  Vídeo 6 - #332 

[Pasta Drive](https://drive.google.com/drive/folders/13OksV1DBLTVUAeKr3cF20lN5QzvZNpSF)

CC: @practice-uffs/con-midia

**Comment by luizdameda** [comment]
@MaNegrao dada a tua sobrecarga, vou criar as issues individuais de cada vídeo, tudo bem?

**Comment by MaNegrao** [comment]
> @MaNegrao dada a tua sobrecarga, vou criar as issues individuais de cada vídeo, tudo bem?

Perfeito, pode criar, linka a issue central em todas elas, cria uma pasta pra cada no drive e pronto. Obrigadão :D

**Comment by luizdameda** [comment]
@MaNegrao todos os vídeos foram finalizados e podem ser encaminhados para a revisão da solicitante. :)

**Comment by MaNegrao** [comment]
Obrigado! vou enviar para prof 
:D

**Comment by MaNegrao** [comment]
Vídeos finalizados!
