### ISSUE TITLE
Remontagem de Vídeo - Andamento TCC de Computação 2 - CH

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#326]
O professor Fernando, docente da diciplina de TCC 1 no curso de ciência da computação da uffs nos solicitou a remontagem de um vídeo de apresentação de andamento do trabalho de tcc. 

As instruções são as seguintes:

> O vídeo foi gravado em resolução 360p:
> Eu gostaria que um novo vídeo fosse criado, com resolução 1080p, com base no áudio do vídeo original e uma nova gravação dos slides
> Também gostaria que o vídeo do narrador fosse integrado no vídeo novo (cortar ele do vídeo antigo e colocar no vídeo novo, talvez com um tamnho máximo de 150x150 pixels).

Eu sugiro no vídeo do narrador, colocarem uma mascara circular com uma borda branca. O vídeo original e os slides estão na pasta entrada da pasta do drive em forma de atalhos.

[Pasta do drive](https://drive.google.com/drive/folders/1NAvsibILELKVHctwKOKQtGWQGtV3ka5U)

CC: @practice-uffs/con-midia

**Comment by luizdameda** [comment]
@robisonjose tu consegue me dar um help aqui? já fiz tudo, só to com dificuldade de colocar a borda branca kkk, onde que encontro isso no Shotcut?

**Comment by luizdameda** [comment]
O vídeo finalizado encontra-se [nesta pasta](https://drive.google.com/drive/u/1/folders/1FQWUlpn2U-2R0Cjp6PIAStlGz84oTIcC). @MaNegrao encaminha para o solicitante, caso seja necessário alguma alteração, eu refaço!

**Comment by MaNegrao** [comment]
Opa, eu enviei e esqueci de avisar kkkk, mas segue o retorno do cliente:

> - Reduzir um pouco o tamanho do apresentador e mover ele um pouquinho para baixo (ele está perigosamente perto do logo do curso).
> - Usar uma suavização maior na borda ao redor do apresentador (está bem serrilhado agora, poderia ser mais "smooth")

**Comment by luizdameda** [comment]
O vídeo revisado está [nesta pasta](https://drive.google.com/drive/u/1/folders/1FQWUlpn2U-2R0Cjp6PIAStlGz84oTIcC)

A borda não ficou 100% como eu desejava que ficasse, mas foi o máximo que consegui suavizar, o Shotcut deixa um pouco a desejar nesse quesito :s, mas acredito que tenha ficado bom.

**Comment by robisonjose** [comment]
Bom dia @luizdameda. 

Para fazer a borda eu utilizei simplesmente um círculo com uma boa qualidade, e com a cor das letras dos slides. E ai coloquei a gravação do apresentador em cima com a máscara do recorte circular.  

![círculo](https://user-images.githubusercontent.com/71669689/100458171-162fd200-30a2-11eb-800f-ca73076d89b8.png)

**Comment by luizdameda** [comment]
> O vídeo revisado está [nesta pasta](https://drive.google.com/drive/u/1/folders/1FQWUlpn2U-2R0Cjp6PIAStlGz84oTIcC)
> 
> A borda não ficou 100% como eu desejava que ficasse, mas foi o máximo que consegui suavizar, o Shotcut deixa um pouco a desejar nesse quesito :s, mas acredito que tenha ficado bom.

@MaNegrao já encaminhou para o solicitante? Caso ele prefira, posso fazer com a borda que o Robison sugeriu, mas acredito que a versão que fiz esteja bem semelhante.

**Comment by MaNegrao** [comment]
> > O vídeo revisado está [nesta pasta](https://drive.google.com/drive/u/1/folders/1FQWUlpn2U-2R0Cjp6PIAStlGz84oTIcC)
> > A borda não ficou 100% como eu desejava que ficasse, mas foi o máximo que consegui suavizar, o Shotcut deixa um pouco a desejar nesse quesito :s, mas acredito que tenha ficado bom.
> 
> @MaNegrao já encaminhou para o solicitante? Caso ele prefira, posso fazer com a borda que o Robison sugeriu, mas acredito que a versão que fiz esteja bem semelhante.

Ainda não, achei que vocês ainda estivessem fazendo as alterações hehe. vou enviar

**Comment by MaNegrao** [comment]
Vídeo aprovado!
