### ISSUE TITLE
Documento de negação para solicitação por e-mail 

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#333]
Conforme debatido na reunião de líderes, será criado um texto que sucintamente explique para um provável solicitante porquê a demanda feita pode ser negada. Juntamente, será elaborado um texto padrão curto explicando o prazo de resposta do email do PRACTICE.

[Pasta do drive](https://drive.google.com/drive/folders/1nNT386wQPFV4oa8S3O7DHHCkiCSDoHvn)

**Comment by alessandrapedrotti** [comment]
> Conforme debatido na reunião de líderes, será criado um texto que sucintamente explique para um provável solicitante porquê a demanda feita pode ser negada. Juntamente, será elaborado um texto padrão curto explicando o prazo de resposta do email do PRACTICE.

[Pasta do drive](https://drive.google.com/drive/folders/1nNT386wQPFV4oa8S3O7DHHCkiCSDoHvn)

**Comment by alessandrapedrotti** [comment]
A primeira versão dos textos já está disponível. Solicito que a @practice-uffs/ger e @VIF-Franca leiam e façam sugestões de melhoras.

**Comment by VIF-Franca** [comment]
@alessandrapedrotti realizei uma leitura no texto de negação de demanda e deixei 03 sugestões, veja o que acha. Sobre os demais textos creio que está bacana.

**Comment by alessandrapedrotti** [comment]
> @alessandrapedrotti realizei uma leitura no texto de negação de demanda e deixei 03 sugestões, veja o que acha. Sobre os demais textos creio que está bacana.

corrigi os pontos apontados. Acredito que está bem completo agora. Fico no aguardo dos apontamentos da gerência.

**Comment by Dovyski** [comment]
Eu achei excelente, parabéns pelo texto!

**Comment by alessandrapedrotti** [comment]
Os textos foram movidos para a pasta [modelos e-mail](https://drive.google.com/drive/folders/1UhywLOcXAnOplX8CiOExw8Yz3igAatB2), para ficarem de mais fácil acesso a quem precisar.
