### ISSUE TITLE
Brainstorming de ideias de vídeos curtos para o instagram do PRACTICE

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#334]
Essa issue foi criada para reunir ideias de vídeos curtos para o instagram do PRACTICE. Qualquer membro pode comentar.

@practice-uffs/todos

**Comment by robisonjose** [comment]
Dicas de como gravar um áudio

**Comment by Dovyski** [comment]
- Informações sobre licenças de conteúdo (creative commons, etc);
- Estatísticas de trabalho do programa (lives atendidas, materiais criados, etc)

**Comment by robisonjose** [comment]
> * Informações sobre licenças de conteúdo (creative commons, etc);
> * Estatísticas de trabalho do programa (lives atendidas, materiais criados, etc)

Tem um vídeo maior sendo feito sobre creative commons, também daria para utilizar algum material dele de alguma forma para criar um vídeo curto.

**Comment by estelavilasboas** [comment]
- Informações sobre o círculo cromático
- Informações sobre proporção áurea

**Comment by GessicaZanon** [comment]
Talvez seria interessante um pequeno vídeo mostrando o que há de disponível no site e como fazer para solicitar algum serviço do PRACTICE.

**Comment by vini2reis** [comment]
Acho que aquelas dicas sobre iluminação e ângulo para transmissão seriam interessante também.

**Comment by estelavilasboas** [comment]
Tendo o gancho da formação de texto e escrita, fazer algo bem simples que fala de boas práticas para escrever, como ter um plano de texto.

**Comment by alessandrapedrotti** [comment]
> Tendo o gancho da formação de texto e escrita, fazer algo bem simples que fala de boas práticas para escrever, como ter um plano de texto.

Posso fazer esse roteiro.

**Comment by TaynaraCh** [comment]
O que vocês acham sobre criar esses videos com base nas cartilhas que já foram desenvolvidas, linkando tudo na legenda com um "pra saber mais acesse o link...", fica mais interativo, o material da cartilha é aproveitado pra outra plataforma e faz com que as pessoas acessem o site.

**Comment by Dovyski** [comment]
Eu acho fantástica essa ideia da @TaynaraCh ! A gente faz uma divulgação, aproveita o material existente e ainda atinge pessoas de outras formas/plataformas.

**Comment by Claudineia-VR** [comment]
Na minha opinião todos os materiais da parte de recursos do site, poderiam ser sintetizados e transformados em vídeos simples e curtos como por exemplo "Dicas para um melhor aproveitamento das aulas em formato remoto". Não sei se esses materiais seriam as próprias cartilhas a que a @TaynaraCh se referem, enfim, acho que seria bem interessante.

**Comment by morgana-mo** [comment]
Todas as ideias dessa issue foram adicionadas a planilha de criação #374
