### ISSUE TITLE
Post para o instagram - palavra PRACTICE

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#335]
É necessário elaborar um post explicando o significado da sigla PRACTICE e o jogo de palavras com a palavra inglesa _practice_.
Nesse post podemos explicar também a pronúncia da palavra.

[Pasta do drive](https://drive.google.com/drive/folders/10yrm3QoucBIwVHXJS_OdDmGXa8RwUiO_)

**Comment by anacarolinamorigi** [comment]
Boa noite!

Fiz [essa ideia de modelo](https://drive.google.com/drive/folders/1Ti1Z7hsAXjYWAIqMj28mru1ns1t-SnwG?usp=sharing) para a publicação e gostaria da opinião de vocês sobre.

A ideia original seria que fossem feito três publicações em sequência buscando deixar o feed organizado e com sequência, mas qualquer coisa ele pode ser feito somente em uma publicação.

**Comment by alessandrapedrotti** [comment]
Acredito que seja possível mudar a sequência proposta para apenas um post com duas imagens.

Na primeira, teríamos o texto: "Você sabe o que significa o nome PRACTICE?" seguido por "O nome do programa é um jogo com a palavra da língua inglesa 'practice', que significa prática. Sua definição se refere a repetição ou exercício de uma atividade, a fim de alcançar maestria e fluência. O que vai de encontro com a nossa filosofia, que é empoderar tecnologicamente as pessoas transformando as práticas diárias de todos na nossa universidade."

Na segunda imagem poderíamos ter a tradução fonética e uma curta explicação da pronúncia da palavra.

**Comment by anacarolinamorigi** [comment]
> Acredito que seja possível mudar a sequência proposta para apenas um post com duas imagens.
> 
> Na primeira, teríamos o texto: "Você sabe o que significa o nome PRACTICE?" seguido por "O nome do programa é um jogo com a palavra da língua inglesa 'practice', que significa prática. Sua definição se refere a repetição ou exercício de uma atividade, a fim de alcançar maestria e fluência. O que vai de encontro com a nossa filosofia, que é empoderar tecnologicamente as pessoas transformando as práticas diárias de todos na nossa universidade."
> 
> Na segunda imagem poderíamos ter a tradução fonética e uma curta explicação da pronúncia da palavra.

Alterações feitas, fico no aguardo do retorno!

**Comment by alessandrapedrotti** [comment]
Eu adorei!!! Ficou muito legal, meus parabéns Ana!!

Acredito que esse post já possa ser integrado no planejamento de postagens, peço apenas que o @Dovyski dê uma olhada e diga se era essa a ideia que ele também tinha em mente.

**Comment by Dovyski** [comment]
Sim, era bem isso, adorei o post também ❤️ Parabéns pelo trabalho!

**Comment by anacarolinamorigi** [comment]
Obrigada!! ❤️ 

O post já foi integrado ao calendário de postagens e será publicado logo mais!
