### ISSUE TITLE
Calendário de postagem de vídeos para 2021

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#336]
Esse projeto servirá para divulgar os vídeos que estão sendo feitos pela equipe mídia.

Os vídeos que estão em produção pela equipe mídia serão adicionados ao planejamento de divulgações elaborado pela equipe de comunicação. Essa issue servirá para tratar das necessidades desse projeto.

**Comment by anacarolinamorigi** [comment]
Boa noite! 

Uma dúvida que surgiu enquanto eu e a @morgana-mo debatíamos sobre a organização do calendário. @MaNegrao gostaríamos de saber se já existe um roteiro, mesmo que prévio, do pessoal mídia com os vídeos finalizados e o que ainda será produzido.

**Comment by MaNegrao** [comment]
Acho que não temos um cronograma de produções, ficamos um pouco a mercê das produções escritas do PRACTICE. Mas Acho que podemos planejar outros vídeos sim. Mas temos pelo menos 20 vídeos planejados ou em execução. 

@robisonjose tu acha que podemos organizar isso?

**Comment by robisonjose** [comment]
Podemos sim. Só temos que conversar para ver como podemos fazer.

**Comment by morgana-mo** [comment]
Como conversado na Issue #344  elaborei um [esboço do calendário para a postagem dos vídeos](https://drive.google.com/drive/folders/1QFrwDMONsVyUp6JL3prbX1XXVSbybqh2).
De janeiro a março coloquei as postagens quinzenalmente, de abril a julho coloquei como semanais tendo em vista que são série de vídeos.
 A escolha da segunda-feira como dia para as postagens foi levando em conta que é o dia que temos mais interações nas nossas redes sociais.
Ficamos no aguardo das opiniões e sugestões!

**Comment by robisonjose** [comment]
Tem um vídeo que já está pronto mas não foi colocado no calendário (ou eu não encontrei), que é o da issue #222.

**Comment by morgana-mo** [comment]
Acho que passou batido por mim esse, vou adicionar

**Comment by morgana-mo** [comment]
Se não houverem mais considerações acredito que podemos fechar a issue e mover esse rascunho para pasta da comunicação e conforme os vídeos forem ficando prontos dentro das possibilidades do @practice-uffs/con-midia , acredito que para ficar mais ordeiro  a equipe de comunicação deve ser  marcada na issue de cada vídeo quando este for  finalizado e vamos adicionando ao calendário oficial e realizando as postagens.

**Comment by MaNegrao** [comment]
Acho que podems fazer assim mesmo, Eu achei excelente dessa maneira. Caso tenha necessidade no futuro podemos reajustar o calendario conforme forem saindo mais vídeos.  Caso o @robisonjose não tenha mais nenhum apontamento podemos encerrar a tarefa @morgana-mo

**Comment by robisonjose** [comment]
A organização está boa, porém a ordem não, pois tem vídeos que já estão prontos que estão depois de vídeos que estão bem no começo. Mas não sei se a ordem é relevante aqui.

**Comment by MaNegrao** [comment]
> A organização está boa, porém a ordem não, pois tem vídeos que já estão prontos que estão depois de vídeos que estão bem no começo. Mas não sei se a ordem é relevante aqui.

Creio que com a conversa feita na issue de mapeamento de vídeos, vamos conseguir sanar esses probleminhas

**Comment by morgana-mo** [comment]
Olá refiz o [calendário](https://docs.google.com/spreadsheets/d/13FptzSBWbvN2RtXno2jPvrgruZ7ia-CS/edit#gid=1341612950) e gostaria da opinião de vocês quanto ao que podemos melhorar nele. Para essa nova organização dei a seguinte ordem de prioridade: Finalizado, últimos ajustes, mais da metade para vídeos individuais.
No que diz respeito as séries de vídeos coloquei na ordem da que estivesse com mais vídeos no mesmo estágio de produção e o estágio mais avançado, as postagens ficaram nessa ordem:
-Tutorial de edição de imagem (5 vídeos mais da metade e 1 vídeo em fase inicial);
-Tutorial ShotCut (3 vídeos em ajustes finais e 3 em fase inicial);
-Tutorial OBS Studio (todos em fase inicial)
Quanto aos vídeos de adaptação das cartilhas e tutoriais de apenas um episódio procurei intercalar com os demais e colocar entre o final de uma série e o início de outra.
Gostaria que os membros do @practice-uffs/con-midia  se manifestassem para deixarmos tudo dentro das possibilidades reais de trabalho da ilha.

**Comment by robisonjose** [comment]
Boa noite @morgana-mo. 

Eu achei o calendário bom. 

Só temos de esperar o pessoal que está trabalhando nos vídeos se manifestar para ver se é possível concretizar o que foi idealizado.

**Comment by luizatonial** [comment]
Em relação aos vídeos que estão sob minha responsabilidade, acredito que esteja bem tranquilo. 
Para os que serão postados em março só falta a narração e os que serão postados em junho já estão em produção, então também devem ficar prontos até a data.

_Parabéns pelo trabalho!_

**Comment by alessandrapedrotti** [comment]
> Olá refiz o [calendário](https://docs.google.com/spreadsheets/d/13FptzSBWbvN2RtXno2jPvrgruZ7ia-CS/edit#gid=1341612950) e gostaria da opinião de vocês quanto ao que podemos melhorar nele. Para essa nova organização dei a seguinte ordem de prioridade: Finalizado, últimos ajustes, mais da metade para vídeos individuais.
> No que diz respeito as séries de vídeos coloquei na ordem da que estivesse com mais vídeos no mesmo estágio de produção e o estágio mais avançado, as postagens ficaram nessa ordem:
> -Tutorial de edição de imagem (5 vídeos mais da metade e 1 vídeo em fase inicial);
> -Tutorial ShotCut (3 vídeos em ajustes finais e 3 em fase inicial);
> -Tutorial OBS Studio (todos em fase inicial)
> Quanto aos vídeos de adaptação das cartilhas e tutoriais de apenas um episódio procurei intercalar com os demais e colocar entre o final de uma série e o início de outra.
> Gostaria que os membros do @practice-uffs/con-midia se manifestassem para deixarmos tudo dentro das possibilidades reais de trabalho da ilha.

A nova organização proposta está excelente! Bastante espaçada mas ao mesmo tempo mantém uma frequência interessante.

**Comment by vini2reis** [comment]
Creio que os vídeos do Tutorial Shotcut ficarão prontos até a data de lançamento tranquilamente.
(O calendário está excelente e muito bonito. Parabéns!!)

**Comment by morgana-mo** [comment]
Se não houverem mais considerações acredito que podemos fechar a issue e mover esse rascunho para pasta da comunicação e conforme os vídeos forem ficando prontos dentro das possibilidades do @practice-uffs/con-midia , acredito que para ficar mais ordeiro a equipe de comunicação deve ser marcada na issue de cada vídeo quando este for finalizado e vamos adicionando ao calendário oficial e realizando as postagens.

**Comment by morgana-mo** [comment]
Closed #336
