### ISSUE TITLE
Serie de Tutorias Shotcut - Episódio 5

### ISSUE THREAD

**Issue by vini2reis** [practice-uffs/programa#337]
Essa issue está relacionada ao episódio `5` da série de vídeo do Shotcut relacionadas na issue #130.

O roteiro deve estar na pasta do drive e os materiais usados devem ser anexados também, o vídeo base está nesse [link](https://www.youtube.com/watch?v=4bcw9_zXEuA&feature=youtu.be).

[Pasta Drive](https://drive.google.com/drive/folders/1o0zGDExyECWDXS7J1DKBNzDpdy4B2Lrh)

**Comment by vini2reis** [comment]
@practice-uffs/con-conteudo Roteiro cinco está na pasta para revisão.

**Comment by thaliafriedrich** [comment]
Fiz a revisão textual. 
Está bem escrito! Deixei duas sugestões no arquivo só para complementar.

**Comment by vini2reis** [comment]
Vídeo concluído na pasta

**Comment by robisonjose** [comment]
EPISÓDIO 5 FINALIZADO!
