### ISSUE TITLE
Serie de Tutoriais Shotcut - Episódio 6

### ISSUE THREAD

**Issue by vini2reis** [practice-uffs/programa#338]
Essa issue está relacionada ao episódio `6` da série de vídeo do Shotcut relacionadas na issue #130.

O roteiro deve estar na pasta do drive e os materiais usados devem ser anexados também, o vídeo base está nesse [link](https://www.youtube.com/watch?v=4bcw9_zXEuA&feature=youtu.be).

[Pasta Drive](https://drive.google.com/drive/folders/1uwShZwDFo-uAZ1CZapmhoKRI0ZQ4QWDA)

**Comment by vini2reis** [comment]
@practice-uffs/con-conteudo  O último roteiro está na pasta para revisão.

**Comment by thaliafriedrich** [comment]
Revisei o roteiro. Fiz pequenas modificações e algumas correções textuais.
Assisti também a vinheta de abertura do tutorial que está na pasta, está faltando o acento em 'Episódio".

**Comment by vini2reis** [comment]
> estão

Farei a correção da vinheta
Obrigado pelas observações 😁

**Comment by vini2reis** [comment]
Vídeo editado esta na pasta do drive.

- @robisonjose

**Comment by robisonjose** [comment]
Bom dia @vini2reis.

O vídeo está bom, tenho apenas três observações:

1. O vídeo está com bordas pretas, seria interessante que ele ficasse igual os outros dois vídeos já produzidos, ocupando a tela toda;
2. As redes sociais poderiam ficar um pouco maiores e centralizadas. Para não ficar esquisito elas centralizadas em cima do vídeo, seria interessante colocar um desfoque no vídeo de tutorial, e as redes sociais em cima, centralizadas e maiores (eu pensei em algo [desse tipo](https://drive.google.com/drive/folders/1HNtFzwznbddYWogHMaekpAAt_N9Y78AE)). Pode ser feito de outra maneira também, colocando elas na parte inferior, porém elas devem estar maiores;
3. Seria interessante colocar uma música baixa de fundo, ela mascara bem alguns detalhes e barulhos do áudio do narrador. 

Talvez seria interessante dar uma editada apenas no áudio, retirar os ruídos caso seja possível, normalizar tudo, cortar momentos de "silêncio" (talvez já tenha sido feito isso e já estamos com o melhor áudio possível, ai é só desconsiderar o que eu acabei de escrever).

**Comment by vini2reis** [comment]
> Bom dia @vini2reis.
> 
> O vídeo está bom, tenho apenas três observações:
> 
> 1. O vídeo está com bordas pretas, seria interessante que ele ficasse igual os outros dois vídeos já produzidos, ocupando a tela toda;
> 2. As redes sociais poderiam ficar um pouco maiores e centralizadas. Para não ficar esquisito elas centralizadas em cima do vídeo, seria interessante colocar um desfoque no vídeo de tutorial, e as redes sociais em cima, centralizadas e maiores (eu pensei em algo [desse tipo](https://drive.google.com/drive/folders/1HNtFzwznbddYWogHMaekpAAt_N9Y78AE)). Pode ser feito de outra maneira também, colocando elas na parte inferior, porém elas devem estar maiores;
> 3. Seria interessante colocar uma música baixa de fundo, ela mascara bem alguns detalhes e barulhos do áudio do narrador.
> 
> Talvez seria interessante dar uma editada apenas no áudio, retirar os ruídos caso seja possível, normalizar tudo, cortar momentos de "silêncio" (talvez já tenha sido feito isso e já estamos com o melhor áudio possível, ai é só desconsiderar o que eu acabei de escrever).

Nova versão ja esta na pasta

**Comment by robisonjose** [comment]
@Boa noite @vini2reis 

O vídeo está show, sugiro que sigam esse padrão em todos os vídeos da série. 

Uma coisa que pensei: será que não ficaria melhor colocar colocar essa música do fim até o inicio corrido? Pq vi que tu deu um corte depois da vinheta de abertura. 

Se não me engano, a vinheta está com essa música de fundo já, então o que eu iria sugerir é tirar o som da vinheta, colocar a música de fundo corrida, iniciando normalmente, como inicia na vinheta de abertura, e dai apenas ir diminuindo ela quando o tutorial começa (diminuir até um volume constante para que ele fique até o fim do vídeo). 

É uma ideia que acredito que ficaria mais interessante. De qualquer forma, o vídeo está muito bom, parabéns.

**Comment by vini2reis** [comment]
> Boa noite @vini2reis!
> 
> O vídeo está show, sugiro que sigam esse padrão em todos os vídeos da série.
> 
> Uma coisa que pensei: será que não ficaria melhor colocar colocar essa música do fim até o inicio corrido? Pq vi que tu deu um corte depois da vinheta de abertura.
> 
> Se não me engano, a vinheta está com essa música de fundo já, então o que eu iria sugerir é tirar o som da vinheta, colocar a música de fundo corrida, iniciando normalmente, como inicia na vinheta de abertura, e dai apenas ir diminuindo ela quando o tutorial começa (diminuir até um volume constante para que ele fique até o fim do vídeo).
> 
> É uma ideia que acredito que ficaria mais interessante. De qualquer forma, o vídeo está muito bom, parabéns.

Concordo contigo.
Atualizei o vídeo com essa mudança na música.

**Comment by robisonjose** [comment]
Acredito que a única coisa que possa ser mudada agora é o volume da música, que deve ser um pouco mais baixo.

**Comment by robisonjose** [comment]
EPISÓDIO 6 FINALIZADO, E PORTANTO, SÉRIE FINALIZADA!

**Comment by morgana-mo** [comment]
Esse último vídeo da série vai ao ar amanhã!
Parabéns pelo excelente trabalho :D
