### ISSUE TITLE
Vídeo - Novo regulamento de ACC - Curso de computação CH

### ISSUE THREAD

**Issue by robisonjose** [practice-uffs/programa#339]
Criação do vídeo relacionado com a issue #303. 

**O vídeo precisa ter as seguintes elementos:**

1. Iniciar com a vinheta oficial do curso;
2. Ser narrado (o PRACTICE deve prover a narração);
3. Ter animações (de texto, de elementos de arte, etc) que mostrem os principais números e informações;
4. A narração pode ser masculina ou feminina;
5. A duração pode ser entre 5 a 7 min (eventualmente pode ser menos de 5 minutos se todas as informações forem apresentadas)
6. O tom pode ser neutro-formal

**Os passos serão:**

- [x] Gravação do [roteiro](https://docs.google.com/document/d/1yZkSPRe81PIIjkPU4dViKKKO30TQXc4OUeZiy-wmCNI/edit) (voz);

- [x] Edição da gravação de voz;

- [x] Edição do vídeo;

- [x] Inserção da legenda.

Acredito que o vídeo deve ter a seguinte estrutura: vinheta curso - conteúdo - créditos - vinheta curso - vinheta PRACTICE

[Pasta Drive](https://drive.google.com/drive/u/0/folders/1dOSc6egV4xu__nvBNGvlC6A5_8gSbTwj).

**Comment by robisonjose** [comment]
@MaNegrao fiquei em dúvida em relação a sprint que devemos entregar o produto. Coloquei Sprint 10 que era a que estava na issue do roteiro. Lamentavelmente eu ainda estou meio perdido em relação aos prazos. Mesmo com aquele fluxo que você passou. Será que não seria interessante criarmos algo parecido [com isso](https://docs.google.com/document/d/1HgJIxk3M9TfI7iLMW1FHsXTgC6Zb1ApIay_dqlVTyA0/edit). Talvez já tenha algo e eu estou louqueando.

**Comment by MaNegrao** [comment]
Nós temos um documento parecido com esse. Na verdade é igual com mais coisa, porém tá desatualizado porque foi feito a um belo tempo atrás, podemos pegar ele e adaptar pro novo funcionamento. 

Na minha visão é plausível terminarmos o vídeo até o final dessa sprint, mas caso tu prefira definir um prazo específico, fica ao teu critério.

**Comment by robisonjose** [comment]
Seria muito bom a gente ter um documento desses com prazos. Tu pode me passar para eu dar uma olhada? Ai já posso ir dando umas ideias para a nova versão. Talvez podemos fazer em conjunto com todos da ilha de vídeos.

**Comment by MaNegrao** [comment]
> Seria muito bom a gente ter um documento desses com prazos. Tu pode me passar para eu dar uma olhada? Ai já posso ir dando umas ideias para a nova versão. Talvez podemos fazer em conjunto com todos da ilha de vídeos.

Anexei no comentário anterior as informações hehe

**Comment by robisonjose** [comment]
@MaNegrao alterei o vídeo para a Sprint 11 pois provavelmente não vou conseguir terminar dentro da Sprint 10. 

Talvez seja interessante falar com o solicitante se eles precisam disso com urgência que ai eu coloco essa issue como prioridade e tento com todas as minhas forças ainda restantes terminar até Terça.

**Comment by MaNegrao** [comment]
Creio que por conta de ser um vídeo bem elaborado não tenha problema, mas posso entrar em contato de qualquer forma

**Comment by robisonjose** [comment]
Seria bom, obrigado!

**Comment by robisonjose** [comment]
@MaNegrao você poderia disponibilizar na pasta de entrada a logo do curso? Não estou conseguindo entrar no site do curso e talvez não tenha a logo disponível com boa qualidade lá, e quero trabalhar nesse vídeo no final de semana, então é melhor pedir agora.

**Comment by MaNegrao** [comment]
> @MaNegrao você poderia disponibilizar na pasta de entrada a logo do curso? Não estou conseguindo entrar no site do curso e talvez não tenha a logo disponível com boa qualidade lá, e quero trabalhar nesse vídeo no final de semana, então é melhor pedir agora.

o site do curso provavelmente tá fora do ar, eu também não consegui entrar. 
Tu pode encontrar as logos do curso no github do mesmo: https://github.com/ccuffs/identidade-visual/tree/master/logos.

Quanto ao e-mail, ainda to esperando a resposta do solicitante sobre o prazo.

**Comment by MaNegrao** [comment]
@robisonjose O solicitante me respondeu sinalizando que não problema adiar o vídeo

**Comment by robisonjose** [comment]
Postei uma [prévia](https://drive.google.com/drive/u/2/folders/1udkZH5HmlrNx72_rgt9TlH8OTBgIKebB) do modelo que vou seguir com o vídeo. 

@MaNegrao, envie ao solicitante para ver o que ele acha e se posso seguir fazendo o vídeo dessa forma. 

@GessicaZanon e @thaliafriedrich me falem o que acharam dessa prévia. 

Assim que obtiver a resposta do solicitante continuarei com o vídeo.

**Comment by thaliafriedrich** [comment]
Eu gostei bastante dessa prévia. As cores se adaptam bem ao estilo do curso e as animações facilitam o entendimento. Só sugiro dar uma maior entonação nas frases de interrogação (nas palavras finais), principalmente nas atividades de extensão.

**Comment by GessicaZanon** [comment]
Concordo com a Thalía sobre as cores utilizadas, combinou super bem; Gostei da música de fundo, ficou bem suave e não atrapalha tua fala; As animações ficaram bem legais, ao meu ver ficou super fácil de entender para quem estiver assistindo; Tua fala está bem limpa e clara e a velocidade está boa; Único ponto que eu coloco é o mesmo que a Thalía destacou sobre a entonação nas frases que anunciam a categoria, não que isso atrapalhe o vídeo. Parabéns, está muito bom!

**Comment by robisonjose** [comment]
Bom dia @thaliafriedrich e @GessicaZanon. 

Obrigado pelo Feedback, vou tentar regravar essas partes, porém não sei se vou conseguir fazer com que a alteração fique boa, pois o timbre da voz muda muito de dia para dia, talvez fique muito discrepante a voz do vídeo, que foi gravada toda na mesma hora, e a voz que eu coloque agora. 

Caso eu não consiga fazer tal alteração, continuarei editando e vocês opinam na versão final, e ai se acharem necessário, eu regravo tudo.

**Comment by robisonjose** [comment]
Boa tarde!

A versão "final" do vídeo está [aqui](https://drive.google.com/drive/u/2/folders/1udkZH5HmlrNx72_rgt9TlH8OTBgIKebB) com o nome de "video_novo_regulamento_v4.0_legendado".

@thaliafriedrich e @GessicaZanon, peço que revisem o vídeo com atenção especial às legendas; 

@MaNegrao peço que revise o vídeo como um todo e mande ao solicitante.

**Comment by Dovyski** [comment]
Eu preciso fazer um comentário aqui: estou *ESPUMANDO* de felicidade ao ver esse vídeo. Uma porque ele foi solicitado pelo curso de Ciência da Computação e ficou maravilhoso para os alunos. Outra porque eu amei o trabalho de todos nesse vídeo: roteiro, edição, narração, legenda, revisão, conteúdo, tudo!

Equipe PRACTICE patrolando tudo pelo caminho e mostrando como se faz! ❤️🥳🚀💌 🥂 👏👏 👏 👏 👏 👏

**Comment by MaNegrao** [comment]
Bom, acho que com o comentário do Fernando não sei nem o que dizer haha, só verificar se há algum ponto para corrigir ou não

**Comment by thaliafriedrich** [comment]
Eu também adorei o vídeo! A narração ficou ótima e as ilustrações e animações deixaram o vídeo dinâmico e atrativo, um ótimo trabalho!

As correções textuais são as seguintes:
Na legenda:
2:18 - escrever "20 horas" (por extenso), pois ao longo do vídeo a palavra "horas" foi utilizada sempre por extenso;
3:08 - inserir uma vígula antes da palavra "considerando";
3:22 - escrever "160 horas" (por extenso);

No vídeo:
4:42 - corrigir a palavra "mini-cursos" (o certo é minicursos);
7:00 - inserir uma vírgula ("Para mais informações, acesse:");
7:11 - corrigir o meu sobrenome nos créditos, o certo é Friedrich :grin:.

**Comment by robisonjose** [comment]
Boa noite @thaliafriedrich. 

Fiz as alterações solicitadas. Assim que a @GessicaZanon revisar também, posto a última versão. 

Peço desculpas por ter errado teu sobrenome :c

**Comment by robisonjose** [comment]
Boa tarde @thaliafriedrich e @GessicaZanon.

Postei a versão atualizada do vídeo na [pasta de saída](https://drive.google.com/drive/u/2/folders/1udkZH5HmlrNx72_rgt9TlH8OTBgIKebB).

Caso não tenham mais alterações, vou fechar a issue. 

@MaNegrao envie ao solicitante (só por mera formalidade).

**Comment by MaNegrao** [comment]
@robisonjose, Enviado Sir.

**Comment by GessicaZanon** [comment]
> Boa tarde @thaliafriedrich e @GessicaZanon.
> 
> Postei a versão atualizada do vídeo na [pasta de saída](https://drive.google.com/drive/u/2/folders/1udkZH5HmlrNx72_rgt9TlH8OTBgIKebB).
> 
> Caso não tenham mais alterações, vou fechar a issue.
> 
> @MaNegrao envie ao solicitante (só por mera formalidade).

Ao meu ponto de vista está tudo ok! Acredito que possa fechar essa issue! Aliás, ficou incrível!! Parabéns a todos os envolvidos :)

**Comment by MaNegrao** [comment]
Demanda foi aceita pelos solicitantes e eles transmitiram a mensagem de que estão extremamente felizes e agradeceram o trabalho excelente realizado pela equipe. Parabéns a todos envolvidos
