### ISSUE TITLE
Melhorias no template de cartilha complexa e moderada

### ISSUE THREAD

**Issue by estelavilasboas** [practice-uffs/programa#340]
Com a realização das melhorias gráficas nos templates de cartilhas simples na issue #211, essas melhorias devem ser transpostas para o [template de cartilha complexa e moderada](https://docs.google.com/presentation/d/1o1xsna5nHDkIa7kTnVi-zcWQfilWNZXV/edit#slide=id.g8d2063f94b_0_2).  Apesar da grande semelhança entre estes templates, as adaptações devem ser realizadas para facilitar o processo de escrita da equipe de redação e a revisão gráfica.
[Pasta saída da issue #211](https://drive.google.com/drive/u/0/folders/1KTzmSpCcDy0NAyRk567MqmcGc3lFXdVL)
[Pasta dessa issue](https://drive.google.com/drive/u/0/folders/1KgWgNObnT1AjvOyAK964XqKsrbiISVsr)

**Comment by TaynaraCh** [comment]
Alterações concluídas, [arquivo novo](https://docs.google.com/presentation/d/1jqwkIYz2eQ7ayDxo5JbW8fgWQDYl5BXkTqWdxpACxt4/edit#slide=id.ga5a98c05a3_0_123) na pasta

**Comment by estelavilasboas** [comment]
Não era necessário a criação de um novo template. A ideia era apenas adaptar o que foi feito na #211 para uma cartilha complexa. Uma cartilha complexa nada mais é do que uma cartilha simples mais longa, por isso ela possui sumário. 
Para ambos os templates criados na #211, deveriam ser criados sumários e o números de páginas adicionados no mestre. Essa seria a única adaptação. A intenção é que o leitor não perceba uma grande diferença entre os templates simples e complexa. Afinal, essa é uma divisão interna.

**Comment by TaynaraCh** [comment]
Alterações concluídas, acredito que agora está tudo certinho kkkk [cartilha simples](https://docs.google.com/presentation/d/1KzLpep1dmgaG_567ZxNg87tOHY3W_rk-Rrc4MOCt28M/edit#slide=id.ga85f9a18f3_0_11) e [cartilha complexa](https://docs.google.com/presentation/d/10DVl129E4djZ_Fk_sH7kFfe8pkB85q8KVZ4joUmNJAE/edit#slide=id.gb13dac385b_0_26)

**Comment by estelavilasboas** [comment]
As orientações descritas nas cartilhas serão revisadas.
