### ISSUE TITLE
Vídeo - Tutorial de edição de podcast

### ISSUE THREAD

**Issue by robisonjose** [practice-uffs/programa#341]
Continuação da issue #213 

Passos a serem seguidos:

- [x] Gravação do [roteiro](https://docs.google.com/document/d/1IcdliSN0sqKSSLSPRtKj5tG8tOV975KG0V0HSRd3TSw/edit);
- [x] Gravação da tela, seguindo o roteiro; 
- [x] Edição do áudio;
- [x] Edição do vídeo.

O estilo do vídeo é tutorial. 

[Pasta Drive](https://drive.google.com/drive/u/0/folders/1mhr3VLajJecnj2QkE5i3xz7XLYM0D2AU)

**Comment by robisonjose** [comment]
Boa tarde @alessandrapedrotti 

Estou te marcando aqui como havia me pedido.

**Comment by MaNegrao** [comment]
@practice-uffs/con-midia

**Comment by robisonjose** [comment]
Apesar da crise criativa, estou trabalhando no vídeo. Uma nova versão (inicial) está na pasta de entrada.

**Comment by alessandrapedrotti** [comment]
Estou vendo o vídeo e, primeiramente, parabéns pra ti @robisonjose, porque sua dicção é ótima!
Em segundo lugar, sugiro que, se possível, a barra de tarefas seja cortada da parte inferior da tela do vídeo, pois acho que não é muito interessante que ela apareça ali.

**Comment by robisonjose** [comment]
Ah sim, eu esqueci de retirar. Obrigado!

**Comment by Dovyski** [comment]
Estou maravilhado com esse tutorial, parabéns, @robisonjose ! 🥳 Não só a narração é maravilhosa, mas a didática e invejável.

**Comment by robisonjose** [comment]
Uma nova versão (ainda com muita coisa faltando) está na pasta de entrada. Aguardo FeedBack. 

Eu ainda estou tendo bastante dificuldade com esse vídeo, porém está andando...

**Comment by robisonjose** [comment]
Bom dia pessoal.

Postei uma versão quase finalizada na pasta de entrada (está com o nome de versao_quasepronta).

Falta um pedaço em que quero gravar mostrando onde fica o microfone, colocando uma meia no celular, algo do tipo.

**Comment by MilenaPaz2020** [comment]
O vídeo está muito bom, @robisonjose! Acho que vai ficar um tutorial muito completo e didático. Parabéns pelo vídeo e pelo trava-línguas, digo dicção! kk

**Comment by amandasegattob** [comment]
O vídeo está ficando maravilhoso! Parabéns pelo trabalho! 

Teu áudio fica impecável, com o que tu grava ele? Quero dicas hehe

**Comment by robisonjose** [comment]
> O vídeo está ficando maravilhoso! Parabéns pelo trabalho!
> 
> Teu áudio fica impecável, com o que tu grava ele? Quero dicas hehe

Eu gravo com um microfone (BM800) e depois edito no audacity. Porém com o celular ele fica tão bom quanto, o segredo está no audacity: tirar o ruído, cortar os errinhos, tirar as respirações e sons estranhos. E claro, gravar muitas vezes e escolher a melhor kkkkk

**Comment by robisonjose** [comment]
@practice-uffs/con-midia 

Eu sugiro que, apesar de não estar pronto, utilizem este tutorial sempre que forem fazer um vídeo em que a voz da narração não esteja tão boa ou seja possível melhorar. A redução de ruído, normalização e cortes (de erros, respirações, barulhos esquisitos) geralmente já darão ao trabalho de vocês uma cara muito mais profissional. 

Existe uma extensão que, quando adicionada, permite jogar o vídeo em mp4 no Audacity para que você possa editar ele. A instalação é simples, é só tentar colocar o vídeo no programa e ler o erro que aparece (caso já não tenha sido instalado a extensão automaticamente). No erro já será informado o que deve ser instalado. 

Geralmente em produções audiovisuais a qualidade de áudio vale muito mais que a qualidade de vídeo. Lembrem disso.

**Comment by luizatonial** [comment]
> @practice-uffs/con-midia
> 
> Eu sugiro que, apesar de não estar pronto, utilizem este tutorial sempre que forem fazer um vídeo em que a voz da narração não esteja tão boa ou seja possível melhorar. A redução de ruído, normalização e cortes (de erros, respirações, barulhos esquisitos) geralmente já darão ao trabalho de vocês uma cara muito mais profissional.
> 
> Existe uma extensão que, quando adicionada, permite jogar o vídeo em mp4 no Audacity para que você possa editar ele. A instalação é simples, é só tentar colocar o vídeo no programa e ler o erro que aparece (caso já não tenha sido instalado a extensão automaticamente). No erro já será informado o que deve ser instalado.
> 
> Geralmente em produções audiovisuais a qualidade de áudio vale muito mais que a qualidade de vídeo. Lembrem disso.

acredito que a @amandasegattob pode inserir esta informação no documento de padrões para os vídeos que ela está desenvolvendo.

**Comment by robisonjose** [comment]
Pessoal, estou com um probleminha e preciso da ajuda de vocês. 

Falta apenas uma parte do vídeo onde é demonstrado como gravar o áudio com o celular. Porém, os celulares disponíveis aqui em casa estão com a tela quebrada. Se alguém conseguir gravar a demonstração seria muito bom, pq eu não tenho outra ideia pra fazer naquela parte. 

É uma gravação simples:

- Mostrar onde fica o microfone do celular;
- Entrar no gravador de áudio do celular e gravar algo (só para aparecer as ondas do áudio, o som em si vai ser cortado);
- Mostrar a distância que deve falar do celular;
- Colocar o celular parado em cima de alguma coisa na altura da boca;
- Colocar uma meia/pano/espuma no microfone.

Se alguém conseguisse gravar em 1080p seria perfeito ;D

@practice-uffs/con-midia

**Comment by luizatonial** [comment]
infelizmente não tenho como gravar...

**Comment by robisonjose** [comment]
O vídeo está sendo renderizado. Logo posto a versão _potencialmente_ final.

**Comment by robisonjose** [comment]
Boa tarde pessoal que está acompanhando essa issue.
@practice-uffs/con-midia 

Peço que alguém revise o vídeo finalizado que está na pasta de saída.

Já percebi que em 00:25 falta uma transição que esqueci de botar. Vou fazer isso depois da revisão de vocês.

**Comment by robisonjose** [comment]
Boa noite @luizatonial. 

Eu não entendi teu apontamento. É pra seguir o que foi feito em "ferramentas básicas" ou para colocar as palavras em duas linhas e espaçar na tela inteira? Se for o segundo caso, tem momentos que as palavras são pequenas, e ai ficaria uma distância muito grande entre cada letra. Se for só pra centralizar mais elas, posso tentar, mas acho que já estão centralizadas. 

Se tu puder tentar explicar de novo tua sugestão eu agradeço :D

**Comment by luizatonial** [comment]
Acho que me expressei mal, eu quis dizer que parece que em 'ferramentas básicas', as letras estão muito espaçadas sabe. E ficam muito próximas às bordas do vídeo. Isso acabou dificultando um pouco minha leitura nesse momento, mas é só uma sugestão mesmo, está legível e o vídeo está ótimo!

**Comment by robisonjose** [comment]
Ah sim, agora entendi. Vou rever isso. E obrigado!

**Comment by robisonjose** [comment]
Versão revisada postada na pasta de saída.

**Comment by robisonjose** [comment]
Boa tarde @luizatonial 

Quando puder revisa novamente o vídeo para eu poder encerrar a issue.

**Comment by luizatonial** [comment]
> Boa tarde @luizatonial
> 
> Quando puder revisa novamente o vídeo para eu poder encerrar a issue.

Não encontrei mais nada que pudesse apontar... O vídeo ficou muito bom, parabéns @robisonjose!

**Comment by morgana-mo** [comment]
Eu geralmente assisto os vídeos várias vezes, mas não tenho o hábito de comentar nas issues, esse assim como os demais que foram produzidos por vocês do mídia estão muito bons!
Parabéns pelo empenho e qualidade dos materiais desenvolvidos pessoal!🚀

**Comment by robisonjose** [comment]
Viva!! Finalmente a issue pode ser encerrada!

**Comment by morgana-mo** [comment]
Esse vídeo irá estrear na quarta-feira no nosso canal de conteúdos do YouTube
