### ISSUE TITLE
Definição de padrões para os vídeos produzidos pelo PRACTICE

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#342]
Com o aumento da produção de vídeos no PRACTICE e a equipe maior, surgiu a necessidade de padronizar alguns aspectos dos vídeos produzidos pelo PRACTICE. Podemos fazer um trabalho conjunto entre o @practice-uffs/con-midia  e o @practice-uffs/con-design, para criação de alguns padrões. Creio que inicialmente devemos discutir detalhadamente e montar um documento com tudo que deve ser feito. 

Ao final creio que podemos criar uma especie de material como guia para garantir que os pontos estão definidos em algum lugar

@robisonjose tu pode assumir essa organização, e o pessoal da ilha de vídeos deve contribuir e esmuiçar tudo que conversamos na reunião.  

Os pontos que comentamos e que tem que ser trabalhados estão abaixo:

- Pagina de créditos.
- Planos de fundo
- Numeração em transições
- Transições
- Padrões do PRACTICE ([pasta de identidade visual](https://drive.google.com/drive/folders/1ymOvitNBOkBeU2RStVchrD6Rg8Ar4FB-))
- Montagem de acervo de vídeos do PRACTICE para serem utilizados (assim que bem especificado, isso vira uma issue separada com a ajuda do @practice-uffs/dev para disponibilizar isso)

Acho que ainda podemos colocar mais pontos. Por favor, comentem tudo que vocês julguem necessario.

[Pasta Drive](https://drive.google.com/drive/folders/1_rEI7bLFgndwcHwkTKASVbMcdNfWatRW)

**Comment by vini2reis** [comment]
O @rafaguilman e eu estamos usando uma pagina de creditos no tutorial do shotcut. Acho que da pra ir usando essa ate definirmos um novo padrao.

**Comment by robisonjose** [comment]
Participem dessa issue @luizdameda e @amandasegattob dando dicas e falando o que vocês acham que pode ser padronizado. 

Ao meu ver, o principal seria:

1. Estilos (dois ou mais) de números (em roboto, mas mais "estilizado") para fazer transições e tópicos. Dentro desses dois estilos fazer com umas quatro cores diferentes (todos da paleta de cores). Os números devem ser do 0 ao 9;
2. Utilizar sempre a fonte Roboto (em qualquer das suas variáveis) quando for escrever algo;
3. Criar um modelo de créditos, mas não um modelo fixo, e sim uma estrutura/esqueleto de como os créditos devem ser criados. Deixando livre para o editor se ele quer colocar os créditos em movimento ou fixo, com cor A ou B. O padrão será apenas no tamanho das fontes, no nome de cada categoria, e de como elas devem aparecer (uma embaixo da outra, colunas, espalhadas na tela, etc). 

O que eu consigo lembrar é isso.

*Obs: A padronização tem por objetivo deixar o negócio mais linear. Creio que se padronizar demais tira a liberdade do editor de criar coisas interessantes. Então deve existir a padronização, mas não uma receita.

**Comment by robisonjose** [comment]
Pessoal do @practice-uffs/con-design. Eu estava dando uma olhada na [paleta de cores](https://drive.google.com/drive/folders/1ymOvitNBOkBeU2RStVchrD6Rg8Ar4FB-) e a primeira cor, com código #264653 não está batendo com o que meu editor de imagens encontra, que é a cor de código #124255. E também não consegui encontrar na paleta de cores, as cores utilizadas para a criação da [vinheta](https://drive.google.com/drive/folders/1FFTk2H4YLBYcyNhBaZ1NikGyIRYdy_RO) do PRACTICE. 

Vocês podem dar uma olhada nisso?

**Comment by luizdameda** [comment]
> Participem dessa issue @luizdameda e @amandasegattob dando dicas e falando o que vocês acham que pode ser padronizado. 
> 
> 
> 
> Ao meu ver, o principal seria:
> 
> 
> 
> 1. Estilos (dois ou mais) de números (em roboto, mas mais "estilizado") para fazer transições e tópicos. Dentro desses dois estilos fazer com umas quatro cores diferentes (todos da paleta de cores). Os números devem ser do 0 ao 9;
> 
> 2. Utilizar sempre a fonte Roboto (em qualquer das suas variáveis) quando for escrever algo;
> 
> 3. Criar um modelo de créditos, mas não um modelo fixo, e sim uma estrutura/esqueleto de como os créditos devem ser criados. Deixando livre para o editor se ele quer colocar os créditos em movimento ou fixo, com cor A ou B. O padrão será apenas no tamanho das fontes, no nome de cada categoria, e de como elas devem aparecer (uma embaixo da outra, colunas, espalhadas na tela, etc). 
> 
> 
> 
> O que eu consigo lembrar é isso.
> 
> 
> 
> *Obs: A padronização tem por objetivo deixar o negócio mais linear. Creio que se padronizar demais tira a liberdade do editor de criar coisas interessantes. Então deve existir a padronização, mas não uma receita. 

Os dois principais tópicos que eu tinha pensado você já citou, que a padronização de números e um novo modelo de crédito que possa ser flexível para cada trabalho (que combine mais com a paleta do solicitante). 

Acredito que os vídeos internos tenha que ter uma melhor padronização, mas não consigo pensar no que...

**Comment by estelavilasboas** [comment]
> Pessoal do @/practice-uffs/con-design. Eu estava dando uma olhada na [paleta de cores](https://drive.google.com/drive/folders/1ymOvitNBOkBeU2RStVchrD6Rg8Ar4FB-) e a primeira cor, com código #264653 não está batendo com o que meu editor de imagens encontra, que é a cor de código #124255. E também não consegui encontrar na paleta de cores, as cores utilizadas para a criação da [vinheta](https://drive.google.com/drive/folders/1FFTk2H4YLBYcyNhBaZ1NikGyIRYdy_RO) do PRACTICE.
> 
> Vocês podem dar uma olhada nisso?

@robisonjose

Acho que com isso devo explicar o que aconteceu.
Primeiramente, digo que já fui informada dessa inconsistência de cores que realmente ocorre em alguns editores.
> Estou considerando que os editores e monitores de vocês estão bem calibrados, ok?

O que acontece é que a cor HEX #2624653 possui um fundo muito acinzentado, o que faz com que ocorra essa discrepância. 
No caso da vinheta do programa, quando foi produzida passou por 3 programas diferentes. Sendo um programa que utilizei para editar as imagens, outro para criar a animação e, por último, o programa que o @/andrewmsilva utilizou para criar a música. Todos estes processos fizeram com que o azul da vinheta se tornasse (pela minha breve análise) um HEX #003753, que contém um fundo muito mais azulado.
![image](https://user-images.githubusercontent.com/30927758/101074320-5f3ec500-357f-11eb-99fb-f20112a5f67a.png)
Profundidade dos tons do azul da vinheta (esquerda) e profundidade dos tons de azul da paleta (direita).

Eu sugiro que estudemos a possibilidade de utilizarmos a HEX #003753 ao invés da HEX #264653, e passemos a utilizá-la nas nossas produções daqui em diante. 
O intuito desde o início era a utilização de um azul escuro não acinzentado, o que ocorreu foi um erro em verificar a profundidade de tons da cor.

**Comment by robisonjose** [comment]
Particularmente eu concordo com a utilização da HEX #003753.

**Comment by amandasegattob** [comment]
Boa noite! Acredito que tudo o que eu pensava já foi citado. A única coisa que poderia ser padronizada (para seguir uma padronização rigorosa), seria os materiais que usados para os vídeos, por exemplo, ou todos em animações ou todos em imagens reais, mas como isso é muito individual de cada um que vai editar o vídeo, acho que isso fica meio inviável. 

Só dou ênfase nos planos de fundo, acho isso bem importante para se ter uma padronização.

**Comment by robisonjose** [comment]
1. Questão da proporção dos vídeos: Utilizar sempre 16x9 e se possível sempre 1920x1080;
2. Utilizar imagens PNG. Se for possível, sempre utilizar SVG e depois converter para PNG para inserir nos vídeos;
3. Fazer um fluxo da edição de vídeos;
4. Sempre que for usar um slide, baixar em SVG ou PDF e depois converter para PNG;
5. Todas as imagens e vídeos utilizados devem ter uma boa qualidade, condizente com a qualidade do vídeo (1080p). Caso seja necessário (muito necessário), ai dá para utilizar vídeos e imagens com qualidade inferior, mas só se não tiver outra opção.

**Comment by luizatonial** [comment]
> 1. Questão da proporção dos vídeos: Utilizar sempre 16x9 e se possível sempre 1920x1080;
> 2. Utilizar imagens PNG. Se for possível, sempre utilizar SVG e depois converter para PNG para inserir nos vídeos;
> 3. Fazer um fluxo da edição de vídeos;
> 4. Sempre que for usar um slide, baixar em SVG ou PDF e depois converter para PNG;
> 5. Todas as imagens e vídeos utilizados devem ter uma boa qualidade, condizente com a qualidade do vídeo (1080p). Caso seja necessário (muito necessário), ai dá para utilizar vídeos e imagens com qualidade inferior, mas só se não tiver outra opção.

só avisando que o shotcut aceita formato SVG, não é necessária a conversão para inserção nos vídeos

**Comment by vini2reis** [comment]
> 1. Questão da proporção dos vídeos: Utilizar sempre 16x9 e se possível sempre 1920x1080;
> 2. Utilizar imagens PNG. Se for possível, sempre utilizar SVG e depois converter para PNG para inserir nos vídeos;
> 3. Fazer um fluxo da edição de vídeos;
> 4. Sempre que for usar um slide, baixar em SVG ou PDF e depois converter para PNG;
> 5. Todas as imagens e vídeos utilizados devem ter uma boa qualidade, condizente com a qualidade do vídeo (1080p). Caso seja necessário (muito necessário), ai dá para utilizar vídeos e imagens com qualidade inferior, mas só se não tiver outra opção.

Pelo Google Apresentações também é possível fazer o download direto em PNG

**Comment by MaNegrao** [comment]
> > 1. Questão da proporção dos vídeos: Utilizar sempre 16x9 e se possível sempre 1920x1080;
> > 2. Utilizar imagens PNG. Se for possível, sempre utilizar SVG e depois converter para PNG para inserir nos vídeos;
> > 3. Fazer um fluxo da edição de vídeos;
> > 4. Sempre que for usar um slide, baixar em SVG ou PDF e depois converter para PNG;
> > 5. Todas as imagens e vídeos utilizados devem ter uma boa qualidade, condizente com a qualidade do vídeo (1080p). Caso seja necessário (muito necessário), ai dá para utilizar vídeos e imagens com qualidade inferior, mas só se não tiver outra opção.
> 
> Pelo Google Apresentações também é possível fazer o download direto em PNG

O problema do PNG baixado pelo Apresentações é a qualidade, ele baixa em 720p, geralmente os videos são feitos em 1080p, então o ideal é baixar em SVG que não perde a qualdiade

**Comment by amandasegattob** [comment]
Seguindo o que conversamos em reunião, fiz um documento e compilei nele tudo que foi falado aqui. Está nessa [pasta](https://drive.google.com/drive/folders/1H48jmZsuclsoUbdA9-Nu-pe8NC760mQC). 

- Criei os materiais no Canva pensando que essa seria uma boa opção para que todos consigam editar e, assim, adequar as cores dos materiais de acordo com seu vídeo, mas mantendo os elementos. 
- Não tenho certeza de como ficará a qualidade depois de fazer o download, fiz alguns testes e eu achei que fica bom, mas seria ideal que fizéssemos mais testes.
- Pensei em dois modelos (nomeados como 1 e 2 no Canva), um mais colorido e outro mais simples, gostaria que vocês me dissessem o que acharam e o que deve ser melhorado e mudado. 
- Em relação às numerações em transições, acredito que o ideal seria escolhermos apenas uma opção de cada um dos modelos. 
- O que está em vermelho são dúvidas e sugestões minhas.

**Comment by robisonjose** [comment]
Bom dia @amandasegattob. 

Dei uma lida no material e dei algumas ideias. Podemos conversar melhor sobre isso na próxima reunião.

**Comment by amandasegattob** [comment]
Bom dia! Fiz as alterações no documento conforme nossas discussões. Ainda precisamos definir a questão das legendas. 
Quem puder dar uma lida, eu agradeço. Provavelmente terão que ser feitas mais alterações.

**Comment by robisonjose** [comment]
Bom dia @amandasegattob.

O que tu acha da gente colocar o papel de fundo com a cor azul que tem a vinheta do PRACTICE (003953)? Acho que fica mais interessante.

**Comment by rafaguilman** [comment]
Boa Tarde

Se puderem retirar meu Email da lista de Transmissão de Envio agradeço.

Obrigado!!

Em ter., 20 de abr. de 2021 às 09:25, Robison ***@***.***>
escreveu:

**Comment by robisonjose** [comment]
Boa tarde @rafaguilman. 

Acredito que só você possa fazer isso.

**Comment by amandasegattob** [comment]
@robisonjose já fiz a alteração!

Pessoal do @practice-uffs/con-design, vocês têm a logo do PRACTICE toda branca? A que tenho está perdendo muito a qualidade na hora de baixar.

**Comment by robisonjose** [comment]
Bom dia @amandasegattob.

Fiz alguns testes com o Format Factory em relação as legendas. Fiz apenas duas opções. Mas me parece ser uma opção viável a utilização do FF. Ele possui a fonte ROBOTO, e também tem a possibilidade de colocarmos aquela faixa preta em baixo da legenda. Segue as configs que fiz e como elas ficaram (não repare na qualidade, coloquei assim só pra ser mais rápido). 

Primeira opção: 
![Captura de Tela (45)](https://user-images.githubusercontent.com/71669689/115733914-b0e5c180-a35f-11eb-9594-ee1cde1ebfc3.png)
![Captura de Tela (46)](https://user-images.githubusercontent.com/71669689/115733919-b216ee80-a35f-11eb-9c4f-943ade69d077.png)

Segunda opção:
![Captura de Tela (47)](https://user-images.githubusercontent.com/71669689/115733963-bb07c000-a35f-11eb-88ae-219592f343d8.png)
![Captura de Tela (48)](https://user-images.githubusercontent.com/71669689/115733970-bcd18380-a35f-11eb-93fe-222a1e8c42cb.png)

**Comment by robisonjose** [comment]
E ai, claro, temos a opção de colocar a fonte com cor branca e borda preta.

**Comment by robisonjose** [comment]
Boa tarde @Dovyski. 

Sim, pensamos bastante sobre essa questão. Esse padrão que estamos criando é para quando o solicitante pedir que a legenda seja inserida no vídeo. 

Por exemplo, em vídeos internos do PRACTICE que irão apenas para o YouTube, acredito que não seja necessário inserir a legenda no vídeo, mas sim ativá-las, como tu disse. No entanto, é importante termos uma padronização para quando for necessário utilizar essa ferramenta.

**Comment by amandasegattob** [comment]
Oie pessoal! Acredito que o documento já está quase finalizado. Alguém da @practice-uffs/con-conteudo pode revisar? 
Peço também que o pessoal da @practice-uffs/con-midia dê uma olhada, principalmente os que são da ilha de vídeos. 

*A pasta com os materiais prontos está vazia, pois ainda não deu tempo de baixar os materiais.

**Comment by robisonjose** [comment]
Boa noite @amandasegattob.

Eu solicitei acesso para ver os designs faz um tempinho já. Tu consegue ver isso pra mim?

Talvez deixar o documento aberto para quem tiver o link seja uma boa (não sei se essa opção existe).

**Comment by robisonjose** [comment]
Outra coisa, agora no documento. Acho que seria melhor aumentar o tamanho das configurações do Format Factory. Do jeito que está não tá dando para ver direito.

**Comment by thaliafriedrich** [comment]
> Oie pessoal! Acredito que o documento já está quase finalizado. Alguém da @practice-uffs/con-conteudo pode revisar?
> Peço também que o pessoal da @practice-uffs/con-midia dê uma olhada, principalmente os que são da ilha de vídeos.
> 
> *A pasta com os materiais prontos está vazia, pois ainda não deu tempo de baixar os materiais.

Fiz a revisão textual. O documento ficou ótimo e bem completo, parabéns! Além de fazer umas pequenas correções textuais, deixei algumas sugestões nos comentários do arquivo, pensando em auxiliar futuros bolsistas da con-midia.

**Comment by amandasegattob** [comment]
Muito obrigada @thaliafriedrich! Teus apontamentos foram ótimos, já estou fazendo as modificações <3

**Comment by amandasegattob** [comment]
Boa noite, pessoal! Terminei as modificações e gostaria de saber se alguém, pincipalmente da @practice-uffs/con-midia, tem mais algum apontamento sobre o documento.

**Comment by luizatonial** [comment]
Eu achei o material muito completo e, a princípio, não teria outras sugestões @amandasegattob. Parabéns!

**Comment by MilenaPaz2020** [comment]
Parabéns, @amandasegattob! Documento muito esclarecedor e completo.

**Comment by robisonjose** [comment]
O documento está maravilhoso. Parabéns @amandasegattob!

**Comment by amandasegattob** [comment]
Boa tarde. Transformei o doc em pdf e coloquei na [pasta da saída](https://drive.google.com/drive/folders/1ttrKgWsKRtd5yAaKdYSaVkoj7qTJYYuO). Assim, vou fechar essa issue, mas sempre que for necessário, podemos atualizar o documento. Obrigada por todas as sugestões pessoal!
