### ISSUE TITLE
Definição de padrões para lives realizadas pelo PRACTICE 

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#343]
Ao longo do programa as lives foram evoluindo e chegamos no momento em que vários membros estão produzindo lives, então precisamos definir padrões para serem utilizados e serem estritamente seguidos. Devemos criar um documento para deixar tudo bem claro. A issue tem como objetivo criar esse dialogo e definição dos pontos.
As lives do prorgama já começaram a ser padronizadas com a criação do overlay na issue #241. Mas devemos definir outros pontos. 

@luizatonial creio que tu pode ficar responsável por tal organização. @practice-uffs/con-midia a ilha de lives pode e deve auxiliar nos pontos que julguem necessario.

Os pontos que discutimos inicialmente são:

- Finalizar o Overlay
- Definifir transições padrão
- Plugins utilizados
- Formatação do countdown
- Chat do youtube (como usar streamlabs)
- Cores e fundos utilizavéis (podemos usar da issue #342 
- Disposição de elementos no OBS

[Pasta Drive](https://drive.google.com/drive/folders/10kZVYfFohT67CtMsSdMYmgG2uFT7wSlE)

**Comment by luizatonial** [comment]
Estamos aguardando o @ricardopatrik fazer os últimos ajustes do overlay. 
Se alguém da ilha de lives (@MilenaPaz2020, @pedroamaximowski, @rafaguilman) ou do @practice-uffs/con-midia tiver alguma sugestão será bem-vinda, verifiquem a issue #287.

**Comment by MilenaPaz2020** [comment]
Boa tarde, pessoal!
Organizando as coisas para a live de hoje (30/11) percebi a necessidade de um "lugar" nos créditos para quem está fazendo a mediação e não faz parte do apoio geral. No caso específico de hoje haverá várias pessoas da universidade trazendo algumas falas, penso em deixar todos os nomes como apresentadores. Mas acho que poderia haver um espaço exclusivo para a mediação.

**Comment by luizatonial** [comment]
Creio que podemos **definir algumas **transições**** específicas:
- uma para a entrada inicial 
- uma para a troca de tela (por exemplo de uma tela sem slides para uma tela com slides)  
- uma para algum ajuste/correção/detalhe específico 
- uma para a finalização e apresentação dos créditos

Na minha opinião, na terceira seria interessante utilizarmos alguma transição que fique menos aparente como o "esmaecer" ou "cortar". E transições mais visuais, nos momentos de entrada e saída, alguma que deslize a tela, por exemplo.

**Comment by luizatonial** [comment]
Realizei alguns ajustes no computador do laboratório em laranjeiras agora, se atentem para manter os padrões:

- Para o chat estamos utilizando o site _streamlabs_, segue descrição retirada do roteiro do OBS:
**(Lembrem-se que vocês devem acessar o site com a conta do canal do youtube em que irão realizar a live. 
E sempre confiram o chat antes das lives, em todas as telas, porque é comum precisar ajustar novamente)**

> Caso seja do seu interesse, você também pode replicar o bate-papo da plataforma em que você está transmitindo, como o YouTube por exemplo, para a tela da transmissão.
Para isso você deve acessar o site: https://streamlabs.com. 
Na sequência você irá selecionar a opção “login”, acessar a plataforma com sua conta do YouTube e conceder as permissões necessárias. 
Se necessário, escolha o plano “Starter”, que é gratuito, prossiga sem inserir nenhum dado de pagamento ou conta, e passe pelas demais configurações adicionais até chegar na tela principal do site.
Nesta tela, você deve encontrar o menu “Features”, selecionar a opção “All Widgets” e, na nova tela, escolher “Chat Box”. Descendo a tela, você encontrará uma simulação do chat, onde irá definir o tema. Neste caso, usaremos a opção “Clean”. Mais abaixo, você pode escolher também a cor e o tamanho do texto que irá aparecer no bate-papo. Em seguida, salve as configurações.
Voltando para a parte superior da tela, você encontrará o menu “Widget URL”, onde você deve clicar no botão “Copy”, para copiar o link que irá gerar seu chat.
De volta ao OBS Studio, você irá adicionar uma nova fonte, do tipo “Navegador”, você pode atribuir um nome, como “Chat”, por exemplo, e colar o link do streamlabs no campo “URL”. Lembre-se de ajustar o tamanho da fonte conforme o overlay.

- Para o cronômetro estamos utilizando a fonte **roboto black italic** com cor em gradiente de laranja e amarelo, seguem os códigos:
![image](https://user-images.githubusercontent.com/71669357/101093349-5eb32800-3599-11eb-9588-c45bc06107c8.png)

**Comment by luizatonial** [comment]
Acho que outra coisa que poderíamos padronizar é a ordem de utilização dos elementos antes da live, por exemplo.

Nós temos a tela de espera com o cronômetro, o vídeo promocional do PRACTICE e a capa da live em si.
Andei reparando que em algumas lives não estamos utilizando a capa, em outras o cronômetro vem antes do vídeo promocional e em algumas outras o cronômetro vem depois deste vídeo e logo antes da entrada dos apresentadores...

Acredito que o vídeo promocional poderia vir antes do cronômetro, enquanto estamos fazendo os ajustes e utilizar a contagem para marcar realmente o início da fala do palestrante, o que vocês acham?

**Comment by MilenaPaz2020** [comment]
> Acho que outra coisa que poderíamos padronizar é a ordem de utilização dos elementos antes da live, por exemplo.
> 
> Nós temos a tela de espera com o cronômetro, o vídeo promocional do PRACTICE e a capa da live em si.
> Andei reparando que em algumas lives não estamos utilizando a capa, em outras o cronômetro vem antes do vídeo promocional e em algumas outras o cronômetro vem depois deste vídeo e logo antes da entrada dos apresentadores...
> 
> Acredito que o vídeo promocional poderia vir antes do cronômetro, enquanto estamos fazendo os ajustes e utilizar a contagem para marcar realmente o início da fala do palestrante, o que vocês acham?

Sim, isso era algo que eu estava pensando e que me deixa com dúvidas.
Em geral eu uso: Promocional do PRACTICE - Capa - Cronômetro. 
Nos casos de tudo estar em ordem antes do horário previsto da live, coloco o promocional uns 10 min antes e quando faltam 5 min coloco cronômetro. Mas precisamos definir um padrão kkk

**Comment by luizatonial** [comment]
> > Acho que outra coisa que poderíamos padronizar é a ordem de utilização dos elementos antes da live, por exemplo.
> > Nós temos a tela de espera com o cronômetro, o vídeo promocional do PRACTICE e a capa da live em si.
> > Andei reparando que em algumas lives não estamos utilizando a capa, em outras o cronômetro vem antes do vídeo promocional e em algumas outras o cronômetro vem depois deste vídeo e logo antes da entrada dos apresentadores...
> > Acredito que o vídeo promocional poderia vir antes do cronômetro, enquanto estamos fazendo os ajustes e utilizar a contagem para marcar realmente o início da fala do palestrante, o que vocês acham?
> 
> Sim, isso era algo que eu estava pensando e que me deixa com dúvidas.
> Em geral eu uso: Promocional do PRACTICE - Capa - Cronômetro.
> Nos casos de tudo estar em ordem antes do horário previsto da live, coloco o promocional uns 10 min antes e quando faltam 5 min coloco cronômetro. Mas precisamos definir um padrão kkk


Concordo! Acho que podemos padronizar esta ordem: **Promocional do PRACTICE - Capa da Live - Tela de Espera/Cronômetro.**
Em algumas lives eu nem consegui utilizar o cronômetro devido à organização com os apresentadores, já em outras eu coloquei em torno de 2-3 min antes, acho que talvez o tempo do cronômetro em si poderia ficar em aberto, mudando de acordo com a situação das transmissões.

**Comment by luizatonial** [comment]
Reparei também que agora o webex está permitindo ocultar o nome dos participantes da reunião, podemos utilizar deste recurso para melhorar o enquadramento dos apresentadores.

**Comment by MaNegrao** [comment]
Os apontamentos estão excelentes, acho que podemos começar a sintetizar isso em um documento e deixamos explicito, e podemos também ramificar uma outra issue do protocolo de lives, creio que a @MilenaPaz2020 gostaria de ir montando o protocolo de ações e etc.

**Comment by MilenaPaz2020** [comment]
> Os apontamentos estão excelentes, acho que podemos começar a sintetizar isso em um documento e deixamos explicito, e podemos também ramificar uma outra issue do protocolo de lives, creio que a @MilenaPaz2020 gostaria de ir montando o protocolo de ações e etc.

Sim :D
Logo irei abrir uma issue para trabalhar no protocolo de lives.

**Comment by luizatonial** [comment]
certo! vou começar a trabalhar no documento referente aos padrões então.

**Comment by MaNegrao** [comment]
@luizatonial e @MilenaPaz2020 Estive pensando e agora que estamos estabelecendo os padrões e protocolo de lives, podemos abrir uma issue para ajustarmos o modelo do roteiro. Conversei com alguns solicitantes e percebo que eles não conseguem entender algumas coisas ainda, então acho que podemos simplificar ainda mais e acrescentar eventuais pontos novos. O que acham?

**Comment by luizatonial** [comment]
> @luizatonial e @MilenaPaz2020 Estive pensando e agora que estamos estabelecendo os padrões e protocolo de lives, podemos abrir uma issue para ajustarmos o modelo do roteiro. Conversei com alguns solicitantes e percebo que eles não conseguem entender algumas coisas ainda, então acho que podemos simplificar ainda mais e acrescentar eventuais pontos novos. O que acham?

Concordo @MaNegrao, acredito que a reformulação seria bem válida.

**Comment by luizatonial** [comment]
Uma primeira versão do documento está na [pasta](https://drive.google.com/drive/folders/1bkWm3M9zkovEktrPv5edOKzgjjZcybUt). 
Tentei fazer um documento mais detalhado, a fim de auxiliar a todos os membros do mídia e não só os da ilha de lives. 

Peço a todos que verifiquem o documento e me ajudem a incrementá-lo. 
Além disso coloquei algumas observações na parte das transições.

@MaNegrao @MilenaPaz2020 @pedroamaximowski @rafaguilman

**Comment by MilenaPaz2020** [comment]
> @luizatonial e @MilenaPaz2020 Estive pensando e agora que estamos estabelecendo os padrões e protocolo de lives, podemos abrir uma issue para ajustarmos o modelo do roteiro. Conversei com alguns solicitantes e percebo que eles não conseguem entender algumas coisas ainda, então acho que podemos simplificar ainda mais e acrescentar eventuais pontos novos. O que acham?

Sim, @MaNegrao, creio que esse ajuste é muito importante.
Eu imaginei em inserir o protocolo de atendimento no próprio roteiro, mas a julgar pelo tamanho do protocolo não seria uma boa ideia.

Se puder abrir uma issue, contendo as dúvidas mais recorrentes dos solicitantes, já poderemos começar a trabalhar no roteiro.

**Comment by MilenaPaz2020** [comment]
> Uma primeira versão do documento está na [pasta](https://drive.google.com/drive/folders/1bkWm3M9zkovEktrPv5edOKzgjjZcybUt).
> Tentei fazer um documento mais detalhado, a fim de auxiliar a todos os membros do mídia e não só os da ilha de lives.
> 
> Peço a todos que verifiquem o documento e me ajudem a incrementá-lo.
> Além disso coloquei algumas observações na parte das transições.
> 
> @practice-uffs/con-midia

Fiz a leitura do documento e fiquei impressionada! Está muito bem escrito e muito claro, @luizatonial. Parabéns!
Fiz um apontamento em relação aos créditos do mediador, mas nos demais pontos estou de acordo.

Acredito que com as lives dessa semana possa surgir mais algum ponto ou dúvida e talvez seja necessária alguma alteração. Acho válido que @pedroamaximowski  e o @rafaguilman opinem em relação ao documento o quanto antes, para que no final dessa semana já tenhamos um parecer sobre os padrões.

**Comment by rafaguilman** [comment]
Acredito que está bem definido!! 👍

**Comment by robisonjose** [comment]
Bom dia pessoal. 

Caramba @luizatonial, ficou muito bem escrito e explicado. Parabéns. 

Talvez para uma melhor organização seja interessante utilizar um espaço entre cada item/letra ou colocar os itens/letras em cores diferentes, tipo laranja. Percebi que no começo é dado esse espaço entre os item, mas depois eles somem. Talvez escolher algo para melhorar a organização seja uma boa ideia. 

Todavia, mandou muito bem.

**Comment by robisonjose** [comment]
> > @luizatonial e @MilenaPaz2020 Estive pensando e agora que estamos estabelecendo os padrões e protocolo de lives, podemos abrir uma issue para ajustarmos o modelo do roteiro. Conversei com alguns solicitantes e percebo que eles não conseguem entender algumas coisas ainda, então acho que podemos simplificar ainda mais e acrescentar eventuais pontos novos. O que acham?
> 
> Sim, @MaNegrao, creio que esse ajuste é muito importante.
> Eu imaginei em inserir o protocolo de atendimento no próprio roteiro, mas a julgar pelo tamanho do protocolo não seria uma boa ideia.
> 
> Se puder abrir uma issue, contendo as dúvidas mais recorrentes dos solicitantes, já poderemos começar a trabalhar no roteiro.

Por isso que é tão importante o FeedBack escrito dos solicitantes após as lives.

**Comment by luizatonial** [comment]
Obrigada pelas sugestões, já fiz a maior parte das alterações em relação ao texto e respondi alguns dos comentários de vocês.
Como não houveram sugestões sobre outros tipos de transições até o momento, finalizei o desenvolvimento do texto desta parte.
E também inseri uma descrição mais detalhada sobre o elemento da "Capa da Live".

Assim que tivermos um retorno dos demais membros da equipe, pretendo trabalhar na revisão da organização/padronização do documento como sugerido.

**Comment by luizatonial** [comment]
Além disso, o @robisonjose sugeriu em um momento a criação de um vídeo curto explicativo, acho a ideia bem válida. 
Então pretendo desenvolver alguns vídeos curtos para integrarem o Telecurso 2000, com demonstrações sobre a configuração do chat, do plano de fundo para a capa e do cronômetro, por exemplo.

**Comment by pedroamaximowski** [comment]
Ficou muito bom esse padrão, utilizei na última Live que fiz e ficou bem melhor !.

**Comment by pedroamaximowski** [comment]
Só estou com uma dúvida de como proceder quando o início da live atrasa.
Por exemplo a última que fiz atrasou meia hora para iniciar, aí para iniciar ela coloquei o promocional do practice, e a capa, sem a tela de espera e o cronômetro, pois já estava atrasada.

**Comment by luizatonial** [comment]
> Só estou com uma dúvida de como proceder quando o início da live atrasa.
> Por exemplo a última que fiz atrasou meia hora para iniciar, aí para iniciar ela coloquei o promocional do practice, e a capa, sem a tela de espera e o cronômetro, pois já estava atrasada.

Acredito que em caso de atraso podemos continuar repetindo o vídeo promocional do Practice e tentar manter a estrutura com a capa e a tela de espera em alguma medida. Se realmente não for possível manter a estrutura em razão da situação da live/solicitante podemos pular algum elemento assim como você fez.

**Comment by luizatonial** [comment]
Em relação ao chat da transmissão, eu havia sugerido a fonte **tamanho 26px** que ficava em um tamanho adequado com o dimensionamento do chat em **450x250** ou **450x600** (realizado nas propriedades da fonte). Pelo menos nos testes que realizei com o OBS no meu computador.

O @pedroamaximowski acabou não verificando a opção ontem e utilizou o tamanho que já estava no OBS para o chat.

Já o @rafaguilman tentou utilizar hoje e acabou ficando muito grande, acredito que isso tenha ocorrido porque a janela estivesse com outra dimensão talvez diferente das recomendadas. Então ele utilizou a opção com **22px** e ficou melhor.

Acredito que nas próximas lives teremos que verificar esta configuração do tamanho da fonte e da dimensão do chat pra ver qual realmente se adequa.

**Comment by robisonjose** [comment]
Ainda em relação ao chat, acho que seria interessante deixar as mensagens por mais tempo na tela.

**Comment by luizatonial** [comment]
> Ainda em relação ao chat, acho que seria interessante deixar as mensagens por mais tempo na tela.

em torno de 50s talvez?

**Comment by robisonjose** [comment]
Não teria como deixar as mensagens sempre? Eu acho meio triste a aba de chat vazia. Ai as últimas mensagens estariam sempre na tela (não sei se é possível fazer isso).

**Comment by luizatonial** [comment]
> Não teria como deixar as mensagens sempre? Eu acho meio triste a aba de chat vazia. Ai as últimas mensagens estariam sempre na tela (não sei se é possível fazer isso).

kk fica um pouco triste mesmo, mas será que as mensagens não vão ficar fora de contexto se continuarem sempre na tela? mas existe a opção sim

**Comment by MaNegrao** [comment]
Talvez diminuir um pouquinho só a fonte pode ajudar a deixar mais populado de comentários TB né

**Comment by luizatonial** [comment]
> Talvez sim. É que está acontecendo isso.
> 
> ![Captura de Tela (25)](https://user-images.githubusercontent.com/71669689/106069852-166c3e00-60e2-11eb-91c6-11d8c9429659.png)
> 
> Tipo, tem muitas mensagens no chat da live, mas pouquissímas no chat da tela.

Entendi, acho que para deixar sempre com alguma mensagem, pela questão do intervalo entre elas, teríamos que deixar elas permanentemente mesmo... se vocês acharem melhor utilizamos dessa maneira

**Comment by luizatonial** [comment]
A primeira versão finalizada do documento está na [pasta de saída](https://drive.google.com/drive/folders/1pHTZEmDa5kWDDjjXEMBPp2cX9J_BMIy0). Todos os pontos sugeridos foram atendidos, contudo, como agora irei assumir a modificação e a finalização do nosso overlay, o documento precisará sofrer alterações no futuro.

**Comment by MaNegrao** [comment]
Vou mover para pasta de mídia e colocar o link no template de issues para lives.
