### ISSUE TITLE
Mapeamento e Organização de vídeos internos do programa

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#344]
Com a produção de muitos vídeos pela equipe de mídia, os vídeos internos estão ficando perdidos no meio das demandas externas. Eu sugiro que montemos uma planilha no docs para armazenar todas as informações relevantes sobre os vídeos já produzidos e posteriormente iremos conseguir definir data de publicação para eles na issue #336 

Podemos encontrar todos os vídeos produzidos pela label de vídeo e colocarmos as informações necessarias na planilha.

Comentem na issue outros pontos importantes.

[Pasta Drive](https://drive.google.com/drive/folders/1PI76POKJnVc487c7ED9zn6kVIf6Cmkws)

CC: @practice-uffs/con-midia

**Comment by robisonjose** [comment]
Comecei a montar a [planilha](https://docs.google.com/spreadsheets/d/1sWDm8tK3bZ47Cw9f_E4gqe013x-fWGFvA3EntSwufDg/edit#gid=0).

**Comment by morgana-mo** [comment]
@robisonjose  posso começar a montar o calendário a partir do que se encontra na planilha ou há algum impedimento de começar antes dessa planilha  ser finalizada?

**Comment by robisonjose** [comment]
Boa tarde @morgana-mo. 

Acredito que seja mais interessante montar o calendário quando tivermos mais vídeos prontos, pois por enquanto ainda temos apenas um vídeo finalizado, e caso não consigamos terminar os vídeos internos devido às demandas externas não conseguiríamos cumprir o calendário. 

@MaNegrao, o que tu me diz?

**Comment by MaNegrao** [comment]
Acho que podemos encontrar um meio termo, vale fazer um esboço do calendario, mas não publicar e nem tornar obrigatório pra se seguir. É interessante para analisarmos a disposição dos videos ao longo do tempo

**Comment by morgana-mo** [comment]
Concordo totalmente com a ideia do @MaNegrao me expressei mal no comentário, vou fazer um esboço sem muito compromisso com os prazos e voltamos a conversar quando os vídeos forem ficando prontos.

**Comment by robisonjose** [comment]
Bom dia @morgana-mo. 

Refiz a [planilha ](https://docs.google.com/spreadsheets/d/1sWDm8tK3bZ47Cw9f_E4gqe013x-fWGFvA3EntSwufDg/edit#gid=0) de uma forma que eu acho que seja melhor para se organizar. 

Peço atenção especial de todos da @practice-uffs/con-midia. Creio que podemos nos organizar em relação ao que estamos fazendo e em que etapa de produção estamos através dessa planilha. Então devemos mantê-la o mais atualizada possível. 

Eu coloquei as etapas de produção da maneira que eu pensei ser, mas a realidade pode não ser essa. Então peço aos responsáveis por cada vídeo que alterem a planilha caso seja necessário.

**Comment by MaNegrao** [comment]
@robisonjose acho que podemos fechar essa issue e colocar a planilha de mapeamento na pasta da Con-Midia do programa, para que possamos acessar ela e popular com os vídeos futuros. O que acha?

**Comment by robisonjose** [comment]
Boa tarde @MaNegrao.

Pode ser.

**Comment by MaNegrao** [comment]
fechandooo
