### ISSUE TITLE
Formação de Texto e Escrita - (02/12) - 19:00

### ISSUE THREAD

**Issue by estelavilasboas** [practice-uffs/programa#345]
Será realizada uma nova edição da formação de texto e escrita nessa **_quarta-feira (02/12)_** às **_19h_**.
Lembramos que é de extrema **importância** a **presença** do maior número de integrantes possível.

Leituras interessantes:
- [Dicas para escrever um bom texto](https://github.com/practice-uffs/programa/files/5190633/DICAS.PARA.ESCREVER.UM.BOM.TEXTO.pptx.pdf)
- [Gêneros textuais - Marcuschi](https://github.com/practice-uffs/programa/files/5190635/generos.textuais.-.Marcuschi.pdf)

cc: @practice-uffs/todos

**Comment by VIF-Franca** [comment]
Show !!!

**Comment by robisonjose** [comment]
Vocês mandam no grupo do telegram o link para a formação?

**Comment by alessandrapedrotti** [comment]
O material base para a formação é o mesmo da original, que pode ser encontrado nessa issue #119.

O foco dessa formação é auxiliar na escrita do relatório. A formação será gravada e posteriormente disponibilizada para quem não puder participar no horário estipulado.

**Comment by VIF-Franca** [comment]
Pessoal o link para a formação de hoje: 
https://uffs.webex.com/meet/vinicius.alves

Abertura da sala: 18:30 para o @pedroamaximowski  preparar o ambiente para a gravação. 

Horário de inicio: 19:00.
