### ISSUE TITLE
Live RP e PIBID III - 14/12 - 15h-16h

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#346]
Terceira conferencia do PIBID e RP

Ministrante(s) Prof. Dr. Lourival José Martins Filho (UDESC/ABALF)
Mediador: Rosenei Cella (Diretora de Políticas de Graduação/UFFS)

Data: 14/12/2020
Horário de início: 15h00min
Horário de término: 16h00min

LInk: https://youtu.be/zLT9UG_GSZI

Todas as informações estão no roteiro, os convidados com nome no roteiro provavelmente terão fala.
A capa será produzida pelo PRACTICE

[Pasta Drive](https://drive.google.com/drive/folders/14HFSkPJcL3i8j5vWvncaxltznwisBtjK?usp=sharing)

CC: @practice-uffs/con-midia

**Comment by MilenaPaz2020** [comment]
Temos uma outra live para ser realizada nesse dia (16:30 - 18:30) que já assumi. Apesar de ter um intervalo de 30min entre elas, creio que não seja aconselhável usar o computador remoto para ambas. Como podemos resolver?

**Comment by MaNegrao** [comment]
@VIF-Franca e @pedroamaximowski acho que podemos colocar o pc de laranjeiras em operação remota, o que acham?

**Comment by VIF-Franca** [comment]
@MaNegrao podemos sim, caso queira a noite podemos testar a conexão remota, ai deixamos ele ligado full time.

**Comment by MaNegrao** [comment]
Perfeito

**Comment by MilenaPaz2020** [comment]
Live finalizada com sucesso! :D
https://www.youtube.com/watch?v=zLT9UG_GSZI
