### ISSUE TITLE
Criação de convite para LIVE PIBID e RP III - 14/12 - 15h

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#347]
Temos que criar um convite para a III conferecia PIBID e RP

Pode ser semelhante a issue #300 com tudo semelhante. 
Os materiais podem ser encontrados na pasta do drive

Link: https://youtu.be/zLT9UG_GSZI

[Pasta Drive](https://drive.google.com/drive/folders/1RmeQ8bJnEbiiG39LU65p1ngm2IkWKehu)

CC: @practice-uffs/con-midia @practice-uffs/con-design

**Comment by TaynaraCh** [comment]
O [arquivo está pronto](https://drive.google.com/drive/folders/1RmeQ8bJnEbiiG39LU65p1ngm2IkWKehu)

Como foi solicitado que fosse semelhante ao outro convite, optei por mudar apenas as cores e manter a mesma identidade das outras edições, assim, diferenciam-se mas ainda pertencem ao mesmo evento. 

Se considerarem necessário, posso elaborar outro convite, dentro da identidade já criada.

**Comment by MaNegrao** [comment]
> O [arquivo está pronto](https://drive.google.com/drive/folders/1RmeQ8bJnEbiiG39LU65p1ngm2IkWKehu)
> 
> Como foi solicitado que fosse semelhante ao outro convite, optei por mudar apenas as cores e manter a mesma identidade das outras edições, assim, diferenciam-se mas ainda pertencem ao mesmo evento.
> 
> Se considerarem necessário, posso elaborar outro convite, dentro da identidade já criada.

Enviei ao solicitante e estou no aguardo da resposta.

**Comment by MaNegrao** [comment]
Foi aceito pelo solicitante
