### ISSUE TITLE
Criação de Identidade Visual Complexa para Podcast do Centro de Línguas da UFFS Chapecó - Complexa 

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#348]
A cliente solicitou a criação de uma Identidade Visual para ser usada no Podcast do Centro de Línguas da UFFS do campus Chapecó

Contendo:
-  símbolo, logotipo, paleta de cores, marca d’água e padronagem informando que se trata de um Podcast da área de "Português como Língua Estrangeira"

Já foi enviado o link do formulário para a solicitante preencher

Contato solicitante: Claudia Andrea Rost Snichelotto <claudiarost@uffs.edu.br>

[Pasta da issue](https://drive.google.com/drive/folders/11jBqVD6kDHwv776vtDFiIQI30A_iV_ud)

**Comment by VIF-Franca** [comment]
@estelavilasboas , essa demanda será atendida em 2020 ainda ?

**Comment by VIF-Franca** [comment]
Conforme definido em reunião essa demanda será atendida em 2020, sendo assim irei sinalizar para o demandante. 

Ao terminar o novo formulário, por gentileza adicionar o link aqui para que seja possível enviar para o cliente.

**Comment by VIF-Franca** [comment]
Cliente notificada sobre atendimento apenas 2021.

**Comment by VIF-Franca** [comment]
Questionário respondido pelo cliente.

**Comment by estelavilasboas** [comment]
Respostas do formulário em pdf na [pasta Entrada](https://drive.google.com/drive/folders/1IkuMr304Wbn0Hzz80qaWEZ-p1dmETuqk).

**Comment by TaynaraCh** [comment]
Adicionei a pasta primeiro envio os [arquivos](https://drive.google.com/drive/folders/1Oo8R8s9NKKsCftYSevjcFSoK_47T3GPm) para a entrega intermediária à solicitante, na pasta encontram-se as opções de logo em png e um pdf contendo as informações sobre elas. @VIF-Franca ou @mariagelain, podem enviar!

**Comment by VIF-Franca** [comment]
E-mail enviado.

**Comment by mariagelain** [comment]
A solicitante escolheu a terceira opção. Não houve nenhuma solicitação de alteração na imagem escolhida, portanto já se pode iniciar a produção da versão final da Identidade Visual.

**Comment by TaynaraCh** [comment]
Já iniciei os detalhes finais para entrega da identidade.

**Comment by TaynaraCh** [comment]
Identidade finalizada! Pngs e pdf com a descrição estão na pasta de [saída,](https://drive.google.com/drive/folders/1HqnE5GKrlkTUc9kSZIVo4qowtCO7_4V5) @mariagelain pode enviar!! uhuuuuuuul

**Comment by TaynaraCh** [comment]
Os arquivos estão salvos em svg na pasta [editáveis](https://drive.google.com/drive/folders/1qk7rniTId0xpPx3OGxuZifQeAleawLnK)

**Comment by mariagelain** [comment]
Os arquivos foram enviados!

**Comment by mariagelain** [comment]
A solicitante aprovou a Identidade Visual, portanto a issue já pode ser fechada.
