### ISSUE TITLE
Escala de férias

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#349]
Será criada uma planilha para controlar a escala de férias da equipe do practice, considerando as informações:

1. **Dos dias 23/12/2020 à 03/01/2021 - período de férias gerais: TODOS os integrantes do programa estarão dispensados;**
2. Dos dias 04/01/2021 à 16/01/2021 - 50% dos bolsistas estarão atuando;
3. Dos DIAS 18/01/2021 à 30/01/2021 - TODOS os bolsistas retornam para as atividades;
4. Dos dias 01/02/2021 à 13/02/2021 - 50% dos bolsistas estarão atuando;
5. **A partir do dia 17/02/2021 - TODOS  os bolsistas retornam e as atividades retornam ao fluxo normal.**

A planilha deverá ser divida por equipes e apresentar 3 colunas, sendo elas: 

- Nome do bolsista;
- período de férias;
- Período de atuação.

A planilha também deve conter um campo para que o líder de cada equipe indique um suplente para ocupar seu lugar no período que estiver afastado.

Lembrando que cada bolsista terá direito ao período de "férias coletivas" e a um dos períodos mutáveis citados acima (tópico 2 ou 4) e esses períodos mutáveis serão discutidos nas reuniões de equipe.

**Comment by Claudineia-VR** [comment]
A primeira versão da planilha de escala de férias está pronta, podem verificar como ela ficou na pasta ''tarefas'', sub-pasta [programa#349](https://docs.google.com/spreadsheets/d/1kgzNocLBRNus9jDrXiTQw0gc82xJIdm_uwXSUknCAEk/edit#gid=0). Coloquei uma parte inicial na primeira aba para ficar visível como um todo, quem são as pessoas que estarão trabalhando em cada período, e quanto a indicação de suplente coloquei uma legenda sugerindo que este seja destacado na cor amarela da identidade visual do PRACTICE, assim a planilha fica menos poluída facilitando a visualização das informações.

Nas demais abas fiz conforme solicitado, separei por equipes utilizando 3 colunas:
 - Nome do bolsista;
 - Período de férias;
 - Período de atuação.
 
 Na última aba fiz uma versão utilizando outras 3 colunas:
 - Nome do bolsista;
 - 04/01 à 16/01;
 - 01/02 à 13/02.

Eu particularmente preferi o formato que fiz como sugestão, mas aguardo os feedbacks de vocês.

**Comment by alessandrapedrotti** [comment]
Estou olhando aqui, e realmente faz mais sentido seguirmos com a sua sugestão, Claudinéia. Ficou muito bom e muito bem organizado.
Te peço para mudar então todas as abas para ficarem de acordo com a tua sugestão.
Também já te indiquei como suplente do período que eu estiver de férias.

**Comment by Claudineia-VR** [comment]
Já mudei a planilha, está pronta e pode ser repassada e preenchida. Peço aos que já haviam colocado seus dados que confiram novamente.

**Comment by Claudineia-VR** [comment]
A planilha foi preenchida por todos os membros e movida para a pasta "materiais" na subpasta [Escala de Férias](https://drive.google.com/drive/u/0/folders/1QKbPOUSii6YNluY3tpCfPRZGmLbevdcJ).
