### ISSUE TITLE
Criar PRACTICE no LinkedIn

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/programa#350]
VIsto que muitos de nós possuímos LinkedIn e que esta plataforma é muito boa para visibilidade profissional, é necessário que seja criado um perfil de empresa para o PRACTICE. Dessa forma, nós poderemos nos vincular ao programa no LinkedIn, aumentando a visibilidade do programa. Além disso, seria bem legal todos poderem deixar essa experiência registrada.

**Comment by morgana-mo** [comment]
Li um pouco sobre a criação de páginas empresariais no LinkedIn, como nunca tive contato com  a plataforma fiquei em dúvida sobre qual associação devemos dar ao PRACTICE no LinkedIn. Se alguém puder ajudar fico grata!
![image](https://user-images.githubusercontent.com/71781124/101197358-c7091480-3640-11eb-9ab0-b468fe23cd32.png)

**Comment by Dovyski** [comment]
O PRACTICE é meio que um "monstro" porque ocupa várias categorias. Eu acho que podemos usar "Pequena Empresa", @morgana-mo .

**Comment by morgana-mo** [comment]
Sigo com este problema do erro interno
![image](https://user-images.githubusercontent.com/71781124/101532004-b1625a80-3972-11eb-8927-26adb28a1e10.png)

**Comment by Dovyski** [comment]
Que negócio estranho isso. Tenta criar o perfil sem uma logo e sem um slogan, @morgana-mo , para ver se resolve o problema.

**Comment by morgana-mo** [comment]
Ali no item 6 explica o porque de não estar dando certo, vou aguardar uns dias e daí acho que vou conseguir criar sem problemas.
![IMG_20201209_115846_608.jpg](https://user-images.githubusercontent.com/71781124/101646189-f5f30200-3a15-11eb-8221-d8a5abe3a659.jpg)

**Comment by morgana-mo** [comment]
Hoje obtive resposta do suporte do LinkedIn, segue o que foi colocado como resposta ao problema da criação da Company page do PRACTICE na plataforma:

IMPORTANTE:

- A página da empresa deve ser criada a partir do perfil PESSOAL. NÃO pode ser criada da partir de um perfil que usa o nome da empresa. Você até poderá conseguir fazer isso, mas o perfil que usa o nome da empresa brevemente será bloqueado e você perderá o acesso, tanto deste perfil como da empresa associada a ele. Portanto use um perfil pessoal como administrador.

- Não é possível criar e gerenciar uma página de empresa sem vínculo a um perfil.

Se você está tentando criar uma página e deu um erro, veja que na maior parte dos casos, esse erro ocorre quando alguns requisitos obrigatórios não foram atingidos.

Pode por favor verificar se cumpre os requisitos abaixo indicados?

1 - Se buscar o nome da página que quer usar (https://www.linkedin.com/company/nome ) e encontrar uma mensagem de que a página está indisponível, o nome não poderá ser usado. Uma página indisponível é uma página existente que está desativada e somente poderá ser reativada pelo seu último administrador. Neste caso a url e nome não poderão ser usados.

Você poderá usar o nome desde que utilize algum complemento que o diferencie da página que foi desativada. Pode acrescentar um hifen, uma sigla, cidade, etc.

2 - A página de Empresa a ser criada a partir de um perfil pessoal no LinkedIn, está configurada com seu nome e sobrenome verdadeiro?

O perfil para acessar uma página deverá ser pessoal. Não pode ser o mesmo nome da empresa.
Se isso ocorrer, o perfil poderá ser restrito por uso comercial. Além disso, poderia causar confusão durante as buscas.

Não é permitido usar um perfil com o nome da empresa para criar a página pois isso viola os termos de uso do LinkedIn e o perfil será bloqueado permanentemente por uso comercial, de forma que o acesso ao perfil será perdido e consequentemente será perdido também o acesso à página vinculada a ele.

3 - Este perfil deve conter conexões, no mínimo de 10, e deve esperar 24 horas desde que o último convite de conexão foi aceito.

4 - O seu perfil deve ter sido criado há pelo menos 7 dias.

5 - Ser funcionário atual da empresa e o cargo estar listado na seção Experiência do perfil.

6 - O domínio de e-mail deve ser corporativo, ou seja, exclusivo da empresa. O seu endereço de e-mail deve estar verificado.
Um domínio de email não pode ser utilizado mais de uma vez para criar uma página.
Infelizmente ou talvez não, os domínio gmail.com, yahoo.com ou outros serviços de e-mail genéricos não são exclusivos de uma empresa, logo não podem ser utilizados para criar uma página.

7 - Para evitar erros por incompatibilidade de arquivos, evite colocar qualquer logotipo antes da criação da página. Você poderá inserir a sua marca após esse processo.

No link abaixo tem o passo a passo para criação de uma LinkedIn Page:

https://www.linkedin.com/help/linkedin/answer/4463


Quando os requisitos acima forem atendidos, clique no link para criar uma página:

https://www.linkedin.com/company/setup/new/

Ainda assim, se não conseguir criar a página da empresa mesmo depois de cumpridos os requisitos acima, verifique por favor se:

a) Existe uma página Empresa com o mesmo nome, e se esta tenta usar um link para a sua página que já esteja sendo usado por outra página empresa. Neste caso terá que alterar ligeiramente o URL para que ele seja único.

b) O URL que está a tentar usar não têm caracteres inválidos. O link seguinte tem informação acerca dos caracteres:
https://www.linkedin.com/help/linkedin/answer/710

c) Tente outro navegador para ver se o problema fica resolvido. Esta é uma lista atual de navegadores de internet compatíveis: https://www.linkedin.com/help/linkedin/answer/4135

Espero que as informações tenham sido úteis.

NOTA: Esteja ciente de que, após 24 horas sem resposta, esse ticket será fechado automaticamente pelo sistema sem a minha intenção.

Atenciosamente

Terezinha Benício
Especialista da comunidade LinkedIn

**Comment by morgana-mo** [comment]
@Dovyski você consegue criar pela sua conta do LinkedIn?

**Comment by Dovyski** [comment]
Claro, vou criar e passar para vocês configurarem depois.

**Comment by Dovyski** [comment]
Criei a página: [linkedin.com/company/practiceuffs](https://www.linkedin.com/company/practiceuffs). @morgana-mo me adiciona no linkedin ([fernandobevilacqua](https://www.linkedin.com/in/fernandobevilacqua/)), por favor, para eu poder te colocar como administradora da página.

**Comment by morgana-mo** [comment]
@Dovyski te adicionei

**Comment by morgana-mo** [comment]
Como a Company page foi criada podemos encerrar a issue
