### ISSUE TITLE
Migrar conta do Drive

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#351]
Eu estou com um problema, inicialmente no programa vinculei minha conta pessoal `vif.franca.alves@gmail.com`, com o passar dos meses e das tarefas desempenhada eu estourei meu limite de armazenamento no Drive, sendo assim pensei na seguinte solução, migrar todos os arquivos que adicionei pela minha conta do Drive institucional, haja visto que a conta `vinicius.franca@estudante.uffs.edu.br` é a versão coorporativa da UFFS e não tem limite de armazenamento. 

Alguém tem alguma outra sugestão ? Caso não devo fazer baixar todos os arquivos de cada issue e posteriormente adicionar novamente por meio da conta institucional.

**Comment by Dovyski** [comment]
Já haviamos discutido algo assim antes e eu acho que temos uma solução. Eu vou baixar todos os arquivos e subir eles para a minha conta (que tem mais espaço), me tornando o dono dos arquivos. Acho que isso resolve todos os problemas.

Eu acho que isso fará todos os links que temos para esses arquivos (nas issues, por exemplo) quebrarem.

**Comment by VIF-Franca** [comment]
@Dovyski Perfeito, acho que essa é uma boa solução. 

Por acaso, não daria para ser uma conta do Practice como proprietário ? A conta `practice@uffs.edu.br` que é a institucional não tem acesso ao espaço do drive ilimitado?

**Comment by Dovyski** [comment]
Não tenho conhecimento de contas de email não estudantil com acesso ao Google. Seria legal o practice ser dono da conta, mas atualmente essa conta não tem espaço.

**Comment by VIF-Franca** [comment]
belezinha

**Comment by VIF-Franca** [comment]
@Dovyski creio podemos fazer de forma periódica o download de todos os arquivos (que foram colocados pelos membros da equipe) e realizar o upload dos arquivos. 

Vejo isso como uma prevenção de possíveis entraves futuros devido ao fluxo de membros no programa. 

De fato iremos perder o link que consta nas issues, porém agora com o bot gerando as pastas automáticas será mais fácil pois a pasta será a correta .
