### ISSUE TITLE
Testar o computador do laboratório de mídias campus laranjeiras do sul 

### ISSUE THREAD

**Issue by pedroamaximowski** [practice-uffs/programa#352]
O computador já esta liberado para teste, ele ficara ligado o tempo todo.
@MaNegrao você poderia testar o computador remoto
@practice-uffs/con-midia o computador remoto já esta liberado para uso

**Comment by luizatonial** [comment]
eu posso testar @pedroamaximowski, vou fazer alguns ajustes no overlay das lives

**Comment by luizatonial** [comment]
O computador parece estar funcionando normalmente. 
Só existe a questão de que ele está com duas telas ativadas, mas no painel de opções lateral pode-se escolher qual tela está em exibição, se necessário.

Precisamos acrescentar o PIN do computador no documento com o acesso às mídias do PRACTICE.

**Comment by MaNegrao** [comment]
se quiser pode acrescentar lá @luizatonial e emseguida pode encerrar a issue

**Comment by luizatonial** [comment]
> se quiser pode acrescentar lá @luizatonial e emseguida pode encerrar a issue

só consigo visualizar o doc

**Comment by MaNegrao** [comment]
Opa, perdão, eu tinha dado permissão pra sua conta institucional. Pode alterar agora em ambas

**Comment by luizatonial** [comment]
> Opa, perdão, eu tinha dado permissão pra sua conta institucional. Pode alterar agora em ambas

desculpa não tinha percebido...

o documento de acesso às mídias foi atualizado.
