### ISSUE TITLE
Gravação Laboratório Professor Lisandro - 08/12

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#353]
Recebemos a demanda para realizar a gravação de um aula pratica no campus de Laranjeiras do Sul, como o @pedroamaximowski e eu estamos em na cidade podemos realizar. 

Data e horário sugerido: terça-feira (08/12/2020) ás 13:30 

@pedroamaximowski  tu pode esse dia e horário?

**Comment by pedroamaximowski** [comment]
Estou disponível nesse dia e horário

**Comment by VIF-Franca** [comment]
@pedroamaximowski ai tu pode limpar os cartões de memorias das câmeras por gentileza.

**Comment by VIF-Franca** [comment]
@pedroamaximowski , ficou combinado com o Prof Lisandro, terça-feira as 14h00 no laboratório de fisiologia vegetal. 

Segue o contato dele caso precise :  (42) 99926 6452

**Comment by pedroamaximowski** [comment]
Eu posso limpar os cartões de memória sim

**Comment by VIF-Franca** [comment]
Vídeos já enviado para o solicitante.
