### ISSUE TITLE
Criação de ilustrações para o manual de apoio aos estudantes

### ISSUE THREAD

**Issue by isabelirk** [practice-uffs/programa#354]
[Pasta da issue](https://drive.google.com/drive/folders/1Sk_FJyT_-6NwTWwKeshoXBuyuX-ORLCR)
Esta issue está sendo criada conforme a necessidade encontrada por mim e pela @brendaellen em relação ao acréscimo de imagens para o manual de apoio aos estudantes #314. No momento temos a sugestão de duas ilustrações que irão agregar o manual.

Da minha parte, achei interessante ilustrar o significado da sigla EPL2R do método robinson. Segue abaixo uma imagem como inspiração para a ilustração.

![metodo-robinson](https://user-images.githubusercontent.com/31291959/101095057-1b0ded80-359c-11eb-8c7e-64c730bddfec.jpg)

Da parte da @brendaellen, foi deixar que ela comente aqui na issue a sua ideia de ilustração.

Para quaisquer dúvidas estou à disposição.

**Comment by estelavilasboas** [comment]
Não estou conseguindo visualizar a imagem.  😢

**Comment by estelavilasboas** [comment]
Não estou conseguindo visualizar a imagem.  😢

**Comment by brendaellen** [comment]
@estelavilasboas , eu havia pensado em uma ilustração que relacionasse o tomate/pomodoro, com as pausas. Segue abaixo uma imagem para inspiração:

![IMAGEM POMODORO](https://user-images.githubusercontent.com/71678514/101228004-9e047600-3678-11eb-994c-d0b4d3f943ef.jpg)

**Comment by isabelirk** [comment]
Boa tarde, atualmente estou desenvolvendo o tópico sobre o quadro Kanban, e acho que é interessante fazer uma ilustração dele. Segue abaixo um exemplo do quadro kanban, a ideia é que seja bem simples, com as mesmas 3 colunas que a imagem possui.

![7d6806b0ff7384d3b27eb93e153f5336](https://user-images.githubusercontent.com/31291959/101398925-8eba3e00-38ad-11eb-8365-d422a3111658.png)

**Comment by isabelirk** [comment]
Boa tarde, vou deixar registrado uma sugestão feita na revisão do texto da issue sobre o desenvolvimento de um fichamento, mas acho que não precisa ser feito pela equipe de conteúdo. É apenas para registro, eu mesma vou providenciar ela.
"figura que ilustra a estrutura padrão de um fichamento, com o cabeçalho, referência e algumas linhas que representassem o conteúdo."

**Comment by brendaellen** [comment]
Boa tarde. Para o tópico de mapas mentais, eu achei interessante colocar o exemplo de um mapa mental que demonstrasse o que foi explicado no passo a passo e nas dicas. No passoa a passo, foi citado como exemplo o tema **GRAMÁTICA** , mas o mapa pode ser de outra temática, e não precisa necessariamente conter muitas informações, pois é apenas um exemplo. 
Caso for complexo, ou houver a necessidade de elencar muitas informações para acrescentar no mapa, eu me encarrego dessa parte.
Segue abaixo um exemplo de como poderia ser o mapa mental. Lembrando que, como no passo a passo estão as instruções para elaborar o mapa manualmente, o exemplo não precisa conter muitos elementos "tecnológicos".

![mapa ment](https://user-images.githubusercontent.com/71678514/102132527-7f4d6e80-3e32-11eb-8e16-44fc66132b86.JPG)

**Comment by morgana-mo** [comment]
Olá fiz um primeiro teste do primeiro desenho que está [aqui](https://www.figma.com/file/Pi8zSYgiG3IrjHEwYHHOKd/TESTE-1-MANUAL-DE-APOIO-AOS-ESTUDANTES?node-id=0%3A1) @isabelirk dá uma olhadinha, ainda estou me habituando com as ferramentas do design, mas acredito que o nosso trabalho ficará muito legal!

**Comment by isabelirk** [comment]
Bom dia @morgana-mo, gostei muito da sua primeira versão. Adorei a utilização das cores do PRACTICE. Acredito que as ilustrações vão ficar ótimas. Só fico em dúvida para qual lado deve ser orientado a escrita na parte de baixo. Mas acho que esses e outros detalhes podemos conversar na reunião de sexta.
Atenciosamente.

**Comment by brendaellen** [comment]
Boa tarde @morgana-mo e @TaynaraCh .
Finalizei o rascunho do infográfico sobre os métodos de estudo e seus respectivos facilitadores, e inseri [nessa pasta](https://drive.google.com/drive/u/0/folders/1Sk_FJyT_-6NwTWwKeshoXBuyuX-ORLCR)
Acrescentei algumas sugestões de modelos de mapas e infográficos, apenas para demonstrar a minha ideia inicial, mas vocês podem ficar livres para criar algo diferente, mais simples, criativo, e que combine com o restante do manual.
Uma única observação é que tanto os **métodos** quanto os **facilitadores** devem permanecer na ordem apresentada no quadro, pois esta ordem foi pensada para dar mais sentido ao infográfico ;)

**Comment by isabelirk** [comment]
Boa noite @morgana-mo @TaynaraCh,
Na mesma pasta que foi criada pela @brendaellen, fiz o rascunho do meu infográfico na planilha. Deixo livre para a estilização dele de acordo com o que fique mais harmônico com o resto do manual. Qualquer dúvida estou à disposição.
Atenciosamente.

**Comment by morgana-mo** [comment]
Olá seguem [algumas ideias](https://drive.google.com/drive/folders/1q8mFWLQHYSLpdxcPVKm4rkGd7beSBDPo),elas não estão prontas mas tratam-se de construções, preciso que vocês me digam se estou perto de vossas ideias iniciais, se pensaram de outra forma. Aguardo vossos feedbacks @practice-uffs/con-conteudo !

**Comment by isabelirk** [comment]
> 
> 
> Olá seguem [algumas ideias](https://drive.google.com/drive/folders/1q8mFWLQHYSLpdxcPVKm4rkGd7beSBDPo),elas não estão prontas mas tratam-se de construções, preciso que vocês me digam se estou perto de vossas ideias iniciais, se pensaram de outra forma. Aguardo vossos feedbacks @practice-uffs/con-conteudo !

Boa tarde, estou adorando seu trabalho. Gostei muito das suas ilustrações. Tenho alguns detalhes que poderiam ser ajustados:

- ilustração quadro kanbam: ok!
- ilustração da tecnica pomodoro: ajustar a parte escrita para que todos fiquem no mesmo sentido (igual na figura aqui do git), o relógio estar na mesma posição em todos os desenhos, o tomate que esta ao lado contrário também colocar no mesmo sentido dos outros tomates.
- ilustração EPL2R: gostei mais da versão que lê a legenda de cima para baixa (a segunda), apenas deixaria essa fonte igual a outra que voce fez (em negrito)
- banner: não consegui abrir :(

**Comment by morgana-mo** [comment]
> > Olá seguem [algumas ideias](https://drive.google.com/drive/folders/1q8mFWLQHYSLpdxcPVKm4rkGd7beSBDPo),elas não estão prontas mas tratam-se de construções, preciso que vocês me digam se estou perto de vossas ideias iniciais, se pensaram de outra forma. Aguardo vossos feedbacks @practice-uffs/con-conteudo !
> 
> Boa tarde, estou adorando seu trabalho. Gostei muito das suas ilustrações. Tenho alguns detalhes que poderiam ser ajustados:
> 
> * ilustração quadro kanbam: ok!
> * ilustração da tecnica pomodoro: ajustar a parte escrita para que todos fiquem no mesmo sentido (igual na figura aqui do git), o relógio estar na mesma posição em todos os desenhos, o tomate que esta ao lado contrário também colocar no mesmo sentido dos outros tomates.
> * ilustração EPL2R: gostei mais da versão que lê a legenda de cima para baixa (a segunda), apenas deixaria essa fonte igual a outra que voce fez (em negrito)
> * banner: não consegui abrir :(

Vou fazer as alterações e nomear elas como versão 2, obrigada Isa <3

**Comment by GessicaZanon** [comment]
> Olá seguem [algumas ideias](https://drive.google.com/drive/folders/1q8mFWLQHYSLpdxcPVKm4rkGd7beSBDPo),elas não estão prontas mas tratam-se de construções, preciso que vocês me digam se estou perto de vossas ideias iniciais, se pensaram de outra forma. Aguardo vossos feedbacks @practice-uffs/con-conteudo !

Só queria deixar registrado que as ilustrações estão ficando um mimo! Parabéns, Morgana!

**Comment by morgana-mo** [comment]
Meninas amadas do meu ❤️ olhem a pasta de entrada na versão V2!

**Comment by isabelirk** [comment]
Boa tarde, sobre as ilustrações na pasta V2:

- EPL2R: ok!
- Mapa mental: Acho q o circulo escrito "classes gramaticais" poderia ser centralizado, as setas padronizadas (deixar em um mesmo estilo), e a fonte também padronizada.
- Pomodoro: eu gostei mais da primeira opção, o arquivo "Pomodoro V2.png"

Atenciosamente

**Comment by brendaellen** [comment]
Boa noite.
Quanto ao Pomodoro, eu também gostei da primeira opção, mesmo que a diferença seja pequena em relação ao outro.
E quanto ao Mapa mental, concordo com as observações da Isa, e acredito que a cor utilizada poderia ser mais viva, tendo em vista que as cores também influenciam na eficácia desse método ;)

**Comment by morgana-mo** [comment]
Boa noite gurias 
[Aqui](https://drive.google.com/drive/folders/1oAZgz1LjmP-38XFQwV9VI_k7CbAngu4K?usp=sharing) a primeira versão dos infográficos!
Esse com os métodos e facilitadores eu tô pensando em como reformular, então ainda terão mais versões dele

**Comment by isabelirk** [comment]
> 
> 
> Boa noite gurias
> [Aqui](https://drive.google.com/drive/folders/1oAZgz1LjmP-38XFQwV9VI_k7CbAngu4K?usp=sharing) a primeira versão dos infográficos!
> Esse com os métodos e facilitadores eu tô pensando em como reformular, então ainda terão mais versões dele

Bom dia,
Parabéns pelo trabalho @morgana-mo, está incrível!! Sobre o meu infográfico, eu gostei mais da versão toda em azul "ig 5", apenas trocaria de lugar a ordem da legenda (primeiro MNM e depois OP). Em relação ao infográfico da @brendaellen eu gostei mais da versão em esquema "ig 1".
Atenciosamente.

**Comment by morgana-mo** [comment]
Boa tarde meninas!
[Aqui](https://drive.google.com/file/d/1YpUE_B7fPtBQqRc8g-CPWiPt4K0aE6vV/view?usp=sharing) as correções da última leva de ilustrações,caso eu tenha esquecido de alguma me avisem!
Assim que tiver o ok destas vou organizar tudo em uma pasta com todas as finalizadas!

**Comment by isabelirk** [comment]
> 
> 
> Boa tarde meninas!
> [Aqui](https://drive.google.com/file/d/1YpUE_B7fPtBQqRc8g-CPWiPt4K0aE6vV/view?usp=sharing) as correções da última leva de ilustrações,caso eu tenha esquecido de alguma me avisem!
> Assim que tiver o ok destas vou organizar tudo em uma pasta com todas as finalizadas!

Boa tarde,
ótimo trabalho @morgana-mo!! Sobre o infográfico ig5 está tudo perfeito. Em relação ao infográfico da @brendaellen gostei mais da versão V2.2.

PS: link correto da pasta com as novas versões: https://drive.google.com/drive/folders/1hr-dyo3W1dbcCSO60TWb5LRd2Or-J2cg

**Comment by morgana-mo** [comment]
Boa noite
Confiram [aqui](https://drive.google.com/drive/folders/1Fkl692AT-l3PdY8Q7Ndhvt8Ff7Pf3GIR?usp=sharing) se as versões finalizadas que eu coloquei na pasta estão corretas e qualquer coisa aguardo mais apontamentos e correções

**Comment by isabelirk** [comment]
> 
> 
> Boa noite
> Confiram [aqui](https://drive.google.com/drive/folders/1Fkl692AT-l3PdY8Q7Ndhvt8Ff7Pf3GIR?usp=sharing) se as versões finalizadas que eu coloquei na pasta estão corretas e qualquer coisa aguardo mais apontamentos e correções

Boa noite,
Verifiquei as ilustrações na pasta e está faltando o mapa mental e decidir qual modelo do infográfico da @brendaellen vai ser utilizado.

Atenciosamente.

**Comment by morgana-mo** [comment]
@mariagelain e @brendaellen [Aqui](https://drive.google.com/drive/folders/1uPxFI-rpU_xNepsnfLpWN6RfbITb2QAx) a versão que eu tinha feito do mapa mental e a segunda versão que fiz depois da reunião de hoje de manhã

**Comment by brendaellen** [comment]
> @mariagelain e @brendaellen [Aqui](https://drive.google.com/drive/folders/1uPxFI-rpU_xNepsnfLpWN6RfbITb2QAx) a versão que eu tinha feito do mapa mental e a segunda versão que fiz depois da reunião de hoje de manhã

Eu gostei mais da segunda versão, e também acho que contempla mais o que a Maria falou sobre formas, e etc.

**Comment by morgana-mo** [comment]
Fiz mais duas versões do pomodoro uma com uma nova cor e outra com a nova cor + um novo modelo de relógio

**Comment by morgana-mo** [comment]
Finalmente organizei as pastas dessa issue para o bem do meu TOC:
[Testes](https://drive.google.com/drive/folders/1q8mFWLQHYSLpdxcPVKm4rkGd7beSBDPo)
[Método Pomodoro](https://drive.google.com/drive/folders/1aPRfGSuVv7uZpxT7oK75YofLVWXghyh8)
[Kanban+ método Robison](https://drive.google.com/drive/folders/1Fkl692AT-l3PdY8Q7Ndhvt8Ff7Pf3GIR)
[Infográficos da @isabelirk ](https://drive.google.com/drive/folders/1dXlHfUxczFZooYmN8xSRYIMx9q7rx5re)
[Infográficos da @brendaellen ](https://drive.google.com/drive/folders/1uPxFI-rpU_xNepsnfLpWN6RfbITb2QAx)
Quando sobrar um tempinho vejam se está tudo correto e se são necessárias edições para ficar tudo certinho!

**Comment by morgana-mo** [comment]
> Boa noite,
> Eu dei uma verificada e percebi que um dos meus infográficos esta sem legenda, o "quantidade de táticas de estudos por classificação". No restante, acho que está tudo conforme o combinado.
> Atenciosamente.

Corrigido :)

**Comment by isabelirk** [comment]
> 
> 
> > Boa noite,
> > Eu dei uma verificada e percebi que um dos meus infográficos esta sem legenda, o "quantidade de táticas de estudos por classificação". No restante, acho que está tudo conforme o combinado.
> > Atenciosamente.
> 
> Corrigido :)

Onde está a versão corrigida?

**Comment by morgana-mo** [comment]
> > > Boa noite,
> > > Eu dei uma verificada e percebi que um dos meus infográficos esta sem legenda, o "quantidade de táticas de estudos por classificação". No restante, acho que está tudo conforme o combinado.
> > > Atenciosamente.
> > 
> > 
> > Corrigido :)
> 
> Onde está a versão corrigida?

[Aqui](https://drive.google.com/drive/folders/1dXlHfUxczFZooYmN8xSRYIMx9q7rx5re) :)

**Comment by isabelirk** [comment]
@morgana-mo, sobre o fichamento vou deixar um exemplo aqui na issue do que tinha pensado, qualquer dúvida estou à disposição.

![IMG_20210813_104531](https://user-images.githubusercontent.com/31291959/129367408-8afade3e-a458-4415-9d44-301eab19fcde.jpg)

**Comment by morgana-mo** [comment]
> @morgana-mo, sobre o fichamento vou deixar um exemplo aqui na issue do que tinha pensado, qualquer dúvida estou à disposição.
> 
> ![IMG_20210813_104531](https://user-images.githubusercontent.com/31291959/129367408-8afade3e-a458-4415-9d44-301eab19fcde.jpg)

[Alguns modelos](https://drive.google.com/drive/folders/1wdaXaDsRIa10Kn36SnRcivj0LAnxYwQF).
Aguardo o feedback!

**Comment by isabelirk** [comment]
Boa tarde @morgana-mo,
Gostei muito do seu trabalho com as ilustrações do fichamento. Eu amei a opção "fichamento 4". Só mudaria um pequeno detalhe: na linha abaixo da referência bibliográfica eu tiraria algumas palavras "texto" para que seja visualmente diferente da citação, talvez tirar dois "texto" dessa linha já seja o suficiente para o leitor entender que se trata de coisas diferentes. Do resto está tudo perfeito.
Atenciosamente.

**Comment by brendaellen** [comment]
Boa noite. @morgana-mo verifiquei novamente todo o material que você produziu e organizou, e não tenho nada a pontuar. Do meu ponto de vista ficou um trabalho muito bom, pois transmitiu o que havia sido proposto inicialmente. Dessa forma, acredito que questões relacionadas com as cores, formas, etc., (pelo menos quanto ao que eu solicitei) podem ser revistas e modificadas, apenas para que o conteúdo como um todo fique mais harmonioso.

**Comment by TaynaraCh** [comment]
Alguma novidade meninas? Queremos terminar a diagramação do manual até o fim do ano, mas precisamos que esteja tudo pronto.

**Comment by morgana-mo** [comment]
@isabelirk  acesso liberado agora, @brendaellen  você também pode colaborar

**Comment by morgana-mo** [comment]
@TaynaraCh o link do [Figma](https://www.figma.com/file/Pi8zSYgiG3IrjHEwYHHOKd/TESTE-1-MANUAL-DE-APOIO-AOS-ESTUDANTES?node-id=104%3A2), se puder mover para um arquivo do design, eu tenei e não consegui.

**Comment by TaynaraCh** [comment]
Transferi os arquivos, encontram-se [aqui](https://www.figma.com/file/B8LEamJaVX0QmfOiPSNKml/Manual-do-Estudante?node-id=2%3A651)

**Comment by brendaellen** [comment]
Olá meninas! Conforme solicitado, criei uma pasta contendos todos arquivos [aprovados](https://drive.google.com/drive/folders/1qfcrrhTnucX7KSglyMak20BEk07bshOd) ao longo desses meses. Entretanto, gostaria de fazer algumas observação, caso ainda seja possível modificá-los:

****Infográficos Isa**:** OK

 **Infográfico Brenda:** Percebi que o tamanho do título está bem maior do que o conteúdo presente nos círculos, portanto, sugiro modificar o tamanho dessas fontes (do título e dos textos) para que fique mais harmônico, e para facilitar a leitura dos conteúdos. Do mesmo modo, acredito que as cores também estão deixando o conteúdo um pouco apagado, então a cor do título poderia ser um pouco mais viva, e a cor dos textos dentro dos círculos, até mesmo dos próprios círculos poderia ser mais escura.

**Fichamento:** A Isa havia feito uma observação aqui nos comentários, quanto ao texto e a quantidade de palavras. Caso essa observação tenha sido atendida, o arquivo está OK.

**Mapa Mental:** OK

**Método Robinson:** OK

**Pomodoro:** Se possível, aumentar um pouquinho a fonte do texto para facilitar a leitura.

**Quadro Kanban:** OK

Me coloco a disposição para discutir a respeito de alguma modificação, ou esclarecer qualquer dúvida ;)

**Comment by morgana-mo** [comment]
Infográfico Brenda: [Aqui](https://www.figma.com/file/B8LEamJaVX0QmfOiPSNKml/Manual-do-Estudante?node-id=2%3A379),vou tentar criar mais versões, aumentei a letra dos facilitadores e diminuí a do centro
Fichamento: Já havia sido corrigido
Pomodoro: [aqui](https://www.figma.com/file/B8LEamJaVX0QmfOiPSNKml/Manual-do-Estudante?node-id=2%3A32)

**Comment by TaynaraCh** [comment]
Já que o material está concluído irei fechar a issue.
