### ISSUE TITLE
Desenvolvimento sobre o tópico do quadro Kanban

### ISSUE THREAD

**Issue by isabelirk** [practice-uffs/programa#355]
Esta issue esta relacionada com a issue #314; é uma subtarefa referente ao quadro kanban; deve ser realizado o desenvolvimento da seção 1 e 2 do manual de apoio dos estudantes deste tópico, que abrange: o que é o quadro kanban, quais são seus objetivos, como podemos utilizá-lo, como podemos introduzir ele nos estudos, e se for necessário ou interessante, trazer algum exemplo.

**Comment by isabelirk** [comment]
link da pasta no drive: https://drive.google.com/drive/folders/1QjE0W0o12php6Rc2NvqJjQmdNkoKzPWv

**Comment by GessicaZanon** [comment]
Parabéns pelo texto, Isa! Tua escrita ficou bem clara e objetiva sobre o assunto, tornando o entendimento fácil. Fiz alterações como sugestões, sendo grande parte de pontuação e algumas frases escritas de forma diferente.

**Comment by isabelirk** [comment]
Obrigada pelo retorno @GessicaZanon, os ajustes finais foram realizados. Sendo assim, está issue será finalizada.
