### ISSUE TITLE
Inclusão de postagens  específicas no calendário 

### ISSUE THREAD

**Issue by morgana-mo** [practice-uffs/programa#356]
Essa issue tem como objetivo incluir posts sobre feedbacks de clientes e  algumas postagens especiais como sendo as "visões de futuro" do PRACTICE. 
Se houverem mais postagens pontuais a serem feitas pedimos para que comentem essa issue para que sejam adicionadas ao calendário.
[Calendário de postagens](https://docs.google.com/spreadsheets/d/1zCZPvyeEfGPVRt1Q8S_JiHBQcz9-hGpw/edit#gid=1152889386)

**Comment by anacarolinamorigi** [comment]
Boa tarde!

@Dovyski poderia sanar uma dúvida referente aos feedbacks, já há algum desses finalizados ou ainda está no processo de organização? 

Questiono isso para podermos nos organizar melhor até para a realização das artes.

**Comment by Dovyski** [comment]
A @practice-uffs/ger-auxilio pode auxiliar com isso. O [formulário](https://github.com/practice-uffs/programa/issues/230) para coletar essas informações está finalizado (ou quase lá), só que ele ainda não foi coletado. Vocês podem acompanhar a aplicação desse formulário e coordenar as publicações de feedback nas redes dai.

**Comment by alessandrapedrotti** [comment]
> A @practice-uffs/ger-auxilio pode auxiliar com isso. O [formulário](https://github.com/practice-uffs/programa/issues/230) para coletar essas informações está finalizado (ou quase lá), só que ele ainda não foi coletado. Vocês podem acompanhar a aplicação desse formulário e coordenar as publicações de feedback nas redes dai.

@VIF-Franca pode fornecer mais informações sobre o asunto.

**Comment by VIF-Franca** [comment]
Sobre a pesquisa de satisfação com os clientes, creio que podemos rodar a pesquisa referente ao ano de 2020 em janeiro juntamente com o retorno de todos os servidores. 

Acho que teremos bons dados e lapidados em fevereiro.

**Comment by VIF-Franca** [comment]
Teria algumas ideias de posts.... 

Os Clássicos: 

- Missão
- Visão 
- Valores 
- Organograma interno

Creio que a "moda" é usar os _reels_ no Instagram, aqueles vídeos de 15 ou 30 segundos, sendo assim dou algumas ideias de _reels_:

- um para cada aba do site (https://practice.uffs.cc/), sobre, serviços, recursos, parcerias, contato. Uma duvida sobre, talvez os serviços pode ser separado por nicho;
- colocar o vídeo que foi gravado no _app_ no _feed_; 
- seria legal criar um mini vídeo com os membros de cada equipe, por exemplo a _con-midia_ tem a ilha de _lives_, os integrantes que fazem _lives_ fazer cada um falando uma frase buscando contemplar a ideia de "oi somos quem vai te ajudar nas _lives_";
- criar um _reels_ ou um _igtv_ com a abertura de alguma _live_, demonstrando é ISSO que você terá ao solicitar uma demanda de live com o PRACTICE, tens algumas legais com o o reitor. 
- pensar em _reels_ que ilustre as edições de vídeos e áudios; 
- fazer um _reels_ para cada cartilha e manual já criado abrindo o conteúdos deles;


*havia deixado algumas ideias na issue #242

**Comment by morgana-mo** [comment]
> Teria algumas ideias de posts....
> 
> Os Clássicos:
> 
> * Missão
> * Visão
> * Valores
> * Organograma interno
> 
> Creio que a "moda" é usar os _reels_ no Instagram, aqueles vídeos de 15 ou 30 segundos, sendo assim dou algumas ideias de _reels_:
> 
> * um para cada aba do site (https://practice.uffs.cc/), sobre, serviços, recursos, parcerias, contato. Uma duvida sobre, talvez os serviços pode ser separado por nicho;
> * colocar o vídeo que foi gravado no _app_ no _feed_;
> * seria legal criar um mini vídeo com os membros de cada equipe, por exemplo a _con-midia_ tem a ilha de _lives_, os integrantes que fazem _lives_ fazer cada um falando uma frase buscando contemplar a ideia de "oi somos quem vai te ajudar nas _lives_";
> * criar um _reels_ ou um _igtv_ com a abertura de alguma _live_, demonstrando é ISSO que você terá ao solicitar uma demanda de live com o PRACTICE, tens algumas legais com o o reitor.
> * pensar em _reels_ que ilustre as edições de vídeos e áudios;
> * fazer um _reels_ para cada cartilha e manual já criado abrindo o conteúdos deles;
> 
> *havia deixado algumas ideias na issue #242

Lendo teu comentário pensei assim:
 
- Postagens mais clássicas seriam uma boa pedida para o aniversário de 1 ano do programa (dá pra fazer uma série na semana, postar todos os dias algo nesse estilo, creio que até as visões de futuro cabem aqui;
- As abas do site poderiam ser em um IGTV;
- Vou adicionar o vídeo do app a lista para ser postado em janeiro ou fvereiro;
- As cartilhas terão os vídeos que estão sendo produzidos pelo mídia, em sua maioria elas não ultrapassam 5 minutos, pensei em colocar no IGTV esses vídeos, mas a idéia dos reels também pode ser aprimorada;
- Sobre as lives vou adicionar nas coisas a fazer em 2021.

**Comment by morgana-mo** [comment]
Ideias adicionadas a planilha de organização para criação #374

**Comment by morgana-mo** [comment]
Closed #356
