### ISSUE TITLE
Desenvolvimento sobre o tópico de planejamento e calendário com prioridades

### ISSUE THREAD

**Issue by brendaellen** [practice-uffs/programa#357]
Esta issue esta relacionada com a issue #314; é uma subtarefa referente a criação de um planejamento e de um calendário com prioridades; deve ser realizado o desenvolvimento da seção 1 e 2 do manual de apoio dos estudantes deste tópico, que abrange: o que é um planejamento, como relaciona-se com o calendário, quais são seus objetivos, como podemos utilizá-lo, como podemos introduzir ele nos estudos, e se for necessário ou interessante, trazer algum exemplo.

**Comment by brendaellen** [comment]
Link da pasta: https://drive.google.com/drive/folders/1DYYEitTxSbplX6uYcQAm3EAHHdN7hHD7

**Comment by GessicaZanon** [comment]
Brenda, parabéns pelo teu texto. Tua linguagem ficou bem objetiva e de fácil entendimento. Como pode perceber, o que mais sugeri como alteração foi em relação a pontuação e mais especificamente as vírgulas, para que o texto fique um pouco mais fluido na hora da leitura, pois inevitavelmente o leitor faz uma pausa quando se depara com uma vírgula e isso pode quebrar a ideia do que tu queres passar para o leitor. Eu tenho mania de colocar muita vírgula quando escrevo e é difícil autocorrigir-se, entretanto, é mais fácil perceber quando é um texto de outra pessoa. Ademais, teu texto está ótimo e espero que as sugestões que deixei sejam do teu agrado e te ajudem :)

**Comment by GessicaZanon** [comment]
Brenda, parabéns pelo teu texto. Tua linguagem ficou bem objetiva e de fácil entendimento. Deixei todas as possíveis alterações como sugestões. Espero que sejam do teu agrado e te ajudem :)

**Comment by brendaellen** [comment]
Muito obrigada pelas observações @GessicaZanon, ajudaram bastante :) 
Com as alterações feitas, acredito que a issue pode ser fechada.
