### ISSUE TITLE
Cards para datas comemorativas - Natal e Ano novo

### ISSUE THREAD

**Issue by anacarolinamorigi** [practice-uffs/programa#358]
Boa tarde!

Issue criada para o desenvolvimento das artes dos cards para o Natal e Ano Novo do PRACTICE.

**Comment by anacarolinamorigi** [comment]
Boa noite!

[Aqui](https://drive.google.com/drive/folders/15GExbV5iA91B2bC9v-NSEfDkn6fGzcme?usp=sharing) encontram-se as ideias para os cards de Natal. A ideia foi desenvolvida em três artes que, são uma sequência, para além de desejar boas festas serve também para mostrar as pessoas envolvidas no programa.

**Comment by morgana-mo** [comment]
Olá
[aqui](https://drive.google.com/drive/folders/1Wxy7GJjFofX0LsNabqFHhxcQmyiipmE9) se encontram as ideias para o post de ano novo, ressalto que há uma sugestão de composição (que na minha opinião fica mais agradável aos olhos) e uma opção de post único. Fico no aguardo do retorno!

**Comment by VIF-Franca** [comment]
Adorei a arte, poderíamos adaptar um modelo para enviar no e-mail dos nossos clientes ? creio ser bacana.

**Comment by anacarolinamorigi** [comment]
> Adorei a arte, poderíamos adaptar um modelo para enviar no e-mail dos nossos clientes, desejando boas energias ? creio ser bacana. 

Claro! Achei muito boa a ideia, assim que finalizar essa arte envio aqui!

**Comment by anacarolinamorigi** [comment]
Boa noite!

[Aqui ](https://drive.google.com/drive/folders/1mt5RPBfA25Hx35g9pL5vfbjZuJexXesY?usp=sharing) encontra-se o modelo de card para envio aos clientes do programa.

Fico no aguardo da avaliação de vocês!

**Comment by VIF-Franca** [comment]
show!!!

**Comment by Dovyski** [comment]
@anacarolinamorigi a mensagem está ótima, mas a cor da parte de cima não ficou tão legal. Acho que tu pode usar branco ou azul claro como cor de fundo da parte de cima, quem sabe?

**Comment by anacarolinamorigi** [comment]
> @anacarolinamorigi a mensagem está ótima, mas a cor da parte de cima não ficou tão legal. Acho que tu pode usar branco ou azul claro como cor de fundo da parte de cima, quem sabe?

Farei essas alterações e logo mais disponibilizo para vocês! Muito obrigada pelo feedback!

**Comment by anacarolinamorigi** [comment]
Alterações feitas, elas se encontram `[aqui ](https://drive.google.com/drive/folders/1mt5RPBfA25Hx35g9pL5vfbjZuJexXesY?usp=sharing)`. Aguardo novo feedback!

**Comment by Dovyski** [comment]
Obrigado, @anacarolinamorigi ficaram ótimas! Eu gostei mais da opção 2, mas a 3 a 4 também estão ótimas. Sintam-se livres para escolher entre elas 😉
