### ISSUE TITLE
Desenvolvimento sobre o tópico de fichamento

### ISSUE THREAD

**Issue by isabelirk** [practice-uffs/programa#359]
Esta issue esta relacionada com a issue #314 ; é uma subtarefa referente ao fichamento; deve ser realizado o desenvolvimento da seção 1 e 2 do manual de apoio dos estudantes deste tópico, que abrange: o que é o fichamento, quais são seus objetivos, como podemos utilizá-lo, como podemos introduzir ele nos estudos, e se for necessário ou interessante, trazer algum exemplo.

**Comment by isabelirk** [comment]
link da pasta: https://drive.google.com/drive/folders/1uSh4q0zn3LpO7-iTeU5EUCtMBYLnHLHc

**Comment by thaliafriedrich** [comment]
Muito bom o seu texto! Tem linguagem adequada e é fácil de entender. 
Fiz algumas modificações, correções e um comentário.

**Comment by isabelirk** [comment]
Boa tarde, conforme o comentário da @thaliafriedrich, foram realizados os ajustes finais no texto. Sendo assim, está issue esta sendo finalizada.
Atenciosamente.
