### ISSUE TITLE
Aprender github.

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#36]
Isso é para aprender isso porque é bem legal e fica lindo no meu currículo.

cc: @lcaimi dá uma olha aqui e diz se está ok.

**Comment by lcaimi** [comment]
> Isso é para aprender isso porque é bem legal e fica lindo no meu currículo.
> 
> cc: @lcaimi dá uma olha aqui e diz se está ok.

Sim, está ótimo.

**Comment by andrewmsilva** [comment]
Okay, estou a aprender

**Comment by CleissonVieira** [comment]
> Okay, estou a aprender

Aprendido com sucesso

**Comment by Dovyski** [comment]
- [ ] Refinar o texto 
- [ ] A imagem do cabeçalho não ficou boa, tem refazer.
- [ ] Não consegui ver a imagem 14.

**Comment by andrewmsilva** [comment]
Agora deu bom, pessoal
