### ISSUE TITLE
Ajustes no overlay para lives do PRACTICE

### ISSUE THREAD

**Issue by luizatonial** [practice-uffs/programa#360]
A fim de prosseguirmos com a padronização das lives (issue #343) precisamos finalizar os ajustes em relação ao overlay de lives que ficaram abertos na issue #287.

 
Seguem alguns detalhes que ficaram em aberto:
- ajustes/padronização no tamanho e alinhamento das bordas
- finalização da tela de apresentação de slides na versão com a imagem principal menor (formato 4:3) - acredito que haviam sido feitas duas versões, precisamos definir qual/como vamos utilizar
- criação de uma tela de créditos, no mesmo padrão, mas com um espaço adicional para quem está fazendo a mediação do evento
- criação de uma tela de intervalo para as lives - talvez com "voltamos em breve" ou algo do tipo (pode ser bem similar à tela inicial, só trocando a frase)
- disponibilização dos arquivos "brutos" e editáveis, para que o pessoal do mídia possa verificar a padronização no OBS e realizar pequenos ajustes, conforme o andamento da live, os quais não interferem nas questões de design

@practice-uffs/con-midia comentem se tiverem alguma outra demanda ou contribuição.

**Comment by MaNegrao** [comment]
@ricardopatrik Chegou a dar uma olhada na tarefa? Eu queria fazer um pedido. 
Se for possivel, coloca um zip ou uma pasta dentro da pasta dessa tarefa aqui os arquivos de projeto que tu usou, para nós do mídia podermos usar também, fico agradecio!

**Comment by estelavilasboas** [comment]
@ricardopatrik Favor colocar os editáveis das versões do overlay trabalhadas nas issues anteriores na [pasta da issue Editáveis](https://drive.google.com/drive/folders/1TRG7gLLxQxfGg1jfuFOYZHmCjZ4gWRRN).

**Comment by alessandrapedrotti** [comment]
Precisamos realocar essa tarefa para um novo responsável. @MaNegrao é possível que alguém da con-mídia a assuma?

**Comment by MaNegrao** [comment]
@luizatonial você pode assumir, creio que tu vai fazer um trabalho maravilhoso

**Comment by luizatonial** [comment]
se puderem dar uma olhada no trabalho já realizado anteriormente e tiverem sugestões para mudanças/ajustes no overlay peço que deixem aqui 😉😉 @practice-uffs/con-midia

**Comment by MaNegrao** [comment]
# Eu tenho algumas sugestões:

## De ajustes:

Acho que no geral é interessante simplificar o overlay, como dar uma clareada e remover o "efeito vinheta" que ele tem atualmente. 
Vejo que é legal também deixar a marca d'agua que está atrás mais transparente e como uma marca d'agua de fato e não só uma imagem lá. 
Na questão das legendas dos nomes dos participantes, podemos utilizar a proporção aurea entre nome e titulação, etc. Pode ser interessante aumentar a area pra que a proporção se encaixe melhor. 

## De novas telas:

Criar fundos para telas divididas, como dois, três e quatro imagens do mesmo tamanho juntas (como tu fez no overlay da formatura). 
(talvez) refazer a tela de creditos, acho que as letras em ítalico não tão casando muito bem com o overlay como um todo, deixar ela mais clean. O mesmo vale para tela de espera. 

## Chat.

Definir um padrão para o tamanho do chat e como ele vai aparecer, há varias maneiras de personalizar as mensagens do chat no streamlabs, podendo utilizar CSS, eu vou por conta dar uma procurada e ver como faz e como ficaria melhor no nosso caso. 


Acho que é isso, se eu pensar em mais eu comento aqui hahah

**Comment by robisonjose** [comment]
Por enquanto minhas únicas sugestões são sobre o chat, mas falei disso na issue #343. 

Vou dando mais sugestões conforme as coisas forem andando e se eu pensar em algo.

**Comment by MaNegrao** [comment]
Outro ponto que comentamos é a criação de telas onde não há o chat, então as telas que temos que atualmente tem o chat podemos tirar e reorganizar, dai fica ao teu critério não me vem nada na cabeça haha. 

Outra coisa para outra issue é o overlay generio que podemos disponibilizar, nesse caso pode ser um trabalho em conjunto com outra equipe, ou total de outra equipe, com nossa ajuda apenas técnica criativa

**Comment by luizatonial** [comment]
estou FINALMENTE conseguindo retomar essa issue, vou fazer alguns testes essa semana e abro uma nova em seguida com todos os pontos necessários.
