### ISSUE TITLE
Desenvolvimento sobre o topico da utilização de mnemônica

### ISSUE THREAD

**Issue by isabelirk** [practice-uffs/programa#361]
Esta issue esta relacionada com a issue #314 ; é uma subtarefa referente ao mnemônica; deve ser realizado o desenvolvimento da seção 1 e 2 do manual de apoio dos estudantes deste tópico, que abrange: o que é o mnemônica, quais são seus objetivos, como podemos utilizá-lo, como podemos introduzir ele nos estudos, e se for necessário ou interessante, trazer algum exemplo.

**Comment by isabelirk** [comment]
link da pasta no drive: https://drive.google.com/drive/folders/1XjuPvwahb9FWisigkuQnY_z1rV1c8mCq

**Comment by alessandrapedrotti** [comment]
Texto revisado. Deixei um comentário no doc em uma parte que precisará ser reescrita pra que fique clara para o leitor.

**Comment by isabelirk** [comment]
Boa tarde. Foram realizados os ajustes solicitados. Sendo assim está issue esta sendo finalizada.
Atenciosamente.
