### ISSUE TITLE
Formação - método de correção

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#362]
Essa issue serva para passar as informações sobre a formação do grupo de líderes e coordenadores envolvidos na correção da avaliação de produtividade dos bolsistas do programa.

Penso em fazermos a formação na sexta-feira (18/12/2020), via webex, para os que puderem participar no horário das 19h. Aos que não puderem participar, deixaremos a formação gravada para assistirem depois.

Vou precisar da ajuda de alguém do mídia (penso que pode ser o França ou o Matheus) para controlar a gravação da formação.

@practice-uffs/lideres @practice-uffs/ger

**Comment by VIF-Franca** [comment]
@alessandrapedrotti creio que posso realizar a gravação,

**Comment by alessandrapedrotti** [comment]
> @alessandrapedrotti creio que posso realizar a gravação,

Certo, sexta-feira então fazemos igual a formação de texto. Muito obrigada.

**Comment by alessandrapedrotti** [comment]
A tabela com as sugestões de corretores por equipe pode ser encontrada [nesta pasta](https://drive.google.com/drive/folders/18lgRIbgaCUKZmpe487Nz8VWOLUtlp50k).

**Comment by alessandrapedrotti** [comment]
Foram adicionados, conforme solicitado, dois tópicos nos materiais desenvolvidos para a correção. Um no método de correção (mais especificamente no conjunto de cores e símbolos que será utilizado) e outro na tabela de responsáveis por correção (referente aos relatórios dos coordenadores).

Os dois materiais serão movidos para a pasta AVALIAÇÃO para serem mais facilmente acessados.

**Comment by VIF-Franca** [comment]
[Link da gravação](https://drive.google.com/file/d/1Mk1pbKnJp9vaPnevV4-bS3zoHis1-4wq/view?usp=sharing)
