### ISSUE TITLE
Desenvolvimento sobre o tópico do mapa mental

### ISSUE THREAD

**Issue by brendaellen** [practice-uffs/programa#363]
Esta issue esta relacionada com a issue #314; é uma subtarefa referente a utilização do mapa mental; deve ser realizado o desenvolvimento da seção 1 e 2 do manual de apoio dos estudantes deste tópico, que abrange: o que é um mapa mental, quais são seus objetivos, como podemos utilizá-lo, como podemos introduzir ele nos estudos, e se for necessário ou interessante, trazer algum exemplo.

**Comment by brendaellen** [comment]
Link da pasta: https://drive.google.com/drive/folders/11EiqXqK9e5AzPvPPI9fhi_29Wuq7stVi

**Comment by brendaellen** [comment]
A primeira versão do texto encontra-se [nessa pasta.](https://drive.google.com/drive/folders/11EiqXqK9e5AzPvPPI9fhi_29Wuq7stVi)
@thaliafriedrich pode fazer a revisão textual, por gentileza.

**Comment by thaliafriedrich** [comment]
Muito bom o seu texto. Foi bem explicado como elaborar um mapa mental e como utilizá-lo. As dicas também ficaram bem legais como complemento. 
Fiz as correções e alterei algumas palavras.

**Comment by brendaellen** [comment]
Muito obrigada pelas correções @thaliafriedrich :) 
Sendo assim, acredito que essa issue já pode ser fechada.
