### ISSUE TITLE
Desenvolvimento sobre o tópico de testes práticos

### ISSUE THREAD

**Issue by brendaellen** [practice-uffs/programa#364]
Esta issue esta relacionada com a issue #314; é uma subtarefa referente a utilização de testes práticos; deve ser realizado o desenvolvimento da seção 1 e 2 do manual de apoio dos estudantes deste tópico, que abrange: o que são os testes práticos, quais são seus objetivos, como podemos utilizá-los, como podemos introduzir eles nos estudos, e se for necessário ou interessante, trazer algum exemplo.

**Comment by brendaellen** [comment]
Link da pasta: https://drive.google.com/drive/folders/1zqxTm8_JHTmnP0cCkpw2TzNpC6rPe9L_

**Comment by brendaellen** [comment]
Tópico finalizado, aguardando revisão.

**Comment by alessandrapedrotti** [comment]
Primeira leitura de revisão feita. Adicionei dois comentários ao documento que precisam ser resolvidos pela redatora.

No geral, o texto ficou muito bom, tive apenas que organizar o parágrafo inicial e arrumar algumas vírgulas ao longo do texto.

**Comment by brendaellen** [comment]
Muito obrigada @alessandrapedrotti . Fiz as alterações conforme sugerido nos comentários, e gostaria por gentileza que você verficasse se está tudo certo.

**Comment by alessandrapedrotti** [comment]
Deixei um comentário nas notas de rodapé.

Salvo isso, o texto está aprovado. Depois da adição sugerida, o texto não precisa passar por mais uma revisão e a issue já poderá ser fechada;

**Comment by brendaellen** [comment]
Realizei a alteração sugerida, sendo assim, essa issue já pode ser fechada.
