### ISSUE TITLE
Desenvolvimento sobre o topico "Texto com dicas bônus sobre a seção 1"

### ISSUE THREAD

**Issue by isabelirk** [practice-uffs/programa#365]
Esta issue esta relacionada com a issue #314 ; é uma subtarefa referente ao Texto com dicas bônus sobre a seção 1; deve ser realizado o desenvolvimento da seção 1 e 2 do manual de apoio dos estudantes deste tópico, que abrange: o que é, quais são seus objetivos, como podemos utilizá-lo, como podemos introduzir ele nos estudos, e se for necessário ou interessante, trazer algum exemplo.

**Comment by isabelirk** [comment]
link da pasta no drive: https://drive.google.com/drive/folders/1uZbtY9T-97gbeeDzISGYMmsjAmUNoyM2

**Comment by isabelirk** [comment]
Parcialmente finalizado, apenas faltou o item referente a sprint literária onde necessito da ajuda da @alessandrapedrotti

**Comment by alessandrapedrotti** [comment]
Encontrei essa explicação que achei bem legal:
"Sprint: (de leitura) traduzido como “período curto de atividade intensa”, um sprint de leitura é um momento de foco. Nada de prestar atenção na novela da tv ligada, nada de conversar com a mãe, nada de olhar o WhatsApp. Um sprint de leitura é um período de tempo determinado (você pode decidir se vão ser 15min, meia hora, uma hora inteira) em que você não faz mais nada a não ser ler.
Geralmente os sprints são utilizados em maratonas literárias. O organizador avisa o começo do sprint, todos fazem a leitura coletiva (cada um na sua casa) e depois do término do sprint ficam online novamente para falar quantas páginas leram naquele período de tempo e compartilhar suas impressões.
Nada te impede de fazer pequenos sprints de leitura durante o dia, mesmo sem participar de uma maratona. O médico cancelou a consulta e você já tinha saído de casa? É só sentar em um café e fazer um sprint de leitura de x minutos. Está no transporte público e pegou trânsito? Faz um sprint de leitura. O que importa é que você se esforce ao máximo para se “desligar” do mundo externo e render na leitura."

Retirada do site: https://medium.com/@tamiresromano/g%C3%ADrias-do-universo-liter%C3%A1rio-53ab69b41ef3

Estou buscando mais materiais a respeito, Atualizarei essa issue no decorrer da semana.

**Comment by isabelirk** [comment]
Boa tarde, o tópico sobre sprint literária foi realizado. Assim, o texto está finalizado aguardando revisão.
Atenciosamente.

**Comment by alessandrapedrotti** [comment]
Primeira leitura de revisão feita. Deixei um comentário no documento para a redatora resolver.

**Comment by isabelirk** [comment]
Boa tarde, ajustes finalizados.
Atenciosamente.

**Comment by isabelirk** [comment]
Conforme o retorno da @alessandrapedrotti esta issue esta sendo finalizada.
