### ISSUE TITLE
Criação de Identidade Visual - Programa de Pós-graduação em Estudos Linguísticos (PPGEL) 

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#366]
A professora adjunta Ani do campus Chapecó, solicitou uma logo para o Programa de Pós-graduação em Estudos Linguísticos: 

> Não precisa ser uma logo com desenho, poderia ser apenas o nome do programa e a sigla mais estilizados. 
> Queremos utilizar essa logo na página do PPGEL e nas redes sociais. O PPGEL terá o curso de doutorado ano que vem (2021) e queremos dar um upgrade nas páginas do programa.
> Dá para olhar o PPGL (UFSC), PPGL (UFRN), PPGL (UERN) nas redes sociais para ter uma ideia do que estamos querendo.

Já foi avisado à solicitante sobre a espera para 2021 e a mesma concordou.

Ani Carla Marchesan (Siape 1729810) - Professora Adjunta - Universidade Federal da Fronteira Sul (UFFS) - Campus Chapecó
E-mail: animarchesan@uffs.edu.br

[Pasta da issue](https://drive.google.com/drive/folders/1K7v7NgzeQFl6ag-zQFsNt6MKLbnEwvLv)

**Comment by ricardopatrik** [comment]
onde encontro o questionário respondido pela solicitante?

**Comment by VIF-Franca** [comment]
Ainda aguardando a resposta do questionário...

**Comment by VIF-Franca** [comment]
@ricardopatrik já está disponível a resposta do formulário.

**Comment by ricardopatrik** [comment]
França, vc criou a pasta no drive com o questionario? Pois nao to achando, da 365 vai para a 368

**Comment by VIF-Franca** [comment]
Ricardo, as respostas do vai o formulário não é criado pasta com as respostas dos formulários. 

Neste link você pode encontrar as respostas : https://forms.gle/fZT2oPBRAKF9aUgE7

**Comment by estelavilasboas** [comment]
As respostas do formulário já estão em pdf na [pasta Entrada](https://drive.google.com/drive/folders/1ovv1DRFhtGLbL5sGK6nCddcBFEmizGyt).

Lembrando que esta demanda será atendida após o período de atendimento de demandas internas. Enquanto isso, a demanda estará na fila de espera.

**Comment by alessandrapedrotti** [comment]
@estelavilasboas e @TaynaraCh conforme conversamos, essa tarefa recebeu prioridade na fila de serviços, portanto deve ser começada logo.

**Comment by TaynaraCh** [comment]
Coloquei na pasta chamada Primeiro envio o arquivo em [pdf](https://drive.google.com/drive/folders/1R_6G-Ph9Ay5yxjbmSVVcLxeDFSbIJF2g) para ser enviado, também está na pasta as imagens em png. 
No pdf já está a descrição sobre as artes elaboradas. Acredito que seja isso, @VIF-Franca , pode enviar!

**Comment by TaynaraCh** [comment]
Os editáveis estão [aqui](https://www.figma.com/file/DPSeqOK74ZQiF2ryA4DXat/PPGEL?node-id=1%3A35), no Figma, ainda estou vendo como faço para deixar que outras pessoas editem, mas acredito que aconteça apenas se eu adicionar o e-mail da pessoa. 
De qualquer forma, salvei em SVG e adicionei os arquivos dentro de uma pasta chamada [editáveis](https://drive.google.com/drive/folders/10vbX6Fd3h8g4aWOJ4SmDcMtYy3rpoBnt), ainda dentro da Primeiro envio.

**Comment by TaynaraCh** [comment]
@VIF-Franca, nada do feedback?

**Comment by morgana-mo** [comment]
@mariagelain pode dar uma conferida no email?

**Comment by mariagelain** [comment]
O email com as primeiras versões foram enviadas!

**Comment by mariagelain** [comment]
### Feedback

> Escolhemos a opção 1,  mas queríamos pedir duas coisas:
> 
> 1º) É possível termos essa logo e mais uma igual, mas com o nome por extenso logo abaixo da sigla (Programa de Pós-Graduação em Estudos Linguísticos)?
> 2º) Como essa logo será utilizada não apenas nos documentos da UFFS, mas nas redes sociais; queríamos ver se é possível alterarmos a cor dela.
> Por exemplo, quando for setembro, queríamos deixar tudo em amarelo (em homenagem ao setembro amarelo); quando for dezembro, tudo em vermelho (como uma referência ao Natal); em outubro em rosa; etc. Usaríamos o verde como a cor oficial e, as outras cores, para marcar determinados períodos do ano.
> 
> Será que é possível termos essas opções?

**Comment by TaynaraCh** [comment]
As alterações podem ser feitas sim! Irei iniciar já.

**Comment by TaynaraCh** [comment]
Alterações concluídas , os arquivos estão na pasta de [saída,](https://drive.google.com/drive/folders/1Dobi_DgGIhwR4PfzFtkxp7I78UrQ1HG3) são pngs e o pdf com a descrição. O arquivo editável encontra-se na pasta da issue. Pode enviar @mariagelain.

**Comment by mariagelain** [comment]
Os arquivos foram enviados a solicitante!

**Comment by mariagelain** [comment]
A versão final da identidade visual foi aprovada pela solicitante.
