### ISSUE TITLE
Identidade Visual Complexa - Grupo Formação de Professores de Ciências - Realeza

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#367]
A solicitante pediu a criação de uma identidade visual complexa com símbolo, logotipo, paleta de cores, marca d'água e padronagem. 

Solicitante: Barbara Grace Tobaldini de Lima 
E-mail: barbara.lima@uffs.edu.br

[Pasta no drive](https://drive.google.com/drive/folders/1Ia7gIeBB92Eouf7SPEJnbplSsPmrmLI6)

**Comment by ricardopatrik** [comment]
onde encontro o questionário respondido pela solicitante?

**Comment by VIF-Franca** [comment]
Aguardando a demandante responder o novo questionário.

**Comment by VIF-Franca** [comment]
O formulário já foi respondido.

**Comment by estelavilasboas** [comment]
Versão em pdf do formulário já está na [pasta Entrada](https://drive.google.com/drive/folders/1LHLKdpsL14x0A_tOeL7jJYXF4xjNrKgn).

Lembrando que esta demanda será atendida após o período de atendimento de demandas internas. Enquanto isso, estará na fila de espera.

**Comment by TaynaraCh** [comment]
Os arquivos estão prontos para serem enviados! Na pasta de [saída](https://drive.google.com/drive/folders/1ipgIT2353vaPki15xf_WHJXAq-wnzHJP) estão, os arquivos em png, as versões editáveis, o pdf com as descrição das logos e também o doc editável.
O envio deve ser apenas das imagens em png e do pdf.
@VIF-Franca ou @mariagelain, podem enviar!

**Comment by mariagelain** [comment]
Email enviado!

**Comment by TaynaraCh** [comment]
As alterações podem ser feitas e já vou iniciar!

**Comment by TaynaraCh** [comment]
Alterações concluídas, na pasta de [saída](https://drive.google.com/drive/folders/1ipgIT2353vaPki15xf_WHJXAq-wnzHJP) estão pngs e pdf com a descrição. Na pasta da issue também está o arquivo editável. Pode enviar, @mariagelain!

**Comment by Dovyski** [comment]
Que coisa mais maravilhosa esse logo! 🎈❤️😍 Parabéns!

**Comment by mariagelain** [comment]
Email enviado!

**Comment by TaynaraCh** [comment]
Solicitante não ternou mais, como todos os arquivos foram já entregues irei fechar a issue, caso retorne com a necessidade de alguma complementação irei reabri-la.
