### ISSUE TITLE
Live Formatura Curso de Agronomia do Campus Erechim - 22/12 às 18h 

### ISSUE THREAD

**Issue by luizatonial** [practice-uffs/programa#368]
**Evento de Formatura do Curso de Agronomia do Campus Erechim**
**Data:** 22/12/2020, terça
**Horário:** 18h
**Transmissão:** pelo UFFS Ao Vivo no Facebook

@MaNegrao não sei se existe um roteiro, mas tomei a liberdade de criar a issue como já estou trabalhando nela.

**Comment by luizatonial** [comment]
Os solicitantes optaram por não utilizar o overlay do PRACTICE para a transmissão, devido à formalidade do evento. Portanto, criei uma tela de fundo e possíveis opções de configurações de câmera para serem utilizadas na transmissão, conforme as orientações recebidas. 

Serão realizados ensaios no dia 18 e 21, onde poderei verificar se o template está adequado para o evento.
[Pasta Drive](https://drive.google.com/drive/u/1/folders/1AQd6JCGN47iApSBUTeqqbnSPB2KsdOIh)

**Comment by MaNegrao** [comment]
Claro, tem que ter liberdade sim. perfeito! Eu vou pegar o roteiro e anexo aqui na issues

**Comment by MaNegrao** [comment]
@luizatonial Conversei com a solicitante e ela me disse que o roteiro e o protocolo estão em fase de finalização e irão te enviar quando finalizado. Tu pode conversar e quando enviarem colocar na pasta da issue :D

**Comment by luizatonial** [comment]
recebi uma versão inicial da cerimônia e teremos novas [reuniões ](https://uffs.webex.com/meet/coord.acad.er)para testes.

**Comment by luizatonial** [comment]
nossa primeira live de formatura realizada com sucesso! disponível no link: https://www.facebook.com/uffsaovivo/videos/143466823982907
