### ISSUE TITLE
Mapeamento e organização dos vídeos externos produzidos pelo programa

### ISSUE THREAD

**Issue by MilenaPaz2020** [practice-uffs/programa#370]
O objetivo dessa issue é organizar os vídeos externos já produzidos pelo programa, semelhante ao que foi feito com os vídeos internos na issue #344.

Havendo sugestões, favor comentar. :D 

[Pasta Drive](https://drive.google.com/drive/u/0/folders/15sR888GjfAFwQk9ZUAryuDMbDv2YS5Dt)

**Comment by vini2reis** [comment]
Uma dúvida
A planilha é para ser preenchida com os vídeos que já foram concluídos?

**Comment by MilenaPaz2020** [comment]
> Uma dúvida
> A planilha é para ser preenchida com os vídeos que já foram concluídos?

Bom dia! Os novos vídeos que estão entrando em produção também serão acrescentados na tabela.

**Comment by vini2reis** [comment]
Completei a tabela com os vídeos que faltavam.
Acho que coloquei todos...

**Comment by MilenaPaz2020** [comment]
Pessoal, creio que todos os vídeos foram mapeados e as novas demandas estão sendo acrescentadas na tabela. 

Mantive essa issue aberta para que os membros da equipe que estavam em recesso também fizessem sugestões. Então, assim que possível, comentem se algo precisa ser alterado ou acrescentado. 

E por gentileza, me apontem em que pasta essa planilha deve ser anexada.

**Comment by MaNegrao** [comment]
@MilenaPaz2020 e @vini2reis parabéns pela eficiente organização, na minha visão está tudo ok, só precisamos mover essa planilha para um lugar acessivel, como a pasta de materiais ou a pasta do próprio mídia (fica a critério de vocês).

**Comment by MilenaPaz2020** [comment]
> @MilenaPaz2020 e @vini2reis parabéns pela eficiente organização, na minha visão está tudo ok, só precisamos mover essa planilha para um lugar acessível, como a pasta de materiais ou a pasta do próprio mídia (fica a critério de vocês).

Não consigo mover a planilha para essas pastas, não tenho permissão para editá-las.

**Comment by MaNegrao** [comment]
Alterei lá e agora tu tem permissão :D

**Comment by MilenaPaz2020** [comment]
A planilha foi movida para a pasta: [Mapeamentos de vídeos produzidos](https://drive.google.com/drive/u/0/folders/1VcmKBMSxMSzJ3ZtnezOktPdMNhj_qm75), uma subpasta de Materiais. Aproveitei e fiz o mesmo com a planilha da issue #344.

Caso julguem necessário alterar o local de armazenamentos dessas planilhas, fiquem a vontade para fazê-lo.
