### ISSUE TITLE
Desenvolvimento sobre o tópico "Facilitador: responde aí"

### ISSUE THREAD

**Issue by isabelirk** [practice-uffs/programa#371]
Esta issue esta relacionada com a issue #314 ; é uma subtarefa referente ao facilitador do app e site "Responde aí"; deve ser realizado o desenvolvimento referente a seção 3 do manual de apoio dos estudantes deste tópico, que abrange: o que é, quais são seus objetivos, como podemos utilizá-lo, vantagens e desvantagens. Caso seja interessante ou necessário, a inclusão de imagens do mesmo.

**Comment by isabelirk** [comment]
link da pasta no drive: https://drive.google.com/drive/folders/1j1gWyTmQyhHpYeQG-9kk_NA841ArPvGQ

**Comment by isabelirk** [comment]
Texto finalizado aguardando revisão.

**Comment by alessandrapedrotti** [comment]
Gostei muito do texto, minha única sugestão é adicionar mais um parágrafo ao final, para encerrar o assunto. Poderia ser algo no sentido de "Apesar dessas desvantagens, a plataforma pode ser muito útil....", para o texto não ficar tão quebrado.

**Comment by isabelirk** [comment]
Boa tarde @alessandrapedrotti, poderia dar uma ultima lida, já finalizei os novos ajustes.

**Comment by alessandrapedrotti** [comment]
Texto aprovado.

Fiz apenas a troca de algumas palavras no parágrafo final.

**Comment by isabelirk** [comment]
Conforme o retorno, esta issue esta sendo finalizada.
