### ISSUE TITLE
Desenvolvimento sobre o tópico "Facilitador: mathway."

### ISSUE THREAD

**Issue by isabelirk** [practice-uffs/programa#372]
Esta issue esta relacionada com a issue #314 ; é uma subtarefa referente ao facilitador "Mathway"; deve ser realizado o desenvolvimento referente a seção 3 do manual de apoio dos estudantes deste tópico, que abrange: o que é, quais são seus objetivos, como podemos utilizá-lo, vantagens e desvantagens. Caso seja interessante ou necessário, a inclusão de imagens do mesmo.

**Comment by isabelirk** [comment]
link da pasta no drive: https://drive.google.com/drive/folders/1kYiLvuI9tuhVKyF8LQxZjQ4kQFPpGIek

**Comment by isabelirk** [comment]
Texto finalizado aguardando revisão.

**Comment by alessandrapedrotti** [comment]
O texto ficou muito bom! Fiz apenas algumas alterações referentes a plurais e algumas vírgulas. Seria necessário formular um pequeno parágrafo de finalização do tópico, para ele tão ficar tão quebrado.

**Comment by isabelirk** [comment]
Boa tarde @alessandrapedrotti, poderia dar uma ultima lida, já finalizei os novos ajustes.

**Comment by alessandrapedrotti** [comment]
Texto aprovado.

Fiz apenas uma pequena adição na última linha do texto.

**Comment by isabelirk** [comment]
Conforme o retorno, esta issue esta sendo finalizada.
