### ISSUE TITLE
Edição de vídeos - PPGE 

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#373]
Pessoal recebemos uma demanda para edição de 02 vídeos da PPGE. 

**O link das vinhetas é:** https://drive.google.com/drive/folders/1sx34HeEbVhIiPdrw-xbfuolkhxUI7cWO?usp=sharing

**Vídeo 1 - Egressa Rosileia -** https://drive.google.com/file/d/1GMLjB21jLWCfKVmTdfFQS95z9j0OBiwA/view?usp=sharing

**Vídeo 2 - Egressa Bruna -** https://drive.google.com/file/d/14ty7F7iy3wt24a_ChUvUAhyswNP1Bz6X/view?usp=sharing

`Precisa ser realizada as seguintes edições:`

- [x] Inserir a vinheta;
- [x] Também adicionar legenda (o texto para a legenda de cada um dos vídeos está anexo);
- [x] Adicionar o tema dos vídeos --> Egressa Rosileia- informação que consta na vinheta inicial é: Políticas de Acesso e Ações Afirmativas na Educação Superior;
- [x] Adicionar o tema dos vídeos --> Egressa Bruna- informação que consta na vinheta inicial é: A Alimentação no Âmbito da Assistência Estudantil para o Ensino Superior.

Contato: 
Geomara Balsanello --> geomarabalsanello@uffs.edu.br

**Comment by amandasegattob** [comment]
Boa tarde! Eu posso editar!

**Comment by amandasegattob** [comment]
Oie, eu posso editar!

Só não encontrei o texto da legenda.

**Comment by VIF-Franca** [comment]
Arquivos recebidos pelo solitante. 

[PASTA](https://drive.google.com/drive/folders/1yukaWPnOMdP5soCURxSQqpn_VL5DJEJi?usp=sharing)

**Comment by amandasegattob** [comment]
Oi gente, eu preciso da ajuda de alguém de vocês para juntar a legenda e o vídeo, porque não tô conseguindo no Format Factory. Deixei os vídeos e a minutagem [nessa pasta](https://drive.google.com/drive/folders/1rQXFzy5WtV1TGXUR3OLl_khBPqQWapPD)
Agradeço muito se alguém puder tentar. 
@MilenaPaz2020 @vini2reis @pedroamaximowski

**Comment by MilenaPaz2020** [comment]
> Oi gente, eu preciso da ajuda de alguém de vocês para juntar a legenda e o vídeo, porque não tô conseguindo no Format Factory. Deixei os vídeos e a minutagem [nessa pasta](https://drive.google.com/drive/folders/1rQXFzy5WtV1TGXUR3OLl_khBPqQWapPD)
> Agradeço muito se alguém puder tentar.
> @MilenaPaz2020 @vini2reis @pedroamaximowski

Oi, Amanda. Posso ajudar sim, mas só consigo amanhã de manhã.
Se também tiver alguma dificuldade chamo por aqui kkk

**Comment by MilenaPaz2020** [comment]
Gente, tentei pelo VLC e não deu certo. 
Alguém consegue ajudar?

**Comment by amandasegattob** [comment]
Será que é algum problema de quando baixa as legendas do YouTube?

**Comment by vini2reis** [comment]
@amandasegattob Eu consegui colocar a legenda
Coloquei os vídeos legendados la na pasta da issue

**Comment by vini2reis** [comment]
> Será que é algum problema de quando baixa as legendas do YouTube?

Provavelmente tu não clicou em "publicar" depois q tu fez a legenda ai o download foi em .sbv e nao em .srt

**Comment by amandasegattob** [comment]
Boa noite, coloquei os vídeos [nessa pasta](https://drive.google.com/drive/folders/1ZlycI8sFu2qh4BRm9UZGmZ6na0FAMlN2). Qualquer alteração é só falar!

**Comment by MilenaPaz2020** [comment]
> Boa noite, coloquei os vídeos [nessa pasta](https://drive.google.com/drive/folders/1ZlycI8sFu2qh4BRm9UZGmZ6na0FAMlN2). Qualquer alteração é só falar!

Olá! Assisti os vídeos agora e gostei bastante! Parabéns, pessoal!
Só uma dúvida. No início de ambos os vídeos, a música da vinheta corta de forma um pouco brusca. Seria possível ir diminuindo essa música no início das falas? Só para ficar um pouco mais suave.

Outra sugestão, nesse caso no vídeo da Bruna, é de cortar só um pouquinho do final (creio que coisa de um segundo), onde ela desliga a câmera. 

No mais, gostei bastante da proposta. Mesmo com o segundo vídeo gravado na vertical, ficou um material de divulgação bem atrativo.

**Comment by amandasegattob** [comment]
> > Boa noite, coloquei os vídeos [nessa pasta](https://drive.google.com/drive/folders/1ZlycI8sFu2qh4BRm9UZGmZ6na0FAMlN2). Qualquer alteração é só falar!
> 
> 
> 
> Olá! Assisti os vídeos agora e gostei bastante! Parabéns, pessoal!
> 
> Só uma dúvida. No início de ambos os vídeos, a música da vinheta corta de forma um pouco brusca. Seria possível ir diminuindo essa música no início das falas? Só para ficar um pouco mais suave.
> 
> 
> 
> Outra sugestão, nesse caso no vídeo da Bruna, é de cortar só um pouquinho do final (creio que coisa de um segundo), onde ela desliga a câmera. 
> 
> 
> 
> No mais, gostei bastante da proposta. Mesmo com o segundo vídeo gravado na vertical, ficou um material de divulgação bem atrativo. 

Oie! Dá para fazer essas alterações sim, fica melhor. Eu deixei assim pq não sabia se podia fazer mais edições do que estava sendo solicitado. 
Logo mais faço as edições.

**Comment by amandasegattob** [comment]
Coloquei os vídeos na pasta.

**Comment by MilenaPaz2020** [comment]
> Coloquei os vídeos na pasta.

Achei o resultado excelente!
Farei o envio aos solicitantes.

**Comment by MilenaPaz2020** [comment]
Vídeos aprovados pelos solicitantes, pessoal! Parabéns.
Só uma dúvida, o material finalizado não precisa ser salvo em nenhuma outra pasta, certo?

**Comment by vini2reis** [comment]
> Vídeos aprovados pelos solicitantes, pessoal! Parabéns.
> Só uma dúvida, o material finalizado não precisa ser salvo em nenhuma outra pasta, certo?

Nao
So na pasta saída mesmo

**Comment by MaNegrao** [comment]
Podemos finalizar :D
