### ISSUE TITLE
Planilha de  mapeamento e organização para a criação de postagens 

### ISSUE THREAD

**Issue by morgana-mo** [practice-uffs/programa#374]
Essa issue tem como objetivo criar uma planilha  mapeamento e controle de criação e organização dos materiais a serem desenvolvidos pela equipe de comunicação, tendo em vista as diversas propostas que se encontram nas issues #334 e #356.
[Planilha](https://docs.google.com/spreadsheets/d/1VJYaOSgFQf5LULs0Zt7Xpw2aJ_cQuL3cNQKgTUQMyy0/edit#gid=0)

**Comment by morgana-mo** [comment]
Um primeiro rascunho da  [planilha de mapeamento](https://docs.google.com/spreadsheets/d/1VJYaOSgFQf5LULs0Zt7Xpw2aJ_cQuL3cNQKgTUQMyy0/edit#gid=491440555)

**Comment by VIF-Franca** [comment]
Achei show a tabela, sugiro que façamos uma postagem para cada mês, como por exemplo: 

> Janeiro branco - saúde mental 
> Fevereiro roxo - alzheimer
> Abril azul - autismo 
> Junho vermelho - doação de sangue 
> Setembro amarelo - combate e prevenção ao suicídio 
> Outubro rosa - câncer de mama 
> Novembro azul - câncer de próstata 

Me recordo desses meses temáticos, porem deve ter para os demais.

**Comment by morgana-mo** [comment]
> Achei show a tabela, sugiro que façamos uma postagem para cada mês, como por exemplo: 
> 
> > Janeiro branco - saúde mental 
> > Fevereiro roxo - alzheimer
> > Abril azul - autismo 
> > Junho vermelho - doação de sangue 
> > Setembro amarelo - combate e prevenção ao suicídio 
> > Outubro rosa - câncer de mama 
> > Novembro azul - câncer de próstata 
> 
> Me recordo desses meses temáticos, porem deve ter para os demais. 

Vou fazer uma pesquisa e já adiciono tanto ao calendário como na planilha!

**Comment by morgana-mo** [comment]
Adicionei as postagens ao calendário e a  planilha

**Comment by morgana-mo** [comment]
Refiz a [planilha](https://docs.google.com/spreadsheets/d/1VJYaOSgFQf5LULs0Zt7Xpw2aJ_cQuL3cNQKgTUQMyy0/edit#gid=912713067) conforme formos dando andamento nas issues ela vai sendo completada

**Comment by morgana-mo** [comment]
Acho que essa issue pode ser finalizada e a planilha movida a pasta de materiais.
@Claudineia-VR algum apontamento?

**Comment by morgana-mo** [comment]
Closed #374
