### ISSUE TITLE
Desenvolvimento sobre o tópico "Facilitador: google drive"

### ISSUE THREAD

**Issue by isabelirk** [practice-uffs/programa#375]
Esta issue esta relacionada com a issue #314 ; é uma subtarefa referente ao facilitador "Google Drive"; deve ser realizado o desenvolvimento referente a seção 3 do manual de apoio dos estudantes deste tópico, que abrange: o que é, quais são seus objetivos, como podemos utilizá-lo, vantagens e desvantagens. Caso seja interessante ou necessário, a inclusão de imagens do mesmo.

**Comment by isabelirk** [comment]
link da pasta no drive: https://drive.google.com/drive/folders/1kJiT8GMuvSABXNl75qcEFcmeW3Kp06Zh

**Comment by isabelirk** [comment]
Tópico finalizado aguardando revisão.

**Comment by alessandrapedrotti** [comment]
Deixei um comentário no texto que deve ser resolvido pela redatora e sugiro a elaboração de um parágrafo de finalização para o tópico. Salvo isso, o texto ficou muito bom!

**Comment by isabelirk** [comment]
Boa tarde @alessandrapedrotti, já realizei os ajustes, poderia dar uma ultima lida antes de finalizar?

**Comment by alessandrapedrotti** [comment]
Texto conferido e aprovado.

Fiz apenas uma pequena mudança no parágrafo final.

**Comment by isabelirk** [comment]
Conforme o retorno, esta issue esta sendo finalizada.
