### ISSUE TITLE
Desenvolvimento sobre o tópico: "Facilitador: google acadêmico"

### ISSUE THREAD

**Issue by brendaellen** [practice-uffs/programa#376]
Esta issue esta relacionada com a issue #314 ; é uma subtarefa referente ao facilitador "Google Acadêmico"; deve ser realizado o desenvolvimento referente a seção 3 do manual de apoio dos estudantes deste tópico, que abrange: o que é, quais são seus objetivos, como podemos utilizá-lo, vantagens e desvantagens. Caso seja interessante ou necessário, a inclusão de imagens do mesmo.

**Comment by brendaellen** [comment]
Link da pasta: https://drive.google.com/drive/folders/1J4zjGAJh1YPjEwOEmqO66KraUYRYt5_4

**Comment by brendaellen** [comment]
Texto finalizado aguardando revisão.

**Comment by alessandrapedrotti** [comment]
@thaliafriedrich, favor tratar da revisão textual desse tópico.

**Comment by thaliafriedrich** [comment]
Muito bom o texto, @brendaellen. Está bem organizado e traz bastante informação sobre a plataforma.
Revisei e fiz algumas modificações de palavras para tentar harmonizar melhor algumas frases.

**Comment by brendaellen** [comment]
Muito obrigada pelas correções @thaliafriedrich 
Sendo assim, acredito que essa issue já pode ser fechada.
