### ISSUE TITLE
Desenvolvimento sobre o tópico: "Facilitadores: issuu"

### ISSUE THREAD

**Issue by isabelirk** [practice-uffs/programa#377]
Esta issue esta relacionada com a issue #314 ; é uma subtarefa referente ao facilitador "Issuu"; deve ser realizado o desenvolvimento referente a seção 3 do manual de apoio dos estudantes deste tópico, que abrange: o que é, quais são seus objetivos, como podemos utilizá-lo, vantagens e desvantagens. Caso seja interessante ou necessário, a inclusão de imagens do mesmo.

**Comment by isabelirk** [comment]
Link da pasta no drive: https://drive.google.com/drive/folders/17CYjs3UkWGZJT-fWW2U_EmcJGN6APRK0

**Comment by isabelirk** [comment]
Texto finalizado apenas aguardando revisão.

**Comment by alessandrapedrotti** [comment]
@thaliafriedrich, favor tratar da revisão textual desse tópico.

**Comment by thaliafriedrich** [comment]
Muito bom esse tópico, gostei das informações e a forma como foram apresentadas no texto.
Revisei e deixei comentários no arquivo.

**Comment by isabelirk** [comment]
Boa tarde, @thaliafriedrich poderia dar uma ultima lida, já finalizei os novos ajustes.

**Comment by thaliafriedrich** [comment]
Li o texto mais uma vez e achei que ficou excelente, parabéns @isabelirk! 
Revisão finalizada.

**Comment by isabelirk** [comment]
Conforme os ajustes realizados e a ultima revisão, esta issue esta sendo finalizada.
