### ISSUE TITLE
Desenvolvimento sobre o tópico "Facilitadores: Evernote"

### ISSUE THREAD

**Issue by isabelirk** [practice-uffs/programa#378]
Esta issue esta relacionada com a issue #314 ; é uma subtarefa referente ao facilitador "Evernote"; deve ser realizado o desenvolvimento referente a seção 3 do manual de apoio dos estudantes deste tópico, que abrange: o que é, quais são seus objetivos, como podemos utilizá-lo, vantagens e desvantagens. Caso seja interessante ou necessário, a inclusão de imagens do mesmo.

**Comment by isabelirk** [comment]
Link da pasta no drive: https://drive.google.com/drive/folders/1I_q9RoPzJ8obc-wJJMMYnC014NlQI7lM

**Comment by isabelirk** [comment]
Texto finalizado aguardando revisão.

**Comment by alessandrapedrotti** [comment]
@thaliafriedrich, favor tratar da revisão textual desse tópico.

**Comment by thaliafriedrich** [comment]
Texto revisado. No geral, ficou muito bom. Deixei os comentários no arquivo como sugestão.

**Comment by isabelirk** [comment]
Boa tarde, @thaliafriedrich poderia dar uma ultima lida, já finalizei os novos ajustes.

**Comment by thaliafriedrich** [comment]
Li o texto mais uma vez e achei que ficou excelente, parabéns @isabelirk! 
Revisão finalizada.

**Comment by isabelirk** [comment]
Conforme os ajustes realizados e a ultima revisão, esta issue esta sendo finalizada.
