### ISSUE TITLE
Desenvolvimento sobre o tópico: "Facilitador: skoob"

### ISSUE THREAD

**Issue by brendaellen** [practice-uffs/programa#379]
Esta questão está relacionada com a questão #314  ; é uma subtarefa referente ao facilitador "Skoob"; deve ser realizado o desenvolvimento referente a seção 3 do manual de apoio dos estudantes deste tópico, que abrange: o que é, quais são seus objetivos, como podemos utilizar-lo, vantagens e desvantagens. Caso seja interessante ou necessário, a inclusão de imagens do mesmo.

**Comment by brendaellen** [comment]
Link da pasta: https://drive.google.com/drive/folders/1Z4MtD0GxopTnmk9FrCiT-3pb9Hu7sRda

**Comment by brendaellen** [comment]
Texto finalizado aguardando revisão.

**Comment by alessandrapedrotti** [comment]
Acho interessante adicionar um parágrafo explicando o desafio de leitura anual da plataforma e também um parágrafo final que encerre o texto, pois da maneira que está, ele parece cortado.

Salvo esses dois pontos, o texto ficou muito bom.

**Comment by brendaellen** [comment]
@alessandrapedrotti obrigada pelas observações. Fiz as alterações sugeridas, e gostaria que você desse uma olhada para ver se está tudo certo. Se possível, também gostaria que você inserisse alguma imagem do Skoob que represente o desafio ou meta de leitura, pois você havia comentado que tem uma conta nessa plataforma.

**Comment by alessandrapedrotti** [comment]
Coloquei na pasta os prints com as regras do desafio e a contagem das leituras que já foram contabilizadas. Peço apenas que editem as imagens da contagem para não aparecer minha foto de perfil.

**Comment by alessandrapedrotti** [comment]
Após serem inseridas as imagens do desafio, gostaria de reler o texto para aprová-lo.

**Comment by brendaellen** [comment]
Já inseri as imagens @alessandrapedrotti , pode fazer a leitura.

**Comment by alessandrapedrotti** [comment]
Texto lido, não existem mais pontos a serem alterados.

**Comment by brendaellen** [comment]
Com a revisão textual finalizada, a issue já pode ser fechada.
