### ISSUE TITLE
Desenvolvimento sobre o tópico: "Facilitador: photomath"

### ISSUE THREAD

**Issue by brendaellen** [practice-uffs/programa#380]
Esta questão está relacionada com a questão #314  ; é uma subtarefa referente ao facilitador "Photomath"; deve ser realizado o desenvolvimento referente a uma seção 3 do manual de apoio dos estudantes deste tópico, que abrange: o que é, quais são seus objetivos, como podemos utilizar-lo, vantagens e desvantagens. Caso seja interessante ou necessário, a inclusão de imagens do mesmo.

**Comment by brendaellen** [comment]
Link da pasta: https://drive.google.com/drive/folders/1gjrTAhFKw28K-dt0bb5ajsLj-5xNEaNS

**Comment by brendaellen** [comment]
Texto finalizado, aguardando revisão.

**Comment by alessandrapedrotti** [comment]
@thaliafriedrich, favor tratar da revisão textual desse tópico.

**Comment by thaliafriedrich** [comment]
Texto revisado. O tópico está bem escrito e contém as principais informações. Só deixei uma sugestão e fiz pequenas alterações em algumas frases.

**Comment by brendaellen** [comment]
@thaliafriedrich obrigada pelas observações. Fiz as alterações no último parágrafo como sugerido, e gostaria que você revisasse novamante para que eu possa fechar a issue.

**Comment by thaliafriedrich** [comment]
> @thaliafriedrich obrigada pelas observações. Fiz as alterações no último parágrafo como sugerido, e gostaria que você revisasse novamante para que eu possa fechar a issue.

De nada :)
Revisei novamente. Tudo ok, já pode fechar a issue.

**Comment by brendaellen** [comment]
Com a revisão finalizada, a issue já pode ser fechada.
