### ISSUE TITLE
Desenvolvimento sobre o tópico: "Facilitador bônus: academia.edu"

### ISSUE THREAD

**Issue by brendaellen** [practice-uffs/programa#381]
Esta questão está relacionada com a questão #314  ; é uma subtarefa referente ao facilitador bônus "Academia.edu"; deve ser realizado o desenvolvimento referente a uma seção 3 do manual de apoio dos estudantes deste tópico, que abrange: o que é, quais são seus objetivos, como podemos utilizar-lo, vantagens e desvantagens. Caso seja interessante ou necessário, a inclusão de imagens do mesmo.

**Comment by brendaellen** [comment]
Link da pasta: https://drive.google.com/drive/folders/17zSdOUfQHT9VDM-qNCiuLkBHoVAxsYKE

**Comment by brendaellen** [comment]
Texto finalizado, aguardando revisão.

**Comment by alessandrapedrotti** [comment]
@thaliafriedrich, favor tratar da revisão textual desse tópico.

**Comment by thaliafriedrich** [comment]
Texto revisado. Deixei duas sugestões no arquivo para verificar, mas no geral, está muito bom.

**Comment by brendaellen** [comment]
@thaliafriedrich fiz as alterações sugeridas, e gostaria por gentileza que você verifica-se se está tudo certo, antes de fechar a issue.

**Comment by thaliafriedrich** [comment]
> @thaliafriedrich fiz as alterações sugeridas, e gostaria por gentileza que você verifica-se se está tudo certo, antes de fechar a issue.

Verifiquei novamente. Está tudo certo, o tópico ficou muito bom.

**Comment by brendaellen** [comment]
Com a revisão finalizada, a issue já pode ser fechada.
