### ISSUE TITLE
Criação de Banner para o curso de Nutrição 

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#382]
Recebemos a demanda abaixo para a criação de banner de divulgação do curso de Nutrição, segue as devidas informações:

- [x] 01 banners com as seguintes dimensões: 90 cm de largura por 1,20 metros;
- [x] As cores precisam ser convertidas em cmyk;
- [x] Disponibilizar o arquivo editável; 

Observação enviada pelo demandante: 

> "Como são banners de divulgação de cursos do campus Realeza, a ideia é desenvolver duas versões de arte que servirão de padrão para cursos que posteriormente solicitarem banner."

Consta [nesta pasta](https://drive.google.com/drive/u/0/folders/1qovMeAulQOTRnCWnANTSMsH57qgR5fuM) do drive os seguintes arquivos: 

- Imagens que devem conter no banner; 
- Material textual para a composição dos banner; 
- Assinatura visual do campus Realeza; 

Solicitante: 
Mariah Carraro Smaniotto
"Comunicação Visual" <comunicacao.visual@uffs.edu.br>;

**Comment by ricardopatrik** [comment]
https://unsplash.com/photos/08bOYnH_r_E
https://unsplash.com/photos/QvkAQTNj4zk
 link das fotos

**Comment by ricardopatrik** [comment]
tem duas opções feitas no drive

**Comment by VIF-Franca** [comment]
Já podemos enviar ao cliente ? Caso sim, por gentileza sempre marcar @VIF-Franca  e adicionar a etiqueta `aux:revisar`.

**Comment by ricardopatrik** [comment]
Sim @VIF-Franca, pode mandar, desculpe por não te marcar

**Comment by alessandrapedrotti** [comment]
@anacarolinamorigi e @morgana-mo tratar dessa tarefa, por gentileza.

**Comment by anacarolinamorigi** [comment]
> @anacarolinamorigi e @morgana-mo tratar dessa tarefa, por gentileza.

Pode deixar!

**Comment by anacarolinamorigi** [comment]
Boa tarde, gente!
[Aqui ](https://drive.google.com/drive/folders/1IMk9R2VV2clKKIQfF82e8EzoqqHdN526?usp=sharing) estão dois modelos de banner, não sei se era dessa forma que gostariam, esse seria só um protótipo de modelo sem estar editável, sem ser cmyk. Aguardo feedback e maiores orientações!

**Comment by VIF-Franca** [comment]
Enviei para o cliente, aguardando feedback.

**Comment by VIF-Franca** [comment]
recebemos o feedback, [adicionei na pasta](https://drive.google.com/file/d/1rJvnX3yKDtJJqR0Z9t0L_giq3tbRVtv3/view?usp=sharing).

Caso não consiga abrir, já pedi uma versão em PDF.

**Comment by VIF-Franca** [comment]
`Feedback inicial`

> O alinhamento do texto ainda veio de forma equivocada, ou seja justificado, solicitei que viesse alinhado a direita.
> 
> Se encaminharem o arquivo em ai sem texto expandido (curvas) posso fazer os ajustes aqui no setor, inclusive no de Nutrição, acredito que facilitaria o trabalho de vocês.

**Comment by VIF-Franca** [comment]
Recebemos o arquivo em PDF, [segue link](https://drive.google.com/file/d/1kUkwe4L1GBjfZu8d9KJrWTr5kBy8-HIc/view?usp=sharing).

**Comment by anacarolinamorigi** [comment]
[Aqui](https://drive.google.com/drive/folders/1lLUeZIbgWsD8gpCJGCM1BJ8Vz6VTrIRp?usp=sharing) está o arquivo do banner, ele encontra-se editável e em cmyk. Podemos dar retorno para a solicitante.

@VIF-Franca

**Comment by morgana-mo** [comment]
A @mariagelain enviou para a solicitante

**Comment by anacarolinamorigi** [comment]
@mariagelain [aqui](https://drive.google.com/file/d/1d97pBRK56pga8let0l5RKWt6mCmT3ug6/view?usp=sharing) encontra-se novamente upado o arquivo com as alterações pedidas pela solicitante, peço que encaminhe para ela que essa versão em PDF pode ser alterar a escrita sem precisar do arquivo do illustrator, só abrir o arquivo no photoshop. Qualquer coisa que ela precisa alterar algo no template daí subo o arquivo do illustrator.

**Comment by anacarolinamorigi** [comment]
Boa noite!

[Aqui](https://drive.google.com/drive/folders/1lLUeZIbgWsD8gpCJGCM1BJ8Vz6VTrIRp?usp=sharing) está a versão editável que a solicitante pediu, estão em dois arquivos: PDF e AI. 
Qualquer outra alteração, só prender o grito.

**Comment by mariagelain** [comment]
Email enviado!

**Comment by anacarolinamorigi** [comment]
Bom dia!

@mariagelain as alterações pedidas pela solicitante já estão na [pasta de saída](https://drive.google.com/drive/folders/1lLUeZIbgWsD8gpCJGCM1BJ8Vz6VTrIRp?usp=sharing), ela está em modelo ppt. Qualquer outra alteração só chamar!

**Comment by mariagelain** [comment]
A alteação foi enviada para a solicitante pelo email

**Comment by morgana-mo** [comment]
Solicitante deu o retorno no email!

> Bom dia!
> Gostaria de agradecer o atendimento. O auxílio foi muito importante para nós da DCS.
> Encaminhe meu parabéns ao pessoal que fez os dois banners para nós.
> Um grande abraço a todos.

Podemos dar por encerrada essa demanda @mariagelain ?

**Comment by mariagelain** [comment]
Sim, tanto esta quando a #383.
