### ISSUE TITLE
Criação de Banner para o curso de Ciências Biológicas

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#383]
Recebemos a demanda abaixo para a criação de banner de divulgação do curso de Nutrição, segue as devidas informações:

- [x] 01 banners com as seguintes dimensões: 90 cm de largura por 1,20 metros;
- [ ] As cores precisam ser convertidas em cmyk;
- [ ] Disponibilizar o arquivo editável;

Observação pelo demandante:

> "Como são banners de divulgação de cursos do campus Realeza, a ideia é desenvolver duas versões de arte que servirão de padrão para cursos que posteriormente solicitarem banner."

Consta [nesta pasta](https://drive.google.com/drive/folders/1_1NJagbVKKuTa-7AGsyvyPACOUcK_VNe?usp=sharing) do drive os seguintes arquivos:
- Imagens que devem conter no banner;
- Material textual para a composição dos banner;
- Assinatura visual do campus Realeza;

Solicitante:
Mariah Carraro Smaniotto
"Comunicação Visual" comunicacao.visual@uffs.edu.br ;

**Comment by ricardopatrik** [comment]
Duas opções na pasta [SÁIDA](https://docs.google.com/presentation/d/1V0ZZyfGRT_XrLPN3DT-yrnkfDKey7wa_hXDtykyIzPM/edit#slide=id.p)

**Comment by ricardopatrik** [comment]
pode enviar @VIF-Franca

**Comment by alessandrapedrotti** [comment]
@anacarolinamorigi e @morgana-mo tratar dessa tarefa, por gentileza.

**Comment by morgana-mo** [comment]
> @anacarolinamorigi e @morgana-mo tratar dessa tarefa, por gentileza.
> 

Certo Ale 😁

**Comment by morgana-mo** [comment]
Boa tarde, gente! 
[Aqui](https://drive.google.com/drive/folders/1FKN5iU-Flhh5IkODp3FL1VNpkuwiP-we) estão dois modelos de banner, não sei se era dessa forma que gostariam, esse seria só um protótipo de modelo sem estar editável, sem ser cmyk. Aguardo feedback e maiores orientações!

**Comment by alessandrapedrotti** [comment]
> Boa tarde, gente!
> [Aqui](https://drive.google.com/drive/folders/1FKN5iU-Flhh5IkODp3FL1VNpkuwiP-we) estão dois modelos de banner, não sei se era dessa forma que gostariam, esse seria só um protótipo de modelo sem estar editável, sem ser cmyk. Aguardo feedback e maiores orientações!

Gostei muito da segunda opção, pois a primeira ficou poluída demais devido ao fundo. Seria possível trabalhar em uma terceira possibilidade? com um fundo mais limpo e moderno?

**Comment by morgana-mo** [comment]
> > Boa tarde, gente!
> > [Aqui](https://drive.google.com/drive/folders/1FKN5iU-Flhh5IkODp3FL1VNpkuwiP-we) estão dois modelos de banner, não sei se era dessa forma que gostariam, esse seria só um protótipo de modelo sem estar editável, sem ser cmyk. Aguardo feedback e maiores orientações!
> 
> Gostei muito da segunda opção, pois a primeira ficou poluída demais devido ao fundo. Seria possível trabalhar em uma terceira possibilidade? com um fundo mais limpo e moderno?

[Novos modelos](https://drive.google.com/drive/folders/1H5UPivGZF7ry4VviZfKHOVDxh1Kozy7q) na pasta, eu tô meio confusa com esse banner não tem referência nenhuma e nenhum padrão de cores a ser seguido

**Comment by VIF-Franca** [comment]
Creio que podemos enviar para o solicitante avaliar. 

Espero o OK da @alessandrapedrotti e/ou @mariagelain.

**Comment by alessandrapedrotti** [comment]
> Creio que podemos enviar para o solicitante avaliar.
> 
> Espero o OK da @alessandrapedrotti e/ou @mariagelain.

Pode ser enviado para a avaliação.

**Comment by VIF-Franca** [comment]
Enviado. Aguardando feedback.

**Comment by VIF-Franca** [comment]
Pessoal recebemos o feedback do demandante. Adicionei uma nova pasta com: a arte aprovada com os devidos comentários do solicitante. [Acesso a pasta](https://drive.google.com/drive/folders/1C6am1F4p7WwBNobhcdcXJVklOD63i8Y-?usp=sharing). 

Destaca-se o seguinte comentário da solicitante: 

> No pdf tem algumas observações que gostaria que fosse corrigida. Sugiro que não seja alterado a questão de maiúscula e minúscula quando o texto não vier com esse pedido.
Outra dica importante, como designer da instituição, é cuidado ao utilizar o texto justificado, pois quando não hifenizado, o texto fica com "caminho de rato", pois há ajustes diferentes entre palavras para deixar o texto alinhado dos dois lados, o que atrapalha esteticamente e de legibilidade.

**Comment by morgana-mo** [comment]
Boa tarde
[Aqui](https://drive.google.com/folderview?id=1bNmcs7u55M-I65f2Eyxk_WTAnWDqEKbj) estão os modelos em cmyk e editáveis para envio a solicitante @VIF-Franca

**Comment by morgana-mo** [comment]
> Boa tarde
> [Aqui](https://drive.google.com/folderview?id=1bNmcs7u55M-I65f2Eyxk_WTAnWDqEKbj) estão os modelos em cmyk e editáveis para envio a solicitante @VIF-Franca

@VIF-Franca ?

**Comment by VIF-Franca** [comment]
Já foi enviado, qualquer coisa reabrimos a issue

**Comment by VIF-Franca** [comment]
> O alinhamento do texto ainda veio de forma equivocada, ou seja justificado, solicitei que viesse alinhado a direita.
> 
> Se encaminharem o arquivo em ai sem texto expandido (curvas) posso fazer os ajustes aqui no setor, inclusive no de Nutrição, acredito que facilitaria o trabalho de vocês.


`Feedback`

**Comment by anacarolinamorigi** [comment]
Boa noite!

[Aqui](https://drive.google.com/drive/folders/1bNmcs7u55M-I65f2Eyxk_WTAnWDqEKbj?usp=sharing) está o arquivo do banner, ele encontra-se editável e em cmyk. Podemos dar retorno para a solicitante. 

@VIF-Franca

**Comment by morgana-mo** [comment]
A @mariagelain  enviou a nova versão para a solicitante

**Comment by mariagelain** [comment]
Como a demanda foi aprovada, a issue já pode ser dada como finalizada.
