### ISSUE TITLE
Testes para o Reels

### ISSUE THREAD

**Issue by morgana-mo** [practice-uffs/programa#384]
Essa Issue tem como objetivo a criação de vídeos teste para o Reels do Instagram do PRACTICE, inicialmente deverão ser testadas as configurações de tela, transições e formato de imagens a serem utilizadas.
[Pasta do Drive](https://drive.google.com/drive/folders/1trzg1D-jyI4gFTCLsvoROwLAabvB4Uac)

**Comment by morgana-mo** [comment]
Pesquisei sobre as configurações
**-Ao criar um Reels, ele estará nas dimensões 1080 x 1920 px. Esse formato é exibido quando você clica para visualizá-lo no perfil de alguém. Ou também quando entra na aba“Explorar”.**

**-Agora, se você estiver rolando seu feed e encontrar um Reels, note que ele tem a proporção 4:5, com dimensões 1080 x 1450 px.**

**-Ao criar um Reels, você tem a opção de incluir uma thumbnail – ou capa. Ela precisa ter as dimensões 1080 x 1800 px para garantir a exibição do conteúdo sem distorções.**

**Comment by morgana-mo** [comment]
Para configurar a  tela ir em:
**Configurações>Modo de vídeo>Personalizado e adicionar as configurações como na imagem**
![formato](https://user-images.githubusercontent.com/71781124/104218985-49dd7600-541c-11eb-95ce-899e77d6af91.jpg)

**Comment by morgana-mo** [comment]
Fiz umas [brincadeiras](https://drive.google.com/drive/folders/1CPbWQlV2Is7JSfvXFPuDl2ERwmrkhE8L) pra testar o formatos, os tamanhos de letra e jogos de cores

**Comment by morgana-mo** [comment]
Fiz mais um [teste](https://drive.google.com/drive/folders/1CPbWQlV2Is7JSfvXFPuDl2ERwmrkhE8L), dessa vez usei os dados do relatório semestral do programa pra cria-lo

**Comment by Dovyski** [comment]
Eu achei bem bom o resultado desses teus testes, @morgana-mo ! 🥳  Eu gostei bastante dos modelos do primeiro teste, que tem uma "moldura" ao redor. Ficaram bem legais.

**Comment by morgana-mo** [comment]
Alguém do @practice-uffs/con-midia poderia ajudar a gente com as configurações de qualidade dos vídeos?
A tendência do Instagram é baixar uns 40-50 % da qualidade original de vídeo para o reels.

**Comment by luizatonial** [comment]
> Alguém do @practice-uffs/con-midia poderia ajudar a gente com as configurações de qualidade dos vídeos?
> A tendência do Instagram é baixar uns 40-50 % da qualidade original de vídeo para o reels.

Não sei até onde isso é verdade, mas sempre ouvi dizer que o Instagram tende a diminuir muito a qualidade do que é postado via android, e mantém uma qualidade melhor quando o post é feito em um iphone/ios.

**Comment by morgana-mo** [comment]
> > Alguém do @practice-uffs/con-midia poderia ajudar a gente com as configurações de qualidade dos vídeos?
> > A tendência do Instagram é baixar uns 40-50 % da qualidade original de vídeo para o reels.
> 
> Não sei até onde isso é verdade, mas sempre ouvi dizer que o Instagram tende a diminuir muito a qualidade do que é postado via android, e mantém uma qualidade melhor quando o post é feito em um iphone/ios.

Eu fiz um teste e em partes isso é verdade, mas eu percebi que no caso do Reels quando o vídeo não é feito no app ele deixa o vídeo meio pixelado,eu tenho feito uns testes em horário não convencional e apagado o mais breve possível pra ver como fica. Talvez se o vídeo fosse salvo em uma configuração melhor não aconteceria isso

**Comment by robisonjose** [comment]
Em vez de Full HD (1080x1920) poderíamos fazer em 2k com a mesma proporção (9x16), isto é, 1440x2560.

**Comment by morgana-mo** [comment]
Padrões devidamente definidos e testados, essa issue pode ser fechada!
Closed #384
