### ISSUE TITLE
Desenvolvimento sobre o tópico: "Facilitador bônus: study bunny"

### ISSUE THREAD

**Issue by brendaellen** [practice-uffs/programa#385]
Esta questão está relacionada com a questão #314  ; é uma subtarefa referente ao facilitador bônus "Study Bunny"; deve ser realizado o desenvolvimento referente a uma seção 3 do manual de apoio dos estudantes deste tópico, que abrange: o que é, quais são seus objetivos, como podemos utilizar-lo, vantagens e desvantagens. Caso seja interessante ou necessário, a inclusão de imagens do mesmo.

**Comment by brendaellen** [comment]
Link da pasta: https://drive.google.com/drive/folders/1Y2WzS5MJN7qJ-CpXlrJJgUOUenWUEqRe

**Comment by brendaellen** [comment]
Texto finalizado, agurdando revisão.

**Comment by thaliafriedrich** [comment]
Texto revisado. Gostei muito, está bem escrito e em um tom super agradável de ler. Só fiz algumas correções de pontuação. 
Como está bem detalhado e finalizado, não serão necessárias alterações.

**Comment by brendaellen** [comment]
Muito obrigada @thaliafriedrich . Conforme a revisão foi finalizada, esta issue já pode ser fechada.
