### ISSUE TITLE
Criação de Identidade Visual Simples - Setor da TI-PF - Campus Passo Fundo

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#386]
Criação de identidade visual simples para ser usada no perfil do WhatsApp Business do Setor de TI-PF do campus passo fundo
O cliente já preencheu e enviou o formulário.

> Gostaríamos de uma arte para por em nosso grupo do Whatsapp. EX: Gostaríamos de impessoalidade aos atendentes, a única diferença entre um atendente para outro é a o horário de atendimento.

[Pasta da issue](https://drive.google.com/drive/folders/1TnuIOX4sag-A8ASk8Ookp0qgvpoau2_y)

**Comment by ricardopatrik** [comment]
Está na pasta

**Comment by VIF-Franca** [comment]
Por gentileza ao concluir uma issue que necessita ser enviada ao cliente adicionar as labes `aux:revisar` e `cliente:revisar`

**Comment by VIF-Franca** [comment]
Enviado para o cliente.

`AGUARDANDO FEEDBACK`

**Comment by ricardopatrik** [comment]
coloquei la em JPEG

**Comment by VIF-Franca** [comment]
`Feedback do Cliente`

> Olá,

A minha sugestão seria acrescentar algo na logo que deixe claro para o usuário que somos da UFFS e que somos de Passo Fundo, e do setor de TI.

Informações que precisam conter na logo:
----------------------------------------------------------
UFFS
TI
PF
Suporte - se der para usar a palavra suporte é interessante, mas o essencial mesmo é UFFS, TI e PF.


A ideia é que quando o usuário visualizar a imagem, ele rapidamente tenha estas 3 informações: é da UFFS, é de Passo Fundo e é do setor de Tecnologia da informação.

Quanto ao design

Atenciosamente,
Mauricio Canali Xavier

**Comment by estelavilasboas** [comment]
@ricardopatrik Favor colocar os editáveis da logo na [pasta da issue](https://drive.google.com/drive/folders/1TnuIOX4sag-A8ASk8Ookp0qgvpoau2_y).

**Comment by estelavilasboas** [comment]
Um e-mail será enviado ao solicitante informando os impedimentos que essa demanda apresenta. Entre os impedimentos está a Identidade Visual da Universidade. 
O texto está sendo elaborado [nessa pasta](https://drive.google.com/drive/folders/1WXQwo5rLsZvQhNVjA7kGIlDTrqERbSue) e, assim que finalizado, enviaremos ao solicitante.

**Comment by estelavilasboas** [comment]
@alessandrapedrotti podderia revisar [o texto do e-mail](https://docs.google.com/document/d/1TaHoJ9G9Zo_42znDecPd7Hk7GmcsCzISl519H1E4I_s/edit)?

**Comment by alessandrapedrotti** [comment]
> @alessandrapedrotti podderia revisar [o texto do e-mail](https://docs.google.com/document/d/1TaHoJ9G9Zo_42znDecPd7Hk7GmcsCzISl519H1E4I_s/edit)?

Revisado. O texto ficou muito bom, com a explicação completa do problema para o solicitante, ao meu ver, já pode ser enviado. Ele deve ser transcrito no corpo do e-mail e **não** enviado como anexo. @VIF-Franca como já estava tratando com este solicitante, pode por favor enviar este e-mail?

Após isso, a issue pode ser fechada.

**Comment by VIF-Franca** [comment]
Mensagem enviada.
