### ISSUE TITLE
Alterações nos Banners 2 e 7- PROGRAD (#268; #274)

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#387]
O solicitante dos 7 Banners da PROGRAD pediu algumas alterações em dois Banners já finalizados, sendo:

>Vamos precisar de pequenos ajustes em dois dos banners, a saber:
**Banner 2:**  (#268 )
- Alinhar os três quadros das Diretorias (DPGRAD está um pouco abaixo), ambos com texto centralizado verticalmente;
- Em "Divisão de Gerenciamento de Diploma", o correto é  "Divisão de Gerenciamento de Diplomas".

**Banner 7:** (#274 )
-Sugiro retirar a hifenização.

**Comment by TaynaraCh** [comment]
Alterações concluídas:
[banner #274](https://drive.google.com/drive/u/0/folders/16e4HcCJ2lZGS8mGsCqRlLrIsLT1yMb0U) na [pasta saída](https://drive.google.com/drive/u/0/folders/16e4HcCJ2lZGS8mGsCqRlLrIsLT1yMb0U)
[banner #268](https://drive.google.com/drive/u/0/folders/1WENwYqUhcpfcrVR2dEKN0a8EWiGoCToP) na [pasta saída](https://drive.google.com/drive/u/0/folders/1WENwYqUhcpfcrVR2dEKN0a8EWiGoCToP)

**Comment by VIF-Franca** [comment]
Enviado ao cliente.
