### ISSUE TITLE
Edição de vídeo - Alimentação e Nutrição (1/3)

### ISSUE THREAD

**Issue by MilenaPaz2020** [practice-uffs/programa#388]
Recebemos uma demanda do Departamento de Nutrição e Alimentação (Pró-Reitoria de Assuntos Estudantis) para a edição de três vídeos com a temática: **Alimentação e Nutrição.**
Os vídeos serão disponibilizados no canal do Youtube da Pró Reitoria de Assuntos Estudantis.

**Esse é o primeiro dos três vídeos.**
A [pasta de materiais](https://drive.google.com/drive/u/0/folders/13NgrSOQMzsuJ_YKa_bJiNiqwg5dQY-c6) contém:
- Dois vídeos (longos), mas que são continuação.
- Slides, que serão incluídos junto ao vídeo.
- Roteiro, com  a minutagem específica onde cada slide deve aparecer.

É preciso:
- [x] Inserir vinheta PRACTICE;
- [x] Editar o vídeo, acrescentando os slides conforme solicitado;
- [x] Inserir os créditos;
- [x] Inserir vinheta PRACTICE;
- [x] Gerar legenda no Youtube;
- [x] Corrigir a legenda;
- [x] Acrescentar a legenda ao vídeo;
- [x] Enviar ao solicitante;
- [ ] Fazer alterações, caso necessário;

Contato:
patricia.dallastra@uffs.edu.br

**Comment by MilenaPaz2020** [comment]
Estou upando os materiais para a pasta. Peço que sinalizem quanto a disponibilidade de realizar a edição.

**Comment by vini2reis** [comment]
> Estou upando os materiais para a pasta. Peço que sinalizem quanto a disponibilidade de realizar a edição.

Eu fico com essa ediçao

**Comment by MilenaPaz2020** [comment]
> > Estou upando os materiais para a pasta. Peço que sinalizem quanto a disponibilidade de realizar a edição.
> 
> Eu fico com essa ediçao

Perfeito! Todos os materiais já estão na pasta.

**Comment by VIF-Franca** [comment]
@vini2reis a edição do vídeo já foi iniciada ? Pergunto pois a solicitante questionou o andamento da edição do vídeo. Ele já está em edição ou ainda está na fila de espera ?

**Comment by vini2reis** [comment]
> @vini2reis a edição do vídeo já foi iniciada ? Pergunto pois a solicitante questionou o andamento da edição do vídeo. Ele já está em edição ou ainda está na fila de espera ?

Esta em ediçao

**Comment by vini2reis** [comment]
@practice-uffs/con-midia Alguem poderia terminar a legenda desse video? O vídeos está no youtube do practice interno (Nuticao-2) e o vídeo editado esta na pasta da issue no drive.

**Comment by amandasegattob** [comment]
@vini2reis eu termino!

**Comment by amandasegattob** [comment]
Boa tarde, fiz a legenda, está no canal do practice interno no youtube. É necessário juntar vídeo e a legenda, pois eu não consegui. Se alguém puder fazer isso, eu agradeço muito!

**Comment by amandasegattob** [comment]
Boa tarde, fiz a legenda, está no canal do practice interno no youtube. É necessário juntar vídeo e a legenda, pois eu não consegui. Se alguém puder fazer isso, eu agradeço muito!

@practice-uffs/con-midia

**Comment by luizatonial** [comment]
> Boa tarde, fiz a legenda, está no canal do practice interno no youtube. É necessário juntar vídeo e a legenda, pois eu não consegui. Se alguém puder fazer isso, eu agradeço muito!
> 
> @practice-uffs/con-midia

Posso fazer, sem problemas!

**Comment by luizatonial** [comment]
Se faltava só juntar o vídeo e a legenda, o mesmo está finalizado na [pasta de saída.](https://drive.google.com/drive/u/1/folders/1rkUvbHaW46hb20q4gWYknQ1wXyqjS-zZ)

**Comment by MaNegrao** [comment]
Se alguem puder juntar o vídeo com a legenda meus lindos, preciso enviar para o solicitante

**Comment by luizatonial** [comment]
kkkk eu fiz isso @MaNegrao, está aqui

> Se faltava só juntar o vídeo e a legenda, o mesmo está finalizado na [pasta de saída.](https://drive.google.com/drive/u/1/folders/1rkUvbHaW46hb20q4gWYknQ1wXyqjS-zZ)

**Comment by MaNegrao** [comment]
ahhhh, eu li errado, perdão

**Comment by MaNegrao** [comment]
Vídeo aprovado e finalizado.
