### ISSUE TITLE
Desenvolvimento sobre o topico "Facilitadores: trello"

### ISSUE THREAD

**Issue by isabelirk** [practice-uffs/programa#389]
Esta issue esta relacionada com a issue #314 ; é uma subtarefa referente ao facilitador "Trello"; deve ser realizado o desenvolvimento referente a seção 3 do manual de apoio dos estudantes deste tópico, que abrange: o que é, quais são seus objetivos, como podemos utilizá-lo, vantagens e desvantagens. Caso seja interessante ou necessário, a inclusão de imagens do mesmo.

**Comment by isabelirk** [comment]
Link da pasta no drive: https://drive.google.com/drive/folders/1LvzCXYLY6HpgQD3-VshdshfW8Ixd6Cm_

**Comment by isabelirk** [comment]
Tópico finalizado aguardando revisão.

**Comment by thaliafriedrich** [comment]
Revisão feita. Adorei o seu texto. Fiz só pequenas alterações. Deixo como sugestão escrever (talvez entre o 1º e 2º parágrafo) que é possível criar mais de um quadro, por exemplo: um para organizar o trabalho e outro para tarefas pessoais (que pode ser mantido privado). E também dizer que a tela de fundo pode ser personalizada, pois há diversas opções de imagens e cores.

**Comment by isabelirk** [comment]
Link da pasta no drive (o outro não funciona): https://drive.google.com/drive/folders/1LvzCXYLY6HpgQD3-VshdshfW8Ixd6Cm_

**Comment by isabelirk** [comment]
Boa tarde @thaliafriedrich, realizei os novos ajustes. Poderia dar uma ultima revisão no texto antes de fechar a issue?

**Comment by thaliafriedrich** [comment]
> Boa tarde @thaliafriedrich, realizei os novos ajustes. Poderia dar uma ultima revisão no texto antes de fechar a issue?

Texto lido e aprovado!

**Comment by isabelirk** [comment]
Conforme o retorno, esta issue esta sendo finalizada.
