### ISSUE TITLE
Imagens de apresentação do projeto para utilização em redes sociais.

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#39]

**Comment by estelavilasboas** [comment]
Essas imagens se referem a posts, banners, ícones... ? Precisam conter alguma informação específica além do nome do programa e as demais redes sociais?

**Comment by VIF-Franca** [comment]
@estelavilasboas acho que poderia ser algumas imagens para postagem no Instagram e Facebook com alguns pontos que tem nesses dois documentos listados a seguir: 
1)https://docs.google.com/presentation/d/1lZAYBmpdQsrJKBgqmdPe2UXVT4oIq0dJxHQN73uOdPU/edit#slide=id.g81e6cb5a66_0_0
2)https://drive.google.com/drive/u/0/folders/1uyyOqwBrKtcLPkFB_mihtZiID_5lDknS

---
I) O que é o Programa ?
II) O que fazemos? 
III) Nossa estrutura organizacional ? 
IV) Quais serviços e Produtos oferecemos ?
V) Objetivos do programa

O que acha dessas ideias rsrsrs? Não sei se ajudei rsrs

**Comment by Dovyski** [comment]
@estelavilasboas sim, elas se referem a posts, banners e ícones. Eu acho que podemos simplificar a tarefa ao criar uma imagem padrão estilo o header do site (ondas, variação de cores, etc), com a logo em algum lugar que permita a colocação de texto sobre a imagem (para colocarmos algo como o "O que é o Programa?" sugerido pelo @VIF-Franca, por exemplo).

**Comment by estelavilasboas** [comment]
Foram criadas várias imagens [padrão quadradas](https://drive.google.com/drive/folders/11KJuWVPzdYr1GV67wr4USJwwm8XSRW6Z) (para posts no Instagram, Facebook e Twitter) e imagens no formato de [Stories](https://drive.google.com/drive/folders/1oDpsc9UQZ3ADmTFg_AQ46urqT3C3QwKr) (Instagram e Facebook). 
Na pasta, vão encontrar todas nomeadas como "Carrossel parte 1", "Carrossel parte 2" e assim por diante. Isso foi feito para possibilidade de criar uma postagem carrossel, como os nomes já sugerem. Lembrando que podem e devem ser utilizados individualmente.
Na pasta, também podem ser encontrados os "carrosséis inteiros", ou seja, as imagens antes de serem cortadas em quadrados.

**Comment by VIF-Franca** [comment]
@estelavilasboas  podemos fechar essa issue ?

**Comment by VIF-Franca** [comment]
Acho que o objetivo da issue foi atingindo... qualquer coisa reabrimos...
