### ISSUE TITLE
Identidade Visual Complexa - NAP - Erechim

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#392]
Pessoal a solicitante gostaria da criação de uma identidade visual completa, a demanda é para o Núcleo de Apoio Pedagógico do campus de Erechim. 

O formulário já foi respondido. 

Contato:
Marta Luiza Sfredo --> e-mail: marta.sfredo@uffs.edu.br; 
Coordenação Acadêmica

[Pasta da issue](https://drive.google.com/drive/folders/1CeZ4N-18BPLzwULrgH8LQx_XDXWKqeub)

**Comment by estelavilasboas** [comment]
As respostas em pdf já estão na [pasta Entrada](https://drive.google.com/drive/folders/1YWKthpsEt6w_A3nZII7LHx9vD-gxdQjW).

Esta demanda será atendida após o período de atendimento de demandas internas. Enquanto isso, a demanda está na fila de espera.

**Comment by TaynaraCh** [comment]
Os arquivos estão prontos para serem enviados, na pasta [saída](https://drive.google.com/drive/folders/1l4etnvUQtZbhkb6aIQsS1Fl5YjaEVyeD) encontram-se o pdf com a descrição das artes e também pngs.
Na pasta da issue estão os editáveis.
@mariagelain, pode encaminhar para a solicitante.

**Comment by mariagelain** [comment]
Email enviado!

**Comment by TaynaraCh** [comment]
Identidade visual finalizada. Estão na pasta de saída o pdf com a descrição da mesma e pngs. 
Arquivo editável encontra-se na pasta da issue.
Pode enviar, @mariagelain!

**Comment by mariagelain** [comment]
email enviado!

**Comment by TaynaraCh** [comment]
Solicitante não retornou mais, acredito estar tudo ok, irei fechar a issue
