### ISSUE TITLE
Edição de vídeo PPGE

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#393]
Recebemos uma nova demanda da PPGE para a edição de um vídeo com a seguinte temática: **Políticas e Práticas de Inclusão.**

O link das vinhetas: 
https://drive.google.com/drive/folders/1sx34HeEbVhIiPdrw-xbfuolkhxUI7cWO?usp=sharing

O Vídeo falando sobre um grupo de pesquisa consta no link: 
https://drive.google.com/file/d/17-XA05yKQUe6LRRksJd9IN9_Ab2e3UUa/view

Sobre a vinheta final, precisaríamos de um ajuste, realizar a retirada dos seguintes nomes:

- Claudia Soares, 
- Karin Henzel, 
- Leticia Stein
- Thais Stella

Precisamos que seja feita a edição dos dois vídeos, inserindo-os em meio às vinhetas. Também adicionar legenda.

O Tema do Vídeo - informação que consta na vinheta inicial é:   Políticas e Práticas de Inclusão.

É preciso:

- [x] Inserir vinheta PRACTICE;
- [x]  Editar o vídeo; 
- [x] Editar a vinheta;
- [x]  Inserir os créditos;
- [x]  Inserir vinheta citada;
- [x] Inserir legenda;
- [x]  Gerar legenda no Youtube;
- [x]  Corrigir a legenda;
- [x]  Acrescentar a legenda ao vídeo;
- [x]  Enviar ao solicitante;
- [x]  Fazer alterações, caso necessário;

Contato:
 "Geomara Balsanello" <geomarabalsanello@uffs.edu.br>;

**Comment by amandasegattob** [comment]
Posso fazer essa edição.

**Comment by amandasegattob** [comment]
Bom dia! Fiz as edições do vídeo, está nessa [pasta](https://drive.google.com/drive/folders/1hHOsfXV9rdYoZVxStFll1i_XUdVUzy9G). É necessário enviar para a solicitante.

@MaNegrao @VIF-Franca

**Comment by MaNegrao** [comment]
Enviei ao solicitante e to esperando a resposta :D

**Comment by MaNegrao** [comment]
vídeo aprovado e finalizado! Parabéns amanda!
