### ISSUE TITLE
Encontros de correção

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#394]
Essa issue serve para organizar todas as informações a respeito das reuniões de discussão dos relatórios produzidos pelos bolsistas do programa.

Os horários dos encontros (conforme o apresentado na reunião de líderes do dia 19/01) são:

**Dia 27/01 (quarta-feira)**
Manhã - 9h: equipe conteúdo;
Tarde: - 14h: equipe dev;

**Dia 28/01 (quinta-feira)**
Manhã - 9h: equipe mídia;
Tarde - 14h: auxílio gerencial;

**Dia 29/01 (sexta-feira)**
Manhã - 9h: discussão das ideias de novos projetos presentes nos relatórios.

Para a realização das discussões, é necessário que os responsáveis tenham realizado suas correções individuais dos textos que lhes cabem, conforme o posto (e aprovado) [nesta planilha](https://docs.google.com/spreadsheets/d/1qAywdIs8-G0WzfqOFLe43VNN0k7_kWiRwk2WGsuTBkM/edit?usp=drive_web&ouid=116927292866334483104).

Também é necessário seguir as orientações de correção apresentadas [neste slide.](https://docs.google.com/presentation/d/1vyBA7ZajHh0SecMdFZl3J_Ey-14Gz5vbITeYisZhvWU/edit)

@practice-uffs/lideres @Dovyski @lcaimi @phdmauricio @VIF-Franca @CleissonVieira

**Comment by CleissonVieira** [comment]
Olá
@alessandrapedrotti, peço desculpas, me marcou mas eu não entendi qual tarefa é para mim realizar com essa Issue.
Conforme citou "Para a realização das discussões, é necessário que os responsáveis tenham realizado suas correções individuais dos textos que lhes cabem, conforme o posto (e aprovado) nesta planilha.", eu acessei a planilha e não entendi as correções que preciso fazer.

**Comment by andrewmsilva** [comment]
Eu, como líder da equipe dev, estou lendo e avaliando relatórios de todos os membros da equipe dev. No entanto, não posso avaliar meu próprio relatório e, portanto, @CleissonVieira foi cotado para ler e avaliar meu relatório. Isso deve ser feito até antes de do nosso encontro de correção (27/01 14h), pois o objetivo dele é discutir as avaliações já feitas.

**Comment by VIF-Franca** [comment]
Creio que como os encontros já foram realizados podemos fechar a issue
