### ISSUE TITLE
Flyers restantes para Lives

### ISSUE THREAD

**Issue by Claudineia-VR** [practice-uffs/programa#395]
Essa issue tem por objetivo realizar a criação dos Flyers que faltam para as Lives já realizadas. 

As lives que precisam ter os flyers montados são (essas lives já ocorreram):

- [x] #252 
- [x] #253 
- [x] #254 
- [x] #255 
- [x] #256 
- [x] #257 
- [x] #260 
- [x] #261 
- [x] #262 
- [x] #263 
- [x] #264 
- [x] #270 
- [x] #277 
- [x] #278 
- [x] #279 
- [x] #309 
- [x] #313 
- [x] #324 
- [x] #346 
- [x] #368 
[Modelo Flyer](https://drive.google.com/drive/folders/1KAwRMgD2yK4NJhxcn5Xv2xulM44LouWw)
https://www.qrcode-monkey.com/

**Comment by morgana-mo** [comment]
Podemos seguir o exemplo da #240 com a organização

**Comment by morgana-mo** [comment]
**FLYERS PRONTOS MAS NÃO POSTADOS** 
CAFÉ COM PESQUISA [18/09](https://drive.google.com/file/d/1Fy10M-6omgLRWACYso8fYQnojjWeNfSF/view?usp=sharing )
PLANOS DE ENSINO [22/09](https://drive.google.com/file/d/13FKGK_5nXuYo9x5PJAWN-EuY5t-P2cht/view?usp=sharing)

**Comment by morgana-mo** [comment]
Criei uma [tabela](https://drive.google.com/drive/folders/1KAwRMgD2yK4NJhxcn5Xv2xulM44LouWw) com as lives e algumas informações

**Comment by morgana-mo** [comment]
Adicionei os [QR codes](https://drive.google.com/drive/folders/1KAwRMgD2yK4NJhxcn5Xv2xulM44LouWw)na pasta

**Comment by anacarolinamorigi** [comment]
Flyers já se encontram na pasta [Entrada do Drive](https://drive.google.com/drive/folders/1q3WHqISSiAwZVP9rXRVmLImdA1F1EgUW?usp=sharing) e aguardo primeira revisão para possíveis alterações. 
@MaNegrao

**Comment by MaNegrao** [comment]
Vou dar uma conferida sim e te retorno 😄

**Comment by MaNegrao** [comment]
Perdão pela demora, só consegui olhar agora, segue as minhas observações para algumas mudanças:

Observações gerais: 

Alguns flyers estão com o alinhamento e tamanho do qr-code e o  link do youtube diferentes, vale dar uma olhadinha.

Creio que nas oficinas da PROAE podemos coloacar no subtitulo o assunto geral do evento, por exemplo:
"Oficina de Apoio Pedagogico: Informática Básica", "Oficina de Apoio Pedagogico: Escrita Academica" e Oficinade Apoio Pedagogico: Matemática Básica" 
Assim conseguirmos diminuir os titulos. Os Flyers são: 253, 254, 255, 262, 263, 264, 270.
 
Algumas Observações especificas:

- 252: Pode manter só SIASS, ela está atrelada a reitoria e não ao campus Chapecó 
- 256: O subtitulo pode ser: "Aula Inaugural do PPGEL 2020.2"
- 368: Subtitulo: Evento de formatura

No mais estão ótimos, parabéns Ana. Peço perdão à vocês pela falta de informações de alguns eventos, esse é um problema que enfrentamos no auxilio as lives e estamos solucionando. Eu fico a disposição caso precisem.

**Comment by anacarolinamorigi** [comment]
> Perdão pela demora, só consegui olhar agora, segue as minhas observações para algumas mudanças:
> 
> Observações gerais:
> 
> Alguns flyers estão com o alinhamento e tamanho do qr-code e o link do youtube diferentes, vale dar uma olhadinha.
> 
> Creio que nas oficinas da PROAE podemos coloacar no subtitulo o assunto geral do evento, por exemplo:
> "Oficina de Apoio Pedagogico: Informática Básica", "Oficina de Apoio Pedagogico: Escrita Academica" e Oficinade Apoio Pedagogico: Matemática Básica"
> Assim conseguirmos diminuir os titulos. Os Flyers são: 253, 254, 255, 262, 263, 264, 270.
> 
> Algumas Observações especificas:
> 
> * 252: Pode manter só SIASS, ela está atrelada a reitoria e não ao campus Chapecó
> * 256: O subtitulo pode ser: "Aula Inaugural do PPGEL 2020.2"
> * 368: Subtitulo: Evento de formatura
> 
> No mais estão ótimos, parabéns Ana. Peço perdão à vocês pela falta de informações de alguns eventos, esse é um problema que enfrentamos no auxilio as lives e estamos solucionando. Eu fico a disposição caso precisem.

Está bem, deve ter modificado no momento que salvou os pequenos errinhos. Irei arruma-los e já disponibilizo eles. 

Obrigada pelo retorno, a equipe agradece!

**Comment by anacarolinamorigi** [comment]
Alterações realizada, encontra-se na pasta de [Entrada](https://drive.google.com/drive/u/3/folders/1q3WHqISSiAwZVP9rXRVmLImdA1F1EgUW). Aguardo confirmação se está tudo okay para podermos finalizar a issue.

@MaNegrao

**Comment by MaNegrao** [comment]
Tá perfeito, creio que de nossa parte está finalizado 

Fica agora a cargo do @practice-uffs/dev acrescentar os flyers ao site

**Comment by anacarolinamorigi** [comment]
Creio que podemos já fechar essa issue então. Muito obrigada pelo trabalho, pessoal!

**Comment by anacarolinamorigi** [comment]
Creio que podemos já fechar essa issue então. Muito obrigada pelo trabalho, pessoal!

**Comment by CleissonVieira** [comment]
Boa tarde pessoal!

Vou pedir para não fechar até ser informado na issue que os flyers estão publicados no site.
Outro pedido, feito em outro momento, é ao criar esses flyers se podem ser nomeados com a data da execução da live (ano-mês-dia) + identificação da organização que realizou + sigla da cidade que foi realizada.
Por exemplo, uma live realizada em 5 de outubro de 2020 pelo NAP em Chapecó. Logo o nome do flyer dessa live fica: "2020-10-05_NAP_CH".

Estou passando de flyer em flyer criado, alterando o nome dos mesmo e escrevendo o link da live no youtube para os usuários terem acesso ao vídeos clicando em cima do flyer.

**Comment by CleissonVieira** [comment]
Flyers publicados no site.
Encerrando issue. 

Obrigado pessoal!
