### ISSUE TITLE
Live Cursos de Férias (1/3) - Laranjeiras do Sul - III Workshop Nacional de Karatê Tradicional - 26/01 - 18h às 23h

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#396]
A Universidade Federal da Fronteira Sul (UFFS) – Campus Laranjeiras do Sul, em parceria com o Instituto Federal do Mato Grosso (IFMT) – Campus Rondonópolis, promove, entre os dias 26 e 28 de janeiro, cursos de férias.

O roteiro está na pasta do drive e maiores informações do evento podem ser consultadas [aqui](https://www.uffs.edu.br/campi/laranjeiras-do-sul/noticias/uffs-e-ifmt-promovem-cursos-de-ferias)

![1610711202phpuqbj4s](https://user-images.githubusercontent.com/31110971/105234346-e2c16f00-5b49-11eb-8973-b2329e9995a2.jpeg)

Link youtube: https://youtu.be/eZ-HnJuS01w

[Pasta Drive](https://drive.google.com/drive/folders/16xyqzUlPZPnv_05e7WBHGRTc5mViae4N?usp=sharing)

@VIF-Franca, @pedroamaximowski e @rafaguilman creio que vocês podem ficar responsáveis pela série de lives. Caso não tenham disponibilidade, podemos consultar os outros membros da ilha de lives e @practice-uffs/con-midia.

**Comment by rafaguilman** [comment]
Faço dia 27

**Comment by MaNegrao** [comment]
@practice-uffs/con-midia Pessoal, preciso retornar ao solicitante a confirmação ou não da realização das lives 1 e 3 (#398). @VIF-Franca 2 @pedroamaximowski.

**Comment by pedroamaximowski** [comment]
Live finalizada !
 live iniciou com atraso devido a problemas com palestrantes, mas de resto ocorreu tudo bem.
https://www.youtube.com/watch?v=mHvV9zZ7WX8
