### ISSUE TITLE
Live Cursos de Férias (2/3) - Laranjeiras do Sul - Curso Nacional para Técnicos de Handebol: práticas e vivências - 27-01 das 19h às 23h

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#397]
A Universidade Federal da Fronteira Sul (UFFS) – Campus Laranjeiras do Sul, em parceria com o Instituto Federal do Mato Grosso (IFMT) – Campus Rondonópolis, promove, entre os dias 26 e 28 de janeiro, cursos de férias.

O roteiro está na pasta do drive e maiores informações do evento podem ser consultadas [aqui](https://www.uffs.edu.br/campi/laranjeiras-do-sul/noticias/uffs-e-ifmt-promovem-cursos-de-ferias)

![1610711202phpuqbj4s](https://user-images.githubusercontent.com/31110971/105234346-e2c16f00-5b49-11eb-8973-b2329e9995a2.jpeg)

Link youtube: https://youtu.be/18o8bc19bJg

[Pasta Drive](https://drive.google.com/drive/folders/175Ov1ZdFTG7gyZCCQCoHGnOQxGbVzYNI)

@VIF-Franca, @pedroamaximowski e @rafaguilman creio que vocês podem ficar responsáveis pela série de lives. Caso não tenham disponibilidade, podemos consultar os outros membros da ilha de lives e @practice-uffs/con-midia.

**Comment by MaNegrao** [comment]
@rafaguilman o solicitante perguntou se há a possibilidade do evento começar as 18h ao inves das 19? preciso da sua confirmação

**Comment by luizatonial** [comment]
@rafaguilman a imagem com as logos para ser utilizada na live está na [pasta](https://drive.google.com/drive/folders/175Ov1ZdFTG7gyZCCQCoHGnOQxGbVzYNI). 

Ela já está no tamanho certo considerando a tela inteira e com transparência.

**Comment by luizatonial** [comment]
a live foi finalizada no link https://www.youtube.com/watch?v=18o8bc19bJg&ab_channel=PRACTICEUFFS

apesar de alguns problemas que ocorreram durante a transmissão sejam resultado de um atraso e falha de comunicação por parte dos solicitantes, peço que o @rafaguilman se atente aos enquadramentos/proporções das câmeras e dos slides, tente manter a ordem de elementos estabelecida na issue #343 e também o tipo de transição que deve ser utilizado.

**Comment by rafaguilman** [comment]
Acho que deixando semi calibrado , dará tudo certo , não precisando fazer tudo correndo e com pressa, acho que se organizar antes , para não ter surpresa na hora, isso ajuda também!!

**Comment by rafaguilman** [comment]
Acho que deixando semi calibrado , dará tudo certo , não precisando fazer tudo correndo e com pressa, acho que se organizar antes , para não ter surpresa na hora, isso ajuda também!!
