### ISSUE TITLE
Live Cursos de Férias (3/3) - Laranjeiras do Sul - Curso Nacional de Teatro - 28-01 das 19h às 23h

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#398]
A Universidade Federal da Fronteira Sul (UFFS) – Campus Laranjeiras do Sul, em parceria com o Instituto Federal do Mato Grosso (IFMT) – Campus Rondonópolis, promove, entre os dias 26 e 28 de janeiro, cursos de férias.

O roteiro está na pasta do drive e maiores informações do evento podem ser consultadas [aqui](https://www.uffs.edu.br/campi/laranjeiras-do-sul/noticias/uffs-e-ifmt-promovem-cursos-de-ferias)

![1610711202phpuqbj4s](https://user-images.githubusercontent.com/31110971/105234346-e2c16f00-5b49-11eb-8973-b2329e9995a2.jpeg)

Link youtube: https://youtu.be/sBQd7_IF8FI

[Pasta Drive](https://drive.google.com/drive/folders/17HfgU4A5fJNaVmiu6UO9Lz08zDzcGqto)

@VIF-Franca, @pedroamaximowski e @rafaguilman creio que vocês podem ficar responsáveis pela série de lives. Caso não tenham disponibilidade, podemos consultar os outros membros da ilha de lives e @practice-uffs/con-midia.

**Comment by MilenaPaz2020** [comment]
Live Finalizada!
Link: https://www.youtube.com/watch?v=sBQd7_IF8FI
