### ISSUE TITLE
Estabelecimento do Protocolo de ações para Lives

### ISSUE THREAD

**Issue by MilenaPaz2020** [practice-uffs/programa#399]
O objetivo dessa issue é estabelecer um protocolo de ações para o atendimento de live destinado aos clientes,
contendo critérios e um passo a passo para que a transmissão ocorra da melhor forma possível. O que inclui:
- Forma de contato entre cliente e o bolsista responsável pela live;
- O tempo em que TODOS devem estar na sala antes de iniciar a transmissão;
- Conectividade dos participantes;
- Local/posicionamento da câmera do palestrante;
- Tempo para o teste de compartilhamento de tela e microfone;
- Formato do arquivo a ser compartilhado (preferencialmente que os slides estejam salvos em PDF);
- Preenchimento completo e correto do roteiro;
(É provável que hajam mais critérios do que os listados acima)

O protocolo está [nessa pasta](https://drive.google.com/drive/u/0/folders/1-iJUedwqyEHvqFrDeKM4KeiFyzv9nBkl), e a proposta é que ele esteja incluso ao roteiro (que pode passar por atualizações).
A participação dos membros da ilha de lives é muito importante para uma boa organização desse documento. Favor, fazer os apontamentos necessários. 
Fica aberto, também, ao pessoal do @practice-uffs/con-midia  para sugestões/críticas.

**Comment by MilenaPaz2020** [comment]
Pessoal, uma versão inicial do protocolo está pronta. Peço que revisem criticamente, apontando o que precisa ser melhorado e o que falta complementar. :)

**Comment by MaNegrao** [comment]
Eu gostei bastante, coloquei alguns apontamentos no texto, mas no geral tá ótimo

**Comment by luizatonial** [comment]
Gostei bastante do protocolo, parabéns! 

Uma coisa só que fiquei em dúvida seria só se mencionamos ou não o contato antes das lives. 
Não sei se com o novo aplicativo não teremos mais que realizar a comunicação via WhatsApp, mas caso ela se mantenha, acho importante colocarmos um tópico abordando isso.

Além disso, fiz alguns apontamentos e sugestões no texto também, mas acredito que esta parte de revisão textual possa ser finalizada com o auxílio do conteúdo.

**Comment by MilenaPaz2020** [comment]
> Gostei bastante do protocolo, parabéns!
> 
> Uma coisa só que fiquei em dúvida seria o fato de mencionarmos ou não o contato antes das lives.
> Não sei se com o novo aplicativo não teremos mais que realizar a comunicação via WhatsApp, mas caso ela se mantenha, acho importante colocarmos um tópico abordando isso.
> 
> Além disso, fiz alguns apontamentos e sugestões no texto também, mas acredito que esta parte de revisão textual possa ser finalizada com o auxílio do conteúdo.

Obrigada pelos apontamentos, pessoal!
A questão do contato com o solicitante foi algo que me intrigou também. Falar com a pessoa responsável pelo apoio geral por WhatsApp durante a live facilita a agilidade do contato, o complicado é usar a conta pessoal para fazer isso.

**Comment by robisonjose** [comment]
Bom dia pessoal. 

O protocolo está ficando ótimo. Simples e claríssimo. Vocês são muito brabos. 

E sobre a questão do contato com o solicitante: Caímos novamente na questão do zipzop para o programa.

**Comment by MaNegrao** [comment]
@lcaimi será que conseguimos finalmente encaminhar um número para o programa? nem que seja provisório e adiquirido por nós mesmos, só para concentrar as comunicações em um lugar só

**Comment by MilenaPaz2020** [comment]
Fiz as alterações sugeridas. Aguardo os apontamentos dos demais membros da ilha de lives.

**Comment by luizatonial** [comment]
Não sei se isso entraria exatamente no protocolo, acho que seria algo mais do roteiro...

Poderíamos pedir que se o solicitante deseja inserir/modificar qualquer elemento que esteja fora do padrão do nosso overlay ele deve nos informar antes, no momento do preenchimento do roteiro, para verificarmos se a alteração pode ser feita e termos tempo pra fazer tal alteração.

**Comment by MaNegrao** [comment]
> Não sei se isso entraria exatamente no protocolo, acho que seria algo mais do roteiro...
> 
> Poderíamos pedir que se o solicitante deseja inserir/modificar qualquer elemento que esteja fora do padrão do nosso overlay ele deve nos informar antes, no momento do preenchimento do roteiro, para verificarmos se a alteração pode ser feita e termos tempo pra fazer tal alteração.

Creio que vá nos dois, no protocolo pedindo pra que informe a alteração e no roteiro o local pra informar

**Comment by MilenaPaz2020** [comment]
Pessoal, fiz mais algumas alterações no protocolo. Inclui o contato com o solicitante e o ajuste no overlay de lives (utilizei o termo 'layout' para facilitar a compreensão.
Se não houver mais nenhuma alteração para ser feita podemos pedir para fazerem a revisão textual. Aguardo o feedback de vocês.

**Comment by MaNegrao** [comment]
Por mim podemos pedir revisão textual, está excelente. O quão mais rápido pudermos utilizá-lo melhor

**Comment by robisonjose** [comment]
Concordo com o @MaNegrao. Não vejo - com meus olhos de ignorância - nada que possa ser mudado/melhorado.

**Comment by luizatonial** [comment]
Quando finalizarmos e incluirmos os links, talvez seja interessante colocar na parte sobre o layout o link da página de "Portfólio" do site do PRACTICE, que tem um exemplo do nosso overlay. 

Mas achei que está muito bom também! Acredito que alguém da @practice-uffs/con-conteudo já possa revisar.

**Comment by alessandrapedrotti** [comment]
@thaliafriedrich favor tratar da revisão desse documento.

**Comment by thaliafriedrich** [comment]
Fiz a revisão textual, só foram necessárias pequenas correções. E deixei uns comentários para verificarem. 
Também achei o texto ótimo, está bem escrito e fácil de entender todos os procedimentos. Parabéns!

**Comment by MilenaPaz2020** [comment]
Fiz as ultimas alterações do Protocolo para transmissões ao vivo. Retirei os links dos vídeos que ainda não foram publicados e o do formulário de satisfação que ainda não está em uso. Em breve deveremos retornar a esse documento para fazer as devidas alterações. 
Um arquivo em PDF está salvo na pasta de saída.
@MaNegrao, para qual pasta do mídia devo mover esse arquivo? Será incluído no template de issues para live?

**Comment by MaNegrao** [comment]
Na pasta documentos, dentro da pasta Equipe Multimídia. E daí podemos encerrar a issue, beleza?

**Comment by MilenaPaz2020** [comment]
Feito!
