### ISSUE TITLE
Texto padrão de apresentação do projeto para utilização em redes sociais

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#40]

**Comment by alessandrapedrotti** [comment]
Pessoal, fiz uma pesquisa rápida e o limite de caracteres para a bio do instagram é 150 e para o twitter é 160. Então elaborei um parágrafo bem simples que ficasse dentro desses limites:

**Este é o Programa PRACTICE (Programa de Ampliação e Consolidação de Tecnologias e Inovação no Contexto Educacional) da UFFS. Saiba mais:
(links do github e site)**

Não acho que só a bio será suficiente para apresentar o projeto nas redes sociais, então elaborei uma ideia de primeira postagem:

**Você sabe o que é o PRACTICE?
O programa PRACTICE (Programa de Ampliação e Consolidação de Tecnologias e Inovação no Contexto Educacional) é um projeto multi-campi da Universidade Federal da Fronteira Sul. Estamos a serviço da comunidade acadêmica para criar ferramentas e materiais de qualidade que auxiliem no processo ensino/aprendizagem, visando empoderar tecnologicamente pessoas no contexto da educação.**

Se puderem interagir aqui com suas opiniões, seria ótimo!

**Comment by elisribas** [comment]
Achei ótimo! Fiz algumas sugestões no texto.

Você sabe o que é o PRACTICE?
O PRACTICE (Programa de Ampliação e Consolidação de Tecnologias e Inovação no Contexto Educacional) é um programa multi-campi da Universidade Federal da Fronteira Sul, UFFS. Estamos à serviço **da comunidade acadêmica** para criar ferramentas e conteúdos educacionais que contribuam com os processos de ensino e aprendizagem. Visa empoderar pessoas para usar tecnologias na educação.

**Comment by VIF-Franca** [comment]
Creio que é aberta para a **comunidade acadêmica**. 

Vou deixar umas sugestões dentro dos 150 caracteres, creio que para o Facebook os dois acima estão ótimos. Deixem sugestões 😊 ...


**1)	O PRACTICE da UFFS está a serviço da universidade para desenvolver ferramentas tecnológicas que contribuam com os processos de ensino/aprendizagem. (147 caracteres);**

**2)	O PRACTICE está a serviço da comunidade acadêmica da UFFS para desenvolver ferramentas tecnológicas que auxiliem nos processos de ensino/aprendizagem. (150 caracteres);**

**3)	O programa PRACTICE da UFFS está a serviço da universidade para desenvolver ferramentas tecnológicas que contribuam com os processos de ensino e aprendizagem. (158 caracteres);**

**4)	O programa PRACTICE está a serviço da comunidade acadêmica da UFFS para desenvolver ferramentas tecnológicas que auxiliem nos processos de ensino/aprendizagem. (159 caracteres).**


PS. Creio que podemos adicionar a localização dos campis (Chapecó-SC & Laranjeiras do Sul-PR) no item específico nas redes sociais. 

cc @Dovyski @lcaimi @phdmauricio

**Comment by Dovyski** [comment]
Eu gostei bastante de todos os textos colocados nessa issue. Qualquer um deles, ao meu ver, será boom. Entretanto, eu acho os textos do @VIF-Franca um pouco mais explicativos para a bio.

O texto da primeira postagem que a @alessandrapedrotti está excelente.

**Comment by Dovyski** [comment]
> **comunidade acadêmica** eu fiquei em dúvida se o serviço é aberto para a comunidade acadêmica (alunos e servidores, isso?)

Eu particularmente acho legal o termo "comunidade acadêmica", porque queremos ajudar todos de certa forma. Inclusive o estúdio é aberto para qualquer um (professor, TAE e aluno).

**Comment by oigor** [comment]
Devido ao Youtube possuir uma descrição bem mais ampla que as redes como Instagram e Twitter, inseri o texto da primeira publicação na parte da descrição.

**Comment by elisribas** [comment]
@Dovyski 
Concordo que os textos propostos pelo @VIF-Franca estão ótimos.
Sanada minha dúvida sobre o termo **comunicade acadêmica**, recomendo que usemos a expressão **ensino e aprendizagem** em nossos textos, pois são processos diferentes e separados e não _ensino/aprendizagem_. :)

**Comment by VIF-Franca** [comment]
Perfeito, 

Adicionei um arquivo no DRIVE com o modelo.

**Comment by phdmauricio** [comment]
Ficaram ótimos.
