### ISSUE TITLE
Mapeamento de todas as Lives auxiliadas pelo PRACTICE

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#400]
Assim como fizemos com os vídeos externos e internos, é interessante que façamos o mapeamento de todas as lives produzidas e auxiliadas pelo PRACTICE. 

Para isso podemos usar a planilha criada para os vídeos externos na issue #370 com alguns ajustes.

Eu sugiro que coloquemos as seguintes colunas adicionais:

- Link para transmissão
- Data da Transmissão
- Onde foi transmitida
- Número de vizualizações
- (sugestão) As lives que são dos youtube's que temos acesso há como coletar mais dados além dos anteriores

E remover a coluna de sprint inicial, visto que as lives acabam ficando apenas em uma Sprint.

Para facilitar a busca pelas lives temos as issues de criação dos flyers, todas as lives feitas pelo practice estão nelas: #395, #240, #95 e #87. 

Se tiverem alguma sugestão fiquem à vontade:

[Pasta Drive](https://drive.google.com/drive/u/0/folders/17WqMg4DTyOYPMVsZ3d0JrGEem0H_r8yS)

CC: @practice-uffs/con-midia /ilha-lives

**Comment by MilenaPaz2020** [comment]
Eu posso assumir essa tarefa! Conto com os apontamentos da galera do @practice-uffs/con-midia/ilha-lives :D

**Comment by luizatonial** [comment]
se ajudar, eu já tenho as lives que realizei listadas, de quando fiz o relatório de produtividade:

- Live Formatura Curso de Agronomia do Campus Erechim - 22/12 às 18h #368 
- Live Aula Aberta Pedagogia do Campus Erechim. - 07/12 - 19:15 #324 
- Live PPGEL - Mesa Redonda: Desafios da Construção do Conhecimento - 01/12 - 19:30h #279
- Live PPGEL - Minicurso Introdução à periferia esquerda dia 2 - 08/12 - 9h #278
- Live - A educação necessária para um mundo sem pandemia - 01/12 9h #260
- Live 3 - Dia Nacional da Leitura - 31/10 - 15h #219

acredito que todas tenham, no fim da issue, os comentários com links que redirecionam para onde está a transmissão.

**Comment by MilenaPaz2020** [comment]
Creio que todas as lives já estão inseridas na planilha. Obrigada @robisonjose  pelo eficiente e rápido trabalho!

 Ainda falta a maioria dos contatos dos solicitantes e o acesso à algumas contas do Youtube como a do NAP, Pró Reitoria e UFFS Laranjeiras do Sul, para a coleta de alguns dados das transmissões. @MaNegrao pode disponibilizar o acesso?

**Comment by MaNegrao** [comment]
Vou buscar o do NAP e te envio. O da PROAE temos salvo no drive em algum lugar. O de laranjeiras @VIF-Franca pode nos ajudar? 

Os solicitantes eu vou colocar os contatos. 

Podemos fechar a issue e criar uma cópia e mover para a pasta do mídia

**Comment by robisonjose** [comment]
Estou dando uma revisada, tem umas datas que estão erradas e acho que tem algumas lives que estão faltando (ou eu estou duplicando). Assim que revisar tudo fecho a issue. Pode ser?

**Comment by MaNegrao** [comment]
Posso auxiliar nessa revisão, muitas das lives fui eu que estive com responsável

**Comment by robisonjose** [comment]
Eu ainda estou adicionando umas aleatórias que ficaram perdidas em meio ao caos. Uma loucura.

**Comment by robisonjose** [comment]
A princípio a planilha está pronta. 

Assim que a revisão for feita, acredito que a issue possa ser fechada e a planilha movida para a pasta do Mídia. Aí qualquer alteração e as futuras atualizações fizemos lá. 

Que trampo! Um parabéns adiantado a todas as pessoas envolvidas nesses mapeamentos.

BRABÍSSIMAS.

**Comment by MaNegrao** [comment]
Pessu, eu tenho uma sugestão e é uma coisa que eu fiz na planilha de vídeos, como estamos estruturando agora podemos definir um periodo de 3 meses ou 6 meses para cada pagina da planilha, pra não ficar um milhão de coisa na mesma pagina. 

De inicio fariamos a primeira pagina como sendo Jun/20 - Jan/21, e dai a outra podemos definir outro periodo

**Comment by MaNegrao** [comment]
Terminei de acrescentar e revisar no geral, acrescentei os contatos e nomes. Creio que podemos decidir sobre o meu ultimo comentario e em seguida fechar e mover a planilha, os dados adicionais de engajamento etc poderão ser colocados depois

**Comment by robisonjose** [comment]
O relatório dos bolsistas vai ser a cada quantos meses? Poderíamos fazer com que as coisas sejam feitas "simultaneamente".

**Comment by MaNegrao** [comment]
Trimestralmente.

Não vejo impedimentos em fazer dessa forma, até acho melhor

> O relatório dos bolsistas vai ser a cada quantos meses? Poderíamos fazer com que as coisas sejam feitas "simultaneamente".

**Comment by robisonjose** [comment]
Ah então podemos fazer assim, para que a "finalização" do mapeamento coincida com a escrita do relatório e com o fim do trimestre.  O problema só vai ser que teríamos que atualizar o "mapeamento finalizado" depois de um mês da inserção da última live. Ou seja, se por acaso fizermos uma live um dia antes de finalizar o trimestre, teriamos que voltar um mês depois para atualizar ela, e isso me parece meio ruim. Poderíamos, em relação às lives, utilizar apenas os números obtidos ao vivo, que ai ela fica pronta "na hora".

**Comment by MaNegrao** [comment]
Vamos manter os dados, porém só das lives feitas no canal do PRACTICE, visto que fica mais facil coletar essas informações e quanto ao tempo depois da transmissão a gente pode discutir futuramente.

O que eu sugiro é colocarmos as lives de semana passada já na nova guia. 

No momento podemos finalizar essa planilha agora e quando tivermos a reunião discutir essas questões.

**Comment by MaNegrao** [comment]
Vou encerrar a issue para colocar a planilha em uso, as alterações faltantes podem ser feitas na planilha na pasta do mídia
