### ISSUE TITLE
Desenvolvimento sobre o tópico "Como fazer um plano de texto"

### ISSUE THREAD

**Issue by isabelirk** [practice-uffs/programa#401]
Esta issue esta relacionada com a issue #314; é uma subtarefa referente ao método Como fazer um plano de texto; deve ser realizado o desenvolvimento da seção 1 e 2 do manual de apoio dos estudantes deste tópico, que abrange: o que é o método, quais são seus objetivos, como podemos utilizá-lo, como podemos introduzir ele nos estudos, e se for necessário ou interessante, trazer algum exemplo. Este será desenvolvido junto com a ajuda da @alessandrapedrotti.

**Comment by isabelirk** [comment]
Link da pasta no drive: https://drive.google.com/drive/folders/10SrsU54DzWfMCUbAeDdbBs49A4bJe3No

**Comment by alessandrapedrotti** [comment]
Farei a reunião de algumas leituras que podem contribuir para a elaboração desse tópico.

**Comment by alessandrapedrotti** [comment]
Coloquei na pasta do drive um artigo curto que exemplifica a criação de um plano de texto, que pode ser utilizado como base para a escrita do tópico.

**Comment by isabelirk** [comment]
Bom dia @alessandrapedrotti, finalizei a minha primeira versão do texto. Aguardo seu retorno.

**Comment by alessandrapedrotti** [comment]
> Bom dia @alessandrapedrotti, finalizei a minha primeira versão do texto. Aguardo seu retorno.

Farei a revisão ainda essa semana.

**Comment by thaliafriedrich** [comment]
Revisei e deixei os comentários ao longo do texto para verificar.
O texto está bem escrito e com clareza. Achei o último parágrafo ótimo para finalizar o tópico. 

Só percebo que a linguagem desse tópico está mais formal quando comparado aos outros do manual, o que é normal, já que o assunto é mais "formal", mas sugiro, se for possível, rever alguns termos e deixar mais próximo do cotidiano para estudantes.

**Comment by isabelirk** [comment]
Boa tarde @thaliafriedrich, já realizei os ajustes. Eu fiz algumas leituras de revisão, para tentar simplificar o texto como voce havia comentado, porém se tratando de um assunto que não tenho muito domínio, acabou que não consegui deixa-lo com um aspecto menos "formal". Enfim, aguardo uma ultima revisão sua para finalizar a issue.
Atenciosamente.

**Comment by thaliafriedrich** [comment]
Boa tarde! 
Tudo bem manter assim, então. Pelo assunto é compreensível que seja mais formal. 
Revisei novamente, só fiz uma alteração em "a estrutura textual influencia", nesse caso não deve ter o acento mesmo.

**Comment by isabelirk** [comment]
Texto revisado e ajustado!
