### ISSUE TITLE
Desenvolvimento sobre o tópico "Facilitadores Bônus: flip"

### ISSUE THREAD

**Issue by isabelirk** [practice-uffs/programa#402]
Esta issue esta relacionada com a issue #314 ; é uma subtarefa referente ao facilitador do app e site "Flip"; deve ser realizado o desenvolvimento referente a seção 3 do manual de apoio dos estudantes deste tópico, que abrange: o que é, quais são seus objetivos, como podemos utilizá-lo, vantagens e desvantagens. Caso seja interessante ou necessário, a inclusão de imagens do mesmo.

**Comment by isabelirk** [comment]
Link da pasta no drive: https://drive.google.com/drive/folders/1w_pBZpgikD1gnZJfhFW2q8S5rk2sDmWe

**Comment by isabelirk** [comment]
Texto finalizado aguardando revisão.

**Comment by thaliafriedrich** [comment]
Fiz a revisão. Nesse não deixei comentários, pois acredito que está bem completo. Gostei das funções do aplicativo em itens e da forma como foi finalizado. Só fiz algumas correções ao longo do texto.

**Comment by isabelirk** [comment]
Conforme o retorno, esta issue esta sendo finalizada.
