### ISSUE TITLE
Projeto Newsletter PRACTICE

### ISSUE THREAD

**Issue by morgana-mo** [practice-uffs/programa#403]
Esse é um novo projeto que passará a ser desenvolvido dentro do programa, com este projeto buscaremos desenvolver Newsletters sobre o programa, a ideia é se ter um somente para os bolsistas do programa  afim de criar um fluxo de comunicação com as todas as equipes, e um que seja direcionado a comunidade acadêmica da UFFS ambos com periodicidade mensal.
Inicialmente precisamos de alguns aportes para o desenvolvimento desse projeto que dará um visibilidade enorme para o PRACTICE

- [x] Criação da persona PRACTICE (#405)

- [x] Desenvolvimento de uma identidade visual 

- [x] Definição dos tipos de colunas  e pautas a serem publicadas (#519)

- [ ] Meios de levar o Newsletter para o IGTV do Instagram do PRACTICE

- [ ] Organização de um repositório no site com os Newsletter

[Pasta da Issue](https://drive.google.com/drive/folders/1NhmRpXTCkcKD9Vvxo4xRaXWKTzZdw4XO)

**Comment by TaynaraCh** [comment]
To muito feliz por fazer parte desse projeto!!!!

Dei uma pesquisada sobre algumas coisas dos tópicos, vocês poderiam comentar sobre o que andaram pensando e como pretendem abordar e elaborá-los?

**Comment by morgana-mo** [comment]
> To muito feliz por fazer parte desse projeto!!!!
> 
> Dei uma pesquisada sobre algumas coisas dos tópicos, vocês poderiam comentar sobre o que andaram pensando e como pretendem abordar e elaborá-los? 

Acho que pra facilitar a gente vai marcar uma reunião com todas as envolvidas no projeto,eu só estou aguardando a reunião que vai discutir alguns pontos dos relatórios pra gente dar prosseguimento.

**Comment by MaNegrao** [comment]
Pelo que comentamos hoje na reunião de líderes, a @luizatonial irá representar o mídia nessa ideia maravilhosa :D

Outro ponto que surgiu foi que no mídia temos uma série de vídeos carinhosamente apelidados de Telecurso2000, que são vídeos curtos voltados para os próprios membros do programa resolverem problemas rápidos. 

Parabéns pelo projeto pessu 🎉

**Comment by GessicaZanon** [comment]
> > To muito feliz por fazer parte desse projeto!!!!
> > Dei uma pesquisada sobre algumas coisas dos tópicos, vocês poderiam comentar sobre o que andaram pensando e como pretendem abordar e elaborá-los?
> 
> Acho que pra facilitar a gente vai marcar uma reunião com todas as envolvidas no projeto,eu só estou aguardando a reunião que vai discutir alguns pontos dos relatórios pra gente dar prosseguimento.

Perfeito! Ansiosa para discutir sobre esse projeto (:

**Comment by morgana-mo** [comment]
Dei uma olhada na planilha de férias e vi que estamos todas atuando, por isso criei um [Doodle](https://doodle.com/poll/n36k8gktzd2nci79?utm_source=poll&utm_medium=link) para escolhermos o horário da reunião e um dia em que todas estejam disponíveis. Aguardo o retorno de vocês!

**Comment by TaynaraCh** [comment]
> Dei uma olhada na planilha de férias e vi que estamos todas atuando, por isso criei um [Doodle](https://doodle.com/poll/n36k8gktzd2nci79?utm_source=poll&utm_medium=link) para escolhermos o horário da reunião e um dia em que todas estejam disponíveis. Aguardo o retorno de vocês!

Respondido!

**Comment by luizatonial** [comment]
Respondi também!

**Comment by anacarolinamorigi** [comment]
> Dei uma olhada na planilha de férias e vi que estamos todas atuando, por isso criei um [Doodle](https://doodle.com/poll/n36k8gktzd2nci79?utm_source=poll&utm_medium=link) para escolhermos o horário da reunião e um dia em que todas estejam disponíveis. Aguardo o retorno de vocês!

Respondido!

**Comment by morgana-mo** [comment]
Gente em nenhum dia todas podemos, os dias com maior número de votos são quinta e sexta-feira das 18 às 19 horas. As que não marcaram como possível esse horário há uma chance de adaptação da agenda para fazermos a reunião?
Pergunto pois sei que alguns estão tendo aula.

**Comment by GessicaZanon** [comment]
> Gente em nenhum dia todas podemos, os dias com maior número de votos são quinta e sexta-feira das 18 às 19 horas. As que não marcaram como possível esse horário há uma chance de adaptação da agenda para fazermos a reunião?
> Pergunto pois sei que alguns estão tendo aula.

De minha parte, qualquer um desses 2 dias nesse horário, está bom!

**Comment by luizatonial** [comment]
> Gente em nenhum dia todas podemos, os dias com maior número de votos são quinta e sexta-feira das 18 às 19 horas. As que não marcaram como possível esse horário há uma chance de adaptação da agenda para fazermos a reunião?
> Pergunto pois sei que alguns estão tendo aula.

Pra mim seria melhor na quinta-feira.

**Comment by anacarolinamorigi** [comment]
> Gente em nenhum dia todas podemos, os dias com maior número de votos são quinta e sexta-feira das 18 às 19 horas. As que não marcaram como possível esse horário há uma chance de adaptação da agenda para fazermos a reunião?
> Pergunto pois sei que alguns estão tendo aula.

Para mim ficaria meio complicado nos dois dias, mas ainda mais viável na quinta. Talvez chegue um pouco mais tarde que o horário combinado, pois tenho aula prática até as 18h e fiquei sabendo disso somente hoje. 😅

**Comment by morgana-mo** [comment]
Criei e reunião para a quinta-feira as 18:30 pois a @anacarolinamorigi  tem aula, confiram se vocês receberam o convite da reunião no email!
