### ISSUE TITLE
Divulgação dos vídeos do Youtube

### ISSUE THREAD

**Issue by morgana-mo** [practice-uffs/programa#404]
Creio que com o início das postagens dos vídeos desenvolvidos pelo programa no Youtube seria importante termos uma imagem de divulgação para postarmos nas redes sociais nos stories como as criadas na #283 com o foco nos vídeos
[Pasta da issue](https://drive.google.com/drive/folders/1tfSSa7NDYGtA5gir_kESq817r57XZuRX)

**Comment by morgana-mo** [comment]
Três [modelo prontos](https://drive.google.com/drive/folders/1GC-8rwFd4lEsRM47th05MOpzecXO5-Bm)aqui

**Comment by alessandrapedrotti** [comment]
Gostei bastante da opção em bloco!

**Comment by morgana-mo** [comment]
Closed #404
