### ISSUE TITLE
Desenvolvimento da Persona para as mídias sociais do PRACTICE

### ISSUE THREAD

**Issue by anacarolinamorigi** [practice-uffs/programa#405]
Seguindo o Projeto Newsletter da issue #403, esta issue refere-se ao desenvolvimento da persona para as mídias sociais do programa. Como buscamos tornar a persona o mais acessível, humanizado e direcionado possível, pensei em desenvolvê-la a partir da nossa equipe, uma vez que também consumimos o que é criado dentro do programa. 

Por isso, formulei um [Google Forms](https://forms.gle/ztm83uE14w8mxcaP9) para termos um real embasamento, sendo algo bem rápido e tranquilo para ser respondido. 

Além disso peço que comentem e deem as suas sugestões referente a esse desenvolvimento!

**Comment by Dovyski** [comment]
Todos @practice-uffs/todos precisam contribuir com essa, por favor.

**Comment by isabelirk** [comment]
Bom dia, já respondi.

**Comment by andrewmsilva** [comment]
Respondido 👍

**Comment by Claudineia-VR** [comment]
Bom dia, respondido!

**Comment by TaynaraCh** [comment]
Respondido!

**Comment by rafaguilman** [comment]
Respondido !! :)

Em ter., 26 de jan. de 2021 às 10:28, Fernando Bevilacqua <
notifications@github.com> escreveu:

**Comment by thaliafriedrich** [comment]
Respondido!

**Comment by luizdameda** [comment]
Respondido!

**Comment by luizatonial** [comment]
Respondido

**Comment by MaNegrao** [comment]
Respondido!

**Comment by MilenaPaz2020** [comment]
Respondido!

**Comment by robisonjose** [comment]
Respondido

**Comment by brendaellen** [comment]
Respondido!

**Comment by GessicaZanon** [comment]
Respondido! :)

**Comment by pedroamaximowski** [comment]
Respondido !.

**Comment by VIF-Franca** [comment]
Feito <3

**Comment by CleissonVieira** [comment]
Respondido s3

**Comment by jeanchilger** [comment]
Feito :smile:.

**Comment by arufonsekun** [comment]
Feito ;)

**Comment by amandasegattob** [comment]
respondido

**Comment by oraphaBorges** [comment]
Respondido

**Comment by anacarolinamorigi** [comment]
Obrigada pelas respostas, pessoal! Vocês foram de grande ajuda!

As respostas para o desenvolvimento da persona encontram-se [aqui](https://drive.google.com/drive/folders/1A80jHNaatSAJ0xdG_UqykXZsWsRnZVgn?usp=sharing). Creio que já podemos começar a estruturação dela.

**Comment by alessandrapedrotti** [comment]
Se todas as respostas já foram recolhidas, a issue pode ser fechada.

**Comment by anacarolinamorigi** [comment]
Boa noite, gente!

Fiz um compilado dos dados da forms sobre a persona e fiz uma [primeira versão](https://docs.google.com/document/d/172-YPERfcjg8iwX7totRYVQEGD9IPufBIkbNukPe8EE/edit?usp=sharing) sobre. Acredito que temos de mexer um pouquinho mais na descrição da persona, como se fosse um personagem de ficção. 
Seria bom se todas pudessem colocar um pouquinho de nós nisso, por isso mexem e modifiquem a vontade!

**Comment by GessicaZanon** [comment]
> Boa noite, gente!
> 
> Fiz um compilado dos dados da forms sobre a persona e fiz uma [primeira versão](https://docs.google.com/document/d/172-YPERfcjg8iwX7totRYVQEGD9IPufBIkbNukPe8EE/edit?usp=sharing) sobre. Acredito que temos de mexer um pouquinho mais na descrição da persona, como se fosse um personagem de ficção.
> Seria bom se todas pudessem colocar um pouquinho de nós nisso, que ficará maravilhoso, por isso mexem e modifiquem a vontade!

Estou escrevendo algumas coisinhas lá, fiquem a vontade para mexer também ou fazer novas versões.. Isso vai ficar incrível.

PS: Será feito alguma reunião para discutir melhor a persona, ou vamos desenvolvendo por alí mesmo?

**Comment by anacarolinamorigi** [comment]
> > Boa noite, gente!
> > Fiz um compilado dos dados da forms sobre a persona e fiz uma [primeira versão](https://docs.google.com/document/d/172-YPERfcjg8iwX7totRYVQEGD9IPufBIkbNukPe8EE/edit?usp=sharing) sobre. Acredito que temos de mexer um pouquinho mais na descrição da persona, como se fosse um personagem de ficção.
> > Seria bom se todas pudessem colocar um pouquinho de nós nisso, que ficará maravilhoso, por isso mexem e modifiquem a vontade!
> 
> Estou escrevendo algumas coisinhas lá, fiquem a vontade para mexer também ou fazer novas versões.. Isso vai ficar incrível.
> 
> PS: Será feito alguma reunião para discutir melhor a persona, ou vamos desenvolvendo por alí mesmo?

Creio que podemos sim marcar uma reunião para discutir o desenvolvimento da Persona, fica até mais prático de sanar as dúvidas.

**Comment by TaynaraCh** [comment]
Adicionei alguns comentários no doc, achei melhor do que modificar o que já foi escrito, vou escrever uma nova versão, acho que uma reunião interessante pra discutirmos sobre, fica mais prático.

**Comment by GessicaZanon** [comment]
Estou escrevendo uma segunda versão da "persona" de acordo com as sugestões já colocadas (para não mexer no que já foi escrito). A ideia é justamente que vocês leiam, coloquem suas opiniões, dizendo o que de cada versão está melhor, ou sugestões de como ficaria melhor (tanto em relação a escrita quanto personalidade, gostos e afins), assim vamos adaptando até chegar em uma única versão :) Fiquem super a vontade para colocarem suas ideias.
