### ISSUE TITLE
Associar Ramal à um WhatsApp Busniess PRACTICE

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#406]
Essa issue tem como objetivo solucionar a falta de um número de whatsapp para o PRACTICE na comunicação direta com os solicitantes. 

Foi sugerido durante a reunião de líderes do dia 26/01/21 a utilização de um ramal da universidade para o whatsapp.

@practice-uffs/lideres @practice-uffs/con-midia @Dovyski @lcaimi

**Comment by MilenaPaz2020** [comment]
Essa issue pode ser encerrada?

**Comment by MaNegrao** [comment]
Pode sim, claro, vou encerrar
