### ISSUE TITLE
Desenvolvimento sobre o tópico: "Facilitador bônus: i love pdf"

### ISSUE THREAD

**Issue by brendaellen** [practice-uffs/programa#408]
Esta questão está relacionada com a questão #314; é uma subtarefa referente ao facilitador bônus "I Love PDF"; deve ser realizado o desenvolvimento referente a uma seção 3 do manual de apoio dos estudantes deste tópico, que abrange: o que é, quais são seus objetivos, como podemos utilizar-lo, vantagens e desvantagens. Caso seja interessante ou necessário, a inclusão de imagens do mesmo.

**Comment by brendaellen** [comment]
Link da pasta: https://drive.google.com/drive/folders/1OkiLgVfh55E327v7NTnOf_5SAIibOK2x

**Comment by brendaellen** [comment]
Texto finalizado. @thaliafriedrich você pode fazer a revisão por gentileza :)

**Comment by thaliafriedrich** [comment]
Revisão realizada. O texto ficou muito bom, fiz pequenas alterações/correções.
- Uma sugestão seria acrescentar que o iLovePDF visa facilitar a organização, edição e formatação de trabalhos acadêmicos em formatos PDF, para explicar melhor onde diz que auxilia na "realização de pesquisas e estudos".
- Fiquei em dúvida se o iLovePDF é utilizado também para ler documentos PDF. Eu acredito que não, e deixei isso destacado no 1º parágrafo, se puder conferir e alterar depois.

**Comment by brendaellen** [comment]
> Revisão realizada. O texto ficou muito bom, fiz pequenas alterações/correções.
> 
> * Uma sugestão seria acrescentar que o iLovePDF visa facilitar a organização, edição e formatação de trabalhos acadêmicos em formatos PDF, para explicar melhor onde diz que auxilia na "realização de pesquisas e estudos".
> * Fiquei em dúvida se o iLovePDF é utilizado também para ler documentos PDF. Eu acredito que não, e deixei isso destacado no 1º parágrafo, se puder conferir e alterar depois.

Obrigada pelas sugestões @thaliafriedrich . Finalizei as alterações, e gostaria que você conferisse o texto novamente para que eu possa fechar a issue.

**Comment by thaliafriedrich** [comment]
> > Revisão realizada. O texto ficou muito bom, fiz pequenas alterações/correções.
> > 
> > * Uma sugestão seria acrescentar que o iLovePDF visa facilitar a organização, edição e formatação de trabalhos acadêmicos em formatos PDF, para explicar melhor onde diz que auxilia na "realização de pesquisas e estudos".
> > * Fiquei em dúvida se o iLovePDF é utilizado também para ler documentos PDF. Eu acredito que não, e deixei isso destacado no 1º parágrafo, se puder conferir e alterar depois.
> 
> Obrigada pelas sugestões @thaliafriedrich . Finalizei as alterações, e gostaria que você conferisse o texto novamente para que eu possa fechar a issue.

Conferido! Tudo certo, pode ser finalizado.

**Comment by brendaellen** [comment]
Com a revisão concluída, esta issue já pode ser finalizada.
