### ISSUE TITLE
Envio de pesquisa de satisfação para os clientes

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#409]
Passamos pela criação da pesquisa de satisfação, agora iremos aplicar, para que em breve conseguimos divulgar os resultados obtidos do PRACTICE. 

O questionário devidamente ajustado encontra-se na issue #230. 

Para a elaboração precisaremos desenvolver as seguintes tarefas para obter com êxito, sendo assim @Claudineia-VR tu pode me dar um help. 

1. Elaborar um banco de dados com todos os clientes ATENDIDOS E OS QUE TAMBEM NÃO FORAM ATENDIDOS, @Claudineia-VR:
_Obs: o banco de dados deve conter ao menos os seguintes itens, os nome, os endereços de e-mail e as issues._ 

- [x] Nessa issue #400 poderá encontrar o mapeamento das **lives** realizadas com o apoio do PRACTICE; 
- [x] Logo na issue #370  encontrará a listagem de **vídeos** editados pelo programa;
- [x] Mapear os clientes de que solicitaram demandas de **edição de áudio**; 
- [x] Mapear os clientes que solicitaram demandas de **criação de identidade visual** (complexas e simples); 
- [x] Listar os demandantes que solicitaram as demandas de **criação de conteúdo**, revisão e diagramação de texto (conteúdo); 
- [x] Mapear os clientes que **não foram atendidos**, creio que as demandas vão ser 

- [x] 2. Compilar todos os dados em uma planilha do drive separados pelos produtos e serviços oferecidos pelo PRACTICE; 

- [x] 3. Acho justos separar em dois espaço temporais nesse primeiro momentos, todas as demandas de 2020 ser o primeiro lote, após isso criar o segundo lote referente ao mês de Janeiro/2021; 

- [x] 4. A ideia e enviar o formulário para a pesquisa de satisfação em Fevereiro/202, após o recesso @VIF-Franca ;

5. Elaborar e-mail modelo para cada uma das demandas @VIF-Franca :
- [x] Lives
- [x] Vídeos
- [x] Edição de áudio
- [x] Criação de identidade visual
- [ ] Não atendidos

**Comment by alessandrapedrotti** [comment]
Adianto que não houveram demandas isoladas de revisão e diagramação, esses serviços foram feitos atrelados a outros projetos, em específico, os slides da série de vídeos do curso de letras.

**Comment by VIF-Franca** [comment]
@Claudineia-VR está ficando show o banco de dados...

**Comment by alessandrapedrotti** [comment]
Como essa issue não foi criada junto com o bot, @Claudineia-VR, podes colocar o link do drive dela aqui?

**Comment by Claudineia-VR** [comment]
O banco de dados se escontra nesta [pasta](https://docs.google.com/spreadsheets/d/1BBYrxi1_FSMUVKDEF4XkAZlEGznrea6FZeBjagw-lYU/edit?pli=1#gid=1555788727).
No momento estou aguardando os dados dos solicitantes atendidos e não atendidos, de criação de conteúdo (@mariagelain ), criação de identidade visual (@estelavilasboas), e os de áudio (@MaNegrao e @VIF-Franca). Todos estão sendo buscados já.

**Comment by VIF-Franca** [comment]
Sobre os áudios, me recordo da seguinte demanda, que inclusive foi um áudio que eu editei em espanhol.  

#111

**Comment by Claudineia-VR** [comment]
Então só temos uma demanda de áudio @VIF-Franca?

**Comment by VIF-Franca** [comment]
Creio que sim, inclusive busquei no GitHub e foi a única que encontrei.

**Comment by Claudineia-VR** [comment]
Certo, então a primeira versão do banco de dados está pronta na pasta já mencionada acima, estou aberta a feedbacks para possíveis melhorias! :)

**Comment by Claudineia-VR** [comment]
Os emails da pesquisa de satisfação foram enviados de acordo com o banco de dados elaborado.

**Comment by alessandrapedrotti** [comment]
Quando os solicitantes responderem ao questionário, criaremos outra issue para a tabulação dos dados. Esta issue já pode ser fechada.
