### ISSUE TITLE
Criar o Guia para equipe con-design

### ISSUE THREAD

**Issue by estelavilasboas** [practice-uffs/programa#410]
Para facilitar a compreensão do nosso fluxo de trabalho e sobre as ferramentas que utilizamos na equipe, devemos criar um Guia para equipe con-design. A ideia surgiu a partir do [Guia para equipe de desenvolvimento](https://github.com/orgs/practice-uffs/teams/dev/discussions/1).
A pasta da issue terá um documento com os principais tópicos a serem abordados para então dar início a escrita.

[Pasta da issue](https://drive.google.com/drive/folders/1oMgdF30EmUK8Ecz-8VpXEV6ekSKX4XQF)

**Comment by TaynaraCh** [comment]
Outra issue será criada e melhor detalhada
