### ISSUE TITLE
Elaboração de texto para os solicitantes

### ISSUE THREAD

**Issue by Claudineia-VR** [practice-uffs/programa#411]
Essa issue consiste na elaboração de um texto para os nossos solicitantes com o objetivo de avisá-los de que no momento estamos em período de organização no programa, devido ao final de mais um semestre letivo, mas assim que possível voltaremos a trabalhar em cima de todas as demandas.

**Comment by alessandrapedrotti** [comment]
Ficarei responsável pela revisão desse texto.

**Comment by Claudineia-VR** [comment]
[Texto para solicitantes](https://docs.google.com/document/d/1ZTlUqybpE-cWnac9XeVHKKZSexatoI4dKtBPRsvqM3Y/edit)

**Comment by alessandrapedrotti** [comment]
texto aprovado! Ele já pode ser enviado aos solicitantes.

**Comment by Claudineia-VR** [comment]
Aguardando o formulário para encaminhar ambos juntos, @VIF-Franca .

**Comment by VIF-Franca** [comment]
Seria a pesquisa de satisfação #230 ? Caso sim, já está finalizado.

**Comment by Claudineia-VR** [comment]
O texto foi enviado por e-mail para todos os nossos solicitantes de acordo com o banco de dados elaborado.
