### ISSUE TITLE
Adequação dos mapeamentos realizados (vídeos internos, externos e lives)

### ISSUE THREAD

**Issue by MilenaPaz2020** [practice-uffs/programa#412]
O objetivo dessa issue é adequar as planilhas de mapeamentos feitos nas issues #370 e #400, colocando o contato dos solicitantes, para que os formulários de satisfação sejam devidamente encaminhados. 

Aproveito para "lembrar de não esquecermos" de manter as planilhas sempre atualizadas. <3

**Comment by MaNegrao** [comment]
Planilha #370 adequada e devidamente localizada no link https://docs.google.com/spreadsheets/d/17fyR7tVs16PX9SGJ8ghkU4jM8W9UoSqlCE3hm2FrOzk/edit?usp=sharing

Podemos encerrar essa issue
