### ISSUE TITLE
Reunião geral do PRACTICE

### ISSUE THREAD

**Issue by Claudineia-VR** [practice-uffs/programa#413]
O objetivo da presente issue é definirmos a data da reunião com todos os membros do programa, com o intuito de nos conhecermos e interagirmos um pouco uns com os outros (@practice-uffs/todos @practice-uffs/ger).

- Os responsáveis pela organização serão os coordenadores;
- Aceitamos sugestões de todos sobre ideias de interação virtual, se tiverem alguma podem comentar aqui;
- A proposta é de que a reunião aconteça entre o dia 10/02 e 12/02 no período da noite, mais especificamente das 19h as 20h30.

Peço que todos respondam este [doodle](https://doodle.com/poll/rc3h23nf5h8ncpg5?utm_source=poll&utm_medium=link) assim que possível para definirmos logo está data, thanks! Os que não puderem em nenhum dos dias mencionados comentem aqui para refletirmos sobre!

**Comment by robisonjose** [comment]
Mas entre os dias 10/02 e 12/02 não é o período de férias de 50% dos bolsistas?

**Comment by CleissonVieira** [comment]
Não tenho certeza do que tens em mente. Segue algumas sugestões:

- Jogos online (como [stop](https://stopots.com/pt/) ou [gartic](https://gartic.io/) acessados pelo navegador) conversando de forma virtual através de alguma plataforma (como o [discord](https://discord.com/) ;
- Dinâmicas com perguntas a serem feitas de forma que todos consigam interagir;
- Gincana virtual;
- Apresentação de talentos, por exemplo tem bolsistas que tocam instrumentos e cantam muito bem (não citarei nomes mas vocês sabem <3), mas pode ser qualquer talento;

**Comment by MaNegrao** [comment]
> Mas entre os dias 10/02 e 12/02 não é o período de férias de 50% dos bolsistas?

A ideia é que seja mais uma confraternização, por isso o periodo escolhido é o periodo de férias entre os semestres, uma vez que todos estarão livres de suas responsabilidades academicas

**Comment by oraphaBorges** [comment]
Olha, para a interação, pensando em uma confraternização, no ano passado eu participei de uma conferencia internacional em que a socialização ocorria no [Gather Tow](https://gather.town/), que é uma plataforma meio joguinho pra isso, você cria um cenário ou usa um já pronto, as pessoas vão entrando nele e recebem um personagem, daí você vai caminhando pelo espaço e quando você se aproxima de alguém a câmera e microfone dessa pessoa abre pra você e vocês podem interagir.
[Aqui](https://www.youtube.com/watch?v=3Qxvfo5cg2k) tem um exemplo.

**Comment by luizdameda** [comment]
Eu gostaria muito de participar, mas só poderei se for na sexta-feira... nós do campus Passo Fundo estamos com o calendário acadêmico em andamento e terei prova dia 10 e dia 11 a noite 🥴😥

**Comment by Claudineia-VR** [comment]
De acordo com o Doodle que obteve 24 participantes, onde: 

- 10/02 recebeu 20 votos;
- 11/02 recebeu 22 votos;
- e 12/02 recebeu 15 votos.

Sendo assim, considerando o dia mais votado pelos membros a reunião geral do PRACTICE acontecerá no dia **11/02/2021, na quinta-feira desta semana, no horário das 19h00 as 20h30**.

**Comment by alessandrapedrotti** [comment]
Foi enviado aos emails de todos os participantes do PRACTICE o convite para o evento. @practice-uffs/todos

**Comment by Claudineia-VR** [comment]
A reunião foi ótima, todos os que se comprometeram a comparecer no dia 11/02 estavam presentes. Revimos um pouco dos números do PRACTICE até hoje, como o total de issues abertas, de emails respondidos entre outros, além disso pudemos interagir e conhecer melhor os colegas de trabalho.
