### ISSUE TITLE
Elaboração da devolutiva dos relatórios 

### ISSUE THREAD

**Issue by Claudineia-VR** [practice-uffs/programa#414]
Estamos responsáveis pela elaboração de um texto, que reuna todos os comentários e apontamentos realizados a respeito dos relatórios de forma sintetizada, para que assim, todos saibam o porque de seus relatórios serem avaliados em determinada métrica/grupo. Esse texto será feito após finalizadas as reuniões de avaliações.

**Comment by alessandrapedrotti** [comment]
Podemos determinar um dia, @Claudineia-VR, para realizarmos essa tarefa?

**Comment by Claudineia-VR** [comment]
Sim, @alessandrapedrotti, por mim pode ser hoje!

**Comment by alessandrapedrotti** [comment]
> Sim, @alessandrapedrotti, por mim pode ser hoje!

Certo, as 14h então.

**Comment by alessandrapedrotti** [comment]
Os feedbacks estão sendo revisados, até o fim da semana, serão enviados aos membros do PRACTICE por email.

**Comment by alessandrapedrotti** [comment]
Os feedbacks em PDF estão na [pasta](https://drive.google.com/drive/folders/1PoSsC_FPTlWzncwfHDGhOM3j5OXzbsbU) da tarefa.
Podemos enviá-los pelo email principal do practice? @Dovyski

**Comment by Dovyski** [comment]
Sim, podem enviar usando o e-mail principal do practice.

**Comment by alessandrapedrotti** [comment]
@Claudineia-VR pode fazer o envio, por favor.

**Comment by Claudineia-VR** [comment]
Todos os feedbacks dos relatórios foram devidamente enviados!
