### ISSUE TITLE
Logística para entrega de presente

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#415]
![IMG_20210128_165458663](https://user-images.githubusercontent.com/512405/106195908-94d2e980-618f-11eb-8cf1-ed551284ca1d.jpg)

Preparamos um presente 🎁 para os membros do programa. É uma singela lembrança para agradecer e inspirar cada um de vocês. Em um mundo ideal, com recurso infinito, enviaríamos o presente para a porta da casa de cada um, mas não dispomos disso (no momento).

Por consequência, precisamos planejar uma logística de entrega. Para os campi que não Chapecó, os presentes serão enviados em um único pacote via malote da UFFS. Vocês, então, precisam organizar a retirada no campus/local e a distribuição entre vocês.

Para Chapecó, eu posso fazer a entrega em mãos (na tarde de sexta-feira, 29/01). Para isso, por favor, informem quais membros podem receber o presente por outros (por exemplo, entrego para A que mora perto de B e pode retirar depois). Isso otimiza minha viagem.

@practice-uffs/todos 

OBS: para registro e fins de auditoria, os presentes, pacotes e adornos foram comprados com verba particular dos coordenadores do projeto. Qualquer item da UFFS no kit é de cunho promocional e já existente para esse fim.

**Comment by amandasegattob** [comment]
Oie! Eu sou do campus Chapecó, mas pra mim fica melhor receber em Passo Fundo, o @luizdameda pode pegar para mim, já que eu não estou em Chapecó e ainda não sei quando volto.

**Comment by robisonjose** [comment]
Daqui de Realeza tem eu, a @MilenaPaz2020 e a @GessicaZanon. Sei que eu e a Milena moramos perto, então eu posso ir pegar, entregar para a Milena, e ai depois a Géssica pega comigo. O que acham?

**Comment by MilenaPaz2020** [comment]
> Daqui de Realeza tem eu, a @MilenaPaz2020 e a @GessicaZanon. Sei que eu e a Milena moramos perto, então eu posso ir pegar, entregar para a Milena, e ai depois a Géssica pega comigo. O que acham?

Perfeito!

**Comment by CleissonVieira** [comment]
Hello peoples
@Dovyski eu posso receber o do @MaNegrao e da @Claudineia-VR, depois entrego a eles.
Se acaso alguém precisar que eu segure também fico a disposição e se precisar de ajuda com a entrega também me disponibilizo Fernando, só não consigo na parte da manhã!

**Comment by GessicaZanon** [comment]
> Daqui de Realeza tem eu, a @MilenaPaz2020 e a @GessicaZanon. Sei que eu e a Milena moramos perto, então eu posso ir pegar, entregar para a Milena, e ai depois a Géssica pega comigo. O que acham?

Perfeito pra mim também!

**Comment by alessandrapedrotti** [comment]
Eu moro mais ou menos próxima da @estelavilasboas, acredito que será possível entregar o dela quando estiver a caminho da minha casa, ou até deixar a lembrancinha dela comigo e eu entrego depois.

**Comment by Dovyski** [comment]
@alessandrapedrotti eu vou deixar as duas contigo então 😉

**Comment by thaliafriedrich** [comment]
Eu posso ir buscar aqui no campus Cerro Largo para mim, para a @morgana-mo e o @ricardopatrik, e depois entregar a eles.

**Comment by TaynaraCh** [comment]
Não vou conseguir pegar o meu,se alguém conseguir pegar na UFFS Erechim e guardar pra mim seria top, por favor 🥺 kkkk quando eu voltar eu pego!

**Comment by luizatonial** [comment]
> Não vou conseguir pegar o meu,se alguém conseguir pegar na UFFS Erechim e guardar pra mim seria top, por favor 🥺 kkkk quando eu voltar eu pego!

Eu pretendo ir para Erechim na semana do dia 09/02, posso passar pegar todos se a @brendaellen não estiver por lá também.

**Comment by andrewmsilva** [comment]
Eu moro em Chapecó, mas num bairro meio longínquo. A @mariagelain está com minha caneca do FronteiraCast, talvez pudesse deixar com ela que aí eu me obrigo pra ir na casa dela e pegar tudo de uma vez hahaha

**Comment by andrewmsilva** [comment]
Entregar o meu pra @alessandrapedrotti, que irá entregá-lo pra @estelavilasboas, que por sua vez irá entregar ele pra mim eventualmente.

**Comment by estelavilasboas** [comment]
> Eu moro mais ou menos próxima da @estelavilasboas, acredito que será possível entregar o dela quando estiver a caminho da minha casa, ou até deixar a lembrancinha dela comigo e eu entrego depois. 

A @alessandrapedrotti poderia pegar a do @andrewmsilva também. 
Assim ela me entrega os dois e eu repasso a do Andrew pra ele.

**Comment by vini2reis** [comment]
> Hello peoples
> @Dovyski eu posso receber o do @MaNegrao e da @Claudineia-VR, depois entrego a eles.
> Se acaso alguém precisar que eu segure também fico a disposição e se precisar de ajuda com a entrega também me disponibilizo Fernando, só não consigo na parte da manhã!

Entregar o meu também para o @CleissonVieira

**Comment by brendaellen** [comment]
> > Não vou conseguir pegar o meu,se alguém conseguir pegar na UFFS Erechim e guardar pra mim seria top, por favor 🥺 kkkk quando eu voltar eu pego!
> 
> @TaynaraCh eu pretendo ir para Erechim na semana do dia 09/02, posso passar pegar todos se a @brendaellen não estiver por lá também.



> > Não vou conseguir pegar o meu,se alguém conseguir pegar na UFFS Erechim e guardar pra mim seria top, por favor 🥺 kkkk quando eu voltar eu pego!
> 
> @TaynaraCh eu pretendo ir para Erechim na semana do dia 09/02, posso passar pegar todos se a @brendaellen não estiver por lá também.

Eu também não estou em Erechim, então seria ótimo @luizatonial . Obrigada ✨

**Comment by Dovyski** [comment]
@isabelirk e @oraphaBorges eu estou com o de vocês, me procurem no Telegram para e entrega semana que vem (ou quando quiserem) 😉

**Comment by Dovyski** [comment]
Para rastreamento dos pacotes, pode-se contatar o setor de expedição e protocolo de cada campi (ou o de Chapecó para consultar a  movimentação).
