### ISSUE TITLE
Definir formatos de produtos para a equipe de vídeo

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#42]

**Comment by MaNegrao** [comment]
A planilha com o detalhamento dos formatos está no google drive. 

https://docs.google.com/spreadsheets/d/17X4ylhJweHGJ6F4WzPu2Q3Ixv9gsvkFL0iQ-nSQu_S4/edit#gid=0

**Comment by lcaimi** [comment]
Excelente. Acho que poderiamos definir com mais detalhes os recursos disponíveis em cada formato. Sugestão de possíveis formatos a serem incorporados são exemplificados abaixo. A lista é uma sugestão (elementos podem ser retirados ou acrescentados) e durante o preenchimento do formulário de solicitação poderia ser selecionado pelo cliente.
- Vídeo
- Hand Draw video
- Mapa conceitual
- Slides
- Animação
- Imagens ou fotos
- narrador
- Composição de imagem, fotos, etc
- Texto sobre video
- Link video externo
- link para páginas

@vini2reis

**Comment by vini2reis** [comment]
A planilha foi atualizada com as sugestões que o @lcaimi passou.

**Comment by MaNegrao** [comment]
O formulario de entrada de pedido está na pasta da issue
Segue link https://docs.google.com/forms/d/e/1FAIpQLSc5zIDzmYYkGwhVvNl7n2qSp4EynNr15P9HPrZISnKquvJrPg/viewform?usp=sf_link

**Comment by vini2reis** [comment]
Link para o doc com a explicação dos produtos: https://docs.google.com/document/d/1brS3rAwuheaVX3_I9F-aHvbShriDRXIeMBDkLe5pOYc/edit#

**Comment by Dovyski** [comment]
Coloquei `gráfico:ok` porque esse material, pelo que eu entendi, não será disponibilizado nesse formato, ele será colocado no site. Se alguém

**Comment by lcaimi** [comment]
Exatamente @Dovyski. Este material de vídeo e o material de audio devem ser colocados no site, na seção referente aos serviços de audio e vídeo.

https://github.com/practice-uffs/website-programa/issues/32 

Vídeo: 
https://docs.google.com/forms/d/e/1FAIpQLSc5zIDzmYYkGwhVvNl7n2qSp4EynNr15P9HPrZISnKquvJrPg/viewform?usp=sf_link

Audio: 
https://docs.google.com/document/d/1uuU5YbcKqEp1kDLo3LjIEQVl5QHnhQTcup0sMVOFyNU/edit#heading=h.9pej0gg8rbcj

**Comment by Dovyski** [comment]
Acho que podemosa fechar essa tarefa. Para o momento atual, o doc já serve de base para tudo que precisamos. Se, no futuro, decidirmos fazer algo mais elaborado, abrimos uma issue nova. Se o comando da con-media concordar, pode fechar essa tarefa.

**Comment by MaNegrao** [comment]
Aguardando apenas a confirmação para poder fechar a tarefa

**Comment by MaNegrao** [comment]
@CleissonVieira Precisa atualizar a explicação dos formatos no site, com a revisão textual concluída

**Comment by CleissonVieira** [comment]
Conteúdo do site atualizado.
