### ISSUE TITLE
Definir formatos de produtos para a equipe de áudio

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#44]

**Comment by vini2reis** [comment]
A planilha com o detalhamento dos formatos:

https://docs.google.com/spreadsheets/d/1bCyyZGW29FSpOVHHfUav9ZimxfjAxLxJjt49S5U6ndA/edit#gid=0

**Comment by MaNegrao** [comment]
Os formatos de audio estão prontos no drive na pasta da issue

**Comment by MaNegrao** [comment]
O doc com explicação dos formatos para o site está na pasta da issue no drive.

**Comment by MaNegrao** [comment]
Os estão definidos, aguardando apenas a aprovação da gerencia para fechar a issue

**Comment by MaNegrao** [comment]
@CleissonVieira Precisa atualizar a explicação dos formatos nessa também, com a revisão textual concluída

**Comment by CleissonVieira** [comment]
Conteúdo do site atualizado.
