### ISSUE TITLE
Cartilha para gravação de vídeo (ângulo, luz, câmera, iluminação).

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#45]
A cartilha deve conter todas as dicas e instruções apresentadas [nesse vídeo](https://www.youtube.com/watch?v=XzWJoFUGEXo) (que também está disponível de forma escrita [nesse link](https://www.theverge.com/2020/4/8/21202907/zoom-tips-video-call-lighting-audio-look-your-best)).

Nos créditos da cartilha, mecionar "The Verge" como author e incluir referência para o vídeo e texto em questão.

**Comment by phdmauricio** [comment]
Essa cartilha para gravação técnica em casa ficaria muito adequada de ser lançada casada com a cartilha das reuniões onlines @VIF-Franca

**Comment by VIF-Franca** [comment]
> Essa cartilha para gravação técnica em casa ficaria muito adequada para ser lançada casada com uma cartilha das reuniões on-line @ VIF-Franca

Prof acha bacana adicionar uma seção na cartilha de videoconferência ou lançar as duas cartilhas juntas ?

**Comment by phdmauricio** [comment]
Acho que dá pra ser na mesma cartilha. uma nova seção nela.

**Comment by Dovyski** [comment]
Também acho interessante as dicas estarem na cartilha de videoconferencia em uma seção dela. De qualquer forma, eu acho que a cartilha de dicas deve ser um material independente (sua própria cartilha).

Se quisermos passar apenas as dicas para algum, precisamos de um material de "fácil digestão", nao a cartilha de videoconferencia inteira.

**Comment by phdmauricio** [comment]
Acho que tínhamos pensar numa cartilha, já que é eletrônica, com highlights. Do tipo, a pessoa lê o que mais precisa, poderíamos pensar em superar esta ideia de revista (texto corrido, de formato analógico/papel)

**Comment by VIF-Franca** [comment]
Prof @phdmauricio adicionei alguns tópicos sobre o ângulo, luz e câmera na cartilha que está no Drive refente a issues #28. 

Por favor veja se ficou faltando algum item.

**Comment by VIF-Franca** [comment]
@practice-uffs/con está disponível para revisão textual, essa ficou bem curtinha caso tenha alguma sugestão de tópico pode sinalizar.

**Comment by alessandrapedrotti** [comment]
Revisão textual concluída.
@mariagelain por favor realizar a revisão gráfica.

No geral o material ficou muito bom, foram necessários apenas alguns ajustes pontuais no texto.

**Comment by Dovyski** [comment]
Para uma versão inicial dessa cartilha, acho que está ok. Ao meu ver, porém, existe muito texto e pouca figura. A @elisribas pode decidir se quer que a cartilha atual seja dada como finalizada assim (e depois fazemos uma mais visual, no formato infográfico), ou se precisamos adequar.

**Comment by elisribas** [comment]
@VIF-Franca dá uma olhada nos comentários que fiz ao longo da cartilha.
Se tiver mais dicas, melhor! A cartilha está muito breve.

@estelavilasboas a cartilha precisa ficar mais atrativa, com mais imagens entre o texto. 

Avisem quando concluirem para revisão final e encerramento da issue.

**Comment by VIF-Franca** [comment]
- [ ] > @VIF-Franca dá uma olhada nos comentários que fiz ao longo da cartilha. Se tiver mais dicas, melhor! A cartilha está muito breve.
- [ ] > @estelavilasboas a cartilha precisa ficar mais atrativa, com mais imagens entre o texto.

> 
> Avisem quando concluirem para revisão final e encerramento da issue.

**Comment by estelavilasboas** [comment]
Adicionei algumas imagens entre o texto. Devo lembrar que os templates de cartilhas estão sendo revisados, assim como o design de todas as cartilhas. Esta cartilha ainda deve sofrer alterações.

**Comment by VIF-Franca** [comment]
Ok Estela, 

Quando finalizar pode fechar a issue.

**Comment by lcaimi** [comment]
Como o @Dovyski comentou acho que tem muito texto e pouca imagem para exemplificar as dicas.
Algo como a imagem abaixo. Mas infelizmente a imagem não é de uso livre e não encontrei nenhuma em repositórios livres

![image](https://user-images.githubusercontent.com/12415747/90778939-9f7d7e80-e2d3-11ea-81e7-1dc0b283faf1.png)
