### ISSUE TITLE
Live SILE 6 - Simpósio: Estudos Dialógicos da Linguagem 2 - 11/03 - 14h

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#458]
<h1 align="center" >Informações Transmissão Ao Vivo</h1>

**Titulo**: Simpósio: Estudos Dialógicos da Linguagem: contribuições para pesquisas em Linguística Aplicada nos contextos escolares e não-escolares.

**Data e Hora**: 11/03/21 - 14h às 17h

**Evento Geral** (se houver): SILE (Seminário Internacional de Letras da Fronteira Sul)

**Solicitante**: Márcia Adriana Dias Kraemer - marcia.kraemer@uffs.edu.br

**Realizador(es)**: Comissão Organizadora do SILE

**Palestrante Principal**: Prof. Dr. Rodrigo Acosta Pereira Universidade Federal de Santa Catarina (UFSC-BR)

**Link Transmissão**: https://youtu.be/TfQ0S0o3Tro

Com os dados e roteiro em mãos, o responsável pela Live deve seguir os padrões do PRACTICE e estabelecer contato com o solicitante, enviando inicialmente o Protocolo de Execução de Lives.

**[Planilha de Lives](https://drive.google.com/drive/folders/16h-YVwTnRF49eqBYBRONKyLqPbisCIbH)**

**[Protocolo de Execução de Lives](https://drive.google.com/file/d/1KQ9vI1gKECqWHi4xwb3LrnuWCgKEHWyd/view?usp=sharing)**

**[Padronização de Lives](https://drive.google.com/file/d/1Bky3nLRTAoCejzHrH0D93GQ_gjsa4Hxl/view?usp=sharing)**

CC: @con-midia / lives

**Comment by MilenaPaz2020** [comment]
Live Finalizada com sucesso! Planilha Atualizada.
