### ISSUE TITLE
Definir formatos de produtos para a equipe de conteúdo (texto e imagem).

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#46]

**Comment by mariagelain** [comment]
Boa tarde, fizemos um esboço do que seria necessário para o projeto do con-material. Por favor vejam se estamos no caminho certo @Dovyski @elisribas 
link: https://docs.google.com/document/d/1YO0iso-ncYoA9gOZW6JBGp2MBEZv_SEgXB5_mRsp-Mo/edit

**Comment by Dovyski** [comment]
Eu gostei, estão no caminho certo, sim. Eu acho que vocês podem detalhar um pouco mais os produtos esperados. Por exemplo, cartilha é bem genérico (qual o limite de characteres/palavras?).

Eu sugiro que vocês façam categorias de produtos, por exemplo:

* Cartilha simples (de 1 a 2 páginas, com 3 imagems, máximo de 1000 chars)
* Cartilha média (de 2 a 4 páginas, com 6 imagems, máximo de 2000 chars)
....

O número de páginas e imagens eu inventei, mas vocês como equipe podem definir isso. Imaginem quantas cartilhas de cada tipo vocês conseguem fazer por sprint. Isso ajuda a quantificar o trabalho que cada uma demanda.

E, além disso, coloquem um documento de exemplo para cada um dos produtos. Pode ser algo com texto "lorem ipsum" e imagens cinza, mas que dê uma ideia do que será o resultado final.

Além disso, é muito importante detalhar o fluxo de trabalho, algo como: 1) cliente entrega materiais; 2) equipe faz esboço e mostra ao cliente, com 24h para resposta; 3) equipe faz material final; 4) cliente sugestiona 4 alterações pequenas ou 1 alteração grande; 5) equipe finaliza documento; 6) cliente recebe produto.

**Comment by isabelirk** [comment]
Boa noite, 
foi realizado um esboço do fluxo de trabalho da equipe con-material, segue link para o documento:
https://docs.google.com/document/d/1vOFtdrKbapYEf5fxnBYS7Y8D6hd9aEwsBZlLkF48ueQ/edit
Atenciosamente.

**Comment by mariagelain** [comment]
Segue link com o os templates já produzidos, aguardo a revisão da @elisribas  
link: https://drive.google.com/drive/folders/1OQQlDWQL1u1ix5DLQr20pQ7OjSbGDMGU

**Comment by elisribas** [comment]
@estelavilasboas Comecei a revisão dos templates, mas quero que você faça a revisão final, pensando no que ficará mais atrativo em termos de desing, tendo em vista sua experiência com criação de imagens, logos, etc... 

Torne-so o mais atrativo possível, considerando a necessidade de que cada material precisa conter *texto* e *imagem*, ou seja, precisa conter a produção que a Maria já estudou e já produziu.

**Comment by elisribas** [comment]
Templates revisados (pedagogicamente):

- cartilhas simples;

- cartilhas moderada e completa

**Comment by elisribas** [comment]
Nas orientações, coloquem também:

- Dicas de cores (indicar para usar as cores do template);
- Criar algumas setas e caixas de círculos para colocar no manual, assim as pessoas poderão apenas copiar e colá-las.

**Comment by elisribas** [comment]
@mariagelain olha esse guia sobre banner científico.

https://www.ufrb.edu.br/gestaopublica/images/phocadownload/materialdidatico/como_elaborar_pster.pdf

**Comment by estelavilasboas** [comment]
> Templates revisados (pedagogicamente):
> 
> * cartilhas simples;
> * cartilhas moderada e completa
> * planfeto;
> * manual.
> 
> @estelavilasboas ver design do Panfleto Practice, bem os demais arquivos.

_[Cartilhas simples](https://drive.google.com/file/d/1uAu1ch-mtO3VpJlX_d4J9J9VunpT3waD/view), [manual](https://drive.google.com/file/d/1dLgunzCsjplxoEOKBCM907gCnGtRQE34/view) e [cartilhas moderada e completa](https://drive.google.com/file/d/1kAZmLHb5EmzaNxz70-jwcg46WCFdyNxr/view):_ 
Foram alterados o título "Orientações" e o rodapé com as redes sociais

_[Panfleto](https://drive.google.com/file/d/1LyPo51N1IICugT8bLqoUnA4C_o0pjOEU/view):_ (versões alteradas estão no final do arquivo pptx)
Foram criadas versões png do panfleto. As mesmas versões existem no pptx.
O nome completo do programa foi movido para baixo da logo.
Foram feitas duas versões. A [primeira](https://drive.google.com/file/d/1j9iGV6rfam1fmtmNhcdC2pBdrL9rEsiP/view) contém todas as redes em uma lista. A [segunda](https://drive.google.com/file/d/1YMuv-9-gxb_gWvi9TpT3De1QePLJknyV/view) possui apenas as principais redes. Como uma rede "leva" para a outra, dessa forma diminuímos a quantidade de elementos no panfleto.
