### ISSUE TITLE
Vídeo tutorial sobre forma de gravação (iluminação, ângulo)

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#47]
Criar um video simples, talvez de 30 segundos para ser usado como "drops" em redes sociais, sobre como é a melhor forma de se aparecer em uma reunião usando câmera. Todas as dicas e instruções sobre isso estão [nesse vídeo do The Verge](https://www.youtube.com/watch?v=XzWJoFUGEXo). Precisamos apenas condensar as dicas dele em 30 segundos.

Não esquecer de colocar nos créditos finais do nosso vídeo uma referência para o vídeo do The Verge.

[Pasta Drive](https://drive.google.com/drive/folders/1vt61NKMiB8HYjkauLHdOcVN5BjmpWcqz)

**Comment by MaNegrao** [comment]
O roteiro começou a ser produzido na pasta do drive, creio que ele servirá mais para saber o que falar e será rápido para fazer, visto que o objetivo do vídeo é ser curto.

**Comment by MaNegrao** [comment]
@MilenaPaz2020 Segue a issue que comentamos

**Comment by MilenaPaz2020** [comment]
Roteiro finalizado, está [nessa pasta](https://drive.google.com/drive/folders/1gMcyQ7y_VO5Z6dcuNjE8sG95fXiRvEh1). Precisa de revisão textual!
Aberto para dicas também!

**Comment by MaNegrao** [comment]
> Roteiro finalizado, está [nessa pasta](https://drive.google.com/drive/folders/1gMcyQ7y_VO5Z6dcuNjE8sG95fXiRvEh1). Precisa de revisão textual!
> Aberto para dicas também!

@practice-uffs/con-conteudo pode nos ajudar :D

**Comment by alessandrapedrotti** [comment]
> Roteiro finalizado, está [nessa pasta](https://drive.google.com/drive/folders/1gMcyQ7y_VO5Z6dcuNjE8sG95fXiRvEh1). Precisa de revisão textual!
> Aberto para dicas também!

@thaliafriedrich favor se encarregar da revisão textual.

**Comment by thaliafriedrich** [comment]
Fiz a revisão. Na minha opinião, o roteiro está muito bom. Fiz apenas a troca de poucas palavras e deixei algumas sugestões para melhorias.

**Comment by MaNegrao** [comment]
@MilenaPaz2020 vi que você deu continuidade em outra issue, podemos fechar essa?

**Comment by MilenaPaz2020** [comment]
Sim, pode ser fechada.
