### ISSUE TITLE
Definir o formato de entrada para o pedido de conteúdo.

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#48]

**Comment by elisribas** [comment]
O formato de entrada possui um fluxo.
Está disponível no Drive https://docs.google.com/document/d/1vOFtdrKbapYEf5fxnBYS7Y8D6hd9aEwsBZlLkF48ueQ/edit

@lucasgalize transformar em diagrama via ferramenta Diagrams.net disponível no Google Drive.

Para mais infos sobre utilização da ferramenta, ver tutorial: https://www.youtube.com/watch?v=XOOVHVfc16U

**Comment by elisribas** [comment]
@lucasgalize precisamos desse fluxograma até amanhã.
@estelavilasboas veja se pode ajudar o Lucas, o ideal é transcender de fluxograma para infográfico.

**Comment by lucasgalize** [comment]
O diagrama está na pasta do drive. Aguardando revisão do grupo con material.

**Comment by elisribas** [comment]
@estelavilasboas trabalhar no design
