### ISSUE TITLE
Desenvolvimento de template e material para a Newsletter

### ISSUE THREAD

**Issue by anacarolinamorigi** [practice-uffs/programa#483]
Conforme a issue #403 seguimos com o desenvolvimento do material para a publicação da newsletter interna e externa. 

Na reunião de hoje conversamos sobre o criação da arte do template e o desenvolvimento do material das colunas que serão colocadas.  Assim, pensamos nessa divisão para o material:

- Desenvolvimento de colunas fixas e editáveis, sendo elas de no máximo 10 itens, as colunas fixas foi pensado em 6 a 8 e o restante as editáveis com colunas flutuantes e mais interessantes que surgirem.
- Na newsletter interna foi pensado em deixar uma coluna para algo mais descontraído como o funcionário do mês.

Dessa forma, precisamos debater como serão e sobre o que serão essas colunas fixas. Podemos elencar as ideias abaixo e organizar melhor as ideias a partir disso.

**Comment by TaynaraCh** [comment]
Não sei se houve algum problema mas não fui notificada sobre essa reunião em nenhum lugar, seria interessante terem me chamado para prensarmos juntas. Outra coisa, me parece que já decidiram o layout, vocês querem que eu faça a diagramação segundo as ideias propostas por vocês e opine sobre o conteúdo dela? Enfim, estou meio perdida. Se possível, por favor, quero participar das reuniões de criação, que é a melhor parte kkkkk e não apenas "colocar os textos" kkkkk

**Comment by morgana-mo** [comment]
> Não sei se houve algum problema mas não fui notificada sobre essa reunião em nenhum lugar, seria interessante terem me chamado para prensarmos juntas. Outra coisa, me parece que já decidiram o layout, vocês querem que eu faça a diagramação segundo as ideias propostas por vocês e opine sobre o conteúdo dela? Enfim, estou meio perdida. Se possível, por favor, quero participar das reuniões de criação, que é a melhor parte kkkkk e não apenas "colocar os textos" kkkkk 

@TaynaraCh fica tranquila que foi uma reunião da equipe de auxílio gerencial que meio que deu os caminhos pra gente começar. Na outra issue tem uma pasta com ideias, mas de momento temos que definir as pautas pra podermos agilizar um pouco o processo

**Comment by TaynaraCh** [comment]
Entendi!! Obrigada! Perdão se fui grosseira estava muuuito cansada quando respondi kkk

**Comment by GessicaZanon** [comment]
@practice-uffs/todos peço que preencham essa [tabela](https://docs.google.com/spreadsheets/d/1ak-9bmB5J5jHmZJ5Mtd9YfRSpp08xqLbsSF3-dVNGSU/edit#gid=0) com as devidas informações.. A ideia é ter um panorama dos projetos que nós desenvolvemos por fora do PRACTICE dentro da universidade, como projetos de ensino/pesquisa/extensão e até mesmo TCC para quem estiver desenvolvendo.. Iremos utilizar dessas informações na nossa newsletter, sendo um jeito até de nos conhecermos mais..

**Comment by Dovyski** [comment]
@GessicaZanon os professores podem preencher essa planilha também, né?

**Comment by GessicaZanon** [comment]
> @GessicaZanon os professores podem preencher essa planilha também, né?

Com toda certeza!!

**Comment by TaynaraCh** [comment]
Gente, eu criei dois estilos diferentes de [diagramação,](https://docs.google.com/presentation/d/1sHLot0dEXr2SJQC982XHmi-coknXSVTDzD2npZ9qL9I/edit#slide=id.gca3b902561_0_18) opinem se gostaram ou não, o que daria pra mudar, ideias e tudo mais que quiserem kkkk com o conteúdo da newsletter pronto vai ser mais fácil pensar a diagramação, e aí a gente organiza tudo certinho seguindo algum estilo já estabelecido.

**Comment by morgana-mo** [comment]
@TaynaraCh eu gostei mais da segunda opção, acredito que um teste com o texto irá colaborar nessa escolha :D

**Comment by Claudineia-VR** [comment]
@TaynaraCh eu particularmente gostei mais da primeira, as cores combinaram mais entre si, mas ambas estão ótimas!!

**Comment by anacarolinamorigi** [comment]
@TaynaraCh amei as duas artes, parabéns! Mas ainda prefiro a primeira em questão de harmonia entre as cores! 🥰🥰

**Comment by alessandrapedrotti** [comment]
> Gente, eu criei dois estilos diferentes de [diagramação,](https://docs.google.com/presentation/d/1sHLot0dEXr2SJQC982XHmi-coknXSVTDzD2npZ9qL9I/edit#slide=id.gca3b902561_0_18) opinem se gostaram ou não, o que daria pra mudar, ideias e tudo mais que quiserem kkkk com o conteúdo da newsletter pronto vai ser mais fácil pensar a diagramação, e aí a gente organiza tudo certinho seguindo algum estilo já estabelecido.

Eu vou ser do contra e dizer que gostei mais da segunda opção hahaha. Mas realmente, se o azul das tarjas fosse o tom mais escuro, acho que ficaria mais harmônico.

**Comment by GessicaZanon** [comment]
> Gente, eu criei dois estilos diferentes de [diagramação,](https://docs.google.com/presentation/d/1sHLot0dEXr2SJQC982XHmi-coknXSVTDzD2npZ9qL9I/edit#slide=id.gca3b902561_0_18) opinem se gostaram ou não, o que daria pra mudar, ideias e tudo mais que quiserem kkkk com o conteúdo da newsletter pronto vai ser mais fácil pensar a diagramação, e aí a gente organiza tudo certinho seguindo algum estilo já estabelecido.

Primeiramente, parabéns! A minha impressão é que a primeira ficou mais "divertida" e a segunda mais formal.. As duas ficaram muito legais! Mas particularmente, gostei mais da segunda opção.. E concordo com a @alessandrapedrotti sobre as cores das tarjas, talvez o azul escuro fique melhor. 

Ainda não conversamos se pretendemos fazer o mesmo estilo para a edição interna e externa. Mas poderíamos por exemplo, utilizar um template para edição interna e outro para a edição externa, ou usar uma das opções como edição especial (a primeira por exemplo, como é mais divertida).

**Comment by isabelirk** [comment]
Que trabalho lindo @TaynaraCh, gostei bastante das duas opções. Eu concordo com o comentário da @GessicaZanon.

**Comment by luizatonial** [comment]
> > Gente, eu criei dois estilos diferentes de [diagramação,](https://docs.google.com/presentation/d/1sHLot0dEXr2SJQC982XHmi-coknXSVTDzD2npZ9qL9I/edit#slide=id.gca3b902561_0_18) opinem se gostaram ou não, o que daria pra mudar, ideias e tudo mais que quiserem kkkk com o conteúdo da newsletter pronto vai ser mais fácil pensar a diagramação, e aí a gente organiza tudo certinho seguindo algum estilo já estabelecido.
> 
> Primeiramente, parabéns! A minha impressão é que a primeira ficou mais "divertida" e a segunda mais formal.. As duas ficaram muito legais! Mas particularmente, gostei mais da segunda opção.. E concordo com a @alessandrapedrotti sobre as cores das tarjas, talvez o azul escuro fique melhor.
> 
> Ainda não conversamos se pretendemos fazer o mesmo estilo para a edição interna e externa. Mas poderíamos por exemplo, utilizar um template para edição interna e outro para a edição externa, ou usar uma das opções como edição especial (a primeira por exemplo, como é mais divertida).

As duas opções ficaram muito legais mesmo, poderíamos pensar nessa ideia de utilizar uma internamente e outra externamente. Acredito que o conteúdo a ser inserido e a diagramação vai ajudar na nossa escolha.

**Comment by MaNegrao** [comment]
Eu achei as duas maravilhosas e concordo com a ideia da @luizatonial, podemos aproveitar toda a critatividade da equipe :D

**Comment by TaynaraCh** [comment]
Finalmente, concluí. 
Por sugestão da Géssica, removi um trecho do conteúdo, que ficará para próxima edição, ficando apenas informações sobre o programa especificamente, acredito que possa ser lançado como comemoração ao aniversário do programa. Eu diagramei no [figma](https://www.figma.com/file/W34y1rxhAAi2pQtDoXDrsO/NEWSLETTER?node-id=0%3A1), mas o pdf encontra-se na pasta de [saída](https://drive.google.com/drive/folders/1vJwXxikGxr__movtmLV_QK6STZawX6WQ) da issue, se acharem necessárias alterações podem comentar aqui!
