### ISSUE TITLE
[Identidade visual] Definir paleta de cores e fontes

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/programa#5]
As cores e as fontes influenciam em como as pessoas enxergam o projeto e quais sentimentos elas hão de sentir ao visualizarem os conteúdos que forem publicados. Portanto, definir uma paleta de cores e um padrão de fontes é essencial para criar uma identidade visual concisa. A paleta de cores deve incluir preto e branco, enquanto o padrão de fontes pode especificar diferentes fontes para títulos e textos longos. 

Além disso, esta issue está relacionada à issue #1. Mais informações podem ser adicionadas em breve.

**Comment by VIF-Franca** [comment]
- [ ] Podemos sinalizar para toda a equipe a sugestão do @Dovyski para a fonte textual `Roboto`;
- [ ] Sobre as cores branca e preta para o texto;
- [ ] As demais cores seguindo a paleta de cores da nossa logo marca, segue a imagem.

![WhatsApp Image 2020-07-08 at 14 48 54](https://user-images.githubusercontent.com/66980370/86953029-3af2cf80-c12a-11ea-90ca-5032027b38c6.jpeg)

**Comment by Dovyski** [comment]
Estou alinhado com o que o @VIF-Franca comentou: usamos `Roboto` como fonte padrão, bastando escolher suas variações para cada caso (ex.: padrão para texto, light/fina para subtítulo, bold/negrito para título).

A paleta de cores que a @estelavilasboas definiu em #1 são excelentes, ao meu ver. Vamos precisar disso para o app também.

@practice-uffs/con-material precisa criar o documento de identidade visual no Google Drive compilando essas informações.

**Comment by estelavilasboas** [comment]
Não sei se é de alguma ajuda, mas quando fomos alterar algumas coisas no site, vimos a necessidade de um banner ([Issue#5 do website](https://github.com/practice-uffs/website-programa/issues/5)). Então, eu criei um banner temporário ([link do drive](https://drive.google.com/file/d/1dv8k4KHVMynxHlpqsVfprBuwPwerh-Mf/view?usp=sharing)) com a paleta que o @VIF-Franca indicou.
![banner-temp](https://user-images.githubusercontent.com/30927758/86962635-a1331e80-c139-11ea-9439-2eb3236cc77e.png)

**Comment by estelavilasboas** [comment]
Observei que começaram a utilizar o banner das ondinhas em outras partes, então criei uma versão transparente e uma sem escrita, que podem ser uteis dependendo do uso.

[Transparente e sem escrita](https://drive.google.com/file/d/1EltQ_2T-WOYTHW2toRUdVI8Y3MRsyDkp/view):
![image](https://lh3.googleusercontent.com/IgqhmxwCM8UJC4QQPDVDFhDk72NjIq2CrxjpTxhWqcW_SxO8xd4E_nkwCY2JE0vZ7mT1KiHJyOjftCoKEska=w1366-h635-rw)

[Transparente com escrita](https://drive.google.com/file/d/1mPRmuOCiZ__FuZjTD0aaYNOArqO9fJnl/view):
![image](https://lh4.googleusercontent.com/XOniKSm2_2Lhm_A1P-3BcDc2Wr-h8rX7aS1jDVBXOOd_c79RGVQRurFY9uXCnx9uNmq1UnHEHI-UTn9dC3iZ=w1366-h635-rw)

Estou fazendo o Banner e estou utilizando a fonte `Roboto`, como citada anteriormente. Para os ***fundos***, estou alternando  entre branco e o azul escuro (#264653) da paleta. Estou fazendo o mesmo com as ***cores da fonte***, de branco para azul escuro (#264653) e preto, conforme a necessidade.
