### ISSUE TITLE
Definir o formato de entrada para o pedido de vídeo.

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#51]

**Comment by phdmauricio** [comment]
Se precisar de ajuda com o texto e a ideia do formulário, posso ajudar Matheus.

**Comment by lcaimi** [comment]
> Se precisar de ajuda com o texto e a ideia do formulário, posso ajudar Matheus.

O formulário está na issue #41 

Abri um GoogleSheets para descrever produtos e formatos usados
[https://docs.google.com/spreadsheets/d/10Mg1D3SfBayohmoYdNqzmasKMmNYAGGHiNvGe0UD2xA/edit#gid=0](url)

**Comment by MaNegrao** [comment]
A planiilha de formatos está na pasta do drive da issuse #42

**Comment by oigor** [comment]
@lcaimi  Professor, passe o seu feedback, alinhamos e enviamos para revisão.

Planilha de formatos do vídeo no drive #42 
Planilha do formato de áudio no drive #43

**Comment by MaNegrao** [comment]
O formulário de entrada de pedidos de video está na pasta do drive da issue #42 Juntamente com a definição dos formatos.

**Comment by phdmauricio** [comment]
https://docs.google.com/document/d/1zkGyBaALD63t72TjKk8mn8hne5Q-hZ8RBEcIKcwL9bs/edit?usp=sharing

Uma ideia aqui
