### ISSUE TITLE
Live Conta aí! Oficina de contação de histórias. 29/04/2021- 19:00 às 22:40

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#512]
<h1 align="center" >Informações Transmissão Ao Vivo</h1>

**Titulo**: Conta aí! Oficina de contação de histórias.

**Data e Hora**: 29/04/2021- 19:00 às 22:40

**Solicitante**: Andréia Inês Hanel Cerezoli | hanelandreia@gmail.com

**Realizador(es)**: Campus Erechim - Extensão

**Palestrante Principal**: Como são muitos eu coloquei direto na pasta

**Link Transmissão**: https://youtu.be/zd4aGdEhykk

Com os dados e roteiro em mãos, o responsável pela Live deve seguir os padrões do PRACTICE e estabelecer contato com o solicitante, enviando inicialmente o Protocolo de Execução de Lives.

**[Planilha de Lives](https://drive.google.com/drive/folders/16h-YVwTnRF49eqBYBRONKyLqPbisCIbH)**

**[Protocolo de Execução de Lives](https://drive.google.com/file/d/1KQ9vI1gKECqWHi4xwb3LrnuWCgKEHWyd/view?usp=sharing)**

**[Padronização de Lives](https://drive.google.com/file/d/1Bky3nLRTAoCejzHrH0D93GQ_gjsa4Hxl/view?usp=sharing)**

CC: @con-midia / lives

**Comment by luizatonial** [comment]
eu tenho disponibilidade para esta live.

**Comment by morgana-mo** [comment]
A capa para esta live foi criada a alguns meses, vou procurar e coloco na pasta de entrada

**Comment by morgana-mo** [comment]
Já está na pasta !

**Comment by MaNegrao** [comment]
@luizatonial a solicitante pediu para entrar em contato e marcar um teste da Live.

**Comment by luizatonial** [comment]
o teste da live ocorrerá nos minutos que antecedem a transmissão, como fazemos normalmente.
a solicitante havia se confundido em relação às informações do protocolo de lives.

**Comment by MaNegrao** [comment]
Beleza :D

**Comment by luizatonial** [comment]
Roteiro completo e atualizado na pasta!

**Comment by luizatonial** [comment]
Live finalizada com sucesso! Me pediram para tentar legendar o vídeo YouTube por questões de acessibilidade, vou verificar a legenda automática do YouTube nos próximos dias e ver o que é possível fazer.
