### ISSUE TITLE
Estruturação da versão teste da Newsletter

### ISSUE THREAD

**Issue by anacarolinamorigi** [practice-uffs/programa#519]
Atrelado as issues #403 e #405 e conforme reunião do grupo responsável pela Newsletter, que ocorreu na tarde do dia 31/03, foi definido os tipos de colunas e pautas a serem publicadas na versão teste - 1ª versão - da newsletter externa, que será divulgada ao público dia 30/04.

O docs com os pontos citados acima encontram-se na pasta de entrada da issue!

**Comment by GessicaZanon** [comment]
Pessoal, iniciei duas partes: "Feedback dos solicitantes" e "Conheça mais sobre o programa". Quem quiser e puder, fique a vontade para dar o tal do pitaco. Deixem comentários, sugestões.. Amanhã irei ajustar o que for necessário e iniciar os demais tópicos.

**Comment by GessicaZanon** [comment]
Primeira versão do texto finalizada! Liberado para sugestões, críticas e possíveis alterações.

**Comment by anacarolinamorigi** [comment]
> Primeira versão do texto finalizada! Liberado para sugestões, críticas e possíveis alterações.

@GessicaZanon na minha visão essa primeira versão ficou muito boa, acabou casando bem todo o texto e as colocações. Ficou uma linguagem bem acessível e descontraída a todos que forem ler. Vai vender muito bem o peixe do programa. Obrigada e parabéns pelo trabalho! 

Creio que agora temos que projetar como iremos organizar os textos no template, mas de resto tudo okay!

**Comment by GessicaZanon** [comment]
> > Primeira versão do texto finalizada! Liberado para sugestões, críticas e possíveis alterações.
> 
> @GessicaZanon na minha visão essa primeira versão ficou muito boa, acabou casando bem todo o texto e as colocações. Ficou uma linguagem bem acessível e descontraída a todos que forem ler. Vai vender muito bem o peixe do programa. Obrigada e parabéns pelo trabalho!
> 
> Creio que agora temos que projetar como iremos organizar os textos no template, mas de resto tudo okay!

Muito obrigadaa! Fico feliz que tenha gostado.

Isso, o próximo passo é justamente diagramar esse texto no template! Acredito que a @TaynaraCh queira realizar essa parte. E aí já vemos também se será necessário excluir alguma coisa ou algo assim..

**Comment by TaynaraCh** [comment]
Gessica, eu vou escrever no doc algumas coisinhas que eu pensei que poderíamos fazer. Já comece a diagramação rsrsrs to criando um novo templete kkkk

**Comment by GessicaZanon** [comment]
> Gessica, eu vou escrever no doc algumas coisinhas que eu pensei que poderíamos fazer. Já comece a diagramação rsrsrs to criando um novo templete kkkk

Sim, fique a vontade! Toda sugestão ou algo a acrescentar é bem vindo.

**Comment by Claudineia-VR** [comment]
Achei essa primeira versão incrível!!! ficou uma leitura leve, interessante e bem completa em todos os aspectos. Concordo com basicamente todas as sugestões da Taynara, acho que vai ficar melhor ainda. Parabéns a @GessicaZanon e aos envolvidos!!!

**Comment by GessicaZanon** [comment]
Muito obrigada, @Claudineia-VR !

> Achei essa primeira versão incrível!!! ficou uma leitura leve, interessante e bem completa em todos os aspectos. Concordo com basicamente todas as sugestões da Taynara no doc, acho que vai ficar melhor ainda. Parabéns a @GessicaZanon e aos envolvidos!!!

Muito obrigada, @Claudineia-VR ! 

Obrigada @TaynaraCh pelas ótimas sugestões! Fiz algumas alterações e acredito que possa ser diagramado para o layout da newsletter. Qualquer ponto que você ache interessante que seja alterado no formato de escrita durante a diagramação, é só falar!

**Comment by morgana-mo** [comment]
@GessicaZanon a primeira versão está fabulosa!
Parabéns pelo ótimo trabalho desenvolvido!

**Comment by GessicaZanon** [comment]
@TaynaraCh eu reduzi os textos diretamente no Figma. Coloquei diversos comentários a respeito disso.. Vamos conversando para ver o que faremos. Qualquer alteração a mais que precise ser feita, só dar um grito :)

**Comment by TaynaraCh** [comment]
Li os comentários e concordo com o que você apontou! Vou finalizar o arquivo, muito obrigada!!!!!!
