### ISSUE TITLE
Fluxo de tramitação dos produtos de áudio.

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#52]

**Comment by MaNegrao** [comment]
Podemos utilizar o fluxo de tramitação dos produtos de video como base para fazer o fluxo de audio. Creio que seriam necessarios algumas apadtações apenas

**Comment by MaNegrao** [comment]
Peguei aquele fluxograma que o prof caimi fez para os videos e fiz pequenas alterações, está no drive. Se houver algo mais a acrescentar fico no aguardo.

Segue link da pasta: https://drive.google.com/drive/u/0/folders/1aF3-jtBdboCkLue2vIDKxQB_pb1w2ehY
