### ISSUE TITLE
Fluxo de tramitação dos produtos de vídeo.

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#53]

**Comment by lcaimi** [comment]
Versão inicial do fluxo de tramitação realizada.

Fluxo desenhado em: [https://app.diagrams.net/](https://app.diagrams.net/)
[fluxo_de tramitação_video.pdf](https://github.com/practice-uffs/programa/files/4903710/fluxo_de.tramitacao_video.pdf)
![fluxo_de tramitação_video](https://user-images.githubusercontent.com/12415747/87166158-8c719a80-c2a1-11ea-914b-5bc222168ef5.png)

**Comment by lcaimi** [comment]
@practice-uffs/con-material poderia olhar a sugestão de fluxo de tramitação.

Alguma sugestão?

Esta é uma visão macro. Pode ser criado um detalhamento do fluxo interno.

Sugestões de tag para as etapas são bem vindas.
 
![video](https://user-images.githubusercontent.com/12415747/87198083-010ffd80-c2d1-11ea-8b87-67f24e3ec827.png)

**Comment by MaNegrao** [comment]
Para uma visão macro creio que ese fluxo esteja ótimo. 

Devemos criar um fluxo mais detalhado para a equipe, com cada processo detalhado ou somente esse é suficiente?

**Comment by lcaimi** [comment]
A equipe é que deve decidir sobre isto. Particularmente acho interessante definir as ações internas da equipe em cada caso. Podemos aproveitar este detalhamento para pensar templates de cada formato, tags de andamento, etc.

**Comment by MaNegrao** [comment]
Concordo que cada formato deve ter um fluxo própio. Só tenho uma duvida quanto a isso, O fluxo seria para cada produto de video que oferecemos certo? Por ex.: O produto com animação teria uma etapa do fluxo _Produção da animação_. 

Penso que com o fluxo especifico de cada produto vamos poder ter uma estimativa de tempo de produção mais precisa em cada etapa.

**Comment by Dovyski** [comment]
Primeiro parabéns à equipe pela elaboração desse fluxo, ficou excelente! Sobre a dúvida do @MaNegrao , eu até concordo com a ideia de termos um fluxo para cada serviço/produto, mas isso deixará as coisas muito complexas ao meu ver.

Um único fluxo, como o proposto, com um conjunto de tags e tarefas bem definidas em cada estágio é o suficiente para mim. Acho que nesse aspecto não podemos ter muitos fluxos/processos diferentes, mas um único fácil de mapear e saber onde está. Diferentes produtos leravão diferentes tempos em cada etapa, mas o fluxo é o mesmo para todos. Meu ver da coisa.
