### ISSUE TITLE
Elaboração das referências bibliográficas do manual de apoio aos estudantes

### ISSUE THREAD

**Issue by isabelirk** [practice-uffs/programa#532]
Esta issue está relacionada com a issue  principal #314 ; no qual se trata de uma subtarefa referente a elaboração das referências bibliográficas do manual de apoio aos estudantes. A tarefa consiste em reunir todas as referências utilizadas para a elaboração deste manual, e fazer a sua formatação conforme as normas da ABNT.

**Comment by brendaellen** [comment]
Link da pasta com as referências: https://drive.google.com/drive/folders/1bZxIhHjKNm3YMRJ9P-G40MSAZT6rlHJw

**Comment by isabelirk** [comment]
Bom dia @brendaellen 
Já adicionei as minhas referencias formatadas.
Atenciosamente.

**Comment by brendaellen** [comment]
Terminei de adicionar as minhas referências já formatadas, e alinhei com as suas @isabelirk 
@thaliafriedrich você poderia fazer a revisão por gentileza?

**Comment by thaliafriedrich** [comment]
Boa noite! 
Revisei as referências. Deixei sugestões para inserir o títulos das matérias de _sites_, sempre que possível, como foi feito na maioria, só em alguns está faltando. Também colocar o ano de publicação da matéria, quando houver essa informação, como foi feito na última referência. 
Além disso, sugeri abreviar o nome dos autores, apenas sobrenome por extenso. Pelo que sei e pesquisei nas normas da UFFS, é opcional apresentar os nomes por extenso ou só sobrenome e abreviatura do nome, desde que mantenha um padrão para todas as referências do trabalho.

**Comment by brendaellen** [comment]
Boa tarde. 
Todas as alterações foram feitas conforme solicitado na revisão, portanto essa issue já pode ser fechada.
