### ISSUE TITLE
Documento afirmando que o cliente detém todos os direitos autorais dos conteúdo a serem utilizados, que aceita o formato do produto, e todos os "termos de condições, ex.: 24 horas para receber".

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#54]

**Comment by VIF-Franca** [comment]
@Dovyski podemos marcar uma call para tirar algumas duvidas sobre esse item ? creio que 30 minutos é suficiente.

**Comment by Dovyski** [comment]
Vamos tentar resolver discutindo na issue antes. Qual é a dúvida?

**Comment by VIF-Franca** [comment]
Estou criando uma prévia do termo de concordância¹, na qual a comunidade acadêmica deve aceitar os termos ao solicitar qualquer demanda, pensei em ter algumas caixas de seleção no final do formulário, a ideia é abordar os seguintes itens em cada um dos aceites:


( x ) No primeiro item pensei em tratar basicamente sobre o **plágio**;
( x ) O item seguinte trata-se que o PRACTICE em hipótese alguma irá **elaborar/pesquisar** conteúdo;
( x ) Já no terceiro aborda que uma equipe de **triagem** irá verificar a demanda e caso tenha informação ou conteúdo incompleto terá 24hs/48hs para responder;
( x ) Por fim no item quarto, que a pessoa poderá solicitar apenas 03 ajustes (precisamos definir melhor o que seria os **ajustes**)

__
¹Elaborei um arquivo na pasta do drive, programa #54
___
**_PS. Seria possível pedir um olhar do jurídico da UFFS ?_**

**Comment by phdmauricio** [comment]
Não vamos passar para a Procuradoria porque demoraria 60 dias um retorno. Eu posso ajudar nas questões jurídicas.

**Comment by VIF-Franca** [comment]
Olá prof @Dovyski e prof @phdmauricio, o que acharam da minuta que elaborei ?

**Comment by phdmauricio** [comment]
Onde esta a minuta?

**Comment by VIF-Franca** [comment]
> Onde esta a minuta?

No drive, segue link ...

https://docs.google.com/document/d/1OobPgyaOb5ydrJpGc1H50Ghg7cvKPfFXupljEguMRIY/edit

**Comment by phdmauricio** [comment]
ok

**Comment by phdmauricio** [comment]
comentei no doc

**Comment by VIF-Franca** [comment]
Perfeito professor todos aceitos,

@Dovyski pode detalhar melhor sobre os ajustes

**Comment by Dovyski** [comment]
Fiz meus comentários no próprio documento.

**Comment by VIF-Franca** [comment]
@Dovyski inclusões realizada.

@elisribas, o professor sugeriu que tu poderia me dar um help no ultimo item do documento que consta no drive. LINK DRIVE: https://docs.google.com/document/d/1OobPgyaOb5ydrJpGc1H50Ghg7cvKPfFXupljEguMRIY/edit


@practice-uffs/con-material, @practice-uffs/con-digital e @practice-uffs/con-midia preciso do apoio de vocês para definir quais ajustes pontuais os clientes podem pedir, eles serão necessários para a elaboração do termo de concordância. Podem editar na issues ou no drive.

**Comment by VIF-Franca** [comment]
> @Dovyski inclusões realizada.
> 
> @elisribas, o professor sugeriu que tu poderia me dar um help no ultimo item do documento que consta no drive. LINK DRIVE: https://docs.google.com/document/d/1OobPgyaOb5ydrJpGc1H50Ghg7cvKPfFXupljEguMRIY/edit
> 
> @practice-uffs/con-material, @practice-uffs/con-digital e @practice-uffs/con-midia preciso do apoio de vocês para definir quais ajustes pontuais os clientes podem pedir, eles serão necessários para a elaboração do termo de concordância. Podem editar na issues ou no drive.

RT

**Comment by elisribas** [comment]
Fiz revisões em todo o texto e ainda precisarei escrever sobre os tipos de licença.
Material precisará passar pela procuradoria para ter legitimidade.

>> da minha parte, está em aberto

**Comment by VIF-Franca** [comment]
Ok Elis

**Comment by phdmauricio** [comment]
Fiz algumas alterações gramaticais, creio que o conteúdo esteja ok, não sei se há necessidade de enviar para a Procuradoria e também não sei se temos status pra isso.

**Comment by VIF-Franca** [comment]
Perfeito, assim que a @elisribas finalizar creio que a @practice-uffs/ger pode decidir sobre o encaminhamento.

**Comment by Dovyski** [comment]
Documento finalizado. Quaisquer equipes que realizarem trabalhos junto a um cliente precisam fazer [uma cópia do documento](https://docs.google.com/document/d/1iO4zmsM_HfIzXZmg0v_kgvN2nGbClm8UEHM_VojxKsA/edit) para dentro da pasta `entrada` da tarefa em questão, fazer os ajustes necessários no doc (nome, indentificações no doc, etc), e solicitar que o cliente assine e entregue o doc.

Abaixo imagem de referência do doc:

![image](https://user-images.githubusercontent.com/512405/93086083-f2e1b300-f66c-11ea-9764-7b4faa7491d3.png)
