### ISSUE TITLE
Criar um doodle para organizar o horário das reuniões de sprints

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#55]
O doodle é para que todos os membros da equipe possam informar o horário preferencial para a reunião de planejamento, acompanhamento e fechamento da sprint (toda sexta-feira).

**Comment by VIF-Franca** [comment]
Criado e enviado e-mail, aguardando feedback do time.

**Comment by VIF-Franca** [comment]
Criado e enviado por e-mail,  caso não recebeu segue link: https://doodle.com/poll/e467ke5ubunw47xa

Aguardando feedback.

cc: @practice-uffs/todos

**Comment by VIF-Franca** [comment]
Horário para as reuniões de acompanhamento das Sprint sextas-feiras com início às 16:00. 

Próxima reunião sexta-feira dia 10/07 às 16:00.
