### ISSUE TITLE
Vídeo tutorial sobre Shotcut - episódio 1

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#56]
Essa issue está relacionada ao episódio `1` da série.

Criar uma sequência de vídeos tutoriais sobre o software de edição Shotcut. O tutorial é, basicamente, uma recriação em português desse tutorial disponível em inglês:

https://www.youtube.com/watch?v=4bcw9_zXEuA&feature=youtu.be

Acho que podemos replicar o mesmo modelo: 6 vídeos, cada um deles apresentando uma das funcionalidades do shotcut (igual o tutorial de referência). Não precisamos filmar a pessoas que fala, apenas mostrar a tela e um audio de narração. Também não acho que precisamos de toda a "energia" do apresentador original (afinal ele é Youtuber). Podemos ter uma narração mais calma e focada, do tipo "Clica aqui, depois aqui, e isso acontece. (pausa). Seguindo, se fizermos tal...".

**Comment by lucasgalize** [comment]
Ok Professor.

**Comment by lucasgalize** [comment]
Primeira versão na integra. Esperando feedback Professor @Dovyski. Primeira versão. 
https://drive.google.com/file/d/1Q3tRKuUd0R8dWSI6CRP-ydxcHqv6gRGy/view?usp=sharing

**Comment by Dovyski** [comment]
Ficou excelente, Lucas! Para que essa versão seja a final, faz uma passada no vídeo onde tem "silêncios" maiores que 2 segundos e corta eles fora. De resto, basta colocar a vinheta do practice no começo, os créditos no final e colocar na pasta saída para publicação.

**Comment by lucasgalize** [comment]
Ok. Professor @Dovyski.

**Comment by lucasgalize** [comment]
Foram feitas os ajustes na revisão do tutorial episódio 1. Esperando sua supervisão Professor @Dovyski.
Vídeo esta no drive também, e está com nome (tutorial PRACTICE 25-09-2020).
https://drive.google.com/file/d/1cEz73hLLks2eMlJXqn0Vzynopr9vLA1z/view?usp=sharing

**Comment by Dovyski** [comment]
Ficou excelente, obrigado, Lucas!

@practice-uffs/ger-auxilio postar o vídeo no canal do Youtube do practice e fechar essa tarefa.

**Comment by VIF-Franca** [comment]
https://youtu.be/Ya-EX-feIu8

**Comment by VIF-Franca** [comment]
Vídeo postado no Youtube.
Qualquer solicitação de edição na descrição ou mesmo vídeo, podem deixar comentários.
@Dovyski , o que acha de postarmos também no Instagram (IGTV) ? 

Link do vídeo : https://youtu.be/Ya-EX-feIu8
