### ISSUE TITLE
Criar esboço técnico de uma sala de telepresença

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#57]
O documento pode ter uma única página que liste os itens de uma sala de telepresença e a suas interações entre si. Além disso, o documento deve conter uma ilustração de uma sala de aula e onde os elementos estarão posicionados.

Os itens são os seguintes:

* Central (Raspberry PI + câmera embutida + microfone condensador apontado para frente) fixado no teto da sala de aula, no centro, com a câmera apontada para o quadro/docente.
* TV de 50 polegadas (fixada na parede do fundo da sala de aula, no meio dela, conecatada à central por um cabo HDMI de 10m).
* Cabo de rede que liga a central até o ponto de rede mais próximo.

**Comment by phdmauricio** [comment]
Eu estou pedindo pro setor de obras o layout das salas de aula (creio que sejam iguais nos 6 campi) para pensarmos já espacialmente de acordo com as dimensões das salas.

**Comment by Dovyski** [comment]
O esquema está disponível em alta resolução no drive em [programa#57](https://drive.google.com/drive/folders/1rY78YQ3_PBFhXhryQFvyiyhXodT3lwGS). Abaixo uma ilustração:

![Esquema - Sala de aula interativa - PRACTICE](https://user-images.githubusercontent.com/512405/87481460-c32f1400-c605-11ea-9881-050d8166223a.png)
