### ISSUE TITLE
Reorganização da equipe @Con-Mídia

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#572]
Com a saída de alguns membros e redução da equipe, algumas estrátegias estão sendo realizadas para otimizar e aprimorar as relações de trabalho da equipe de mídia.

**Comment by robisonjose** [comment]
Junto dessa reorganização temos que fazer a reformulação dos prazos (dos vídeos e de respostas/aceitação às demandas). Já fizemos a reformulação do tipo de vídeos (está inserida no formulário de vídeos)

**Comment by robisonjose** [comment]
Acredito que a reorganização está quase que completamente feita. O que não foi feito ainda, está muito bem encaminhado. 

Dessa forma, podemos fechar essa issue. O que acham?

**Comment by MilenaPaz2020** [comment]
Concordo com o Robison. Encerrarei a issue, mas caso sintam necessidade podem reabrir e daremos continuidade às discussões.
