### ISSUE TITLE
Projeto do Livro Didático Digital.

### ISSUE THREAD

**Issue by phdmauricio** [practice-uffs/programa#58]
_ Refinar o projeto do livro didático digital (Não sei se um novo Projeto junto a PROEC, ou um projeto dentro do PRACTICE), para atender à demanda de curricularização de extensão.

_ O livro será inteiramente em plataforma digital e contará com mídias de texto, vídeo, aúdio e jogos eletrônicos.

_ Definir parceiros (docentes e discentes) dos cursos de licenciatura da UFFS para a produção de conteúdos.

_ Credenciar escolas e colégios com professores parceiros do Projeto para a modelagem e testes do material na prática de sala de aula.

**Comment by phdmauricio** [comment]
Vou  marcar uma reunião específica pra isso, será um projeto grande dentro do programa, juntamento com o Além da Fronteira.

**Comment by mariagelain** [comment]
Como este projeto está sendo desenvolvido nas issues #513 e #551 podemos fechar esta issue.
