### ISSUE TITLE
Produzir a Arte do Banner do Programa

### ISSUE THREAD

**Issue by phdmauricio** [practice-uffs/programa#59]
Desenvolver a arte do Banner que será confeccionado para o programa.

**Comment by phdmauricio** [comment]
e camiseta, caneca e moletom

**Comment by estelavilasboas** [comment]
Que tipo de informações o Banner deve conter?

**Comment by estelavilasboas** [comment]
Até o momento, no Banner foram adicionados o nome completo do programa, redes sociais, site e parcerias (que foram descritas em outra Issue). 
![image](https://user-images.githubusercontent.com/30927758/87361432-9665f880-c542-11ea-8342-0c98bf5daa93.png)

**Comment by estelavilasboas** [comment]
> Que tipo de informações o Banner deve conter?

@phdmauricio

**Comment by estelavilasboas** [comment]
Finalizei as ideias para camisetas, caneca e moletons. As imagens estão disponíveis na [pasta do drive](https://drive.google.com/drive/u/0/folders/1gHgDiNs4HFmHr-WzVRSy5nFN_PRDQJ2c) da Issue e, como são várias opções, questiono se seria apropriado realizar uma votação. Eu mesma já poderia realizá-la caso concordem
Quanto ao banner, ele não esta na pasta ainda, ele está como na imagem do comentário anterior e aguardo novas informações para que possa ser finalizado.

**Comment by phdmauricio** [comment]
Olá Estela; Ficaram todas excelentes, como de costume.
