### ISSUE TITLE
Definir a política de licenças a serem utilizadas nos materiais do programa

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#60]
Qualquer material produzido pelo programa deve ser disponibilizado com uma licença. Temos que definir isso.

**Comment by elisribas** [comment]
@mariagelain Vamos trabalhar juntas nessa demanda.

**Comment by elisribas** [comment]
@mariagelain Criar uma cartilha informando sobre os diferentes tipos de licença e que os materiais produzidos pelo Practice terá licença CC BY-NC-SA. Ver infos em https://br.creativecommons.org/licencas/

**Comment by elisribas** [comment]
@lcaimi @Dovyski Fizemos uma [prévia](https://docs.google.com/document/d/1Ohqw5SlPjHGOC8FaFTp4KlUnWe89kKJhvxBxDxiUvUk/edit) de explicações dos tipos de licença e agora precisamos definir, entre nós da gerência, quais vamos definir. Eu sugiro que tenhamos os tipos de licença:

**Atribuição-NãoComercial - CC BY-NC: Esta licença permite que outros remixem, adaptem e criem a partir do seu trabalho para fins não comerciais, e embora os novos trabalhos tenham de lhe atribuir o devido crédito e não possam ser usados para fins comerciais, os usuários não têm de licenciar esses trabalhos derivados sob os mesmos termos.

Atribuição-NãoComercial-CompartilhaIgual - CC BY-NC-SA: Esta licença permite que outros remixem, adaptem e criem a partir do seu trabalho para fins não comerciais, desde que atribuam a você o devido crédito e que licenciem as novas criações sob termos idênticos.**

Dúvidas, vejam o documento.
@mariagelain, aguardaremos a definição para tocarmos a produção gráfica do material.

**Comment by Dovyski** [comment]
O meu voto é para usarmos `CC BY-NC` em vez de `CC BY-NC-SA`. Minha visão é que `CC BY-NC` protege nossos direitos, garante amplo acesso, e _não_ limita projetos que estejam usando alguma licença diferente de `CC BY`. Por exemplo, alguma instituição pode colocar nosso material em um projeto educativo de software com licença mista (`MIT`, `Apache 2.0`, `GPL`, etc).

Se escolhermos `CC BY-NC-SA`, o conteúdo não pode ser vinculado a esse software sem alterar a sua licença (o que nem sempre é possível). De qualquer forma, `CC BY-NC-SA` também funciona pra mim.

**Comment by mariagelain** [comment]
A cartilha está em produção, espero a resolução final de qual licença usaremos para então solicitar a revisão textual e gráfica do material.

**Comment by alessandrapedrotti** [comment]
> O texto da cartilha, a principio, está pronto. Peço para que a @alessandrapedrotti faça a revisão textual e que a @estelavilasboas faça as adições de imagem necessárias.

Revisão textual finalizada. Foram necessárias poucas alterações.

Solicito que a @elisribas dê a última olhada e feche a issue.

**Comment by Dovyski** [comment]
Eu achei a cartilha excelente, parabéns, pessoal! Eu fiz uma pequenas alterações tipográficas (algumas coisas em negrito, inclusão de uma imagem no final). Se não gostarem, podem desfazer minhas alterações.

Uma questão geral de diagramação (talvez a @practice-uffs/con-design possa opinar): a margem de parágrafo é mesmo necessária? Não fica mais legal ter o texto começando na mesma margem? Por exemplo:

![image](https://user-images.githubusercontent.com/512405/91333145-96911f00-e7a3-11ea-92d6-55cbee9afbfd.png)

Parece melhor do que:

![image](https://user-images.githubusercontent.com/512405/91333170-a0b31d80-e7a3-11ea-872f-cb8c33ed14fb.png)

**Comment by alessandrapedrotti** [comment]
> Eu achei a cartilha excelente, parabéns, pessoal! Eu fiz uma pequenas alterações tipográficas (algumas coisas em negrito, inclusão de uma imagem no final). Se não gostarem, podem desfazer minhas alterações.
> 
> Uma questão geral de diagramação (talvez a @practice-uffs/con-design possa opinar): a margem de parágrafo é mesmo necessária? Não fica mais legal ter o texto começando na mesma margem? Por exemplo:
> 
> ![image](https://user-images.githubusercontent.com/512405/91333145-96911f00-e7a3-11ea-92d6-55cbee9afbfd.png)
> 
> Parece melhor do que:
> 
> ![image](https://user-images.githubusercontent.com/512405/91333170-a0b31d80-e7a3-11ea-872f-cb8c33ed14fb.png)

Não que seja impossível deixar sem o recuo de parágrafo, mas eu acho muito importante, porque assim o leitor consegue identificar as divisões do texto. Se retirarmos o recuo, não vai ser possível identificar o que é parágrafo e o que é apenas um início de frase depois de um ponto no mesmo parágrafo.

**Comment by Dovyski** [comment]
Sem problemas, @alessandrapedrotti , e concordo com as tuas colocações. Tudo certo da minha parte.

**Comment by alessandrapedrotti** [comment]
Movido para https://drive.google.com/drive/u/0/folders/1HQ8xXPLlBfsx5XI6WaRl-3PfbsgzKCie
Material finalizado e pronto para ir para o site.
