### ISSUE TITLE
Elaboração de material base para revisão textual

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#61]
Texto de orientação para revisão textual.

https://drive.google.com/drive/u/0/folders/1uPeEWEIt0ZzlIB9hZuKsMxPZ6gr6mvtM

**Comment by alessandrapedrotti** [comment]
Texto de orientações para a escrita de materiais instrucionais criado hoje (23/07).

**Comment by elisribas** [comment]
@estelavilasboas é preciso trabalhar em uma versão gráfica do material criado pela @alessandrapedrotti

**Comment by alessandrapedrotti** [comment]
O texto dessa tarefa está, a princípio, pronto. Caso seja decidido pela @elisribas que o material será apresentado a comunidade, serão feitos os ajustes necessários no texto.

**Comment by alessandrapedrotti** [comment]
Material transferido para modelo de cartilha. @practice-uffs/con-design por favor fazer a revisão necessária.

**Comment by estelavilasboas** [comment]
Revisado, com adições e substituições de imagens.

**Comment by alessandrapedrotti** [comment]
@elisribas por favor olhar a versão final do produto.
@mariagelain adicionar versão 1.0 na página que ficar decidido e adicionar os créditos de revisão visual.

**Comment by alessandrapedrotti** [comment]
Cartilha concluída e pronta para ir para o site, movida para https://drive.google.com/drive/u/0/folders/1HQ8xXPLlBfsx5XI6WaRl-3PfbsgzKCie.
