### ISSUE TITLE
Apresentação para site e redes sociais

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/programa#62]
Cada integrante do projeto (coordenadores e alunos) deve elaborar um texto de apresentação sobre si mesmo. Esse texto integrará a página "equipe" do site do PRACTICE, assim como será utilizado para divulgações e posts nas redes sociais do programa.
É importante que todos os membros respeitem o limite de 500 caracteres no texto de apresentação e tenham claro que esse texto poderá sofrer alterações por questões de clareza, concordância e erros gramaticais.
Também é necessária 1 foto de cada integrante que mostre claramente o rosto da pessoa (sem óculos escuros, chapéus e outros adereços).

**Comment by CleissonVieira** [comment]
@practice-uffs/con-digital @practice-uffs/con-material @practice-uffs/con-midia @practice-uffs/dev @practice-uffs/con

**Comment by oigor** [comment]
Igor Matheus

Acadêmico de Ciências Econômicas na UFFS, Campus Laranjeiras do Sul, membro fundador da Liga de Investimentos da UFFS, paulista apaixonado por mercado financeiro e finanças pessoais.

**Comment by Dovyski** [comment]
@alessandrapedrotti você comentou na reunião que o texto precisa ser um pouco mais "descontraído", e não tão formal. Eu achei ótima a ideia. Quero apenas confirmar se o texto será mesmo nesse formato.

**Comment by alessandrapedrotti** [comment]
> @alessandrapedrotti você comentou na reunião que o texto precisa ser um pouco mais "descontraído", e não tão formal. Eu achei ótima a ideia. Quero apenas confirmar se o texto será mesmo nesse formato.

Isso. O texto deve contextualizar o leitor a respeito do integrante, não necessariamente precisa constar toda a carreira acadêmica, só realmente as informações necessárias para a contextualização. Fora isso, acredito que cada integrante pode usar da criatividade pra se apresentar.

**Comment by Dovyski** [comment]
Fernando Bevilacqua

Professor e coordenador do curso de Ciência da Computação da UFFS, Chapecó. Antes de ser professor, Fernando trabalhou como desenvolvedor de jogos em um estúdio brasileiro por vários anos. Atualmente trabalha com pesquisas relacionadas a Interação Humano-Computador e games. Nas horas vagas, contribui para projetos open-source, programa, olha vídeos de restauração e construção no Youtube. Gosta de viajar, consumir filmes/séries/livros de ficção científica, e de junções gastronômicas com amigos.

![fernando-bevilacqua (1)](https://user-images.githubusercontent.com/512405/87415146-1cb22700-c5a3-11ea-983a-31681841e9e4.jpg)

**Comment by MaNegrao** [comment]
Matheus D. Negrão

Academico de Ciência da Computação da UFFS Chapecó e um dos hosts do FronteiraCast. Paulista, corinthiano roxo e apaixonado por Star Wars e Formula 1.
![107593420_3412406522184481_530995072343389290_o](https://user-images.githubusercontent.com/31110971/87429478-3874f780-c5ba-11ea-9d7c-45e38512fff2.jpg)

**Comment by andrewmsilva** [comment]
Andrew M. Silva

Estudante e pesquisador na área da Ciência da Computação e músico multi-instrumentista. Nas horas vagas, joga diferentes jogos digitais, lê livros e artigos e assiste animações, filmes e séries. Também gosta de guardar dinheiro, cantar, cozinhar, viajar e rolezear com amigos e família.

![IMG_20200501_100500_007](https://user-images.githubusercontent.com/18292676/87464036-d2539900-c5e8-11ea-9391-42f168d6e7bc.jpg)

**Comment by isabelirk** [comment]
Isabeli R. Reik

Acadêmica do curso de Ciência da Computação, feminista, vegetariana e atenta. Apaixonada por aprender coisas novas, nas horas vagas estuda vários assuntos relacionados as áreas de sociologia, filosofia e psicologia. Ama cozinhar, ler, assistir séries/filmes e sair com os amigos.

![EXcXeZ-WkAEqVNs](https://user-images.githubusercontent.com/31291959/87479684-4a7a8880-c602-11ea-9759-7b8c53d6cc69.jpg)

**Comment by CleissonVieira** [comment]
Cleisson Vieira Raimundi, um amante da intensidade e diversidade, apaixonado por tecnologias e antiguidades, vivendo em um mundo entre a sociedade e solidão. Gosto do meio termo, mas do meio termo intenso.

Sou acadêmico do curso de Ciência da Computação da UFFS Campus Chapecó, integrante do PRACTICE e do FronteiraCast e sempre disponível para novos desafios.

**Comment by alessandrapedrotti** [comment]
Alessandra Pedrotti, acadêmica de Letras – Português e Espanhol na UFFS – Campus Chapecó. Membro da equipe de criação de conteúdo, responsável pela revisão textual dos materiais do PRACTICE. Apaixonada por sagas de fantasia intermináveis e séries de TV de qualidade duvidosa, feminista e tutora de 3 gatos em tempo integral. Também participa do podcast FronteiraCast como roteirista e apresentadora.

A foto pode ser a mesma que já está no site.

**Comment by estelavilasboas** [comment]
Estela Vilas Boas

Acadêmica de Ciência da Computação, trabalha no desenvolvimento de sistemas web e cria identidades visuais, além de pertencer a equipe do FronteiraCast. É uma colecionadora de histórias que se diverte criticando furos de roteiros alheios e os reescreve por puro capricho. No tempo livre, canta, compõe e joga diversos jogos digitais. E ela ouve Sweater Weather.


(A foto pode ser a do Git)

**Comment by mariagelain** [comment]
Maria Gelain 
acadêmica de Geografia da UFFS Campus Chapecó. Membro do PRACTICE e também do FronteiraCast. Vegetariana, entusiasta de plantas, gatos e piadas ruins. Ama desenhar, ouvir música, assistir séries e animações, conversar e cozinhar.

A foto pode ser a mesma que já está no site

**Comment by phdmauricio** [comment]
A foto pode ser aquela que esta lá já. O texto segue: 

Maurício Fernando Bozatski

É professor na UFFS desde sua inauguração em 2010. Foi o primeiro coordenador do Curso de Filosofia; Atuou na Assistência Estudantil, nos Assuntos Internacionais, sendo responsável pela criação do JUFFS, PROHAITI, foi Coordenador do Programa Ciência sem Fronteiras; do Programa Inglês sem Fronteiras; ajudou a fundar o Fronteira Sul Futebol Clube e o FronteiraCast. É doutor em Filosofia da Tecnologia – por isso a paixão por tecnologia e inovação. Antes da UFFS foi professor no Paraná, atuando na Rede Pública e Privada de Ensino, no Ensino Médio, Superior e no EJA para estudantes em reclusão de liberdade numa penitenciária de segurança máxima. Antes de ser professor já atuou no “comércio internacional”  (Viagens semanais para Ciudad del Este); Foi apicultor, trabalhou em um madeireira e também foi sócio proprietário de um Bar da família. Além de tecnologias, filosofia e suas interfaces é um entusiasta por videogames, filmes, séries, rock, animais, vida selvagem e viagens...Dizem que também consegue produzir comida decente.

**Comment by alessandrapedrotti** [comment]
> A foto pode ser aquela que esta lá já. O texto segue:
> 
> Maurício Fernando Bozatski
> 
> É professor na UFFS desde sua inauguração em 2010. Foi o primeiro coordenador do Curso de Filosofia; Atuou na Assistência Estudantil, nos Assuntos Internacionais, sendo responsável pela criação do JUFFS, PROHAITI, foi Coordenador do Programa Ciência sem Fronteiras; do Programa Inglês sem Fronteiras; ajudou a fundar o Fronteira Sul Futebol Clube e o FronteiraCast. É doutor em Filosofia da Tecnologia – por isso a paixão por tecnologia e inovação. Tradutor dos livros do filóisofo Don Ihde para a língua portuguesa. Antes da UFFS foi professor no Paraná, atuando na Rede Pública e Privada de Ensino, no Ensino Médio, Superior e no EJA para estudantes em reclusão de liberdade numa penitenciária de segurança máxima. Antes de ser professor já atuou no “comércio internacional” (Viagens semanais para Ciudad del Este); Foi apicultor, trabalhou em um madeireira e também foi sócio proprietário de um Bar da família; construtor de barcos e domador de cavalos. Além de tecnologias, filosofia e suas interfaces é um entusiasta por videogames, filmes, séries, rock, animais, natureza e viagens...Dizem que também consegue produzir comida decente.

Prof, o sr passou do limite de caracteres estipulados. Teria como fazer uma redução do texto?
E a foto que está no site é uma que estas usando óculos escuros. Na descrição da issue eu coloquei que o ideal seriam fotos em que a pessoa não estivesse usando esse tipo de adereço, para que quem for ver a descrição no site (e futuramente nas redes sociais)  consiga ver bem o rosto de cada integrante.

**Comment by phdmauricio** [comment]
Exisitiam limites?

**Comment by phdmauricio** [comment]
Vou achar uma fotos sem óculos.

Pode ser esta aqui Ale,por gentileza:

![mauricio site](https://user-images.githubusercontent.com/66969029/87792327-1da0be00-c81a-11ea-83d1-a91a681a8622.jpg)

**Comment by phdmauricio** [comment]
vou sumarizar o texto, li a descrição agora.

**Comment by vini2reis** [comment]
Vinicius dos Reis (nao uso o "de Jesus" por questões históricas), acadêmico de Ciência da Computação da UFFS Chapecó. Co-criador e host do FronteiraCast. Paulista, bissexual, fanático por esportes, torcedor do tricolor paulista e um nerd de carteirinha apaixonado por Harry Potter. Vidasnegrasimportam!✊

(A foto pode ser a mesma que já está no site)

**Comment by lucasgalize** [comment]
Lucas Ferreira, 25 anos, paranaense, acadêmico do curso de Agronomia na UFFS. Formado em 
Técnico em Agropecuária e _treinee_ em Agronegócio na Liga de Investimentos. Curte Fórmula 1, é fã do Tricampeão Ayrton Senna, corintiano, é apaixonado por fotografia, séries, e Star Wars. 
Preza pela cultura Gaúcha e um bom mate, é fundador do evento Hora do Mate em Laranjeiras do Sul desde 2017. 

![96120346_10218359196871145_2228553195821465600_o](https://user-images.githubusercontent.com/67007449/87814890-f73f4a80-c83a-11ea-984b-261205a0c326.jpg)

**Comment by VIF-Franca** [comment]
Vinícius França é graduando de Ciências Econômicas na UFFS, desenvolve pesquisa sobre a Economia do Crime com foco nas repercussões da lavagem de dinheiro na macroeconomia, co-fundador e atual vice-presidente da Liga de Investimentos da UFFS, já integrou a tesouraria e a presidência da SAECO nas 6ª e 7ª edições, Atualmente é empresário do ramo alimentício, exerce atividade de assessoria financeira para PME. Entusiasta de viagens, fascinado pelos seriados Suits, House of Cards e diversas series espanholas. Tem um Pug (vulgo Keynes), é adepto a caminhadas noturnas e dedica horas semanais para matear com os amigos, embora seja paulista.

**Comment by alessandrapedrotti** [comment]
> Vinícius França é graduando de Ciências Econômicas na UFFS, desenvolve pesquisa sobre a Economia do Crime com foco nas repercussões da lavagem de dinheiro na macroeconomia, co-fundador e atual vice-presidente da Liga de Investimentos da UFFS, já integrou a tesouraria e a presidência da SAECO nas 6ª e 7ª edições, Atualmente é empresário do ramo alimentício, exerce atividade de assessoria financeira para PME. Entusiasta de viagens, fascinado pelos seriados Suits, House of Cards e diversas series espanholas. Tem um Pug (vulgo Keynes), é adepto a caminhadas noturnas e dedica horas semanais para matear com os amigos, embora seja paulista.

Ficou muito legal o texto. Precisamos de uma foto bacana que mostre bem seu rosto também!

**Comment by VIF-Franca** [comment]
> > Vinícius França é graduando de Ciências Econômicas na UFFS, desenvolve pesquisa sobre a Economia do Crime com foco nas repercussões da lavagem de dinheiro na macroeconomia, co-fundador e atual vice-presidente da Liga de Investimentos da UFFS, já integrou a tesouraria e a presidência da SAECO nas 6ª e 7ª edições, Atualmente é empresário do ramo alimentício, exerce atividade de assessoria financeira para PME. Entusiasta de viagens, fascinado pelos seriados Suits, House of Cards e diversas series espanholas. Tem um Pug (vulgo Keynes), é adepto a caminhadas noturnas e dedica horas semanais para matear com os amigos, embora seja paulista.
> 
> Ficou muito legal o texto. Precisamos de uma foto bacana que mostre bem seu rosto também!

Enviada...


![WhatsApp Image 2020-07-20 at 23 04 41](https://user-images.githubusercontent.com/66980370/88004452-718ef980-cadd-11ea-8933-a78268f782d9.jpeg)

**Comment by elisribas** [comment]
Preciso comentar que esse povo é muito bonito! Gente, vocês são demais!! ♥♥

**Comment by elisribas** [comment]
Elis|ângela Ribas, Pedagoga, Doutora em Educação em Ciências e Matemática. Estuda os processos de ensino e aprendizagem, em especial aqueles ligados à Educação a Distância. Pedagoga no Núcleo de Apoio Pedagógico e Assessoria Pedagógica, da UFFS Campus Chapecó. Coordenadora Pedagógica no Practice, responsável pela equipe de Conteúdo. Gaúcha em solo catarinense! Apaixonada pela natureza, pelos animais, por pessoas leves e por tantas outras coisas que o limite de caracteres não permitiram expor! ♥

**quero mudar o tamanho da imagem, logo, enviar outro arquivo de imagem, alguém ajugaaaaa**

![alt text](https://github.com/practice-uffs/website-programa/blob/master/src/images/equipe/elisangela-ribas.jpg?raw=true)

**Comment by alessandrapedrotti** [comment]
> Vinícius França é graduando de Ciências Econômicas na UFFS, desenvolve pesquisa sobre a Economia do Crime com foco nas repercussões da lavagem de dinheiro na macroeconomia, co-fundador e atual vice-presidente da Liga de Investimentos da UFFS, já integrou a tesouraria e a presidência da SAECO nas 6ª e 7ª edições, Atualmente é empresário do ramo alimentício, exerce atividade de assessoria financeira para PME. Entusiasta de viagens, fascinado pelos seriados Suits, House of Cards e diversas series espanholas. Tem um Pug (vulgo Keynes), é adepto a caminhadas noturnas e dedica horas semanais para matear com os amigos, embora seja paulista.

França, percebi agora que seu texto extrapolou o limite de caracteres. Você pode reduzi-lo um pouco?

**Comment by VIF-Franca** [comment]
> > Vinícius França é graduando de Ciências Econômicas na UFFS, desenvolve pesquisa sobre a Economia do Crime com foco nas repercussões da lavagem de dinheiro na macroeconomia, co-fundador e atual vice-presidente da Liga de Investimentos da UFFS, já integrou a tesouraria e a presidência da SAECO nas 6ª e 7ª edições, Atualmente é empresário do ramo alimentício, exerce atividade de assessoria financeira para PME. Entusiasta de viagens, fascinado pelos seriados Suits, House of Cards e diversas series espanholas. Tem um Pug (vulgo Keynes), é adepto a caminhadas noturnas e dedica horas semanais para matear com os amigos, embora seja paulista.
> 
> França, percebi agora que seu texto extrapolou o limite de caracteres. Você pode reduzi-lo um pouco?

É graduando em Economia na UFFS, desenvolve pesquisa sobre Economia do Crime focado nas repercussões da lavagem de dinheiro, co-fundador e vice-presidente da Liga de Investimentos, já integrou a tesouraria e a presidência da SAECO. Atualmente é empresário do ramo alimentício, exerce atividade de assessoria financeira para PME. Entusiasta de viagens, fascinado nos seriados Suits e House of Cards. Tem um Pug, o Keynes, é adepto a caminhadas adora dedicar horas para matear, embora seja paulista.

Ajustado rsrs

**Comment by CleissonVieira** [comment]
@lcaimi consegue enviar uma foto sua conforme descrição para utilizar no site?

**Comment by lcaimi** [comment]
Luciano Lores Caimi

Professor do curso de de Ciência da Computação da UFFS, Chapecó. Possui graduação e mestrado em Engenharia Elétrica e doutorado em Ciência da Computação. 
Trabalhou com o desenvolvimento e instalação de produtos para automação de Pequenas Centrais Hidrelétricas e como professor em Universidades Comunitárias no RS. Na UFFS atuou como Diretor de Infraestrutura de Tecnologia da Informação na UFFS entre 2011 e 2014. Atualmente trabalha com pesquisas relacionadas a comunicação e segurança em sistemas de múltiplos núcleos que utilizam redes intra-chip. Gosto de chimarrão, viagens, futebol, séries e filmes (suspense policial e de nerd preferencialmente)

![caimi_face](https://user-images.githubusercontent.com/12415747/88727053-3f951d00-d105-11ea-9eaa-d3cfd6eddb87.jpg)

**Comment by VIF-Franca** [comment]
@alessandrapedrotti  já podemos realizar as postagens nas redes sociais, pensei em postar uma equipe por dia, visando movimentar a página diariamente, o que acha ?

**Comment by alessandrapedrotti** [comment]
> @alessandrapedrotti já podemos realizar as postagens nas redes sociais, pensei em postar uma equipe por dia, visando movimentar a página diariamente, o que acha ?

Farei a revisão textual dos perfis que estão pendentes ai sinalizo aqui quando estiver pronto.

Para a postagem nas redes, acredito que é a gerência que deve liberar.

**Comment by alessandrapedrotti** [comment]
> Luciano Lores Caimi
> 
> Professor do curso de de Ciência da Computação da UFFS, Chapecó. Possui graduação e mestrado em Engenharia Elétrica e doutorado em Ciência da Computação.
> Trabalhou com o desenvolvimento e instalação de produtos para automação de Pequenas Centrais Hidrelétricas e como professor em Universidades Comunitárias no RS. Na UFFS atuou como Diretor de Infraestrutura de Tecnologia da Informação na UFFS entre 2011 e 2014. Atualmente trabalha com pesquisas relacionadas a comunicação e segurança em sistemas de múltiplos núcleos que utilizam redes intra-chip. Gosto de chimarrão, viagens, futebol, séries e filmes (suspense policial e de nerd preferencialmente)
> 
> ![caimi_face](https://user-images.githubusercontent.com/12415747/88727053-3f951d00-d105-11ea-9eaa-d3cfd6eddb87.jpg)

@lcaimi seu texto extrapolou o número de caracteres estipulados na descrição, é necessário reduzi-lo.

**Comment by alessandrapedrotti** [comment]
> > @alessandrapedrotti já podemos realizar as postagens nas redes sociais, pensei em postar uma equipe por dia, visando movimentar a página diariamente, o que acha ?
> 
> Farei a revisão textual dos perfis que estão pendentes ai sinalizo aqui quando estiver pronto.
> 
> Para a postagem nas redes, acredito que é a gerência que deve liberar.

Esqueci de dizer, aguardo as adaptações sugeridas em 2 perfis.

**Comment by elisribas** [comment]
@lcaimi  e @phdmauricio, @alessandrapedrotti ? Se for, por favor, podem providenciar as alterações solicitadas com brevidade, colegas?

**Comment by phdmauricio** [comment]
Maurício Fernando Bozatski

Professor do Curso de Filosofia da UFFS. Áreas de interesse e atuação: Filosofia da Tecnologia; Antropologia Evolutiva; Economia e Tecnociência. Bio: https://filosofiadatecnologia.com/bio/

**Comment by lcaimi** [comment]
Luciano Lores Caimi

Professor do curso de de Ciência da Computação da UFFS. Gradução e mestrado em Eng. Elétrica e doutorado em Ciência da Computação. Trabalhei com o desenvolvimento e instalação de produtos para automação de PCHs e como professor em Universidades Comunitárias no RS. Na UFFS atuei como Diretor de Infraestrutura de Tecnologia da Informação. Pesquiso comunicação e segurança em sistemas de múltiplos núcleos. Gosto de chimarrão, viagens, futebol (vamô Inter!!!) e séries.

**Comment by elisribas** [comment]
Considerando que todas as revisões foram feitas, o conteúdo está pronto para ser publicado nas redes sociais.
Antes de ir ao ar, favor excluir minha apresentação.
@VIF-Franca

**Comment by VIF-Franca** [comment]
> > @alessandrapedrotti já podemos realizar as postagens nas redes sociais, pensei em postar uma equipe por dia, visando movimentar a página diariamente, o que acha ?
> 
> Farei a revisão textual dos perfis que estão pendentes ai sinalizo aqui quando estiver pronto.
> 
> Para a postagem nas redes, acredito que é a gerência que deve liberar.

@elisribas e @alessandrapedrotti qual pasta do drive está as revisões realizadas ? Não encontrei a pasta #62 nas tarefas do drive.

**Comment by VIF-Franca** [comment]
Sobre a arte que será postada no _feed_, na live de apresentação do PRACTICE foi elaborado [essas imagens](https://drive.google.com/drive/u/0/folders/1LuNMIIDxVwiPPsWPTS9Vse-9EdJNKijY), será utilizada essa ???  Caso sim, como deveremos realizar a postagem... um post para cada equipe... um post para cada membro... ??? Obs.: post único com todos os membros não é possível pois no estilo carrossel é limitado o número de imagens. 

![17](https://user-images.githubusercontent.com/66980370/92350788-62c1cd80-f0b0-11ea-891e-22fddbc3a083.png)

**Comment by VIF-Franca** [comment]
DÚVIDAS... 

A) Creio que devemos colocar o link da [PORTARIA Nº 610/GR/UFFS/2020](https://www.uffs.edu.br/atos-normativos/portaria/gr/2020-0610) de nomeação de todos os membros, essa versão está desatualizada, dúvida seguimos todos os nomes que nelas consta ? OU realizamos a exclusão dos membros que já saíram do PRACTICE, talvez devemos consultar os que já saíram se querem ou não, haja vista que já fizeram parte e talvez queira o registro disso e salve engano não temos a  publicação oficial de exoneração.

B) É necessário criar um termo de autorização de veiculação de imagens ? Na minha opinião acho valido juridicamente ([exemplo ilustrativo](http://www.gestaoescolar.diaadia.pr.gov.br/arquivos/File/pdf/termo_autorizacao_imagem_filmagem.pdf)) julgo ser valido haja visto que iremos postar a foto de diversas pessoas em mídias sociais. 


@Dovyski @phdmauricio e @lcaimi

**Comment by Dovyski** [comment]
Em relação às dúvidas:

a) Não acho necessário, pode prosseguir sem a portaria. A sequencia de posts é sobre os integrantes do programa, não sobre os detalhes institucionais dele.

b) Em teoria sim, porém todas as imagens e descrições foram fornecidas pelos próprios autores com a exclusiva finalidade de postar nas redes sociais. Há um consentimento quanto a texto e imagem. Não acho que precisamos dos termos.

**Comment by alessandrapedrotti** [comment]
> > > @alessandrapedrotti já podemos realizar as postagens nas redes sociais, pensei em postar uma equipe por dia, visando movimentar a página diariamente, o que acha ?
> > 
> > 
> > Farei a revisão textual dos perfis que estão pendentes ai sinalizo aqui quando estiver pronto.
> > Para a postagem nas redes, acredito que é a gerência que deve liberar.
> 
> @elisribas e @alessandrapedrotti qual pasta do drive está as revisões realizadas ? Não encontrei a pasta #62 nas tarefas do drive.

Eu fiz a revisão aqui pelo github mesmo, para fazer as postagem você só precisa se atentar para pegar os comentários corretos.

**Comment by VIF-Franca** [comment]
> > > > @alessandrapedrotti já podemos realizar as postagens nas redes sociais, pensei em postar uma equipe por dia, visando movimentar a página diariamente, o que acha ?
> > > 
> > > 
> > > Farei a revisão textual dos perfis que estão pendentes ai sinalizo aqui quando estiver pronto.
> > > Para a postagem nas redes, acredito que é a gerência que deve liberar.
> > 
> > 
> > @elisribas e @alessandrapedrotti qual pasta do drive está as revisões realizadas ? Não encontrei a pasta #62 nas tarefas do drive.
> 
> Eu fiz a revisão aqui pelo github mesmo, para fazer as postagem você só precisa se atentar para pegar os comentários corretos.

@alessandrapedrotti unifiquei todos no drive, [clique aqui](https://docs.google.com/spreadsheets/d/1PvuDG2VYJPXou-BsCPy_KgsX7Y-sf2GyemNaSdinB1g/edit#gid=0). Creio que você precisa dar uma olhada pois tem alguns errinhos.

**Comment by VIF-Franca** [comment]
> Sobre a arte que será postada no _feed_, na live de apresentação do PRACTICE foi elaborado [essas imagens](https://drive.google.com/drive/u/0/folders/1LuNMIIDxVwiPPsWPTS9Vse-9EdJNKijY), será utilizada essa ??? Caso sim, como deveremos realizar a postagem... um post para cada equipe... um post para cada membro... ??? Obs.: post único com todos os membros não é possível pois no estilo carrossel é limitado o número de imagens.
> 
> ![17](https://user-images.githubusercontent.com/66980370/92350788-62c1cd80-f0b0-11ea-891e-22fddbc3a083.png)
> 
> cc. @estelavilasboas @practice-uffs/con-design

rt

**Comment by alessandrapedrotti** [comment]
> > > > > @alessandrapedrotti já podemos realizar as postagens nas redes sociais, pensei em postar uma equipe por dia, visando movimentar a página diariamente, o que acha ?
> > > > 
> > > > 
> > > > Farei a revisão textual dos perfis que estão pendentes ai sinalizo aqui quando estiver pronto.
> > > > Para a postagem nas redes, acredito que é a gerência que deve liberar.
> > > 
> > > 
> > > @elisribas e @alessandrapedrotti qual pasta do drive está as revisões realizadas ? Não encontrei a pasta #62 nas tarefas do drive.
> > 
> > 
> > Eu fiz a revisão aqui pelo github mesmo, para fazer as postagem você só precisa se atentar para pegar os comentários corretos.
> 
> @alessandrapedrotti unifiquei todos no drive, [clique aqui](https://docs.google.com/spreadsheets/d/1PvuDG2VYJPXou-BsCPy_KgsX7Y-sf2GyemNaSdinB1g/edit#gid=0). Creio que você precisa dar uma olhada pois tem alguns errinhos.

Prontinho @VIF-Franca, inclusive ficou muito legal essa tabela que tu fez, acho que podemos alimentá-la futuramente com as bios dos novos bolsistas pra ter um "banco" de informações bem legal.

**Comment by Dovyski** [comment]
@VIF-Franca em relação a forma de postagem, pode usar o layout da @practice-uffs/con-design porém *sem* a barra de informação, assim:

<img width="415" alt="92350788-62c1cd80-f0b0-11ea-891e-22fddbc3a083" src="https://user-images.githubusercontent.com/512405/92922383-240f7880-f40c-11ea-9541-ad9d7828fd27.png">

A informação sobre o que a pessoa faz, equipe, etc, será em formato de texto no próprio post. Lembrar de usar a resolução máxima permitida para imagens para cada rede social. Por exemplo, no Instagram esse tamanho é `1080x1080`.

Por favor, cria uma issue nova relacionada com a postagem de cada membro, com a data na qual cada membro será postado. Podemos fazer um intervalo de no mínimo 1 dia entre cada postagem.
