### ISSUE TITLE
Live Palestras do VIII EPEA e VII Semana Acadêmica de Engenharia de Alimentos (VII SEMEA) - 15/07 (14h - 17h)

### ISSUE THREAD

**Issue by MilenaPaz2020** [practice-uffs/programa#620]
<h1 align="center" >Informações Transmissão Ao Vivo</h1>

**Titulo**: Palestras do VIII EPEA e VII Semana Acadêmica de Engenharia de Alimentos (VII SEMEA) 

**Data e Hora**: 15/07 (14h - 17h)

**Evento Geral** (se houver): VIII Encontro Paranaense de Engenharia de Alimentos (VIII EPEA) e VII Semana Acadêmica de Engenharia de Alimentos (VII SEMEA)

**Solicitante**: Jaíne do Amaral Pare

**Realizador(es)**: Curso de Engenharia de Alimentos

**Solicitação no Mural**: https://mural.practice.uffs.cc/servico/362

**Link Transmissão**: _Precisa ser criado. A transmissão ocorrerá no canal do curso de Eng. de alimentos._

Com os dados e roteiro em mãos, o responsável pela Live deve seguir os padrões do PRACTICE e estabelecer contato com o solicitante, enviando inicialmente o Protocolo de Execução de Lives.

**[Planilha de Lives](https://drive.google.com/drive/folders/16h-YVwTnRF49eqBYBRONKyLqPbisCIbH)**

**[Protocolo de Execução de Lives](https://drive.google.com/file/d/1KQ9vI1gKECqWHi4xwb3LrnuWCgKEHWyd/view?usp=sharing)**

**[Padronização de Lives](https://drive.google.com/file/d/1Bky3nLRTAoCejzHrH0D93GQ_gjsa4Hxl/view?usp=sharing)**

**[TeleCurso 2000](https://drive.google.com/drive/folders/1r_Gea2VxB3J-4VfIXr9jqXa2NgStNvCs?usp=sharing)**

CC: @con-midia / lives

**Comment by MilenaPaz2020** [comment]
Estranho, o bot não criou as pastas. Mas os arquivos estão [aqui](https://drive.google.com/drive/folders/1Bor482wBibOGQjqfMFK_9hblpybSS5I9?usp=sharing).

**Comment by pedroamaximowski** [comment]
A solicitante já me enviou as capas e eu já as coloquei na pasta do drive.

**Comment by MilenaPaz2020** [comment]
Encerrando demanda. @pedroamaximowski, caso ainda não tenha atualizado a planilha de lives faça isso quanto retornar do recesso.

**Comment by pedroamaximowski** [comment]
Desculpa, acabei esquecendo de encerrar a demanda aqui no Github.

**Comment by luizatonial** [comment]
Temos 3 preenchimentos de formulário referentes à #619 e #620, então por favor verifique a [planilha de lives](https://docs.google.com/spreadsheets/d/1e1Dritl0YD1UljjbF8AME4__hyOunQoFiXQerzoXluU/edit#gid=655858290). 
São as lives nº 1,5 e 6 (que estão destacadas em vermelho) na aba 'jul21-set21'.
Peço que o @pedroamaximowski apague qual está errada e atualize as demais. Obrigada!
