### ISSUE TITLE
Live Abertura Semana Acadêmica de Física - 09/08 (19h - 20h20)

### ISSUE THREAD

**Issue by MilenaPaz2020** [practice-uffs/programa#623]
<h1 align="center" >Informações Transmissão Ao Vivo</h1>

**Titulo**:  Abertura Semana Acadêmica de Física 

**Data e Hora**:  09/08 (19h - 20h20)

**Evento Geral** (se houver): Semana Acadêmica de Física - Campus Realeza

**Solicitante**: Robison José

**Realizador(es)**: CA Física

**Palestrante Principal**: Professores Beal e Viviane

**Solicitação no Mural**: https://mural.practice.uffs.cc/servico/439

**Link Transmissão**:  https://youtu.be/8C6ts1Ujgos

Com os dados e roteiro em mãos, o responsável pela Live deve seguir os padrões do PRACTICE e estabelecer contato com o solicitante, enviando inicialmente o Protocolo de Execução de Lives.

**[Planilha de Lives](https://drive.google.com/drive/folders/16h-YVwTnRF49eqBYBRONKyLqPbisCIbH)**

**[Protocolo de Execução de Lives](https://drive.google.com/file/d/1KQ9vI1gKECqWHi4xwb3LrnuWCgKEHWyd/view?usp=sharing)**

**[Padronização de Lives](https://drive.google.com/file/d/1Bky3nLRTAoCejzHrH0D93GQ_gjsa4Hxl/view?usp=sharing)**

**[TeleCurso 2000](https://drive.google.com/drive/folders/1r_Gea2VxB3J-4VfIXr9jqXa2NgStNvCs?usp=sharing)**

CC: @con-midia / lives

**Comment by MilenaPaz2020** [comment]
Formulário ainda não preenchido, mas para fins de organização a issues já estão sendo abertas.

**Comment by luizatonial** [comment]
como será numa segunda já sei que não consigo assumir, se o @pedroamaximowski puder...

**Comment by robisonjose** [comment]
Lembrando que, como ainda temos quase dois meses pela frente, uma possibilidade é que a própria @GessicaZanon faça algumas das transmissões.

**Comment by GessicaZanon** [comment]
> Lembrando que, como ainda temos quase dois meses pela frente, uma possibilidade é que a própria @GessicaZanon faça algumas das transmissões.

Ficaria extremamente feliz se eu puder fazer! Acredito que já estarei bem mais acostumada e habituada com todos os processos.. kkkk

E como estou na organização da semana acadêmica também, tenho contato bem direto com o pessoal.

**Comment by MilenaPaz2020** [comment]
Acho a ideia perfeita! <3

**Comment by MilenaPaz2020** [comment]
Formulário da transmissão e protocolo estão [aqui](https://drive.google.com/drive/u/0/folders/11ysK8-sTXP1G3J07ZFp3lDgckBIefFXr).

**Comment by MilenaPaz2020** [comment]
Link da transmissão criado. As lives ocorrerão no nosso canal. Havendo capa da transmissão, favor acrescentar no YT.

**Comment by luizatonial** [comment]
@GessicaZanon nós temos a [planilha de lives](https://docs.google.com/spreadsheets/d/1e1Dritl0YD1UljjbF8AME4__hyOunQoFiXQerzoXluU/edit#gid=655858290), onde coletamos alguns dados sobre as transmissões realizadas pela equipe.
Preenchi as suas duas lives do dia 09/08, você pode seguir o modelo nas próximas lives... ai você pode atualizar a planilha e fechar as issues quando finalizar as transmissões.

**Comment by GessicaZanon** [comment]
> @GessicaZanon nós temos a [planilha de lives](https://docs.google.com/spreadsheets/d/1e1Dritl0YD1UljjbF8AME4__hyOunQoFiXQerzoXluU/edit#gid=655858290), onde coletamos alguns dados sobre as transmissões realizadas pela equipe.
> Preenchi as suas duas lives do dia 09/08, você pode seguir o modelo nas próximas lives... ai você pode atualizar a planilha e fechar as issues quando finalizar as transmissões.

Perfeito! Obrigada, Luiza!
