### ISSUE TITLE
Escolha de camisetas e moletons

### ISSUE THREAD

**Issue by estelavilasboas** [practice-uffs/programa#64]
Com a Issue #59, foram criadas ideias para camisetas, moletons e canecas do programa e precisamos da colaboração de todos para a decisão final. 

- Para cada item/comentário, cada integrante tem direito de votar em **até 2 opções**. 
- A votação será contabilizada a partir das **reações nos comentários**. Cada opção terá uma reação correspondente em sua descrição. 
- **Leia com atenção** cada pergunta/comentário
- A votação seguirá até segunda-feira (20/07) às 19h.

Todas as imagens originais estão disponíveis na[ pasta da Issue](https://drive.google.com/drive/u/0/folders/1gHgDiNs4HFmHr-WzVRSy5nFN_PRDQJ2c ).

`As ideias foram criadas sem o conhecimento prévio de qual empresa prestaria o serviço, sendo assim alguns modelos podem sofrer pequenas alterações.`

**Comment by estelavilasboas** [comment]
### Escolha o moletom
`Selecione até 2 opções`


Azul com capuz laranja 👍 
![Azul com capuz laranja](https://user-images.githubusercontent.com/30927758/87791451-a28ad800-c818-11ea-8bc9-ae6f6eba9273.png)

Preto com capuz laranja 😆
![Preto com capuz laranja](https://user-images.githubusercontent.com/30927758/87791509-c3ebc400-c818-11ea-846d-c882e8121f1c.png)

Azul com capuz branco, com a lâmpada ❤️ 
![Azul com capuz branco, estampado com a lâmpada](https://user-images.githubusercontent.com/30927758/87791569-dd8d0b80-c818-11ea-945a-dab0c7602750.png)

Preto com capuz branco, com a lâmpada 🎉 
![Preto com capuz branco, estampado com a lâmpada](https://user-images.githubusercontent.com/30927758/87791621-f4336280-c818-11ea-8c0c-a671c482e82c.png)

Azul com capuz azul, com a lâmpada 👀 
![Azul com capuz azul, estampado com a lâmpada](https://user-images.githubusercontent.com/30927758/87791707-1a590280-c819-11ea-94a7-e672cc8b5e60.png)

"Não gostei de nenhum, eu lamento" 👎

**Comment by estelavilasboas** [comment]
### Escolha a COR da camiseta
Essa escolha afeta **APENAS A COR** da camiseta. Escolha até 2 opções.

Azul :+1:
![Camiseta Apenas Logo na frente](https://user-images.githubusercontent.com/30927758/87792154-dca8a980-c819-11ea-95c5-33ddbfecc1b7.png)

Preta 😆 
![Camiseta Preta](https://user-images.githubusercontent.com/30927758/87792209-efbb7980-c819-11ea-9d9a-5239b47a12f0.png)

Branca ❤️ 
![Camiseta branca](https://user-images.githubusercontent.com/30927758/87792235-fba73b80-c819-11ea-9786-1b75b88e19a8.png)

Manga azul 🎉 
![Camiseta Manga azul](https://user-images.githubusercontent.com/30927758/87792404-39a45f80-c81a-11ea-80bc-a5c9ff82f3c5.png)


"Não gostei de nenhuma cor, eu lamento" 👎

**Comment by estelavilasboas** [comment]
### Escolha como fica a LOGO na camiseta
Essa escolha afeta APENAS A POSIÇÃO da logo na camiseta.

Logo na frente, símbolo atrás :+1:
![Camiseta Logo na frente, símbolo atrás](https://user-images.githubusercontent.com/30927758/87792547-68bad100-c81a-11ea-9ebd-a31ec72bc12d.png)

Apenas Logo na frente 😆 
![Camiseta Apenas Logo na frente](https://user-images.githubusercontent.com/30927758/87792587-783a1a00-c81a-11ea-813a-e79e4562f9b5.png)

Logo virada :heart:
![Camiseta Logo virada](https://user-images.githubusercontent.com/30927758/87792628-89832680-c81a-11ea-916a-5d80ee9ba3ee.png)

"Não gostei de nenhuma, eu lamento" 👎

**Comment by estelavilasboas** [comment]
### Se você não gosta de polo, tem uma opção para você
`Polo criada a pedidos feitos diretamente à minha pessoa`

Azul :+1:
![Polo Azul](https://user-images.githubusercontent.com/30927758/87793127-352c7680-c81b-11ea-952c-7ffa25f27165.png)

Preto (é um azul tão escuro que considero preto) 😆 
![Polo Preto (é um azul tão escuro que considero preto)](https://user-images.githubusercontent.com/30927758/87793163-42e1fc00-c81b-11ea-8d80-200fce3d89cc.png)

Branca ❤️ 
![Polo Branca](https://user-images.githubusercontent.com/30927758/87793299-745ac780-c81b-11ea-84a6-eeaa20e70b5d.png)

"Não gosto de polo" 👀 

"Não gostei de nenhuma, eu lamento" 👎

**Comment by estelavilasboas** [comment]
### Caneca
Sim, só tem uma opção.

![A caneca](https://user-images.githubusercontent.com/30927758/87793473-b4ba4580-c81b-11ea-94d5-17ab601623e3.png)
Arte completa na [pasta da Issue 59](https://drive.google.com/drive/u/0/folders/1gHgDiNs4HFmHr-WzVRSy5nFN_PRDQJ2c)

A ideia é a logo ficar na lateral, assim fica legal para ***destros e canhotos***.

Reaja com 👎 se não gostou. Caso contrário, reaja com qualquer coisa.

**Comment by estelavilasboas** [comment]
Votação aberta, @practice-uffs/todos !

**Comment by Dovyski** [comment]
Eu preciso comentar que o trabalho de design da Estela é absolutamente incrível! Parabéns, Estela! 🏆❤️ 🚀

**Comment by estelavilasboas** [comment]
Votação encerrada!
E o vencedores são...

**Moletom**: azul com capuz branco, com a lâmpada 

<p align="center">
    <img width="300" height="400" src="https://user-images.githubusercontent.com/30927758/88053289-ed1a9600-cb31-11ea-93bf-3235dd26e226.png" title="Moletom"><br />
</p>

**Cor de camiseta**: azul

**Posição da logo**: ***EMPATE***! *
*Logo na frente, símbolo atrás* ***VS*** *Logo virada*

<p align="center">
    <img width="350" height="400" src="https://user-images.githubusercontent.com/30927758/88056769-72547980-cb37-11ea-960c-2f46163d2528.png" title="Camiseta posição da logo"><br />
</p>


**Polo**: Preta 
> (6 votos preta e 4 votos "Não gosto de polo")

<p align="center">
    <img width="450" height="400" src="https://user-images.githubusercontent.com/30927758/88060953-43d99d00-cb3d-11ea-9732-49dfefe8340e.png" title="Polo Preta"><br />
</p>


> *O empate será resolvido nos próximos comentários. Aguarde mais informações

**Comment by estelavilasboas** [comment]
### Decisão final da posição da logo
Como ocorreu um empate, estou abrindo essa última votação que ficará aberta até **amanhã (22/07) às 9 horas**. 
Atendendo a pedidos, fiz uma alternativa que junta as duas propostas.
Cada integrante poderá votar em **apenas 1 opção**.
Caso ocorra empate novamente, a decisão será feita através de um gerador de números aleatórios.



Logo na frente, símbolo atrás 👍
<p align="center">
    <img width=700" height="400" src="https://user-images.githubusercontent.com/30927758/88063280-3d005980-cb40-11ea-840b-73859784c7a1.png" title="Camiseta Logo na frente"><br />
</p>

Logo virada 😆 
<p align="center">
    <img width=700" height="400" src="https://user-images.githubusercontent.com/30927758/88063709-b7c97480-cb40-11ea-9529-a42061a48fed.png" title="Camiseta Logo virada"><br />
</p>

Logo virada e símbolo atrás 👀 
<p align="center">
    <img width=700" height="400" src="https://user-images.githubusercontent.com/30927758/88063893-f3fcd500-cb40-11ea-93f3-33b30b168da5.png" title="Camiseta Logo virada com símbolo atrás"><br />
</p>

**Comment by estelavilasboas** [comment]
### Votação encerrada (e sem empates)!
A vencedora do desempate foi a **"Logo na frente, simbolo atrás"** 🎉 

![image](https://user-images.githubusercontent.com/30927758/88183444-dba3bd80-cc07-11ea-9f54-96a07002d5fe.png)

> Lembrando que os mockups foram feitos sem o conhecimento de um orçamento e de qual empresa prestaria o serviço, ou seja, podem ocorrer pequenas alterações no produto final.
