### ISSUE TITLE
Criar vídeo promocional sobre o PRACTICE para o site

### ISSUE THREAD

**Issue by vini2reis** [practice-uffs/programa#65]
Criar o vídeo de apresentação do PROGRAMA para estar no site no dia do lançamento. Nele deve conter: O que é; objetivos do programa; organização (Gerência Geral e Equipes nos Campi) e horizontes de implementação. Deve ter a duração de no máximo 5 minutos.

@practice-uffs/con-midia

**Comment by MaNegrao** [comment]
O roteiro de narração do video está no drive, na pasta da issue, segue link:

https://docs.google.com/document/d/1bTwGz20RZoh7ZAT6ZQF2YZfGdvgfUvB2uh9_B89NQow/

**Comment by MaNegrao** [comment]
@phdmauricio e @lcaimi, Podem dar uma olhada no roteiro da narração do video e nos dizer se está no caminho certo?

**Comment by phdmauricio** [comment]
Olho depois que voltar da academia.

**Comment by phdmauricio** [comment]
sim, este é o caminho. Sucinto e informativo.

**Comment by MaNegrao** [comment]
@alessandrapedrotti O texto está pronto para revisão :)

**Comment by phdmauricio** [comment]
Decidiram quem vai narrar?

**Comment by vini2reis** [comment]
Então, a ideia é que o matheus e eu fizessemos a narração, mas a gente nao sabe se pode ter dois narradores. Se for só um narrador o matheus faz a narração

**Comment by phdmauricio** [comment]
Façam o teste de duas formas , aí a gente decide.

**Comment by alessandrapedrotti** [comment]
> @alessandrapedrotti O texto está pronto para revisão :)

Primeira leitura de revisão feita. Deixei alguns comentários no texto sobre pontos que os redatores precisam resolver.

Meus apontamentos:
O texto em si está muito bom, só me preocupa o teto do tempo do vídeo, já que o roteiro ficou bem extenso e considerando que a leitura do texto para a narração deve ser bem clara, talvez seja necessário encurtar o roteiro.
Seria interessante colocar os créditos do roteiro e produção no vídeo, seja em imagem ou narração, assim todas as pessoas que participaram da produção desse material seriam devidamente contempladas.

Caso seja necessária mais uma leitura de revisão após feitas as alterações que sugeri no texto, é só me marcar.

**Comment by MaNegrao** [comment]
O texto está pronto e revisado pela Alessandra. Reduzimos a parte das equipes para não ficar muito especifico.
O próximo passo é gravar e ver como fica

**Comment by MaNegrao** [comment]
Os três audios estão no drive, na mesma pasta da tarefa. Agora falta apenas decidir qual irá para o video final

**Comment by vini2reis** [comment]
O áudio escolhido para o vídeo foi o Juntos.mp3

**Comment by oigor** [comment]
Vídeo postado no Drive para revisão

**Comment by phdmauricio** [comment]
Opa. Tem o link?

**Comment by Dovyski** [comment]
O vídeo está bem legal, parabéns. Precisamos fazer algumas alterações nele:

* [ ] Várias imagens estão com resolução baixa (ficaram pixeladas).
* [ ] Utilizar fonte `Roboto` para título e `Roboto Light`  para outros textos.
* [ ] O "Apresenta" animado no começo não ficou bom. Eu removeria ele.

**Comment by MaNegrao** [comment]
Professor, tem algum trecho especifico que não está nos conformes ou o audio como um todo está comprometido?

**Comment by Dovyski** [comment]
De forma alguma o audio todo está comprometido. Eu acho que vocês podem passar um pente fino e identificar frases no qual a uma pequena pausa ou "trancadinha" (parece que o narrador vai falar uma coisa, mas fala outra).

Eu não sei se vocês gravaram o audio como um bloco só, mas talvez fosse interessante regravar apenas parágrafos que não ficaram tão "suaves".

**Comment by oigor** [comment]
As Imagens pixeladas você fala dos "apresentadores  perto da câmera" essa ficam dessa forma por se tratar da foto maior em zoom.


Posso resolver retirando o efeito de gravação e colocando de outra forma.

**Comment by MaNegrao** [comment]
Nós gravamos todo o texto cada um e intercalamos as falas. Fiz esse pente fino e identifiquei as partes que realmente dao uma engasgada, dai troquei algumas falas . Creio eu que agora está mais lapidado. O audio está na pasta do drive https://drive.google.com/drive/folders/1YikuYiofu1a3hSHExyaRC3erw4VMFXpe como "Narração Final - Corrigida"

**Comment by Dovyski** [comment]
> As Imagens pixeladas você fala dos "apresentadores perto da câmera" ?
> Elas ficam dessa forma por se tratar da foto maior em zoom.> 

Vários. Por exemplo, o primeiro texto que aparece, "Carência no Contexto Tecnológico" está pixelado. Algumas das imagens com efeito de zoom também estão pixeladas, mas não todas.

Olhando agora com mais calma, parece que *todos* os textos (com exceção do logo do PRACTICE) estão pixelados. Se eles são imagens, elas certamente não tem resolução grande. Precisam ser ajustadas.

![image](https://user-images.githubusercontent.com/512405/88587865-04bfb600-d02d-11ea-9ee3-3378b2d95430.png)


> Nós gravamos todo o texto cada um e intercalamos as falas. Fiz esse pente fino e identifiquei as partes que realmente dao uma engasgada, dai troquei algumas falas . Creio eu que agora está mais lapidado.

Ficou excelente! ❤️ Suave como manteiga agora 😄

**Comment by oigor** [comment]
[Vídeo Finalizado](https://drive.google.com/drive/folders/10lwJ3NZlBycb_UTE0ShS-NWXnnPL9wYA)

**Comment by Dovyski** [comment]
@oigor ficou muito bom!

@practice-uffs/ger eu acho que para uma primeira versão, podemos seguir com esse vídeo. O que acham?
