### ISSUE TITLE
Roteiro da live de lançamento do programa

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#66]
Essa issue é para gerenciar a criação do roteiro da live de lançamento. O roteiro será feito como um arquivo de texto auxiliado por uma apresentação no Google Slides.

* [x] Criar roteiro textual da live
* [x] Atualizar [apresentação de slides]( https://docs.google.com/presentation/d/1O3oj6F4tk4iVCnrzjNPux_JwaF34gGRv-sMfrBiTjzI/edit#slide=id.p) com "barrinha" que mostra o nome de cada apresentador (essas informações estão listadas em quadrinhos ao longo do texto do roteiro). Fazer um slide por barrinha/apresentador.
* [x] Atualizar [apresentação de slides]( https://docs.google.com/presentation/d/1O3oj6F4tk4iVCnrzjNPux_JwaF34gGRv-sMfrBiTjzI/edit#slide=id.p) e criar um slide para cada equipe (produção de material; desenvolvimento). 
* [x] Atualizar [apresentação de slides]( https://docs.google.com/presentation/d/1O3oj6F4tk4iVCnrzjNPux_JwaF34gGRv-sMfrBiTjzI/edit#slide=id.p) e, depois do slide de cada equipe, coloca um slide para cada integrante daquela equipe; o slide deve conter foto da pessoa, nome, curso e campus.

**Comment by VIF-Franca** [comment]
Olá pessoal, criei um arquivo no drive com um esboço de roteiro. 

Podemos marcar uma reunião para afinar os blocos presentes na live de lançamento ? Podemos decidir o horário pelo telegram.

**Comment by VIF-Franca** [comment]
Link para o drive: https://docs.google.com/document/d/1Us8mpqyoWiVIyCni1kRPgsY-7QybrjN2vtqMIki1yWw/edit

**Comment by Dovyski** [comment]
Tivemos uma reunião da gerência para refinar o roteiro. Fizemos as alterações no documento do @VIF-Franca acima.

Além disso, criamos uma [apresesentação](https://docs.google.com/presentation/d/1O3oj6F4tk4iVCnrzjNPux_JwaF34gGRv-sMfrBiTjzI/edit#slide=id.p) no Google Slides que será usada ao longo da live. Atualizei essa issue com o que é necessário fazer nessa apresentação.

**Comment by Dovyski** [comment]
@VIF-Franca tu pode falar com a @estelavilasboas para te ajudar com a arte das "barrinhas" com o nome de cada integrante. No momento, a [apresentação](https://docs.google.com/presentation/d/1O3oj6F4tk4iVCnrzjNPux_JwaF34gGRv-sMfrBiTjzI/edit#slide=id.p) tem um rascunho de como essas barrinhas podem ser.

**Comment by VIF-Franca** [comment]
Ok, aguardando a @estelavilasboas elaborar o "modelo" com a foto, nome, curso e campus dos membros.

**Comment by Dovyski** [comment]
@VIF-Franca você pode assumir essa tarefa, por favor. Pode utilizar as informações que estão no site e na issue de coleta de foto dos membros. A @estelavilasboas pode revisar o layout final.

**Comment by estelavilasboas** [comment]
> @VIF-Franca você pode assumir essa tarefa, por favor. Pode utilizar as informações que estão no site e na issue de coleta de foto dos membros. A @estelavilasboas pode revisar o layout final.

Já fiz a base... Só falta colocar as fotos e informações

**Comment by VIF-Franca** [comment]
Belezinha

**Comment by elisribas** [comment]
@VIF-Franca as barrinhas com os nomes **precisam** estar corretos.
Nome da pessoa - correto, ver nomes conforme estão no site
Nome do cargo da pessoa 
Ver infos no site https://practice.uffs.cc/equipe/

**Comment by VIF-Franca** [comment]
> @VIF-Franca as 'barrinhas' com os nomes **precisam** estar **corretos**.
> 
> Nome da pessoa;
> Nome do cargo da pessoa;
> Ver infos no site https://practice.uffs.cc/equipe/
> 
> **URGENTE**

Atualizadas, qualquer coisa me grite.
