### ISSUE TITLE
Atualizar as redes sociais com informações sobre a live de lançamento

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#67]
Atualizar as redes sociais com informações sobre a live de lançamento. Fazer uma postagem para cada um dos seguintes:

* [x] Vídeo de apresentação do PRACTICE (que está no Youtube)
* [x] Panfleto data e horário para a live (convite) [depende de #68]
* [ ] Postar as cartilhas disponíveis (com um link para o site)

O panfleto de convite deverá ser colocado em todas as redes sociais. Ele também será enviado por e-mail para toda a UFFS.

**Comment by VIF-Franca** [comment]
@Dovyski as cartilhas postaremos antes da live ou após a live ?

Sobre a postagem do vídeo, temos o refente a #65 é esse o vídeo ?

**Comment by VIF-Franca** [comment]
Profs o que acha de criar um Labels para todo o material que estiver perfeito para postar nas redes sociais ?

**Comment by Dovyski** [comment]
> @Dovyski as cartilhas postaremos antes da live ou após a live ?

Tentaremos postar antes da live no site.

> Sobre a postagem do vídeo, temos o refente a #65 é esse o vídeo ?

Não, é o vídeo referente à #70.

> Profs o que acha de criar um Labels para todo o material que estiver perfeito para postar nas redes sociais ?

O que estiver marcado com a label `gerência:ok` pode ser postado em redes sociais.

**Comment by VIF-Franca** [comment]
Criei um issue específica para postar as cartilhas, até o momento nenhuma cartilha está a etiqueta  `gerência: ok` para ser postada.
