### ISSUE TITLE
Panfleto com data e horário para a live

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#68]
Criar um panfleto de convite para a live de lançamento do programa. O resultado será uma imagem com as informações abaixo:

* Logo e nome do programa
* Data da live (dia e horário)
* Link para a live
* Link para o site do Practice

**Comment by estelavilasboas** [comment]
Foram criados 3 tamanhos diferentes e estão todos na [pasta da Issue](https://drive.google.com/folderview?id=17WlZtAVadplEoeS67QDZmpuyfavnzOgc).
Caso seja necessário algum ajuste, por favor informar.

**Comment by Dovyski** [comment]
Ficou lindo, Estela, parabéns!

@practice-uffs/ger-auxilio por favor, postar em todas as redes sociais do programa, inclusive no banner do vídeo do youtube onde será a live.

**Comment by VIF-Franca** [comment]
Todos os posts realizados no Facebook, Instagram e YouTube

**Comment by Dovyski** [comment]
Tivemos problemas com a live. Por favor, re-criar o panfleto para conter um *novo* link (e QR code) para a live:

[https://uffs.cc/practice-live](https://uffs.cc/practice-live)

**Comment by Dovyski** [comment]
@estelavilasboas depois que você atualizar o panfleto, por favor, avise o @VIF-Franca para que ele atualize o conteúdo das redes sociais.

**Comment by estelavilasboas** [comment]
Feito
