### ISSUE TITLE
Produzir Manual do  OBS

### ISSUE THREAD

**Issue by elisribas** [practice-uffs/programa#69]
É necessário montar um manual explicando as funcionalidades do OBS.

- Explicar o funcionamento do software por si;
- Como realizar uma transmissão a partir do Google Meet;
- Como alternal telas durante a transmissão;
- Como fazer o agendamento de horário de transmissão no YouTube.

@lucasgalize @VIF-Franca

**Comment by VIF-Franca** [comment]
https://docs.google.com/presentation/d/1dLgunzCsjplxoEOKBCM907gCnGtRQE34/edit#slide=id.p1 

Modelo gráfico do manual produzido pela equipe.

-> Já criei a pasta no drive

**Comment by VIF-Franca** [comment]
@elisribas o OBS permite a gravação de tele e outras funções, tu acha que devemos explicar isso no manual? Por ser um manual creio que seja válido a explicação. 

@elisribas eu e o @lucasgalize levaremos um tempo adicional pois precisaremos se aprofundar e aprender a utilizar o software da melhor forma.

**Comment by elisribas** [comment]
Sim, será importante criar um manual completo.
Podemos considerar também a transmissão a partir do Webex. 
Vamos ver o prazo em nossa próxima reunião geral.
O @MaNegrao poderá auxiliar com dicas e orientações a vocês para a produção do material.

**Comment by MaNegrao** [comment]
Estou a disposição para auxiliar, caso necessario

**Comment by elisribas** [comment]
@lucasgalize  Conseguimos conclui-la para a próxima semana?

**Comment by MaNegrao** [comment]
@elisribas Será que é possivel trocar o google meet pelo Webex no manual? Dado as experiencias que obtivemos utilizando ambas?

**Comment by lucasgalize** [comment]
Foi finalizado a cartilha #69. Agora esperando revisão para ajustes.

**Comment by elisribas** [comment]
> @elisribas Será que é possivel trocar o google meet pelo Webex no manual? Dado as experiencias que obtivemos utilizando ambas?

Sim, combinamos que seriam explicados os dois recursos. Olhei a cartilha e agora penso que falta apenas adicionar a questão da transmissão pelo Webex.

**Comment by MaNegrao** [comment]
Eu vou assumir essa issue, considerando que evoluímos muito na utilização do OBS teremos muito a reformular no manual

**Comment by alessandrapedrotti** [comment]
> Eu vou assumir essa issue, considerando que evoluímos muito na utilização do OBS teremos muito a reformular no manual

Neste contexto, você pode analisar a necessidade da existência da tarefa #81? Ela me parece um pouco desnecessária.

**Comment by MaNegrao** [comment]
> > Eu vou assumir essa issue, considerando que evoluímos muito na utilização do OBS teremos muito a reformular no manual
> 
> Neste contexto, você pode analisar a necessidade da existência da tarefa #81? Ela me parece um pouco desnecessária.

Eu penso que as funcionalidades do OBS são exatamente as mesmas pra transmissão e para gravação, o que muda é o botão de iniciar, só vamos ter que criar uma secção de gravação pra mostrar como colocar câmera etc.

**Comment by alessandrapedrotti** [comment]
> > > Eu vou assumir essa issue, considerando que evoluímos muito na utilização do OBS teremos muito a reformular no manual
> > 
> > 
> > Neste contexto, você pode analisar a necessidade da existência da tarefa #81? Ela me parece um pouco desnecessária.
> 
> Eu penso que as funcionalidades do OBS são exatamente as mesmas pra transmissão e para gravação, o que muda é o botão de iniciar, só vamos ter que criar uma secção de gravação pra mostrar como colocar câmera etc.

Sendo assim, fecharei a issue #81.

**Comment by MaNegrao** [comment]
Como o manual vai ser praticamente todo refeito, acho que a gente pode encerrar essa issue aqui e abrir uma nova com descrições e fluxo de trabalho atualizados. pode ser @alessandrapedrotti ?

**Comment by alessandrapedrotti** [comment]
> Como o manual vai ser praticamente todo refeito, acho que a gente pode encerrar essa issue aqui e abrir uma nova com descrições e fluxo de trabalho atualizados. pode ser @alessandrapedrotti ?

Sim, pode fechar a issue e abrir uma nova.
Só gostaria de salientar que se qualquer trecho do texto já produzido pelo redator desse manual for utilizado, o nome dele deve constar nos créditos finais como redator também.
