### ISSUE TITLE
[Site] Atualizar página de pessoas

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/programa#7]
Deve-se seguir o estilo da [https://cc.uffs.edu.br/pessoas](https://cc.uffs.edu.br/pessoas). Basta copiar a página de pessoas do repositório do site do curso de Computação e utilizar ela tal e qual, apenas trocando as informações de cada pessoa para refletir os integrantes do projeto.

No site de Computação, existem apenas dois grupos (Professores e Taes). Para o site do PRACTICE, existirá um grupo para cada uma das equipes, incluindo a Coordenação Geral (Fernando, Maurício) e Coordenação Técnico Pedagógica (Caimi e Elis).

**Comment by CleissonVieira** [comment]
@Dovyski  @andrewmsilva 
O Nedilso se encaixa em qual equipe?

Outra dúvida que tenho é se faço equipe mais generalizadas conforme **caixas vermelhas** na imagem abaixo, ou conforme **caixas azuis**?
![image](https://user-images.githubusercontent.com/29258164/86505236-8b6bd500-bd98-11ea-85c2-b52cb97f636a.png)

Atualmente está assim:
![image](https://user-images.githubusercontent.com/29258164/86505269-c968f900-bd98-11ea-85d3-95493670b724.png)
![image](https://user-images.githubusercontent.com/29258164/86505271-d4238e00-bd98-11ea-8d70-1d4e22b95a92.png)
![image](https://user-images.githubusercontent.com/29258164/86505276-dbe33280-bd98-11ea-8e4d-a30a08e30e51.png)

Outra questão é se peço o Currículo lattes de todos os integrantes do projeto para deixar o botão do currículo funcional, ou retiro o botão dos integrantes que não devem ter?

**Comment by CleissonVieira** [comment]
Issue resolvida em [Atualizar página de pessoas #2](https://github.com/practice-uffs/website-programa/issues/2)
