### ISSUE TITLE
Notícia sobre o lançamento do programa Practice na página do programa

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/programa#71]
Inserir notícia com lançamento do programa. Inserir o QR code e o link para youtube na notícia.

**Comment by andrewmsilva** [comment]
A notícia foi criada e está disponível no [ambiente de desenvolvimento](https://ci.uffs.cc/practice-website-programa/dev/0143207efd3456fa9fa60241ecddabc92903bd38/noticias/live-de-lancamento-do-practice/). Se forem revisar o conteúdo da notícia, favor utilizar este link e comentar nesta issue as mudanças, pois a notícia ainda não foi publicada oficialmente. Assim que estiver tudo revisado e todas as alterações feitas, a publicação oficial será feita.
