### ISSUE TITLE
Descrição simplificada dos serviços de conteúdo

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#72]
Criar um documento semelhante a [esse](https://docs.google.com/document/d/1uuU5YbcKqEp1kDLo3LjIEQVl5QHnhQTcup0sMVOFyNU/edit#heading=h.uhot9691i99i) (feito na #44 pela con-midia) para que possamos colocar as informações dos servícos de conteútos no site. No documento vocês não precisam necessariamente colocar os ícones/ilustrações que o pessoal da con-midia usou no doc deles, mas seria interessante se pudessem.

Responsável: @practice-uffs/con-material 

cc: @practice-uffs/dev-web fiquem atentos a essa issue para atualizar o site conforme o documento fique pronto. Colocar isso na página `servicos/midia`, em uma seção própria.

**Comment by alessandrapedrotti** [comment]
Texto elaborado.  Está na pasta programa#72 nas tarefas no google drive.

**Comment by CleissonVieira** [comment]
Pagina concluída com o conteúdo desse [documento](https://docs.google.com/document/d/1bwAiI75uLVHmSIX6oo922fLuK3kh4_2mKg4ms1Cjwic/edit) atualizado até o presente momento (29/07/2020 00:07h)

**Comment by Dovyski** [comment]
Para o momento inicial, eu considero esse doc pronto e suficiente, por isso vou fechar a tarefa. Se no futuro a coordenação da con-material decidir fazer algo mais elaborado, criamos issues novas.
