### ISSUE TITLE
Alteração no formulário de solicitação de transmissões ao vivo

### ISSUE THREAD

**Issue by MilenaPaz2020** [practice-uffs/programa#722]
O objetivo dessa issue é incluir a solicitação de confecção das capas de live dentro do [formulário de solicitação de transmissões](https://docs.google.com/forms/d/1mieqNA7b_cG4EQCTcfODlH0kZSEt_xmpuUfN71tGfU0/edit) ao vivo, haja vista as confusões geradas anteriormente.

Aproveitando esse momento de aterações, será incluído, ainda, uma opção onde o cliente poderá escolher se deseja divulgar a live nos stories do Instagram do PRACTICE.

**Comment by MilenaPaz2020** [comment]
Alteração feita. Peço, que a @morgana-mo e @TaynaraCh façam uma revisão desse formulário, verificando se a solcitação de capa está adequada (apenas transferi as perguntas do outro formulário) e se a solicitação de divulgação é pertinente.

Peço, ainda, que a equipe @practice-uffs/con-midia verifique essas alterações e, se acharem por bem, façam as adequações necessárias.

**Comment by luizatonial** [comment]
Fiz umas poucas alterações pra ordem ficar certinha e etc

**Comment by morgana-mo** [comment]
Acredito que esteja bem redondinho, @TaynaraCh achou falta de alguma coisa?

**Comment by MilenaPaz2020** [comment]
Percebemos a necessidade de adicionar uma sessão onde o cliente pode anexar a descrição que ele quer que esteja no Youtube ou Facebook. Adicionei esse sessão, contudo, somente quando a transmissão for feita nos nossos canais.

**Comment by TaynaraCh** [comment]
Oi gente, só consegui ver isso agora, sorry!

Eu fiz algumas alterações, atualizei a capa exemplo e adicionei uma pergunta pra que o solicitante envie logotipos, símbolos ou até a imagem de fundo que quiser. Como nunca atendi de fato uma solicitação de capa de live, acho que seria bom a Morgana conferir se está tudo ok kkkk

**Comment by TaynaraCh** [comment]
Agora pensei que talvez possa ser colocado como anexo, não sei dizer como fica melhor...

**Comment by luizatonial** [comment]
Dei mais uma revisadinha e acredito que (da parte das lives) esteja adequado. 
Sobre a questão levantada pela @TaynaraCh sobre as logos/imagens, acredito que seria mais interessante como está mesmo, separado, de modo que o solicitante entenda que naquele momento as informações estejam ligadas com a capa e, posteriormente, com a transmissão e suas especificidades.

**Comment by MilenaPaz2020** [comment]
Considero adequada as alterações estejam adequadas. Vou deixar a @morgana-mo dar mais uma olhada nas alterações feitas pela Tay, com o aval dela poderemos fechar a issue.

**Comment by morgana-mo** [comment]
Está tudo ok ao meu ver!

**Comment by MilenaPaz2020** [comment]
Maravilha! Encerramos, por enquanto, a atualização do formulário. Obrigada pela colaboração, pessoal!
