### ISSUE TITLE
Baixar, editar e repostar a live de lançamento do Practice no canal do Youtube

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/programa#73]
Precisamos de alguns ajustes na live antes de repostar:
- antes de tudo assistir toda a live e anotar os "problemas";
- remover o eco do inicio da live (talvez tenha em outros momentos);
- ajustar transições entre as falas;
- ajustar, quando necessário, o nome da pessoa que está falando. Sugiro sobrepor em uma nova camada;
- gerar a legenda da live.

[Pasta do Drive](https://drive.google.com/drive/u/0/folders/1tIJqQkMvrqld-B0n7kR8HYh8XRqgzlNd)

**Comment by lcaimi** [comment]
Acho que pode ser colocado os créditos no final com o nome de todos os participantes, inclusive das interpretes de libras.

**Comment by vini2reis** [comment]
[Pasta do Drive](https://drive.google.com/drive/u/0/folders/1tIJqQkMvrqld-B0n7kR8HYh8XRqgzlNd)

**Comment by vini2reis** [comment]
O eco não consegui remover, tentei varias formas e não cosegui. Também pedi ajuda para o @MaNegrao e ele também não conseguiu remover. Creio que algum mic ficou ligado no momento da live e acabou gerando esse eco.

**Comment by vini2reis** [comment]
O vídeo editado já está na pasta do Drive

**Comment by MaNegrao** [comment]
@lcaimi o video está editado já faz um tempo, iremos publicá-lo no youtube ou essa issue já pode ser encerrada?

**Comment by lcaimi** [comment]
Vamos aguardar os novos bolsistas e ver se alguém conhece algum filtro ou programa para tentar tirar o eco presente.

**Comment by MaNegrao** [comment]
@robisonjose Nós temos um problema com essa live que o áudio ficou duplicado por uns 15 minutos, só que ninguém da equipe inicial conseguiu solucionar, Se tu puder dar uma olhada na live editada que está na pasta e ver se tem algo que possa ser feito em relação ao áudio.

**Comment by robisonjose** [comment]
Vou dar uma olhada, mas geralmente quando o áudio está duplicado em uma única faixa fica bem complicado de resolver.

**Comment by MaNegrao** [comment]
Sim, exatamente, esse é o problema, eu tentei solucionar com a edição de áudio e remoção de ruído, mas não tive tanto sucesso. só deu uma abafada

**Comment by robisonjose** [comment]
Postei o áudio editado [aqui](https://drive.google.com/drive/u/0/folders/1tIJqQkMvrqld-B0n7kR8HYh8XRqgzlNd) com o nome de "audio_live_v2". Tentei dar uma trabalhada no áudio mas o retorno é quase impossível de retirar, tentei ir retirando a mão tudo que deu. Também fiz umas mudanças de volume, tinha momentos em que a fala de alguém estourava, e em outros que a fala ficava baixa. Dei uma revisada nisso. No momento em que o vídeo do PRACTICE passava ele estava com o áudio muito mais alto que aquele que estava anteriormente, então deixei os dois mais ou menos na mesma altura. No fim do áudio alguma pessoa faz um comentário já fora da live, cortei isso. Também dei uma olhada no "audio_editado_Audacity", ele ficou com o som bem comprimido e baixo, creio que por conta dos filtros utilizados, então tem momentos em que os professores falam que quase não dá para escutar, além de que a voz ficou bem "não natural". 

*Obs: Fiz as edições de forma que não se alterassem a duração do arquivo e a posição das falas, portanto, acredito que o áudio esteja pronto para ser colocado no vídeo. Todavia, acho interessante revisar se não ocorreu nenhuma dessincronização.

**Comment by MaNegrao** [comment]
@lcaimi Da uma olhada no áudio editado pelo Robison, acho que é o máximo que podemos chegar
