### ISSUE TITLE
Coleta de informações para treinar a AURA

### ISSUE THREAD

**Issue by Eweline** [practice-uffs/programa#753]
Essa issue tem o intuito de coletar informações (dúvidas da comunidade acadêmica) para treinar a AURA.
Inicialmente será preparado um documento para enviar à comunidade acadêmica, e a partir dessas dúvidas serão produzidas as respostas que a AURA dará.

**Comment by isabelirk** [comment]
Bom dia @Eweline, fiz uma leitura do material e deixei algumas sugestões de coisas que poderiam ser adicionadas para a Aura.
Atenciosamente.

**Comment by Dovyski** [comment]
Para conhecimento da @practice-uffs/con-conteudo , a @Eweline ficará como responsável pelo gerenciamento de todos os treinamentos da Aura (incluindo o trabalho de outras equipes relacionadas a essa tarefa).

@Eweline eu gostaria de marcar um treinamento contigo sobre como adicionar materiais na Aura. O objetivo é você ter esse conhecimento para poder coordenar as outras pessoas que farão esse trabalho junto contigo. O tempo previsto de treinamento é uns 30 a 40 min. Pode falar comigo no Telegram para vermos um dia e horário.
