### ISSUE TITLE
Live -  Seminário Evasão nos cursos de graduação da UFFS (01/09 - 13h30)

### ISSUE THREAD

**Issue by MilenaPaz2020** [practice-uffs/programa#754]
<h1 align="center" >Informações Transmissão Ao Vivo</h1>

**Titulo**: Seminário Evasão nos cursos de graduação da UFFS

**Data e Hora**: 01/09 - 13h30

**Solicitante**: Noemia Salete Wismann

**Realizador(es)**:

**Palestrante Principal**:

**Solicitação no Mural**: https://mural.practice.uffs.cc/servico/1219

**Link Transmissão**: _Deve ser criado._

Com os dados e roteiro em mãos, o responsável pela Live deve seguir os padrões do PRACTICE e estabelecer contato com o solicitante, enviando inicialmente o Protocolo de Execução de Lives.

**[Planilha de Lives](https://drive.google.com/drive/folders/16h-YVwTnRF49eqBYBRONKyLqPbisCIbH)**

**[Protocolo de Execução de Lives](https://drive.google.com/file/d/1KQ9vI1gKECqWHi4xwb3LrnuWCgKEHWyd/view?usp=sharing)**

**[Padronização de Lives](https://drive.google.com/file/d/1Bky3nLRTAoCejzHrH0D93GQ_gjsa4Hxl/view?usp=sharing)**

**[TeleCurso 2000](https://drive.google.com/drive/folders/1r_Gea2VxB3J-4VfIXr9jqXa2NgStNvCs?usp=sharing)**

CC: @con-midia / lives

**Comment by morgana-mo** [comment]
> @morgana-mo, foi solicitado a divulgação da live em nossas redes. A solicitante encaminhou um card, creio que poderá ser utilizado.

Para fins de registro na hoje 30/08 realizei uma postagem nos stories na conta do programa do Instagram e do Facebook  com a divulgação do evento e na quarta no horário da live farei mais uma chamada!

**Comment by MilenaPaz2020** [comment]
Adicionei, no protocolo cerimonial, o nome das pessoas que estarão auxiliando no andamento do evento. Devem estar nos créditos da live.

**Comment by pedroamaximowski** [comment]
Live finalizada com sucesso!
