### ISSUE TITLE
Reunião - Dúvidas live (30/08 - 14h)

### ISSUE THREAD

**Issue by MilenaPaz2020** [practice-uffs/programa#755]
Em virtude do grande número de participantes da Live Seminário Evasão nos cursos de graduação da UFFS (01/09 - 13h30) (#754) e o fato da maioria dos palestrantes estarem se ambientando à esse tipo de evento, a solicitante pediu uma reunião rápida para tirar dúvidas (no máximo 20 minutos). 

Link da reunião: meet.google.com/yai-jxdn-yhw

**Comment by luizatonial** [comment]
só avisando que tem uma mensagem no whatsapp do practice da solicitante pedindo para alterar a data e o horário da reunião... abri sem querer mas não respondi

**Comment by MilenaPaz2020** [comment]
> só avisando que tem uma mensagem no whatsapp do practice da solicitante pedindo para alterar a data e o horário da reunião... abri sem querer mas não respondi

Sim, a solicitante pediu alteração da sala de reunião e horário, por conta dos demais participantes. O LINK CORRETO DA REUNIÃO É ESSE AQUI: https://uffs.webex.com/meet/prograd

**Comment by MilenaPaz2020** [comment]
Reunião finalizada com sucesso!
Dúvidas sanadas e solicitantes mais seguros em relação ao evento. O PRACTICE foi altamente elogiado!
A solicitante irá encaminhar um novo protocolo cerimonial, pois algumas pessoas serão acrescentadas. Assim que ela encaminhar eu anexo na pasta de entrada da issue #754.
