### ISSUE TITLE
Criar modelo de créditos para adicionar no final de vídeos 

### ISSUE THREAD

**Issue by elisribas** [practice-uffs/programa#76]
@estelavilasboas Cria um modelo de créditos a ser utilizado em todos os vídeos produzidos pelo Practice.

**Comment by estelavilasboas** [comment]
[Imagem base](https://drive.google.com/drive/folders/1a7umddYh64OPEb8dNqBkltVpUHxLT1AS) já criada. Estou montando exemplos para facilitar a montagem dos créditos.

**Comment by elisribas** [comment]
@VIF-Franca acompanha o produto que está sendo produzido.

**Comment by estelavilasboas** [comment]
A imagem base está em uma resolução grande, pois não sabia exatamente o tamanho necessário para os vídeos. 
Os exemplos estão concluídos. 
A [pasta ](https://drive.google.com/drive/folders/1a7umddYh64OPEb8dNqBkltVpUHxLT1AS)também possui a imagem separada do "sublinhado/destaque" inserida nos exemplos.
O arquivo "Créditos.xcf" é o projeto editável do GIMP.

**Comment by elisribas** [comment]
Material entregue pela @estelavilasboas
