### ISSUE TITLE
Criar vinheta animada do programa para colocar no começo de cada vídeo

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#77]
Quando fizermos qualquer vídeo, ele terá conteúdo diverso, mas as pessoas precisam saber que foi feito por nós. Dessa forma, é importante termos uma  "abertura" oficial do programa.

A abertura do Xbox é o que me vem a mente:

https://www.youtube.com/watch?v=xy_XBeDdooA&list=PLZEa3DXlNcoq6iWfpvLstnLc9jPOh-lp7&index=19

Algo simples, rápido, de no máximo 4 segundos é o suficiente. Não precisamos de coisas em 3D ou afins, mas algo como o ícone do PRACTICE (o "P") seguido do logo completo com uma transição/transformação entre eles é o ideal.

**Comment by Dovyski** [comment]
Essa tarefa precisa ser terminada até o fim dessa sprint (15/09). Se isso não acontecer, utilizaremos a vinheta já existente.

**Comment by estelavilasboas** [comment]
A [pasta](https://drive.google.com/drive/folders/1-y1azb4MjGHuqz9d2jiv8Jb6xdci_JLE) contém três versões, sendo duas delas com som e uma sem.
A música foi criada pelo meu amigo músico, @andrewmsilva .

**Comment by Dovyski** [comment]
Eu achei o máximo a vinheta e a música! ❤️🥳❤️ Parabéns para vocês dois! Minha única sugestão é que o texto além de "PRACTICE" apareça um segundo depois que a palavra "PRACTICE" aparecer. Da forma atual, eles aparem todos juntos (logo completo do programa, nome do programa, informações extra).

Acho que as infos extras podem aparecer um pouquinho depois, só para não chamar a atenção.

**Comment by estelavilasboas** [comment]
> Eu achei o máximo a vinheta e a música! ❤️🥳❤️ Parabéns para vocês dois! Minha única sugestão é que o texto além de "PRACTICE" apareça um segundo depois que a palavra "PRACTICE" aparecer. Da forma atual, eles aparem todos juntos (logo completo do programa, nome do programa, informações extra).
> 
> Acho que as infos extras podem aparecer um pouquinho depois, só para não chamar a atenção.

Feito : )

**Comment by Dovyski** [comment]
Linda! \o/ Por favor, fazer o seguinte para fechar essa tarefa:

* [ ] Colocar os arquivos na pasta `saída` da [programa#77](https://drive.google.com/drive/folders/1-y1azb4MjGHuqz9d2jiv8Jb6xdci_JLE)
* [ ] Colocar os arquivos na pasta [Identidade Visual/Vinhetas](https://drive.google.com/drive/u/0/folders/1FFTk2H4YLBYcyNhBaZ1NikGyIRYdy_RO)

@practice-uffs/con-midia e @practice-uffs/con-conteudo agora temos uma vinheta oficial do programa. Por favor, utilizar ela em todos os trabalhos de agora em diante.

**Comment by phdmauricio** [comment]
Fantástica, parabéns, estou assistindo em loop faz meia hora.
