### ISSUE TITLE
Live - Contribuição da arte e cultura para a promoção da saúde mental e emocional. (28/09 - 19h às 21h30)

### ISSUE THREAD

**Issue by MilenaPaz2020** [practice-uffs/programa#770]
<h1 align="center" >Informações Transmissão Ao Vivo</h1>

**Titulo**: "Contribuição da arte e cultura para a promoção da saúde mental e emocional".

**Data e Hora**: 28/09 - 19h às 21h30

**Evento Geral** (se houver):

**Solicitante**: Cassio Silva Matos

**Realizador(es)**:

**Palestrante Principal**:

**Solicitação no Mural**: https://mural.practice.uffs.cc/servico/1371

**Link Transmissão**:https://youtu.be/TpLm3tLYBWw

Com os dados e roteiro em mãos, o responsável pela Live deve seguir os padrões do PRACTICE e estabelecer contato com o solicitante, enviando inicialmente o Protocolo de Execução de Lives.

**[Planilha de Lives](https://drive.google.com/drive/folders/16h-YVwTnRF49eqBYBRONKyLqPbisCIbH)**

**[Protocolo de Execução de Lives](https://drive.google.com/file/d/1KQ9vI1gKECqWHi4xwb3LrnuWCgKEHWyd/view?usp=sharing)**

**[Padronização de Lives](https://drive.google.com/file/d/1CldqvcbHPleVFd-ZKcigHhSua0VdR0mi/view?usp=sharing)**

**[TeleCurso 2000](https://drive.google.com/drive/folders/1r_Gea2VxB3J-4VfIXr9jqXa2NgStNvCs?usp=sharing)**

CC: @con-midia / lives

**Comment by MilenaPaz2020** [comment]
Issue aberta para fins de organização. O formulário já foi encaminhado ao solicitante. Por gentileza, @MariaLuizaReviliau adicionar os documentos na pasta da issue assim que o preenchimento for efetuado. Atentar-se com as opções da capa e divulgação.

**Comment by MariaLuizaReviliau** [comment]
Documentos adicionados na pasta de entrada!
Desejam a criação da capa do evento e post para divulgação nas redes sociais @practice-uffs/con-design @TaynaraCh. 
Desejam a divulgação do evento nas redes sociais do Practice @morgana-mo

**Comment by MariaLuizaReviliau** [comment]
@MilenaPaz2020 não foi criada automaticamente a pasta de entrada, onde adiciono os documentos?

**Comment by morgana-mo** [comment]
Oi @MariaLuizaReviliau  coloquei a divulgação na agenda da comunicação!
Sobre as pastas, eu acho que o bot deu uma falhada, daí se criam as pastas na mão!
Eu conferi e criei elas pra ti, no meu próximo comentário vou colocar elas pra ti

**Comment by morgana-mo** [comment]
[Pasta da Issue](https://drive.google.com/drive/folders/1mXMwoAHCyC2XHB123Nac16sR_ie4KPty)
[Entrada](https://drive.google.com/drive/folders/19LpBorA1981Kr1s-Z33P9H6hyFKlAE8d)
[Saída](https://drive.google.com/drive/folders/11YZ37K_P-MaeR13_6QBR96oiaCy0s3FN)

**Comment by MariaLuizaReviliau** [comment]
Obrigada @morgana-mo : )

**Comment by MariaLuizaReviliau** [comment]
Transmissão criada no youtube! Link https://youtu.be/TpLm3tLYBWw

**Comment by MilenaPaz2020** [comment]
O solicitante fez alteração no título do evento. Deve ser alterado no Youtube.

**Comment by TaynaraCh** [comment]
Iremoas realizar a capa da live, porém a arte de divulgação nas redes sociais deve ser solicitada no mural. Gostaria de pedir que, se possível, vocês orientem os solicitantes a realizar um pedido separadamente, no mural, de outros materiais que não sejam a capa da live.

**Comment by TaynaraCh** [comment]
Ficarei responsável pela criação dessa capa

**Comment by TaynaraCh** [comment]
Enviei alguns modelos de capa para o solicitante, no aguardo pelo feedback. Informei também sobre a arte de divulgação, deve ser feita através de uma nova solicitação no mural.

**Comment by TaynaraCh** [comment]
A confecção da capa está sendo realizada no [figma](https://www.figma.com/file/5iyxr2oQMDyRxmAvxV81wN/CAPAS-DE-LIVE?node-id=326%3A2)

**Comment by TaynaraCh** [comment]
Solicitante fez modificações em uma das capas produzidas e adicionou em uma pasta, sendo assim, capa disponível no [link.](https://drive.google.com/drive/folders/11YZ37K_P-MaeR13_6QBR96oiaCy0s3FN)

**Comment by MariaLuizaReviliau** [comment]
capa adicionada ao youtube!

**Comment by morgana-mo** [comment]
@TaynaraCh  a solicitante abriu uma solicitação da a arte de divulgação?
Posso fazer a divulgação nos stories utilizando o material que está disponível no [Instagram do projeto ](https://www.instagram.com/joaninha_cultural/) proponente do evento, isso nos pouparia tempo e material humano, qualquer coisa podemos falar sobre isso na reunião de líderes amanhã!

**Comment by GessicaZanon** [comment]
Transmissão realizada e dados inseridos na planilha!
