### ISSUE TITLE
Live - V Instituto de Estudos Linguísticos (IEL): Conferência de encerramento (05/11 - 19h)

### ISSUE THREAD

**Issue by MilenaPaz2020** [practice-uffs/programa#789]
<h1 align="center" >Informações Transmissão Ao Vivo</h1>

**Titulo**: Conferência de encerramento: A indissociabilidade entre questões, teoria e método

**Data e Hora**: 05/11 - 19h às 21h

**Evento Geral** (se houver):  V Instituto de Estudos Linguísticos (IEL)

**Solicitante**: ALINE PEIXOTO GRAVINA

**Realizador(es)**: PPGEL

**Palestrante Principal**: Livia Oushiro
**Solicitação no Mural**: https://mural.practice.uffs.cc/servico/1460

**Link Transmissão**: https://youtu.be/6Tl5yTjjtx4
Com os dados e roteiro em mãos, o responsável pela Live deve seguir os padrões do PRACTICE e estabelecer contato com o solicitante, enviando inicialmente o Protocolo de Execução de Lives.

**[Planilha de Lives](https://drive.google.com/drive/folders/16h-YVwTnRF49eqBYBRONKyLqPbisCIbH)**

**[Protocolo de Execução de Lives](https://drive.google.com/file/d/1KQ9vI1gKECqWHi4xwb3LrnuWCgKEHWyd/view?usp=sharing)**

**[Padronização de Lives](https://drive.google.com/file/d/1CldqvcbHPleVFd-ZKcigHhSua0VdR0mi/view?usp=sharing)**

**[TeleCurso 2000](https://drive.google.com/drive/folders/1r_Gea2VxB3J-4VfIXr9jqXa2NgStNvCs?usp=sharing)**

CC: @con-midia / lives

**Comment by MilenaPaz2020** [comment]
Adicionar o link dessa transmissão na agenda google do programa.

**Comment by MilenaPaz2020** [comment]
Essa issue pode ser encerrada?

**Comment by MariaLuizaReviliau** [comment]
Sim, tinha esquecido. Desculpa.

**Comment by GessicaZanon** [comment]
Transmissão realizada e dados inseridos na planilha.
