### ISSUE TITLE
Apoio técnico nas oficinas Semana de Formação Docente II - Laranjeiras do Sul

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#79]
Demanda da Professora Letícia Cristina Barbosa e Professor Alexandre Manoel. 

Ideia inicial: promover uma oficina possibilitando a capacitação dos professores da UFFS em maximizar a utilização da plataforma de web conferência oficial Cisco Webex.

**Comment by VIF-Franca** [comment]
Reunião para acolher a demanda e afinar os detalhes marcada para amanhã (13/08) às 8:00 via Cisco Webex.

**Comment by VIF-Franca** [comment]
Informações sobre tal demanda: 

Realizar gravação, apoio técnico, edição de vídeo e upload no Youtube do campus. 

Seguintes datas e horário de cada evento:
18/08 - terça-feira às 09:00
20/08 - quinta-feiras às 19:00
21/08 - sexta-feira às 14:00


Demanda enviada pelo professor Coordenador Acadêmico  Thiago e Profª Letícia - Campus Laranjeiras do Sul/PR

**Comment by VIF-Franca** [comment]
- [ ] Gravar evento que acontecerá dia 18/08 com a Professora Letícia sobre a plataforma Padlet;

- [ ] Criar imagens para adicionar na edição do vídeo referente ao dia 18/08;

- [ ] Editar vídeo referente ao evento dia 18/08;

- [ ] Upload do vídeo ref 18/08 no drive;

______

- [ ] Gravar evento que acontecerá dia 20/08 com a Professora Letícia  e Professor Alexandre Manoel sobre a plataforma Webex;

- [ ] Criar imagens para adicionar na edição do vídeo do dia 20/08;

- [ ] Editar vídeo referente ao evento dia 20/08;

- [ ] Upload do vídeo ref  20/08 no drive;

_______

- [ ] Gravar evento que acontecerá dia 21/08 com o Professor Bruno sobre a plataforma Moodle PARTE II;

- [ ] Criar imagens para adicionar na edição do vídeo referente ao dia 21/08;

- [ ] Editar vídeo referente ao evento dia 21/08;

- [ ] Upload do vídeo ref 21/08 no drive.


_______

**Comment by VIF-Franca** [comment]
@lcaimi  a edição referente a gravação do dia 18/08 está disponível em : 

https://drive.google.com/drive/u/0/folders/1egysme9klbWjiXu08oF0VCvunLyhUFpd

Aguardo seu feedback para enviar ao cliente.

**Comment by lcaimi** [comment]
@VIF-Franca Ficou excelente!

Pode liberar para o cliente.

**Comment by VIF-Franca** [comment]
Show @lcaimi irei postar no canal do campus. 

Tarefa segue aberta pois ainda temos mais dois dias do evento. Vou postando aqui as demais atividades.

**Comment by VIF-Franca** [comment]
Link do vídeo disponível no canal do Youtube do Campus Laranjeiras do Sul: 

https://youtu.be/miPJ_cFzg2I

**Comment by VIF-Franca** [comment]
Vídeo editado referente a oficina do Moodle Parte 2, ministrado pelo professor Bruno Oliveira.

Link do drive, [clique aqui](https://drive.google.com/file/d/1IKVSkNTZiCCG6RdTKpc-45yomA16iT8S/view?usp=sharing). 


@lcaimi , aguardo sua aprovação para disponibilizar no canal do YouTube do Campus laranjeiras.

**Comment by lcaimi** [comment]
Está Ok para liberar ao cliente.

Uma sugestão para a tela com o nome dos  apresentadores (próximas ocorrências)

Colocar a sigla da Instituição entre parênteses após o nome da pessoa.

Ao colocar o nome da UFFS nesta tela deixar somente o nome por extenso ou primeiro a sigla e depois o mome por extenso

![image](https://user-images.githubusercontent.com/12415747/91097260-bdc9de00-e635-11ea-8069-4fe2f76f0abc.png)

**Comment by VIF-Franca** [comment]
Show Prof Caimi

Vídeos postados.

**Comment by VIF-Franca** [comment]
Link para acessar os eventos, sendo eles os seguintes:
`Oficina: Moodle (Parte 2) -- LINK: `
