### ISSUE TITLE
[Vídeo de lançamento] Criar uma animação que explique o PRACTICE

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/programa#8]
É necessário a criação de um vídeo/animação que explique o que é o PRACTICE, quais são seus objetivos, quais pessoas  o compõe e como ele funciona. Assim que mais detalhes surgirem, esta issue será devidamente editada ou comentada.

**Comment by MaNegrao** [comment]
Como essa tarefa foi realizada pelos novos bolsistas, nós do @practice-uffs/con-midia vamos escolher um deles para ser publicado
