### ISSUE TITLE
Criar manual sobre como produzir boas apresentações de slides

### ISSUE THREAD

**Issue by elisribas** [practice-uffs/programa#80]
@mariagelain 
@estelavilasboas 

Criar uma tutorial sobre como criar boas apresentações de slides, usando o Google Apresentações.  

Ver modelos inovadores na internet e criar a partir disso.

**Comment by mariagelain** [comment]
Primeira versão do texto pronta. Peço para que a @elisribas de uma olhada e de sugestões a respeito do texto e que a @alessandrapedrotti faça a revisão textual.

**Comment by mariagelain** [comment]
A cartilha está pronta. Aguardo a revisão técnica para poder dar essa tarefa como finalizada ou não.

**Comment by alessandrapedrotti** [comment]
O conteúdo da cartilha está muito bom, só é preciso adicionar os nomes dos novos integrantes na lista da página de créditos ou colocar o link para a página de equipe do site.

Depois disso, podemos converter o material em PDF e indicar para o dev por no site.

**Comment by Dovyski** [comment]
Eu achei a cartilha maravilhosa, parabéns aos envolvidos! Minha única sugestão seria fazer um link na nota de rodapé sobre licenças para a nossa carilha de licenças de conteúdo. Acho que é um excelente material de apoio ao leitor.

De resto, está aprovada.

**Comment by MaNegrao** [comment]
@practice-uffs/con-midia podem ir dando uma olhada e estudando essa cartilha para adaptarmos para vídeo o conteúdo dela, é bem interessante para os profes e todos aqueles que forem fazer apresentações etc.

**Comment by alessandrapedrotti** [comment]
@mariagelain colocar uma versão em PDF na pasta de saída e na coletânea de materiais, depois disso, informar ao @practice-uffs/dev-web que a cartilha está pronta para ir ao site.

Vale também produzir um pequeno resumo para integrar o site, já que agora temos essa oportunidade.

Depois disso, a issue pode ser fechada.

**Comment by mariagelain** [comment]
@practice-uffs/dev-web a cartilha está concluída. 

Creio que para o resumo do material poderia ser o seguinte:

"Esta cartilha foi elaborada com o intuito de instruir sobre alguns pontos-chave para uma boa apresentação de slides, o objetivo deste material não é apresentar um manual de didática, muito menos ensinar a um professor como fazer seu trabalho"

**Comment by CleissonVieira** [comment]
@mariagelain Cartilha adicionada ao site com o respectivo resumo citado acima.
Issue pode ser fechada. 

Em aproximadamente 1 hora será publicada ao site.
