### ISSUE TITLE
Criar manual sobre uso do OBS para gravação de vídeos

### ISSUE THREAD

**Issue by elisribas** [practice-uffs/programa#81]
@lucasgalize criar um manual específico sobre produção de vídeos com uso do OBS.

**Comment by lucasgalize** [comment]
Ok.

**Comment by lucasgalize** [comment]
Terminamos a cartilha. Esperando revisão agora.

**Comment by lucasgalize** [comment]
Professor @Dovyski peço desculpas, fiz equívoco. Eu comentei na tarefa errada. Eu terminei a cartilha #69. Essa cartilha ainda está em andamento.

**Comment by elisribas** [comment]
@lucasgalize @MaNegrao 

A cartilha produzida na #69 trata do uso do OBS para transmissões de vídeos no YouTube. Não é explicado como se faz para que seja gravado um vídeo a partir do próprio software e depois que esse vídeo seja exportado, por exemplo. 
A ideia dessa nova cartilha é a de apresentar apenas a funcionalidade do OBS para gravação de vídeos. Ok?
Assim ficaria uma produção mais objetiva.

**Comment by lucasgalize** [comment]
Sim, vou fazer essa ainda, a cartilha desta issue.

**Comment by lucasgalize** [comment]
Boa Tarde, criei o documento já da cartilha para gravação no OBS, e estou trabalhando em cima dela ja.

**Comment by alessandrapedrotti** [comment]
Vide comentários na issue #69.
