### ISSUE TITLE
Aprender a manuser softwares de animação

### ISSUE THREAD

**Issue by elisribas** [practice-uffs/programa#82]
@estelavilasboas 
@lucasgalize 
@mariagelain 
@alessandrapedrotti 

Vamos aprender a manusear softwares de animação, opensource, preferencialmente, para começarmos a apresentar nossos conteúdos de forma interativa.

Vamos listar abaixo os softwares que podem ser explorados.

https://www.powtoon.com/index/ - Precisamos ver se continua aberto.

**Comment by Dovyski** [comment]
Eu usei o [Wick](https://www.wickeditor.com/#/) recentemente. Ele é 100% online, relativamente simples de trabalhar, e é open-source. Inclusive a equipe de dev pode criar uma versão em portugues dele no futuro e disponibilizar como ferramenta do próprio programa, se for interessante.

**Comment by elisribas** [comment]
Ótimo, @Dovyski. Obrigada! 

Então vamos tomar como ponto de partida a exploração dessa ferramenta @mariagelain @estelavilasboas @alessandrapedrotti @lucasgalize e esquecer o PowToon, ao menos por enquanto.

**Comment by vini2reis** [comment]
@MaNegrao vamos aprender esses softwares também

**Comment by lucasgalize** [comment]
Ok.

**Comment by elisribas** [comment]
> Eu usei o [Wick](https://www.wickeditor.com/#/) recentemente. Ele é 100% online, relativamente simples de trabalhar, e é open-source. Inclusive a equipe de dev pode criar uma versão em portugues dele no futuro e disponibilizar como ferramenta do próprio programa, se for interessante.

@isabelirk esse é o software que te comentei. Essa demanda está contigo a partir de hoje.

**Comment by Dovyski** [comment]
Eu comencei com a gerência de fazer uma capacitação sobre esse software. Vou deixar isso registrado para não perdermos a ideia.

**Comment by isabelirk** [comment]
Achei alguns comandos que podem ser úteis: https://github.com/Wicklets/wick-editor-2018/blob/master/HOWTO.md

**Comment by elisribas** [comment]
@isabelirk esses dois sites poderão ajudar com importação de recursos para serem animados.
https://www.kenney.nl/assets
https://undraw.co/illustrations

**Comment by isabelirk** [comment]
Boa tarde

@Dovyski poderíamos marcar um horário para realizar a capacitação e tirar algumas duvidas?

Atenciosamente

**Comment by Dovyski** [comment]
Sim, @isabelirk. Desculpe que não consegui te atender antes. Eu acho que tu pode começar pelos seguinte vídeos:

- Básico: https://www.youtube.com/watch?v=pAsrXT8KIrI&list=PLsupk6IPoB4hHKTOyJRoMA6EDl3mE9nTB
- Animação simples: https://www.youtube.com/watch?v=fiTimi02PEg&list=PLsupk6IPoB4hHKTOyJRoMA6EDl3mE9nTB&index=10

**Comment by Dovyski** [comment]
Essa tarefa está relacionada com https://github.com/practice-uffs/programa/issues/135.

**Comment by isabelirk** [comment]
Boa tarde @Dovyski,

Já assisti todos os vídeos que foram indicados logo acima. Será que podemos abrir um Doodle para acertar um horário?

**Comment by Dovyski** [comment]
Como essa é uma tarefa muito aberta, vamos fechar ela e focar em criação de animações independentes.

**Comment by elisribas** [comment]
@robisonjose analisa os conteúdos aqui compartilhados e veja se podem explorar a ferramenta [Wick](https://www.wickeditor.com/#).
