### ISSUE TITLE
Alteração formulário solicitação serviços @Con-Mídia

### ISSUE THREAD

**Issue by MilenaPaz2020** [practice-uffs/programa#822]
O objetivo dessa issue é alterar os formulários de [solicitação de edição de áudio e vídeo](https://docs.google.com/forms/d/1EojL35DBPjGUjZpqUH5QQ-Tyz8hF9Vn5Lij9JtdJ9ms/edit?usp=drive_web) e de [transmissões ao vivo](https://docs.google.com/forms/d/1mieqNA7b_cG4EQCTcfODlH0kZSEt_xmpuUfN71tGfU0/edit),
Deve-se criar, nos dois formulários, um campo onde o cliente aceita os [termos de direitos autorais](https://docs.google.com/document/d/1hdAegs3TdIvBAJMjrHGKLtSMW8avRXhcUtc-HQoD81o/edit) e onde confirma estar encaminhando todos os materias pertinentes à solicitação (roteiro, material a ser editado, protocolo...).

- [ ] Criar texto para seção de direitos autorais;
- [ ] Criar texto para seção de confirmação de envio dos materiais;
- [ ] Revisar textos;
- [ ] Alterar formulário solicitação de edição áudio e vídeo;
- [ ] Alterar formulário solicitação de transmissões
- [ ] Revisar formulários;

@practice-uffs/con-midia

**Comment by amandasegattob** [comment]
Oi @MilenaPaz2020, o link de "termos de direitos autorais" está pedindo permissão de acesso. Você poderia liberar?

**Comment by MilenaPaz2020** [comment]
> Oi @MilenaPaz2020, o link de "termos de direitos autorais" está pedindo permissão de acesso. Você poderia liberar?

@amandasegattob, vamos esperar um pouco para essa tarefa. Tem alguns pontos que preciso verificar ainda.

**Comment by MilenaPaz2020** [comment]
Levando em consideração que o mural v2 já possui uma checkbox informando sobre os termos de direitos autorais, não faz mais sentido manter essa issue aberta. Encerrando para podermos trabalhar em outras questões.
