### ISSUE TITLE
Acrescentar dados nas planilhas

### ISSUE THREAD

**Issue by Claudineia-VR** [practice-uffs/programa#824]
Gente peço que acrescentem o CPF, matrícula e chave do pix na [planilha de membros e equipes](https://docs.google.com/spreadsheets/d/15kGGrER8UTGQhPIvGm2jHhs3pEO6f7gqISZgRyqpMKE/edit#gid=0).

@practice-uffs/todos

**Comment by robisonjose** [comment]
Atualizado. Espero que a chave do pix não seja em vão.

**Comment by luizdameda** [comment]
Atualizado ✅

**Comment by CleissonVieira** [comment]
Atualizado (esperando pix) xD

**Comment by GessicaZanon** [comment]
Feito!!

**Comment by Eweline** [comment]
@Claudineia-VR  feito
