### ISSUE TITLE
Principais órgãos da UFFS e suas funções

### ISSUE THREAD

**Issue by Vandipedrotti** [practice-uffs/programa#825]
Issue criada a pedido da @mariagelain para desenvolver minha cartilha sobre algum assunto interessante e útil relacionado à UFFS, como forma de treinamento na equipe de @practice-uffs/con-conteudo . Estou testando minhas habilidades aqui, hora de descobrir se aprendi a abrir uma issue rsrs

**Comment by Vandipedrotti** [comment]
Gostaria que dessem uma olhada no doc do drive para opinar se é um bom assunto, outros tópicos que posso adicionar lá ou se tem nada a ver o que estou fazendo @practice-uffs/con-conteudo

**Comment by Dovyski** [comment]
Não vou conseguir ficar sem comentar 😆 Eu achei o assunto *maravilhoso*! Não só é uma informação muito útil, como podemos utilizar o material para postagens no insta e, na sequência, no treinamento da Aura.

**Comment by Eweline** [comment]
Pensei a mesma coisa que o professor!

Viu @Vandipedrotti , acredito que pode colocar a label de equipe:con-conteúdo, pois é a nossa equipe quem está irresponsável pela tarefa. A @mariagelain  ou a @GessicaZanon  pode confirmar para mim?

**Comment by mariagelain** [comment]
Primeiro eu gostaria de parabenizar a @Vandipedrotti pelo assunto da cartilha e sim @Eweline a label correta é a de equipe:con-conteúdo

**Comment by MilenaPaz2020** [comment]
Cheguei pelo título curioso da issue! hehehe
Sensacional o assunto escolhido! :D

**Comment by Eweline** [comment]
Boa noite, @Vandipedrotti .
Primeiro, gostaria de parabenizar pela cartilha, está muito legal e bem escrita. E como eu já havia dito, acho de extrema importância esse assunto!

Deixei algumas contribuições no texto sobre algumas dúvidas que tenho quanto a regras de português, para serem pesquisadas e resolvidas.

Qualquer dúvida, só chamar!

**Comment by GessicaZanon** [comment]
Vandy, o modelo de cartilha simples está na issue #211 na pasta de saída e o modelo de cartilha moderada e complexa está na issue #340. Essas issues ainda não possuíam nosso bot maravilhoso, então verifique na descrição e nos comentários, alí consta o link das pastas.. Tua cartilha se encaixa no modelo de cartilha simples (pela quantidade de páginas). Acho que a diagramação ficará bem bacana.

Qualquer dúvida, fico a disposição :)

**Comment by Vandipedrotti** [comment]
Certo, irei começar a diagramação, obrigada Gessica sz

**Comment by GessicaZanon** [comment]
> Certo, irei começar a diagramação, obrigada Gessica sz

Esqueci de falar.. mas crie uma cópia do layout de cartilha que vai utilizar e a mova para a pasta dessa issue. Aí você fará a diagramação nessa cópia que fica dentro da pasta desta issue.

**Comment by Vandipedrotti** [comment]
Olá, finalizei a diagramação da Cartilha. Gostaria de pedir a revisão novamente da introdução e das considerações finais. Após essa revisão, estarei pedindo a revisão da diagramação. São poucos parágrafos, acho que no máximo 5, 10 mim está pronta a revisão. Agradeço quem puder revisar.

**Comment by Eweline** [comment]
Boa tarde @Vandipedrotti .
A revisão da introdução e conclusão já foi feita. Está tudo certo. Só coloquei uma sugestão que fica a seu critério.

Achei muito legal o _layout_ da cartilha. Se puder passar o _link_ de onde conseguiu ele, agradeço muito. Gostei que cada página ficou destinada a um órgão específico.

Novamente, parabéns pelo desenvolvimento da cartilha; é de fundamental importância para estudantes e outros interessados.

**Comment by Vandipedrotti** [comment]
Olá pessoal do @practice-uffs/con-design! Gostaria de pedir a ajuda de vocês para revisar minha diagramação da cartilha sobre os Órgãos da UFFS. Não se trata de algo urgente, mas desde já agradeço ^-^

**Comment by minieradka** [comment]
> Olá pessoal do @practice-uffs/con-design! Gostaria de pedir a ajuda de vocês para revisar minha diagramação da cartilha sobre os Órgãos da UFFS. Não se trata de algo urgente, mas desde já agradeço ^-^

Ótimo trabalho! Parabéns 
se achar necessário algumas ilustrações ficariam ótimas para complementar os espaços <3

**Comment by Vandipedrotti** [comment]
Olá pessoal! Gostaria de pedir uma ajudinha da galera do @practice-uffs/dev para postar meu bebê (a cartilha) agora que está toda pronta e revisada! Agradeço quem puder fazer isso. Assim que pronto desejo ter a maravilhosa sensação de fechar essa issue rsrsrs Beijinhos de Luz :*

**Comment by GuilhermeGraeff** [comment]
Bom dia @Vandipedrotti, seria postar nas [notícias](https://practice.uffs.edu.br/noticias/) do [site](https://practice.uffs.edu.br/) do PRACTICE né?  
Notícia que também, por estar no site, deve aparecer no app do PRACTICE.

Só tirando essa dúvida aqui hehe :)

**Comment by Vandipedrotti** [comment]
Olá, a  cartilha deve ser postada juntamente com os demais materiais de cartilhas. Segue uma pequena descrição para anexar junto: _"O PRACTICE elaborou essa cartilha no intuito de auxiliar os acadêmicos facilitando o acesso às informações relacionadas aos órgãos da UFFS e das funções que cada órgão desenvolve"_. Agradecida ^^

**Comment by alissonpeloso** [comment]
@Vandipedrotti, [Issue](https://github.com/practice-uffs/website-programa/issues/105) criada para o @practice-uffs/dev adicionar a cartilha no site :)

**Comment by alissonpeloso** [comment]
Cartilha adicionada ao site, assim que for atualizado o site que está rodando, ela aparecerá na aba de recursos

**Comment by morgana-mo** [comment]
Solicitei uma imagem de divulgação da cartilha na  #1070

**Comment by JuliaGaboardiB** [comment]
Será divulgada ainda essa semana. :)
