### ISSUE TITLE
Configuração PC's remotos para lives.

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#826]
Observada a demanda por establidade dos computadores remotos para fazer lives, foram solicitadas máquinas no datacenter da uffs. Essa atividade serve apenas para demarcar que esse trabalho de configuração está sendo feito.

**Comment by MilenaPaz2020** [comment]
Algum encaminhamento desta tarefa?

**Comment by MaNegrao** [comment]
Não consegui avançar em nada :(. No começo do mês enquanto eu tava em são paulo eu tentei algumas vezes entender e acessar as máquinas virtuais, mas não tive muito sucesso. 

Não sei até que ponto vale a pena insistirmos nessa solução ou tentar outra coisa agora que vai voltar a ter atividades presenciais regularmente na UFFS.

**Comment by luizatonial** [comment]
> > Não consegui avançar em nada :(. No começo do mês enquanto eu tava em são paulo eu tentei algumas vezes entender e acessar as máquinas virtuais, mas não tive muito sucesso.
> > Não sei até que ponto vale a pena insistirmos nessa solução ou tentar outra coisa agora que vai voltar a ter atividades presenciais regularmente na UFFS.
> 
> Sim, não sei se ainda teremos demanda de transmissões para termos que utilizar essa solução. @lcaimi, o que nos diz?

conversamos em reunião que como a demanda para transmissões está baixa e a tarefa é complicada iremos suspender seu andamento.

**Comment by MaNegrao** [comment]
Recentemente eu me empenhei mais um pouco nessa questão, mesmo que a principio tenhamos disistido de fazer as maquinas virtuais, e creio que aprendi a maneira correta de fazer corretamente as interfaces gráficas das máquinas virtuais usando o google remote desktop. Atualmente o meu problema para configurar essas máquinas no servidor da uffs está sendo acessar a rede VPN da universidade, que eu nunca consigo. Pensei em fazer diretamente nos pcs remotos, que estão dentro da universidade e por consequencia em sua rede (no momento estão todos desligados). 

Logo, acredito que podemos reabrir a issue e realizar essa última tentativa.

**Comment by MaNegrao** [comment]
O pc remoto foi configurado pelo Fernando e está online, então a issue pode ser fechada
