### ISSUE TITLE
Horários PRACTICE 2022

### ISSUE THREAD

**Issue by Claudineia-VR** [practice-uffs/programa#829]
O objetivo desta issue é elaborar a planilha com os horários de 2022 para auxiliar na organização do programa.

**Comment by Claudineia-VR** [comment]
Boa tarde pessoal, então como o período de rematrícula encerra hoje já vou da o recado. Preciso que todos (@practice-uffs/todos ) gerem o documento dos seus horários do semestre 2021/2 no portal do aluno e adicionem os mesmos na pasta [Horários 2021/2](https://drive.google.com/drive/folders/1jMshEqpODMRJTCQLE2fOKgZZAtzlK7v8) na pasta de entrada desta issue. Peço que nomeiem o documento com seus nomes completos.

**Comment by robisonjose** [comment]
Boa tarde. Eu vou esperar pra adicionar depois que eu fizer o ajuste de uma matéria.

**Comment by Claudineia-VR** [comment]
Acabei de finalizar as planilhas de horários, peço que se possível todos preencham com os seus horários pelo menos a semana do dia 15/11/2021 ao dia 20/11/2021 até segunda-feira, para fazermos um teste e ver se elas precisam de melhorias. Criei uma planilha por equipe e dentro delas vão encontrar abas com os nomes de cada integrante.

@practice-uffs/todos 

Sintam-se a vontade para sugerirem ideias de melhorias!!

**Comment by robisonjose** [comment]
> Boa tarde. Eu vou esperar pra adicionar depois que eu fizer o ajuste de uma matéria.

Adicionado.

**Comment by isabelirk** [comment]
Olá @Claudineia-VR eu não consigo acessar a pasta da issue para atualizar meus horários.

**Comment by luizdameda** [comment]
Boa tarde! Não adicionei ainda porque o campus Passo Fundo tem um calendário próprio. Aqui a gente começou o 2021/2 em agosto e já estamos praticamente no final dele (terminará dia 15/12), por conta disso acredito que não compensará eu colocar meu horário desse semestre na pasta. Estarei de férias da faculdade até dia 07/03, quando iniciará o 2022/1.

**Comment by Claudineia-VR** [comment]
@isabelirk adicionei seu email!

@luizdameda peço que adicione este e assim que iniciar o próximo você coloca o horário posterior!

@MilenaPaz2020 eu havia esquecido deste detalhe que por eu não ter aula a noite havia colocado os horários diferentes, vou providenciar essa mudança, obrigada!

**Comment by luizdameda** [comment]
> @isabelirk adicionei seu email!
> 
> 
> 
> @luizdameda peço que adicione este e assim que iniciar o próximo você coloca o horário posterior!
> 
> 
> 
> @MilenaPaz2020 eu havia esquecido deste detalhe que por eu não ter aula a noite havia colocado os horários diferentes, vou providenciar essa mudança, obrigada!

Adicionado

**Comment by annacarolis** [comment]
Adicionado!

**Comment by annacarolis** [comment]
Adicionado!

**Comment by GessicaZanon** [comment]
Preenchido para essa semana como solicitado! Aliás, que coisa mais MARAVILHOSA essa planilha, Néia! Será super útil! Perfeita +q perfeita.

**Comment by JuliaGaboardiB** [comment]
Concordo com a Gess! Ficou muito organizado, Néia! Adorei. Preenchi os meus horários para a semana também.

**Comment by isabelirk** [comment]
Bom dia,

Dados adicionados!

Atenciosamente.

**Comment by MaNegrao** [comment]
Muito boa a ideia e muito bem executada, parabéns! :D. 

Eu tenho uma sugestão, não sei se será útil no momento atual, mas no futuro pode ser, que é colocar uma legenda "Transito", que pode indicar que o membro está em transito entre o campus e/ou algo do genero. (pode ser uma besteira desnecessaria também)

**Comment by MilenaPaz2020** [comment]
> Acabei de finalizar as planilhas de horários, peço que se possível todos preencham com os seus horários pelo menos a semana do dia 15/11/2021 ao dia 20/11/2021 até segunda-feira, para fazermos um teste e ver se elas precisam de melhorias. Criei uma planilha por equipe (que estão na [pasta da issue](https://drive.google.com/drive/folders/1l3w4TERrC9f2mb1DPQaSB6_J9r9KbrTM)) e dentro delas vão encontrar abas com os nomes de cada integrante.
> 
> @practice-uffs/todos
> 
> Sintam-se a vontade para sugerirem ideias de melhorias!!

@robisonjose, @S4ntin e @amandasegattob, lembrem de preencher a planiha.

**Comment by S4ntin** [comment]
> > Acabei de finalizar as planilhas de horários, peço que se possível todos preencham com os seus horários pelo menos a semana do dia 15/11/2021 ao dia 20/11/2021 até segunda-feira, para fazermos um teste e ver se elas precisam de melhorias. Criei uma planilha por equipe (que estão na [pasta da issue](https://drive.google.com/drive/folders/1l3w4TERrC9f2mb1DPQaSB6_J9r9KbrTM)) e dentro delas vão encontrar abas com os nomes de cada integrante.
> > @practice-uffs/todos
> > Sintam-se a vontade para sugerirem ideias de melhorias!!
> 
> @robisonjose, @S4ntin e @amandasegattob, lembrem de preencher a planiha.

Preenchido.

**Comment by Claudineia-VR** [comment]
As planilhas foram movidas para o drive na pasta 'Equipes' cada uma para a sua equipe de interesse!
