### ISSUE TITLE
Criar um guia de lives do PRACTICE

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#83]
Conforme definido em reunião (19/08) da con-mídia deveremos elaborar um guia detalhado com o passo a passo referente as demandas de lives. Contendo o fluxo interno, tamplates, roteiro, infraestrutura e requisitos mínimos.

Link Pasta do Drive: https://drive.google.com/drive/u/0/folders/1tG3JliUf-LanVg9SAueydrdjlBaTBvRM

**Comment by VIF-Franca** [comment]
Pasta do drive pode conter alguns imagens que poderá ser adotada como base: https://drive.google.com/drive/u/0/folders/1LZOdVqhJEN9IL92J1pv2C2Tj4dTfPoPq

**Comment by MaNegrao** [comment]
Creio que precisamos ter um modelo mais simples, que não precise ser altamente alterado de live pra live fora do OBS, como ao inves de fazer uma imagem pra cada layer de nome de participante, fazer um layer e no OBS utilizarmos a fonte de texto, como na imagem. 

![Captura de Tela (14)](https://user-images.githubusercontent.com/31110971/90774277-98537200-e2cd-11ea-9ed1-42ae81aaadfc.png)

A ideia é não sobrecarregar o OBS e deixar ele o mais leve e simples possivel pra que todo mundo consiga usar sem dificuldade, co menos cenas e fontes possiveis, sem que muitas alterações fora do nosso template precisem ser feitas. Além de dar menos trabalho para organização da live. Podemos fazer isso com os creditos também, colocando a imagem de fundo e apenas alterando o texto, creio que a unica coisa que muda fora do OBS seja a imagem de capa de cada evento.

**Comment by MaNegrao** [comment]
Acho interessante pra gente começar, definir uma sequencia do que estará no nosso guia e por onde começamos, pra ficar bem organizado. penso que podemos começar falando sobre qual o conteúdo da live (Uma reunião com varias pessoas, uma unica pessoa, com material, etc). O que acham?

**Comment by VIF-Franca** [comment]
Pessoal criei uma versão da nossa cartilha interna, gostaria do olhar do @lcaimi @MaNegrao @vini2reis sintan-se avontade para realizar modificações, deixei alguns comentários no arquivo. 

[Acesso a cartilha. ](https://drive.google.com/file/d/1NLGTrQgjdiMvpRmztX2VezV5eTLMzg84/view?usp=sharing)

**Comment by MaNegrao** [comment]
Eu olhei a versão feita e alterei coisas que julguei necessário. Olhei a parte técnica e os comentários, e também o primeiro capitulo de preparação, pretendo amanha pela amanha olhar o templates e adicionar algumas coisas, creio que depois disso podemos mandar pra revisão e já atrelar ela a capacitação

**Comment by MaNegrao** [comment]
Terminei todos os acréscimos e alterações, creio que podemos enviar para revisão.

**Comment by VIF-Franca** [comment]
@MaNegrao show suas alterações no guia.

**Comment by MaNegrao** [comment]
Ótimo, então está pronto para revisão 👍

**Comment by alessandrapedrotti** [comment]
Primeira leitura de revisão concluída.
Aguardo que os redatores @MaNegrao e @VIF-Franca façam as alterações que sugeri por meio de comentários no arquivo.

**Comment by MaNegrao** [comment]
> Primeira leitura de revisão concluída.
> Aguardo que os redatores @MaNegrao e @VIF-Franca façam as alterações que sugeri por meio de comentários no arquivo. Quando concluídas, sinalizar aqui para que eu faça a segunda leitura de revisão.

Todas as alterações requisitadas foram feitas, fico no aguardo do retorno.

**Comment by alessandrapedrotti** [comment]
Revisão textual concluída. O texto ficou muito bom, os revisores @MaNegrao e @VIF-Franca estão de parabéns.
Peço que a @mariagelain faça a revisão da diagramação.

**Comment by VIF-Franca** [comment]
Doodle respondido...

**Comment by mariagelain** [comment]
Revisão concluída.

**Comment by MaNegrao** [comment]
O guia foi adicionado em sua versão final a pasta de materiais do practice.
