### ISSUE TITLE
Escala de férias 2021.2

### ISSUE THREAD

**Issue by Claudineia-VR** [practice-uffs/programa#831]
Peço a todos que preencham a [planilha de escala de férias](https://docs.google.com/spreadsheets/d/158QsUoflxwexa0OPx6m-FXIA94iqTC1ibCiysz_cB_w/edit?usp=drive_web&ouid=115463295764233110881).

**Se vocês quiserem tirar férias em um período específico que não seja nenhuma destas datas, preencham apenas as abas 'visão geral', colocando seus nomes em ambos os períodos de atuação e 'Outra data' com o seu nome e o período que deseja. O único cuidado que precisamos ter é que sempre tenha pelo menos uma pessoa responsável atuando, para amparar a equipe.** Se ainda não programaram como vai ser podem preencher mais tarde, sem problemas.

Lembrando que só tem direito a férias quem já está no programa a mais de 1 mês, conforme descrito no [termo de direito às férias](https://docs.google.com/document/d/1IBBMq7PFYhOi1WHtNhcHsLxCpR9UgOHt3ZgBz5gmL5U/edit).

Qualquer dúvida estou a disposição!!!

@practice-uffs/todos

**Comment by robisonjose** [comment]
Também estou sem acesso.

**Comment by Claudineia-VR** [comment]
Gente desculpa, estavam todos apenas como leitores, mas já liberei!
