### ISSUE TITLE
Live - Bullying Escolar: Práticas de reflexão e combate (10/11 - 19h30)

### ISSUE THREAD

**Issue by MilenaPaz2020** [practice-uffs/programa#832]
<h1 align="center" >Informações Transmissão Ao Vivo</h1>

**Titulo**: Bullying Escolar: Práticas de reflexão e combate 

**Data e Hora**: 10/11 - 19h30

**Solicitante**: ANDREIA FLORENCIO EDUARDO DE DEUS

**Realizador(es)**: PROEC

**Palestrante Principal**: _Ainda não informado_

**Solicitação no Mural**: https://mural.practice.uffs.cc/servico/1684

**Link Transmissão**: https://youtu.be/XeoL0vxX7eI

Com os dados e roteiro em mãos, o responsável pela Live deve seguir os padrões do PRACTICE e estabelecer contato com o solicitante, enviando inicialmente o Protocolo de Execução de Lives.

**[Planilha de Lives](https://drive.google.com/drive/folders/16h-YVwTnRF49eqBYBRONKyLqPbisCIbH)**

**[Protocolo de Execução de Lives](https://drive.google.com/file/d/1KQ9vI1gKECqWHi4xwb3LrnuWCgKEHWyd/view?usp=sharing)**

**[Padronização de Lives](https://drive.google.com/file/d/1CldqvcbHPleVFd-ZKcigHhSua0VdR0mi/view?usp=sharing)**

**[TeleCurso 2000](https://drive.google.com/drive/folders/1r_Gea2VxB3J-4VfIXr9jqXa2NgStNvCs?usp=sharing)**

CC: @con-midia / lives

**Comment by MariaLuizaReviliau** [comment]
Capas finalizadas prontas para revisão, pode fazer isso @minieradka? estão no [link](https://www.figma.com/file/BV9ASnUC3sPRVoxPQtDLM9/Eventos-%C3%BAnicos?node-id=114%3A21) do figma.

**Comment by minieradka** [comment]
> Capas finalizadas prontas para revisão, pode fazer isso @minieradka? estão nesse [link](https://www.figma.com/file/BV9ASnUC3sPRVoxPQtDLM9/Eventos-%C3%BAnicos?node-id=114%3A21) do figma.

ficaram ótimas pode escolher a que preferir enviar ao solicitante

**Comment by MariaLuizaReviliau** [comment]
Obrigada @minieradka pela revisão. As capas estão na pasta de [saída](https://drive.google.com/drive/u/2/folders/1u0jYc_Tuvj4m2g9vEGQ-f9AePYSnQ_Sn), pode encaminhar para a solicitante, @MilenaPaz2020?

**Comment by MilenaPaz2020** [comment]
Na pasta de saída constam capas de outro evento.

**Comment by MariaLuizaReviliau** [comment]
As capas estão certas, apenas estavam com o título trocado. Já arrumei.

**Comment by MilenaPaz2020** [comment]
> As capas estão certas, apenas estavam com o título trocado. Já arrumei.

Enviada para a solicitante.

**Comment by MariaLuizaReviliau** [comment]
@MilenaPaz2020  a solicitante não respondeu qual modelo preferem usar?

**Comment by luizatonial** [comment]
Como não houve resposta do solicitante sobre qual capa usar, acabamos escolhendo dentro da equipe. 
Aguardo a @GessicaZanon atualizar a planilha e encerrar a issue.

**Comment by GessicaZanon** [comment]
Transmissão realizada e dados inseridos na planilha!
