### ISSUE TITLE
Live - “Formação Permanente de Professores: desafios e tensões em contextos emergentes” (26/11 - 8h30)

### ISSUE THREAD

**Issue by MilenaPaz2020** [practice-uffs/programa#833]
<h1 align="center" >Informações Transmissão Ao Vivo</h1>

**Titulo**:  “Formação Permanente de Professores: desafios e tensões em contextos emergentes”

**Data e Hora**: 26/11  (8h30 - 10h30)

**Evento Geral** (se houver): 3o Encontro do Projeto Formação Continuada de Professores da Região Macromissioneira –Edição 2021

**Solicitante**: NEUSETE MACHADO RIGO

**Realizador(es)**: Profa Dra Dóris Pires Vargas Bolzan/UFSM

**Palestrante Principal**: Projeto de Extensão de Formação Continuada de Professores da Região Macromissioneira

**Solicitação no Mural**: https://mural.practice.uffs.cc/servico/1704

**Link Transmissão**: https://www.facebook.com/events/856917868308917/

Com os dados e roteiro em mãos, o responsável pela Live deve seguir os padrões do PRACTICE e estabelecer contato com o solicitante, enviando inicialmente o Protocolo de Execução de Lives.

**[Planilha de Lives](https://drive.google.com/drive/folders/16h-YVwTnRF49eqBYBRONKyLqPbisCIbH)**

**[Protocolo de Execução de Lives](https://drive.google.com/file/d/1KQ9vI1gKECqWHi4xwb3LrnuWCgKEHWyd/view?usp=sharing)**

**[Padronização de Lives](https://drive.google.com/file/d/1CldqvcbHPleVFd-ZKcigHhSua0VdR0mi/view?usp=sharing)**

**[TeleCurso 2000](https://drive.google.com/drive/folders/1r_Gea2VxB3J-4VfIXr9jqXa2NgStNvCs?usp=sharing)**

CC: @con-midia / lives

**Comment by MariaLuizaReviliau** [comment]
Documentos adicionados na pasta. 
Desejam a divulagação do evento nas redes sociais do Practice @morgana-mo 
 A transmissão será no [facebook](https://www.facebook.com/profile.php?id=100009243321976), amanhã entrarei em contato com a solicitante para pedir login e senha para criar a transmissão. 
Desejam a confecção da capa da live, vou ficar responsável por essa parte.

**Comment by MariaLuizaReviliau** [comment]
Link da video conferência no webex: https://uffs.webex.com/meet/neusete.rigo

**Comment by MilenaPaz2020** [comment]
> Documentos adicionados na pasta. Desejam a divulagação do evento nas redes sociais do Practice @morgana-mo A transmissão será no [facebook](https://www.facebook.com/profile.php?id=100009243321976), amanhã entrarei em contato com a solicitante para pedir login e senha para criar a transmissão. Desejam a confecção da capa da live, vou ficar responsável por essa parte.

A mesma solicitante pediu a confecção de um cartaz para esse evento. Seria legal se a capa seguisse o mesmo padrão do cartaz. (#845)

**Comment by MariaLuizaReviliau** [comment]
Ok. Obrigada Rainha Miena. 
A transmissão foi criada no facebook do projeto: https://www.facebook.com/events/856917868308917/

**Comment by MariaLuizaReviliau** [comment]
capa finalizada, desculpa pela demora, mas acredito que a solicitante não irá pedir alterações pois segui o modelo do cartaz que a solicitante pediu. Alguém da @practice-uffs/con-design pode fazer a revisão gráfica? está no [figma](https://www.figma.com/file/BV9ASnUC3sPRVoxPQtDLM9/Eventos-%C3%BAnicos?node-id=197%3A3). Após a revisão vou encaminhar por whatsapp para a solictante aprovar com mais rapidez.

**Comment by TaynaraCh** [comment]
Realizei alguns ajustes, está tudo ok!

**Comment by MariaLuizaReviliau** [comment]
Solicitante aprovou a capa. Adicionei a mesma na pasta de entrada da issue e atualizei no youtube.

**Comment by luizatonial** [comment]
Live finalizada e planilha atualizada.
