### ISSUE TITLE
Reunião geral + Capacitação do Figma

### ISSUE THREAD

**Issue by Claudineia-VR** [practice-uffs/programa#834]
O objetivo desta issue é definirmos o dia e horário para a nossa reunião geral do PRACTICE e também o dia e horário que acontecerá a Capacitação do Figma. 

Estes dois eventos serão feitos em dias distintos, porém ambos ocorrerão no recesso universitário (23/10 à 08/11), então para facilitar criei apenas um doodle para votação.

Peço que respondam o [doodle](https://doodle.com/poll/ykk3xv5fph3adkkd?utm_source=poll&utm_medium=link) assim que possível!!! Qualquer dúvida é só chamar ;)

@practice-uffs/todos

**Comment by TaynaraCh** [comment]
Formação no figma concluída! Está disponível no [link](https://drive.google.com/file/d/1uv1-9lbHc1TcSldnQrVVSH00wyuUI-za/view?usp=sharing).
