### ISSUE TITLE
Coleta de dados de trabalhos realizados pela Con-Design 

### ISSUE THREAD

**Issue by TaynaraCh** [practice-uffs/programa#835]
Precisamos contabilizar e destacar entregas realizadas pela @practice-uffs/con-design, os itens são:

- [x] ID visuais;
- [x] Cartazes (inclusos cards instagram);
- [x] Banners;
- [x] Folders;
- [x] Outros;

Além disso, destacar trabalhos que consideramos de grande impacto, como por exemplo, a campanha realizada para o SAE, a ID de uma revista acadêmica, a REGIONEM, entre outros.
Todo o conteúdo deve estar no doc dentro da pasta de entrada dessa issue.

**Comment by TaynaraCh** [comment]
Realizei a coleta de de dados, escrevi um pouco sobre o trabalho realizado em cada tópico e elenquei algumas produções importantes, @minieradka, peço que leia e adicione informações que considerar pertinente, se lembrar de algo para o portfólio seria interessante acrescentar.

**Comment by minieradka** [comment]
> Realizei a coleta de de dados, escrevi um pouco sobre o trabalho realizado em cada tópico e elenquei algumas produções importantes, @minieradka, peço que leia e adicione informações que considerar pertinente, se lembrar de algo para o portfólio seria interessante acrescentar.

revisado ficou bem bom, alterei pequenas coisas apenas

**Comment by TaynaraCh** [comment]
alguém da @practice-uffs/con-conteudo poderia fazer a revisão, por favor? Não temos um prazo especifico para entrega, portanto, podem organizar conforme o cronograma de vocês.

**Comment by GessicaZanon** [comment]
> alguém da @practice-uffs/con-conteudo poderia fazer a revisão, por favor? Não temos um prazo especifico para entrega, portanto, podem organizar conforme o cronograma de vocês.

Claro, Tay! Hoje mesmo já vejo a disponibilidade das gurias e te atualizo por aqui quem ficará responsável.

**Comment by GessicaZanon** [comment]
A Júlia Ficará responsável pela revisão!

**Comment by JuliaGaboardiB** [comment]
Iniciei a revisão! Assim que concluir, aviso e comento sobre ela.

**Comment by JuliaGaboardiB** [comment]
Iniciei a revisão! Assim que concluir, aviso e comento sobre ela.

**Comment by JuliaGaboardiB** [comment]
Revisão concluída. Está tudo ok! Parabéns pelo texto.

**Comment by TaynaraCh** [comment]
Muito obrigada Julia! PDF criado e adicionado a pasta de saída.

**Comment by Eweline** [comment]
Pessoal da Con-Design, primeiro eu gostaria de parabeniza-los pela escrita do material, e à Júlia, pelo excelente trabalho de revisão. 
Só alterei uma palavra, "universidade", que coloquei em maiúsculo, pois está se referindo à UFFS, e como é tipo o nome da instituição, precisa ser colocado em maiúsculo, pelo que pesquisei.

O material revisado já está na pasta de saída.
