### ISSUE TITLE
Reunião sobre a Aura

### ISSUE THREAD

**Issue by Eweline** [practice-uffs/programa#836]
Conforme demanda, a @practice-uffs/ger-auxilio e a @practice-uffs/con-conteudo precisam fazer uma reunião de treinamento sobre a Aura.

O link para responder os possíveis horários da reunião é [este](https://dozz.io/roj1da).

A reunião está aberta a todos que tiverem interesse em participar.

**Comment by Dovyski** [comment]
O link para a gravação da reunião está [aqui](https://drive.google.com/file/d/1inEpvirypAw9t8MkGJkqFogk0fhyghNt/view?usp=sharing).
