### ISSUE TITLE
Revisão textual do Mural V2

### ISSUE THREAD

**Issue by Eweline** [practice-uffs/programa#837]
Essa issue tem relação com [esta issue](https://github.com/practice-uffs/mural/issues/384) do repositório mural.

Serão abertos, inicialmente, dois documentos, um sobre algumas dúvidas e modificações do site em geral, e outro sobre a parte dos serviços descritas na página inicial do Mural. Os documentos encontram-se na pasta de entrada.

A parte das dúvidas e modificações, [esta](https://docs.google.com/document/d/1Zuc6CuvNkhtJ9_MOX42VikwCgDu5xWcli22nYU0-BLA/edit#heading=h.6eqnd29mkbeb), deve ser considerada pelo @practice-uffs/ger-auxilio , @Dovyski , @lcaimi , enquanto a revisão da parte dos serviços, [esta](https://docs.google.com/document/d/1-YgwEnRZ3EQhwpFRs0_RfH8PeNBW_EwK7KLP6rqWdd0/edit) será feita por cada equipe responsável.

Qualquer dúvida, estou à disposição.

**Comment by Dovyski** [comment]
Para garantir que nada seja perdido, e para facilitar a incorporação, por favor, @Eweline, adicione no documento de revisão os textos que o pessoal da @practice-uffs/con-midia fez no https://v2.mural.practice.uffs.cc. Dessa forma, quando o @practice-uffs/dev incorporar tudo na versão oficial (https://practice.uffs.edu.br/mural/), nada ficará de fora.

**Comment by Eweline** [comment]
> Sim, a gente sabe como fazer as alterações. Não o fizemos porque falaram que iria ser incorporado automaticamente na mudança de url, para não ter um retrabalho. Inclusive, como comentei, o Fernando disse que vai fazer isso, então vamos aguardar.

Entendi.

**Comment by Eweline** [comment]
> Para garantir que nada seja perdido, e para facilitar a incorporação, por favor, @Eweline, adicione no documento de revisão os textos que o pessoal da @practice-uffs/con-midia fez no https://v2.mural.practice.uffs.cc. Dessa forma, quando o @practice-uffs/dev incorporar tudo na versão oficial (https://practice.uffs.edu.br/mural/), nada ficará de fora.


Professor, fazer isso com relação a todos os serviços? Pois muita coisa mudou do V2 teste para esse que será lançado.
Acredito que a melhor opção seria ir olhando o V2 teste para modificar no que será lançado, pois acho que ficará menos confuso que criar um documento grande com imagens e descrições do que já está no V2 teste.

Qualquer coisa, posso ir modificando o V2 que será lançado com as novas descrições e serviços que foram modificados por cada equipe no V2 teste, e ir revisando.

Outra coisa, não tem campo para colocar ícone nas categorias. Vocês poderiam ver isso? Pois uma categoria será modificada em outras duas, e seria interessante deixa-las juntas (a de Edição de Vídeos e de Criação de Vídeos), o que acho que teria que ser feito no final, já que as categorias são criadas uma abaixo da outra, não tendo como modificar as posições delas. E precisa dos ícones para ficar padrão no Mural.

Caso não me fiz entender, peço que entrem em contato.

**Comment by CleissonVieira** [comment]
A revisão da parte das dúvidas e modificações foi aplicada
Assim que o site ficar acessível irei aplicar a revisão da parte dos serviços

**Comment by CleissonVieira** [comment]
Revisão aplicada as categorias de serviços. As demais futuras correções podem ser realizadas pelos administradores do sistema. Quem não for administrador pode solicitar a mim, ou qualquer outro administrador, que alteramos
