### ISSUE TITLE
Disponibilidade de equipamento  - UFFS/LS

### ISSUE THREAD

**Issue by minieradka** [practice-uffs/programa#839]
em decorrência da dificuldade para exercer as atividades do programa, solicito o envio de um computador para o campus laranjeiras para a realização das demandas da con-midia e con-design.

**Comment by Dovyski** [comment]
O PC foi despachado no protocolo da UFFS Chapecó em 28/10. Não há uma previsão certa da data de chegada, mas você pode contatar o setor de malote/protocolo do campus Laranjeiras do Sul para saber do status, @minieradka .
