### ISSUE TITLE
Live - Evento GEPECMaT: "Diálogos virtuais: Alfabetização Científica e Tecnológica" (18/11 - 9h)

### ISSUE THREAD

**Issue by MilenaPaz2020** [practice-uffs/programa#840]
<h1 align="center" >Informações Transmissão Ao Vivo</h1>

**Titulo**: "Diálogos virtuais: Alfabetização Científica e Tecnológica"

**Data e Hora**: 18/11  (9h - 11h)

**Evento Geral** (se houver): Diálogos virtuais: Alfabetização Científica e Tecnológica

**Solicitante**: LEANDRO BORDIN

**Realizador(es)**: GEPECMaT (Grupo de estudo e pesquisa em educação em ciências, matemática e tecnologia) 

**Palestrante Principal**: _Verificar_

**Solicitação no Mural**: https://mural.practice.uffs.cc/servico/1733

**Link Transmissão**: https://youtu.be/4bH_lDzpnB8

Com os dados e roteiro em mãos, o responsável pela Live deve seguir os padrões do PRACTICE e estabelecer contato com o solicitante, enviando inicialmente o Protocolo de Execução de Lives.

**[Planilha de Lives](https://drive.google.com/drive/folders/16h-YVwTnRF49eqBYBRONKyLqPbisCIbH)**

**[Protocolo de Execução de Lives](https://drive.google.com/file/d/1KQ9vI1gKECqWHi4xwb3LrnuWCgKEHWyd/view?usp=sharing)**

**[Padronização de Lives](https://drive.google.com/file/d/1CldqvcbHPleVFd-ZKcigHhSua0VdR0mi/view?usp=sharing)**

**[TeleCurso 2000](https://drive.google.com/drive/folders/1r_Gea2VxB3J-4VfIXr9jqXa2NgStNvCs?usp=sharing)**

CC: @con-midia / lives

**Comment by MilenaPaz2020** [comment]
> Issue aberta para fins de organização. Assim que os documentos chegara, a descrição e título da issue devem ser alterados. @MariaLuizaReviliau

O solicitante precisava do link de modo urgente. Já criei e coloquei o mesmo na descrição. Os docs não foram adicionados.

**Comment by MariaLuizaReviliau** [comment]
Documentos adicionados a pasta de entrada desta issue. 
Link da sala do webex: https://uffs.webex.com/meet/lbordin
Não desejam ter capa para o evento, porem desejam a divulgação do evento nas redes sociais... Vou entrar em contato para ver se eles possuem a imagem de divulgação. @morgana-mo 
Link adicionado na agenda de lives do Practice.

**Comment by MilenaPaz2020** [comment]
Link de acesso para a capa do evento: https://drive.google.com/file/d/1PuPDH1VSkqeQS8uA1UxRwPOKM_5_bsYJ/view?usp=sharing

**Comment by MariaLuizaReviliau** [comment]
Adicionei como miniatura no Youtube

**Comment by GessicaZanon** [comment]
Transmissão realizada e dados inseridos na planilha!
