### ISSUE TITLE
Material de divulgação - Aprendendo a fazer transmissões ao vivo com o OBS Studio

### ISSUE THREAD

**Issue by MilenaPaz2020** [practice-uffs/programa#841]
Com extrema empolgação que avançamos mais alguns passos rumo à capacitação promovida pelo PRACTICE! (#813)

Como já conversado de modo informal, precisamos de alguns materiais de divulgação deste evento. Os textos foram elaborados e estão [neste documento](https://docs.google.com/document/d/1vxSCgRqk9WJdpr1oIvpkSLq70BZLs7ZFwgGq2n2kLGw/edit).

Deve-se seguir a ordem de confecção conforme disposto no documento (flyer, cars feed e cards story).

Nosso prazo para iniciar a divulgação era 05/11. Contudo, em vista das diversas demandas que foram surgindo, atrasamos na confecção do texto. Sugere-se, portanto, que a divulgação inicie em 10/11. Para isso o material inicial (flyer) precisaria estar finalizado até 08/11. 

Estamos à disposição em caso de dúvidas ou necesidade de apoio. 

@practice-uffs/con-design 
@practice-uffs/con-midia

**Comment by TaynaraCh** [comment]
Os cards estão sendo criados no [figma](https://www.figma.com/file/vKsmv9TiwF1RFERsOEs31T/Issues---Instagram?node-id=42%3A2).

**Comment by MariaLuizaReviliau** [comment]
As capas serão desenvolvidas no [figma](https://www.figma.com/file/BV9ASnUC3sPRVoxPQtDLM9/Eventos-%C3%BAnicos?node-id=127%3A2)

**Comment by TaynaraCh** [comment]
Material de divulgação está pronto, @luizatonial, pode dar uma conferida no [figma](https://www.figma.com/file/vKsmv9TiwF1RFERsOEs31T/Issues---Instagram?node-id=42%3A2) para termos a aprovação final? 
Adicionei o material na pasta de [entrada](https://drive.google.com/drive/folders/1XWsVKQJCUHMMNg0PTjzagY21jrPPWioR) da issue também, depois de aprovado deve ser transferido para pasta de saída.

**Comment by luizatonial** [comment]
O material está muito bom gente! Parabéns!
Como já comentado com a Tay, verifiquei apenas a questão de que as letras estavam em duas cores e já foi corrigido.
Vou revisar o material novamente quando tivermos o link para inscrição no moodle e ai faço o download e transfiro para a pasta de saída.

**Comment by luizatonial** [comment]
@TaynaraCh inseri os links e QR codes, se tu puder dar uma olhadinha pra gente finalizar.

**Comment by annacarolis** [comment]
Gente que lindo que está esse material!! Parabéns!!

**Comment by MariaLuizaReviliau** [comment]
Bom, acredito que as capas estão finalizadas!! Vou adicioná-las na pasta de entrada e se alguém quiser fazer alguma sugestão ou alteração, pode fazer através do [link do figma](https://www.figma.com/file/BV9ASnUC3sPRVoxPQtDLM9/Eventos-%C3%BAnicos?node-id=145%3A25). Se não houverem novas modificações, vou adicioná-las ao youtube.

**Comment by luizatonial** [comment]
> Bom, acredito que as capas estão finalizadas!! Vou adicioná-las na pasta de entrada e se alguém quiser fazer alguma sugestão ou alteração, pode fazer através do [link do figma](https://www.figma.com/file/BV9ASnUC3sPRVoxPQtDLM9/Eventos-%C3%BAnicos?node-id=145%3A25). Se não houverem novas modificações, vou adicioná-las ao youtube.

Perfeito @MariaLuizaReviliau! Pode atualizar no YouTube.

**Comment by TaynaraCh** [comment]
Realizei alguns ajustes e alterei os arquivos nas pastas do drive também, acredito que esteja tudo ok!

**Comment by TaynaraCh** [comment]
Criei duas bases para usar quando forem responder respostas da caixinha através de texto ou vídeo.

**Comment by luizatonial** [comment]
Muito Obrigada! Esperamos que tenham perguntas hahah

**Comment by luizatonial** [comment]
Ficou tudo maravilhoso, obrigada novamente! Falta apenas divulgar dois storys e um vídeo... Podemos encerrar a issue?

**Comment by TaynaraCh** [comment]
> Ficou tudo maravilhoso, obrigada novamente! Falta apenas divulgar dois storys e um vídeo... Podemos encerrar a issue?

Acredito que sim!
