### ISSUE TITLE
Apoio em Lives do NAP-CH

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#85]
Foi solicitado apoio para realização das lives de capacitação do Nucleo de Apoio Pedagogico do Campus Chapecó, as lives estão sendo realizadas todas as quartas-feiras do mês de agosto, como cronograma abaixo.

![Screenshot(58)](https://user-images.githubusercontent.com/31110971/90772700-4a3d6f00-e2cb-11ea-9777-1bd68e4a17f2.png)

Lives já realizadas:

- [x] Atividades para aulas remotas - Ivan Prá
- [x] Como ensinar e avaliar no ensino remoto - Mônica Ferreira
- [x] Criação de VideoAulas - Paulo Montanaro
- [x] Perguntas e Respostas sobre aulas remotas - Elisangela Ribas

**Comment by MaNegrao** [comment]
1ª Live, Profesor Ivan Prá:
https://www.youtube.com/watch?v=ST1lirQw3Nc

**Comment by MaNegrao** [comment]
3ª Live, Professor Paulo Montanaro:
https://www.youtube.com/watch?v=82CgeXsu4FE

**Comment by lcaimi** [comment]
@elisribas Favor colocar os roteiros e documentos de acordo com as datas

Pretendo usar os roteiros para coletar as informações da issue #87

**Comment by lcaimi** [comment]
PDF da live de 26/08/2020 [aqui](https://drive.google.com/file/d/1TlPuwfe5WJTE1otVW5gNiPMHGAz5jwIX/view?usp=sharing)
@MaNegrao

**Comment by MaNegrao** [comment]
4ª Live, Elisangela Ribas
https://www.youtube.com/watch?v=z4DtG-PvcM0

**Comment by MaNegrao** [comment]
@lcaimi Creio que podemos fechar essa issue, visto que as próximas tem issues próprias e estamos preenchendo todas as informações na #87
