### ISSUE TITLE
Criação de Templates do OBS para realização de lives

### ISSUE THREAD

**Issue by MaNegrao** [practice-uffs/programa#86]
A ideia é criar templates padrões para as lives realizadas e apoiadas pelo PRACTICE. O OBS permite que criemos perfis e coleções de cenas dentro desses perfis, então podemos criar um perfil para o programa e agregar nossas coleções dentro dele e exportarmos o perfil, garantindo que todos que forem realizar lives utilizem o mesmo perfil.
Penso que as coleções de cena devem ser objetivas e com o minimo de redundancia possivel, não precisamos de inumeras cenas, apenas algumas bem feitas e aproveitadas com os recursos que o software disponibilza. 
Para que o template seja totalmente aproveitado a pessoa terá que baixar a pasta com as imagens padrão do programa, o que deve ser demonstrado e explicado no guia da issue #83 

O primeiro passo para a criação dos templates é decidir quantos e quais tipos de live deverão ter templates.

[Pasta Dive](https://drive.google.com/drive/u/0/folders/1MjjRDyl5DZhlZ2EavCAOJm1RUVltNBMs)

**Comment by MaNegrao** [comment]
Adicionei na pasta da issue no drive um exemplo base que podemos já usar, ele tá bem completo e funcional, tenho utilizado ele nas lives do NAP com o Webex

**Comment by MaNegrao** [comment]
O template base foi atualizado, eu modifiquei ele pra que posa ser utilizado em uma tela só. Contendo apresentação, apresentador e interprete de libras.

**Comment by Dovyski** [comment]
Como uma sugestão, podemos criar um repositório chamado `practice-obs-templates`, onde cada pasta é um template "oficial" do practice. Dessa forma, fica ótimo para nós e para outras pessoas interessadas (inclusive da interwebs).

**Comment by MaNegrao** [comment]
Acho ótimo. Fica melhor organizado e visível. Se for o caso podemos transportar esse primeiro modelo para lá.

**Comment by vini2reis** [comment]
@MaNegrao criei dois novos pequenos videos de logos inspirado naquele que você fez.
[logos_alternativos.zip](https://github.com/practice-uffs/programa/files/5170274/logos_alternativos.zip)

Se você concordar adiciono no template.

**Comment by MaNegrao** [comment]
Boaaa, coloca lá na pastinha e tá tudo certo, eu atualizo o JSON com eles daí. Valeeeu

**Comment by vini2reis** [comment]
Ok. Coloquei la na pasta já

**Comment by MaNegrao** [comment]
@lcaimi Iremos prosseguir para o repositório separado?

**Comment by lcaimi** [comment]
Vamos seguir a recomendação do Fernando.

Criei a pasta [OBS-templates](https://drive.google.com/drive/folders/10rRXLCNkY4bBaWlzciepf9-hm47RZdvI?usp=sharing) dentro da pasta Materiais do programa. Pode transferir para a pasta e encerrar esta ISSUE. @MaNegrao

**Comment by MaNegrao** [comment]
Coloquei lá, tudo certo
