### ISSUE TITLE
Registro das Lives que tiveram auxilio do Practice

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/programa#87]
Esta issue foi criada para registrar as Lives já realizadas com o auxílio do Practice.
Depois de termos as informações coletadas vamos criar um flyer para cada uma delas e colocar na página do programa com o respectivo link de acesso. Poderemos usar o flyer para enviar para grupos e mídias sociais também. 

Exemplo de informações e preenchimento

Titulo: Produção de Video para aulas remotas
Organizador: NÚcleo de Apoio Pegagógico - campus Chapecó
Palestrante: Fulano de tal
Participantes: Elisangela Ribas
               Igor Catalão
Data: 20/08/2020
Hora: 9h
Link: www.youtube.com/jhadfg
Equipe Practice: Vinicius França
                 Mateus Negrão

**Comment by lcaimi** [comment]
- Live Andifes - Maurício/Nedilso
@phdmauricio  coloca as informações aqui. Veja exemplo abaixo

- Live Capacitação Ensino Estadual I - Maurício
@phdmauricio  coloca as informações aqui. Veja exemplo abaixo

- Live Capacitação Ensino Estadual II - Maurício
@phdmauricio  coloca as informações aqui. Veja exemplo abaixo

- Live LS - Maurício/Caimi 
  Com direção do campus
  VInicius França
  @phdmauricio  coloca as informações aqui. Veja exemplo abaixo
 @VIF-Franca   coloca as informações aqui. Veja exemplo abaixo

- Live Lançamento Practice
	Promoção: projeto Practice
	Titulo: Lançamento do Programa Practive - UFFS
	Participantes: Gismael 
		Nedilso Brugnera
		Maurício Bazatski
		Fernando Bevilacqua
		Elisângela Ribas
		Luciano L. Caimi
	Equipe Practice: Vinicius França
		Vinícius Reis
		Cleisson Vieira Raimundi 
	Data: 29/07
	Horário: 14h
	Link: https://www.youtube.com/watch?v=JQMc37pS3cM

- Live NAP - CH 
	Promoção: NAP - Campus Chapecó
	Titulo: Atividades em Aulas Remotas
	Palestrante: Ivan Prá
	Mediação: Elisângela Ribas
	Equipe Practice: Matheus Negrão
	Data: 05/08
	Horário: 9h
	Link: https://www.youtube.com/watch?v=ST1lirQw3Nc  

- Live LS
	Evento: Semana de Formação Docente da UFFS - Campus Laranjeiras do Sul
	Promotor: NAP - campus Laranjeiras do Sul
	Titulo: Ferramentas tecnológicas para o ensino e aprendizagem em tempos de covid-19 
	Palestrante: Profª Wendy Beatriz Witt Haddad Carraro (UFRGS)
	Organizadores: Anderson Sartorelli 
		Joaquim Gonçalves da Costa 
		Letícia Cristina Bizarro Barbosa 
		Lucimara Lemiechek 
		Silva Romão 
		Thiago Bergler Bitencourt 
	Equipe Practice: Vinícius França Alves
	Data: 05/08
	Horário: 18:00h
	link: https://www.youtube.com/watch?v=o2yXowjtzPw&feature=youtu.be


- Live NAP -LS
	Evento: Semana de Formação Docente da UFFS - Campus Laranjeiras do Sul
	Promotor: NAP - campus Laranjeiras do Sul
	Titulo: (Re)organizando a prática pedagógica em tempos de pandemia:experiências e desafios 
	Palestrante: Profº Thiago Bitencourt (UFFS)
	Organizadores: Anderson Sartorelli 
		Joaquim Gonçalves da Costa 
		Letícia Cristina Bizarro Barbosa 
		Lucimara Lemiechek 
		Silva Romão 
		Thiago Bergler Bitencourt 
	Equipe Practice: Vinícius França Alves
	Data: 06/08
	Horário: 14:00h
	link: https://www.youtube.com/watch?v=fvxV0-kJ300

- Live NAP - LS
	Evento: Semana de Formação Docente da UFFS - Campus Laranjeiras do Sul
	Promotor: NAP - campus Laranjeiras do Sul
	Titulo: Oficina: O ambiente MOODLE como ferramenta nos processos de ensino e aprendizagem 
	Palestrante: Profª Bruno Oliveira (UFFS)
	Organizadores: Anderson Sartorelli 
		Joaquim Gonçalves da Costa 
		Letícia Cristina Bizarro Barbosa 
		Lucimara Lemiechek 
		Silva Romão 
		Thiago Bergler Bitencourt 
	Equipe Practice: Vinícius França Alves
	Data: 07/08
	Horário: 14:30h
	link: https://www.youtube.com/watch?v=cvHEtuMbebo


- Live NAP - CH 
	Promoção: NAP - Campus Chapecó
	Título: Como ensino e avalio no ensino remoto
	Palestrante: Monica Ferreira - CEFET/MG
	Mediação: Elisângela Ribas
	Participantes: Igor Catalão	
	Equipe Practice: Matheus Negrão
	Data: 12/08
	Horário: 9h
	Link: 

- Live NAP - CH
	Promoção: NAP - Campus Chapecó
	Titulo: Criação de Video Aulas
	Palestrante: Paulo Montanaro (UFSCAR)
	Mediador: Elisângela Ribas
	Equipe Practice: Matheus Negrão
	Data: 18/08
	Horário: 9h
	Link: https://www.youtube.com/watch?v=82CgeXsu4FE


- Live NAP - LS
	Evento: Semana de Formação Docente da UFFS - Campus Laranjeiras do Sul
	Promoção: NAP - Campus Laranjeiras do Sul
	Titulo: Oficina Padlet
	Palestrante: Profª Letícia C. Bizarro Barbosa
	Organizadores: Anderson Sartorelli 
		Joaquim Gonçalves da Costa 
		Letícia Cristina Bizarro Barbosa 
		Lucimara Lemiechek 
		Silva Romão 
		Thiago Bergler Bitencourt 
	Equipe Practice: Vinícius França Alves
	Data: 18/08
	Horário: 9:30h



- Live LS
	Evento: Semana de Formação Docente da UFFS - Campus Laranjeiras do Sul
	Promotor: NAP - campus Laranjeiras do Sul
	Titulo: Oficina Webex
	Palestrante: Profº Alexandre Manoel
	Organizadores: Anderson Sartorelli 
		Joaquim Gonçalves da Costa 
		Letícia Cristina Bizarro Barbosa 
		Lucimara Lemiechek 
		Silva Romão 
		Thiago Bergler Bitencourt 
	Equipe Practice: Vinícius França Alves
	Data: 20/08
	Horário: 19:00h


- Live LS 
	Evento: Semana de Formação Docente da UFFS - Campus Laranjeiras do Sul
	Promotor: NAP - campus Laranjeiras do Sul
	Titulo: Oficina Moodle
	Palestrante: Profº Bruno Fernandes de Oliveira
	Organizadores: Anderson Sartorelli 
		Joaquim Gonçalves da Costa 
		Letícia Cristina Bizarro Barbosa 
		Lucimara Lemiechek 
		Silva Romão 
		Thiago Bergler Bitencourt 
	Equipe Practice: Vinícius França Alves
	Data: 21/08
	Horário: 16:00h

**Comment by VIF-Franca** [comment]
Link ajustados.

**Comment by lcaimi** [comment]
@phdmauricio precisamos das informações das formações que você realizou.

**Comment by phdmauricio** [comment]
Live
Evento: Capacitação docentes rede municipal de ensino de Anchieta - SC. 
Promotor: Maurício Fernando Bozatski
Titulo: Ecossistemas Educacionais. Conectando Tecnociência e Sociedade.
Palestrante: Prof. Dr. Maurício Fernando Bozatski
Organizadores: Maurício Fernando Bozatski; Claudete Junges.
Equipe Practice: Maurício Fernando Bozatski
Data: 30/06
Horário: 19:00h
LINK: https://www.youtube.com/watch?v=EnuxBQZoJbc&t=519s

**Comment by phdmauricio** [comment]
Live
Evento: Capacitação docentes rede municipal de ensino de Maravilha- SC.
Promotor: Maurício Fernando Bozatski
Titulo: Inovações Tecnológicas e Paradimas Educacionais
Palestrante: Prof. Dr. Maurício Fernando Bozatski
Organizadores: Maurício Fernando Bozatski; Dilma Bertoldi Benvenuti
Equipe Practice: Maurício Fernando Bozatski
Data: 29/06
Horário: 14:00h
LINK:  https://www.youtube.com/watch?v=f3NY06KpAWo

**Comment by phdmauricio** [comment]
PS.: Galera, nas abreviações existe Prof. = professor e Profa. = professora.

Profo. = professoro esta incorreto.
