### ISSUE TITLE
Divulgar edital de novos bolsistas do PRACTICE nas redes sociais

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#88]
Precisamos divulgar o edital para bolsista do PRACTICE. Para isso, fazer o seguinte:

* [x] Criar arte com as informações sobre o edital para bolsistas do programa (@practice-uffs/con);

- [x] @practice-uffs/ger-auxilio após a criação deve realizar a postagens em todas as redes sociais;

[https://www.uffs.edu.br/UFFS/atos-normativos/edital/gr/2020-0460](https://www.uffs.edu.br/UFFS/atos-normativos/edital/gr/2020-0460)

A postagem/imagem deve conter:

* Data de inscrição: 21 a 27/08/2020
* Quantidade de vagas:

Cerro Largo  03
Chapecó  03
Erechim  03
Passo Fundo  03
Realeza  03

Link para o edital: https://www.uffs.edu.br/UFFS/atos-normativos/edital/gr/2020-0460

* [ ] Criar uma notícia do site do PRACTICE com uma das artes e com as informações acima.

**Comment by Dovyski** [comment]
@practice-uffs/con e @practice-uffs/ger-auxilio ficam encarregadas do conteúdo/arte e publicação na redes sociais. @practice-uffs/dev-web coloca a notícia no site.

**Comment by CleissonVieira** [comment]
Pessoal, já criei a notícia só preciso saber exatamente o que colocar nele, assim que for disponibilizado imagem ou novos conteúdos eu vou atualizando a notícia.

![image](https://user-images.githubusercontent.com/29258164/90820687-251b2180-e308-11ea-8410-8331ebff6f86.png)

![image](https://user-images.githubusercontent.com/29258164/90821030-a8d50e00-e308-11ea-9c45-0439721b8441.png)
![image](https://user-images.githubusercontent.com/29258164/90821067-b2f70c80-e308-11ea-9620-29b769a22221.png)

**Comment by VIF-Franca** [comment]
Edital divulgado nas redes sociais, sendo elas as seguintes: Instagram, Facebook e Twitter. 

Como as inscrições são permitidas até dia 27/08, irei repostar no story dia 26/08.


- [ ] repostar no story sobre o processo seletivo --> @practice-uffs/ger-auxilio
