### ISSUE TITLE
Live - Palestra de Governança Pública nas IFES - Primeiros Passos: O Caso da UNIFEI (15/12 - 8h30)

### ISSUE THREAD

**Issue by MilenaPaz2020** [practice-uffs/programa#887]
<h1 align="center" >Informações da Transmissão Ao Vivo</h1>

**Titulo**: Palestra de Governança Pública nas IFES - Primeiros Passos: O Caso da UNIFEI 

**Data e Hora**: 15/12 - 8h30

**Evento Geral** (se houver): _Não informado_

**Solicitante**: FABIANO GEREMIA

**Realizador(es)**: _Não informado_

**Palestrante Principal**: _Não informado_

**Solicitação no Mural**: https://mural.practice.uffs.cc/servico/1832

**Link Transmissão**: https://youtu.be/KMiR1P_EshQ

- [x] #980

Com os dados e roteiro em mãos, o responsável pela Live deve seguir os padrões do PRACTICE e estabelecer contato com o solicitante, enviando inicialmente o Protocolo de Execução de Lives.

**[Planilha de Lives](https://drive.google.com/drive/folders/16h-YVwTnRF49eqBYBRONKyLqPbisCIbH)**

**[Protocolo de Execução de Lives](https://drive.google.com/file/d/1KQ9vI1gKECqWHi4xwb3LrnuWCgKEHWyd/view?usp=sharing)**

**[Padronização de Lives](https://drive.google.com/file/d/1CldqvcbHPleVFd-ZKcigHhSua0VdR0mi/view?usp=sharing)**

**[TeleCurso 2000](https://drive.google.com/drive/folders/1r_Gea2VxB3J-4VfIXr9jqXa2NgStNvCs?usp=sharing)**

CC: @con-midia / lives

**Comment by MilenaPaz2020** [comment]
@MariaLuizaReviliau, o formulário foi encaminhado para o solicitante. Assim que chegar, favor adicionar os docs e alterar descrição.

**Comment by MariaLuizaReviliau** [comment]
Documentos adicionados na pasta de entrada
Precisam da confecção da capa 
link adicionado na agenda de lives
desejam a divulgação nas redes sociais @morgana-mo

**Comment by MariaLuizaReviliau** [comment]
capa adicionada a pasta de entrada

**Comment by MilenaPaz2020** [comment]
Live finalizada e planilha atualizada.
