### ISSUE TITLE
Postar no canal do Youtube do programa o vídeo passado durante a live de lançamento

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#89]
Se eu não estou enganado, o vídeo que passou durante a live de lançamento (de 1 min e 40 segundos mais ou menos) está no canal do Youtube como privado ou não listado. Pode postar esse vídeo publicamente, com uma descrição adequada e o título "Nossa visão do futuro (resumido)".

**Comment by VIF-Franca** [comment]
No nosso canal do Youtube os vídeos que constam como privados são os vídeos promocionais elaborados na Issue #65. Sendo assim adicionei o vídeo promocional adaptado da issue #70 no nosso canal. 

A/c.: @practice-uffs/con-conteudo --> Por gentileza realizar a revisão da redação sobre a descrição. 


**Título**: Nossa visão do futuro (resumido)

Descrição: 

Você já conhece a visão de futuro que buscamos alcançar com o PRACTICE, o Programa de Ampliação e Consolidação de Tecnologias e Inovação no Contexto Educacional

Buscamos facilitar e otimizar a produção e a distribuição de materiais educacionais e de entretenimento, criando soluções de problemas através da inovação, empoderando tecnologicamente as pessoas no contexto educacional.

Para saber mais sobre o PRACTICE, se inscreva no canal e acompanhe os próximos conteúdos.

Redes Sociais
Instagram: @practiceuffs
Facebook: Practice UFFS
Twitter: @practiceuffs
Website: https://practice.uffs.cc/


@Dovyski veja o que acha do texto.

**Comment by alessandrapedrotti** [comment]
> Você já conhece a visão de futuro que buscamos alcançar com o PRACTICE, o Programa de Ampliação e Consolidação de Tecnologias e Inovação no Contexto Educacional
> 
> Buscamos facilitar e otimizar a produção e a distribuição de materiais educacionais e de entretenimento, criando soluções de problemas através da inovação, empoderando tecnologicamente as pessoas no contexto educacional.
> 
> Para saber mais sobre o PRACTICE, se inscreva no canal e acompanhe os próximos conteúdos.

Sugiro: 

Você já conhece a visão de futuro que buscamos alcançar com o PRACTICE, o Programa de Ampliação e Consolidação de Tecnologias e Inovação no Contexto Educacional?

Buscamos facilitar e otimizar a produção e a distribuição de materiais educacionais, solucionando problemas através da inovação e empoderando tecnologicamente as pessoas em contextos educacionais.

Para saber mais sobre o PRACTICE se inscreva no canal e fique atento aos próximos conteúdos.

*Um adendo: é importante adicionar as labels corretas. Nessa issue, por exemplo, deveria ter sido adicionada a label "texto: revisar" e a label da equipe de conteúdo.*

**Comment by VIF-Franca** [comment]
Obrigado @alessandrapedrotti 

Obrigado pela dica das labels. 


`LINK DO VÍDEO POSTADO --> https://youtu.be/V6kS3fPytiQ`
