### ISSUE TITLE
Fluxograma de agendamento de gravação

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/programa#9]
Para manter todas as demandas organizadas e manter um fluxo de trabalho eficiente e transparente, é necessário criar um fluxograma que explique como agendamentos de gravação devem ser feitos.

Assim que mais detalhes surgirem, essa issue será devidamente editada e comentada (@Dovyski e @lcaimi).

[Pasta Drive](https://drive.google.com/drive/folders/1MAV61IQ6aS1PIsHnTYipdKrhpF3IdAkP)

**Comment by MaNegrao** [comment]
@lcaimi creio que podemos trabalhar nesse fluxo, visto que já estamos com as operações do estudio ativas

**Comment by lcaimi** [comment]
Sim. Você consegue editar um fluxo usando como base os fluxos criados para produção de vídeo e audio ([Issue #53](https://github.com/practice-uffs/programa/issues/53))?

Tem que incluir no início do fluxo, antes de aceitar a demanda no Practice a assinatura do termo de licença ([issue #54](https://github.com/practice-uffs/programa/issues/54))

**Comment by MaNegrao** [comment]
Consigo editar sim, vou acresentar o que pediu. A gente vai manter toda a parte de edição que vem posteriormente ou vamos fazer só o fluxo até a gravação e a partir dai é outro fluxo?

**Comment by MaNegrao** [comment]
![Fluxo de tramitação Estudio](https://user-images.githubusercontent.com/31110971/94620395-f1c39f00-0284-11eb-96cb-73e25f618854.png)

Eu fiz uma primeira versão, tentei agregar tudo que envolve as gravações

**Comment by MaNegrao** [comment]
@lcaimi pode dar uma olhada e ver se precisamos acrescentar algo?

**Comment by lcaimi** [comment]
Acho que a verificação de disponibilidade de horário tem que ser feita na primeira interação com o solicitante. É uma informação muito importante e determinante na viabilidade de auxílio.

**Comment by MaNegrao** [comment]
> Acho que a verificação de disponibilidade de horário tem que ser feita na primeira interação com o solicitante. É uma informação muito importante e determinante na viabilidade de auxílio.

Sim, vou alterar e mando a nova versão aqui

**Comment by MaNegrao** [comment]
![Fluxo de tramitação Estudiov2](https://user-images.githubusercontent.com/31110971/95640012-0ff18200-0a71-11eb-99f2-ff4087960b3b.png)
Fiz uma versão nova, creio que tá mais perto do real agora

**Comment by MaNegrao** [comment]
@lcaimi, quando puder dar uma olhada, acho que não serão mais necessárias alterações

**Comment by MaNegrao** [comment]
Por ora, mantemos esse, caso precisemos alterar, reabrimos a issue
