### ISSUE TITLE
Criar Flyer para as Lives já realizadas

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/programa#95]
Criar um flyer de divulgação para cada uma das lives já realizadas pelo programa, conforme a issue #87 

O flyer deve conter (coim exemplo):

- Título: Ferramentas para o ensino remoto
- Palestrante: Prof. Dr.  Fulano de tal (IFRS)
- Promoção: NAP - campus Chapecó
- Link de acesso: www.youtube.com/huHB2ljD
- QRcode com o link de acesso

[Pasta do Drive](https://drive.google.com/drive/u/0/folders/1TsOlgI0ul58KR4G6GaJzmFF-MjlhYdpO)

**Comment by MaNegrao** [comment]
Acho que pode ser apenas transpostas essas informações para um dos modelos de Panfleto contidos na pasta do drive da issue #46

**Comment by MaNegrao** [comment]
Eu fiz um primeiro modelo bem simples e direto. Pelo que eu entendi que o Caimi descreveu era isso, um informativo de portfólio. Eu utilizei o modelo de panfleto da issue #46, com algumas alterações de tamanho de letra e etc. 
Gostaria de saber o que o pessoal da @practice-uffs/ger achou.

Completo dizendo que se esse modelo for adotado como padrão, não precisaremos atolar o con-design com estes flyers, já que é só editar o pptx.

![Flyer Live NAP 05_08](https://user-images.githubusercontent.com/31110971/91771353-38a47300-ebb9-11ea-9d60-442084eebe01.png)

**Comment by lcaimi** [comment]
Eu achei ok!
@elisribas 
@Dovyski 
@phdmauricio 
@estelavilasboas 

Se aprovado o modelo podemos fazer para as demais

**Comment by Dovyski** [comment]
Eu achei excelente, parabéns! Uma coisa que me ocorreu agora: não seria legal colocar tipo uma "estampa" do tipo "evento realizado"? Para deixar bem claro que é algo passado?

**Comment by MaNegrao** [comment]
Acho uma ideia muito boa. Tipo um emblema no lado, ia ficar bem massa.

**Comment by Dovyski** [comment]
hum, não sei se gostei muito desse =P Eu imaginava algo mais assim:

![image](https://user-images.githubusercontent.com/512405/92140215-33c50680-ede7-11ea-9116-bd891d572a6e.png)

@estelavilasboas é factível criar uma estampa nesse estilo sem muito trabalho?

**Comment by Dovyski** [comment]
@MaNegrao outro detalhe: reduzir o espaçamento entre linhas no titulo do evento. Há muito espaço entre as linhas agora:

![image](https://user-images.githubusercontent.com/512405/92140416-725ac100-ede7-11ea-8c97-3f3aa7b957c1.png)

**Comment by MaNegrao** [comment]
Belezaa. Eu alterei o título e fico aguardando quanto ao selinho haha

**Comment by estelavilasboas** [comment]
> hum, não sei se gostei muito desse =P Eu imaginava algo mais assim:
> 
> ![image](https://user-images.githubusercontent.com/512405/92140215-33c50680-ede7-11ea-9116-bd891d572a6e.png)
> 
> @estelavilasboas é factível criar uma estampa nesse estilo sem muito trabalho?

Assim?
![image](https://user-images.githubusercontent.com/30927758/92243555-084e2480-ee98-11ea-8a29-f42dfbcf8f48.png)

**Comment by Dovyski** [comment]
Estou em prantos de felicidade, @estelavilasboas , é extamente assim! E muito além do que eu poderia imaginar na escala de "buniteza". Obrigado! ❤️😭🥳😄

**Comment by estelavilasboas** [comment]
Vou fazer versões nas cores da paleta e colocar na pasta Elementos do drive, assim, se for necessário para outros usos, já está pronto.    :)

**Comment by MaNegrao** [comment]
![Flyer Live NAP 05_08](https://user-images.githubusercontent.com/31110971/92246392-10a85e80-ee9c-11ea-851f-a1afcb946846.png)

O Flyer final ficou assim :D. Eu curti, se aprovarem, acho que podemos fazer todos nesse estilo...

**Comment by estelavilasboas** [comment]
Observação: Cortou o "P" do escrito "Programa" 😆

**Comment by MaNegrao** [comment]
Opa, desatenção minha haha, já arrumo

**Comment by Dovyski** [comment]
O flyer ficou excelente. Pode seguir com a criação de todos os arquivos PNG dos flyers, colocando eles na pasta [saída](https://drive.google.com/drive/u/0/folders/1e8ygrPWVIYHaberERZQBe9pRBVteSBe9) dessa issue.

**Comment by VIF-Franca** [comment]
Ficou TOP a arte!!!

**Comment by VIF-Franca** [comment]
Eventos já realizados de acordo coma issue #87 

- [ ] Evento: Capacitação docentes rede municipal de ensino de Maravilha- SC.
Promotor: Maurício Fernando Bozatski
Titulo: Inovações Tecnológicas e Paradimas Educacionais
Palestrante: Prof. Dr. Maurício Fernando Bozatski
Organizadores: Maurício Fernando Bozatski; Dilma Bertoldi Benvenuti
Equipe Practice: Maurício Fernando Bozatski
Data: 29/06
Horário: 14:00h
LINK: https://www.youtube.com/watch?v=f3NY06KpAWo

- [ ] Evento: Capacitação docentes rede municipal de ensino de Anchieta - SC.
Promotor: Maurício Fernando Bozatski
Titulo: Ecossistemas Educacionais. Conectando Tecnociência e Sociedade.
Palestrante: Prof. Dr. Maurício Fernando Bozatski
Organizadores: Maurício Fernando Bozatski; Claudete Junges.
Equipe Practice: Maurício Fernando Bozatski
Data: 30/06
Horário: 19:00h
LINK: https://www.youtube.com/watch?v=EnuxBQZoJbc&t=519s

- [ ] Live LS - Maurício/Caimi
Promoção: Diretor Martinho Machado Jr do Campus Laranjeiras do Sul
Titulo: EDUCAÇÃO E INOVAÇÃO: REPENSANDO PARADIGMAS E PROPONDO POSSÍVEIS SOLUÇÕES
Mediação: Prof° Martinho Machado Junior - Diretor do campus LDS
Convidados:
Prof° Nedilso Lauro Brugnera;
Prof° Maurício Fernando Bozatski;
Prof° Luciano Lores Caimi;
Profª Vivian Machado Menezes;
Prof° Alexandre Manoel;
Prof° Rubens Fey
Equipe Practice: Vinicius França
Data: 23/06/2020
Horário: 19h
Link: https://youtu.be/JpcaYe_R52Q

- [ ] Live Lançamento Practice
Promoção: projeto Practice
Titulo: Lançamento do Programa Practive - UFFS
Participantes: Gismael
Nedilso Brugnera
Maurício Bazatski
Fernando Bevilacqua
Elisângela Ribas
Luciano L. Caimi
Equipe Practice: Vinicius França
Vinícius Reis
Cleisson Vieira Raimundi
Data: 29/07
Horário: 14h
Link: https://www.youtube.com/watch?v=JQMc37pS3cM

- [ ] Live NAP - CH
Promoção: NAP - Campus Chapecó
Titulo: Atividades em Aulas Remotas
Palestrante: Ivan Prá
Mediação: Elisângela Ribas
Equipe Practice: Matheus Negrão
Data: 05/08
Horário: 9h
Link: https://www.youtube.com/watch?v=ST1lirQw3Nc

- [ ] Live LS
Evento: Semana de Formação Docente da UFFS - Campus Laranjeiras do Sul
Promotor: NAP - campus Laranjeiras do Sul
Titulo: Ferramentas tecnológicas para o ensino e aprendizagem em tempos de covid-19
Palestrante: Profª Wendy Beatriz Witt Haddad Carraro (UFRGS)
Organizadores: Anderson Sartorelli
Joaquim Gonçalves da Costa
Letícia Cristina Bizarro Barbosa
Lucimara Lemiechek
Silva Romão
Thiago Bergler Bitencourt
Equipe Practice: Vinícius França Alves
Data: 05/08
Horário: 18:00h
link: https://www.youtube.com/watch?v=o2yXowjtzPw&feature=youtu.be

- [ ]

**Comment by VIF-Franca** [comment]
Adicionei aqui na issue as lives já realizadas com as caixinhas de check list, creio que irá auxiliar para saber quais flayer já estão executados.

**Comment by MaNegrao** [comment]
Criei o Flyer para todas as lives realizadas, incluindo a issue #92 para as marcadas, procurei manter o padrão, então alguns títulos eu tive que encurtar, estou a disposição se quiserem mudar algo em algum dos flyer. 

Todos eles estão na pasta saida da pasta do drive

**Comment by lcaimi** [comment]
Exatamente. Temos que ver um mecanismo para o pessoal do @practice-uffs/dev-web ir adicionando no site->repositório conforme ficam disponíveis os Flyers.

**Comment by lcaimi** [comment]
Falamos o seguinte. Para cada Live realizada cria o Flyer e coloca na pasta da respectiva ISSUE. Quando o Flyer estiver pronta marca o @practice-uffs/dev-web para incluir no repositório.

**Comment by CleissonVieira** [comment]
@lcaimi Cria uma Issue para fazer uma tela que lista todos os Flyer existentes até o momento, que só foi solicitado para listar 4 dessas na página `/portfolio` conforme print abaixo. Ai eu coloco a opção de ver todos nessa tela que direciona para `/portfolio/flyers` por exemplo. O que você acha? Ai conforme vai acontecendo live e mais flyers são criados, uma nova issue forma e eu adiciono. 

![image](https://user-images.githubusercontent.com/29258164/92785131-8bcab280-f37d-11ea-8f95-2c4fcf05b22d.png)

**Comment by Dovyski** [comment]
Já criei a issue, @CleissonVieira: https://github.com/practice-uffs/website-programa/issues/54

**Comment by MaNegrao** [comment]
@CleissonVieira Criei uma pasta no drive dentro da pasta de materiais, pra ficar mais fácil pra ti acessar os flyers dessas lives e das futuras que vamos produzir.

@lcaimi podemos fechar essa tarefa então?

**Comment by lcaimi** [comment]
Sim. Segue na issue criada [website-programa#54](https://github.com/practice-uffs/website-programa/issues/54).
