### ISSUE TITLE
Capacitação interna para auxílio em Lives

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/programa#96]
Nesta issue definiremos os participantes e a data da capacitação e a data da mesma.

[Roteiro](https://docs.google.com/document/d/11_SIfmgM7lbX149Eo9ytWklyjNIaO6t26EAUVjzSvRU/edit#heading=h.pad3oc1uymo9)
Ministrantes: @MaNegrao, @VIF-Franca 
Requisitos para capacitação:

- Cadastre-se no youtube e solicite a ativação de transmissões que leva 24h (Caso nunca tenha feito). Para solicitar basta clicar no botão de fazer transmissão, como na imagem.
![Captura de Tela (22)](https://user-images.githubusercontent.com/31110971/91613018-10b4d580-e955-11ea-988f-7cb55b5c9b3f.png)
- Baixe e instale o OBS no [Link](https://obsproject.com/pt-br/download)
- Baixe o [modelo de template](https://drive.google.com/file/d/1ONuQHkzTsulC20j-8WneRF5b1fNtVEan/view?usp=sharing) do OBS do PRACTICE 
- Baixe e instale a família de fontes Roboto no Windows, o zip está na junto ao template
- Solicite a criação da sua conta no Webex com o e-mail institucional, através do [Link](https://servicos.uffs.edu.br/faqs/webex-orientacoes-e-primeiro-acesso), caso não consiga até a capacitação, poderá ser utilizado a conta padrão.
- Baixe em seu computador, se for possível, a aplicação do Webex Meeting (o Webex pode ser utilizado no navegador caso não consiga baixar)
- Leia de forma atenta a primeira versão do guia de transmissões: [Guia Para Gerenciamento De Transmissões Ao Vivo V1](https://github.com/practice-uffs/programa/files/5144319/Guia.Para.Gerenciamento.De.Transmissoes.Ao.Vivo.pdf)

Data: definir no Doodle
[https://doodle.com/poll/qzta2ndcpir8gkhz](https://doodle.com/poll/qzta2ndcpir8gkhz)

[Pasta Drive](https://drive.google.com/drive/u/0/folders/1Bp07CXczcXy3eWuq60fqcngjChSK9WyW)

**Comment by Dovyski** [comment]
O representante da equipe de dev que participará é o @CleissonVieira . Por favor, acessar o doodle para informar seus horários de particpação.

**Comment by VIF-Franca** [comment]
Doodle respondido.

**Comment by MaNegrao** [comment]
Vou montar um "roteiro" do que pretendo abordar na capacitação com base na cartilha interna que estamos produzindo na issue #83, assim conseguimos delimitar corretamente o tempo e os assuntos sem que fique sem pé nem cabeça. 
E como solicitado pelo professor Caimi vou acrescentar aqui na issue o que será necessário para a capacitação semana que vem.

**Comment by MaNegrao** [comment]
Adicionei a descrição da issue tudo aquilo que penso ser minimamente necessário para capacitação, o ideal é que tenhamos tudo isso inicialmente feito. Se houver algo mais podem colocar.

**Comment by MaNegrao** [comment]
[Guia Para Gerenciamento De Transmissões Ao Vivo V1](https://github.com/practice-uffs/programa/files/5144319/Guia.Para.Gerenciamento.De.Transmissoes.Ao.Vivo.pdf)

Segue a primeira versão do guia de lives

**Comment by MaNegrao** [comment]
Para todos que forem participar:
Eu atualizei a ultima versão do template do OBS da issue #86 pra que ele possa ser usado com uma tela só, vai ser esse que utilizaremos na capacitação. Além do que acrescentei o pacote de fontes Roboto (Padrão PRACTICE), baixem e instalem no windows. Creio que estamos prontos para capacitação. Até lá.

**Comment by MaNegrao** [comment]
Mantemos essa issue até o nosso reencontro para apresentação ou fechamos ela e abrimos outra? @lcaimi

**Comment by lcaimi** [comment]
Sim. Mantemos por enquanto.

**Comment by MaNegrao** [comment]
Como conversado na reunião de lideres, vamos marcar outra capacitação com os bolsistas integrantes do midia, além da produção de videos tutoriais para utilização do OBS

**Comment by MaNegrao** [comment]
Agora com a equipe completa, precisamos marcar uma reunião para capacitar o máximo de bolsistas possível para realização de transmissões on-line, abordarei também como realizar uma conexão remota para utilização de um dos pcs do programa. A ideia é ter pelo menos 3 ou 4 pessoas especializadas em fazer lives além da equipe inicial.

@practice-uffs/con-midia  Todos aqueles que puderem e quiserem, além dos participantes da ilha de lives, deve fazer a capacitação.

@practice-uffs/todos Todos do programa que quiserem podem participar também, como disse, quanto maior o número de participantes, melhor!

**Comment by MaNegrao** [comment]
https://doodle.com/poll/7yctc8z7ssu6brqa Segue link do doodle

**Comment by MaNegrao** [comment]
Finalizamos duas rodadas muito produtivas de capacitação, creio que estamos no passo para desafogar as demandas de live :D
