### ISSUE TITLE
Seleção de bolsistas de acordo com edital 460/GR/UFFS/2020

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/programa#97]
Acompanhamento do edital:

- [x] responder dúvidas no email
- [x] confirmar recebimento de inscrições
- [x] salvar documentos em pasta do google Drive
- [x] Fazer análise das propostas
- [x] montar lista de classificação da etapa 1
- [x] enviar para publicação edital com classificação da etapa 1
- [x] avaliar e responder recursos da etapa 1
- [x] designar tarefas da etapa 2
- [x] analisar tarefas da etapa 2
- [x] montar lista de classificação da etapa 2
- [x] enviar para publicação edital com classificação da etapa 2
- [x] avaliar e responder recursos da etapa 2
- [x] montar lista de classificação final

**Comment by elisribas** [comment]
Link para edital https://www.uffs.edu.br/atos-normativos/edital/gr/2020-0460

**Comment by Dovyski** [comment]
O prazo para a equipe de gerência classificar todas as propostas para a fase 1 é 12:00 (meio dia) do dia 01/09/2020. O resultado deve ser colocado [nesse documento](https://docs.google.com/document/d/1Vev27ZZVvY6u1GB10s3_bmPYV9oQnhA7teErMfknKi4/edit),  que o @phdmauricio enviará ao @nedilso1 um pouco depois do prazo (meio dia).
