### ISSUE TITLE
Confecção capa de live (Governança Pública nas IFES - 15/12)

### ISSUE THREAD

**Issue by MilenaPaz2020** [practice-uffs/programa#980]
Issue destinada a confecção da capa da live "Palestra de Governança Pública nas IFES - Primeiros Passos: O Caso da UNIFEI (15/12 - 8h30) #887 ".

**Comment by MariaLuizaReviliau** [comment]
A capa será desenvolvida no [figma](https://www.figma.com/file/BV9ASnUC3sPRVoxPQtDLM9/Eventos-%C3%BAnicos?node-id=221%3A2)

**Comment by MilenaPaz2020** [comment]
Como está o andamento desta tarefa?

**Comment by MariaLuizaReviliau** [comment]
Alguém da equipe @practice-uffs/con-design pode fazer a revisão? Tive um pouco de dificuldade em entender qual imagem seria mais ideal para representar o tema da palestra, por isso fiz vários modelos. Se tiver alguma imagem que julguem estar nada a ver, daí eu excluo.

**Comment by TaynaraCh** [comment]
Realizei alguns ajustes nas capas, UNIFEI é uma universidade né? Acredito que as imagens adicionadas de alguma forma refletem a proposta da live, com exceção da opção 2, que ficou muito interessante mas acho que não possui muito sentido, talvez devesse ser descartada.

**Comment by MariaLuizaReviliau** [comment]
solicitante pediu uma alteração, para inverter os títulos de lugar. Já realizei a alteração e atualizei a capa no youtube. Capa está na pasta de saída desta issue.

**Comment by MariaLuizaReviliau** [comment]
posso fechar essa issue?

**Comment by MilenaPaz2020** [comment]
Se a capa estiver aceita pode sim, coloca ela na pasta de entrada da issue da live. obrigada!

**Comment by MilenaPaz2020** [comment]
Aguardando a capa ser movida para #887 para encerrar a issue.

**Comment by MariaLuizaReviliau** [comment]
capa adicionada a pasta de entrada da issue [#887](https://github.com/practice-uffs/programa/issues/887)
